### ISSUE TITLE
Galaxy API V2

### ISSUE THREAD

**Issue by tima** [ansible/galaxy#1007]
### Use Case

Have a clear and standard way of documenting the REST API that Galaxy implements.

### Proposed Solution

Use the OpenAPI spec and Swagger (see below) as many modern applications including Kubernetes and AWX have.

The OpenAPI Specification (formerly Swagger Specification) is an API description format for REST APIs. An OpenAPI file allows you to describe your entire API. Swagger is a set of open-source tools built around the OpenAPI Specification that can help you design, build, document and consume REST APIs.

https://swagger.io/docs/specification/about/
https://medium.com/@dewni.matheesha/automatic-code-generation-from-a-swagger-definition-for-a-rest-api-b2d080cffe09

### Alternatives

Use what is built into Django: http://www.django-rest-framework.org/topics/documenting-your-api/

### Implementation

I want to integrate with Galaxy I need a means of knowing how to integrate with it thru its API and ideally generate a client library to do so.

**Comment by chouseknecht** [comment]
Needs to happen after we upgrade to Django 2, and as part of Galaxy API v2.

We also need to consult with the Tower team, and understand how they document their API, and what their future API plans are so that Galaxy and Tower come together, and provide a consistent user experience.

**Comment by chouseknecht** [comment]
Tentatively adding to the 3.2 milestone. Depending on timing, it may slip to 3.3
