### ISSUE TITLE
rename ansible galaxy organization to match 3.0 naming convention

### ISSUE THREAD

**Issue by tobias-richter** [ansible/galaxy#1012]
Hi,

we are currently working on importing our roles into ansible galaxy from http://github.com/wcm-io-devops.

We already have a namespace: https://galaxy.ansible.com/wcm-io-devops.
This namespace was created before Ansible Galaxy 3.0. 

Since our roles would get "_" instead of "-" during import it would be nice when namespace is following the same naming convetions.

May it be possible to rename the Ansible Galaxy namespace from

"wcm-io-devops" to
"wcm_io_devops"?

I found no option for this in the GUI.

Thank you very much.

**Comment by chouseknecht** [comment]
@tobias-richter 

The namespace is now "wcm_io_devops".

**Comment by tobias-richter** [comment]
Wow, that was fast. Thank you @chouseknecht !
