### ISSUE TITLE
Proposal: API for logging JavaScript Events in Angular

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy#1013]
## Problem

Support for JavaScript event tracking is currently being added in #995. We need to determine how the data from the Galaxy UI will be sent and ingested by the API.

### Data Format
Send the tracking data from the UI to a single API endpoint using the following format:
```
{
  type: 'event_type',
  payload: {
     // Specific attributes for the event type.
  }
}
``` 

Right now we are aiming to support tracking for link and button clicks, which represent two different types and might look like this:

Link data:
```
{
  type: 'link',
  payload: {
    href: "https://www.galaxy.com/davidwittman/redis",
    name: "redis",
    current_page: "/search"
  }
}
``` 

Button data:
```
{
  type: 'button',
  payload: {
    name: "Read Me",
    current_page: "/davidwittman/redis"
  }
}
```

New event types such as page views and errors can be added as needed. 

### Django REST API
The back end would implement an API endpoint at `api/vx/js_event/` that would only accept post requests in the format described above. We would set up the endpoint to triage requests based on the event type, and store the payload data in the database accordingly.

### Securing the API
Exposing a public API for tracking usage metrics is somewhat risky because it opens up the opportunity for people to spam the API to inflate metrics for their content on Galaxy. I would like to do some basic mitigation for this by only accepting requests that have a `User-Agent` HTTP header and a valid CSRF token from Django, while this doesn't really guarantee that people won't spam the API, it adds a few basic roadblocks to prevent that from happening. 

I'm not really sure how to solve this problem and feedback is much appreciated.

### Error Messaging
Since the health of this API endpoint doesn't really affect people's ability to use Galaxy, I would like to set up the endpoint so that it always returns a HTTP 200 return code, regardless of whether or not the data is accepted. Error messages can be surfaced to the dev team for debugging and monitoring via the console. This would also help make it harder for people to spam the endpoint. 

### Sessions for all Users
Right now we only create session variables for users once they log in. It would be nice to be able to attach a session ID to these API calls so that we can group logging data from the same session together. In order to protect people's privacy, the session should not be correlated nor be able to be correlated to any of the user's identifiable attributes (name, username, email etc.) Sessions can be tracked by setting a randomized cookie with a short (15 minute) lifespan that gets renewed each time the browser makes an API request to galaxy.

**Comment by cutwater** [comment]
Can you please describe what problem this proposal is intended to solve? It would be great if you write it in "Problem" paragraph.

**Comment by newswangerd** [comment]
@cutwater We just need an API endpoint that we can use to send UI interactions to. The API endpoint needs to be relatively secure so that people don't just bombard it with fake data. I was hoping to get your feedback on the design of the API endpoint as well as some suggestions regarding how to keep people posting fake data to it.
