### ISSUE TITLE
Logging attempt to galaxy causes http error 500

### ISSUE THREAD

**Issue by KAMI911** [ansible/galaxy#1032]
##### SUMMARY
When I try to login to https://galaxy.ansible.com/login page I got Server Error (500) on link: https://galaxy.ansible.com/accounts/github/login/callback/?code=06179188383d2ce5af7c&state=b5AqN52Iol6j

##### STEPS TO REPRODUCE
Navigate to https://galaxy.ansible.com/login page and login. Other may work it. I have no idea what went wrong. I tried with Firefox, Nightly and Chromium. I am using Linux Mint 19. I Tried to empty cache, delete cookies. 

##### EXPECTED RESULTS
Successful login to Galaxy page.

##### ACTUAL RESULTS
Got Server Error (500) 

##### Communication on errorous page 
Accept 
text/html,application/xhtml+xm…plication/xml;q=0.9,*/*;q=0.8
Accept-Encoding
gzip, deflate, br
Accept-Language
hu-HU,hu;q=0.8,en-US;q=0.5,en;q=0.3
Connection 
keep-alive
Cookie 
****************************
DNT
1
Host   
galaxy.ansible.com
Referer
https://galaxy.ansible.com/login?error=false
Upgrade-Insecure-Requests  
1
User-Agent 
Mozilla/5.0 (X11; Ubuntu; Linu…) Gecko/20100101 Firefox/61.0
 
----------------
 
   
Content-Length 
27
Content-Type   
text/html
Date   
Mon, 06 Aug 2018 17:17:09 GMT
Server 
gunicorn/19.7.1
Set-Cookie 
csrftoken=*********************; Max-Age=31449600; Path=/
Vary   
Cookie
X-Frame-Options
SAMEORIGIN

**Comment by KAMI911** [comment]
I also have same issue with: galaxy-qa.ansible.com

**Comment by chouseknecht** [comment]
@KAMI911 

Removed duplicate Galaxy namespace 'kami911', along with duplicate provider namespace 'kami911'. That should fix the problem. I thought I did this yesterday, but maybe not.

**Comment by KAMI911** [comment]
Thank you it is working now!

**Comment by lalitjoshi29** [comment]
I am having the same issue. 

Unable to login to Galaxy web - Server Error (500)
