### ISSUE TITLE
Namespace Already Exists Error When Adding Provider Namespace

### ISSUE THREAD

**Issue by sgurnick** [ansible/galaxy#1063]
##### SUMMARY
I am the GitHub organization owner of UCLA Library namespace. However, when I sign-in to Galaxy and attempt to add the UCLALibrary namespace provider into my Selected Namespace provider list, I receive the following error message:

```
Error! This provider namespace is already associated with a Galaxy namespace (UCLALibrary) 
```

I discovered there is a UCLALibrary contributor (https://galaxy.ansible.com/UCLALibrary), but for some reason this is not getting mapped to the UCLALibrary namespace available in my namespace list. 

##### STEPS TO REPRODUCE

1. Log-in to Galaxy.
2. Go to My Content in the side bar.
3. In the field where my username (sgurnick) is present, on the far right side of the screen click on the three vertical dots next to the Add Content button.
4. In the menu that pops-up, select Edit Properties.
5. On the Edit Namespace screen, navigate to the Available Namespace list.
6. Click the check-box for UCLALibrary.
7. Visibly see UCLALibrary appear in the Select Provider Namespaces list on the right side of the screen. 
8. Click the Save button.
9. Observe the error message appear at the top of the screen: "Error! This provider namespace is already associated with a Galaxy namespace (UCLALibrary) "

##### EXPECTED RESULTS
I would expect the save function to complete successfully and allow me to contribute content for the UCLALibrary namespace. 

##### ACTUAL RESULTS
The save indicates the error message as mentioned above.

I'm looking for next steps for how to proceed so I can contribute content that is associated with the UCLALibrary namespace.

**Comment by chouseknecht** [comment]
@sgurnick 

You're now an owner of the UCLALibrary namespace on Galaxy. That gives you the ability to maintain some attributes about the namespace as well as add and remove roles. 

Let us know, if you still run into issues. Thanks for reaching out to us!

**Comment by sgurnick** [comment]
Thank you very much for the help on this. I was able to set-up the namespace so our org can contribute to it.
