### ISSUE TITLE
geerlingguy.github-users role needs to be updated to use dash as before

### ISSUE THREAD

**Issue by geerlingguy** [ansible/galaxy#1074]
##### SUMMARY

Going back to #775 — the Ansible Galaxy role [geerlingguy.github-users](https://galaxy.ansible.com/geerlingguy/github-users) should be listed as `geerlingguy.github-users` but is shown as `geerlingguy.github_users`, and so builds are failing due to the incorrect underscore.

(e.g. `ansible-galaxy install geerlingguy.github-users` should work, but does not currently).

##### STEPS TO REPRODUCE

ansible-galaxy install geerlingguy.github-users

##### EXPECTED RESULTS

This role should be installed: https://galaxy.ansible.com/geerlingguy/github-users

##### ACTUAL RESULTS

```
$ ansible-galaxy install geerlingguy.github-users
- downloading role 'github-users', owned by geerlingguy
 [WARNING]: - geerlingguy.github-users was NOT installed successfully: - sorry, geerlingguy.github-users was not found
on https://galaxy.ansible.com.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**Comment by chouseknecht** [comment]
@geerlingguy 

Fixed. Installing with 'github-users' now works:

```
ansible-galaxy install geerlingguy.github-users
- downloading role 'github-users', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-github-users/archive/1.2.0.tar.gz
- extracting geerlingguy.github-users to /Users/chouseknecht/.ansible/roles/geerlingguy.github-users
- geerlingguy.github-users (1.2.0) was installed successfully
```

Found `php_pecl`, and fixed that as well:

```
ansible-galaxy install geerlingguy.php-pecl
- downloading role 'php-pecl', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-php-pecl/archive/1.4.0.tar.gz
- extracting geerlingguy.php-pecl to /Users/chouseknecht/.ansible/roles/geerlingguy.php-pecl
- geerlingguy.php-pecl (1.4.0) was installed successfully
```
