### ISSUE TITLE
Access to namespace gone

### ISSUE THREAD

**Issue by azielke** [ansible/galaxy#1088]
##### SUMMARY
I have the GitHub Organization "clutterbox" and used it to publish roles, but I noticed that i don't have access to the galaxy namespace "clutterbox" anymore - only to my personal namespace.

I've seen similar requests here, so I opened this one.
Could my user be set as owner of the namespace clutterbox?

**Comment by chouseknecht** [comment]
Done. You're now an owner of `clutterbox`.
