### ISSUE TITLE
403 Error on some content detail pages.

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy#1090]
Some repository pages such as https://galaxy.ansible.com/andrewrothstein/ansible-devpi-server fail to load. This particular one tries to pull data from https://galaxy.ansible.com/api/v1/content/12001/, which returns 

```
HTTP 403 Forbidden
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "detail": "You do not have permission to perform this action."
}
```

**Comment by chouseknecht** [comment]
Closing as a duplicate of #810
