### ISSUE TITLE
Unable to login to Galaxy web - Server Error (500)

### ISSUE THREAD

**Issue by VerosK** [ansible/galaxy#1102]
##### SUMMARY
I'm trying to login to Ansible Galaxy web via https://galaxy.ansible.com/login .    After clicking to GitHub icon, I receive **Server Error (500)**  . Seems related to already solved #1032 

I tried already tried to clean my cookies and revoke Authorization to Galaxy on GitHub but no change happened.

My Github account is `verosk`, I'm using `VerosK` as author name on Galaxy.  

##### STEPS TO REPRODUCE
1. Login to GitHub
2. Visit *Login* page on Ansible Galaxy web.
3. Click Github icon. 

##### EXPECTED RESULTS
I should be redirected back to Ansible Galaxy web.

##### ACTUAL RESULTS
Got page https://galaxy.ansible.com/accounts/github/login/callback/?code=xxxx&state=xxxx with

**Server Error (500)**

**Comment by chouseknecht** [comment]
@VerosK 

There were 2 namespaces in Galaxy - *verosk* and *VerosK*. All of your roles seem to exist under *VerosK*, so went ahead and removed the *verosk* namespace.

I think this should fix the 500 error.

**Comment by VerosK** [comment]
Fixed. Thank you.

**Comment by pontikis** [comment]
Hello! 
I have exactly the same problem. I cannot sign up... Could you please check it for my Github account (pontikis)? Thanks!

**Comment by fvigo** [comment]
Same problem here, with my github account (fvigo). Thanks!
