### ISSUE TITLE
Can't register a role under my organization

### ISSUE THREAD

**Issue by gustavomcarmo** [ansible/galaxy#1103]
I don't know if I'm missing something but I'm not able to register a role imported from my organization repo in GitHub with the name of my organization. Galaxy insists in registering the role under my namespace (gustavomcarmo) but what I want is registering it under my organization (codeyourinfra). How can I do that?

This issue is the same as reported in: https://stackoverflow.com/questions/51246177/how-to-publish-ansible-galaxy-role-in-my-organization-name

**Comment by tolland** [comment]
Yep. I have the same problem. All my roles are under my org account `limepepper`, but my github login is `tolland`. So the roles in galaxy are mis-named compared to what I have deployed...

**Comment by chouseknecht** [comment]
@tolland

There's now a *limepepper* namespace in Galaxy, and you are the owner. Log into Galaxy, click on My Content, and edit the *limepepper* namespace. Add the *limepepper* provider namespace, and update any other attributes. From there, you should be able to add your role repositories.

**Comment by chouseknecht** [comment]
@gustavomcarmo 

There is now a *codeyourinfra* namespace in Galaxy, and you are the owner. Log into Galaxy, click on My Content, and edit the *codeyourinfra* namespace. Add the *codeyourinfra* provider namespace, and update any other attributes. From there, you should be able to add your role repositories.

**Comment by chouseknecht** [comment]
I assume heart emojis means everyone is happy, and this issue can be closed. Thank you @gustavomcarmo  and @tolland for reaching out to us. If there's anything else you need help with, please let us know.

Thanks!

**Comment by gustavomcarmo** [comment]
@chouseknecht it's ok for me you closing this issue, but wouldn't it be a kind of bug which should be fixed?

**Comment by bittner** [comment]
Hi @chouseknecht, I'm looking for registering a role under the _painless_ namespace for the @painless-software organization of my GitHub account.

The reason for not matching the org name is that I'm not sure whether having a hyphen in a role namespace is a good idea, and I also use _painless_ on [Docker Hub](https://hub.docker.com/u/painless/dashboard/) as a namespace. Can you make this happen?

Note that @painless is already an (inactive) GitHub user. Just to point out some potential conflict.

**Comment by bittner** [comment]
@chouseknecht Any chance I get help with my need for an organization on Galaxy?
