### ISSUE TITLE
No namespace after log in

### ISSUE THREAD

**Issue by sebbrousse** [ansible/galaxy#1108]
I try to log in and nothing appeared into "My content". 

NB : When I search into "Community", I can find a sebbrousse but it is an old trial account from several years ago. May be this old account make some trouble into the process. Could you repair/delete the old account so I can use the galaxy, please ?

**Comment by chouseknecht** [comment]
Delete the existing *sebbrousse* namespace, and created a new one with your username as the owner. Hopefully that fixes things. When you go to My Content, you should see the *sebbrousse* namespace. Edit, and associate your GitHub provider namespaces with it. Update any attributes, and save. From there, you should be able to add your role repositories.

**Comment by sebbrousse** [comment]
It is fixed and everything works perfectly. Thx a lot !
