### ISSUE TITLE
Unable to login to Galaxy web - Server Error (500)

### ISSUE THREAD

**Issue by bdp** [ansible/galaxy#1122]
##### SUMMARY
I'm trying to login to Ansible Galaxy web via https://galaxy.ansible.com/login .
It only offers GitHub login, and appears to be no way to complete a plain user:pass login.
After clicking to GitHub icon, I receive Server Error (500) . Seems related to already solved #1032 and #1102 

I've deleted cookies.
I've revoked Authorization to Galaxy from GitHub.
I've attempted all the same in Chrome & Firefox, and in incognito modes.
I've been unable to self-solve this issue.

##### STEPS TO REPRODUCE
Login to GitHub
Visit Login page on Ansible Galaxy web.
Click Github icon.

##### EXPECTED RESULTS
Successful login.
##### ACTUAL RESULTS
500 error

**Comment by chouseknecht** [comment]
@bdp 

I assume you attempted to log into Galaxy using the *bdp* GitHub username. The problem seems to be with Django Allauth, but I'm not completely sure what the issue is. Can you share the email address associated with your account on GitHub?

**Comment by bdp** [comment]
@chouseknecht same email as existing account in Galaxy. I've email you directly via address on your Github profile to also verify this email address.

**Comment by chouseknecht** [comment]
@bdp 

Found your account in Galaxy based on email address. It was originally created via Google OAuth. Not sure if that's the issue, but seems like it, so I deleted it. Please attempt to log in again.

Thanks!

**Comment by bdp** [comment]
@chouseknecht, thank you. All fixed now.

**Comment by j-dexx** [comment]
Hi,

I'm having the same issue.  Any ideas?

**Comment by huertico** [comment]
Hello

I'm having the same issue. Any ideas?
