### ISSUE TITLE
Playbook works for one cisco switch but not working on other device

### ISSUE THREAD

**Issue by rinoalpha0** [ansible/galaxy#1127]
##### SUMMARY -- Example of playbook --
- hosts: AMB
  name: Save Configurations (IOS)
  connection: local
  tasks:
    - ios_command:
        commands: show run
      register: config
    - debug:
        msg: "{{ config.stdout[0] }}"
    - copy:
        content: "{{ config.stdout[0] }}"
        dest: "/etc/ansible/backups/AMB/{{ inventory_hostname }}.txt"

##### STEPS TO REPRODUCE
Works only with one Cisco 3850, but not working for other Cisco 3850 switch.

post debuging found . "
    },
    "stdout": [
            },
    "stdout": [
        "None"
    ],
    "stdout_lines": [
        [
            "None"
        ]
    ]
}

TASK [debug] ******************************************************************************************************
task path: /etc/ansible/jvplaybook/sh_run.yml:134
ok: [172.18.254.1] => {
    "msg": "None"

    ],
    "stdout_lines": [
        [
            "None"
        ]
    ]
}

TASK [debug] ******************************************************************************************************
task path: /etc/ansible/jvplaybook/sh_run.yml:134
ok: [172.18.254.1] => {
    "msg": "None"

##### EXPECTED RESULTS
Sh run output should get saved as .txt
##### ACTUAL RESULTS
nothing is getting saved in .txt, As "stdout":  output show none
```

```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This issue should be filed on https://github.com/ansible/ansible/issues

Should you still wish to discuss things further, or if you disagree with our thought process, please stop by one of our two mailing lists:

  * https://groups.google.com/forum/#!forum/ansible-project
  * https://groups.google.com/forum/#!forum/ansible-devel

We'd be happy to discuss things.

Thank you once again!
