### ISSUE TITLE
namespace for GitHub organization

### ISSUE THREAD

**Issue by sbaerlocher** [ansible/galaxy#1145]
##### SUMMARY
For my employer I opened a GitHub organization `itigoag` and used it to publish Windows roles.

I don't find any options to open namespaces in the Ansible Galaxy. Can anyone help me?

**Comment by Fryguy** [comment]
I am also having the same issue...how do I create a namespace from an org (I am an owner of the ManageIQ github org)?

**Comment by chouseknecht** [comment]
@Fryguy 

There's now a [manageiq](https://galaxy.ansible.com/manageiq) namespace, and you're the owner.

**Comment by chouseknecht** [comment]
Assuming this can be closed, since requested namespaces were created. If more help is needed, please let us know.

Thanks @Fryguy and @sbaerlocher for reaching out to us!

**Comment by vide** [comment]
@chouseknecht can you please also create a Galaxy namespace for [StuartApp](https://github.com/StuartApp) please? I'd like to publish a role not under my personal account

**Comment by NickUfer** [comment]
@chouseknecht can you please create the galaxy namespace `inwx` for me too? I want to publish a collection for the company I work for. Thanks :+1:

**Comment by vide** [comment]
@NickUfer we had more luck opening a dedicated ticket (basically my comment here was ignored)

**Comment by NickUfer** [comment]
@vide thanks for the info, going to do that instead :+1:
