### ISSUE TITLE
Can't Log Into Galaxy on Mobile

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#1148]
Known issue, and not straightforward to fix. When the screen size is small, and the left nav is replaced by the drop-down menu, the drop-down menu contains no login option.

**Comment by gundalow** [comment]
One idea could be to get rid of horizontal navigation bar and move everything to the left vertical menu

**Currently**

- Home
- Search
- Community
- (My Content) # only shown when signed in
- (My Imports) # only shown when signed in

**Possibility**
- Home
- Search
- Community
- (My Content) # only shown when signed in
- (My Imports) # only shown when signed in
- About
- Help
- Documentation
- Login/out
