### ISSUE TITLE
Kovarus namespace addition

### ISSUE THREAD

**Issue by as0bu** [ansible/galaxy#1159]
I'm needing a galaxy namespace created called "kovarus", the name of the company I work for and attached to my galaxy user.

Is that possible to do?

**Comment by chouseknecht** [comment]
@as0bu 

Thanks for reaching out! 

You now have [kovarus](https://galaxy.ansible.com/kovarus).

**Comment by as0bu** [comment]
@chambridge Thanks for doing that!

How would I go about changing some of the information on the profile such as profile picture, etc?

Thanks again!
