### ISSUE TITLE
Repository description not updating

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#1165]
##### SUMMARY
It appears we set the Repository object description during creation, but then never update it during subsequent content imports. The initial value is set to the GitHub repository description, and then remains frozen, despite modifying the repo description on GitHub and modifying the description value in `meta/main.yml`.

##### STEPS TO REPRODUCE
GitHub repo description change:
- Add a new Repository
- See Repository created
- Modify the repository description on GitHub
- Import the Repository on Galaxy
- See no change has occurred to the description on Galaxy

Metadata description change:
- Modify the description in `meta/main.yml`, and push the change to GitHub
- Import the Repository on Galaxy
- See that no change has occurred to the Repository description on Galaxy

##### EXPECTED RESULTS
Since we're working on not being tightly coupled to GitHub, we should update the Repository description with the value found in the Collection metadata. So for a traditional role, modifying `meta/main.yml` should result in a change to the Repository objects's description value.

##### ACTUAL RESULTS
No way to update the Repository object description.

**Comment by abenokraitis** [comment]
CC: @privateip

**Comment by abenokraitis** [comment]
CC: @rcarrillocruz

**Comment by chouseknecht** [comment]
@abenokraitis 

Working on a fix for this now. Will get it into production ASAP. In the meantime, if you want us to, we can go through and update ansible-network repos with the current GitHub descr. Just give me the nod to do so.

**Comment by abenokraitis** [comment]
Awesome, thanks @chouseknecht ! Based on feedback from @privateip all the text should be updated. Here are the entries that probably need to be manually updated:

https://galaxy.ansible.com/ansible-network/aws
https://galaxy.ansible.com/ansible-network/azure
https://galaxy.ansible.com/ansible-network/openstack
https://galaxy.ansible.com/ansible-network/rhel

**Comment by chouseknecht** [comment]
@abenokraitis 

As requested, manually updated the aws, azure, openstack, and rhel roles with a description value matching the GitHub repository description.

Going forward, please make sure the correct description is set in the `meta/main.yml` file. The next time any of these roles are imported, the description will be set to the metadata value.
