### ISSUE TITLE
Github avatar icon cut off in certain modes in Ansible Galaxy Web UI

### ISSUE THREAD

**Issue by IPvSean** [ansible/galaxy#1170]
##### SUMMARY
When you have the page over a certain width the icon gets cut off slightly (like 5px or so worth are cut off).

##### STEPS TO REPRODUCE
Go to https://galaxy.ansible.com/ansible-network/arista_eos and look at the Red Ansible logo.  Make the page as thin as you can, the logo will show clearly as a circle.  When you make the webpage as wide as you can there will be a line like `|`, and the Ansible logo will be cut off not making a full circle.

##### EXPECTED RESULTS
No cut off logo

##### ACTUAL RESULTS
Let me know if you need screen shots, I can provide them if this is not easily apparent.

**Comment by jawyoonis** [comment]
I am working on this issue #1170
