### ISSUE TITLE
Problem with namespace after changing GitHub username

### ISSUE THREAD

**Issue by macunha1** [ansible/galaxy#1172]
Did some Googling (and procrastination) about reflecting changes in my GitHub username at Ansible Galaxy. 
About 6 months before I changed my GitHub username, now I'm trying to add the new Namespace to my Galaxy Account at "My Content" (with the old name: matheuscunha) and seeing the following: "Error! This provider namespace is already associated with a Galaxy namespace (macunha1) ".
Also, when I try to import roles at "My Imports", it shows me: Permission Denied.

AFAIK, the only way to fix it, is asking here. Could you please change my Ansible Galaxy namespace to `macunha1`?

Maybe related to #309 and #310

**Comment by chouseknecht** [comment]
@macunha1 

Thanks for reaching out for help. I think I managed to rename your namespace to 'macunha1'.

**Comment by macunha1** [comment]
Thanks a lot for your fast answer and straightforward solution
