### ISSUE TITLE
Namespace for GitHub organization

### ISSUE THREAD

**Issue by ezhivitsa** [ansible/galaxy#1175]
##### SUMMARY

I'm the owner of the organization `auxilincom` on Github, also I have an account `ezhivitsa` on ansible galaxy. Is it possible to create namespace `auxilin` or `auxilincom` in order to upload roles from my organization?
Thanks.

**Comment by chouseknecht** [comment]
Thanks for reaching out to us! Namespace `auxilincom` created, and `ezhivitsa` is the owner. Let us know, if you need any additional help.
