### ISSUE TITLE
Typo on website

### ISSUE THREAD

**Issue by davewujcik** [ansible/galaxy#1186]
"galaxy_tags
Optional. Provide a list of tags. A tag is a single **world** that helps categorize your role. You can invent tags, or guess at tags other might be using to describe similar roles, but why do that, when you can see what others are using by browsing existing tags here."

From: https://galaxy.ansible.com/docs/contributing/creating_role.html

"world" should be "word"

-- Dave

**Comment by newswangerd** [comment]
Thanks for the spot @davewujcik
