### ISSUE TITLE
Improve PEP8 compliance

### ISSUE THREAD

**Issue by cutwater** [ansible/galaxy#122]
All ignored flake8 checks specified in `tox.ini` file should be removed and appropriate warnings fixed.

Warnings:

- [x] E221 - Multiple spaces after operator
- [x] E231 - Missing whitespace after ','
- [x] E241 - Multiple spaces after ','
- [x] E251 - Unexpected spaces around keyword / parameter equals
- [x] E501 - Line too long
- [x] E722 - Do not use bare except
- [x] E731 - Prefer def over lambda

**Comment by akaRem** [comment]
It looks like this issue is related to `setup.cfg` instead of `tox.ini`

**Comment by cutwater** [comment]
@akaRem the issue related to `setup.cfg` and `tox.ini` has been addressed already.
I'm not closing this issue, because we're still ignoring `E501 - line too ling` lint warning.
Line length warnings were fixed only partially.

**Comment by akaRem** [comment]
@cutwater Yep, just mentioned for next visitors of this issue.
It looks like tox.ini was deprecated in favour of setup.cfg and does not exists any more.
