### ISSUE TITLE
create namespace for my organisation

### ISSUE THREAD

**Issue by scuben** [ansible/galaxy#1221]
I would like to publish my roles under the namespace of my company, not myself. Hence I would need a new namespace "ARTACK" (or "artack") beside my own namespace "scuben".

**Comment by chouseknecht** [comment]
@scuben 

Namespace 'artack' created, and you are the proud owner. You'll need to go to My Content, edit the namespace, and add the GitHub namespaces (i.e. usernames and/or organizations) from which content will be imported. From there, you should be able to use the Add Content feature to import your roles.

Please let us know, if you run into any problems.
