### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by AlekKras** [ansible/galaxy#1237]
## Security Issue

There is a security issue with the repo. 
Vulnerable module: `PyYAML`
Introduced through: `ansible@2.7.0 and ansible-lint@3.5.0`

- Introduced through: `ansible/galaxy@ansible/galaxy#b0ac4e8d38e27bc5af47e4e902d710ab9d12b587 › ansible@2.7.0 › PyYAML@3.13`

- Introduced through: `ansible/galaxy@ansible/galaxy#b0ac4e8d38e27bc5af47e4e902d710ab9d12b587 › ansible-lint@3.5.0 › ansible@2.7.0 › PyYAML@3.13`

Affected versions of this package are vulnerable to Arbitrary Code Execution due to using the insecure `yaml.load()` function.

**Comment by chouseknecht** [comment]
@AlekKras 

Thanks for looking into this. 

Not seeing a reference to PyYaml in commit [b0ac4e8d38e27bc5af47e4e902d710ab9d12b587](b0ac4e8d38e27bc5af47e4e902d710ab9d12b587). We do use PyYaml, and I think we're always using `yaml.safe_load()`, as [seen here in the Galaxy code](https://github.com/ansible/galaxy/blob/8e0bc2e6fa4040f68f7c976df1ebc1351c359837/galaxy/importer/utils/ast.py#L39).

As far as the reference to Ansible Lint, the issue will need to be addressed in that project. I'll take a look, and see if `yaml.safe_load()` is not being used, and file an issue.

**Comment by chouseknecht** [comment]
Looks like ansible-lint uses `yaml.load()', [see reference here](https://github.com/willthames/ansible-lint/blob/651d92608cb2aa282567f5cd168c04a44bfc2953/lib/ansiblelint/__main__.py#L44)

**Comment by chouseknecht** [comment]
Add issue to Ansible Lint: https://github.com/willthames/ansible-lint/issues/382

**Comment by awcrosby** [comment]
Ansible Lint has now been patched for this
