### ISSUE TITLE
Ansible Galaxy does not align renamed GitHub User Name

### ISSUE THREAD

**Issue by uniQconsulting** [ansible/galaxy#1238]
Hi Galaxy Admins
We exactly run into the same issue like:
#309, #310 & #1172

GitHub before: uQcGitHub
GitHub now: uniQconsulting
Everything in GitHub looks fine, but imported roles and ansible galaxy user remain to old names.
Is there a way we can trigger a update to align the Galaxy user to the GitHub user?
Or could you please run it manually like you did for @drew-kun.
Thanks
Chris

**Comment by chouseknecht** [comment]
@uniQconsulting 

I updated the name from `uQcGitHub` to `uniQconsulting`. That seems like it takes care of the issue, so closing. Let us know, if you still need help. Thanks for reaching out!

**Comment by uniQconsulting** [comment]
Hi @chouseknecht 
Thanks for the fast response.
Import is now working as expected, but it looks like it only partially updated.
Name on the top right corner is still the old one.
I added screenshot to show up.

thanks
chris
![ansible_galaxy_20181024-164018](https://user-images.githubusercontent.com/43484153/47439065-fdaaaa80-d7ab-11e8-8f06-5d8a531ad6f1.png)
