### ISSUE TITLE
Quality Score + Community Score

### ISSUE THREAD

**Issue by awcrosby** [ansible/galaxy#1242]
1. On the Search and Community pages we use the term “Score” which is the average of the Quality and Community Score if both exist, if just one exists it displays that score number, if neither exist the term “Score” is not displayed. - We may have a minor bug where the Community pages is not averaging but just looking at quality.

2. The Content Details page shows the following “hierarchy” for scoring:
- Content Score (a UI widget without a number)
  - Quality Score
    - ~~Content Score~~ Syntax Score
    - Metadata Score
  - Community Score

~~We use the term “Content Score” twice. @tima do you want to see any change here?~~

![content_details_scores](https://user-images.githubusercontent.com/4432895/47433018-89e9ad00-d76d-11e8-8035-0b254b18180f.png)

**Comment by tima** [comment]
@awcrosby 1 sounds good other than the bug. I see your point on 2 and ideally that shouldn't remain but I'm not sure what to change it to either. I think the top level use is the more important one where "content" should remain. If we go with that, what does the other become? Syntax? Drawing a blank right now and need to think about it.
