### ISSUE TITLE
Create a namespace for organization

### ISSUE THREAD

**Issue by qmfrederik** [ansible/galaxy#1315]
Can I ask you to create a new namespace for organization "quamotion" and to assign me as an owner?

Thank you!

**Comment by newswangerd** [comment]
Hi @qmfrederik 
Apologies for the delay. I added the new namespace: https://galaxy.ansible.com/quamotion
Before you can start using it you need to log in and add quamtion as a provider namespace to the new namespace. You can do this by going to "My Content" and selecting "Edit Properties" from the dropdown.

If your org doesn't show up under the list of provider namespaces you need to grant third party access to Ansible Galaxy on your organization. You can do this by going to https://github.com/settings/connections/applications/3e92491593df34c92089 and granting access for your org.

**Comment by qmfrederik** [comment]
Awesome, thanks!
