### ISSUE TITLE
Create new namespace for organisation

### ISSUE THREAD

**Issue by tobias-richter** [ansible/galaxy#1316]
I tried to do this myself using the ansible galaxy web ui and triggering a notification using travis but it seems that i need your help for this.

Can you please create a new namespace "pro_vision", link it to https://github.com/pro-vision and add me as an owner?

Thank you!

**Comment by tobias-richter** [comment]
@chouseknecht sorry for bothering you directly, but is there any chance that one of the team can take care of this (and when already in the admin ui also this https://github.com/ansible/galaxy/issues/1315?)

**Comment by newswangerd** [comment]
Hi @tobias-richter 

Apologies for the delay. I added the new namespace: https://galaxy.ansible.com/pro_vision

Before you can start using it you need to log in and add https://github.com/pro-vision as a provider namespace to the new namespace. You can do this by going to "My Content" and selecting "Edit Properties" from the dropdown.

If your org doesn't show up under the list of provider namespaces you need to grant third party access to Ansible Galaxy on your organization. You can do this by going to https://github.com/settings/connections/applications/3e92491593df34c92089 and granting access for your org.

**Comment by tobias-richter** [comment]
Thanks @newswangerd!
