### ISSUE TITLE
Travis badge not working for roles imported from travis-ci.com

### ISSUE THREAD

**Issue by Bassinator** [ansible/galaxy#1352]
##### SUMMARY
For all my roles imported from travis-ci.com the build status is shown unknown.

The link of the badge is pointing to travis-ci.org. I guess that's the reason for this issue.

##### STEPS TO REPRODUCE
Import ansible role and notify from travis-ci.com

##### EXPECTED RESULTS
correct badge with actual build result is shown

##### ACTUAL RESULTS
build status unknown

```

```

**Comment by chouseknecht** [comment]
@newswangerd 

I suspect we're hardcoding the badge link in the API to `travis-ci.org`.

**Comment by Bassinator** [comment]
If you want to keep these hard coded. I would suggest to stick it to travis-ci.com because all builds on travis-ci.org will be migrated to travis-ci.org.

**Comment by newswangerd** [comment]
@Bassinator the fix for this problem should be going into production sometime tomorrow.

**Comment by Bassinator** [comment]
I can confirm, that this is fixe. Build state is indicated with the correct badge after the next run on travis.
