### ISSUE TITLE
Unable to add namespace

### ISSUE THREAD

**Issue by cognifloyd** [ansible/galaxy#1353]
##### SUMMARY
I have two namespaces under my account (@cognifloyd and @theatro-noc), and I would like to add a third: @theatro.
I can't find a way to add a namespace for a new organization in the galaxy UI.
I have validated that galaxy is allowed in github permissions for the org.

I can add an org to an existing namespace, but I can't add another namespace. I also tried notifying galaxy from a successful travis build, but that also did not add the role or the org.

##### STEPS TO REPRODUCE
look for button/link to add a namespace in the galaxy UI

##### EXPECTED RESULTS
Find button. Click. Add namespace

##### ACTUAL RESULTS
No way to add a namespace.

**Comment by chouseknecht** [comment]
@cognifloyd 

`theatro` has been created, and you are the owner.

**Comment by cognifloyd** [comment]
@chouseknecht Thank you! So, is there a way to add a namespace and I just missed it?
