### ISSUE TITLE
Please add 10.13 and 10.14 to MacOSX platform

### ISSUE THREAD

**Issue by elliotweiser** [ansible/galaxy#1356]
##### SUMMARY

Please add items `10.13` (for High Sierra) and `10.14` (for Mojave) versions of the `MacOSX` platform. Unfortunately, there are some duplicate platform names similar to `MacOSX` and I believe this has made declaring these a little confusing for other MacOSX role developers as well (see comments in #654). In the future, that should be cleaned up/standardized to reduce confusion amongst developers and to prevent you from duplicating work.

The ability to declare these versions in `meta/main.yml` will tell users of Ansible Galaxy that certain roles are actively supported with the latest versions of `MacOSX`. Thanks!

**Comment by cutwater** [comment]
Done

**Comment by elliotweiser** [comment]
Thanks!
