### ISSUE TITLE
Cannot log in 

### ISSUE THREAD

**Issue by r-darwish** [ansible/galaxy#1360]
##### SUMMARY
I am unable to log in to galaxy.ansible.com

##### STEPS TO REPRODUCE
1. Click on login
2. The only option is to click on a Github icon - click it
3. Sometimes I get a page saying "An error occurred while attempting to login via your social network account."
4. Other times a get a page saying "You are about to use your GitHub account to login to galaxy.ansible.com. As a final step, please complete the following form:". From there I can either click "Sign up" or "Sign in"
5. If I click "Sign up" and fill in my username and email I get these two messages:
* `An account already exists with this e-mail address. Please sign in to that account first, then connect your GitHub account.`
* `%(model_name)s with this %(field_label)s already exists.`
6. If I click Sign In and fill in my username (which is r-darwish) and password I'm redirected to a page that says `Server Error (500)`

##### EXPECTED RESULTS
I should be able to log in

##### ACTUAL RESULTS
Explained above

```

```

**Comment by leafnode** [comment]
Same here

**Comment by chouseknecht** [comment]
@r-darwish 

Removed the existing Galaxy account for your username. Can you please attempt to login again, and let us know what happens.

**Comment by chouseknecht** [comment]
@leafnode 

Removed the existing Galaxy account for your username. Please try logging in again. It should create the GitHub social account this time.

**Comment by leafnode** [comment]
Worked out for me! Stumbled upon some other issues though - the roles from my organization (`iroquoisorg`) were imported under other co-owner name, I can't access them now, can't add as a separate namespace and so on. I probably should open another issue for that...

**Comment by chouseknecht** [comment]
@leafnode 

The content for your org should probably be imported as `iroquoisorg` in Galaxy. We can create an `iroquoisorg` Namespace in Galaxy, and set you as the owner. Should we do that?

**Comment by leafnode** [comment]
@chouseknecht if you could be so kind...

**Comment by chouseknecht** [comment]
@leafnode 

Fixed the association.

**Comment by r-darwish** [comment]
Seems to work now. Thanks.

**Comment by chouseknecht** [comment]
The authentication problems seem to be resolved. Closing.

Thanks for reaching out to us!
