### ISSUE TITLE
Warning: Invalid platform: "Fedora-29", skipping.

### ISSUE THREAD

**Issue by sourcejedi** [ansible/galaxy#1388]
Same issue as #494, except for Fedora-29. Fedora 29 has been released for a little while now :-).  Can you add it to the list please?

https://fedoramagazine.org/announcing-fedora-29/

(Yes, I am a sucker for stuff like the yellow warning triangles on my Ansible roles :-).

**Comment by chouseknecht** [comment]
New platform added. You can view it here" https://galaxy.ansible.com/api/v1/platforms/?name=Fedora&release=29
