### ISSUE TITLE
Severity: High: Role info should contain company 

### ISSUE THREAD

**Issue by sourcejedi** [ansible/galaxy#1389]
##### SUMMARY
Specifying a company in `meta/main.yml` is [documented](https://galaxy.ansible.com/docs/contributing/creating_role.html) as optional.  But, Galaxy treats the absence of a company as "severity: high".  I do not have a legal company.

If Galaxy requires contributors to have a company, the documentation needs to be fixed, and this requirement needs to be made very clear in advance.

##### STEPS TO REPRODUCE
Clone my git repo & import it on your Ansible Galaxy account.  Notice the score, view the role page on ansible galaxy, and click details to view the score breakdown.

Git repo: https://github.com/sourcejedi/ansible-rpmfusion__impl

##### EXPECTED RESULTS
Company is not required

##### ACTUAL RESULTS

> Metadata Score:
> 4.3
> Warnings: 2
> 
>    1 [Severity: High]
>    E701:
>    <b>Role info should contain company</b>
>    1 [Severity: Medium]
>    IMPORTER101:
>    Invalid platform: "Fedora-29", skipping. 
> 

![screenshot from 2018-12-03 11-19-40](https://user-images.githubusercontent.com/14057/49370884-77a84a80-f6ed-11e8-8c81-7fb319f9cc22.png)

**Comment by awcrosby** [comment]
@sourcejedi `company` was removed as a required field in the metadata. If you reimport your role, the scoring will run and it will not be listed as a warning. Thanks for flagging this!
