### ISSUE TITLE
Add new contributor to f5devcentral namespace

### ISSUE THREAD

**Issue by caphrim007** [ansible/galaxy#1393]
I am the current maintainer of this namespace, but I'd like to add @wojtek0806 to it as well.

**Comment by caphrim007** [comment]
You can also add them to the F5Networks namespace

**Comment by chouseknecht** [comment]
Owner @wojtek0806 added to `f5devcentral` and `F5Networks`. 

As an owner of a Namespace in Galaxy, you can select Edit Properties from the dropdown menu, and add additional owners. If you didn't notice it, on My Content, all the way to the right for each Namespace there is a little *kabob* symbol. Click that, and you'll see the menu.
