### ISSUE TITLE
Warning: Invalid platform: "Ubuntu-cosmic", skipping.

### ISSUE THREAD

**Issue by timorunge** [ansible/galaxy#1397]
Same issue as #494 and #1388. Ubuntu Cosmic (18.10, http://releases.ubuntu.com/18.10/) has been released around 1,5 months ago. Can you add it to the list please (I was not able to find the definition, otherwise I would also have created a PR :))

**Comment by chouseknecht** [comment]
New platform added to the database. You can view it here: https://galaxy.ansible.com/api/v1/platforms/?name=Ubuntu&release=cosmic
