### ISSUE TITLE
Support request: Please add a Galaxy namespace for my organisation @dcos

### ISSUE THREAD

**Issue by MrMarvin** [ansible/galaxy#1398]
##### SUMMARY
I have a single personal namespaces under my account (@MrMarvin), and I would like to add a shared second one for my organisation: @dcos.
I can't find a way to add a namespace for a new organization in the galaxy UI.
I have validated that galaxy is allowed in github permissions for the org via my personal Github connection. We do plan to add multiple people as admins to this new namespace.

##### STEPS TO REPRODUCE
look for button/link to add a namespace in the galaxy UI

##### EXPECTED RESULTS
Find button. Click. Add namespace

##### ACTUAL RESULTS
No way to add a namespace.
Copying the prior #1353, this seems to be the way of handling this feature right now. Or has there been changes to the process recently that would allow me to add a namespace myself?

**Comment by chouseknecht** [comment]
Namespace `dcos` created with owner @MrMarvin.

On My Content, you'll need to edit the namespace ,and under *Provider Namespaces*, add any GitHub Organizations containing repositories to be imported.
