### ISSUE TITLE
UI: Partially visible drop-down menu on "My Imports” page

### ISSUE THREAD

**Issue by kbugaienko** [ansible/galaxy#1409]
##### STEPS TO REPRODUCE
1. Select “My Imports”.
2. Click on “Clear all filters”.
3. Scroll down of the page.
4. Click on dropdown-menu to select amount items per page.

##### EXPECTED RESULTS
All drop-down menu items are visible.

##### ACTUAL RESULTS
Last drop-down menu items are hidden by the bottom of the page.

![screen shot 2018-12-10 at 13 57 54](https://user-images.githubusercontent.com/3986911/49735060-6d0a2a00-fc86-11e8-9b72-2e82037309b9.jpg)

**Comment by newswangerd** [comment]
This got fixed as part of the rewrite of this page for 3.2
