### ISSUE TITLE
Create new namespace for organisation

### ISSUE THREAD

**Issue by bittner** [ansible/galaxy#1414]
Can I ask you to create a new namespace for organization "painless" and to assign me as an owner?

Background
-----------

I'm looking for registering a role under the _painless_ namespace for the @painless-software organization of my GitHub account.

The reason for not matching the org name is that I'm not sure whether having a hyphen in a role namespace is a good idea, and I also use _painless_ on [Docker Hub](https://hub.docker.com/u/painless/) as a namespace. Can you make this happen?

Note that @painless is already an (inactive) GitHub user. Just to point out some potential conflict.

Obsoletes: https://github.com/ansible/galaxy/issues/1103#issuecomment-421541748

**Comment by chouseknecht** [comment]
@bittner 

Done. Namespace `painless` now exists with you as the owner. You can modify it, and add content using the My Imports page.

Thanks for reaching out to us. Please let us know, if you run into any problems with the new namespace.
