### ISSUE TITLE
Access to namespace

### ISSUE THREAD

**Issue by fbatschi** [ansible/galaxy#1421]
I am owner of Github organization `bytepark` and used to updated roles in the namespace `bytepark` on Galaxy. The access in Galaxy seems to be gone. 

I can select `bytepark` as Provider Namespace in my account, but receive the error `Error! This provider namespace is already associated with a Galaxy namespace (bytepark)`

Would you be so kind as to add the access again?

**Comment by chouseknecht** [comment]
@fbatschi 

You are now an owner of the `bytepark` namespace.
