### ISSUE TITLE
The Required Github Access Is a Vast Transgression

### ISSUE THREAD

**Issue by muellert** [ansible/galaxy#1424]
##### SUMMARY

I wanted to open a Galaxy account because I wanted to publish a role that I have written for Ansible.
When I reviewed the access that Galaxy wants on my Github account, I found that Galaxy wants way too much control over my account, and even read-write access to everything.

##### STEPS TO REPRODUCE

1. Open a Github account.
2. Go to galaxy.ansible.com and click "log in" using that github account.
3. Review the rights Galaxy is asking for.
4. Decline.

##### EXPECTED RESULTS

I expected that Galaxy would want read-only access to the repository containing the role ONLY.

##### ACTUAL RESULTS

Galaxy asks to pwn my Github account.

```

```

**Comment by chouseknecht** [comment]
@muellert 

Thanks for reaching out to us and sharing your concern.

When interacting with the GitHub API, Galaxy requests the `public_repo` scope. Here's the settings we use: https://github.com/ansible/galaxy/blob/devel/galaxy/settings/default.py#L262

The `public_repo` scope grants Galaxy the following:

```
Grants read/write access to code, commit statuses, collaborators, and deployment statuses for public repositories and organizations. Also required for starring public repositories.
```

I don't see a way to request read-only access to public repositories. Here are the available scopes: https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes

There is a `repo:status` scope, but that would give Galaxy access to view both public and private repositories, which seems worse than `public_repo` IMHO.

**Comment by chouseknecht** [comment]
@cutwater pointed out that Galaxy may actually no longer need the `public_repo` scope. We used to allow users to star and watch a repository from Galaxy by clicking a button. This required updating the repository; however, we're no longer offering that feature.

We'll do some testing, and if possible, eliminate the scope.

**Comment by chouseknecht** [comment]
@muellert removing the `public_repo` scope from our [QA environment](https://galaxy-qa.ansible.com).

**Comment by cutwater** [comment]
@muellert Fix for this issue was released today. Please try to sign up again.
