### ISSUE TITLE
Request for new namespace "inoxio"

### ISSUE THREAD

**Issue by MichaelKunze** [ansible/galaxy#1425]
Not sure if it's appropriate but could you please create a new namespace called "inoxio" in galaxy for me?

- org: https://github.com/inoxio
- owner: @michaelkunze

Thank you very much!

**Comment by chouseknecht** [comment]
New Namespace `inoxio` created with `MichaelKunze` set as the owner.

**Comment by MichaelKunze** [comment]
Great. Thank you very much!
