### ISSUE TITLE
eNiXHosting github organisation rename issue

### ISSUE THREAD

**Issue by lcaflc** [ansible/galaxy#1439]
##### SUMMARY
A few months ago we've changed our Organisation name.
So changed [eNiXHosting](https://github.com/eNiXHosting) to [enix](https://github.com/enix) in github.
Then to avoid squatting of our old content we create eNiXHosting Org with empty content.
As github provide virtual links for already existing contents at that time older role manual import work fine.
However I am unable to add new roles as the namespace still linked to eNiXHosting does not see anything.
I so tried to change the associated Provider namespace but I can't.

##### STEPS TO REPRODUCE
Go into namespace properties, and untick old provider namespace (eNiXHosting), tick the new one (enix)

##### EXPECTED RESULTS
New association should be to provider namespace enix and I should be able to import new roles.

##### ACTUAL RESULTS
Got 
```
Error! Error creating or updating provider namespaces: get() returned more than one ProviderNamespace -- it returned 5! (undefined)
```

Thanks.

**Comment by chouseknecht** [comment]
@lcaflc 

Created `enix` namespace in Galaxy for you. You should be able to delete the existing roles and disassociate any provider namespaces from `eNixHosting`, and then associate the correct provider namespace and add repositories/roles to `enix`.

**Comment by lcaflc** [comment]
Thank you,
I'm now trying to attach the enix github namespace and get this error:
```Error! Error creating or updating provider namespaces: get() returned more than one ProviderNamespace -- it returned 5! (undefined)```

see screenshot:
![galaxy](https://user-images.githubusercontent.com/9885798/50597214-e7edeb80-0ea6-11e9-8792-c944c6c305a0.png)

Thanks.

**Comment by chouseknecht** [comment]
Removed the existing `enix` provider namespaces from the Galaxy database. There were 5 of them. Not sure why.

**Comment by lcaflc** [comment]
Works now. Thanks a lot
