### ISSUE TITLE
Request for new namespace "webplates"

### ISSUE THREAD

**Issue by sagikazarmark** [ansible/galaxy#1442]
Not sure if this is the right place but could you please create a new namespace called "webplates" in galaxy for me?

- org: https://github.com/webplates
- owner: @sagikazarmark

Thank you very much!

**Comment by chouseknecht** [comment]
@sagikazarmark 

Done. Thanks for reaching out to us. Please let us know, if you have any trouble accessing the new namespace.

**Comment by sagikazarmark** [comment]
Awesome, works like a charm! Thanks for the fast response @chouseknecht
