### ISSUE TITLE
Import triggered by Travis fails when UI import succeeds

### ISSUE THREAD

**Issue by mcred** [ansible/galaxy#1443]
##### SUMMARY
We are trying to import contents directly from Travis using a notification webhook. The repository is owned by an organization **delphix**, travis builds for this organization, but the import fails in galaxy with the following error:

`Failed to get GitHub account for Galaxy user delphix. You must first authenticate with GitHub.`

I am able to import the contents successfully through the web UI as my user **mcred**, but the webhook trigger fails. The documentation for importing content with travis mentions associating a Galaxy Namespace with a GitHub Organization and I can confirm that for the **delphix** namespace the **delphix** organization is under "Selected Provider Namespaces".

Repository with issue:
https://github.com/delphix/ansible-target-host

##### STEPS TO REPRODUCE
Add a travis.yml build file for a repository owned by an organization then trigger build with 
```
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
```

##### EXPECTED RESULTS
A successful import, same as if I click the import button in the UI.

##### ACTUAL RESULTS
```
Starting import: task_id=347904, repository=delphix/ansible-target-host

Task "347904" failed: Failed to get GitHub account for Galaxy user delphix. You must first authenticate with GitHub.
```

**Comment by chouseknecht** [comment]
It appears that `delphix` is being passed by Travis to Galaxy as the GitHub username. Is there a `delphix` GitHub user account? If so, you'll need to connect to Galaxy with that account, which will create a `delphix` Galaxy user, then associate the Galaxy user with the Namespace.

**Comment by CloudSurgeon** [comment]
I attached travisci to one of my org's (Delphix) repos. A 'delphix' user does not exist, it is only a organization. So Travis sends a webhook as the organization, and not as me. I don't see a way to modify this behavior in Travis. 
![image](https://user-images.githubusercontent.com/12521930/50647560-dcea9800-0f46-11e9-871f-6eefe94ad17e.png)

**Comment by mcred** [comment]
The user is set from the TRAVIS_REPO_SLUG by a string split in the function below. Is there no way to overwrite this or set a user in the webhook? What's the recommended setup for publishing artifacts owned by an GitHub Orginzation?

```
def _get_repo_info(self, request):
        """Return github username and repository from request headers."""

        slug = request.META.get('HTTP_TRAVIS_REPO_SLUG')
        if not slug:
            raise ValidationError('Expected "TRAVIS_REPO_SLUG" header')
        return slug.split('/', 1)
```

**Comment by chouseknecht** [comment]
@mcred, there is no way to override it.

**Comment by mcred** [comment]
@chouseknecht Thanks for confirming. Any input on my second question:

What's the recommended setup for publishing artifacts owned by an GitHub Orginzation?

**Comment by chouseknecht** [comment]
@mcred 

The only way to make it work is to log into Galaxy as the `delphix` GitHub user.

**Comment by CloudSurgeon** [comment]
This is the disconnect: ‘delphix’ is a github organization, not a user. A github login does not exist for ‘delphix’. Users, like myself, who are assigned to the delphix github organization can login and use the organization’s repos, etc.

**Comment by chouseknecht** [comment]
@mcred 

Right. So the other option is to configure Travis-Ci under a username, rather than an org name.

**Comment by CloudSurgeon** [comment]
@chouseknecht Thanks, but there doesn't seem to be a way to do that, I am afraid. That was my first thought to try. But, even if I could, the TRAVIS_REPO_SLUG variable that is sent in the webhook would still be the same since it is <repoowner>/<reponame>. And, per your code that my colleague referenced above, Galaxy would still be in search of **delphix**/ansible-target-host. Even if we could override the TRAVIS_REPO_SLUG to say, **cloudsurgeon**/ansible-target-host, 1) That would point to a github repo that doesn't exist 2) It would point to a Galaxy role that doesn't exist (cloudsurgeon/targethost)

**Comment by chouseknecht** [comment]
@mcred @CloudSurgeon 

Removed the `delphix` user, as mentioned above. Can you trigger a new Travis-CI build. I think it will work this time.

**Comment by mcred** [comment]
@chouseknecht That did it! The build from Travis succeeded and the import did as well! Thank you for your help looking into this.

**Comment by CloudSurgeon** [comment]
aahhh! Awesome. Thank you so much, @chouseknecht . This was so confusing.
