### ISSUE TITLE
Remove or change weight of "Used in production?" survey result

### ISSUE THREAD

**Issue by geerlingguy** [ansible/galaxy#1444]
### Use Case

When reviewing roles on Galaxy (or heck, when using them), whether individuals use them in production or not does not seem to be nearly as important as the other metrics.

Many people (myself included) use Ansible a _ton_ for what I would consider "development" resources, but don't directly manage production resources with Ansible playbooks. Therefore, this question (unlike the other four) seems to be up for interpretation.

For example, many people use local development environments which are built fully or in part using a role like `geerlingguy.java`: https://galaxy.ansible.com/geerlingguy/java

It currently has a code quality score of 5/5, and scores 5/5 for all the other metrics.

But because many users likely use it to build development environments (and use some other solution for installing Java, or have it pre-installed, in production), the "Used in production?" question gets a 3.3/5, and takes the role's overall score **down from 5/5 to 4.2/5**.

The problem is the idea of 'production' probably meant "I use this for mission-critical things" (e.g. my primary development environment, CI, or maybe even 'prod' servers), but most people interpret the question as "I use this for production servers", therefore don't give a high rating for this question for certain roles.

### Proposed Solution

Either change the weighting of the survey questions so the 'used in production?' question affects the overall role ratings less, or drop the question (and maybe replace it with a question like "I would feel safe using this role in a production environment" or something more along those lines, since I think that's the _spirit_ of the question).

### Alternatives

N/A

### Implementation

N/A

**Comment by newswangerd** [comment]
This is a really good point. I think it's probably still useful to give user's an indication if the role has been used in production or not, so my proposal is to remove "used in production" from the content score entirely, but still display the ratio of how many people have said that they use it in production.

How does that sound?

**Comment by geerlingguy** [comment]
That metric does seem useful on its own, for sure.

**Comment by tima** [comment]
We had a quick huddle up to hash this out. We realized this would require some tinkering and appreciate the feedback. We think the intent of the question (is this ready for production?) is a good one and should still be included in the weighting of the community feedback. So we're going to leave the scoring as is, but tweak the question to clarify that intent to "Ready for production?" We also intend to add some explanatory rollover to expand on that question. Something like "The intent of this question is to ask if the content is production class in the opinion of reviewer. The reviewer may not actually be using the content in a production environment or mission-critical workflow, but would be comfortable doing so if they had the need." It's a subjective question (all of the community survey questions are), but we believe given enough ratings some consensus of "production" will emerge.  We need to continue to work on ways of getting more surveys from the community. (That's a whole there epic thread though.)

**Comment by geerlingguy** [comment]
@tima - That would be helpful. I just think the question is a bit too subjective currently, and because of it some of my poor roles have been unnecessarily dinged a few points. You know how important it is for me to have my fancy internet karma points!
