### ISSUE TITLE
Add new namespace

### ISSUE THREAD

**Issue by betrcode** [ansible/galaxy#1445]
Please add a new namespace `crisp` with `betrcode` as owner.  If `crisp` is already taken, use `crispab` instead.

Crisp refers to the Crisp GitHub organization: https://github.com/crispab

**Comment by chouseknecht** [comment]
The namespace `crisp` is available. I don't find a `betrcode` username in Galaxy. Please authenticate to Galaxy using the `betrcode` GitHub account.

**Comment by betrcode** [comment]
Sorry, the Galaxy user seems to be `max.wenzin`, and that's what I get when I log in with my github user `betrcode`

**Comment by betrcode** [comment]
![image](https://user-images.githubusercontent.com/777108/50645242-56987b00-0f73-11e9-9fc1-80cea66681e9.png)

**Comment by betrcode** [comment]
@chouseknecht Works. Thanks! Closing this.
