### ISSUE TITLE
Preserve dashes in role name (idealista.java-role)

### ISSUE THREAD

**Issue by dortegau** [ansible/galaxy#1452]
##### SUMMARY

Our role was renamed to "[java_role](https://galaxy.ansible.com/idealista/java_role)" instead of jave-role and all our roles with dependecies on this, and our playbooks are broken. 

Could you preserve the name with dashes?

##### STEPS TO REPRODUCE

Basically we cannot execute hundreds of internal playbooks or public roles that has [idealista.java-role](https://github.com/search?l=YAML&q=org%3Aidealista+%22idealista.java-role%22&type=Code) as dependency

##### ACTUAL RESULTS

Fails because Ansible Galaxy returns a 404

**Comment by chouseknecht** [comment]
Fixed. As long as you don't delete the `java-role` and re-import, it should be OK.

**Comment by dortegau** [comment]
Is not working anymore :(
