### ISSUE TITLE
Unable to use ansible-galaxy to install requirements without warnigns

### ISSUE THREAD

**Issue by ssbarnea** [ansible/galaxy#1455]
##### SUMMARY
It seems that at this moment there is no way to run `ansible-galaxy install -r requirements.yaml` in an idempotent way without triggering warnings.

Galaxy installer needs to avoid such false-positive warnings. At minimal it should provide some command line parameter that can disable this "feature".

##### STEPS TO REPRODUCE

Run `ansible-galaxy install -r requirements.yml` twice. The second time you will see a warning.

##### EXPECTED RESULTS
Do nothing when requirements are already present, clearly avoiding to display a warning which is not something to worry about.

##### ACTUAL RESULTS

```
ansible-galaxy install -r requirements.yml
 [WARNING]: - avinetworks.docker (2.3.0) is already installed - use --force to change version to unspecified
```

**Comment by chouseknecht** [comment]
@ssbarnea 

Thanks for reaching out to us. We're not doing any new development or feature work on `ansible-galaxy`. We're actively working on [Mazer](https://github.com/ansible/mazer) as the future installer and manager of Ansible content.

**Comment by whalecoiner** [comment]
> Mazer will be deprecated with the release of Ansible 2.9. The functionality developed in Mazer will migrate to the ansible-galaxy command line tool. See https://github.com/ansible/ansible/pull/57106 for details.

🤔
