### ISSUE TITLE
Getting: "Error! Save repository import failed: (Http failure response for https://galaxy.ansible.com/api/v1/imports/: 403 Forbidden) " on all imports

### ISSUE THREAD

**Issue by ahuffman** [ansible/galaxy#1458]
##### SUMMARY

Getting "Error! Save repository import failed: (Http failure response for https://galaxy.ansible.com/api/v1/imports/: 403 Forbidden)" when attempting to import roles to Galaxy.
##### STEPS TO REPRODUCE

Click the import button.

##### EXPECTED RESULTS

Succesful re-import
##### ACTUAL RESULTS

Error message "Error! Save repository import failed: (Http failure response for https://galaxy.ansible.com/api/v1/imports/: 403 Forbidden)"

```
Error! Save repository import failed: (Http failure response for https://galaxy.ansible.com/api/v1/imports/: 403 Forbidden)
```

**Comment by chouseknecht** [comment]
@ahuffman 

What's the namespace and repository you're attempting to import?

**Comment by ahuffman** [comment]
@chouseknect the namespace is ahuffman, and I'm having the problem on https://github.com/ahuffman/ansible-resolv as an example, but seems to be happening with all my repos.

**Comment by ahuffman** [comment]
Also for reference, it seems that particular galaxy role was tied to an older release v1.2 which no longer exists.  When you run ansible-galaxy install ahuffman.resolv I would expect the latest 1.3.1 release to be installed, which was imported a month ago.

**Comment by ahuffman** [comment]
I tried one more thing.  I just did a logout on Galaxy and log back in.  After a full logout and login I was able to import once again.  Thanks for looking into this, seems that it was an auth timeout related issue.
