### ISSUE TITLE
Ansible Galaxy import fails with permission denied

### ISSUE THREAD

**Issue by rockandska** [ansible/galaxy#1463]
##### SUMMARY
Can't upload role through ansible-galaxy cli

##### STEPS TO REPRODUCE
```
$ ansible-galaxy login --github-token='[redacted]'
Successfully logged into Galaxy as rockandska
$ ansible-galaxy import rockandska ansible-role-erlang
ERROR! Permission denied.
```
Seems exactly the same as #874 and is maybe the reason for why I can't see anything too in "My content" on the web ui ?

Already tried to logout / login

Token is the same in the WebUi and ~/.ansible_galaxy

ping @cutwater 

Regards,

**Comment by cutwater** [comment]
Hi @rockandska. Thank you for reporting this issue. I'll take a look asap.

**Comment by cutwater** [comment]
@rockandska Can you please provide details when the issue happened and what actions you performed prior to the issue. Did you rename your GitHub account any time in past?

**Comment by rockandska** [comment]
If i had renamed my GitHub account (not sure about it, but regarding to my previous emails, it seems i had once renamed it to reverted it back a few days later at the creation) it was long before my first login on ansible-galaxy.

Before trying to import through the cli, i was able to delete some roles through the cli : the one i try to re-import, and a role imported through "api" from travis due to a PR. I've done those deletions through the cli cause i wasn't able to do it through the WebUI (nothing was shown on "my content").

I didn't tried to import another role (new to my namespace) to see if the bug is due to my previous delete or is general to all roles i want to import.

Regards,

**Comment by rockandska** [comment]
Tried with a fresh role and same behavior

```
$ exec env -i bash --norc --noprofile
bash-4.4$ cd /tmp
bash-4.4$ git clone https://github.com/rockandska/testrepository                         
Cloning into 'testrepository'...
remote: Enumerating objects: 3, done.        
remote: Counting objects: 100% (3/3), done.        
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0        
Unpacking objects: 100% (3/3), done.
bash-4.4$ ~/.local/bin/ansible-galaxy --force init testrepository/           
- testrepository/ was created successfully
bash-4.4$ cd testrepository/
bash-4.4$ git add .
bash-4.4$ git config user.email "yoann_mac_donald@hotmail.com"         
bash-4.4$ git config user.name "RockAndSka"                   
bash-4.4$ git commit -m"test role"
[master bb62573] test role
 8 files changed, 113 insertions(+), 1 deletion(-)
 rewrite README.md (100%)
 create mode 100644 defaults/main.yml
 create mode 100644 handlers/main.yml
 create mode 100644 meta/main.yml
 create mode 100644 tasks/main.yml
 create mode 100644 tests/inventory
 create mode 100644 tests/test.yml
 create mode 100644 vars/main.yml
bash-4.4$ git push
Username for 'https://github.com': rockandska
Password for 'https://rockandska@github.com': 
Counting objects: 16, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (16/16), 2.51 KiB | 855.00 KiB/s, done.
Total 16 (delta 0), reused 0 (delta 0)
To https://github.com/rockandska/testrepository
   a426dea..bb62573  master -> master
bash-4.4$ ~/.local/bin/ansible-galaxy login
[redacted preferred token message]
Github Username: rockandska
Password for rockandska: 
Successfully logged into Galaxy as rockandska
bash-4.4$ echo $(($(date +%s) - $(date +%s -r /home/rockandska/.ansible_galaxy)))
30
bash-4.4$ ~/.local/bin/ansible-galaxy import rockandska testrepository           
ERROR! Permission denied.
bash-4.4$ 
```

**Comment by rockandska** [comment]
This is the security log from GH.
It is weird , but from the message we could trust that the token is revoked just after its creation

![log](http://i.imgur.com/akhar4y.png)

**Comment by cutwater** [comment]
@rockandska Thanks for sharing details, analyzing it.
Namespace owners is now fixed, please check again.
