### ISSUE TITLE
Create a namespace for organization

### ISSUE THREAD

**Issue by rvansa** [ansible/galaxy#1468]
##### SUMMARY
Please create a Galaxy namespace `hyperfoil` for GitHub organization Hyperfoil. Thank you.

It's a bit sad that the only way to do this is through GitHub issue, given that requests like appear since 2015.

**Comment by chouseknecht** [comment]
Namespace created.

Apologies for the inconvenience. We're creating new namespaces manually in hopes of preventing copyright/trademark infringements.

Thanks for reaching out to us. Please let us know, if you run into any issues accessing the new namespace.
