### ISSUE TITLE
Travis CI notifications import not working #2

### ISSUE THREAD

**Issue by DrPsychick** [ansible/galaxy#1479]
##### SUMMARY
I have the exact same problem as stated in https://github.com/ansible/galaxy/issues/1033
with both of my ansible roles imported and connected to travis-ci.org.

What works:
* login to galaxy (web or terminal)
* manually import the role (web or terminal)

What doesn't work:
* find any notifications on https://galaxy.ansible.com/api/v1/notifications
* use the form on the page and POST : Error 500

Galaxy: https://galaxy.ansible.com/DrPsychick/docker-deploy
GitHub: https://github.com/DrPsychick/ansible-docker
Travis: https://travis-ci.org/DrPsychick/ansible-docker

I also have a second repository https://github.com/DrPsychick/ansible_influx_downsampling which has the same role name as the repository, so that should not be the issue.

I tried re-configuring the integration in the terminal with `ansible-galaxy`, but it did not help.

##### STEPS TO REPRODUCE
It never works for me (not sure it has worked before, but I think it worked when I set it up)

##### EXPECTED RESULTS
A successful build on travis-ci should trigger an import on ansible-galaxy

##### ACTUAL RESULTS
ansible-galaxy does not import the role after a successful build, whether its tagged correctly or not.

**Comment by chouseknecht** [comment]
@cutwater 

We talked about this on Slack. Adding an update here for tracking.

Testing imports in `galaxy-dev` to see if long commit strings are automatically truncated. However, getting the following error consistently:

```
Task "280918" failed: [Errno 2] No such file or directory: '/var/tmp/galaxy/imports/tmpvqc8rs8j'
```

**Comment by chouseknecht** [comment]
@DrPsychick 

I am able to get this to work in our `galaxy-dev` environment using the latest changes. I setup testing using `travis-ci.com`, and created a fork of your `ansible-docker` repo. Within my fork, I merged a PR with a typical commit message, and one with a really long commit message. In both cases a notification was created on Galaxy, and the import worked as expected.

Here's a link to the notification created with a really long commit msg: https://galaxy-dev.ansible.com/api/v1/notifications/215893/

**Comment by DrPsychick** [comment]
Awesome @chouseknecht, many thanks for the fast response on this bug!
I'm ready to test it once its on production.
