### ISSUE TITLE
Namespace rename

### ISSUE THREAD

**Issue by seandst** [ansible/galaxy#1498]
Currently, I am an owner of a github organization, oasis-roles, which imports roles into a galaxy namespace of the same name. Based on #775, https://github.com/ansible/galaxy/issues/779#issuecomment-454445902, and other similar comments, it appears that continuing to use the "oasis-roles" namespace in galaxy will lead to problems.

As such, I think the answer is to rename the `oasis-roles` namespace in galaxy to `oasis_roles`, and based on several similar issues, I think this is the correct way to request the change.

So, if all of that makes sense, please rename the `oasis-roles` galaxy namespace to `oasis_roles`.

I'm curious about whether or not redirects will be put in place to prevent breaking existing references to the `oasis-roles` namespace, but I'm prepared to deal with the aftermath if this results in a breaking change for users of `oasis-roles`.

**Comment by chouseknecht** [comment]
@seandst 

Before we do this, couple things to understand:

1. For now, the GitHub namespace (organization) needs to match the Galaxy namespace. 
2. GitHub does not all '_' in the namespace name. So, `oasis_roles` won't work in GitHub.

**Comment by seandst** [comment]
I was afraid of that first point, as that means we can't do this, exactly. I'll check with the team regarding other naming options.

What exactly do you mean by "For now", though? Any information that helps plan around this inconvenience would be appreciated.

**Comment by chouseknecht** [comment]
We're working on Galaxy actually hosting content in the form of an artifact. In Galaxy 3.2, users will have the option to publish or upload an artifact to Galaxy. In that case, the namespace does not need to be tied to GitHub.

**Comment by chouseknecht** [comment]
@seandst 

My first response was actually incorrect. The Galaxy namespace does not have to match the GitHub namespace. My bad.

We can change the name in Galaxy to `oasis_roles`, and imports to Galaxy will continue to work. Users will just need to know that when they install things, they'll need to use the new namespace. For example, `ansible-galaxy install oasis_roles.chrony`

Apologies for the confusion.

**Comment by seandst** [comment]
That is terrific news. Given that, please proceed with the rename at your earliest convenience.

**Comment by chouseknecht** [comment]
@seandst 

Renamed complete. Let us know, if you run into any problems. Thanks for reaching out to us!
