### ISSUE TITLE
New namespace for my organization

### ISSUE THREAD

**Issue by tr1ck3r** [ansible/galaxy#1506]
Please add the 'venafi' organization namespace to ansible-galaxy under my supervision.  Thank you in advance!

**Comment by chouseknecht** [comment]
Done. Thanks for reaching out to us!

**Comment by tr1ck3r** [comment]
Thank you @chouseknecht 

It doesn't seem to be letting me add my provider namespace "Venafi" when I edit the properties of the new "venafi" galaxy namespace I now have in My Content.  

> Error! This provider namespace is already associated with a Galaxy namespace (Venafi)

I don't find any existing "Venafi" namespace when I search the community.  Could the issue be the mixed case?  If so, would you please rename the new galaxy namespace to "Venafi" to match GitHub?
