### ISSUE TITLE
Organization namespace request for @sopel-irc

### ISSUE THREAD

**Issue by dgw** [ansible/galaxy#1513]
After searching around all morning, I've come to the conclusion that opening an issue here is the only way to do this. Apologies if I've missed a way to do it through Galaxy's web interface!

I would like to ask that a Galaxy namespace be created for the @sopel-irc organization.

We would prefer to use just `sopel` as the namespace name, rather than `sopel_irc`, if that's OK. :smile_cat:

Please add myself and @duckle29 as owners. Thanks!

**Comment by chouseknecht** [comment]
@dgw

Done. New namespace `sopel` created. Thanks for reaching out to us!
