### ISSUE TITLE
ansible-galaxy install from multi-role repo picks wrong role

### ISSUE THREAD

**Issue by rvansa** [ansible/galaxy#1517]
##### SUMMARY
When installing my role from ansible-galaxy multi-role repository it installs different role (from that repo) under the desired role.

##### STEPS TO REPRODUCE
```
> ansible-galaxy install hyperfoil.hyperfoil_setup
- downloading role 'hyperfoil_setup', owned by hyperfoil
- downloading role from https://github.com/Hyperfoil/hyperfoil-ansible/archive/master.tar.gz
- extracting hyperfoil.hyperfoil_setup to /home/rvansa/.ansible/roles/hyperfoil.hyperfoil_setup
- hyperfoil.hyperfoil_setup (master) was installed successfully

> head -n 1 ~/.ansible/roles/hyperfoil.hyperfoil_setup/README.md
Hyperfoil test runner
```

##### EXPECTED RESULTS
The command above should print out `Hyperfoil setup` as per [hyperfoil-setup readme](https://github.com/Hyperfoil/hyperfoil-ansible/blob/master/roles/hyperfoil-setup/README.md) but it shows the readme for [hyperfoil-test](https://github.com/Hyperfoil/hyperfoil-ansible/tree/master/roles/hyperfoil-test).

##### ACTUAL RESULTS
The issue is with whole role, not just README - all files are copied from the wrong role.

```
ansible-galaxy 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/rvansa/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-galaxy
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

**Comment by chouseknecht** [comment]
`ansible-galaxy` does not support multi-role repositories. You'll want to use [Mazer](https://github.com/ansible/mazer)

**Comment by rvansa** [comment]
It is a bit confusing that this half-works, so ansible-galaxy should either fail with 'Multi-role repos not supported' or install it to the correct place. I assume that you want any new feature to end up in mazer instead, though.

Is there any ETA when the mazer content layout will be available to mainstream Ansible? I don't really want to enforce building Ansible from source to anyone who wants to use my scripts. Or could mazer have a `--legacy` option to use the classic layout?
