### ISSUE TITLE
Cannot add provider namespace to new galaxy namespace

### ISSUE THREAD

**Issue by tr1ck3r** [ansible/galaxy#1521]
I'm not able to add my GitHub provider namespace "Venafi" when I edit the properties of the new "venafi" galaxy namespace I now have in My Content (created for me in #1506).  I get the following error:

> Error! This provider namespace is already associated with a Galaxy namespace (Venafi)

I don't find any existing "Venafi" namespace when I search the community. I suspect the issue could be the mixed case based on #1187. Assuming that is the issue, would you please rename my new galaxy namespace to "Venafi" to match GitHub?  Thank you for your help.

**Comment by chouseknecht** [comment]
@tr1ck3r 

The provider namespace `vanafi` is associated with namespace [arykalin](https://galaxy.ansible.com/arykalin).

**Comment by tr1ck3r** [comment]
Thank you @chouseknecht that explains it.  Alexander is one of my developers.  I'll just ask him to remove our organization's provider namespace from his personal account so I can add it to the new "venafi" organization you created for me.
