### ISSUE TITLE
/account/login : Server Error (500)

### ISSUE THREAD

**Issue by meabed** [ansible/galaxy#1537]
##### SUMMARY

I get Server Error (500) every i try to login.
##### STEPS TO REPRODUCE

- Go to page: https://galaxy.ansible.com/accounts/login/
- Input Email and Password
- I get 500 server error

##### EXPECTED RESULTS

Logged in

**Comment by chouseknecht** [comment]
I removed the `meabed` user account from Galaxy. Please try to login again.

**Comment by meabed** [comment]
Awesome thank you
