### ISSUE TITLE
role's dependencies aren't updated at Ansible Galaxy.

### ISSUE THREAD

**Issue by suzuki-shunsuke** [ansible/galaxy#1539]
##### SUMMARY

I removed some dependencies from role's meta/main.yml and ran "restart import" with Ansible Galaxy's web UI but dependencies aren't removed from Ansible Galaxy.

For example, [suzuki-shunsuke.pyenv](https://galaxy.ansible.com/suzuki-shunsuke/pyenv) looks to depend on suzuki-shunsuke.ghq-module but actually it doesn't depend on.

https://github.com/suzuki-shunsuke/ansible-pyenv/blob/master/meta/main.yml

I reproduced this behavior at the following roles.

* https://galaxy.ansible.com/suzuki-shunsuke/pyenv
* https://galaxy.ansible.com/suzuki-shunsuke/tmux-tpm

##### STEPS TO REPRODUCE

Remove dependencies from role and run "restart import".

##### EXPECTED RESULTS

Dependencies are removed.

##### ACTUAL RESULTS

Dependencies aren't removed.

**Comment by chouseknecht** [comment]
Looks like the import process may not be removing dependencies when `meta/main.yml` has been updated.
