### ISSUE TITLE
Support for platform: oracle linux in meta/API

### ISSUE THREAD

**Issue by daniel-wtd** [ansible/galaxy#1542]
### Use Case

I want to publish roles in the ansible galaxy with support for oracle linux. Currently this seems not supported according to:

<https://galaxy.ansible.com/api/v1/platforms/>

### Proposed Solution

Adding the oracle linux platform would be awesome. It could look like:

        {
            "id": $ID,
            "url": "/api/v1/platforms/$ID/",
            "related": {},
            "summary_fields": {},
            "created": "$DATE",
            "modified": "$DATE",
            "name": "Oracle",
            "release": "7.6",
            "active": true
        },

### Alternatives

No "official" support for Oracle Linux in the galaxy.

**Comment by chouseknecht** [comment]
@daniel-wtd 

I think this falls under Enterprise Linux, which is designated in Galaxy as `EL`: https://galaxy.ansible.com/api/v1/platforms/?name=EL

**Comment by daniel-wtd** [comment]
@chouseknecht I thought, RHEL is meant with EL. Is it the same? (basically OL is EL with some teweaks, of course ^^)

**Comment by chouseknecht** [comment]
EL is Enterprise Linux, which covers RHEL, Oracle Linux, Centos, etc.

**Comment by daniel-wtd** [comment]
@chouseknecht thanks a lot! :+1:
