### ISSUE TITLE
Namespace for GitHub organization

### ISSUE THREAD

**Issue by gtema** [ansible/galaxy#1554]
Can you please create following namespaces for GitHub organizations:

- "otc" (or "opentelekomcloud" if not possible) for https://github.com/opentelekomcloud
- "otc_infra" (or "opentelekomcloud_infra" if not possible) for https://github.com/opentelekomcloud-infra

(I am an admin for both organizations) 

P.S. from the docs it is not really clear (and took me really quite some time to figure out) how to create/request namespace for organization.

Thank you

**Comment by xprazak2** [comment]
I would like to request a namespace for organization as well:

* 'theforeman' for https://github.com/theforeman/

cc @tbrisker and @GregSutcliffe

Thank you

**Comment by newswangerd** [comment]
@gtema @xprazak2 done. I also added some extra documentation for the process (#1557).
