### ISSUE TITLE
Set new owner for existing namespace

### ISSUE THREAD

**Issue by benpatterson** [ansible/galaxy#1559]
Hi - I am a GitHub owner of an existing space (`threatstack`) and the previous owner has left the company. I'd like to get ownership so we can publish out our latest version of an existing role. I'll also add other folks to avoid this kind of issue if I win the lottery. 

I would also need a way of adding the repo to "my content". That call fails with a 504 even for my own personal namespace. (Potentially the OAuth permissions by the Ansible Galaxy GH application are not permissive enough since the `public_repo` access is no longer part of the deal.)

Could you-all help fix me up to push out the latest role for the `threatstack` org? Thank you!

Similar to #846 or #1225

**Comment by newswangerd** [comment]
Hi @benpatterson. I added you as an admin on the galaxy threatstack namespace. You should be able to see it listed under "My Content" now.

What exactly are you doing when you encounter this 504 error? Does it show up when you click the "Add Content" button on the "My Content" page?

**Comment by benpatterson** [comment]
Hi @newswangerd --

Excellent news re: the threatstack namespace. I see it under My Content now, just as you have described. I'll attempt to import a role and can log a new issue if I have a problem there.

Re: the 504 error... That occurs when I click on "Add Content". It looks like it's making an xhr request to `https://galaxy.ansible.com/api/v1/providers/sources/github/benpatterson/` and getting the 504 from there.

**Comment by benpatterson** [comment]
I successfully imported our role, which is great. I'm happy to open a new issue for the 504, if you feel that's warranted. Thanks again for the help!

**Comment by newswangerd** [comment]
@benpatterson I'd appreciate it if you could open another issue so that we can track it separately from threatstack admin request.

Glad it works!
