### ISSUE TITLE
504 when attempting to add repositories to "My Content"

### ISSUE THREAD

**Issue by benpatterson** [ansible/galaxy#1564]
## Bug Report 
When attempting to add repositories under "My Content", the call results in a HTTP 504.

##### SUMMARY
Although I am not new to ansible, I am new to ansible galaxy. We successfully imported a role for our org earlier this week after some namespace/ownership cleanup. So previous repositories were already loaded for my account. However, I see that, should I decide to add more repositories under either my GitHub org, or my personal account, the outbound xhr request results in a 504.

##### STEPS TO REPRODUCE

Login to Ansible Galaxy. *Note, as a new user, the Oauth Permissions allowed are read-only to org and team membership, as well as my e-mail address.*

![galaxy_oauth_permissions](https://user-images.githubusercontent.com/2004678/52791012-f1d24500-3035-11e9-97c9-33c24c72f5f4.png)

Next, access My Content. 

On this screen, click on the blue bar, "+Add Content" on the right side of the screen.
![add_content_button](https://user-images.githubusercontent.com/2004678/52791123-3b229480-3036-11e9-8638-a373fc248946.png)

A modal then appears and attempts to load; however it spins for awhile before getting a 504.

Behind this modal (which registers a failure message), there is a toast message that appears in the background, pointing out the 504. 

![loading_repositories_hang2](https://user-images.githubusercontent.com/2004678/52791212-6d33f680-3036-11e9-9da7-bba9cd91c305.png)

For easy copy/paste, here's the url: `https://galaxy.ansible.com/api/v1/providers/sources/github/benpatterson/`

I am able to reproduce this whether it's my own space, or the space of the org that I'm a member of.

##### EXPECTED RESULTS
I expected some repository options to load, or if the logic is smarter, only relevant repos (if any) to load. I do not expect a protocol error.

##### ACTUAL RESULTS
Captured above in steps-to-repro

Happy to provide more detail if needed. I'm able to do what I have to do at this point, but wanted to report this issue. Chers & thanks.

**Comment by newswangerd** [comment]
```
Traceback (most recent call last):
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/galaxy/api/views/repository_source.py", line 69, in get
    repos = GithubAPI(user=request.user).get_namespace_repositories(
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/galaxy/api/githubapi.py", line 35, in __init__
    self.client = self.get_client()
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/galaxy/api/githubapi.py", line 56, in get_client
    "User does not have a GitHub OAuth token"
Exception: User does not have a GitHub OAuth token
```

I tracked the error down in our logs. Looks like we're missing your GitHub token. Something must have gone wrong during the sign up process. Not entirely sure why this happened or how to fix it, but I'll keep looking into it.

**Comment by benpatterson** [comment]
Thanks @newswangerd  That's interesting. 
If it helps, I encountered this issue yesterday, so revoked the access and re-signed-up, but the problem persisted. Feel free to ping me if you'd like me to test anything out for you.

**Comment by newswangerd** [comment]
Actually, it looks like that stack trace might be a red herring. I think the issue might be caused by our infrastructure and not Galaxy. I'll see if someone more familiar with that area can help.

**Comment by chouseknecht** [comment]
@newswangerd 

Noticed that the user is part of the Jenkins GitHub org, which contains over 2000 repositories. Could the number of repositories have something to do with this?

**Comment by cutwater** [comment]
@benpatterson Can you please confirm that the issue still persists?

**Comment by benpatterson** [comment]
Hi @cutwater indeed...I still see the problem on galaxy.ansible.com. Thx for doublechecking.

**Comment by chouseknecht** [comment]
My theory is that we're timing out somewhere [because of this loop](https://github.com/ansible/galaxy/blob/devel/galaxy/api/githubapi.py#L110). In this particular case it loops over 74 pages of repositories. Wondering if there is a more efficient way to call the GitHub api, and only get the repositories that fall under the username `benpatterson`. In the current code, we're getting the set of repositories the use has access to, which is a lot.

**Comment by newswangerd** [comment]
@benpatterson I think we finally managed to fix the issue. @chouseknecht was right about our API in that our back end was querying for all of your repos (including the 2000 some in jenkinsci) and causing the system to time out.

The changes are currently live on our dev environment: https://galaxy-dev.ansible.com/. If you can confirm that it works there we'll get the fix back ported into production later this week.

**Comment by benpatterson** [comment]
Hi @newswangerd wow thanks for such a quick fix on this; I realize it's a bit of an edge case.

I checked it out in the dev environment, and it works for my own namespace; however, I cannot pull in the `threatstack` namespace, which is the other (smaller) org that I am a member of. I'm thinking that might be too limiting a change for other users. What do you think?

**Comment by newswangerd** [comment]
@benpatterson looks like we're using an older copy of the database for galaxy-dev that was cloned from production before I set you up as an admin for `threatstack`. I added you as an admin on galaxy-dev so it should work now.

**Comment by benpatterson** [comment]
@newswangerd Ah, excellent. Indeed it's working perfectly. Thanks a lot for addressing this! 🎉

**Comment by newswangerd** [comment]
We got prod deployed this morning so this issue should be resolved now. Thanks for your patience!
