### ISSUE TITLE
https://galaxy.ansible.com/api/v1/platforms/ is out of date

### ISSUE THREAD

**Issue by SpokeyWheeler** [ansible/galaxy#1566]
### Use Case
SLES 15 is out, but the API doesn't recognise it. Same for Ubuntu bionic beaver.

### Proposed Solution

Update the available platforms

### Alternatives

Are there any?

### Implementation

No idea.

**Comment by newswangerd** [comment]
Just added SLES 15:  https://galaxy.ansible.com/api/v1/platforms/?id=197

Ubuntu is listed as Ubuntu bionic: https://galaxy.ansible.com/api/v1/platforms/?id=155
