### ISSUE TITLE
No namespace after logging in

### ISSUE THREAD

**Issue by mvasilenko** [ansible/galaxy#1568]
##### SUMMARY
No namespace after logging in

##### STEPS TO REPRODUCE
Log in to ansible galaxy

##### EXPECTED RESULTS
one namespace

##### ACTUAL RESULTS
no namespaces, empty My Content, unable to contribute/upload/etc

Looks similar to #1108, when I'm searching for _mvasilenko_ in community, one old role was found, please delete this namespace and create an empty new one @chouseknecht 

```

```

**Comment by chouseknecht** [comment]
Deleted the namespace and user `mvasilenko`. Let us know if you run into trouble getting logged in again.
