### ISSUE TITLE
Content Not Found

### ISSUE THREAD

**Issue by vbotka** [ansible/galaxy#1570]
##### SUMMARY
https://galaxy.ansible.com/vbotka/ansible-nginxinc-nginx
reports; "Content Not Found"
Role ansible-nginxinc-nginx is not among the roles reported by: ansible-galaxy search --author vbotka

##### STEPS TO REPRODUCE
Take a look at
https://galaxy.ansible.com/vbotka/ansible-nginxinc-nginx

Run command
ansible-galaxy search --author vbotka

##### EXPECTED RESULTS
I expect to see the same list of roles at Galaxy and CLI.

##### ACTUAL RESULTS
Malformed role ansible-nginxinc-nginx is present at Galaxy. No such roles is present among roles listed by CLI.
```

```

**Comment by chouseknecht** [comment]
@vbotka 

The role in question is not found because the import failed. Take a look at: https://galaxy.ansible.com/my-imports?namespace=vbotka&selected=376984&page_size=10

**Comment by vbotka** [comment]
> @vbotka
> 
> Also, looks like you set the role name to `nginx`: https://github.com/vbotka/ansible-nginxinc-nginx/blob/master/meta/main.yml#L3

Not me. NGINX, Inc.did it.
https://github.com/nginxinc/ansible-role-nginx/blob/master/meta/main.yml

The point is "how to get rid of https://galaxy.ansible.com/vbotka/ansible-nginxinc-nginx"?

**Comment by chouseknecht** [comment]
@vbotka 

It can be deleted on My Content. From the list of content associated with the `vbotka` namespace, click on the drop-down menu all the way to the right of `ansible-nginxin-nginx`.  See the attached screen shot. 

![delete-repo](https://user-images.githubusercontent.com/1282865/52961699-8952d300-3369-11e9-928b-d9030186979c.png)


I went ahead and deleted the `ansible-nginx-nginx` role for you.

**Comment by chouseknecht** [comment]
@vbotka 

Can we close this issue?

**Comment by vbotka** [comment]
> @vbotka
> 
> Can we close this issue?

Sure. Go ahead. Thank you for the assistance!
