### ISSUE TITLE
UI: A list of additional content is displayed incorrectly

### ISSUE THREAD

**Issue by kbugaienko** [ansible/galaxy#1571]
##### SUMMARY
When user goes to the “Author's profile” page, a list of additional content is displayed incorrectly, only if there is no field "Score".

##### STEPS TO REPRODUCE

1. Select “Search” page.
2. Find a user “dj-wasabi”  or “UnderGreen”.
3. Click on user’s image to view more content from “dj-wasabi”.

##### ACTUAL RESULTS
![screen_shot_2019-02-17](https://user-images.githubusercontent.com/3986911/52918242-2de6fd80-32f5-11e9-819f-74343f61a316.jpg)

![screen_shot_2019-02-17-2](https://user-images.githubusercontent.com/3986911/52918386-af8b5b00-32f6-11e9-8c6e-4ee305b4ce20.jpg)

**Comment by newswangerd** [comment]
Scores aren't displayed when an item doesn't have a score (as is the case here). We addressed some of the problems with clutter here in 3.2 by removing the github stats (watchers, stars, forks). Items still don't quite line up correctly when the score is missing, but that's unfortunately just how patternfly lists work.

Eventually these list items will be replaced by something that looks a little more like what's on the search page.
