### ISSUE TITLE
Unable to publish roles under organization namespace

### ISSUE THREAD

**Issue by michaltomczuk** [ansible/galaxy#1575]
## Namespace Request

We would like to publish our Ansible roles under organization namespace. Namespace `ZeroDowntime` is already created and owned by `michaltomczuk`. Its synced with GitHub orgzanization but there is no `add content` button on organization level. Also I cannot add users (admins) to `zerodowntime` orgaznization only to my personal namespace. 

##### Github Org Link
https://github.com/zerodowntime

##### Admins
michaltomczuk
kotewa
stawii

**Comment by chouseknecht** [comment]
The Namespace `ZeroDowntime` now exists in Galaxy with the specified owners. Please let us know, if you run into any problems.

Thanks for reaching out to us!
