### ISSUE TITLE
Add New Organization Namespace

### ISSUE THREAD

**Issue by MyNameIsCosmo** [ansible/galaxy#1576]
##### Github Org Link
https://github.com/hxr

##### Admins
@mynameiscosmo
@lucidone

**Comment by MyNameIsCosmo** [comment]
For future reference, is there any better way to do this?
I did not see any issues/projects that addressed namespaces in the future.

**Comment by chouseknecht** [comment]
@MyNameIsCosmo 

This is the right way to request a Namespace in Galaxy. In hopes of protecting copyrights and trademarks, we do not allow creation of namespaces. 

The new namespace `xhr` has been added with you as the owner. I don't see a `LucidOne` user in Galaxy. That person will need to log into Galaxy, and then you can add them to the list of owners.

Thanks for reaching out to us!

**Comment by MyNameIsCosmo** [comment]
@chouseknecht 
Thank you for clarifying.

Would you be able to rename the workspace from `xhr` to `hxr`?
I should have clarified in the original listing, I read it wrong this morning as well.

Noted on the adding owners.

**Comment by MyNameIsCosmo** [comment]
bump
