### ISSUE TITLE
Request a Namespace (IFB)

### ISSUE THREAD

**Issue by dbenaben** [ansible/galaxy#1589]
## Namespace Request

Can you please create a new namespace for organization **IFB** (Institut Français de Bioinformatique) or maybe francebioinformatique, or otherwise IFBelixirFR.

##### Github Org Link
https://github.com/IFB-ElixirFr/

##### Admins
julozi
lecorguille
dbenaben

Thank you!

**Comment by chouseknecht** [comment]
New namespace [ifb](https://galaxy.ansible.com/ifb) created. Thanks for reaching out to us!

**Comment by dbenaben** [comment]
Thank you !
