### ISSUE TITLE
Output of import process lost important information

### ISSUE THREAD

**Issue by ironfroggy** [ansible/galaxy#1590]
##### SUMMARY
Integration tests started failing yesterday and the problem was tracked down to a change in the output of the import process. Specifically, the output logging changed from messages of `===== IMPORTING ROLE: FOOBAR =====` to `===== LOADING ROLE =====`, breaking tests that depend on this output to monitor and confirm the results of the import and removing the information about what was actually imported entirely (the name isn't even included anymore).

This also *retroactively* changes every previously released version of `ansible-galaxy`, which pipes the task output to the user. Because of this broad retroactive change I'm filing this as a bug because I don't think that scope was considered and, even if this change is deemed necessary, the scope of the change needs a quick conversation to decide if that's the change or if this is a regression that needs to change.

##### STEPS TO REPRODUCE
On `devel` branch import any content with `ansible-galaxy` and look at the output or the import log in the Galaxy UI.

##### EXPECTED RESULTS
Log output including lines like `===== IMPORTING ROLE: FOOBAR =====` indicating imported roles.

##### ACTUAL RESULTS
Log output including lines like `===== LOADING ROLE =====` indicating something was loaded, but not indicating what, and changing the format breaking user expectations and any processes parsing the output.

**Comment by ironfroggy** [comment]
Relevant recent change: https://github.com/ansible/galaxy/pull/1583/files#diff-90b3bc25b7b3ebe0a81ea2c9ae2736b6R116

**Comment by awcrosby** [comment]
In PR #1583 we moved validation of the role from the celery worker to the importer (things like `Checking role platforms`), so at the time of `===== LOADING ROLE =====` we have not loaded the name of the content.

We could add back in the `===== IMPORTING ROLE: FOOBAR =====`. The downside is there will be no messages under that heading such as `Checking role platforms` so it will take up extra space in the importer output, especially on collections with many pieces of content.
