### ISSUE TITLE
API can fail to find a role that does have a page on Ansible Galaxy

### ISSUE THREAD

**Issue by Porkepix** [ansible/galaxy#1597]
##### SUMMARY
I was pointed out to a role page that failed to install through `ansible-galaxy` so I digged into the issue. `ansible-galaxy install -vvv` pointed me to the API link that ended up showing me it didn't found the role.

##### STEPS TO REPRODUCE
First, check https://galaxy.ansible.com/telus/taiga to verify the role is known by Ansible Galaxy.
Then, check https://galaxy.ansible.com/api/v1/roles/?owner__username=telus&name=taiga which is the link `ansible-galaxy` binary is trying to get the role from and fail to. You'll notice that the API didn't found the role.

##### EXPECTED RESULTS
API should reflect what the user can see on Ansible Galaxy website.

**Comment by chouseknecht** [comment]
@Porkepix 

Thanks for reporting this. The role is definitely in the database, [link to role](https://galaxy.ansible.com/api/v1/roles/?name=taiga). Not sure why the client can't find it. Will poke around and see what I can find.

**Comment by chouseknecht** [comment]
@Porkepix 

The role `telus.taiga` had not been imported since way before Galaxy v3.0 released. I suspect something got lost during data conversion at that time. 

I ran a new import on the role. It imported successfully, and I can now successfully install it. Here's the results of an install on my local machine:

```
ansible-galaxy install telus.taiga
- downloading role 'taiga', owned by telus
- downloading role from https://github.com/telus/ansible-taiga/archive/master.tar.gz
- extracting telus.taiga to /Users/chouseknecht/roles/telus.taiga
- telus.taiga (master) was installed successfully
- adding dependency: telusdigital.upstart
- adding dependency: telusdigital.python
- adding dependency: telusdigital.nginx
- adding dependency: telusdigital.postgresql
- adding dependency: telusdigital.logrotate
- downloading role 'upstart', owned by telusdigital
- downloading role from https://github.com/telus/ansible-upstart/archive/master.tar.gz
- extracting telusdigital.upstart to /Users/chouseknecht/roles/telusdigital.upstart
- telusdigital.upstart (master) was installed successfully
- dependency telusdigital.logrotate already pending installation.
- downloading role 'python', owned by telusdigital
- downloading role from https://github.com/telus/ansible-python/archive/master.tar.gz
- extracting telusdigital.python to /Users/chouseknecht/roles/telusdigital.python
- telusdigital.python (master) was installed successfully
- downloading role 'nginx', owned by telusdigital
- downloading role from https://github.com/telus/ansible-nginx/archive/master.tar.gz
- extracting telusdigital.nginx to /Users/chouseknecht/roles/telusdigital.nginx
- telusdigital.nginx (master) was installed successfully
- adding dependency: telusdigital.apt-repository
- dependency telusdigital.logrotate already pending installation.
 [WARNING]: - dependency telusdigital.python from role telusdigital.nginx differs from already installed version (master), skipping

- downloading role 'postgresql', owned by telusdigital
- downloading role from https://github.com/telus/ansible-postgresql/archive/master.tar.gz
- extracting telusdigital.postgresql to /Users/chouseknecht/roles/telusdigital.postgresql
- telusdigital.postgresql (master) was installed successfully
- dependency telusdigital.apt-repository already pending installation.
- dependency telusdigital.logrotate already pending installation.
- downloading role 'logrotate', owned by telusdigital
- downloading role from https://github.com/telus/ansible-logrotate/archive/master.tar.gz
- extracting telusdigital.logrotate to /Users/chouseknecht/roles/telusdigital.logrotate
- telusdigital.logrotate (master) was installed successfully
- downloading role 'apt-repository', owned by telusdigital
- downloading role from https://github.com/telus/ansible-apt-repository/archive/master.tar.gz
- extracting telusdigital.apt-repository to /Users/chouseknecht/roles/telusdigital.apt-repository
- telusdigital.apt-repository (master) was installed successfully
```

**Comment by chouseknecht** [comment]
@Porkepix 

I think we can close this issue. Please comment or close, if you agree. Thanks!

**Comment by Porkepix** [comment]
What do you mean by "imported" here? I already noticed the field on Ansible Galaxy's website, but without being able to figure out what was it involving.
In the example of the current case, I'm also quite curious about how is the website determining the minimum Ansible version as it's not in the `meta/main.yml`
I'm also quite curious about how can it find the roles it depends on: it's not in the repository where to find those either and it's not found on Ansible's website.

As for the issue, I guess it's solved, yeah.

**Comment by AllenJB** [comment]
I have what appears to be the same issue with https://galaxy.ansible.com/computology/packagecloud (using ansible-galaxy 2.7.5 on CentOS 7.6)

If a package can't be installed via the ansible-galaxy command, I'd expect it to at least not display the "Installation" command, and better yet display some sort of notice / warning.

**Comment by chouseknecht** [comment]
@AllenJB there are no owners on the `computology` namespace in Galaxy. Tried to add you, but not finding you in Galaxy users. You may need to log into Galaxy using your GitHub credentials. That should create your user account, and then we can add you.

**Comment by chouseknecht** [comment]
@AllenJB as an admin I was able to import the `packagecloud` role, and verified that I can install it via `ansible-galaxy install computology.packagecloud`.

**Comment by chouseknecht** [comment]
@Porkepix 

Not sure why the dependencies work. I would not expect them to either, but there must be something in how the data got converted. The right thing to do would be to update the list of dependencies in the `meta/main.yml` file. I'm not inclined to go poking around in the Galaxy database and potentially make things worse.

As for the `min_ansible_version`, guessing that if you don't specify one, we're defaulting to `2.4`.
