### ISSUE TITLE
https://galaxy.ansible.com favicon is low DPI (www.ansible.com one fine)

### ISSUE THREAD

**Issue by tim-seoss** [ansible/galaxy#161]
Very minor niggle - the favicon (e.g. as displayed in Chrome for tabs under https://galaxy.ansible.com ) is low DPI.  The ones used by http://docs.ansible.com/ and https://www.ansible.com/ are both high DPI (although a bit different from each other, strangely).

So the Galaxy ones look pixelated on a 4k (or other high DPI) display.

**Comment by cchurch** [comment]
FYI, additional info on what's missing from a site I've used to create favicons: https://realfavicongenerator.net/favicon_checker?protocol=https&site=galaxy.ansible.com

**Comment by cutwater** [comment]
@cchurch Thanks for suggestion, it's really useful resource.

**Comment by cutwater** [comment]
`favicon.ico` has been replaced with multisize version. Fix will land on https://galaxy.ansible.com in the next release.

**Comment by chouseknecht** [comment]
@cutwater 

Got it to be all green!

https://realfavicongenerator.net/favicon_checker?protocol=https&site=galaxy-qa.ansible.com#.WiG5vLQ-eV5
