### ISSUE TITLE
ansible galaxy project rename

### ISSUE THREAD

**Issue by karljohns0n** [ansible/galaxy#1610]
Hello, 

A GitHub issue seems to be the place to ask for a rename. Could you please rename the following project:

ansible_role_nginx_more -> nginx-more

So the role will be karljohns0n.nginx-more

Thanks! It would be great if we can set this at the first import.

Karl

**Comment by chouseknecht** [comment]
@karljohns0n 

The repository and content have been renamed to `nginx-more` as requested. You can [view the role here](https://galaxy.ansible.com/karljohns0n/nginx-more)
