### ISSUE TITLE
Allow manual url for Travis badge

### ISSUE THREAD

**Issue by rockandska** [ansible/galaxy#1617]
### Use Case
It seems that the Travis badge is only available when using "notification" webhook.
I personally don't use the notification due to the fact we can't trigger it only on tag for example, so i add in my CI, an import through the ansible-galaxy CLI to only trigger import when i push a new tag and avoid to see any update on galaxy every time a build is triggered ( even if it is better since #1460, i only want to see import done when want it to ).
But my workflow have a disadvantage, not having the travis badge on search result :(

### Proposed Solution
Having a repository parameter to get a build badge from an url, corresponding to : 
- a branch
- or the last tag shown in "version"

This way, even if the user doesn't use the Travis notification (or Travis itself), a user will be able to link a badge corresponding to the build he want

**Comment by chouseknecht** [comment]
Don't think we're going to continue iterating on traditional Ansible Roles being imported from GitHub repositories. The future is hosted artifacts using the new Ansible Collection format.
