### ISSUE TITLE
Collections return unhelpful message when uploading artifiacts with incorrect namespace.

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy#1619]
This should say something along the lines of "can't upload collections from other namespaces."

<img width="625" alt="image" src="https://user-images.githubusercontent.com/6063371/53809407-addeab80-3f22-11e9-9266-fb53f39c3829.png">

Need to either change the API response or add a check in the UI on the file name with a more descriptive error.

**Comment by chouseknecht** [comment]
@newswangerd 

IMHO, we should modify the message returned by the API
