### ISSUE TITLE
Refactor existing models to work with collections

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy#1620]
Surveys and user preferences both have foreign key dependencies on repositories. We need to add similar dependencies for collections

Preferences
- [x] Add followed collections to `UserPreferences` model
  - [x] Update API with collections followed
  - [x] Update User preferences page
  - [x] Update content detail view follow functionality

Surveys
- [x] Add foreign key for collections to community survey
  - [x] Add `CollectionSurvey` endpoint
  - [x] Refactor community survey on content detail to handle surveys for collections
  - [x] Refactor user notifications

**Comment by chouseknecht** [comment]
User notifications is being worked in #1803
