### ISSUE TITLE
Option for hiding email address

### ISSUE THREAD

**Issue by marcobellaccini** [ansible/galaxy#1621]
### Use Case
It seems like there's no way for users using GitHub OAuth integrated sign-in to prevent their email address from showing up in Galaxy author's page (the one accessible at *https://galaxy.ansible.com/[USERNAME]*).

Apart from the privacy implications, the email address appears in plain form in a *mailto* link, exposing users addresses to spammers. 

### Proposed Solution
It would be nice to have an option to hide the email address (and it would be good to have it enabled by default).

**Comment by newswangerd** [comment]
Hi @marcobellaccini. You can remove your email by going to https://galaxy.ansible.com/my-content/namespaces and selecting 'Edit Namespace' from the little drop down menu next to the Add Content button. From there just delete the email address from the form and hit save.

What you're actually seeing when you go to https://galaxy.ansible.com/[USERNAME] is your namespace, not your user account. The Namespace email is just used for display purposes so you're free to delete it or change it to whatever you want.

**Comment by marcobellaccini** [comment]
Thank you @newswangerd!
That was not so straightforward...
I definitely agree with you on https://github.com/ansible/galaxy/issues/1625: Galaxy behavior should be consistent with GitHub email privacy settings by default.
I'm closing this issue.

Cheers

Marco
