### ISSUE TITLE
Can't add collections to namespaces with dashes in them

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy#1622]
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/6063371/53825163-aaa7e780-3f43-11e9-970c-144141af7501.png">

**Comment by cutwater** [comment]
This is expected behavior. According to the spec dash is used as namespace \ name \ version delimiter and namespaces should be python compatible names. Therefore malformed namespace names are not supported by collections.
