### ISSUE TITLE
Respect GitHub private email settings when creating a new user.

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy#1625]
Git Hub has an option to keep the user's email private.

<img width="763" alt="image" src="https://user-images.githubusercontent.com/6063371/53827715-c1e9d380-3f49-11e9-84b0-ad4330c285ba.png">

When a user logs into galaxy for the first time we create a namespace for them and set their new namespace's email to the email provided from Git Hub. If the user has selected private emails or doesn't have an email on display on their profile we should respect that and leave their namespace's email blank.

Related: #1621

**Comment by chouseknecht** [comment]
Since we can't really tell from [the GitHub API response](https://developer.github.com/v3/users/#response-with-public-and-private-profile-information) what the user's private preferences are, let's set the Namespace email property to a blank or None value.

**Comment by ironfroggy** [comment]
Should we do anything about all the users already existing with exposed emails?
