### ISSUE TITLE
DragonFly BSD missing from the list of platforms

### ISSUE THREAD

**Issue by tuxillo** [ansible/galaxy#1633]
### Use Case
DragonFly BSD missing from the list of platforms. (www.dragonflybsd.org)

### Proposed Solution
Add DragonFly BSD missing from the list of platforms.

Platform: DragonFly BSD
Releases: 5.2, 5.4, master

* For 'master' which is the current HEAD I don't know how you guys handle that one for other platforms.

### Alternatives
N/A

### Implementation
N/A

**Comment by chouseknecht** [comment]
Requested platforms added. You can [view them here](https://galaxy.ansible.com/api/v1/platforms/?name=DragonFlyBSD).

Thanks for reaching out!
