### ISSUE TITLE
New Pacifica Namespace

### ISSUE THREAD

**Issue by dmlb2000** [ansible/galaxy#1638]
##### Github Org Link
https://github.com/pacifica
##### Admins
@dmlb2000 @Gitbytes

Primarily it would be useful for loading the pacifica ansible role https://github.com/pacifica/ansible-pacifica.git

**Comment by chouseknecht** [comment]
Created namespace `pacifica` with user `dmlb2000` as the owner. Could not find an account in Galaxy for `GitBytes`. Once that person logs into Galaxy, you can add them.

Thanks for reaching out to us!

**Comment by dmlb2000** [comment]
@chouseknecht Thanks for adding this, however I'm not seeing the Github Pacifica organization to add content, I may have forgot to enable that organization when I created my account. How do I add authorization for you to access additional Github organizations?

**Comment by dmlb2000** [comment]
@chouseknecht I think I figured it out, thanks.
