### ISSUE TITLE
Transfer Role to new (repo) owner

### ISSUE THREAD

**Issue by ahuffman** [ansible/galaxy#1646]
Is there any way in Galaxy to transfer the ownership from one namespace to another?  I haven't found anything in the documentation on this topic, and I'm sure it probably comes up from time to time.

A repo owner recently transferred ownership to me on github, but I'm still seeing the role (in my galaxy account) under their namespace, while the github repository has been fully transferred to my account.

Thanks!

**Comment by chouseknecht** [comment]
@ahuffman 

Can you provide the current namespace.role and the desired namespace.role. Thanks!

**Comment by ahuffman** [comment]
wtcross/sudoers <-old namespace 
ahuffman/sudoers <- new namespace

**Comment by chouseknecht** [comment]
There's no button to press for changing ownership. Have you attempted to import `ahuffman/sudoers`?

As far as the old one, Tyler can delete it, or we can delete it.

**Comment by ahuffman** [comment]
@chouseknecht the repository does not show under my namespace for whatever reason, and only shows the additional wtcross namespace with the repository under it.  I'd hate to delete because we would lose our collective download stats on the project.

**Comment by chouseknecht** [comment]
@ahuffman 

To add it to the `ahuffman` namespace, go to My Content, and next to the `ahuffman` namespace, all the way to the right, click Add Content. This will cause a pop-up window to display, where you can select the `ahuffman/ansible-sudoers` repository. See the attached screenshot

![ahuffman](https://user-images.githubusercontent.com/1282865/54761495-95c88680-4bc8-11e9-9628-d5331e954e81.png)

Selecting the repository will initiate an import.

**Comment by ahuffman** [comment]
Ah, there it is.  Thanks.  

Unfortunately that just re-imports under a new namespace.  It does not offer any ability to transfer the existing import to my namespace even though it comes out of the same repo.  

I've deleted the old import of the role in the wtcross namespace, but that essentially caused us to lose all of our download statistics, which is a big deal when you're searching for roles by relevance.  Just putting it out there that there really should be some method of transferring roles if a repo is transferred to another github user.  Feel free to close this if necessary, but I think it would be good to have a conversation on how to prevent this issue from happening in the future.

**Comment by chouseknecht** [comment]
Doesn't seem there's much else to do here. At some point we *may* consider adding a 'transfer' feature; however, our focus is on moving toward collections and Galaxy hosted artifacts, and we all know that download count is only marginally meaningful.
