### ISSUE TITLE
Update ROADMAP.md

### ISSUE THREAD

**Issue by ironfroggy** [ansible/galaxy#1648]
##### SUMMARY
The `ROADMAP.md` document appears to be outdated, not reflected the last major release 3.1 or outlining the upcoming 3.2 release.

##### STEPS TO REPRODUCE
Read the document.

##### EXPECTED RESULTS
Information about what was released in 3.1 and what is expected to be released in 3.2.

##### ACTUAL RESULTS
Information about 3.1 as if it hadn't been released yet (so it isn't clear if this is accurate) and no mention of current work or roadmap.

**Comment by chouseknecht** [comment]
We'll get to it.
