### ISSUE TITLE
Request to add Namespace Gavika

### ISSUE THREAD

**Issue by bngsudheer** [ansible/galaxy#1651]
## Namespace Request
Gavika

##### Github Org Link
https://github.com/Gavika

##### Admins
bngsudheer

**Comment by chouseknecht** [comment]
Done. Thanks for reaching out to us!

**Comment by bngsudheer** [comment]
Thanks. But when I click on the arrow next to the folder `gavika`, I get this error:

```Error! Query repository failed: ('' value must be an integer.) 
```
I am unable to add the repositories under the new namespace. If the namespace is case-sensitive, it should be `Gavika` instead of `gavika`.

**Comment by bngsudheer** [comment]
I renamed the organization on Github to match the name `gavika` and it worked.
