### ISSUE TITLE
Please create namespace `epfl-idevelop`

### ISSUE THREAD

**Issue by domq** [ansible/galaxy#1665]
##### Github Org Link

https://github.com/epfl-idevelop/

##### Admins

domq
edbugnion
ponsfrilus
multiscan

**Comment by chouseknecht** [comment]
@domq 

Namespace `epfl_idevelop` created. Note that Galaxy does not allow `-` in the name. 

Added users `domq` and `ponsfrilus` as owners. The other two usernames do not exist in Galaxy. Once they log into Galaxy for the first time, you can modify the namespace and add them.

Thanks for reaching out to us! Please let us know, if you run into any issues.

**Comment by ponsfrilus** [comment]
@chouseknecht Thanks !
