### ISSUE TITLE
Namespace Request b1-systems

### ISSUE THREAD

**Issue by netzvieh** [ansible/galaxy#1675]
## Namespace Request
When I try to add the namespace from my available provider namespaces to the selected one I get:

> Error! This provider namespace is already associated with a Galaxy namespace (b1-systems) 

##### Github Org Link

https://github.com/b1-systems

##### Admins

netzvieh https://galaxy.ansible.com/netzvieh

Thanks!

**Comment by chouseknecht** [comment]
@netzvieh you're now an owner of `b1-systems` on Galaxy
