### ISSUE TITLE
Can I have a namespace to import to?

### ISSUE THREAD

**Issue by mikejonesey** [ansible/galaxy#1676]
## Namespace Request
I can't seem to publish content to ansible-galaxy, Can't view my content either since having to login with github.

Through the web interface, under my content, I only see "No Items Available" (so i guess i need to request a namespace)?

`$ ansible-galaxy -vvvvvv import --branch master mikejonesey blinkstick-zabbix
Using /etc/ansible/ansible.cfg as config file
Opened /home/mike/.ansible_galaxy
Initial connection to galaxy_server: https://galaxy.ansible.com
Base API: https://galaxy.ansible.com/api/v1
https://galaxy.ansible.com/api/v1/imports/
ERROR! Permission denied.
`

##### Github Org Link
Do I need an "organisation" in github?

https://github.com/mikejonesey

https://galaxy.ansible.com/mikejonesey

##### Admins
me

**Comment by chouseknecht** [comment]
There was already a `mikejonesey` namespace on Galaxy. Probably brought over during the v3.0 migration / data conversion, but you were not set as the owner.

You're now the owner, and you should be able to import content. Try using logging in through the web site, and going to My Content.
