### ISSUE TITLE
ansible-galaxy update

### ISSUE THREAD

**Issue by wardcomm** [ansible/galaxy#1711]
## Feature Request

ansible-galaxy update switch to update local working copy to git hub using ansible-galaxy
### Use Case

this will use ansible-galaxy to update roles locally from the files that are on github which galaxy.ansible.com is connected to

### Proposed Solution

I want to  be able to type
ansible-galaxy update wardcomm.kerberos_client
and it will go out and update changes that are in git hub

### Alternatives

don't know of any

### Implementation
add the switch that will tell galaxy.ansible to go update with github for this role and send changes back to where you type in the command ansible-galaxy update wardcomm.kerberos_client

**Comment by chouseknecht** [comment]
@wardcomm 

We're not currently adding new features to `ansible-galaxy`. An `update` command will be added to [Mazer](https://github.com/ansible/mazer) client at some point.
