### ISSUE TITLE
Rename account on Ansible Galaxy to match Github

### ISSUE THREAD

**Issue by aemdesign** [ansible/galaxy#1712]
Hi Galaxy Admins and @chouseknecht !

I have same issue as a few people have had 😭 

I have changed by github username: 
devops_aemdesign -> aemdesign

Is there a way for me to update Galaxy to reflect this? 😃 

Thanks a lot and keep up the great tool! no1 fan! 🥇

**Comment by wildone** [comment]
oh that was me posting this 😄 
on the other hand is it possible to delete an account from ansible galaxy?

**Comment by chouseknecht** [comment]
@wildone 

Removed user `devops-aemdesign` from Galaxy. The username `wildone` exists, and has been added to the `devops_aemdesign` namespace.
