### ISSUE TITLE
Rename workspace devops_aemdesign -> aem-design

### ISSUE THREAD

**Issue by wildone** [ansible/galaxy#1723]
Rename namespace [devops_aemdesign](https://galaxy.ansible.com/devops_aemdesign) to [aem-design](https://github.com/aem-design)

##### Admins
wildone
aemdesign

**Comment by chouseknecht** [comment]
Renamed to `aem_design`. 

Galaxy does not allow `-` in Namespace names. This is due to coming changes in how Ansible content will be installed and consumed. In a nut shell, names must be Python compatible.
