### ISSUE TITLE
Unable to login - Server Error (500) 

### ISSUE THREAD

**Issue by plschubert** [ansible/galaxy#1724]
SUMMARY

I get Server Error (500) every i try to login.
STEPS TO REPRODUCE

    Go to page: https://galaxy.ansible.com/accounts/login/
    Input Email and Password (patrick.schubert@atos.net)
    I get 500 server error

EXPECTED RESULTS

Logged in

**Comment by chouseknecht** [comment]
@plschubert 

I assume when you say, "Input Email and Password", you're authenticating with GitHub. I don't see a `plschubert` account in Galaxy.

My guess is that you may not have the correct permissions granted to the Ansible Galaxy OAuth App. If you go into your GitHub Settings, Applications, you can view the permissions granted to Galaxy. They should include "Access Public Repositories", "Read org and team membership, read org projects", and "Access user email addresses (read-only)".

If that's not the case, you need to delete the app, attempt to login again, and grant the requested permissions.

**Comment by plschubert** [comment]
Hi,

the permission in my github account look like this: 

![galaxy](https://user-images.githubusercontent.com/22399623/55933062-4a841f80-5c2c-11e9-879c-f6e4c50674b4.PNG)

I tried deleting the app and retrying, but the error still persists. 

The login page looks like this:
![galaxy 2](https://user-images.githubusercontent.com/22399623/55933236-e7df5380-5c2c-11e9-9442-f2e964377d72.PNG)

And after logging in I get:

![galaxy 3](https://user-images.githubusercontent.com/22399623/55933245-f0d02500-5c2c-11e9-87e4-8b5d69417c1d.PNG)

**Comment by chouseknecht** [comment]
Hmm... You may need to refresh your browser cache or maybe disable an ad blocker? You don't seem to have the latest Javascript nor the CSS. The login page in the above comments looks very old. The current login page only shows a single option - GitHub. The screenshot above lists 3 - GitHub, Google and Twitter. It also contains username/password, which are also no longer available.

**Comment by chouseknecht** [comment]
Closing, as this appears to be resolved, and we have not heard anything more from @plschubert
