### ISSUE TITLE
automate adding new platform versions

### ISSUE THREAD

**Issue by nusenu** [ansible/galaxy#173]
Everytime a new OS version is released one has to file an issue here to add it.
Examples:
https://github.com/ansible/galaxy/issues/73
https://github.com/ansible/galaxy/issues/121
https://github.com/ansible/galaxy/issues/172

Could you automate that process?

**Comment by cutwater** [comment]
Hello @nusenu,

Thank you for your feedback. We are aware of this problem and planning to improve the process. Please use issue #80 to track it.
