### ISSUE TITLE
Unable to sign-in - Server Error (500)

### ISSUE THREAD

**Issue by tanribilir** [ansible/galaxy#1734]
##### SUMMARY
I created account on Galaxy as 'tanribilir'. Tried to bind it to my Github account but receiving Server (500) error message. 

Ansible is reported as an authorized OAuth application in Github with read permissions.

##### STEPS TO REPRODUCE
Everytime I try to login with my Github account.

```

```

**Comment by chouseknecht** [comment]
@tanribilir 

Removed the existing account from Galaxy. Please log in again using GitHub, and make sure that you leave the requested scopes checked. Galaxy does ask for `user:email` and `read:org` scopes.

**Comment by chouseknecht** [comment]
Closing, as this appears to be resolved, and we have not heard anything additional from @tanribilir
