### ISSUE TITLE
ansible galaxy: unable to install from non-master branch

### ISSUE THREAD

**Issue by ltalirz** [ansible/galaxy#1739]
##### SUMMARY

This is about installing ansible roles hosted on github via ansible galaxy.

I used to be able to install the role `marvel-nccr.aiida` directly from the `develop` branch of the [github repository](https://github.com/marvel-nccr/ansible-role-aiida) (proof in [travis logs](https://travis-ci.org/marvel-nccr/quantum-mobile/builds/518446562#L740)).
At that point in time, there was no tag/release in the github repo.

Since I've added a tag, I'm no longer able to install from the `develop` branch (installing from `master` still works for some reason).

##### STEPS TO REPRODUCE
requirements.yml
```yaml
---
- src: marvel-nccr.aiida
  version: develop
```
I'm using ansible 2.7.10.

##### EXPECTED RESULTS
As stated in the [documentation](https://galaxy.ansible.com/docs/using/installing.html#role-versions) I can install the role directly from the branch using 
`ansible-galaxy install -r requirements.yml`

##### ACTUAL RESULTS
```
$ ansible-galaxy install -r requirements.yml
- downloading role 'aiida', owned by marvel-nccr
 [WARNING]: - marvel-nccr.aiida was NOT installed successfully: - the specified version (develop) of marvel-
nccr.aiida was not found in the list of available versions ([{u'download_url': u'https://github.com/marvel-nccr
/ansible-role-aiida/archive/v0.1.0.tar.gz', u'name': u'v0.1.0', u'created': u'2019-04-13T13:23:36.298075Z', u'url':
u'', u'summary_fields': {}, u'modified': u'2019-04-13T13:23:36.298099Z', u'related': {}, u'commit_date':
u'2019-03-03T06:16:43-05:00', u'version': u'0.1.0', u'commit_sha': u'07352a8c3ee5d102fb110e9475cc1184c6f98685',
u'active': None, u'id': 91876}]).
```

The available versions listed here include only the tag v0.1.0.
For some reason, specifying `version: master` still works, however.

**Comment by chouseknecht** [comment]
Seems to be working OK with Ansible 2.7

Works with a tag...

My `requirements.yml` looks like this:
```
 src: https://github.com/marvel-nccr/ansible-role-aiida.git
  version: v0.1.0
  name: aiida
```

Here's the install:
```
ansible-galaxy install -r requirements.yml
- extracting aiida to /Users/chouseknecht/roles/aiida
- aiida (v0.1.0) was installed successfully
- adding dependency: marvel-nccr.current_user (master)
- downloading role 'current_user', owned by marvel-nccr
- downloading role from https://github.com/marvel-nccr/ansible-role-current-user/archive/master.tar.gz
- extracting marvel-nccr.current_user to /Users/chouseknecht/roles/marvel-nccr.current_user
- marvel-nccr.current_user (master) was installed successfully
```

Trying with a branch...

My `requirements.yml` looks like this:
```
 src: https://github.com/marvel-nccr/ansible-role-aiida.git
  version: develop
  name: aiida
```

Here's the install:
```
ansible-galaxy install --force -r requirements.yml
- changing role aiida from v0.1.0 to develop
- extracting aiida to /Users/chouseknecht/roles/aiida
- aiida (develop) was installed successfully
- dependency marvel-nccr.current_user is already installed, skipping.
```

**Comment by chouseknecht** [comment]
@ltalirz 

I see the issue. You're attempting to use a GitHub branch with a Galaxy role name. That's not going to work. To use a branch, you have to give the GitHub URL as the name. See my example above.

**Comment by ltalirz** [comment]
@chouseknecht Thanks for looking into this and for the workaround by specifying the github URL!

> You're attempting to use a GitHub branch with a Galaxy role name. That's not going to work. To use a branch, you have to give the GitHub URL as the name.

Please note that the travis log I linked above seems to prove that it actually *did* work before I introduced a tag in the git repository:

 * link to [`requirements.yml`](https://github.com/marvel-nccr/quantum-mobile/blob/020b4e1a94169e3d60abdf880749850b456ba0c5/requirements.yml#L34-L35)
 * link to [travis log](https://travis-ci.org/marvel-nccr/quantum-mobile/builds/518446562#L740)

Perhaps this is not by design - still, I would say this behavior is rather unexpected from a user perspective.

**Comment by ltalirz** [comment]
The relevant code is this:
https://github.com/ansible/ansible/blob/aa8d23b42f82dd48c5929f7c62e71f2a93861103/lib/ansible/galaxy/role.py#L238-L240

On the surface the logic seems fine.
What I wonder is: what does the github API return for `role_versions` if there are no tags defined? Does it perhaps return the branch names?

The code also explains why specifying `master` still works (this case is considered "special").
