### ISSUE TITLE
https://galaxy.ansible.com site has different `favicon.ico` icons

### ISSUE THREAD

**Issue by cutwater** [ansible/galaxy#174]
Public site http://galaxy.ansible.com uses two different icons:

* `/favicon.ico`
* `/static/img/favicon.ico`

**Comment by chouseknecht** [comment]
I think this has been resolved. During the deployment process, we copy `/static/img/favicon.ico` to the site root.

**Comment by cutwater** [comment]
I confirm, issue has been resolved.

https://realfavicongenerator.net/favicon_checker?protocol=https&site=galaxy.ansible.com
