### ISSUE TITLE
yamllint reports errors and warnings after ansible-galaxy init

### ISSUE THREAD

**Issue by jkirk** [ansible/galaxy#1759]
##### SUMMARY
yamllint reports errors and warnings after `ansible-galaxy init`

##### STEPS TO REPRODUCE
```sh
jkirk@executor ~proj/misc % ansible-galaxy init ansible-role-galaxytest                                                                                                                                             
- ansible-role-galaxytest was created successfully
jkirk@executor ~proj/misc % cd ansible-role-galaxytest
jkirk@executor ~proj/misc/ansible-role-galaxytest % yamllint meta/main.yml 
meta/main.yml
  1:1       warning  missing document start "---"  (document-start)
  21:81     error    line too long (84 > 80 characters)  (line-length)
  27:81     error    line too long (81 > 80 characters)  (line-length)
  30:4      warning  missing starting space in comment  (comments)
  33:81     error    line too long (84 > 80 characters)  (line-length)
  34:81     error    line too long (85 > 80 characters)  (line-length)
  51:5      warning  comment not indented like content  (comments-indentation)
  51:81     error    line too long (83 > 80 characters)  (line-length)
  52:81     error    line too long (82 > 80 characters)  (line-length)
  55:81     error    line too long (83 > 80 characters)  (line-length)
  59:3      warning  comment not indented like content  (comments-indentation)
  59:81     error    line too long (85 > 80 characters)  (line-length)
  60:42     error    no new line character at the end of file  (new-line-at-end-of-file)

jkirk@executor ~proj/misc/ansible-role-galaxytest % ansible-galaxy --version
ansible-galaxy 2.7.8
  config file = /home/jkirk/.ansible.cfg
  configured module search path = [u'/home/jkirk/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jkirk/software/venv/local/lib/python2.7/site-packages/ansible
  executable location = /home/jkirk/software/venv/bin/ansible-galaxy
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]

jkirk@executor ~proj/misc/ansible-role-galaxytest % yamllint -v    
yamllint 1.11.1
```

##### EXPECTED RESULTS
I would at least expect no errors (although I am not sure if more than 80 characters are really that bad). But still, having a clean `yamllint meta/main.yml` output would be nice.

This also affects `molecule lint` (see: [Molecule](https://molecule.readthedocs.io/en/stable/))

**Comment by chouseknecht** [comment]
@jkirk 

Thanks for taking the time to reach out to us. Since `ansible-galaxy` is part of the [ansible project](https://github.com/ansible/ansible), you will need to open an issue there.

I did look in the Ansible project to find the allowed line size. I found this reference in [tox.ini](https://www.redhat.com/en/blog/importance-nanosecond-remembering-grace-hopper?source=author&term=27741), and this one in the [yamllint config](https://github.com/ansible/ansible/blob/devel/test/sanity/yamllint/config/default.yml#L15). It seems that Ansible accommodates lines longer than 80 chars.

For the reasons stated above, closing this issue. If you feel it's appropriate, please open an issue at the Ansible project.

**Comment by jkirk** [comment]
@chouseknecht 

Thanks for your feedback. I filed the issue ansible/ansible#56546.

(JFTR: I liked the story about Grace Hopper in your `tox.ini` reference, but I think actually meant [this](https://github.com/ansible/ansible/blob/867e357eb14cf0c2d91bd9ee734b26f7a1c0c058/tox.ini#L32), right?)
