### ISSUE TITLE
ansible-galaxy import not giving enough error message to fix

### ISSUE THREAD

**Issue by wardcomm** [ansible/galaxy#1764]
first error message:
Failed 2 minutes ago

if you click on that you get this error:
Starting import: task_id=415092, repository=wardcomm/windows_update

Task "415092" failed: expected string or buffer

my github is project that i am trying to import is:
https://github.com/wardcomm/windows_update

**Comment by wardcomm** [comment]
runnning in cli i get:
sudo ansible-galaxy import wardcomm windows_update --status -vvv
-------------------------------------
ansible-galaxy 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-galaxy
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /etc/ansible/ansible.cfg as config file
Opened /root/.ansible_galaxy
https://galaxy.ansible.com/api/v1/imports/?github_user=wardcomm&github_repo=windows_update
https://galaxy.ansible.com/api/v1/imports/?id=415092
Starting import: task_id=415092, repository=wardcomm/windows_update

Task "415092" failed: expected string or buffer

**Comment by awcrosby** [comment]
@wardcomm as a workaround if you put quotes around your meta/main.yml numeric galaxy_tags: `"2016"` and `"2019"` then the import should succeed. Our next release should not fail import for this case. Thanks for reporting!

**Comment by wardcomm** [comment]
That worked 100% I wish the error said something like that. Thank you very much.
