### ISSUE TITLE
 IMPORTER101: Invalid platform: "windows-2019", skipping.

### ISSUE THREAD

**Issue by wardcomm** [ansible/galaxy#1767]
I am getting this metadata error:
1IMPORTER101:
Invalid platform: "windows-2019", skipping.
=================================
meta/main.yml looks like this
-------------------------------------------------------------
---
galaxy_info:
  author: wardcomm
  description: Windows Updates For Windows Server 2016
  company: jchadward.com
  license: MIT
  min_ansible_version: 2.1
  role_name: windows_update
  platforms:
  - name: windows
    versions:
      - 2016
      - 2019
  galaxy_tags:
    - windows
    - update
    - "2016"
    - "2019"
dependencies: []
----------------------------------------------------------

github location
https://github.com/wardcomm/windows_update
ansible galaxy location
https://galaxy.ansible.com/wardcomm/windows_update

**Comment by chouseknecht** [comment]
@wardcomm 

Release `2019` added, finally. Apologies for the delay.
