### ISSUE TITLE
"Scroll to end of log" breaks import navigation on My Imports page

### ISSUE THREAD

**Issue by ironfroggy** [ansible/galaxy#1770]
##### SUMMARY
Using the "Scroll to end of log" icon to quickly go to the end of an import log causes navigation to any other imports on the My Import page to break, wiping the contents of the page and leaving the page in a stuck state. Clicking to go back to "My Imports" does not work, only refreshing or navigating away and back restores functionality.

##### STEPS TO REPRODUCE
- Import more than one repository or collection
- Scroll to the bottom of one import log with the down arrow icon at the top of the log
- Try to navigate to the other import log by clicking it in the list to the left of the log

##### EXPECTED RESULTS
I expect to go read the other import log available to me

##### ACTUAL RESULTS
The contents of the page are gone. Only the top bar and left-hand navigation remain.

![galaxy-import-nav-failure](https://user-images.githubusercontent.com/34982/56981992-34dc8880-6b4e-11e9-9886-5c41cc836b02.gif)

**Comment by newswangerd** [comment]
+1 for the perfectly looped gif
