### ISSUE TITLE
fix import of role with dashes in name and ansible- prefix

### ISSUE THREAD

**Issue by andrewrothstein** [ansible/galaxy#1773]
per #775 can u fix my two roles
github.com/andrewrothstein/ansible-openjdk should import as andrewrothstein/openjdk
and
github.com/andrewrothstein/ansible_restic should import as andrewrothstein/restic

thanks!

**Comment by chouseknecht** [comment]
@andrewrothstein 

You should be able to do this yourself. Delete the role, and in `meta/main.yml`, set the value of `role_name`. You can see an example here: https://galaxy.ansible.com/docs/contributing/importing.html#content-name-limitations

**Comment by andrewrothstein** [comment]
It worked. You and the team are heroes. Thank you!
