### ISSUE TITLE
setup.py build drops hidden galaxy data files (e.g. .travis.yml)

### ISSUE THREAD

**Issue by jdennis** [ansible/galaxy#1777]
This is related to https://github.com/ansible/galaxy/issues/659

The `.travis.yml` files are not getting installed and hence never get deployed by `ansible-galaxy init`. I traced the problem back to the fact the files are never picked up the by `setup.py build` command which is the starting point for creating a distribution.

The fundamental problem has to with the python glob function used by distutils to build a file list. From [python glob doc](https://docs.python.org/3/library/glob.html) it clearly states at the bottom *"If the directory contains files starting with . they won’t be matched by default."* In order to pick up hidden files (e.g. those beginning with a dot) you must explicitly specify a glob pattern like this `".*"`. Hence to pick up all the files in directory foo you need two glob patterns `"foo/*"` and `"foo/.*"`

The glob patterns for `package_data` are defined in `setup.py`, here is a snipped for the galaxy data files:

>            'galaxy/data/*/*.*',
>            'galaxy/data/*/*/.*',
>            'galaxy/data/*/*/*.*',

Note how the 2nd glob above is designed to pick up hidden files (hence someone understood the issue). However there is no hidden glob pattern that will pick up files such as

>  galaxy/data/default/.travis.yml

for that you need this additional glob:

>            'galaxy/data/*/.*',

Note: I have not examined the `package_data` in `setup.py` for any other potential missing hidden file globs. There may be other issues, I was just trying to figure out what was causing `.travis.yml` to be omitted from the galaxy skeleton.

**Comment by chouseknecht** [comment]
@jdennis 

Thanks for bringing this to our attention. This should actually be filed at [the Ansible project](https://github.com/ansible/ansible/issues).
