### ISSUE TITLE
Galaxy should use all relative urls for all Galaxy links

### ISSUE THREAD

**Issue by bmbouter** [ansible/galaxy#1778]
### Use Case
Galaxy returning full urls makes it more difficult to deploy Galaxy in various ways because the application layer now has to be aware of how its deployed including the prototcol scheme, hostname, port, and if the application is root deeper in the url namespace.

### Proposed Solution
Have Galaxy use all relative urls from the "root" of the Galaxy namespace.

### Alternatives
I don't know of any.

### Implementation
Revert this commit?  https://github.com/ansible/galaxy/commit/077c8966cff2b347fe4f89ba846d16a68ad6228d

**Comment by chouseknecht** [comment]
We debated relative vs exact (or full) URLs as a team and landed on exact. For 3.2 we're sticking with that decision. Based on input from our PM and further discussion, we may revisit this in the next release.

**Comment by bmbouter** [comment]
At this point I don't think we can change this because the V2 api is so fixed and older versions of the ansible client won't be updated to accommodate a change.
