### ISSUE TITLE
Namespace "Change" Request

### ISSUE THREAD

**Issue by ddavison** [ansible/galaxy#1805]
## Namespace Fix

In a galaxy far far away, I had created the `seleniumhq/selenium` project. https://galaxy.ansible.com/seleniumhq/selenium . 

The project *should* be, `SeleniumHQ/selenium`.

![Screen Shot 2019-05-07 at 5 27 52 PM](https://user-images.githubusercontent.com/2972876/57341164-1e09d900-70ee-11e9-8e93-0cbd39f97e3d.png)

The weird part is https://galaxy.ansible.com/seleniumhq/selenium and https://galaxy.ansible.com/SeleniumHQ/selenium both go to the Same content, even though they are different. (*the casing of SeleniumHQ vs seleniumhq*)

![Screen Shot 2019-05-07 at 5 28 05 PM](https://user-images.githubusercontent.com/2972876/57341106-e569ff80-70ed-11e9-9259-03fdb3287081.png)

The other thing is that it shows the content as `seleniumhq` when it should be `SeleniumHQ`

![Screen Shot 2019-05-07 at 5 28 16 PM](https://user-images.githubusercontent.com/2972876/57341143-0a5e7280-70ee-11e9-8d3b-ef1f8d7f14b2.png)

---

### Is there a way I can consolidate these into SeleniumHQ?

**Comment by chouseknecht** [comment]
@cutwater 

We need to prevent this from happening in the future. When a new namespace is added, the uniqueness check should be case insensitive. In other words, `SeleniumHQ` and `selenium` should match, and only one instance should get created.

**Comment by chouseknecht** [comment]
@ddavison 

I deleted the `seleniumhq` namespace, and associated role. You can add additional GitHub namespaces to `SeleniumHQ` and import roles. That should address the 'consolidation' you requested.

**Comment by ddavison** [comment]
it sure did.  thanks very much for this!  https://galaxy.ansible.com/SeleniumHQ/selenium is looking much more appropriate now. 👌
