### ISSUE TITLE
Inconsistencies in handling of namespace casing between legacy and collection versions

### ISSUE THREAD

**Issue by ironfroggy** [ansible/galaxy#1810]
##### SUMMARY
Handling of namespace casing for collections is inconsistent with current treatment and actually broken for some namespaces. Specifically these are non-username namespaces, since usernames from Github logins are always lowercase in the first place.

Here's a summary of the issues found:
- Mazer refuses to build namespaces with uppercase characters, although these are valid namespaces and many such namespaces are in active use today for repositories.
- Collections built with lowercase versions of mixed-case namespaces cannot be uploaded by the UI, because the UI fails to locate the namespace by that name.
- It isn't clear yet if collections eventually built and published to mixed-case namespaces (when this is fixed) will be installed properly by Mazer. I can't test this until I can publish them in the first place.
- If a namespace is renamed just to fix the casing, which is a request we've had, all existing collections are no longer accessible, even though the URLs to access the collection detail page are themselves case insensitive. For example, if I publish a collection to `http://127.0.0.1:8000/collections/orionuser1ns/collection_simple_role_zmaiwwfk` I can also bring up that same content at `http://127.0.0.1:8000/collections/OrionUser1NS/collection_simple_role_zmaiwwfk`. If I then I rename the collection from `"orionuser1ns"` to `"OrionUser1NS"`, the same URL no is a 404.

This is a collection is issue related to the namespace casing and I'm filing it partly to document any information that can be provided or decisions around this. I don't know what behaviors we see in namespaces today are deliberate versus coincidental, so maybe we don't _want_ to support mixed-case namespaces!

But the fact remains that we already have them, that people are already using them, and that we already have established patterns of behavior for them. So, what's the right way to handle this with regard to collections?

**Comment by chouseknecht** [comment]
Related to #1805

**Comment by alikins** [comment]
@ironfroggy 


> * It isn't clear yet if collections eventually built and published to mixed-case namespaces (when this is fixed) will be installed properly by Mazer. I can't test this until I can publish them in the first place.

My suspicion is that mazer would find it, download it, extract/install it, then raise errors when it 'reloads' the installed collection and applying the CollectionInfo/galaxy.yml validation.  

I don't think it would fail until after it extracted the artifact to the collections_path, since the artifact extraction code doesn't validate the content. ie, the namespace lowercase restriction wouldn't be validated until it needs to create a mazer CollectionInfo object, which it avoids doing during the extract phase. 

(The extract path has avoided that since it's had to support Role Repository archives, plain 'unbuilt' collection archives, scm checkouts, local 'editable' installs etc. Mazer _could_ start validating the artifacts CollectionInfo including the namespace validation now, at least for collection artifacts.  )

**Comment by chouseknecht** [comment]
We have 961 Namespace Names that contain mixed case. I don't think we want to touch any of those just yet; but rather, we want to focus on preventing more mixed case names from being created.

We'll need to review the [user_logged_in handler](https://github.com/ansible/galaxy/blob/devel/galaxy/main/signals/handlers.py#L37) to make sure that it matches existing users with their existing namespace, but does not create new namespaces containing mixed case. If a GitHub user 'FooBar' comes along, and there is no existing 'FooBar' Namespace, and there is no existing 'foobar' namespace, then a new namespace 'foobar' will be created.

The other thing we need to check is that when creating or updating a namespace on My Content, the user cannot create names containing mixed case. I think the checks for this occur in the [Namespace view](https://github.com/ansible/galaxy/blob/devel/galaxy/api/views/namespace.py).

**Comment by ironfroggy** [comment]
@chouseknecht If we want to normalize namespace creation at GitHub login, what do we do with those starting with a number?

**Comment by chouseknecht** [comment]
@ironfroggy No idea. Not much we can do.

**Comment by chouseknecht** [comment]
If you have a legacy namespace where the name contains mixed case, we do NOT allow collections to be uploaded.

**Comment by alikins** [comment]
> * Mazer refuses to build namespaces with uppercase characters, although these are valid namespaces and many such namespaces are in active use today for repositories.

This can be changed of course, it's just based on enforcing the collection spec. As far as I know, ansible can/could load collections with they have mixed case names. If the collections are referenced with the matching mixed case name. Afaik, it would not do any case insensitive matching however.
