### ISSUE TITLE
Oracle Namespace

### ISSUE THREAD

**Issue by nalsaber** [ansible/galaxy#1813]
## Namespace Request
Oracle

##### Github Org Link
https://github.com/oracle/oci-ansible-modules

##### Admins

nalsaber
manojmeda 
mross22
smak-oracle

**Comment by chouseknecht** [comment]
@nalsaber 

Created namespace `oracle` with @nalsaber as the owner. Could not find other users in Galaxy. Have them log into Galaxy, and then you can add them as additional owners of the namespace.

Thanks for reaching out to us!
