### ISSUE TITLE
Gentoo and Clearlinux missing from the list of platforms

### ISSUE THREAD

**Issue by diodonfrost** [ansible/galaxy#1814]
### Use Case
Gentoo Linux missing from the list of platforms. ([https://www.gentoo.org/](https://www.gentoo.org/))
ClearLinux missing from the list of platforms ([https://clearlinux.org/](https://clearlinux.org/))

### Proposed Solution
Add Gentoo  and ClearLinux missing from the list of platforms: [https://galaxy.ansible.com/api/v1/platforms/](https://galaxy.ansible.com/api/v1/platforms/)

Platform: Gentoo
Release: any

Platform: ClearLinux
Release: any

### Alternatives
N/A

### Implementation
N/A

**Comment by chouseknecht** [comment]
@diodonfrost 

Requested platforms added. Thanks!
