### ISSUE TITLE
/api/v2/collections/ does not accept GET

### ISSUE THREAD

**Issue by bmbouter** [ansible/galaxy#1842]
##### SUMMARY

I was testing the collection API on galaxy-dev.ansible.com and I
1. logged in
2. request https://galaxy-dev.ansible.com/api/v2/collections/

##### EXPECTED RESULTS
I expected it to show data like https://galaxy-dev.ansible.com/api/v1/roles/ does (obviously w/ the correct data format v2, collections).

##### ACTUAL RESULTS

```


GET /api/v2/collections/

HTTP 405 Method Not Allowed
Allow: POST, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "code": "method_not_allowed",
    "message": "Method \"GET\" not allowed."
}

```

**Comment by chouseknecht** [comment]
Another feature that needs to be added to the v2 API. Probably not getting done until after 3.2.
