### ISSUE TITLE
Auth required for V2 API, but not for V1?

### ISSUE THREAD

**Issue by bmbouter** [ansible/galaxy#1843]
##### SUMMARY

You should be able request public data from the /api/v2/collections/ endpoint without logging in. Without this mazer won't be able to eventually filter content without ever request being authenticated.

##### STEPS TO REPRODUCE

1. logout of https://galaxy-dev.ansible.com/
2. Try to request  https://galaxy-dev.ansible.com/api/v2/collections/

##### EXPECTED RESULTS
I expected it to serve public Collection data similar to it does for V1 roles:  https://galaxy-dev.ansible.com/api/v1/roles/

##### ACTUAL RESULTS

I get a not authenticated error:

```
{
    "code": "not_authenticated",
    "message": "Authentication credentials were not provided."
}
```

**Comment by chouseknecht** [comment]
Not exactly a bug, more of a missing feature that needs to be completed for 3.2
