### ISSUE TITLE
Need some artifact shasum for a CollectionVersion

### ISSUE THREAD

**Issue by alikins** [ansible/galaxy#1846]
## Feature Request

At the moment, there is no info about the artifact associated with a CollectionVersion available from the API. There is a download_url that can point at anything.

For mazer, it needs to be able to check the artifacts it downloads for corruption/etc, and
easiest way to do that would be to compare the sha256sum of the artifact with an expected sha256sum. Since mazer has to get the CollectionVersion info already (https://galaxy-qa.ansible.com/api/v2/collections/alikins/collection_inspect/versions/0.0.42/ for ex) having the sha256sum of the accociated artifact available there would allow for checking the downloads.

### Use Case
Installing collections and verifying they were not corrupted or compromised during the file transfer from the download_url. 

### Proposed Solution
If we make the assumption than a CollectionVersion or CollectionVersionArtifact is associated with exactly one collection artifact and that galaxy imported that artifact, then we can add a sha256sum[1] to the CollectionVersion detail. 

Mazer needs to be able to know what the expected shasum of a artifact it is downloading will be so that it can verify it. That could mean adding chksum info to CollectionDetail views, or adding hyperlinked resources for artifact info ('api/v2/artifacts/' or the like). Or exposing artifact info from pulp api. For any given CollectionVersion it has decided to install, it needs to get the expected chksum from the galaxy api to corroborate with chksums it computes of downloaded artifacts. 

[1] or whatever chksums....

### Alternatives
The details of the object model doesn't matter a ton, so the data could come from a pulp api or other service. 

### Implementation

Get the info from the pulp_app_artifact row associated with the collectionversion and add it as a field on the returned data?

**Comment by cutwater** [comment]
Partially fixed by #1850.
