### ISSUE TITLE
Namespace Request for LesFurets.com

### ISSUE THREAD

**Issue by notsag** [ansible/galaxy#1848]
## Namespace Request

Hello, 

I'd like to create a new namespace for my organization.
The link to the organisation and the admins are provided below in the corresponding sections.

##### Github Org Link
https://github.com/lesfurets

##### Admins
@notsag, @samh57

Thanks a lot.

**Comment by chouseknecht** [comment]
@notsag 

New namespace `lesfurets` created. Both you and @Samh57 are owners. You'll need to edit the namespace and associate your GitHub organization(s) with it. 

Thanks for reaching out to us!
