### ISSUE TITLE
namespace request for 'collections_lockfile'

### ISSUE THREAD

**Issue by alikins** [ansible/galaxy#1852]
Wanting to reserve 'collections_lockfile' as a namespace, so I can use it as a placeholder 
for mazer messages that references Requirements from a collections lockfile.

ie, for a collections_lock.yml like:
``` yaml
alikins.collection_ntp: '>=0.1.6'
```

when used like:

```
mazer install --collections-lock collections_lock.yml
```

The normal requirement/requirement_spec messages displayed will be:
```
Installing requirement alikins.collection_ntp,>=0.1.6 (required by collections_lockfile.cli)
```

See https://github.com/ansible/mazer/issues/173 and 
https://github.com/ansible/mazer/pull/271 for WIP 'lockfile' support. 

## Namespace Request
collections_lockfile

##### Admins

alikins
chouse
other galaxy folks

**Comment by chouseknecht** [comment]
@alikins 

Created the requested namespace: https://galaxy.ansible.com/collections_lockfile

Still not clear on why we need this, or what we're going to do with it.
