### ISSUE TITLE
Receiving 404 error attempting to checkout dcos/dcos_ansible

### ISSUE THREAD

**Issue by daniel-sullivan** [ansible/galaxy#1862]
##### SUMMARY
Currently attempting to deploy DCOS via their Ansible packaging as per:
https://docs.mesosphere.com/1.13/installing/production/dcos-ansible/ansible-quickstart/

Using either ansible-galaxy (fresh yum install of Ansible on Centos 7.6.1810) or Mazer (Installed via pip (19.1.1 - Python 3.6) results in a 404 response.

I would normally assume it's an issue with the original packager (DCOS) but in this case nothing seems to have changed on their end recently (no updates in a month) and the Ansible Galaxy page https://galaxy.ansible.com/dcos/dcos_ansible is loading correctly seemly indicating that it should be still hosted.

##### STEPS TO REPRODUCE
Run either: 
``` ansible-galaxy install dcos.dcos_ansible ```
or 
``` mazer install dcos.dcos_ansible ```

##### EXPECTED RESULTS
The checkout of the package to occur.

##### ACTUAL RESULTS
Mazer returns:
```
Installing dcos.dcos_ansible (version_spec: *)
404 Client Error: Not Found for url: https://galaxy.ansible.com/api/v2/collections/dcos/dcos_ansible/:
- you can use --ignore-errors to skip failed collections and finish processing the list.
```

Ansible-galaxy returns:
```
- downloading role 'dcos_ansible', owned by dcos
 [WARNING]: - dcos.dcos_ansible was NOT installed successfully: - sorry, dcos.dcos_ansible was not found on https://galaxy.ansible.com.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**Comment by chouseknecht** [comment]
[docs/dcos_ansible](https://galaxy.ansible.com/dcos/dcos_ansible) is a multi-content repository. Support for these has been removed from Galaxy and Mazer. It was a tech-preview feature that we've discontinued. They'll need to convert to Collection. More info regarding Collections can be [found here](https://galaxy.ansible.com/docs/contributing/creating_collections.html).
