### ISSUE TITLE
Galaxy and GitHub organization migraton

### ISSUE THREAD

**Issue by sbesson** [ansible/galaxy#1863]
Our organization has been using Ansible Galaxy for the last couple of years to manage our Ansible roles under the [openmicroscopy](https://galaxy.ansible.com/openmicroscopy) namespace. First of all, huge thanks for all the work.

The source code for all our Ansible roles had been historically created under the [openmicroscopy](http://github.com/openmicroscopy) GitHub organization and most of them are deployed on Galaxy. At present, we are unifying all our GitHub repositories under the [OME](http://github.com/ome/) organization.

GitHub redirects all links following a repository transfer so that the migration ends up largely non-breaking for users from the source code perspective. Ideally, we would like to create a similar experience for consumers of the Ansible roles i.e. maintain the published roles unmodified so that existing playbooks remain functional without change and have the Galaxy roles pulling from the new source code location.

We performed an initial test by mapping both of our GitHub organizations (ome, openmicroscopy) to the openmicroscopy Galaxy namespace and migrated the source code of a [deprecated role](https://galaxy.ansible.com/openmicroscopy/jekyll-build) between the two organizations - . Unfortunately, this led to the creation of a [new role](https://galaxy.ansible.com/openmicroscopy/ansible-role-jekyll-build) rather than updating the existing role.

From the Galaxy side, is it possible to update the mapping between existing roles and the source code repository? We can provide a mapping of the locations that will migrate in whatever format would be appropriate. Or is there another approach to achieve the migration goals as described above?

/cc @manics @joshmoore @jburel

**Comment by chouseknecht** [comment]
I would suggest creating a new org on Galaxy called `ome`, mapping the GitHub `ome` org to it, and then importing the roles into `ome` on Galaxy. Existing playbooks will keep working, as the `openmicroscopy` namespace in Galaxy remains untouched. Ask your community/users to begin migrating to the new `ome` namespace, if they want to get the latest changes and updates.

As we've been saying since the release of Galaxy 3.1, role names need to be Python compatible, and thus for newly imported roles `-` gets converted to `_`. Thus all the new roles under the `ome` namespace in Galaxy will contain `_`. Make sure any install instructions for GitHub repos in the OME org point this out.

**Comment by chouseknecht** [comment]
@sbesson 

The new `ome` namespace now exists in Galaxy, and you're the owner. You can edit under My Content, and add additional owners and associate the GiHub OME org.

**Comment by sbesson** [comment]
@chouseknecht thanks for creating the new namespace. We are looking into the steps required to roll out the migration of our roles to the new namespace. As you mentioned, we will probably need to review the naming scheme to be Python compatible and properly set `role_name` across the board.

Coming back briefly to the linking question, once a role is migrated and created under the new namespace, I assume there is no mechanism to link it back to the old role (which will be deprecated) or inherit statistics and downloads count?

**Comment by chouseknecht** [comment]
There is not currently a linking mechanism in Galaxy to connect one role to another or share download stats.

Assuming we can close this, since the main issue of changing namespaces has been addressed. Please reach out to us, if we can provide any additional help.
