### ISSUE TITLE
Namespace request for consensus organization

### ISSUE THREAD

**Issue by lamech** [ansible/galaxy#1870]
## Namespace Request
Please create a namespace (ideally, 'consensus' or failing that, consensusenterprises) for us.

##### Github Org Link
https://github.com/consensus-enterprises

##### Admins
@ergonlogic

**Comment by chouseknecht** [comment]
@lamech 

New namespace created. Thanks for reaching out to us!

**Comment by colans** [comment]
Thanks.  It looks like the new namespace exists at https://galaxy.ansible.com/consensus, but the "View on GitHub" link goes to our Web site instead of our GitHub namespace.  Is this is bug, perhaps?
