### ISSUE TITLE
Setting up Galaxy Locally with Custom GitHub URL

### ISSUE THREAD

**Issue by muchatlu** [ansible/galaxy#1883]
Hi Team, 

I was trying to setup Galaxy locally and use our own GitHub URL for Login and Maintaining the Code.

Galaxy is up and I have Modified the GitHub URL and other files where it is pointing to github.com to our URL. But Even after modifying the files, Login is still redirecting to github.com only. 

Could you please point me to some documentation or Files where I have to modify. 

Thank You

**Comment by chouseknecht** [comment]
We're using Django Allauth. It might be as simple as setting the server URL in the `SOCIAL_ACCOUNT_PROVIDERS` settings as described here: https://django-allauth.readthedocs.io/en/latest/providers.html#github

Hope that helps!
