### ISSUE TITLE
Add Note for Local SCM dependency resolution and installation

### ISSUE THREAD

**Issue by ckupe** [ansible/galaxy#1890]
### Use Case
When configuring requirements.yml in roles directory for Ansible Tower project repositories, it is important to make a note that using "scm:" in a local git scm provider is *required* for local dependency resolution and installation to work. Not using "scm: " results in failures to resolve a local git repository url directly to Ansible Galaxy, which is not expressed in the documentation. 

### Proposed Solution
Add a NOTE block or adding more detail on the "scm" variable to explain its required use in order to do local resolution and installation without hitting Ansible Galaxy. https://galaxy.ansible.com/docs/using/installing.html#installing-multiple-roles-from-a-file

### Alternatives
N/A

### Implementation

Append "Note: scm is required in order to resolve to a local SCM provider that is not on Ansible Galaxy" to the scm descriptor.

**Comment by chouseknecht** [comment]
Thanks for pointing this out! PRs welcome.
