### ISSUE TITLE
Add a namespace for Institute of High Energy Physics, Austrian Academy of Sciences

### ISSUE THREAD

**Issue by dietrichliko** [ansible/galaxy#1891]
## Namespace Request
Plae add the namespace "hephyvienna" for the 

Institute for High Energy Physics
Austrian Academy of Sciencies

http://www.hephy.at 

##### Github Org Link
http://github.com/hephyvienna

##### Admins
dietrichliko

Thanks, Dietrich

**Comment by chouseknecht** [comment]
@dietrichliko 

Namespace `hephyvienna` created. Thanks for reaching out to us!
