### ISSUE TITLE
Collections: web-site keeps loading

### ISSUE THREAD

**Issue by robertdebock** [ansible/galaxy#1905]
##### SUMMARY
After publishing [my first collection](https://github.com/robertdebock/ansible-development-environment) the [galaxy page](https://galaxy.ansible.com/robertdebock/ansible_development_environment) keeps loading but never finished.

##### STEPS TO REPRODUCE
Upload [my first collection](https://github.com/robertdebock/ansible-development-environment) and open the related [galaxy page](https://galaxy.ansible.com/robertdebock/ansible_development_environment).

##### EXPECTED RESULTS
...

##### ACTUAL RESULTS
A loading "chain of balls" spinning.

**Comment by newswangerd** [comment]
@robertdebock Try setting a description in your `galaxy.yml`. It looks like there's a bug where the UI crashes if there's no description set.

**Comment by robertdebock** [comment]
Cool, that fixes my issue, thanks!
