### ISSUE TITLE
Role details redirects to Page Not Found

### ISSUE THREAD

**Issue by freemanjp** [ansible/galaxy#1907]
##### SUMMARY
When clicking on any of my organisations role names to see the details I get redirected to https://galaxy.ansible.com/not-found.

##### STEPS TO REPRODUCE

View any of the https://galaxy.ansible.com/gantsign roles e.g.:

https://galaxy.ansible.com/gantsign/maven

##### EXPECTED RESULTS
The page displaying details about the role.

##### ACTUAL RESULTS
Redirected to https://galaxy.ansible.com/not-found (Page Not Found).

**Comment by newswangerd** [comment]
Hi @freemanjp 

Looks like there was a duplicate namespace (`GantSign`) in our DB that was confusing the API when the website queries for your namespace `gantsign`. Since `GantSign` has no content or owner's I've deleted it and it that should resolve the issue.

**Comment by freemanjp** [comment]
@newswangerd thanks for fixing this so quickly.

FYI: `GantSign` was my original organisation name in GitHub (~3 years ago). I changed it to lowercase soon after creating it because mixed case caused issues for some services integrating with GitHub.
