### ISSUE TITLE
Adding ContinuousSecurityTooling Namespace

### ISSUE THREAD

**Issue by hypery2k** [ansible/galaxy#1908]
## Namespace Request

please consec-tools as namespace for this GitHub Org:

##### Github Org Link
https://github.com/ContinuousSecurityTooling

##### Admins
* hypery2k
* srsp

**Comment by chouseknecht** [comment]
New namespace [continuoussecuritytooling](https://galaxy.ansible.com/continuoussecuritytooling) created. Thanks for reaching out to us!
