### ISSUE TITLE
Request a namespace: batfish

### ISSUE THREAD

**Issue by ratulm** [ansible/galaxy#1912]
## Namespace Request
batfish

##### Github Org Link

https://github.com/batfish/batfish

##### Admins

ratulm
sfraint
saparikh

**Comment by chouseknecht** [comment]
New namespace created. Not seeing accounts for sfraint and saparikh in Galaxy. Once those guys log into Galaxy, you can add them as owners.

**Comment by ratulm** [comment]
Thanks, @chouseknecht. 

I cannot figure out something simple (and wondering if you can point me in the right direction): How do I import a role from GitHub into this new namespace? 

On the Galaxy website, I only see the option to upload a collection, and the role-importing functionality is grayed out.

**Comment by ratulm** [comment]
Figured it out ... :)
