### ISSUE TITLE
Renaming github namespace from: uniQconsulting -> uniqconsulting

### ISSUE THREAD

**Issue by joe-speedboat** [ansible/galaxy#1920]
##### SUMMARY
Hi 
We recently cleaned up our namespace again to align with github and role names:
To make the import and naming more robust, we changed uQc account from:
uniQconsulting to uniqconsulting
Now problem that I cannot access my roles anymore from within Galaxy Webpage:
https://galaxy.ansible.com/uniqconsulting (is showing all the roles)
If i click on one role, I get a "Page not found" error message.

##### STEPS TO REPRODUCE
Now problem that I cannot access my roles anymore from within Galaxy Webpage:
https://galaxy.ansible.com/uniqconsulting (is showing all the roles)
If i click on one role, I get a "Page not found" error message.

##### EXPECTED RESULTS
Now problem that I cannot access my roles anymore from within Galaxy Webpage:
https://galaxy.ansible.com/uniqconsulting (is showing all the roles)
If i click on one role, I would expect to see role details.
##### ACTUAL RESULTS
Now problem that I cannot access my roles anymore from within Galaxy Webpage:
https://galaxy.ansible.com/uniqconsulting (is showing all the roles)
If i click on one role, I get a "Page not found" error message.
##### QUESTION
May you please purge all the roles from https://galaxy.ansible.com/uniqconsulting so I can run a fresh import that hopefully will get accepted by webinterface of galaxy

Thanks a lot
Chris

**Comment by awcrosby** [comment]
@joe-speedboat - those 11 roles have been deleted, let us know if you have issues after you re-import them.
Thanks!

**Comment by uniqconsulting** [comment]
@awcrosby 
I reimported and still get the same "Page not found" message if I try to view role details from within ansible galaxy page:
eg: https://galaxy.ansible.com/uniqconsulting/graylog3

btw, cli still works as expected (no issues there!?):
```
[chris@sp-remote-01 files]$ ansible-galaxy search uniqconsulting

Found 10 roles matching your search:

 Name                            Description
 ----                            -----------
 uniqconsulting.collabora        installation and configuration of collabora CODE with nginx reverse proxy
 uniqconsulting.graylog3         Install graylog3 and configure single server instance
 uniqconsulting.guacamole        Install and configure Guacamole with Nginx ssl reverse proxy
 uniqconsulting.mariadb          installation and configuration of mariadb (mysql)
 uniqconsulting.network_setup    Network Setup
 uniqconsulting.nextcloud        nextcloud installation and configuration
 uniqconsulting.open_vm_tools    installation of open VMware Tools
 uniqconsulting.os_basic         Basic OS Server Setup
 uniqconsulting.os_update        Full or Security OS Updates
 uniqconsulting.veeam_linux_repo installation and configuration of Veeam Repository
```
Can you please check again, it must be something else which is depending on github user name

thanks
chris

**Comment by joe-speedboat** [comment]
@awcrosby 
@chouseknecht 
Hi, may you please reopen this issue?

thanks a lot

chris

**Comment by chouseknecht** [comment]
@joe-speedboat 

Fixed. Removed the duplicate namespace, and pointed the provider namespaces and content items to the correct namespace.
