### ISSUE TITLE
ansible-galaxy install not installing latest commit of role

### ISSUE THREAD

**Issue by hwwilliams** [ansible/galaxy#1925]
##### SUMMARY
Installing one of my roles using ansible-galaxy install doesn't pull the latest commit even though the role was recently imported on galaxy, its pulling an old commit instead.

##### STEPS TO REPRODUCE
1. Notice role [here](https://github.com/hwwilliams/ansible-role-epel) for latest activity.
2. Notice the content of main task [here](https://github.com/hwwilliams/ansible-role-epel/blob/master/tasks/main.yml).
3. Notice the role on galaxy [here](https://galaxy.ansible.com/hwwilliams/epel) and that it does show a new import and latest commit.
4. Run 'ansible-galaxy install hwwilliams.epel'.
5. Check the content of locally installed role's main task, the content isn't that of the latest commit.

##### EXPECTED RESULTS
I expected the latest commit to be pulled.

##### ACTUAL RESULTS
An old commit was pulled that was basically right after I forked the repo.

Another note, I did rename this role shortly after importing it for the first time but I deleted that instance and re-imported it on Galaxy after doing so. I do remember it working for a time after that but other than renaming the repo on Github and it being a fork I don't see why this repo would behave any differently than others that install as expected.

**Comment by ironfroggy** [comment]
@hwwilliams Can you give a little more information, please? Specifically, give the output of `ansible-galaxy --version`. Also, the output of the `install` command when you try to install the latest version of your role.

**Comment by chouseknecht** [comment]
Imports are based on tags. The last tag on your repo is `1.2.3` from April 20, 2018. The latest commit is from June 15, 2019. To get this last commit into Galaxy, you'll need to create a new tag.

When I run the install, it seems to do the right thing. Notice it installs the latest release, `1.2.3`, as expected:

```
ansible-galaxy install hwwilliams.epel
- downloading role 'epel', owned by hwwilliams
- downloading role from https://github.com/hwwilliams/ansible-role-epel/archive/1.2.3.tar.gz
- extracting hwwilliams.epel to /Users/chouseknecht/roles/hwwilliams.epel
- hwwilliams.epel (1.2.3) was installed successfully
```

**Comment by chouseknecht** [comment]
Based on my observations above, I think this can be closed. Please re-open, if I'm mistaken.
