### ISSUE TITLE
Upgrade or replace Elasticsearch

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#193]
Why?

- Because we depend on `drf-haystack`, we can't upgrade to Elasticsearch >= 5. 
- Because we depend on `elasticsearch-dsl`, we can' upgrade to Elasticsearch 6.

It appears that `drf-haystack` is not being actively maintained, or at least not actively enough, and thus should be eliminated as a dependency. 

Since we're in this position, it's also time to evaluate alternatives to Elasticsearch. One strong possibility is Postgresql full text search. 

Deliverables:

1. Write-up on changes needed and level of effort to switch to Postgresql full text search 
2. If option #1 is not viable, then a write-up for removing `drf-haystack` and `elasticsearch-dsl`, and upgrading to the Elasticsearch 6.

**Comment by chouseknecht** [comment]
Blocker to moving hosting and support of public Galaxy to Red Hat's internal IT.

**Comment by chouseknecht** [comment]
@cutwater completed in the current sprint

**Comment by cutwater** [comment]
Addressed by #355
