### ISSUE TITLE
namespace request for inverse-inc organization

### ISSUE THREAD

**Issue by nqb** [ansible/galaxy#1932]
##### Github Org Link
https://github.com/inverse-inc

##### Admins
- @extrafu
- @cgx
- @nqb

**Comment by nqb** [comment]
I read [Namespace limitations](https://galaxy.ansible.com/docs/contributing/namespaces.html?namespace-limitations#namespace-limitations), could you create a `inverse_inc` namespace ?

Thanks.

**Comment by chouseknecht** [comment]
Done. Thanks for reaching out!
