### ISSUE TITLE
My Stars

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#194]
- Add a menu option under the user's menu for 'My stars'.
- Add a 'My stars' page that shows any content *starred* by the user.
- Review the celery refresh tasks, and make sure we are updating stars, subscribers (watchers), and forks as part of the task. This should be part of the nightly refresh job that runs in Jenkins.

**Note: on a nighty basis we run deploy/ec2/refresh-counts.yml, which should rebuild the search indexes, remove any roles that no longer exist in GitHub, and update the counts.

**Comment by cutwater** [comment]
Blocked by #209

**Comment by chouseknecht** [comment]
I can confirm that `starring` and `un-starring` a repo through the Galaxy UI is updating the My Stars page in real-time, as expected.The menu option is working, and the page loads as expected. 

Checked our code for when we perform a batch update. We actually do it [here, on login](https://github.com/ansible/galaxy/blob/develop/galaxy/main/signals/handlers.py#L40).
