### ISSUE TITLE
Unable to configure provider namespace

### ISSUE THREAD

**Issue by jeffsheltren** [ansible/galaxy#1942]
##### SUMMARY
When editing the namespace for `tag1consulting`, I'm unable to configure the required `Provider Namespace`. When I select `tag1consulting`, I get the error: `This provider namespace is already associated with a Galaxy namespace (tag1consulting)`.

##### STEPS TO REPRODUCE
Edit namespace -> Select `tag1consulting` for Provider Namespace -> Save

##### EXPECTED RESULTS
Save the new Provider Namespace

##### ACTUAL RESULTS
Error message, attached.

<img width="524" alt="Screen Shot 2019-06-27 at 6 16 12 AM" src="https://user-images.githubusercontent.com/880136/60265733-aeb99580-98a3-11e9-93bc-e65aa5eb32ea.png">

**Comment by nqb** [comment]
Hello @jeffsheltren,

I got same issue yesterday. 

In My content -> jeffsheltren -> Edit properties, uncheck `tag1consulting` as a provider namespace and check it in the new namespace.

**Comment by chouseknecht** [comment]
@jeffsheltren 

The provider namespace `tag1consulting` was actually associated with `traviswhitehead`. I removed the association, so you should be able to add it now.

**Comment by jeffsheltren** [comment]
That worked, thanks @chouseknecht!
