### ISSUE TITLE
Request a Namespace for cylc

### ISSUE THREAD

**Issue by kinow** [ansible/galaxy#1943]
##### Github Org Link

https://github.com/cylc/

##### Admins

https://github.com/hjoliver
https://github.com/kinow/
https://github.com/alanbchristie/

Thank you!

**Comment by kinow** [comment]
@alanbchristie namespace for our [Ansible role](https://github.com/cylc/cylc-ansible) created!

**Comment by alanbchristie** [comment]
OK nice. I'm not sure how _I_ see this namespace. When I log into Galaxy the only namespaces I see are my own (**alanbchristie** and **matildapeak**) under `My Content`. Theres is no **cylc** namespace available to me and so I cannot see how I `Add Content` for **cylc**. For now, someone else is going to have to `Add Content`.

**Comment by kinow** [comment]
I suspect it will be added to ansible galaxy, and after that we should be able to use it to import projects.

**Comment by chouseknecht** [comment]
New namespace `cylc` added. Thanks for reaching out to us!

**Comment by kinow** [comment]
Feel free to try to import it @alanbchristie , if that doesn't work I will try it later too (about to go to airport, limited internet until mid next week)

**Comment by alanbchristie** [comment]
I now see the namespace but the **Import from GitHub** button is disabled - likely due to my `cylc` organisation permissions. I'll leave the publishing to you/someone else.

**Comment by kinow** [comment]
I had a similar issue. Then removed the provider from my user namespace, then added it to the cylc namespace, and the I coukr successfully list and import.

Can you confirm it's working?

https://galaxy.ansible.com/cylc/cylc

**Comment by alanbchristie** [comment]
Yep - just installed via Galaxy and have run the role. `cylc.cylc` is ready.
