### ISSUE TITLE
Namespace request for intel organization

### ISSUE THREAD

**Issue by radoslawKuschel** [ansible/galaxy#1959]
## Namespace Request
intel
##### Github Org Link

https://github.com/intel
##### Admins

radoslawKuschel
martinkennelly
intmc
IvensZambranoIntel

**Comment by chouseknecht** [comment]
Namespace `intel` created. User `radoslawKuschel` set to the owner. The other users do not exist in Galaxy. You can add them as namespace owners after they log into Galaxy for the first time.

**Comment by radoslawKuschel** [comment]
Hi @chouseknecht  
I can see the name space was created https://galaxy.ansible.com/intel but the View on GitHub button is missing, also in 'My Content' i can see 0 Provider Namespaces, when i try to add Provider Namespaces the intel name space is no there. Any hint how can I link project from my organization's public repo to galaxy?
