### ISSUE TITLE
This provider namespace is already associated with a Galaxy namespace

### ISSUE THREAD

**Issue by alanbchristie** [ansible/galaxy#1965]
##### SUMMARY
I have my own namespace (`alanbchristie`) but I am also the owner of the GitHub organisation MatildaPeak. Both `alanbchristie` and `matildapeak` exist as namespaces in Ansible Galaxy but I (`alanbchristie`) appear not to be able to be the **Provider Namespace** for both of them. When I try to add myself as a Provider Namespace for `matildapeak` I'm presented with the message **This provider namespace is already associated with a Galaxy namespace (alanbchristie)**

Can I be the **Provider Namespace** for two Galaxy namespaces? If not, how to I add content for `matildapeak`?

##### STEPS TO REPRODUCE
- Login to Ansible Galaxy
- Navigate to the **Edit Properties** for `matildapeak`
- Select `alanbchristie` from the list of **Provider Namespaces**
- Click **Save**

##### EXPECTED RESULTS
Become the **Provider Namespace** for the `matildapeak` namespace.

##### ACTUAL RESULTS
Error dialogue with the message **This provider namespace is already associated with a Galaxy namespace (alanbchristie)**

**Comment by chouseknecht** [comment]
@abc A GitHub org or GitHub user namespace can only be associated with a single Galaxy namespace. If the goal is to put content into `matlidapeak`, then your GitHub user namespace, `alanbchristie`,  should be associated with `maltildapeak` only in Galaxy. 

Do you want us to make the change?

**Comment by alanbchristie** [comment]
Ah, OK. So, is it possible to add the `matildapeak` GitHub organisation (of which I am an owner) to the existing MatildaPeak galaxy namespace so that I can publish content to it using that GitHub namespace?

**Comment by chouseknecht** [comment]
I can't make the association because I'm not part of the `matildapeak` GitHub org. However, you can. Go to My Content and all the way to the right of the `matildapeak` namespace, click the menu icon, and select Edit Properties. On the next page, down at the bottom, you can add GitHub orgs.

**Comment by alanbchristie** [comment]
When I Select **Edit Properties** I can see a table at the bottom with the name **Provider Namespaces**. `matildapeak` is not in the list and I cannot add it to the list - I can only select an item that is in the list.

I wonder whether there's something _special_ about `matildapeak` ... ? (I'll check visibility settings)

**Comment by alanbchristie** [comment]
It appears to be caused by the organisation's **Third-party application access policy**. If this is set then the org does not appear in the list of ** Provider Namespaces**.

So I guess, to use **Galaxy** an org cannot have **Restricted Access**?

**Comment by chouseknecht** [comment]
@abc Seems you answered your own question. Marking this as closed.
