### ISSUE TITLE
namespace request: ubicast

### ISSUE THREAD

**Issue by nikaro** [ansible/galaxy#1975]
## Namespace Request

Hello, can you please add an "ubicast" namespace?

##### Github Org Link

https://github.com/UbiCastTeam

##### Admins

@nikaro

**Comment by chouseknecht** [comment]
There is no `nikaro` user. You need to first log into Galaxy using your GitHub credentials.

**Comment by nikaro** [comment]
@chouseknecht sorry i though that the GitHub user was needed, on Galaxy is it `nicolas11` (which indeed is linked to my `nikaro` GitHub account).

**Comment by chouseknecht** [comment]
@nikaro 

Created with user `nicolas11` as the owner.
