### ISSUE TITLE
Collection galaxy.yml tags with underscores do not pass Galaxy validation

### ISSUE THREAD

**Issue by geerlingguy** [ansible/galaxy#1976]
##### SUMMARY

I added the following tags in my collection `galaxy.yml`:

```yaml
tags:
  - centos
  - amazon_linux
```

When I try to publish the built collection artifact using Ansible devel I get the following error:

```
Publishing collection artifact '/Users/jgeerling/Dropbox/VMs/collections/geerlingguy.php_roles/geerlingguy-php_roles-0.9.1.tar.gz' to https://galaxy.ansible.com
ERROR! Galaxy import process failed: Invalid collection metadata. 'tag' has invalid format: amazon_linux (Code: GLW0002)
```

##### STEPS TO REPRODUCE

  1. Create a collection with a tag with an underscore.
  2. Try to publish the collection artifact to galaxy.

##### EXPECTED RESULTS

I expected no errors. The [Collections documentation](https://galaxy.ansible.com/docs/contributing/creating_collections.html) states for `tags`:

> `tags`: a list of tags. These have the same character requirements as `namespace` and `name`.

And for `namespace`:

> May only contain alphanumeric characters and underscores. Additionally namespaces cannot start with underscores or numbers and cannot contain consecutive underscores.

##### ACTUAL RESULTS

```
Publishing collection artifact '/Users/jgeerling/Dropbox/VMs/collections/geerlingguy.php_roles/geerlingguy-php_roles-0.9.1.tar.gz' to https://galaxy.ansible.com
ERROR! Galaxy import process failed: Invalid collection metadata. 'tag' has invalid format: amazon_linux (Code: GLW0002)
```

**Comment by geerlingguy** [comment]
I noticed the collection tests in galaxy have a tag like `bad_tag` included in the 'bad tags' test: https://github.com/ansible/galaxy/blob/7d6c928fcb5fbcb9a207ecb79754a512dabaeef5/galaxy/importer/tests/test_collection_info.py#L61-L68 — I wonder then if this is a bug with the documentation, and tags must only be individual keywords...

E.g. you can only have `amazon` and `linux` or something like that.

The only concern I have there is that semantically a tag like `amazon_linux` is a lot different than separate tags, since `amazon` more often refers to aws-type stuff, whereas `amazon_linux` is a specialized linux distribution almost always referred to as 'Amazon Linux' (vs. something like Debian, which you wouldn't normally call "Debian Linux").

**Comment by chouseknecht** [comment]
The documentation is wrong. We don't allow special chars in tags.

**Comment by chouseknecht** [comment]
NOTE: the addition of `_` only applies to Collections. We have not applied this to Roles and likely should not.

**Comment by geerlingguy** [comment]
So the idea is that `_` _will_ be allowed so tags match name/namespace in their allowed formatting?

**Comment by awcrosby** [comment]
That is correct.
