### ISSUE TITLE
arubanetworks

### ISSUE THREAD

**Issue by tchiapuziowong** [ansible/galaxy#1985]
## Namespace Request
arubanetworks

##### Github Org Link
https://github.com/aruba/aoscx-ansible-role.git

##### Admins
tchiapuziowong
madhusudan-pranav-venugopal

**Comment by chouseknecht** [comment]
Done. Thanks for reaching out to us!

**Comment by tchiapuziowong** [comment]
Hi @chouseknecht thank you for the speedy response!! Question, I'm attempting to import a role from Github into Galaxy but the option is disabled - do you know why this would be the case?

![image](https://user-images.githubusercontent.com/16353697/63185071-e0cab680-c00d-11e9-8a69-f5630e2b4c80.png)

**Comment by madhusudan-pranav-venugopal** [comment]
It is disabled for me too

**Comment by chouseknecht** [comment]
You need to associate the GitHub org with the new Galaxy namespace. Go to My Content and choose the Edit Properties option from the menu all the way to the right.

**Comment by tchiapuziowong** [comment]
Okay we'll work on that thank you!!

**Comment by madhusudan-pranav-venugopal** [comment]
Hey, we were able to import the role into the Galaxy namespace. Thank you

**Comment by tchiapuziowong** [comment]
https://galaxy.ansible.com/arubanetworks/aoscx
