### ISSUE TITLE
Add AIX to platforms list

### ISSUE THREAD

**Issue by d-little** [ansible/galaxy#1986]
## Feature Request
Please add platform support for IBM's AIX.  There are a number of modules that support AIX now and I'm working on a few more and a number of roles.

ie:
- https://galaxy.ansible.com/d_little/ansible_role_aix_etc_configs
- https://galaxy.ansible.com/d_little/ansible_role_aix_lvm

### Proposed Solution
```yaml
AIX:
  - 6.1
  - 7.1
  - 7.2
```

(The earliest version of AIX that I can find support for in most modules is AIX6.1, I dont imagine anyone will try to support <=5.3)

**Comment by chouseknecht** [comment]
@d-little 

Done. See https://galaxy.ansible.com/api/v1/platforms/?name=AIX
