### ISSUE TITLE
BaobabLims Organisation namespace request

### ISSUE THREAD

**Issue by zipho** [ansible/galaxy#1988]
## Namespace Request
BaobabLims

##### Github Org Link
https://github.com/BaobabLims

##### Admins
zipho.m@gmail.com
coertquinton
hocinebendou

**Comment by chouseknecht** [comment]
Done. New namespace name is `baobablims`, as uppercase letters are not allowed. User `zipho` is set as the owner. Once others log into Galaxy using their GitHub credentials, you can add them as additional owners.

Thanks for reaching out to us!
