### ISSUE TITLE
Requesting HPE namespace 

### ISSUE THREAD

**Issue by thedoubl3j** [ansible/galaxy#1998]
## Namespace Request
ansible.galaxy.com/hpe
##### Github Org Link

https://github.com/HewlettPackard
##### Admins

bobfraser1

**Comment by thedoubl3j** [comment]
requesting on behalf of the partner

**Comment by chouseknecht** [comment]
Done.

**Comment by thedoubl3j** [comment]
thank you @chouseknecht
