### ISSUE TITLE
Unable to login to Galaxy web - Server Error (500)

### ISSUE THREAD

**Issue by BlackLacost** [ansible/galaxy#2000]
##### SUMMARY
I get Server Error (500) every i try to login.

##### STEPS TO REPRODUCE
    Go to page: https://galaxy.ansible.com/accounts/login/
    Input Email and Password
    I get 500 server error

##### EXPECTED RESULTS
Logged in

##### ACTUAL RESULTS
Server Error (500)

**Comment by chouseknecht** [comment]
The page `https://galaxy.ansible.com/accounts/login/` no longer exists. You may need to refresh your browser cache or something on your end.

**Comment by BlackLacost** [comment]
### I cleared cache.

### Then go to https://galaxy.ansible.com/login and click
![Screenshot from 2019-08-30 14-51-23](https://user-images.githubusercontent.com/1394083/64018667-b876a800-cb35-11e9-8310-ffcfff9cd052.png)

### redirect to https://galaxy.ansible.com/accounts/social/signup/
![Screenshot from 2019-08-30 14-55-19](https://user-images.githubusercontent.com/1394083/64018847-3b97fe00-cb36-11e9-8bad-d6e701b368ad.png)

### If i click Sign Up button
![Screenshot from 2019-08-30 14-56-52](https://user-images.githubusercontent.com/1394083/64018910-6c783300-cb36-11e9-9967-f2851e30a165.png)

### If i click Sign In link.
![Screenshot from 2019-08-30 14-58-52](https://user-images.githubusercontent.com/1394083/64019021-b3662880-cb36-11e9-80d2-c1651c85e07f.png)

Input Email and Password
I get 500 server error

**Comment by ironfroggy** [comment]
It looks like you have an old account from 2014 when Galaxy supported login by Google, which your account is currently linked to. You don't appear to have any content associated with that account, so potentially we could delete the unlinked account. You could then login correctly with Github.

**Comment by BlackLacost** [comment]
Delete the unlinked account please.

**Comment by cutwater** [comment]
@BlackLacost The account is deleted. Could you please check if sign it works.

**Comment by BlackLacost** [comment]
Thank you! Sign it works.
