### ISSUE TITLE
Request new namespace

### ISSUE THREAD

**Issue by ahuffman** [ansible/galaxy#2003]
## Namespace Request
ansible_fact
##### Github Org Link

https://github.com/ahuffman/ansible-fact
##### Admins

ahuffman
john-westcott-iv

**Comment by chouseknecht** [comment]
Created `ansible_fact`. Added `ahuffman` as the owner. Don't see a `john-westcott-iv`, but you can add additional owners. That person may just need to log into Galaxy for the first time.
