### ISSUE TITLE
Why does galaxy demands access to my private repos?

### ISSUE THREAD

**Issue by dmitrybelyakov** [ansible/galaxy#2007]
There's no open/closed issue that addresses that problem.

##### SUMMARY
Today I wanted to re-import one of my roles into galaxy. Since the recent changes the only way to log in is via github. OAuth flow requires me to give access to all my private repos.  This seems a bit excessive. I am unable to log in without giving this permission.

##### STEPS TO REPRODUCE
Remove galaxy app from github and start a new oauth flow to see the permission scope requested.

##### EXPECTED RESULTS
Private repo access should not be required to log into galaxy.

##### ACTUAL RESULTS
It is.

**Comment by chouseknecht** [comment]
I'm not sure that it's asking for 'access to all [your] private repos'. We ask for "user:email" and "read:org" scopes when authenticating to GitHub. See [code here](https://github.com/ansible/galaxy/blob/devel/galaxy/settings/default.py#L281).

**Comment by chouseknecht** [comment]
Here's what it actually looks like during sign-in:

![scopes](https://user-images.githubusercontent.com/1282865/64362272-3a564d80-cfdc-11e9-968c-c62f6560beb8.png)

**Comment by dmitrybelyakov** [comment]
Apologies Chris, you are right.  Thank you for looking into this. I will close this now.
