### ISSUE TITLE
Galaxy fails to display Asciidoc README 

### ISSUE THREAD

**Issue by lae** [ansible/galaxy#2010]
##### SUMMARY
A Readme is not rendered on Galaxy if it's written in asciidoc (and possibly other supported markups on GitHub)

##### STEPS TO REPRODUCE
Create a new role with a `README.adoc` in the repository instead of a `README.md` and import that role. Sample content:

```
= test role
```

##### EXPECTED RESULTS
Based on reading #1109, I assume Galaxy just pulls the Github-rendered README instead of generating the README itself, so I'd expect the same to happen here.

##### ACTUAL RESULTS
Galaxy doesn't display a Readme button like it does for `README.md`: [lae.netbox](https://galaxy.ansible.com/lae/netbox)

**Comment by chouseknecht** [comment]
We support markdown (`.md`) and, I believe, `.rst`. There's no plan to add `.adoc`.
