### ISSUE TITLE
Galaxy Can't See Roles Directory

### ISSUE THREAD

**Issue by ry1015** [ansible/galaxy#2011]
Hi,

I have an application repo where we added a roles directory. Howcome galaxy is unable to read this directory?
Tree ex.
```
app-repo
  -- src/
  -- roles/
     -- defaults/
     -- meta/
     -- tasks/
     -- templates/
  -- other_directories/
```
requirements.yaml
```
- name: app
  src: git+ https://github.com/username/app.git
  version: v1.0.0
```
Thanks in advance,
Ry

**Comment by chouseknecht** [comment]
I think you're asking, "How do I make `ansible-galaxy` install to a specific directory?"

Please view https://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html?highlight=galaxy#installing-roles, and see the `roles_path` topic.

**Comment by chouseknecht** [comment]
Closing this, as I believe it's answered. However, please re-open if you have additional questions.

**Comment by ry1015** [comment]
I realized that my src was wrong. But I'll ask another question since it's outside this scope in regards to automating galaxy-ansible with Gitlab.

Thanks for the response!
