### ISSUE TITLE
Galaxy Unable To Install Role - the file downloaded was not a tar.gz - Gitlab CI Runner

### ISSUE THREAD

**Issue by ry1015** [ansible/galaxy#2018]
Hi All,

I'm running into a problem with Galaxy and Gitlab CI Runner. I'm getting the error, "the file downloaded was not a tar.gz." Below is the error.
```
$ ansible-galaxy install https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.ENDPOINT.com/PATH/PROJECT.git,t1.0.0.0
- downloading role from https://gitlab-ci-token:[MASKED]@gitlab.ENDPOINT.com/PATH/PROJECT.git.git
 [WARNING]: - PROJECT was NOT installed successfully: the file downloaded
was not a tar.gz
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

For reference here's my requirements.yaml
```
- name: goose
  src: "https://gitlab-ci-token:[MASKED]@gitlab.ENDPOINT.com/PATH/PROJECT.git"
  version: "t1.0.0.0"
```

Locally, everything is working properly.

Any advice is much appreciated.

Thanks,
Ry

**Comment by chouseknecht** [comment]
@ry1015 

Please review https://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html?highlight=galaxy#installing-multiple-roles-from-a-file

You're specifying the `src:` parameter incorrectly

**Comment by ry1015** [comment]
Thanks for the response. But looking at the the docs, it seems there isn't a way to properly integrate a Gitlab CI with galaxy-ansible.

All those examples either require a credentials prompt or have the ssh key stored in Gitlab. This will not work with a Gitlab CI. They only way, that I know of, is to use the Gitlab token to pull the required repos.

**Comment by ry1015** [comment]
I figured out how ansible-galaxy can work with Gitlab Runner. Below is my yaml file.
```
- src: https://gitlab-ci-token:$CI_JOB_TOKEN@ENDPOINT.com/PATH/TO/PROJECT.git
  scm: 'git'
  version: v1.0.0
  name: PROJECT_NAME
```

Result
```
- extracting PROJECT_NAME to /root/.ansible/roles/goose
- goose (v1.0.0) was installed successfully
```
