### ISSUE TITLE
Add "icinga" as an organization/namespace to Ansible Galaxy

### ISSUE THREAD

**Issue by widhalmt** [ansible/galaxy#2023]
## Namespace Request
Hi,

I'd like to add "icinga" as an organization/namespace to Ansible Galaxy so we can upload roles as an organization.

Thank you in advance!

##### Github Org Link
https://github.com/icinga

##### Admins

* gethash
* widhalmt

More can come later, I hope, that's no problem.

**Comment by chouseknecht** [comment]
Done. Thanks for reaching out!
