### ISSUE TITLE
Request a new namespace 'extreme'

### ISSUE THREAD

**Issue by ujwalkomarla** [ansible/galaxy#2029]
##### Github Org Link

https://github.com/extremenetworks
##### Admins

@bigmstone
@UjwalKomarla

**Comment by chouseknecht** [comment]
Done. `ujwalkomarla` doesn't exist in Galaxy. Once they log into Galaxy, you can add them as an owner.

**Comment by ujwalkomarla** [comment]
@chouseknecht  Thanks! My bad. Logged into galaxy with github now. Would it be possible to add me(ujwalkomarla) as an owner now?

**Comment by ujwalkomarla** [comment]
@chouseknecht Matthew is experiencing difficulty adding me as an admin.

He is receiving the following error message: [screenshot](https://www.dropbox.com/s/w3vhx10n2txq8o/Screenshot%202019-10-03%2012.19.49.png?dl=0), as a provider is required before he can submit a form adding me as an admin.

Can you please help me here?

Thanks.
