### ISSUE TITLE
offline role installation is not possible or documented

### ISSUE THREAD

**Issue by ssbarnea** [ansible/galaxy#2030]
Initially raised as a [question](https://stackoverflow.com/questions/58135668/how-can-i-perform-an-offline-install-with-ansible-galaxy), but it seems to be more of a bug as the documentation does not state any way of installing a role from a local source.

Documentation of `requirements.yml` is very well hidden at https://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html#installing-multiple-roles-from-a-file and does not give any example of using a local source, like a `file://` url or something similar.

There are multiple reasons for needing this:
* environments where internet access is blocked
* GitHub giving 401 Access Denied
* CI testing, where installing roles could be done a big number of times even inside the same job.

```
---
- name: timezone
  src: yatesr.timezone
  version: 1.1.0
```

This bus is also a **blocker for changing default dependency installer in molecule** from [gilt](https://gilt.readthedocs.io/en/latest/) to galaxy, because gilt works offline.

**Comment by chouseknecht** [comment]
You can simply pass in a list of *tar* files. Here's the instructions from `ansible-galaxy install --help`:

```
Usage: ansible-galaxy install [options] [-r FILE | role_name(s)[,version] | scm+role_repo_url[,version] | tar_file(s)]

Install Roles from file(s), URL(s) or tar file(s)

Options:
  -f, --force           Force overwriting an existing role
  -h, --help            show this help message and exit
  -c, --ignore-certs    Ignore SSL certificate validation errors.
  -i, --ignore-errors   Ignore errors and continue with the next specified
                        role.
  -g, --keep-scm-meta   Use tar instead of the scm archive option when
                        packaging the role
  -n, --no-deps         Don't download roles listed as dependencies
  -r ROLE_FILE, --role-file=ROLE_FILE
                        A file containing a list of roles to be imported
  -p ROLES_PATH, --roles-path=ROLES_PATH
                        The path to the directory containing your roles. The
                        default is the roles_path configured in your
                        ansible.cfg file (/etc/ansible/roles if not
                        configured)
  -s API_SERVER, --server=API_SERVER
                        The API server destination
  -v, --verbose         verbose mode (-vvv for more, -vvvv to enable
                        connection debugging)
  --version             show program's version number and exit
```

If you feel more examples in the docs would be helpful, please submit a PR to the Ansible project.

**Comment by ssbarnea** [comment]
Another issue is that apparently galaxy-install returns error if no roles are mentioned inside the requirements.yml file, this also closing another door related to testing.

**Comment by chouseknecht** [comment]
@decentral1se @ssbarnea 

This issue needs to be opened at the [Ansible project](https://github.com/ansible/ansible), as the `ansible-galaxy` command line tool is part of Ansible.

**Comment by decentral1se** [comment]
:man_facepalming:

**Comment by KasperSkytte** [comment]
When creating new ansible galaxy roles with a `ansible-galaxy init` I also got annoyed that I would have to commit and push changes to a git repo first to be able to install from there to be able to test out the changes. Now I simply make a symbolic link from the folder with the role in development to a folder in `roles/` and use that instead. Surely it would be more handy to have a development feature to complement `ansible-galaxy init` to install the with something like `ansigle-galaxy install path/to/new/role --type local`.
