### ISSUE TITLE
No permission to delete role?!?

### ISSUE THREAD

**Issue by DrPsychick** [ansible/galaxy#2035]
I checked several bug reports. It could be that I'm affected by a legacy integration or renaming issue. The bug I reported previously was fixed, but did not fix my issue: https://github.com/ansible/galaxy/issues/1479

## Bug Report 
I have 2 roles imported on https://galaxy.ansible.com/my-content/namespaces which refer to the same GitHub repo. I cannot delete the role "ansible-docker" ("Error! Save repository failed: (You do not have permission to perform this action.)"), please delete it for me: https://galaxy.ansible.com/drpsychick/ansible-docker

I tried to "reset" my GitHub integration by revoking access in GitHub and then re-login on galaxy to grant access again - no change :(

##### SUMMARY
My overall problem is: Notifications from travis-ci never trigger Galaxy imports. When I manually POST a notification, I always get a 500 server error. I believe it might be connected with my Galaxy account being somewhat "broken".

**Comment by chouseknecht** [comment]
Roles deleted. You should be able to import them back in now.

**Comment by DrPsychick** [comment]
Thanks for the fast response @chouseknecht !

So now the issue becomes more prominent: I see 2 namespaces associated with my galaxy account: one all lowercased, one with uppercase letters like on github.

I reimported both roles manually, then did merged a PR with master -> still no notification/reimport on galaxy.

I think it's easiest if you delete my Galaxy account completely and I hope that all issues disappear when I set it up from scratch again.

**Comment by chouseknecht** [comment]
Everything looks fine. There's only a single namespace, and your roles appear to be imported successfully.

![drpsychik](https://user-images.githubusercontent.com/1282865/66046922-c339a980-e4f4-11e9-8eda-9dd5751892a9.png)

**Comment by chouseknecht** [comment]
There were 2 provider namespaces associated with your namespace. I removed the extra one. See if that helps.

**Comment by DrPsychick** [comment]
Yes. Help, it did. The problem solved, it has.

muchas gracias
