### ISSUE TITLE
ansible-galaxy collections install not working

### ISSUE THREAD

**Issue by schmots1** [ansible/galaxy#2037]
##### SUMMARY
When trying to run `ansible-galaxy collections install netapp.ontap -p ~/.ansible/collections` I get the following error.

[root@4cf5e2de55ea ~]# ansible-galaxy collections install netapp.ontap -p ~/.ansible/collections/
- downloading role 'collections', owned by
 [WARNING]: - collections was NOT installed successfully: Content has no field named 'owner'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

##### STEPS TO REPRODUCE
run `ansible-galaxy collections install netapp.ontap -p ~/.ansible/collections

##### EXPECTED RESULTS
download and place the netapp.ontap collection in ~/.ansible/collections/ansible_collecitons/netapp/ontap/

##### ACTUAL RESULTS
[root@4cf5e2de55ea ~]# ansible-galaxy collections install netapp.ontap -p ~/.ansible/collections/
- downloading role 'collections', owned by
 [WARNING]: - collections was NOT installed successfully: Content has no field named 'owner'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

```

**Comment by ironfroggy** [comment]
The subcommand is "collection" not "collections"
Somehow you are triggering an attempt to install a _role_ named "collections", although I'm not able to reproduce this. Please try with the correct invocation:

`ansible-galaxy collection install netapp.ontap -p ~/.ansible/collections`

I believe both this and #2039 to be invalid.

**Comment by schmots1** [comment]
nope.. even with 'collection' and not collections.  both with and without ignore.  Ansible 2.8.5

[root@4cf5e2de55ea ~]# ansible-galaxy collection install netapp.ontap -p ~/.ansible/collections
- downloading role 'collection', owned by
 [WARNING]: - collection was NOT installed successfully: Content has no field named 'owner'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
[root@4cf5e2de55ea ~]# ansible-galaxy collection install netapp.ontap -p ~/.ansible/collections --ignore-errors
- downloading role 'collection', owned by
 [WARNING]: - collection was NOT installed successfully: Content has no field named 'owner'

- downloading role 'ontap', owned by netapp
 [WARNING]: - netapp.ontap was NOT installed successfully: - sorry, netapp.ontap was not found on https://galaxy.ansible.com.

[root@4cf5e2de55ea ~]#

**Comment by chouseknecht** [comment]
The `collection` subcommand only exists in Ansible 2.9. You're referencing Ansible 2.8.5. Also, this is related to `ansible-galaxy` which is part of the Ansible project. Please file issues at [ansible/ansible/issues](https://github.com/ansible/ansible/issues)
