### ISSUE TITLE
a known collection is not found

### ISSUE THREAD

**Issue by schmots1** [ansible/galaxy#2039]
## Bug Report 

Error saying collection not found on galaxy

##### SUMMARY
When running the collections install with --ignore-errors per the error I get and submitted as issue #2037, I now get the error that a collection that does exist and will install fine with mazer isn't there.

##### STEPS TO REPRODUCE
run `ansible-galaxy collections install netapp.ontap -p ~/.ansible/collections --ignore-errors`

##### EXPECTED RESULTS
Should download and install NetApp ONTAP collection

##### ACTUAL RESULTS
[root@4cf5e2de55ea ~]# ansible-galaxy collections install netapp.ontap -p ~/.ansible/collections/ --ignore-errors
- downloading role 'collections', owned by
 [WARNING]: - collections was NOT installed successfully: Content has no field named 'owner'

- downloading role 'ontap', owned by netapp
 [WARNING]: - netapp.ontap was NOT installed successfully: - sorry, netapp.ontap was not found on https://galaxy.ansible.com.

```

**Comment by chouseknecht** [comment]
Same as on #2037, the `collection` subcommand is only available in Ansible 2.9.0. Issues related to `ansible-galaxy` should be filed against the Ansible project.
