### ISSUE TITLE
remove the requirement for -p from ansible-galaxay collection

### ISSUE THREAD

**Issue by schmots1** [ansible/galaxy#2042]
## Feature Request
Per the discussions at AnsibleFest I am opening this issue.
### Use Case
Much like mazer install defaults to ~/.ansible/collections/ansible_collections/ so should ansible-galaxy collection.  -p should only be required if you want it somewhere else.

### Proposed Solution
When running `ansible-galaxy collection install <namespace>.<collection>` it will just default to ~/.ansible/collections/ansible_collections/

**Comment by chouseknecht** [comment]
This is already in progress here: https://github.com/ansible/ansible/pull/62870
