### ISSUE TITLE
Galaxy Login Issues (Server Error (500))

### ISSUE THREAD

**Issue by afpacket** [ansible/galaxy#2048]
##### SUMMARY
I apologize in advance for opening a GitHub issue for this, but I didn't see any other way to request support.

I cannot log into Galaxy - I have what I believe is a local account (not linked to GitHub or other third party login) that I can log into via https://galaxy.ansible.com/accounts/login/ but get `Server Error (500)` upon logging in. The behavior is identical to https://github.com/ansible/galaxy/issues/2000

Would it be possible to delete my account (afpacket)?

Thank you.
##### STEPS TO REPRODUCE
Navigate to https://galaxy.ansible.com/accounts/login/ and fill in Login and Password fields

##### EXPECTED RESULTS
Successful login

##### ACTUAL RESULTS
`Server Error (500)`

**Comment by chouseknecht** [comment]
You can only log into Galaxy using GitHub.

**Comment by chouseknecht** [comment]
There was an `afpacket` user account. I went ahead and removed it, so you should now be able to log in using GitHub.

**Comment by afpacket** [comment]
Excellent, I am now able to log in without any issues - thank you so much and please feel free to close the issue.

**Comment by islander** [comment]
I have the same issue, can't sign in with github account (e-mail: zombie32@gmail.com). My previous username was `kiba`.
