### ISSUE TITLE
Galaxy 'My Roles' dashboard can get out of sync

### ISSUE THREAD

**Issue by dougszumski** [ansible/galaxy#205]
For example this role is currently imported into Galaxy:

![screenshot from 2017-11-24 10-14-28](https://user-images.githubusercontent.com/1140727/33205873-5e2bb13c-d100-11e7-9827-63944cd09491.png)

But in the 'My Roles' dashboard it looks like this (it doesn't help pressing the refresh button):

![screenshot from 2017-11-24 09-59-42](https://user-images.githubusercontent.com/1140727/33205305-5d7c94ba-d0fe-11e7-8d6c-bc78d4485283.png)

If I try to import the role by pressing the toggle button, I get:

```
An error occurred while attempting to start the import. Error: Request to /api/v1/imports/ resulted in 500 - INTERNAL SERVER ERROR
```

![screenshot from 2017-11-24 10-01-55](https://user-images.githubusercontent.com/1140727/33205366-97cbd090-d0fe-11e7-94b3-152fb2962396.png)

If I change the name of the role it imports without error:

![screenshot from 2017-11-24 10-03-29](https://user-images.githubusercontent.com/1140727/33205820-3518bdc6-d100-11e7-9770-ce0a5c599de3.png)

If I then update the name to the original name, the import fails with:

```
Starting import 163357: role_name=monasca-agent-2 repo=stackhpc/ansible-role-monasca-agent
Accessing branch: master
Parsing and validating meta data.
Setting role name to monasca-agent
No issue tracker defined. Enable issue tracker in repo settings, or provide an issue tracker in meta data.
Parsing galaxy_tags
Found categories in meta data. Update the meta data to use galaxy_tags rather than categories.
Parsing platforms
Parsing and validating README
Adding repo tags as role versions
Removing old tags
Import completed
Status SUCCESS : warnings=2 errors=0
Error saving role: duplicate key value violates unique constraint "main_role_namespace_36aa1070a7d8dc70_uniq" DETAIL: Key (namespace, name)=(stackhpc, monasca-agent) already exists.
```

Attempting to remove it via the CLI also doesn't seem to work:

```
doug@node:~$ ansible-galaxy delete stackhpc ansible-role-monasca-agent
Role stackhpc.ansible-role-monasca-agent not found. Maybe it was deleted previously?
```

Using the name of the role in galaxy, which has the prefix ```ansible-role``` removed (doesn't match the git repo which contains the prefix):
```
doug@node:~$ ansible-galaxy delete stackhpc monasca-agent
ERROR! Galaxy user dougszumski does not have access to repo stackhpc/monasca-agent
```

The expected behavior is:

The dashboard syncs with the current import state of the role.

**Comment by cutwater** [comment]
Looks like related of #177.

**Comment by dougszumski** [comment]
Thanks @cutwater - I agree it looks like the same issue. I managed to work around it using your procedure in #177.
