### ISSUE TITLE
new namespace request

### ISSUE THREAD

**Issue by drewmullen** [ansible/galaxy#2060]
## Namespace Request

please name it `hamr` 

##### Github Org Link
https://gitlab.com/hamr

##### Admins
@drewmullen
@terryhowe

**Comment by chouseknecht** [comment]
Done. You'll need to add `TerryHowe` as an owner after they log into Galaxy the first time.

**Comment by drewmullen** [comment]
thanks!

**Comment by TerryHowe** [comment]
I logged into Galaxy this morning @drewmullen if you need to take any more action there. Thanks.
