### ISSUE TITLE
Request namespace for Void Linux

### ISSUE THREAD

**Issue by the-maldridge** [ansible/galaxy#2065]
## Namespace Request
In order of preference:
* void
* voidlinux
* void_linux

##### Github Org Link
https://github.com/void-ansible-roles

##### Admins
the-maldridge

##### Remarks
This namespace is to be used to manage the officially provided and supported roles for Void Linux.  These roles are managed by myself and the others in the Void Linux infrastructure team.  Void is 100% Ansible managed across the fleet, and up until now we've used strictly git submodules to manage our roles, but now we'd like to offer our roles to others via Galaxy.

**Comment by the-maldridge** [comment]
cc @bobertlo for tracking.

**Comment by chouseknecht** [comment]
Namespace `void` created.

**Comment by the-maldridge** [comment]
Thanks!
