### ISSUE TITLE
curl need timeout argv, how can i do?

### ISSUE THREAD

**Issue by songruiyong** [ansible/galaxy#2066]
##### ACTUAL RESULTS

```
- name: 'check curl "http://{{ inventory_hostname }}/txxx" =>true'
      local_action: uri
        url=http://{{ inventory_hostname }}:80/txxx
        return_content=yes
      register: webpage

    - fail: msg='http://{{ inventory_hostname }}:80/txxx'
      when: "'true' not in webpage.content"

this example curlxx need a long time; 
i want  the "curl"  add timeout  argv   ,how can i  do?


```

**Comment by chouseknecht** [comment]
Try the `timeout` parameter. More information regarding the `uri` module can be [found here]( https://docs.ansible.com/ansible/latest/modules/uri_module.html?highlight=uri).

If you have additional playbook questions, view the [Communication Page](https://docs.ansible.com/ansible/latest/community/communication.html) for instructions on how to interact with the community. If you run into specific bugs, please open issues at [the Ansible project](https://github.com/ansible/ansible).

**Comment by songruiyong** [comment]
Added, implemented; thank you
