### ISSUE TITLE
Suggestion to update flake8 line length from 120 to 160

### ISSUE THREAD

**Issue by awcrosby** [ansible/galaxy#2069]
There is a suggestion to update flake8 line length from 120 to 160:

https://github.com/ansible/galaxy/blob/devel/galaxy/importer/linters/__init__.py#L26

**Comment by awcrosby** [comment]
^ @AlanCoding

**Comment by AlanCoding** [comment]
Yeah I was just looking at ansible-lint and I saw this commit

https://github.com/ansible/ansible-lint/commit/fef890e78aa26ce7d0da41f3371a4ebcdb4dac89

then in Ansible core

https://github.com/ansible/ansible/blob/5673482460d225a0f1591c2d7864b834d719f6ef/test/lib/ansible_test/_internal/sanity/pep8.py#L66

https://github.com/ansible/ansible/blob/1fbb93074771d7b0072c2e03f65b4f10d3d1100e/test/lib/ansible_test/_internal/sanity/pylint.py#L213

(this matches with my anecdotal memory of its CI)

For people migrating collections out of core, it would be nice to the churn that would come about from changing to a shorter limit.
