### ISSUE TITLE
dellemc

### ISSUE THREAD

**Issue by anil-degwekar** [ansible/galaxy#2073]
##### Github Org Link

https://github.com/dell

##### Admins

anil-degwekar, astripei70

**Comment by anil-degwekar** [comment]
We would like the namespace 'dellemc'

**Comment by thedoubl3j** [comment]
coming under us @chouseknecht we got it

**Comment by chouseknecht** [comment]
Done. Only see user `anil-degwekar`, and they have been added as an owner. That person can add `astripel70`, once they log in for the first time.
