### ISSUE TITLE
Request new Ansible Galaxy namespace

### ISSUE THREAD

**Issue by ctrufan** [ansible/galaxy#2077]
## Namespace Request
Request for an "entrust_datacard" galaxy namespace.

##### Github Org Link
https://github.com/EntrustDatacard

##### Admins
ctrufan
plalonde-edc
thadreez
tylert

**Comment by chouseknecht** [comment]
New namespace `entrust_datacard` added with owner `ctrufan`. You can add provider namespaces and additional owners from the My Content page using the Edit menu (to the right of the namespace).
