### ISSUE TITLE
Namespace Request: launchdarkly-labs

### ISSUE THREAD

**Issue by InTheCloudDan** [ansible/galaxy#2079]
##### Github Org Link
https://github.com/launchdarkly-labs

##### Admins
intheclouddan
jkodumal
bwoskow-ld
arun251
ldhenry

**Comment by chouseknecht** [comment]
Created `launchdarkly_labs` with owner `intheclouddan`. You can edit the namespace on the My Content page to add a provider namespae(s) and additional owners.

**Comment by InTheCloudDan** [comment]
@chouseknecht we are only looking to have a Collection, No roles at this time. It's not allowing me to edit namespace though because it requires `Provider Namespace`. Is there a way to update admins without connecting it to our GH Organization?
