### ISSUE TITLE
Galaxy Role Cleanup Action Required email

### ISSUE THREAD

**Issue by geerlingguy** [ansible/galaxy#208]
I received an email earlier today warning that some of my GitHub repositories were imported into duplicate Galaxy roles, and to check my 'My Roles' page on Galaxy and disable any duplicates.

I've checked through that list, but can't find any duplicates—though I have a large number of roles, so maybe I'm missing something. It'd be quite an annoyance if one of my roles (e.g. `geerlingguy.solr`, which I know has had some funky things happen when I started up my `ansible-container` project based on it) suddenly disappeared.

Is there any way I can get a list of what roles might be duplicates? I'm assuming there was a query or operation that was run on the backend to find accounts where duplicates might be an issue. Any way to run that on the `geerlingguy` namespace?

Thanks!

**Comment by hudecof** [comment]
I have received the warning too, but did not found any duplicates.

**Comment by hudecof** [comment]
my username is `hudecof`

**Comment by karlmdavis** [comment]
Same here. My Galaxy username is `karlmdavis`. I'm thinking that it's maybe that I renamed/moved one of my role's Git repos (https://galaxy.ansible.com/karlmdavis/ansible-role-jenkins2) at one point? Galaxy didn't seem to handle that very smoothly -- took a **long** while to figure out the new repo was there, lost my download count, etc.

(And thanks for filing this issue, Jeff!)

**Comment by cutwater** [comment]
We're still investigating this issue.
@hudecof, I checked database and found that you have roles `hudecof.ansible_zabbix-agent` [1] and `hudecof.zabbix-agent` [2] that seem to be duplicates. Can you please check if both of them are visible on your import screen [3]?

[1] https://galaxy.ansible.com/hudecof/ansible_zabbix-agent/
[2] https://galaxy.ansible.com/hudecof/zabbix-agent/
[3] https://galaxy.ansible.com/roleadd#/

**Comment by hudecof** [comment]
@cutwater I see only `hudecof/ansible_zabbix-agent` aka `https://galaxy.ansible.com/hudecof/ansible_zabbix-agent/`.

**Comment by chouseknecht** [comment]
@hudecof 

Here are the duplicates we're seeing:

```
 namespace |         name         | github_user |     github_repo
-----------+----------------------+-------------+----------------------
 hudecof   | zabbix-agent         | hudecof     | ansible_zabbix-agent
 hudecof   | ansible_zabbix-agent | hudecof     | ansible_zabbix-agent
```

**Comment by chouseknecht** [comment]
@karlmdavis 

Here are the duplicates we're seeing:

```
 namespace  |         name          | github_user |        github_repo
------------+-----------------------+-------------+---------------------------
 karlmdavis | ansible-role-jenkins2 | karlmdavis  | ansible-role-jenkins2
 karlmdavis | tested-bind           | karlmdavis  | ansible-role-bind-dns
 karlmdavis | bind-dns              | karlmdavis  | ansible-role-bind-dns
 karlmdavis | rcm-ansible-role      | karlmdavis  | ansible-role-rcm-dotfiles
 karlmdavis | jenkins2              | karlmdavis  | ansible-role-jenkins2
 karlmdavis | rcm-dotfiles          | karlmdavis  | ansible-role-rcm-dotfiles
 karlmdavis | ansible-role-bind-dns | karlmdavis  | ansible-role-bind-dns
```

**Comment by cutwater** [comment]
@chouseknecht Looks like duplicates appear on "Browse roles" page and in user's roles list but not on import page.

**Comment by chouseknecht** [comment]
@AdnanHodzic

Here's what we're seeing:

```
  namespace  |              name               | github_user |             github_repo
-------------+---------------------------------+-------------+--------------------------------------
 AdnanHodzic | containerized-wordpress-project | AdnanHodzic | ansible-role-containerized-wordpress
 AdnanHodzic | wordpress-docker-deploy         | AdnanHodzic | ansible-role-containerized-wordpress
 AdnanHodzic | containerized-wordpress         | AdnanHodzic | ansible-role-containerized-wordpress
 AdnanHodzic | docker-compose-setup            | AdnanHodzic | ansible-role-docker-compose-setup
 AdnanHodzic | docker-compose                  | AdnanHodzic | ansible-role-docker-compose-setup
```

**Comment by chouseknecht** [comment]
@ysz

Here's what we see for duplicates:

```
 namespace |                       name                        | github_user |          github_repo
-----------+---------------------------------------------------+-------------+--------------------------------
 ysz       | buildbot_handlers                                 | ysz         | ansible-role-buildbot_handlers
 ysz       | git-github.com-ysz-ansible-role-buildbot_handlers | ysz         | ansible-role-buildbot_handlers
```

**Comment by chouseknecht** [comment]
@cutwater 

I suppose that's because _My Roles_ is seeded from GitHub directly. Nevertheless, we still need to know which ones to delete. So if people have a preference, they need to let us know. Otherwise, I think the only thing we can do, is preserve the most recently modified versions.

**Comment by geerlingguy** [comment]
@chouseknecht thanks for the help—in that case, you can drop the following for me:

```
  namespace  |      name      | github_user |     github_repo
 geerlingguy | letsencrypt    | geerlingguy | ansible-role-certbot
 geerlingguy | ac-solr        | geerlingguy | solr-container
```

The certbot and solr-container ones are the newer / updated ones.

**Comment by AdnanHodzic** [comment]
@chouseknecht thanks for your assistance, after thorough analysis, could you **please keep**: 

```
  namespace |           name         | github_user |      github_repo
------------+------------------------+-------------+------------------------------------
AdnanHodzic | containerized-wordpress| AdnanHodzic | ansible-role-containerized-wordpress
AdnanHodzic | docker-compose         | AdnanHodzic | ansible-role-docker-compose-setup
```
While rest of them can be dropped:

```
wordpress-docker-deploy
docker-compose-setup
wordpress-docker-deploy
```

**Comment by hudecof** [comment]
@chouseknecht 

**keep**

```
 namespace |         name         | github_user |     github_repo
-----------+----------------------+-------------+----------------------
 hudecof   | ansible_zabbix-agent | hudecof     | ansible_zabbix-agent
```

**Comment by chouseknecht** [comment]
@geerlingguy 
@AdnanHodzic 
@hudecof 

Manually removed the unwanted roles. You guys are now fine, and will not be effected.

**Comment by chouseknecht** [comment]
@cutwater 

Here are the deletes I had to do in order to manually remove a role:

```
delete from main_importtaskmessage where task_id in (select id from main_importtask where role_id in (767));

delete from main_notification_imports where importtask_id in (select id from main_importtask where role_id in (767));

delete from main_importtask where role_id in (767);

delete from main_notification_roles where role_id in (767);

delete from main_role_tags where role_id in (767);

delete from main_roleversion where role_id in (767);

delete from main_role_platforms where role_id in (767);

delete from main_role_dependencies where from_role_id in (767);

delete from main_role_categories where role_id in (767);

delete from main_rolerating where role_id in (767);

delete from main_role where id in (767);
```
Use the above as a guide for adding `cascade on delete` to foreign keys.

**Comment by cutwater** [comment]
@chouseknecht Thanks for deleting requested roles manually. Remaining duplicates will be automatically removed by #220

**Comment by chouseknecht** [comment]
Manually fixed the one duplicate for @ysz. We exchanged emails, and determined that `git-github.com-ysz-ansible-role-buildbot_handlers` was the one to remove.

**Comment by karlmdavis** [comment]
@chouseknecht Thanks for the list! Looks like my dupes were caused by me renaming the GitHub repos to try and match Galaxy's naming conventions. Which of these has been updated most recently? I'm guessing that the most active versions are `bind-dns`, `jenkins2`, and `rcm-dotfiles`? If so, please drop the other, stale ones.

```
 namespace  |         name          | github_user |        github_repo
------------+-----------------------+-------------+---------------------------
 karlmdavis | tested-bind           | karlmdavis  | ansible-role-bind-dns
 karlmdavis | ansible-role-bind-dns | karlmdavis  | ansible-role-bind-dns
 karlmdavis | bind-dns              | karlmdavis  | ansible-role-bind-dns
 karlmdavis | ansible-role-jenkins2 | karlmdavis  | ansible-role-jenkins2
 karlmdavis | jenkins2              | karlmdavis  | ansible-role-jenkins2
 karlmdavis | rcm-ansible-role      | karlmdavis  | ansible-role-rcm-dotfiles
 karlmdavis | rcm-dotfiles          | karlmdavis  | ansible-role-rcm-dotfiles
```

**Comment by cutwater** [comment]
All duplicates were automatically deleted as 2.4 released.
