### ISSUE TITLE
My provider namespace is missing for my personal github

### ISSUE THREAD

**Issue by cfawcett82** [ansible/galaxy#2080]
##### Github Org Link

https://github.com/cfawcett82
##### Admins

myself (cfawcett82)

**Comment by chouseknecht** [comment]
It seems to exist. https://galaxy.ansible.com/cfawcett82. The namespace is associated with `https://github.com/cfawcett82` as well.

What problem are you experiencing exactly?

**Comment by cfawcett82** [comment]
Please close it resolved itself some how. 

Thanks.
