### ISSUE TITLE
import role: running over 17 hours, no feedback provided on delay provided

### ISSUE THREAD

**Issue by cfawcett82** [ansible/galaxy#2082]
##### SUMMARY
trying to import role, not failing, not finishing either.
https://galaxy.ansible.com/cfawcett82/linux_join_domain_role_survey
##### STEPS TO REPRODUCE
Unknown, as this is my first attempt at importing a role.
##### EXPECTED RESULTS
import to fail after a period of time, and provide details of the failure and next steps required.
##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/43487784/67947836-896ec800-fbb2-11e9-972f-998d639c4215.png)

**Comment by AttilioGreco** [comment]
Same issue,
For me is not the frist role, problem start yesterday

![Schermata da 2019-10-31 14-12-05](https://user-images.githubusercontent.com/6053820/67949770-9a3a3080-fbe8-11e9-876d-521175c99661.png)

**Comment by cfawcett82** [comment]
so might be bad timing.

**Comment by chouseknecht** [comment]
Looking into it...

**Comment by cutwater** [comment]
@cfawcett82 @AttilioGreco Thank you for reporting this issue. We had a problem with our environment, now it's successfully resolved. All pending imports have been cancelled. Please restart your imports.
