### ISSUE TITLE
fiaasco namespace is unusable

### ISSUE THREAD

**Issue by stroobl** [ansible/galaxy#2087]
##### SUMMARY
A few weeks ago I opened # #2028 for a rename issue of the fiaas namespace. This issue was closed, but the namespace is still not ok.

##### STEPS TO REPRODUCE
Try to add the fiaasco namespace:
My content > fiaasco > edit properties:
Provider namespaces: select fiaasco
Save.

##### EXPECTED RESULTS
Namespace is added.

##### ACTUAL RESULTS
Error! Error creating or updating provider namespaces: get() returned more than one ProviderNamespace -- it returned 9! (undefined) 

![fiaas-namespace](https://user-images.githubusercontent.com/9917025/68017384-e2179100-fc96-11e9-83e6-5231cc8bff0c.png)

**Comment by chouseknecht** [comment]
Think I have it fixed. The namespace `fiaasco` in Galaxy is now owned by `stroobl` and shows the correct GitHub provider namespace of `fiaasco`.

**Comment by stroobl** [comment]
Indeed, I'm able to import roles again. Thanks @chouseknecht !
