### ISSUE TITLE
Add Ubuntu 19.10 Eoan Ermine platform

### ISSUE THREAD

**Issue by albers** [ansible/galaxy#2090]
## Feature Request

Ansible Galaxy does not support the current Ubuntu release [19.10](http://releases.ubuntu.com/19.10/):

These queries do not find any matches:
- https://galaxy.ansible.com/api/v1/platforms/?release__icontains=eoan
- https://galaxy.ansible.com/api/v1/platforms/?release__icontains=ermine

Please add it to the list of supported platforms.

**Comment by chouseknecht** [comment]
Added.
