### ISSUE TITLE
Duplicate provider namespaces: smartopsacademy

### ISSUE THREAD

**Issue by slapic** [ansible/galaxy#2092]
Somehow I have two provider namespaces: SmartOpsAcademy and smartopsacademy (the difference is just the case). I can't add "smartopsacademy" to my smartopsacademy namespace because "SmartOpsAcademy" is attached to my personal (slapic) namespace. I can't remove "SmartOpsAcademy" from my personal namespace either. Looks like the "SmartOpsAcademy" provider namespace is stalled. Could you remove it? Thank you!

##### Github Org Link
https://github.com/smartopsacademy

##### Admins
slapic

**Comment by chouseknecht** [comment]
Moved `smartopsacademy` provider namespace under the `smartopsacademy` namespace. This should be resolved now.
