### ISSUE TITLE
Nutanix-Ansible playbook error

### ISSUE THREAD

**Issue by jhuynh08** [ansible/galaxy#2094]
##### SUMMARY
When I try to run the role for mbach04.nutanix_vm_provisioner I am getting an error at one of the task. Full disclaimer: I'm pretty new to Ansible. The github location for the playbook I'm using is: 

https://github.com/mbach04/nutanix_vm_provisioner

My test.yml script:

---
- name: Provision some VMs
  hosts: localhost
  gather_facts: false
  vars:
    my_vms:
      - {vm_name: server1, vm_ip: 'XXX.XXX.XXX.XXX', vm_ram: 4096, vm_num_cpu_per_socket: 1, vm_num_sockets: 4, vm_disk_list: [disk_size_mib: 76294, disk_size_mib: 152588]}
  tasks:
    - name: Provision VMs on Nutanix
      include_role:
        name: nutanix_provisioner
      vars:
        vm_defs: "{{ my_vms }}"

##### STEPS TO REPRODUCE
1. run ansible-playbook test.yml command
2. All the task oks until it gets to the "create face with VM template contents"

##### EXPECTED RESULTS
It should in theory create a VM template

##### ACTUAL RESULTS

TASK [nutanix_provisioner : Create fact with VM template contents] **************************************************************************************************************************************************************************
fatal: [10.71.30.80]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'iteritems'\n\nThe error appears to be in '/etc/ansible/roles/nutanix_provisioner/tasks/provision_vm.yml': line 11, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create fact with VM template contents\n  ^ here\n"}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
10.71.30.80                : ok=11   changed=0    unreachable=0    failed=1    skipped=5    rescued=0    ignored=0

```

**Comment by chouseknecht** [comment]
Looks like an issue for the role author.
