### ISSUE TITLE
Namespace request: caddy-ansible

### ISSUE THREAD

**Issue by lbischof** [ansible/galaxy#2096]
##### Github Org Link
https://github.com/caddy-ansible

##### Admins
lbischof, joelnb

Please also move the current ansible-galaxy repository: https://galaxy.ansible.com/antoiner77/caddy to the new namespace.

**Comment by chouseknecht** [comment]
Done.

**Comment by chouseknecht** [comment]
The actual namespace name is `caddy_ansible`

**Comment by lbischof** [comment]
@chouseknecht Thank you very much. I get 'Missing provider namespaces.' when I try to 'Add Content' with Github.
