### ISSUE TITLE
Unable to login to Galaxy web - Server Error (500)

### ISSUE THREAD

**Issue by lalitjoshi29** [ansible/galaxy#2098]
##### ACTUAL RESULTS

```

```

**Comment by lalitjoshi29** [comment]
I'm trying to login to Ansible Galaxy web via https://galaxy.ansible.com/login . After clicking to GitHub icon, I receive Server Error (500) . 

I already tried to clean my cookies and revoke Authorization to Galaxy on GitHub but no change happened. I tried other browsers also but no luck.

**Comment by lalitjoshi29** [comment]
my git hub user name is : lalitjoshi29

**Comment by chouseknecht** [comment]
Not finding anything related to your account in our database, so not sure what's causing the issue. Did you happen to change your GitHub username at some point, and if so, what was the old username?

**Comment by chouseknecht** [comment]
There's been no response. Please open a new issue, if you require further assistance.
