### ISSUE TITLE
Infinera

### ISSUE THREAD

**Issue by dnaik-infinera** [ansible/galaxy#2100]
## Namespace Request
Infinera

##### Github Org Link

https://github.com/infinera 

##### Admins

 dnaik-infinera dnaik@infinera.com

**Comment by dnaik-infinera** [comment]
Need help to create namespace for our company on galaxy
https://galaxy.ansible.com/infinera namespace.

I get the following error when I try to add infinera namespace to galaxy using the following instructions. 

https://galaxy.ansible.com/docs/contributing/namespaces.html#galaxy-namespace-requests 

Save gives the following error. 
Error! This provider namespace is already associated with a Galaxy namespace (infinera)

**Comment by chouseknecht** [comment]
Done. Added the namespace `infinera`.
