### ISSUE TITLE
Applying to be the owner of https://galaxy.ansible.com/fortinet

### ISSUE THREAD

**Issue by jamie-pate** [ansible/galaxy#2103]
## Namespace Request

https://galaxy.ansible.com/fortinet 

##### Github Org Link
https://github.com/fortinet

##### Admins

github accounts: `jamie-pate`, `fgtdev-hblu` and `frankshen01`

**Comment by chouseknecht** [comment]
Additional users added to `fortinet`

**Comment by jamie-pate** [comment]
I suppose I should have requested the `fortinet` account be added too? The instructions say that it should be available in the `Provider Namespaces` field of the `Edit Namespace` page
