### ISSUE TITLE
Cannot Edit Properties on Namespace.

### ISSUE THREAD

**Issue by InTheCloudDan** [ansible/galaxy#2104]
## Bug Report 
Cannot `Edit Properties` on namespace because it is not connected to Github Org it seems. We have a collection for `launchdarkly_labs` that I cannot edit even though I'm the admin because I'm not selecting a `Provider Namespace` because we have no plans to have a role at this time. `Save` is grayed out because of the provider namespace not being selected but neither of them apply to this.

##### STEPS TO REPRODUCE
Be added to a new collection but not link that collection with oauth to a Github Org.

##### EXPECTED RESULTS
That I could go under `Edit Properties` and make changes then be able to `Save` them.

##### ACTUAL RESULTS
`Save` button is grayed out.

**Comment by chouseknecht** [comment]
Just add a provider namespace. You're not required to upload a role.

**Comment by InTheCloudDan** [comment]
@chouseknecht so I can use my own namespace and it won't cause any other issues? I only see 2 `Provider Namespaces` available. `InTheCloudDan` and `Ansible`. I'm not sure how the provider namespace in edit properties is used throughout the system.

**Comment by chouseknecht** [comment]
You can add provider namespaces, and it won't cause issues. Or, I can make the edits as an admin, if you communicate what you want changed.

**Comment by InTheCloudDan** [comment]
I don't have any option to add provider namespaces. I'm looking to add the metadata info of company name, location, homepage and avatar. And also add admins. There's no way to do this without oauth to the org?

**Comment by chouseknecht** [comment]
If you provide the values you want, we can set them for you. Otherwise, you'll need to add a GitHub org.

**Comment by InTheCloudDan** [comment]
@chouseknecht thanks for your help on this, we just went ahead with allowing access.
