### ISSUE TITLE
Ansible network community namespaces

### ISSUE THREAD

**Issue by pabelanger** [ansible/galaxy#2106]
## Namespace Request
Greetings, we are looking to start publishing the ansible network collections to the following namespaces:

aristsa.eos
cisco.ios
cisco.iosxr
cisco.nxos
juniper.junos
network.cli
network.netconf

As such, can I be added as admin on these repos.

##### Github Org Link
https://github.com/pabelanger

##### Admins

pabelanger

**Comment by chouseknecht** [comment]
Done. You're now an owner on the following namespaces in Community Galaxy: `cisco`, `arista`, `juniper`, `network`
