### ISSUE TITLE
Unable to publish juniper.junos community collection

### ISSUE THREAD

**Issue by pabelanger** [ansible/galaxy#2107]
##### SUMMARY

We are currently seeing the following error from galaxy when we try to publish the community juniper.junos collection.

localhost | ERROR! Error when publishing collection to release_galaxy (https://galaxy.ansible.com/api/) (HTTP Code: 400, Message: Namespace "juniper" does not exist. Code: invalid)

https://object-storage-ca-ymq-1.vexxhost.net/v1/a0b4156a37f9453eb4ec7db5422272df/ansible_07/078927906a92dc7ad9ce1074f655ac097dee2a4e/post/release-ansible-collection-galaxy/e594474/job-output.html#l792

However, the namespace exists: https://galaxy.ansible.com/juniper

##### STEPS TO REPRODUCE

/opt/venv/zuul-ansible/2.9.1/bin/ansible-galaxy collection publish /var/lib/zuul/builds/e5944740d9a241a4852dbb571e741725/work/artifacts/juniper-junos-0.0.1-dev40.tar.gz

Publishing collection artifact '/var/lib/zuul/builds/e5944740d9a241a4852dbb571e741725/work/artifacts/juniper-junos-0.0.1-dev40.tar.gz' to release_galaxy https://galaxy.ansible.com/api/
ERROR! Error when publishing collection to release_galaxy (https://galaxy.ansible.com/api/) (HTTP Code: 400, Message: Namespace "juniper" does not exist. Code: invalid)

##### ACTUAL RESULTS

```

```

**Comment by chouseknecht** [comment]
The namespace was actually `Juniper` with a capital `J`. It's now `juniper` with a lowercase `j`. See if that fixes the issue.

**Comment by pabelanger** [comment]
@chouseknecht thanks! Just to confirm before we try again, this should results in 2 things on galaxy using juniper.junos right? One role, which exists today and the new collection we are about to upload.

**Comment by abenokraitis** [comment]
But when you view the page on Galaxy web, it redirects regardless of case AFAIK

**Comment by pabelanger** [comment]
Tested, we are not able to publish a collection if a role exists with the same name. How do we proceed here for the community juniper.junos collection?

**Comment by chouseknecht** [comment]
Thinking we've resolved this internally by now. Closing.
