### ISSUE TITLE
Add me to CSCfi namespace

### ISSUE THREAD

**Issue by martbhell** [ansible/galaxy#2110]
##### SUMMARY

Hello!

Under content I see CSC-IT-Center-for-Science and I can't add the CSCfi namespace as it's already in use somewhere. 
A few years ago the github organization was renamed.
If possible could we remove CSC-IT-Center-for-Science, add all the users from the "CSC-IT-Center-for-Science" and add those to the CSCfi namespace?
I have tried to revoke the galaxy access in github and relogin - still can't see the CSCfi content in galaxy.

##### ACTUAL RESULTS

```

```

**Comment by chouseknecht** [comment]
You're now an owner on `CSCfi`.
