### ISSUE TITLE
Error adding a new admin to a namespace

### ISSUE THREAD

**Issue by thedoubl3j** [ansible/galaxy#2114]
##### SUMMARY

Attempted to admin namespace "CumulusNetworks" and when I add a new admin and attempt to save, I get an error saying ```Error! This provider namespace is already associated with a Galaxy namespace (CumulusNetworks)```
##### STEPS TO REPRODUCE

Add a new admin to the namespace, click save. 

##### EXPECTED RESULTS

The admin is added to the namespace correctly.
##### ACTUAL RESULTS

Failure with message saying 

```
Error! This provider namespace is already associated with a Galaxy namespace (CumulusNetworks)
```

**Comment by chouseknecht** [comment]
Removed `cumulusnetworks` and added `shokxi` as an owner to `CumulusNetworks`.
