### ISSUE TITLE
namespace: community

### ISSUE THREAD

**Issue by gundalow** [ansible/galaxy#2115]
## Namespace Request
`community`

##### Github Org Link
Is this needed just to reserve the namespace?

##### Admins
@gundalow
@pabelanger

**Comment by pabelanger** [comment]
Can you also add me as an admin? This will be used by zuul for now to handle our uploads.

**Comment by gundalow** [comment]
Also @pabelanger made a good point, how will this impact https://galaxy.ansible.com/community

**Comment by chouseknecht** [comment]
Created `community` namespace with `pabelanger` as owner. Don't see user `gundalow` in Galaxy.
