### ISSUE TITLE
New version of a role not available, despite showing on galaxy.ansible.com

### ISSUE THREAD

**Issue by jonpugh** [ansible/galaxy#2116]
##### SUMMARY

The latest version of `geerlingguy.php` according to [Galaxy Web](https://galaxy.ansible.com/geerlingguy/php) and [GitHub.com Releases](https://github.com/geerlingguy/ansible-role-php/releases) is `3.7.0`.

But when you go to install it from the CLI, you get `3.6.3`.

This also causes a failure when running `ansible-galaxy install` with a requirements.yml file that tries to use 3.7.0.

##### STEPS TO REPRODUCE

```
ansible-galaxy install geerlingguy.php
```

##### EXPECTED RESULTS

Installs latest version: 3.7.0.

##### ACTUAL RESULTS
Installs older version: 3.6.3.
```
$ ansible-galaxy install geerlingguy.php
- downloading role 'php', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-php/archive/3.6.3.tar.gz
- extracting geerlingguy.php to /home/jon/.ansible/roles/geerlingguy.php
- geerlingguy.php (3.6.3) was installed successfully
```

##### Error with requirements.yml install.

If 3.7.0 is in your requirements file, it throws an error that the version is not in the list:

```yml
# requirements.yml
- src: geerlingguy.php
  version: 3.7.0
```
```
ansible-galaxy install -r requirements.yml
- downloading role 'php', owned by geerlingguy
[WARNING]: - geerlingguy.php was NOT installed successfully: - the specified version (3.7.0) of geerlingguy.php was not found in the list of
available versions ([{'id': 54757, 'url': '', 'related': {}, 'summary_fields': {}, 'created': '2018-03-10T17:18:34.585842Z', 'modified':
'2018-06-29T23:05:53.594377Z', 'name': '3.5.1', 'version': '3.5.1', 'commit_date': '2018-03-10T12:14:33-05:00', 'commit_sha': None,
'download_url': 'https://github.com/geerlingguy/ansible-role-php/archive/3.5.1.tar.gz', 'active': None}, {'id': 22326, 'url': '', 'related':
...
```

First reported in https://github.com/geerlingguy/ansible-role-php/issues/283
cc @geerlingguy

**Comment by geerlingguy** [comment]
@jonpugh - This was fixed in Ansible 2.9.1; see related issues:

  - https://github.com/ansible/galaxy/issues/2089
  - https://github.com/ansible/ansible/issues/64355
  - Fixed in: https://github.com/ansible/ansible/pull/64373

Closing this issue, but please feel free to re-open if you find that 2.9.1 is not working as well. 2.9.0 was the only version I encountered the problem with (and it caused about 40 of my CI builds to fail for a couple weeks!).

**Comment by jonpugh** [comment]
Thanks a ton. I was installing ansible with `pip install molecule docker` which is still resulting in ansible 2.9.0 in some places!

**Comment by jonpugh** [comment]
Uh oh...

Am I seeing it happen with Ansible 2.9.1 here?

https://github.com/opendevshop/devshop/pull/430/checks?check_run_id=320467291#step:5:48

Looks like. I added ansible and ansible-galaxy --version just to be sure: 

![Screenshot from 2019-11-25 21-43-21](https://user-images.githubusercontent.com/106420/69595143-b43f1700-0fcc-11ea-8638-52334685f272.png)

**Comment by geerlingguy** [comment]
@jonpugh 3.7.1 doesn't exist (yet): https://github.com/geerlingguy/ansible-role-php/releases

**Comment by jonpugh** [comment]
😭 Sorry.

I don't know how that happened!

thanks, jeff

**Comment by henvo** [comment]
Hey,

I am using
```
ansible-galaxy --version
ansible-galaxy 2.9.6
```
on Ubuntu.

And in my requirements.yml i have
``` yaml
---
roles:
  - name: oefenweb.fail2ban
    version: 3.3.15
```

When running
```
ansible-galaxy install -r requirements.yml
```

I get this error:
```
- downloading role 'fail2ban', owned by oefenweb
[WARNING]: - oefenweb.fail2ban was NOT installed successfully: - the specified version (3.3.15) of oefenweb.fail2ban was not found in the list of available versions
```

I already switched to other versions. But still not working. Can anyone help me out here?

**Comment by nleiva** [comment]
Hi @henvo,  I just run into the same issue and my Google search got me here, so I'm documenting what I found out.

It turns out the version has to be an exact match. For some roles, the version [is not a semantic version](https://semver.org/#is-v123-a-semantic-version) as they prefix it with a “v”. For your `requirements.yml` file to work you need to include the "v", like this:

```yaml
---
roles:
  - name: oefenweb.fail2ban
    version: v3.3.15
```
