### ISSUE TITLE
Namespace request for usegalaxy-eu

### ISSUE THREAD

**Issue by erasche** [ansible/galaxy#2117]
##### Github Org Link

https://github.com/usegalaxy-eu

##### Admins

- @erasche
- @natefoo
- @bgruening
- @gmauro

Thanks so much!

**Comment by chouseknecht** [comment]
Done.

**Comment by erasche** [comment]
Thanks so much!

Op ma 2 dec. 2019 15:47 schreef Chris Houseknecht <notifications@github.com
