### ISSUE TITLE
Feature Request: Install an Ansible collection from a git repository URI instead of local filesystem

### ISSUE THREAD

**Issue by pcgeek86** [ansible/galaxy#2118]
## Feature Request

[Originally posted on StackOverflow](https://stackoverflow.com/questions/59003007/install-ansible-collections-directly-from-a-git-uri-with-ansible-galaxy)

### Use Case
Deploy an Ansible collection, without having to separately clone and clean-up a git repository with a wrapper script.

### Proposed Solution
When I run `ansible-galaxy collection install`, I would like to be able to specify a URI to a git repository, instead of the path to a local directory on a filesystem. I would expect the `-p` parameter to interpret a remote URI (ie. ssh or https protocols) and treat the URI as a git repository, instead of a local folder.

### Alternatives
I'm still learning about Ansible Galaxy and collections, so I'm not sure what alternative options might be available. I'm open to learning about them, though.

### Implementation

N/A

**Comment by chouseknecht** [comment]
The `ansible-galaxy` CLI is part of the [Ansible](https://github.com/ansible/ansible) project, so any related issues need to be filed there.
