### ISSUE TITLE
Namespace request for Raine.ai

### ISSUE THREAD

**Issue by evelineraine** [ansible/galaxy#2119]
##### Github Org Link
https://github.com/raine-ai

##### Admins
- evelineraine

P. S. Could you also let me know beforehand how do you convert the Org name to namespace (does **raine.ai** turn into `raine-ai` or `raine_ai` or `raineai`) and whether I'm able to choose? Thanks!

**Comment by chouseknecht** [comment]
New namespace is `raine_ai`.
