### ISSUE TITLE
namespace request: scaleway

### ISSUE THREAD

**Issue by remyleone** [ansible/galaxy#2125]
##### Github Org Link

github.com/scaleway

##### Admins

@jerome-quere
@remyleone
@kindermoumoute 
@QuentinBrosse
@loicbourgois

**Comment by chouseknecht** [comment]
The username `remyleone` does not exist in Galaxy. Did you use a different GitHub account or perhaps you changed your username?

**Comment by remyleone** [comment]
I changed my username. It used to be `sieben` in the past.

**Comment by chouseknecht** [comment]
Namespace `scaleway` created with `sieben` as the owner. You can edit the namespace and add additional owners.
