### ISSUE TITLE
We'd love to have a namespace for MageOps 

### ISSUE THREAD

**Issue by pinkeen** [ansible/galaxy#2126]
## Namespace Request

Hello,

On behalf of creativestyle Polska I'd like to request creation of MageOps namespace.

We're in the process of opensourcing our cloud infrastructure/ci code for hosting and developing Magento-based shops. 

There's not much in the MageOps org yet and the site is not ready for the time being. We've already opensourced most of our Magento related code though, what you can examine at:
- https://magesuite.io/
- https://github.com/magesuite

If further verification is necessary that you can check the Whois records for the following domains:
- mageops.sh
- mageops.pro

##### Github Org Link
https://github.com/mageops

##### Admins
krisdante, szpadel, pinkeen

**Comment by chouseknecht** [comment]
New namespace `mageops` created.
