### ISSUE TITLE
netapp_uk_ps

### ISSUE THREAD

**Issue by bjake1878** [ansible/galaxy#2129]
## Namespace Request
netapp_uk_ps
##### Github Org Link
https://github.com/bjake1878/ansible_collections_netapp_uk_ps

##### Admins
bjake1878
markrob

**Comment by chouseknecht** [comment]
There's already a `netapp` namespace. This looks suspicious.

**Comment by bjake1878** [comment]
Hi

Yes there is already a netapp namespace for engineering we were hoping to create a separate one for NetApp UK professional services, the department I work in.

Regards,
Ben Jakeman

Mobile +44(0) 7584 102937

**Comment by bjake1878** [comment]
Will it be possible to have this namespace or is there a process when requesting this type of namespace?

**Comment by chouseknecht** [comment]
Namespace `netapp_uk_ps` created with `bjake1878` as owner.
