### ISSUE TITLE
Request for a namespace barracudanetworks

### ISSUE THREAD

**Issue by aravindan-barracuda** [ansible/galaxy#2134]
## Namespace Request
Please add the namespace "barracudanetworks" as we would like to publish the role with this namespace. Currently the role is published with the individual's name space i.e aravindan_barracuda, which needs to be changed to barracudanetworks.
##### Github Org Link
https://github.com/barracudanetworks

##### Admins
aravindan@barracuda.com

**Comment by chouseknecht** [comment]
Namespace `barracudanetworks` created with `aravindan-barracuda` as the owner.
