### ISSUE TITLE
Create a new namespace on Galaxy for Nokia

### ISSUE THREAD

**Issue by wisotzky** [ansible/galaxy#2135]
##### Github Org Link
https://github.com/nokia

##### Admins
wisotzky <sven.wisotzky@nokia.com>

**Comment by wisotzky** [comment]
I can see a provider namespace called "Nokia" in my profile:
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/10410757/70148704-f50eee00-16a6-11ea-92a3-beda5ba5f436.png">

**Comment by wisotzky** [comment]
Also seeing it right here:
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/10410757/70148760-1374e980-16a7-11ea-90ce-2d0f00cc6dd5.png">

**Comment by wisotzky** [comment]
But when trying to upload, I am getting this:
<img width="620" alt="image" src="https://user-images.githubusercontent.com/10410757/70148832-3901f300-16a7-11ea-9b9b-717a29300eb1.png">

**Comment by wisotzky** [comment]
Just guessing, the namespace was not yet properly created in Galaxy - so all I am seeing is coming from Nokia GitHub.

**Comment by chouseknecht** [comment]
Namespace `nokia` created with `wisotzky` as the owner.

**Comment by wisotzky** [comment]
Could you please add the following Avatar for Nokia organisation:
https://raw.githubusercontent.com/nokia/nsp-workflow/master/logo.png
