### ISSUE TITLE
ansible-galaxy collection build needs way to override version

### ISSUE THREAD

**Issue by ssbarnea** [ansible/galaxy#2143]
### Use Case
Collections are sometimes by-product of bigger projects which may control versioning in a different way, like git tags.

For example in use cases I encountered so far with OpenStack teams we almost always had a python based repository model where running `python setup.py --version` in its root would return a valid version string, usually based on last git tag plus number of commits after, like `0.6.2.dev4`. If we can make galaxy make use of this and produce same versioning it would be great.

### Proposed Solution
There are two possible solutions:
1. Add an option to override version at build time, like `ansible-galaxy collection build --version 1.2.3`
2. Allow environmental variable expansion inside `galaxy.yml` so we can put something like `version: ${VERSION}`. This can be implemented using shell like expansion or jinja2.

### Alternatives
Generating the `galaxy.yml` before doing the effective build is quite inconvenient as it breaks the development workflow making impossible to just build it.

### Implementation
Once we agree on how this should be addressed I could propose a CR implementing it.

**Comment by geerlingguy** [comment]
I agree, this is the most annoying aspect of using CI processes to automatically release new versions of my collections. Hacking around with YAML file output in bash or even via an Ansible playbook is not that fun in the best of times.

**Comment by cfedde** [comment]
Every artifact used in a large system must be branded with a version.   The version number is how you let downstream users know the status of the code and what features it has.  However you choose to implement versioning and release management for your system I need to know that when I download a release I can access a static version string in the  galaxy.yml file.

**Comment by pabelanger** [comment]
In network, we remove the version string from our galaxy.yaml files, and at collection build time generate. This is for the same use case above:

  https://github.com/ansible-network/releases/blob/master/ansible_releases/cmd/generate_ansible_collection.py

I would like to see this pushed up into ansible-galaxy by default.

**Comment by chouseknecht** [comment]
This issue should be filed in the [Ansible project](https://github.com/ansibl/ansible/issues).

**Comment by abenokraitis** [comment]
@ssbarnea Since the `ansible-galaxy` utility is distributed as part of the base Ansible distribution, this should be filed there instead. Thanks!

**Comment by chouseknecht** [comment]
As noted above, this should be filed in the Ansible project. Closing.

**Comment by geerlingguy** [comment]
@ssbarnea - Are you wanting to open an issue in ansible/ansible? If not, I'd like to, just to make sure we don't lose momentum on this.

**Comment by geerlingguy** [comment]
Created https://github.com/ansible/ansible/issues/65920 over in ansible/ansible
