### ISSUE TITLE
Community namespace vs Community authors

### ISSUE THREAD

**Issue by gundalow** [ansible/galaxy#2149]
## Feature Request

`community` will the used as the namespace for most of the content that lives in github.com/ansible-collections/, as requested in https://github.com/ansible/galaxy/issues/2115

However `community` has some special meanings in Galaxy, such as:
* https://galaxy.ansible.com/community

Which need to be moved elsewhere.

**Comment by chouseknecht** [comment]
Duplicate of #2145
