### ISSUE TITLE
Update cached GitHub user name

### ISSUE THREAD

**Issue by gundalow** [ansible/galaxy#2150]
##### SUMMARY
When I first signed up to Galaxy in 2013-12-20 my username was bob-smith, though that was changed a long time ago, Galaxy seems to have cached that

##### STEPS TO REPRODUCE

https://galaxy.ansible.com/api/v1/users/?search=bob-smith

##### EXPECTED RESULTS
https://galaxy.ansible.com/api/v1/users/?search=gundalow

**Comment by chouseknecht** [comment]
Changed to `gundalow`. Ping me on Slack, if it doesn't work.
