### ISSUE TITLE
Only github, why?

### ISSUE THREAD

**Issue by hartpvn** [ansible/galaxy#2151]
### Use Case
I want use galaxy in localnet. I want use galaxy support gitlab.

### Proposed Solution
Just do support

**Comment by hartpvn** [comment]
Please explain why you categorically refuse to do this?

**Comment by chouseknecht** [comment]
Well, for one, adding additional OAuth services, like Gitlab, takes resources. Our team is focused on other business initiatives, like building [Automation Hub](https://www.ansible.com/products/automation-hub).

Secondly, we introduced Collections as one way to at least enable content authors to use whatever SCM platform they like for managing code. With a Collection, you publish an artifact to Galaxy, which allows your code to be hosted anywhere. Unlike a Role, Galaxy does not require access to the source repository. Host your code on Gitlab, for example, build an artifact, and publish it to Galaxy. [More on Collections can be found here](https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html#developing-collections).

**Comment by hartpvn** [comment]
Thanks for the answer, I understand.
