### ISSUE TITLE
Namespace Request: rename slingcsm 

### ISSUE THREAD

**Issue by wildone** [ansible/galaxy#2153]
## Namespace Request
I am so sorry I made a typo when I made the original request and update admins.

Can you please rename https://galaxy.ansible.com/slingcsm to slingcms.

Github Org Link
https://github.com/slingcms

Admins
https://github.com/devops-slingcms
https://github.com/wildone

**Comment by chouseknecht** [comment]
Done. The namespace is now `slingcms`.
