### ISSUE TITLE
Namespace Request: justereseau

### ISSUE THREAD

**Issue by lucasmaurice** [ansible/galaxy#2154]
## Namespace Request
justereseau

##### Github Org Link
https://github.com/justereseau

##### Admins
lucasmaurice
AleRousse

**Comment by gundalow** [comment]
@lucasmaurice Thank you for the request:
I don't see `AleRousse`, have they logged into galaxy.ansible.com?

Namespace created

**Comment by lucasmaurice** [comment]
Apparently he's not already signed up, I'll do it later. Thanks!
