### ISSUE TITLE
Request a Namespace for Mellanox (Ansible-Onyx)

### ISSUE THREAD

**Issue by samerd** [ansible/galaxy#2155]
##### Github Org Link

https://github.com/Mellanox
##### Admins

samerd@github.com

**Comment by chouseknecht** [comment]
User `samerd` doesn't exist in Galaxy.

**Comment by gundalow** [comment]
https://github.com/ansible/galaxy/pull/2158 updates the issue template to make it clearer that users should log into to Galaxy to create their account.

**Comment by gundalow** [comment]
@samerd Hi, could you please log into Galaxy via https://galaxy.ansible.com/login which will create your account.

**Comment by samerd** [comment]
> @samerd Hi, could you please log into Galaxy via https://galaxy.ansible.com/login which will create your account.

Done!
Thanks a lot

**Comment by chouseknecht** [comment]
Namespace `mellanox` created.
