### ISSUE TITLE
Namespace Request

### ISSUE THREAD

**Issue by sandvige** [ansible/galaxy#2156]
##### Github Org Link
https://github.com/rgsystemes

##### Admins
@sandvige
@bbalzola
@fidanf

Thanks :heart:

**Comment by gundalow** [comment]
Just to clarify, do you want the namespace to be `rgsystemes`?

**Comment by gundalow** [comment]
I don't see a user for `bbalzola` have they logged into galaxy.ansible.com

**Comment by sandvige** [comment]
Hello, bbalzola created its account, and yes we want the namespace to be rgsystemes

**Comment by fidanf** [comment]
Bump

**Comment by chouseknecht** [comment]
Namespace `rgsystemes` created.
