### ISSUE TITLE
ansible-galaxy install requirements.yml doesn't work with github when version is not master

### ISSUE THREAD

**Issue by luckeyca** [ansible/galaxy#2159]
##### SUMMARY
ansible-galaxy install fails when version in the requirements.yml is a non-master branch name. It used to work. now only works when version is a master branch name, a tag or a commit hash.

##### STEPS TO REPRODUCE
1. create a standard requirements.yml with any standard test ansible roles similar as below

- name: ansible-ping-hosts
  src: git+https://url-to-test-role-repo.git
  scm: git
  version: test

2. run command: ansible-galaxy install -f -r requirements.yml

##### EXPECTED RESULTS
The roles defined in requirements.yml should be installed successfully.

##### ACTUAL RESULTS
The roles only install correctly when the version in requirement.yml is the default value: master or a tag. When it's non-master branch or a commit hash, the installation fail. Technically as per ansible documentation, the allowed value for version attribute in requirements.yml are branch names, tag or commit hash. Right now only master branch, tag and commit hash work, non-master branch doesn't which used to work. This problem exists with both ansible 2.7 and 2.9.1

```
[WARNING]: - ansible-ping-hosts was NOT installed successfully: - command /usr/local/bin/git checkout test failed in directory /home/vagrant/.ansible/tmp/ansible-local-37771fhsd3ir/tmp1pbq52ad/ansible-ping-hosts (rc=128)

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

```

**Comment by chouseknecht** [comment]
Thank you for taking the time to report this bug. Since `ansible-galaxy` is part of core Ansible and thus maintained by the core team, please file this in the [Ansible](https://github.com/ansible/ansible) project.
