### ISSUE TITLE
API timeouts

### ISSUE THREAD

**Issue by till** [ansible/galaxy#2170]
##### SUMMARY

Cannot install roles from Ansible Galaxy.

##### STEPS TO REPRODUCE

 1. Add roles to requirements.yml
 2. Run galaxy install

##### EXPECTED RESULTS

 1. Roles are successfully installed

##### ACTUAL RESULTS

```
- extracting cloudalchemy.alertmanager to /root/.ansible/roles/cloudalchemy.alertmanager
--
647 | - cloudalchemy.alertmanager (0.13.5) was installed successfully
648 | [WARNING]: - cloudalchemy.grafana was NOT installed successfully: Failed to
649 | get data from the API server (https://galaxy.ansible.com/api/): The read
650 | operation timed out
651 | ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

This is from our CI system, when I re-run my builds, the error moves on to a different role.

**Comment by till** [comment]
Btw, a proper status page would be neat. :)

**Comment by mashayev** [comment]
Same issue for me.
As @till said ->  A status page would be nice!

**Comment by Flarf** [comment]
Same here.  Discovered the issue around 10PM MST, and still seeing the issue.

**Comment by chouseknecht** [comment]
Galaxy is experiencing some intermittent problems. We’re looking into it. Will provide an update when we know more. Thanks to those that reported seeing issues.

**Comment by nqb** [comment]
Issue seems still present.

**Comment by mashayev** [comment]
@chouseknecht Any ETA ?

**Comment by mashayev** [comment]
As a workaround(I don't like it, but at least it works) you can add a for loop and limit it to 10 or something:
`for i in {0..10}; do ansible-galaxy install -p <blah> <blah> && break; done`

This is a temp fix till Galaxy will be fixed.

**Comment by till** [comment]
My workaround is to download roles from git/github directly:

```diff
 - name: robertdebock.bootstrap
+  src: https://github.com/robertdebock/ansible-role-bootstrap
   version: 3.0.4	  version: 3.0.4
```

**Comment by chouseknecht** [comment]
Influx database where we capture monitoring data grew passed available volume space. Working on cleaning it up. Should be fixed within the next hour or two.

**Comment by chouseknecht** [comment]
Fixed. Many thanks to @cutwater

**Comment by ssbarnea** [comment]
Any regression measures implemented so we do not see this happening again, for same or similar reasons? We should have a live status page and alerts, not to rely on users reporting it on irc first.

**Comment by till** [comment]
@ssbarnea I started something: #2172 — feel free to weigh in. Apparently this is being discussed after the holidays.
