### ISSUE TITLE
add OpenBSD 6.6, FreeBSD 11.3, 12.1 to platform list

### ISSUE THREAD

**Issue by nusenu** [ansible/galaxy#2174]
same as previously #73, #172, #280, #705, #2170, #1585

> Warnings: 3
    IMPORTER101:
    Invalid platform: "OpenBSD-6.6", skipping.
    Invalid platform: "FreeBSD-12.1", skipping.
    Invalid platform: "FreeBSD-11.3", skipping. 

ref
#80

**Comment by chouseknecht** [comment]
Added.
