### ISSUE TITLE
Galaxy Login Issues (Server Error (500))

### ISSUE THREAD

**Issue by islander** [ansible/galaxy#2176]
##### SUMMARY

I have the same issue as in https://github.com/ansible/galaxy/issues/2048, can't sign in to galaxy with github account.

My previous username was `kiba`.

##### STEPS TO REPRODUCE
Trying to login https://galaxy.ansible.com/accounts/login/

##### EXPECTED RESULTS
Sucessfull login.

##### ACTUAL RESULTS
When I try to sing up, I get:

> An account already exists with this e-mail address. Please sign in to that account first, then connect your GitHub account.

When I try to sign in with old username, I get:

> Server Error (500)

**Comment by chouseknecht** [comment]
@islander 

Deleted the `kiba` account. Let's see if that fixes the issue.

**Comment by islander** [comment]
Thanks, it's worked.
