### ISSUE TITLE
Galaxy download counter doesn't increment

### ISSUE THREAD

**Issue by kbreit** [ansible/galaxy#2177]
# Bug Report 
##### SUMMARY
I noticed the counter on my modules, cisco.meraki, isn't increasing. I installed it on my system and it is still showing 0.

##### STEPS TO REPRODUCE
Download and install via `ansible-galaxy`

##### EXPECTED RESULTS
I expected to see the download counter increase by 1.

##### ACTUAL RESULTS
The download counter still shows 0.

**Comment by chouseknecht** [comment]
We don't actually track download count at the module level. Not even sure we're tracking at the Collection level.

**Comment by kbreit** [comment]
The collections do list a download counter but it's still at 0, even though I know it was downloaded. I'd like to either see it removed if it's not incremented, or even better, increment and keep track.

**Comment by alikins** [comment]
Yup, currently, download_count isn't tracked for collections, only roles. 

Will add a collection download count analogous to the role download count.

**Comment by alikins** [comment]
I think the download view is just checking for the wrong user agent ('Mazer/', the old client) on downloads and not counting those by current 'ansible-galaxy' ('ansible-galaxy/ user agent).
