### ISSUE TITLE
My content is empty

### ISSUE THREAD

**Issue by yaegashi** [ansible/galaxy#2184]
##### SUMMARY
After logging in as @yaegashi "My Content" shows no namespace for me.  There remains my old resources in the past at https://galaxy.ansible.com/yaegashi.

##### STEPS TO REPRODUCE
Newly register and log in galaxy.ansible.com as GitHub user @yaegashi.

##### EXPECTED RESULTS
There should be one namespace for @yaegashi in "My Content."

##### ACTUAL RESULTS
There's no namespace available in "My Content."

**Comment by chouseknecht** [comment]
For some reason `yaegashi` was not set to the owner of the existing `yaegash` namespace. Should be fixed now.
