### ISSUE TITLE
Galaxy Login Issues (Server Error (500)) #2048

### ISSUE THREAD

**Issue by bboss-org** [ansible/galaxy#2185]
Hi,

Sorry for the inconvenient, I tried to create an user account without GitHub Connection.
Now it's blocking the registration with GitHub. Could you please remove it from the database.
The behavior is identical to #2048.
User: bboss

Thank's in advance,
Best Regard,
Laurent Marchelli

**Comment by chouseknecht** [comment]
Deleted the requested user: `bboss`

**Comment by bboss-org** [comment]
Thank you, it's working fine now.
