### ISSUE TITLE
namespace: nebulaworks

### ISSUE THREAD

**Issue by drewmullen** [ansible/galaxy#2187]
## Namespace Request
Namespace: nebulaworks

##### Description
namespace for my company [nebulaworks](www.nebulaworks.com)

##### GitHub Org Link
https://gitlab.com/nebulaworks
https://github.com/nebulaworks

##### Admins
https://github.com/drewmullen
https://github.com/sarcasticadmin

**Comment by chouseknecht** [comment]
Namespace `nebulaworks` created with owner `drewmullen`. You can add additional owners.
