### ISSUE TITLE
Requesting a Galaxy Namespace for Route 1337, LLC

### ISSUE THREAD

**Issue by ahrenstein** [ansible/galaxy#2188]
## Namespace Request
Namespace: route1337

##### Description
Providing open source tools and tutorials for the modern DevOps professional.

##### GitHub Org Link
https://github.com/route1337

##### Admins
https://galaxy.ansible.com/ahrenstein

**Comment by chouseknecht** [comment]
Namespace `route1337` created.

**Comment by ahrenstein** [comment]
Thanks for the speedy work!
