### ISSUE TITLE
Canceled and maybe stuck import?

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#2191]
From `drybjed` via IRC:

Got an issue during Galaxy import: https://galaxy.ansible.com/my-imports/361?type=collection; Error Message: duplicate key value violates unique constraint "pulp_app_repositoryversion_repository_id_number_07cb5788_uniq" DETAIL: Key (repository_id, number)=(1, 735) already exists.

Since I cannot add a collection with the same version again, can't remove an existing version... what can I do to fix this?

Also, an import of a different version was cancelled, no way to re-import it: https://galaxy.ansible.com/my-imports/361

Is there currently Galaxy server maintenance being done? is there a way to see that there's a maintenance in progress?

**Comment by chouseknecht** [comment]
There was an upgrade of the OpenShift cluster overnight. This might have been what caused the import to cancel. Will get @cutwater to take a look as soon as he can, as he's on PTO.

**Comment by cutwater** [comment]
@chouseknecht There is a race condition in pulp source code. Related issue: https://pulp.plan.io/issues/5982

**Comment by chouseknecht** [comment]
We delete the 1.1.7 and 1.2.1 versions of the debops.debops collection. Please try to re-import, and since there is a known race conditions, please import them one at a time. Let one finish and then import the next.

**Comment by drybjed** [comment]
Thanks for the help and investigation. I think that for the time being, a Big Fat Warning should be added into the import UI. Later perhaps, a queue?

**Comment by drybjed** [comment]
I did as suggested, but still got an error:

> Import Task "998" failed: duplicate key value violates unique constraint > "pulp_app_repositoryversion_repository_id_number_07cb5788_uniq" DETAIL: Key (repository_id, number)=(1, 766) already exists.  

https://galaxy.ansible.com/my-imports/361?type=collection

**Comment by cutwater** [comment]
@drybjed Can you please try import the same collection again?

**Comment by chouseknecht** [comment]
Fixed. @drybjed was able to re-import the affected versions.
