### ISSUE TITLE
Requesting devshop namespace.

### ISSUE THREAD

**Issue by jonpugh** [ansible/galaxy#2192]
## Namespace Request
Namespace: devshop

##### Description

I've had opendevshop on Galaxy for many years now. This is because "devshop" was taken on GitHub.

It would be awesome to drop the "open" part.

Not only would it be shorter, we would be able to match our galaxy role names with our docker containers!  

We also have the devshop packagist namespace.

##### GitHub Org Link

https://github.com/opendevshop

##### Admins

Just me for now: jonpugh

**Comment by chouseknecht** [comment]
Namespace `devshop` created.
