### ISSUE TITLE
Problem with login galaxy.ansible.com

### ISSUE THREAD

**Issue by maciej-wawrzynczuk** [ansible/galaxy#2195]
## Bug Report 

I'm unable to login with email/password on https://galaxy.ansible.com/accounts/login/
I get Server Error (500).
I use email maciej.wawrzynczuk@gmail.com
I'm sure password is correct - otherwise I got different message.

**Comment by chouseknecht** [comment]
Found your account and deleted on the Galaxy side. Try logging in again from scratch. Also, you should not be prompted for a password by the Galaxy server. Authentication is strictly via GitHub OAuth.

**Comment by maciej-wawrzynczuk** [comment]
Works fine. Thanks!
