### ISSUE TITLE
Add a download button for Collections

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#2198]
To help users on air-gapped networks, add a download button to the Collection detail page.

**Comment by chouseknecht** [comment]
Target release date: 31 January

**Comment by abenokraitis** [comment]
FYI: The other "half" of this feature: https://github.com/ansible/ansible/issues/66534

**Comment by ironfroggy** [comment]
Will this download mechanism also increment the download counter, per https://github.com/ansible/galaxy/issues/2177 ?

**Comment by chouseknecht** [comment]
The download link was added by PR #2210
