### ISSUE TITLE
This provider namespace is already associated with a Galaxy namespace (wavefrontHQ)

### ISSUE THREAD

**Issue by vandanasubbu** [ansible/galaxy#2200]
# SUMMARY
I would like to upload content into the namespace wavefrontHQ from user vandanasubbu

##### STEPS TO REPRODUCE
1. Login to Galaxy as vandanasubbu
2. In the my-content -> Edit namespace, under the provider namespace section -> select wavefrontHQ and click save.
3. Error -> This provider namespace is already associated with a Galaxy namespace (wavefrontHQ)

##### EXPECTED RESULTS
able to upload content as user vandanasubbu into the provider namespace

**Comment by 532910** [comment]
Could you say how you solved this?
