### ISSUE TITLE
upload to galaxy fails with invalid namespace

### ISSUE THREAD

**Issue by vandanasubbu** [ansible/galaxy#2201]
##### SUMMARY
Trying to uoload https://github.com/wavefrontHQ/ansible-collection-wavefront/blob/master/wavefrontHQ-ansible_collection_wavefront-1.2.0.tar.gz into the namespace wavefrontHQ. fails with invalid namespace. I am the owner of the namespace
##### STEPS TO REPRODUCE
1. in the Add content under the wavefrontHQ namespace, click upload collection.
2. upload the below collection build https://github.com/wavefrontHQ/ansible-collection-wavefront/blob/master/wavefrontHQ-ansible_collection_wavefront-1.2.0.tar.gz
ERROR: invliad namespace ``wavefronthq

##### EXPECTED RESULTS
collection uploaded successfully
##### ACTUAL RESULTS

```

```

**Comment by chouseknecht** [comment]
The namespace name and collection name must be all lowercase. To fix the issue we'll need to change your namespace to `wavefronthq`.

**Comment by vandanasubbu** [comment]
Is this a collection limitation to have the namespace name in all lower case. We were able to upload roles to galaxy with the existing namespace `wavefrontHQ` successfully. We would like to retain the same name. Is that possible ?

**Comment by vandanasubbu** [comment]
@chouseknecht ^^^^
please help

**Comment by chouseknecht** [comment]
Yes, it's a limitation of collections. Names have to Python compatible.

**Comment by vandanasubbu** [comment]
Thanks @chouseknecht.

If that's the case, can you please help me create namespace with the below details.

Namespace name : wavefront

Description
Wavefront's ansible collection and roles

GitHub Org Link
https://github.com/wavefrontHQ/ansible-collection-wavefront

Admins
vandanasubbu
mzeier

**Comment by vandanasubbu** [comment]
@chouseknecht : gentle reminder.

**Comment by chouseknecht** [comment]
Done. Namespace `wavefront` created.
