### ISSUE TITLE
Failed collection import: "Role metadata not found"

### ISSUE THREAD

**Issue by drybjed** [ansible/galaxy#2202]
##### SUMMARY

During testing the changes in my Ansible Collection I encountered an issue on the https://galaxy-dev.ansible.com/ and https://galaxy-qa.ansible.com/ test servers. The failed imports can be found [on the import page](https://galaxy-dev.ansible.com/my-imports/361?type=collection&name=debops).

The server reports an error "Role metadata not found" for the `unattended_upgrades` role included in the collection. However upon inspection of the tarball, the `roles/unattended_upgrades/meta/main.yml` file can be found. To check the import process, I created a different collection tarball with the `unattended_upgrades` role removed - in this case, the error happened with a previously fine `php` role instead, which is imported before the `unattended_upgrades` role. @chouseknecht suspect that this might be a bug with the importer.

**Comment by alikins** [comment]
@drybjed which commit of https://github.com/debops/debops/commits/master is equilivent to the 1.2.3 release that fails?

**Comment by drybjed** [comment]
@alikins I just made [another import](https://galaxy-dev.ansible.com/my-imports/361?type=collection) on `galaxy-dev.ansible.com` using the current `master` branch (https://github.com/debops/debops/commit/6d1a2f8dff52db2abe0fc84b04b859745a5bc29d), fails again the same way. If you want I can give you the built tarball, catch me on `#ansible-galaxy` IRC channel.

**Comment by alikins** [comment]
@drybjed I grabbed 6d1a2f8dff52db2abe0fc84b04b859745a5bc29d (which seems to be 1.2.0?), updated the namespace template to use my namespace, and ran 'make collection' and tried importing it from the ui in a local dev instance of galaxy and the import seemed to go okay.  (import log at https://gist.github.com/alikins/6f5b60f10c4c01d051e9af3aaa755e8f).

Any ideas what would be different with 1.2.3? (I don't see a 1.2.3 tag).

**Comment by drybjed** [comment]
The `1.2.3` tag is not present, I used it because Ansible Galaxy doesn't allow me to re-import an existing tag that succeeded. This is only meant for testing.

If you used that commit then there's no difference between your tarball and mine. I have no idea what could be the issue on `galaxy-dev.ansible.com` - perhaps due to DebOps size some limit was reached and the importing process was killed? I was hoping that you had access to the `galaxy-dev.ansible.com` instance to see something in the logs. What are the import limits set on that instance?

**Comment by chouseknecht** [comment]
We've poked at this on `galaxy-dev` and found nothing obvious. Maybe it's a limitation of the environment. My first suggestion would be to run the import at `galaxy.ansible.com` and see if it works as expected. It seems like the last few imports there have worked fine. 

My second suggestion would be to break the collection into several smaller collections. Including 400 roles in a single collection may be pushing the bounds of what we're able to support for now.

**Comment by drybjed** [comment]
@chouseknecht Thanks for looking into it. I plan to make a new DebOps release today, so we will be able to see how it works.

The problem with releasing directly on https://galaxy.ansible.com/ for me is that each release is effectively immutable - I cannot either replace a given tag with an updated version or remove it, I need to make a completely new version I want to update the Collection. With a [3-month release schedule](https://docs.debops.org/en/master/news/releases.html#current-release-schedule) it becomes very hard to test the Collections there - that's why I welcomed the `galaxy-dev` and `galaxy-qa` servers for just this purpose. However if they are not equivalent to the production servers (just the one would suffice, just pick one, perhaps `galaxy-qa`) testing Collection-related changes again becomes problematic.

As for breaking the collection - I thought about it, but I don't see a good set of namespaces to use for different roles. Perhaps that will happen in the future, will see.

So, is `debops.debops` collection effectively the larges on Galaxy, at least with the number of roles? Do you know the average number of roles and other "stuff" in a Collection? Any chance to get a blog post with some interesting statistics about Ansible Collections? It was some time since official release, it would be interesting to see if that solution has taken off within the community.

**Comment by drybjed** [comment]
@chouseknecht I released DebOps v2.0.0 and tried to [import the collection to Galaxy](https://galaxy.ansible.com/my-imports/361?type=collection), but the import failed the same way as on the `galaxy-qa` and `galaxy-dev` servers. Any suggestions?

**Comment by drybjed** [comment]
@chouseknecht, @bmclaughlin, any news about this issue? Is there a chance that you could increase the limits that are encountered during the import process?

**Comment by cutwater** [comment]
@djzager @chouseknecht It's not clear from logs which role fails exactly, but after import log and error log analysis I suspect that the importer fails when trying to import `roles/debops.ansible_plugins` directory. This is the only directory in `roles/` that doesn't have `meta/main.yml` file.

**Comment by drybjed** [comment]
@cutwater The role [has the `meta/main.yml` file](https://github.com/debops/debops/blob/master/ansible/roles/ansible_plugins/meta/main.yml). In the collection generation script the role directories are copied as a whole, so that file should be included in the tarball. I just checked the collection tarball I generated a few hours ago and that file is definitely inside. Can you check again?

**Comment by cutwater** [comment]
@drybjed Can you please send me this tarball for further analysis?

**Comment by drybjed** [comment]
Sure, I'll include it in the comment.

[debops-debops-2.0.0.tar.gz](https://github.com/ansible/galaxy/files/4172269/debops-debops-2.0.0.tar.gz)

**Comment by cutwater** [comment]
Import fails on the directory `debops.ansible_plugins`. It doesn't looks like a typical role directory. 
Also I don't see it in https://github.com/debops/debops repository. I assume that it may be created during collection build process.

<img width="644" alt="Screenshot_20200207_190812" src="https://user-images.githubusercontent.com/62445/74053909-3096a300-49dd-11ea-864d-20e4bc8eddb8.png">

Can you please check this.

**Comment by drybjed** [comment]
@cutwater Ah, you're right. This must have been a leftover after renaming all of the roles and switching `git` branches a few times. My bad. I'll add some safeguards to the collection generation script to ensure that it doesn't happen again in the future.

So I suppose without that directory there would be no issue with importing DebOps collection at all. Still, at the moment the tarball has 1,5 MB and will most likely increase before the next release in April. With the current limit of 2 MB per collection I would have to split it anyway. Or do you plan to increase that limit in the future to allow for larger collections?

**Comment by chouseknecht** [comment]
Looks like we can close this.
