### ISSUE TITLE
Namespace request for wazuh  

### ISSUE THREAD

**Issue by rshad** [ansible/galaxy#2203]
## Namespace Request
Namespace: wazuh

##### Description
Wazuh Ansible roles

##### GitHub Org Link

https://github.com/wazuh

##### Admins

- Username: rshad 
   Github Account: https://github.com/rshad

- Username: jm404
   Github Account: https://github.com/jm404
 
- Username: xr09
   Github Account: https://github.com/xr09

- Username: manuasir
   Github Account: https://github.com/manuasir

**Comment by rshad** [comment]
Hi @gundalow !

Is it possible to be informed about the estimated time to get the namespace created?

Kr,

Rshad

**Comment by gundalow** [comment]
@rshad Hi, it's live now.

**Comment by rshad** [comment]
Thank you @gundalow !

Kr,

Rshad
