### ISSUE TITLE
Request to create "infoblox" namespace

### ISSUE THREAD

**Issue by saileshgiri** [ansible/galaxy#2205]
## Namespace Request
Namespace: infoblox

##### Description
Infoblox namespace for Ansible roles and collections  

##### GitHub Org Link
https://github.com/infobloxopen 

##### Admins
Shankarganesh PJ: email - sganesh@infoblox.com, github- sganesh-infoblox
Vaishnavi T R email - vtr@infoblox.com, github - Vaishnavi-infoblox

**Comment by saileshgiri** [comment]
CC @sganesh-infoblox, @Vaishnavi-infoblox

**Comment by thedoubl3j** [comment]
@saileshgiri do you have the galaxy usernames by chance?

**Comment by saileshgiri** [comment]
Hello @thedoubl3j , the usernames are: “sganesh-infoblox” and “vaishnavi-infoblox”

**Comment by thedoubl3j** [comment]
done :)
