### ISSUE TITLE
Ubuntu has eoan, disco dingo and NOT focal or focal fossa

### ISSUE THREAD

**Issue by mf69** [ansible/galaxy#2207]
please address an inconsistency in the Ubuntu platform
Per https://galaxy.ansible.com/api/v1/platforms/

```
{
            "id": 207,
            "url": "/api/v1/platforms/207/",
            "related": {},
            "summary_fields": {},
            "created": "2019-07-02T14:31:12.330919Z",
            "modified": "2019-07-02T14:31:12.330941Z",
            "name": "Ubuntu",
            "release": "disco dingo",
            "active": true
        },
        {
            "id": 218,
            "url": "/api/v1/platforms/218/",
            "related": {},
            "summary_fields": {},
            "created": "2019-11-06T17:02:58.747761Z",
            "modified": "2019-11-06T17:03:12.046063Z",
            "name": "Ubuntu",
            "release": "eoan",
            "active": true
        },
```

Notice that 1) disco dingo should just be disco to be consistent with all other Ubuntu entries which just use the first word. 2) focal (focal fossa) 20.04 is not yet present, please add a new entry as it is due to be released soon (April).

Thank you!

**Comment by mf69** [comment]
It looks like disco just went EOL today.

**Comment by chouseknecht** [comment]
Done. Thanks for pointing this out and helping us keep the platform list up to date.

**Comment by mf69** [comment]
No problem, I was able to use focal in my platform list.
TY
