### ISSUE TITLE
Namespace request for Open Zaak

### ISSUE THREAD

**Issue by sergei-maertens** [ansible/galaxy#2209]
## Namespace Request
Namespace: openzaak

##### Description
Provide tooling to deploy Open Zaak and related projects

##### GitHub Org Link
https://github.com/open-zaak

##### Admins
- joeribekker
- sergei_maertens

**Comment by gundalow** [comment]
@sergei-maertens Thanks, all created.

**Comment by sergei-maertens** [comment]
Thank you!
