### ISSUE TITLE
namespace: FreeIPA

### ISSUE THREAD

**Issue by Akasurde** [ansible/galaxy#2213]
## Namespace Request
Namespace: freeipa

##### Description

Please reserve namespace for FreeIPA / IDM project.

##### GitHub Org Link

[@freeipa](https://github.com/freeipa/)

##### Admins

@Akasurde 
@t-woerner

**Comment by gundalow** [comment]
@Akasurde Created, enjoy

**Comment by gundalow** [comment]
@Akasurde Actually `ipa` already exists 
Existing admins are @t-woerner and @abbra 

@t-woerner and @abbra are you happy for me to add @Akasurde?

**Comment by abbra** [comment]
@gundalow yes. I think you can also add me to the other 'freeipa' namespace too.

**Comment by chouseknecht** [comment]
@Akasurde added.
