### ISSUE TITLE
namespace 'extreme' admins

### ISSUE THREAD

**Issue by ujwalkomarla** [ansible/galaxy#2214]
## Bug Report 
Issue adding admins to 'extreme' namespace.

##### SUMMARY

Previously, when requesting the 'extreme' namespace: https://github.com/ansible/galaxy/issues/2029, I hadn't created a galaxy account and wasn't added as an admin.

Later, Matthew, the other admin, has been having issues adding me as an admin.
Can you please help me by adding me as admin?

**Comment by ujwalkomarla** [comment]
@gundalow Can you help me on this?

**Comment by chouseknecht** [comment]
Done. `ujwalkomarla` is now an owner of namespace `extreme`.
