### ISSUE TITLE
Namespace request for 'ufz'

### ISSUE THREAD

**Issue by Normo** [ansible/galaxy#2215]
## Namespace Request
Namespace: ufz

##### Description
Helmholtz Centre for Environmental Research - UFZ

##### GitHub Org Link
https://github.com/Helmholtz-UFZ

##### Admins
@sloan87
@robimac04 
@Normo 

Thank you very much.

**Comment by gundalow** [comment]
@sloan87 @robimac04 @Normo `ufz` namespace has been created. Enjoy!

**Comment by Normo** [comment]
Thank you @gundalow !
