### ISSUE TITLE
"ansible-galaxy collection build" should not package files in ".gitignore"

### ISSUE THREAD

**Issue by JGoutin** [ansible/galaxy#2219]
### Use Case

Many people use Git as version control when writing Ansible roles and collection. And many Git repositories already include a `.gitignore` file.

The command `ansible-galaxy collection build` should look for `.gitignore` files and apply them when selecting files to package.

I see that the [doc](https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders) show we can use `build_ignore` in `galaxy.yml` to filter files to package.

But repeating the same thing twice is a loss of time and error prone (Easy to forget it).

Having a more automatic way to filter files that are included in the packages will make packages lighter and will improve the collections download speed and reduce the required storage size on the Galaxy server.

### Proposed Solution

Parse `.gitignore` and apply them when packaging the collection.

**Comment by chouseknecht** [comment]
Thank you for filing this issue. We appreciate the feedback. However, this should be filed at [ansible/ansible](https://github.com/ansible/ansible/issues).
