### ISSUE TITLE
namespace: dominion_solutions

### ISSUE THREAD

**Issue by spam-n-eggs** [ansible/galaxy#2221]
## Namespace Request
Namespace: dominion_solutions

##### Description
Dominion Solutions LLC is a software consulting firm specializing in custom, full-stack solutions utilizing PHP and Java on multiple cloud platforms.

##### GitHub Org Link
@dominion-solutions
##### Admins
@spam-n-eggs

**Comment by spam-n-eggs** [comment]
@gundalow Is there something missing from this namespace request that is holding up the process?

**Comment by chouseknecht** [comment]
Done.
