### ISSUE TITLE
namespace: tapp

### ISSUE THREAD

**Issue by swilla** [ansible/galaxy#2222]
## Namespace Request
Namespace: tapp

##### Description
Tapp Networks LLC is a full-stack development firm that specialized in custom software and integrations in the cloud and on premise. 

##### GitHub Org Link
https://github.com/TappNetwork

##### Admins
swilla
spam_and_eggs

**Comment by spam-n-eggs** [comment]
@gundalow When you create this org, it should be spam_n_eggs, not spam-and-eggs.

**Comment by chouseknecht** [comment]
Done
