### ISSUE TITLE
namespace: ibmcloud

### ISSUE THREAD

**Issue by svennam92** [ansible/galaxy#2233]
## Namespace Request
Namespace: ibmcloud

##### Description
Collections managed by IBM Cloud.

##### GitHub Org Link
org: https://github.com/IBM-Cloud
project: ansible-collection-ibm

##### Admins
github.com/svennam92 || galaxy.ansible.com/svennam92
github.com/Anil-CM || galaxy.ansible.com/anil_cm

**Comment by chouseknecht** [comment]
Done.
