### ISSUE TITLE
Create a new namespace called devopstoolbox

### ISSUE THREAD

**Issue by crivetimihai** [ansible/galaxy#2234]
## Namespace Request
Namespace: devopstoolbox

##### Description
DevOps Toolbox - Collection of Ansible Roles and Playbooks for Linux Build and Migration scenarios, with detailed documentation.

##### GitHub Org Link
https://github.com/devopstoolbox

##### Admins
crivetimihai

**Comment by chouseknecht** [comment]
Done.
