### ISSUE TITLE
My content is empty, unable to add a new role

### ISSUE THREAD

**Issue by opdavies** [ansible/galaxy#2235]
##### SUMMARY
After logging into Galaxy, `My Content` is empty and `My Imports is blank.

##### EXPECTED RESULTS
I would expect to see my existing roles (https://galaxy.ansible.com/opdavies), and be able to upload new roles.

##### ACTUAL RESULTS

`My content` says 'No Items Available'.

`My imports` is showing a blank page, and has an error in the Console:

```
> ERROR TypeError: Cannot read property 'id' of undefined
    at t.loadImportList (5.9d256f63217f6c4cdf0f.js:1)
```

**Comment by chouseknecht** [comment]
Fixed.

**Comment by opdavies** [comment]
Thanks @chouseknecht!
