### ISSUE TITLE
Please add ddimatos and others to the ibm namespace

### ISSUE THREAD

**Issue by ddimatos** [ansible/galaxy#2236]
## Namespace Request
ibm

## GitHub Org Link
https://github.com/ansible-collections/ibm_zos_core

## Admins
ddimatos
itsBryantP
khite1983

**Comment by thedoubl3j** [comment]
@ddimatos users {khite1983, ddimatos} were added as admins, I didn't see the username itsBryantP in galaxy.

**Comment by ddimatos** [comment]
Thanks Jake. I am having a bit of an issue; having uploaded collections to my personal namespace with no issue, I am having some trouble with the `ibm` namespace unless there is a incubation period for access to fully propagate.  

I have signed out and dropped my cookies as well thinking something in cache, also try from the command line with the api-key='...' and still have a failure. 

According to doc, i should be able to upload given i have admin access to namespace `ibm`:

"When uploading collections it doesn’t matter which namespace you select. The collection will be uploaded to the namespace specified in the collection metadata in the galaxy.yml file. If you’re not an owner of the namespace, the upload request will fail." 

Steps:
<img width="597" alt="image" src="https://user-images.githubusercontent.com/25803172/74297967-479b0500-4cfd-11ea-8b66-4b343a99eb21.png">

Error:
<img width="597" alt="image" src="https://user-images.githubusercontent.com/25803172/74297992-5a153e80-4cfd-11ea-8879-18756f98d65c.png">

galaxy.yml:
<img width="319" alt="image" src="https://user-images.githubusercontent.com/25803172/74298079-90eb5480-4cfd-11ea-829e-a768789c6927.png">

URI to galaxy.yml
https://github.com/ansible-collections/ibm_zos_core/blob/dev/galaxy.yml

**Comment by chouseknecht** [comment]
Requested users are already listed as owners of the `ibm` namespace. I also see that `v0.0.4 ` of the `ibm_zos_core` collection was uploaded 2 days ago.

Can we close this?

**Comment by gundalow** [comment]
> Requested users are already listed as owners of the `ibm` namespace. I also see that `v0.0.4 ` of the `ibm_zos_core` collection was uploaded 2 days ago.


@ddimatos Is this working OK for your now, can we close this request, given the comment in

**Comment by chouseknecht** [comment]
There's been no update. Assuming all is working and closing.

**Comment by ddimatos** [comment]
Thanks Chris, i apologize for the delay in responding, I will reopen as I still have issues but in the middle of a release currently, I have a work around using another ID to upload to Galaxy for now.

**Comment by ddimatos** [comment]
See this PR where i will continue the request: https://github.com/ansible/galaxy/issues/2465
