### ISSUE TITLE
MichaelRigart.interfaces releases missing and role page not found

### ISSUE THREAD

**Issue by markgoddard** [ansible/galaxy#2237]
##### SUMMARY

Recent releases not available for https://galaxy.ansible.com/michaelrigart/interfaces. Also, the role home page gets 'Page not found'.

##### STEPS TO REPRODUCE

ansible-galaxy role install MichaelRigart.interfaces,v1.4.0

##### EXPECTED RESULTS

Role is installed.

##### ACTUAL RESULTS

```
- downloading role 'interfaces', owned by MichaelRigart
[WARNING]: - MichaelRigart.interfaces was NOT installed successfully: - the specified version (v1.4.0) of MichaelRigart.interfaces was not found in the list of available versions ([{'id': 53602, 'url':
'', 'related': {}, 'summary_fields': {}, 'created': '2018-02-20T14:30:48.119034Z', 'modified': '2018-06-19T08:29:08.095092Z', 'name': 'v1.0.0', 'version': '1.0.0', 'commit_date':
'2017-12-20T15:17:49-05:00', 'commit_sha': None, 'download_url': 'https://github.com/michaelrigart/ansible-role-interfaces/archive/v1.0.0.tar.gz', 'active': None}, {'id': 72116, 'url': '', 'related': {},
'summary_fields': {}, 'created': '2018-08-06T08:07:41.385338Z', 'modified': '2018-08-06T08:07:41.385367Z', 'name': 'v1.1.0', 'version': '1.1.0', 'commit_date': '2018-06-19T04:27:02-04:00', 'commit_sha':
'fd7fc2589b6b7636c55540e1eae0609efc682ae7', 'download_url': 'https://github.com/michaelrigart/ansible-role-interfaces/archive/v1.1.0.tar.gz', 'active': None}, {'id': 86879, 'url': '', 'related': {},
'summary_fields': {}, 'created': '2019-01-29T11:44:54.965949Z', 'modified': '2019-01-29T11:44:54.965972Z', 'name': 'v1.2.0', 'version': '1.2.0', 'commit_date': '2019-01-29T04:22:11-05:00', 'commit_sha':
'cd3bbd715c29276f642e0841e09eeb67d3a07e5a', 'download_url': 'https://github.com/michaelrigart/ansible-role-interfaces/archive/v1.2.0.tar.gz', 'active': None}]).
```

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

**Comment by chouseknecht** [comment]
There were somehow two namespaces `MichaelRigart` and `michaelrigart`. I deleted the lowercase one, as you seemed to be working with the mixed case. That was apparently the wrong one to delete, because now all the content is gone. You'll need to re-import all of your roles.

If you intend to use collections, you'll want to use `michaelrigart` in lowercase, as namespaces need to be Python compatible for Collections to work. Let use know, if you want to switch to lowercase.

**Comment by markgoddard** [comment]
@chouseknecht I have tried to reimport all of Michael's roles, but it has applied the new naming rules and there is no way to rename through the UI. For example, `interfaces` is now `ansible_role_interfaces`.

**Comment by markgoddard** [comment]
@chouseknecht please respond - this will have broken consumers of these roles. Sadly also it will have reset statistics which in some cases were pretty high.

**Comment by markgoddard** [comment]
@michaelrigart

**Comment by ramondelafuente** [comment]
I did not want to create a new issue, since this might be related.

I have the same issue for all roles in the /f500/ namespace. We have used these for years without problem, but now suddenly all roles show a `page not found`.

<img width="1440" alt="Screenshot 2020-02-12 at 21 23 41" src="https://user-images.githubusercontent.com/668391/74374136-23fbbb80-4dde-11ea-92a9-a050fcaf7539.png">
<img width="1440" alt="Screenshot 2020-02-12 at 21 23 51" src="https://user-images.githubusercontent.com/668391/74374139-24945200-4dde-11ea-83b8-00df0562dfa4.png">
<img width="322" alt="Screenshot 2020-02-12 at 21 24 00" src="https://user-images.githubusercontent.com/668391/74374143-252ce880-4dde-11ea-98b8-6c6d813a3743.png">

**Comment by markgoddard** [comment]
I have updated the name of the interfaces role that I have access to using the `role_name` field in `meta/main.yml`.

@chouseknecht the other roles are still broken. Please respond.

**Comment by ramondelafuente** [comment]
Am I understanding correctly that we can fix this issue by adding a "role name" field to `meta/main.yml`? What do we add there; only the nameof the role or also the prefix?

**Comment by markgoddard** [comment]
yes - `role_name`. Some caveats - if your roles were created a long time ago, they were allowed to have dashes in the name. This is no longer allowed (don't get me started on that...), and they will be converted to underscores.

**Comment by chouseknecht** [comment]
@markgoddard 

If you re-import the roles, we change the name to whatever you want. Just send a list what needs to be changed. We can even set things to dashes, if it helps legacy users.

The naming standard was changed to prevent future content from introducing names and namespaces that are not Python compatible.

**Comment by chouseknecht** [comment]
@ramondelafuente I'll take a look.

**Comment by markgoddard** [comment]
> @markgoddard
> 
> If you re-import the roles, we can manually change the name to whatever you want. Just send a list what needs to be changed. We can even set things to dashes, if it helps legacy users.
> 
> The naming standard was changed to prevent future content from introducing names and namespaces that are not Python compatible.

I have reimported all of @michaelrigart's roles already. I don't know for sure what they were called previously, but it appears that they all follow the popular `ansible-role-<role name>` convention.

**Comment by chouseknecht** [comment]
@ramondelafuente  https://galaxy.ansible.com/f500 now displays lots of roles.

**Comment by chouseknecht** [comment]
@markgoddard Do you want us to drop the 'ansible-role'?

**Comment by chouseknecht** [comment]
@markgoddard 

Renamed them all to `ansible-role-<role name>`. Let us know, if further modification is needed.

**Comment by ramondelafuente** [comment]
@chouseknecht Thanks, that solves it for us I guess. No reason for this problem to return?
Do we stil need to add the names to the roles?

**Comment by markgoddard** [comment]
> @markgoddard
> 
> Renamed them all to `ansible-role-<role name>`. Let us know, if further modification is needed.

@chouseknecht they all still have an `ansible-role-` prefix, except for the one I changed already.

**Comment by chouseknecht** [comment]
@markgoddard 

Done. Removed `ansible-role-` from all the role names.

**Comment by chouseknecht** [comment]
I believe everything has been addressed. Closing. If you run into additional problems, please open a new issue with details.

**Comment by markgoddard** [comment]
Thanks @chouseknecht
