### ISSUE TITLE
namespace: network_automation

### ISSUE THREAD

**Issue by IPvSean** [ansible/galaxy#2241]
## Namespace Request
Namespace: network_automation

##### Description
A community for network automation. This includes various Github repositories with examples, samples, demonstrations and more for agnostic network automation of various network vendors including Cisco, Juniper, Arista and more

##### GitHub Org Link
https://github.com/network-automation

##### Admins
https://github.com/IPvSean
https://github.com/termlen0
https://github.com/jmcleroy
https://github.com/michaelford85
https://github.com/colin-mccarthy

**Comment by IPvSean** [comment]
my galaxy username is seanx820 for some reason, how do I change this :)

**Comment by anshulbehl** [comment]
Created with all the mentioned users as admin
https://galaxy.ansible.com/network_automation
