### ISSUE TITLE
Namespace request for gillbus

### ISSUE THREAD

**Issue by levonet** [ansible/galaxy#2243]
## Namespace Request
Namespace: gillbus

##### Description
Ansible collections by [Busfor](https://busfor.com/en/about) company.

##### GitHub Org Link
private repository https://github.com/gillbus

##### Admins
- @bot-bi
- @levonet
- @lexusag
- @egoryachun
- @RomanPasichenko
- @Kostiuchenko-dg

Thank you.

**Comment by chouseknecht** [comment]
Namespace `gillbus` created with owner `levonet`. User `levonet` can go to My Content, Edit the namespace, and add any additional owners.
