### ISSUE TITLE
Render tables in Ansible galaxy

### ISSUE THREAD

**Issue by IPvSean** [ansible/galaxy#2245]
### Use Case
Right now I have multiple Ansible Collections that use their README.md with tables (either markdown or html tables that are fully supported by markdown standards and Github.com)

Here is what Github.com renders->
![image](https://user-images.githubusercontent.com/6537680/74462930-04f13e00-4e5f-11ea-9b79-abe951a2b934.png)

Right now this gets rendered like this in galaxy.ansible.com->
![image](https://user-images.githubusercontent.com/6537680/74462816-d4a99f80-4e5e-11ea-90a1-6c316fa88c65.png)

### Proposed Solution
Just render tables please

### Alternatives
I have no idea

### Implementation
see above

**Comment by chouseknecht** [comment]
This might be an easy-ish fix. When using *bleach*, we use [this as the conservative markdown whitelist](https://github.com/yourcelf/bleach-whitelist/blob/master/bleach_whitelist/bleach_whitelist.py#L52-L62) ... But we did add 'pre' to support blocks, and can add table ones as well (e.g., 'table', 'thead', 'th', 'tr', 'td').
