### ISSUE TITLE
Namespace request for alliedtelesis

### ISSUE THREAD

**Issue by dalyIsaac** [ansible/galaxy#2249]
## Namespace Request
Namespace: alliedtelesis

##### Description
Allied Telesis is a network infrastructure/telecommunications company.

##### GitHub Org Link
https://github.com/alliedtelesis

##### Admins

- dalyIsaac (@dalyIsaac)
- tony-vanderpeet (@tony-vanderpeet)
- hanktastic (@hanktastic)

**Comment by chouseknecht** [comment]
Done. There is no user `hanktastic` in Galaxy. Once that person logs into Galaxy the other owners can go to My Content, edit the namespace, and add the missing user.
