### ISSUE TITLE
Collection Delete Request: alvistack.kubernetes_collection

### ISSUE THREAD

**Issue by hswong3i** [ansible/galaxy#2252]
Could someone give me a hand to delete https://galaxy.ansible.com/alvistack/kubernetes_collection? 

Since I have split my original role from `alvistack.kubernetes` into:
  - https://galaxy.ansible.com/alvistack/kube_master
  - https://galaxy.ansible.com/alvistack/kube_node

Therefore reuse the name `alvistack.kubernetes` for my collection; BTW, there is no UI or CLI for me to remove the legacy uploaded collection.

Looking for a kindly help ;-)

**Comment by chouseknecht** [comment]
Collections can be deprecated, not deleted. Your `kubernetes_collection` is already marked as deprecated.
