### ISSUE TITLE
Create the namespace rolehippie

### ISSUE THREAD

**Issue by tboerger** [ansible/galaxy#2256]
## Namespace Request
Namespace: rolehippie

##### Description
Ansible role collection of Webhippie managing Linux systems

##### GitHub Org Link
https://github.com/rolehippie

##### Admins
tboerger
xoxys

**Comment by chouseknecht** [comment]
Done

**Comment by tboerger** [comment]
I'm not able to import any GitHub repo for that org.

<img width="1680" alt="Screenshot 2020-03-07 at 6 15 32 PM" src="https://user-images.githubusercontent.com/156964/76147775-0e597900-60a0-11ea-913d-8f8dc7e76ed6.png">
