### ISSUE TITLE
Create the namespace machippie

### ISSUE THREAD

**Issue by tboerger** [ansible/galaxy#2257]
## Namespace Request
Namespace: machippie

##### Description
Ansible role collection of Webhippie managing macOS systems

##### GitHub Org Link
https://github.com/machippie

##### Admins
tboerger
xoxys

**Comment by chouseknecht** [comment]
Done

**Comment by tboerger** [comment]
I'm not able to import any GitHub repo for that org.

<img width="1680" alt="Screenshot 2020-03-07 at 6 15 49 PM" src="https://user-images.githubusercontent.com/156964/76147791-216c4900-60a0-11ea-991f-5b09e1827263.png">
