### ISSUE TITLE
namespace: jpmens

### ISSUE THREAD

**Issue by jpmens** [ansible/galaxy#2259]
## Namespace Request
Namespace:  jpmens

##### Description

JP’s collection

##### GitHub Org Link
https://github.com/jpmens

##### Admins

jpmens

**Comment by jpmens** [comment]
As per https://github.com/ansible-collections/overview/issues/14#issuecomment-589275771

**Comment by chouseknecht** [comment]
The namespace `jpmens` already exists with owner `jpmens`. Can we close this, or is something not working as expected?

**Comment by jpmens** [comment]
Can you say why it already exists? Is it because I logged into Galaxy once before?

**Comment by chouseknecht** [comment]
Correct. When you log in the first time, Galaxy creates a namespace for you.
