### ISSUE TITLE
Allow collection to use lowe or uppercase 

### ISSUE THREAD

**Issue by mnecas** [ansible/galaxy#2260]
##### SUMMARY

When installing the collection we need to use all lowercase letters of our namespace.

##### STEPS TO REPRODUCE

This is just an example 
```Bash
# Installing role
ansible-galaxy install oVirt.image-template
ansible-galaxy install ovirt.image-template
# Works without a problem and install it to both to separate folders.

# Installing collection
ansible-galaxy collection install oVirt.ovirt_collection
ansible-galaxy collection install ovirt.ovirt_collection
# collection was not found 
```

##### EXPECTED RESULTS

Be able to install collection as a role.
##### ACTUAL RESULTS

Failed to find collection

```

```

**Comment by mnecas** [comment]
@chouseknecht @cutwater please take a look at this issue. 
A similar issue is when uploading the collection. 


cc @mwperina

**Comment by mnecas** [comment]
@jborean93

**Comment by chouseknecht** [comment]
According to the [Collection Galaxy Metadata Structure](https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html#collections-galaxy-meta).

>[Namespace names and Collection names] May only contain alphanumeric lowercase characters and underscores. Namespaces cannot start with underscores or numbers and cannot contain consecutive underscores.

Galaxy is enforcing this standard. We can change your Namespace name to be all lowercase, if you like.

**Comment by mnecas** [comment]
That would be great thank you.

**Comment by chouseknecht** [comment]
Done. `oVirt` is now `ovirt`.
