### ISSUE TITLE
Platforms available on Galaxy doesn't include current openSUSE releases

### ISSUE THREAD

**Issue by chkpnt** [ansible/galaxy#2262]
##### SUMMARY
Ansible Galaxy supports only outdated versions of openSUSE. According to the [API](https://galaxy.ansible.com/api/v1/platforms/?search=opensuse), the only supported versions are 12.1, 12.2, 12.3, 13.1 and 13.2.
The following versions are [missing](https://en.wikipedia.org/wiki/OpenSUSE_version_history#Version_history): Leap 42.1, Leap 42.2, Leap 42.3, Leap 15.0, Leap 15.1, Leap 15.2 and Tumbleweed.
I would also prefere the spelling "openSUSE" instead of "opensuse".

##### STEPS TO REPRODUCE

When importing a role with the following meta/main.yml

```yaml
  [...]
  platforms:
    - name: openSUSE
      versions:
      - Leap 15.1
  [...]
```
the Quality Score Details lists a warning "IMPORTER101: Invalid platform: "openSUSE-Leap 15.1", skipping. 

##### EXPECTED RESULTS
No warning and platform openSUSE (Version "Leap 15.1") is assigned to the imported role.

##### ACTUAL RESULTS
No platform is assigned to the imported role. Example role: https://galaxy.ansible.com/chkpnt/mailserver

**Comment by chouseknecht** [comment]
Added all but Tumbleweed.
