### ISSUE TITLE
namespace: InfluxData

### ISSUE THREAD

**Issue by BondAnthony** [ansible/galaxy#2264]
## Namespace Request
Namespace: InfluxData

##### Description

Add additional admins
##### GitHub Org Link

https://github.com/influxdata

##### Admins

spacer007
russorat

**Comment by BondAnthony** [comment]
@gundalow would it be possible to get a list of current admins? We're trying to track down who has access today.

**Comment by chouseknecht** [comment]
New admins added to `influxdata`. Admins can go to `My Content`, choose `Edit Properties` from the menu to the right of the namespace, and add/remove admins.
