### ISSUE TITLE
Rename epfl_idevelop to epfl_si

### ISSUE THREAD

**Issue by domq** [ansible/galaxy#2266]
## Namespace Request
Namespace: epfl_si

##### Description
EPFL. Systèmes d'Information (SI)

##### GitHub Org Link
https://github.com/epfl-si

##### Admins
- domq
- ponsfrilus
- honiix

💡If at all possible, please rename [the existing epfl_idevelop](https://galaxy.ansible.com/my-content/namespaces/12322) to epfl_si. We did the same rename on the GitHub side on Feb 12th.

**Comment by chouseknecht** [comment]
Done. Renamed `epfl_idevelop` to `epfl_si`.
