### ISSUE TITLE
Invalid namespace error when uploading a collection

### ISSUE THREAD

**Issue by plumbis** [ansible/galaxy#2268]
##### SUMMARY
I am an owner of the "CumulusNetworks" namespace on galaxy but when I try to upload a collection tar.gz I get an error that the name space is invalid

##### STEPS TO REPRODUCE
1.) Create collection tar.gz
2.) Upload via Add Content -> Upload New Collection buttons
3.) Receive error

##### EXPECTED RESULTS
The collection would upload. 

##### ACTUAL RESULTS
![Screen Shot 2020-02-26 at 10 39 06 AM](https://user-images.githubusercontent.com/10537576/75376065-3ff26900-5884-11ea-9178-7ce2219ec653.png)

**Comment by abenokraitis** [comment]
@thedoubl3j @anshulbehl @JohnLieske FYI can you take a look at this?

**Comment by thedoubl3j** [comment]
capital letters are the issue here I think. Namespace changed, let me know if it is still failing.

**Comment by plumbis** [comment]
changing the namespace + collection filename and galaxy.yml data seems to have fixed it. Thanks for the rapid turnaround.
