### ISSUE TITLE
namespace: FIXME

### ISSUE THREAD

**Issue by grastogi23** [ansible/galaxy#2273]
## Namespace Request
Namespace: 
avinetworks

##### Description

All Ansible modules for the Avi Networks (now VMware) modules

##### GitHub Org Link

https://github.com/avinetworks

##### Admins
avinetworks

grastogi23, chaitanyaavi, ericsysmin, khaltore

Here are existing galaxy modules
https://github.com/avinetworks/ansible-role-docker
https://github.com/avinetworks/ansible-role-avisdk
https://github.com/avinetworks/ansible-role-avicontroller
https://github.com/avinetworks/ansible-role-avicontroller-vmware
https://github.com/avinetworks/ansible-role-avise
https://github.com/avinetworks/ansible-role-aviconfig
https://github.com/avinetworks/ansible-role-avise-csp
https://github.com/avinetworks/ansible-role-avicontroller-csp
https://github.com/avinetworks/ansible-role-avimigrationtools

**Comment by chouseknecht** [comment]
Namespace `avinetworks` already exists, and user `grastogi23` is an owner. As an owner you can go to My Content, choose Edit Properties on the menu to the right of the Namespace, and add/remove owners and update other attributes.
