### ISSUE TITLE
Galaxy Login Issues (Server Error (500))

### ISSUE THREAD

**Issue by elct9620** [ansible/galaxy#2274]
##### SUMMARY

I have the same issue as in #2176, can't sign in to galaxy with GitHub account.

My username is `elct9620`.

##### STEPS TO REPRODUCE
Trying to login https://galaxy.ansible.com/accounts/login/

##### EXPECTED RESULTS
Sucessfull login.

##### ACTUAL RESULTS
When I try to sing up, I get:

> An account already exists with this e-mail address. Please sign in to that account first, then connect your GitHub account.

When I try to sign in with the old username, I get:

> Server Error (500)

**Comment by chouseknecht** [comment]
Deleted user `elct9620`. Please try to log in again.

**Comment by elct9620** [comment]
Login success, thanks 🎉
