### ISSUE TITLE
Namespace Request: netbox

### ISSUE THREAD

**Issue by FragmentedPacket** [ansible/galaxy#2277]
## Namespace Request
Namespace: netbox

##### GitHub Org Link

https://github.com/netbox-community/
##### Admins

- FragmentedPacket

If any questions, please review discussion: https://github.com/ansible/ansible/pull/67586

**Comment by thedoubl3j** [comment]
done

**Comment by thedoubl3j** [comment]
https://galaxy.ansible.com/netbox
