### ISSUE TITLE
Can't login via Github OAuth for jnpr-community-netdev

### ISSUE THREAD

**Issue by vnitinv** [ansible/galaxy#2280]
##### SUMMARY
even when we are logged into github page, we get kicked out to

![image](https://user-images.githubusercontent.com/767016/75946944-9420cd00-5ec4-11ea-9965-40a8b0f85eb9.png)

Might be something similar to 
https://github.com/ansible/galaxy/issues/1185

please help us in resolving this issue.

**Comment by vnitinv** [comment]
@ganeshrn Can you help us with this?

**Comment by chouseknecht** [comment]
@vnitinv 

There was a user named `Juniper` associated with the email address `jnpr-community-netdev@juniper.net` already in Galaxy. I suspect that's the issue, so I've gone ahead and deleted. Please try logging in again.

**Comment by chouseknecht** [comment]
Haven't heard back, so assuming this is fixed.

**Comment by vnitinv** [comment]
It's working fine. Thanks @chouseknecht
