### ISSUE TITLE
Namespace issue in collection

### ISSUE THREAD

**Issue by rahkumar651991** [ansible/galaxy#2281]
##### SUMMARY
Juniper has a role named juniper.junos. When we try to add the collection with namespace juniper.junos it gives an error of namespace conflict with the role. We want same namespace to be used for collection as well.

![image001](https://user-images.githubusercontent.com/58289625/75970214-078f0280-5ef6-11ea-95dd-29d1cb6843ea.png)

**Comment by abenokraitis** [comment]
Greetings, unfortunately existing roles and collections cannot have the same name, as it would create a conflict for the `ansible-galaxy` CLI tool. You have two options:
1. Move all existing roles into a new collection named `juniper.junos`
2. Leave all existing roles alone and create a new collection with a new name such as `juniper.junos_collection` or something.

**Comment by abenokraitis** [comment]
I believe the only issue users will have is that they will need to explicitly issue a `ansible-galaxy install collection juniper.junos` command, because without the `collection` would default to a role install.

**Comment by chouseknecht** [comment]
Closing, as this has been answered.
