### ISSUE TITLE
Galaxy namespace for Project Receptor

### ISSUE THREAD

**Issue by j00bar** [ansible/galaxy#2285]
## Namespace Request
Namespace: project-receptor

##### Description
Project Receptor is a flexible multi-service relayer with remote execution and orchestration capabilities linking controllers with executors across a mesh of nodes.

##### GitHub Org Link
https://github.com/project-receptor

##### Admins
matburt
jhjaggars
ghjm
j00bar

**Comment by cutwater** [comment]
Done.
