### ISSUE TITLE
Can’t login to ansible galaxy. Get 500 error

### ISSUE THREAD

**Issue by notjustanyjoe** [ansible/galaxy#2292]
SUMMARY

I have the same issue as in #2048, can't sign in to galaxy with github account.

My previous username was josephgsalas. 

STEPS TO REPRODUCE

Trying to login https://galaxy.ansible.com/accounts/login/

EXPECTED RESULTS

Sucessfull login.

ACTUAL RESULTS

When I try to sing up, I get:

An account already exists with this e-mail address. Please sign in to that account first, then connect your GitHub account.
When I try to sign in with old username, I get:

Server Error (500)

**Comment by chouseknecht** [comment]
Deleted user `josephgsalas`.  Please attempt to login again.

**Comment by notjustanyjoe** [comment]
That worked. Thank you.
