### ISSUE TITLE
Lots of deprecated collections appear on Galaxy search results landing page

### ISSUE THREAD

**Issue by geerlingguy** [ansible/galaxy#2294]
When I go to Galaxy and click on one of the categories (e.g. "System", "Playbook Bundles", or any of them, really), I end up seeing a lot of deprecated collections on the first page of results:

<img width="1300" alt="Screen Shot 2020-03-13 at 10 37 55 AM" src="https://user-images.githubusercontent.com/481677/76636298-ceb6e500-6516-11ea-9df9-057712bbcbd4.png">

This doesn't inspire a lot of confidence, seeing that at least half of the content listed is deprecated.

I think we should make sure that 'Deprecated' content (roles or collections) is always listed at the end of any results. Otherwise, search ordering still seems quite arbitrary in general, but there's already a separate issue for the general ordering for 'relevancy': https://github.com/ansible/galaxy/issues/1994

## Steps to reproduce

  1. Visit https://galaxy.ansible.com
  2. Click on one of the 'Most Popular' links (e.g. "System" or "Playbook Bundles")
  3. Observe the results.

## Expected Result

  - Relevant results would be returned.
  - I won't see collections and / or roles that are deprecated (or if so, they're at the end of the results).

## Actual Result

  - Many deprecated collections are on the first page.
  - Search result ordering seems arbitrary.

**Comment by chouseknecht** [comment]
That's not actually true. When you first access the Search page, the `deprecated=false` filter is in place, and thus no deprecated Collection appear. If you click `Clear Filters` at any point that filter goes away, and all the deprecated Collections appear.

**Comment by geerlingguy** [comment]
@chouseknecht 

> When I go to Galaxy and click on one of the categories

![galaxy-deprecated](https://user-images.githubusercontent.com/481677/76860347-dd5c0f80-6828-11ea-9717-e7925086d910.gif)

**Comment by chouseknecht** [comment]
Ah. That's different. That seems like a simple bug.

**Comment by geerlingguy** [comment]
> That seems like a simple bug.

Good!

Not sure about priority/low, however—this is one of the CTAs on the home page of Galaxy, and it makes for a pretty jarring user experience when someone is excited to start using Ansible, and the first thing they do is click a category, and see a bunch of Deprecated stuff.

**Comment by geerlingguy** [comment]
PR here: https://github.com/ansible/galaxy/pull/2309

In action:

![galaxy-deprecated-fix](https://user-images.githubusercontent.com/481677/77789299-c12e4e80-7030-11ea-8874-1916068591c4.gif)
