### ISSUE TITLE
please rename role ansible_local_certificate_authority_role to  local_certificate_authority

### ISSUE THREAD

**Issue by tpo** [ansible/galaxy#2295]
##### SUMMARY
It seems like telling `ansible-galaxy` to use a different `--role-name` [doesn't work](https://github.com/ansible/ansible/issues/68283) doesn't work.

Could you please rename the [ansible_local_certificate_authority_role](https://galaxy.ansible.com/tpo/ansible_local_certificate_authority_role) to "local_certificate_authority"?

I expect to be uploading other roles to Ansible Galaxy. I'd be very glad no know how to upload them "correctly" in the future, so that Github project name != role name, to spare you work?

**Comment by chouseknecht** [comment]
I would recommend that we delete the role from Galaxy. If you don't have the ability to do this, we can do it. From there, name the repository as you wish it to appear in Galaxy.

I'm not sure where we left things with `role_name`. I think once a role is imported into Galaxy, `role_name` is ignored. In other words, you may not be able to use it to override the name of the role after the fact. It might only work on the first import.

**Comment by tpo** [comment]
Hi @chouseknecht ,

I've deleted and reimported the role with `role_name` correctly set. I had searched my tickets for this one but didn't find it, so I didn't close it, which I herewith do.

*Thanks a lot* for coming back to this ticket and caring!
