### ISSUE TITLE
Random 401 errors when trying to download roles

### ISSUE THREAD

**Issue by Kocal** [ansible/galaxy#2298]
Hi :wave: 

##### SUMMARY
When running `ansible-galaxy install` we have random 401 errors that happen.

##### STEPS TO REPRODUCE
Install a dependency or a list of dependency: `ansible-galaxy install -r requirements.yml`

##### EXPECTED RESULTS
It should not randomly fail.

##### ACTUAL RESULTS

I have an error 401 why trying to download role `DavidWittman.Redis` 
![Sélection_152](https://user-images.githubusercontent.com/2103975/77419377-9772ee80-6dc8-11ea-8412-28797a78b8f9.png)

After some seconds, the role `DavidWittman.redis` has been downloaded correctly and everything is okay:
![Sélection_153](https://user-images.githubusercontent.com/2103975/77419448-b3769000-6dc8-11ea-9ca4-ceb51c7b8666.png)

It's not specific to `DavidWittman.redis`, sometimes it's the dependency `influxdata.chronograf` which triggers a 401 :confused: 

Thanks!

**Comment by gabops** [comment]
Same here when installing "geerlingguy.pip" role from requirements file.

**Comment by chouseknecht** [comment]
Your error message seems to indicate that the failure is on GitHub. The role that didn't install is `https://github.com/DavidWittman/ansible-redis/archive/1.2.7.tar.gz`. That's not a Galaxy server issue.

**Comment by Kocal** [comment]
Oh yes you're right, sorry!

**Comment by wongyouth** [comment]
I have the same 401 issue when using `ansible-galaxy install`, but can download by wget.
![image](https://user-images.githubusercontent.com/944583/86505161-fa2a4c00-bdf3-11ea-81d3-b8f3bfd4fc1b.png)
