### ISSUE TITLE
IMPORTER101: Invalid platform: "os10-all", skipping error for my collections

### ISSUE THREAD

**Issue by parkrish** [ansible/galaxy#2300]
##### SUMMARY
The os10 collections published to the galaxy https://galaxy.ansible.com/dellemc_networking/os10 is reporting warning for metadata for the roles in the collections.

===== LOADING ROLE ===== 
Checking role metadata tags 
Checking role platforms 
Invalid platform: "os10-all", skipping. 
 

##### STEPS TO REPRODUCE
Following is the content of my meta/main.yml file

# copyright (c) 2020 Dell Inc. or its subsidiaries. All Rights Reserved.
---
galaxy_info:
  author: Dell EMC Networking Engineering
  description: The os10_aaa role facilitates the configuration of Authentication Authorization Acccounting (AAA) attributes in devices running Dell EMC Networking Operating Systems.
  license:  Apache 2.0
  min_ansible_version: 2.2

  platforms:
  - name: os10

  galaxy_tags:
    - networking
    - dell 
    - emc
    - dellemc
    - os10

##### EXPECTED RESULTS
Platform: os10 be accepted and metadata score be not reduced.

**Comment by chouseknecht** [comment]
Add platform `os10` with release `all`. This should work now. Please let us know if you run into any additional issues.
