### ISSUE TITLE
namespace: veeamhub

### ISSUE THREAD

**Issue by carceneaux** [ansible/galaxy#2310]
## Namespace Request
Namespace: veeamhub

##### Description
VeeamHub projects are community driven projects, and are not created by Veeam R&D nor validated by Veeam Q&A. They are maintained by community members which may or not be Veeam employees.

##### GitHub Org Link
https://github.com/veeamhub

##### Admins
carceneaux

**Comment by carceneaux** [comment]
I thought I had taken care of this but when I try to publish my collection using `ansible-galaxy` it fails with `Namespace "veeamhub" does not exist`.

![image](https://user-images.githubusercontent.com/17179966/79280049-63499580-7e7d-11ea-8cda-89df9a10d49e.png)

![image](https://user-images.githubusercontent.com/17179966/79280022-59279700-7e7d-11ea-9255-c881c0093a2b.png)
 
Thanks for your help!

**Comment by carceneaux** [comment]
When I publish to namespace `carceneaux`, I have no issues.

**Comment by chouseknecht** [comment]
Created namespace `veeamhub`. You should be good.
