### ISSUE TITLE
Incorporate module/plugin linting into quality score for collections

### ISSUE THREAD

**Issue by geerlingguy** [ansible/galaxy#2311]
### Use Case

Currently, it seems that only roles and collections that have roles in them affect Galaxy content's 'Quality score'. It would be nice if collections' other content (besides roles) also had an impact on quality score (or were reflected in the score).

The motivation is the fact there are now many collections with no roles, thus showing "0/5" for the quality score (with "No Score Available"). For example, the [`community.kubernetes` collection](https://galaxy.ansible.com/community/kubernetes):

<img width="1319" alt="Screen Shot 2020-03-27 at 4 19 58 PM" src="https://user-images.githubusercontent.com/481677/77801407-d0b89200-7046-11ea-8323-d75183c33105.png">

### Proposed Solution

  - Individual roles, modules, plugins, etc. are linted (using `ansible-test sanity` [?] and `ansible-lint`, as needed). Each item in a collection gets a score.
  - The scores of all the included items are averaged into the overall 'Quality score' metric, which is displayed in the UI and affects search ranking.

### Alternatives

Getting rid of the quality score, or breaking it up into multiple metrics, like 'roles quality', 'modules quality', etc.

### Implementation

N/A

### Related Issues

  - https://github.com/ansible/galaxy/issues/363
  - https://github.com/ansible/galaxy/issues/365
  - https://github.com/ansible/galaxy/issues/1994

**Comment by chouseknecht** [comment]
Nope. Quality score for collections is going away.
