### ISSUE TITLE
Red8Labs Namespace Request

### ISSUE THREAD

**Issue by stobias123** [ansible/galaxy#2312]
## Namespace Request
Namespace: red8labs

##### Description
I work at Red8 - we call our internal development red8labs. I'd like to publish shared content for our clients and workshops to the red8labs namespace.

##### GitHub Org Link
https://github.com/RedEight

##### Admins
stobias123
jfmatth

**Comment by gundalow** [comment]
jfmatth doesn't appear to have logged into Galaxy.

Namespace has been created, so once they've logged in once, you'll need to add them.
