### ISSUE TITLE
Namespace request for the performancecopilot project

### ISSUE THREAD

**Issue by natoscott** [ansible/galaxy#2313]
## Namespace Request
Namespace: performancecopilot

##### Description
We'd like to use an organisation namespace for our work on the Performance Co-Pilot Ansible role, rather than using my personal account.

##### GitHub Org Link
https://github.com/performancecopilot

##### Admins
https://github.com/natoscott
https://github.com/portante
https://github.com/andreasgerstmayr

**Comment by gundalow** [comment]
https://galaxy.ansible.com/performancecopilot now exists, enjoy!

**Comment by natoscott** [comment]
@gundalow I don't seem to be able to upload a role to this namespace - any ideas what I might be doing wrong?  In the Galaxy web interface, the 'role' option is greyed out (for uploads within the performancecopilot namespace - no problem to do this in my 'natoscott' user account) and it seems it will only allow me to upload a collection (not greyed out, but I don't have a collection)?  Thanks!
