### ISSUE TITLE
Namespace Request

### ISSUE THREAD

**Issue by vanguard737** [ansible/galaxy#2314]
## Namespace Request
Namespace: alpha29

##### Description
Roles for Linux servers and workstations.

##### GitHub Org Link
https://github.com/alpha29/

##### Admins
@vanguard737

(I *think* this is still the right way to request a namespace, yeah?  If you guys need more info, let me know - thanks.)

**Comment by vanguard737** [comment]
ping

**Comment by gundalow** [comment]
Created
