### ISSUE TITLE
Collections: remove quality score and add docs renderer

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#2317]
We're porting the AH collection importer to Galaxy. This will create a consistent experience for contributors to both platforms. As part of this work, we need to also do the following:

- [x] hide any quality score info related to Collections in the UI. The current quality score only relates to roles. It doesn't do anything with regard to plugins, so on the whole it's not very meaningful.
- [ ] ~~if it's not too complex, add the docs renderer javascript to the UI. In AH we're able to surface `.md` styles docs in the UI. Since the importer will be capturing this info in the Galaxy database, it makes sense to surface it, if we can~~.

**Comment by chouseknecht** [comment]
Blocked by #2323

**Comment by ironfroggy** [comment]
The content survey still is shown for collections, tho the scores have been removed from results.

![galaxy_collection_score](https://user-images.githubusercontent.com/34982/81439965-467f4580-913d-11ea-9c4b-cba0a6e8dd84.jpeg)

**Comment by ironfroggy** [comment]
👍
