### ISSUE TITLE
This provider namespace is already associated with a Galaxy namespace

### ISSUE THREAD

**Issue by luisescobar89** [ansible/galaxy#2320]
##### SUMMARY
I have my own namespace (`luisescobar89`) but I am also the part of the GitHub organization `Dynatrace`. Both `luisescobar89` and `Dynatrace` exist as namespaces in Ansible Galaxy but I (`luisescobar89`) appear not to be able to be the Provider Namespace for both of them. When I try to add myself as a Provider Namespace for `Dynatrace` I'm presented with the message This provider namespace is already associated with a Galaxy namespace (`Dynatrace`)

Is is possible for me to be the name provider for `Dynatrace`?

##### STEPS TO REPRODUCE
Login to Ansible Galaxy
Navigate to the Edit Properties for `luisescobar89`
Select `Dynatrace` from the list of Provider Namespaces
Click Save

##### EXPECTED RESULTS
Become the Provider Namespace for the `Dynatrace` namespace.

##### ACTUAL RESULTS
**Error dialogue with the message** This provider namespace is already associated with a Galaxy namespace (`Dynatrace`)

**Comment by chouseknecht** [comment]
Looks like `luisescobar89` is no longer associated with any namespace. You can go to My Content, edit `Dynatrace` and add `luisescobar89` as a provider namespace.

**Comment by chouseknecht** [comment]
Added `luisescobar89` as an owner of `Dynatrace`.
