### ISSUE TITLE
Galaxy Login Issues (Server Error (500))

### ISSUE THREAD

**Issue by r0drigomarques** [ansible/galaxy#2327]
##### SUMMARY
I have the same issue as in #2176 and #2274, can't sign in to galaxy with GitHub account.

My email is rodrigo.marques---at---gmail.com.

##### STEPS TO REPRODUCE
Trying to login https://galaxy.ansible.com/accounts/login/

##### EXPECTED RESULTS
Sucessfull login.

##### ACTUAL RESULTS
When I try to sing up, I get:

An account already exists with this e-mail address. Please sign in to that account first, then connect your GitHub account.

When I try to sign in with the old username, I get:

Server Error (500)

**Comment by chouseknecht** [comment]
User `rodrigo.marques` deleted. That should fix the issue.
