### ISSUE TITLE
Feature Request: Allow deletion of a colleciton

### ISSUE THREAD

**Issue by resmo** [ansible/galaxy#2330]
### Use Case
people try things out and can't delete the mess afterwards. Also see #2123

### Proposed Solution
Allow deletion of collection on galaxy.ansible.com with a big fat red warning that this will break things.

### Alternatives
none

**Comment by chouseknecht** [comment]
Try things in `galaxy-dev.ansible.com`. You deprecate collection but not delete. That's by design.
