### ISSUE TITLE
Imports delayed by huge gaps between completion and start of each import

### ISSUE THREAD

**Issue by ironfroggy** [ansible/galaxy#2333]
##### SUMMARY
Imports are slower on galaxy-dev after the galaxy-importer deploy, but the bulk of the time lost appears to be spent between imports. After one import completes, it takes more than an hour for the next job to begin.

##### STEPS TO REPRODUCE

Try to run two imports on galaxy-dev, then watch your imports and see how long you must wait between the first completing and the second beginning.

##### EXPECTED RESULTS

There should be little or no gap between imports.

##### ACTUAL RESULTS

![SharedScreenshot](https://user-images.githubusercontent.com/34982/78717270-5ca3a700-78ee-11ea-9150-dc12f5349fe3.jpg)

Note the completion times on these imports.

```

```

**Comment by awcrosby** [comment]
During a https://galaxy-dev.ansible.com import, after the `galaxy-importer` loading, there is the [atomic transaction](https://github.com/ansible/galaxy/blob/devel/galaxy/worker/tasks/collection.py#L132) writing `Collection`, `CollectionVersion`, and some `pulp_model`s. During this transaction the import hangs, sometimes indefinitely, and the `postgres` container is constrained on resources. This is not reproducible on local development environment. 

Increasing the openshift galaxy-dev container size helped but did not resolve the issue: `.4cpu/1Gi`: 8min hang, `1.0cpu/1Gi`: 3min hang

Likely next step: Revert recent addtion of `galaxy-importer` and run QE tests with just the updated python dependencies, notably testing the change from `django==2.1.11` to `django=2.2.11`

**Comment by chouseknecht** [comment]
Our current understanding is that this is environment specific. Stems from the amount of test data sitting in `galaxy-dev`
