### ISSUE TITLE
ansible galaxy install offline

### ISSUE THREAD

**Issue by dineshtobe** [ansible/galaxy#2334]
I need to install Juniper.junos package in ansible-galaxy . Internet access is restricted from device/

I need to install it offline.

ansible-galaxy install Juniper.junos

**Comment by chouseknecht** [comment]
`Juniper.junos` is an Ansible role. You can install the role and copy the resulting directory structure internally. You can also [visit the GitHub project](https://github.com/Juniper/ansible-junos-stdlib/releases), download the source directly, and copy to wherever you need.

If you're looking for changes to the `ansible-galaxy` CLI, please file an issue [at the Ansible project](https://github.com/ansible/ansible).
