### ISSUE TITLE
namespace: zuul

### ISSUE THREAD

**Issue by emonty** [ansible/galaxy#2336]
## Namespace Request
Namespace: zuul

##### Description
Collections related to Zuul CI

##### GitHub Org Link
There is no github org - zuul is hosted at https://opendev.org/zuul

##### Admins
emonty
jeblair

**Comment by gundalow** [comment]
Done https://galaxy.ansible.com/zuul
You can set an avatar and update descriptions etc

**Comment by ssbarnea** [comment]
@emonty What is the progress with use of zuul namespace? I would really like to see zuul-jobs published as a single collection, even manually for start until we setup a proper pipeline.

**Comment by emonty** [comment]
We haven't really started working on this yet, largely because so-far zuul doesn't have support for _using_ code from collections yet (due to min supported Ansible being <2.9 still)

That said - thanks for the reminder. There are a few modules that we'd like to publish in individual collections too.
