### ISSUE TITLE
namespace: honeylogic

### ISSUE THREAD

**Issue by danihodovic** [ansible/galaxy#2339]
## Namespace Request
Namespace: honeylogic

##### Description
HoneyLogic (https://honeylogic.io)

##### GitHub Org Link
https://github.com/honeylogic-io

**Comment by chouseknecht** [comment]
Namespace `honeylogic` created.

**Comment by danihodovic** [comment]
Thanks!

cc @adinhodovic

**Comment by danihodovic** [comment]
Could you rename the namespace to `honeylogic-io`. It seems like it has to match the Github org.

![image](https://user-images.githubusercontent.com/5557301/80133532-0bf6a400-85a6-11ea-95b2-3a98ec4bb483.png)
