### ISSUE TITLE
Galaxy Login Issues (Server Error (500))

### ISSUE THREAD

**Issue by pmarques** [ansible/galaxy#2340]
# Bug Report 

##### SUMMARY

I have the same issue as in #2048, can't sign in to galaxy with github account since I had a previous account with same username: **pmarques**

**Comment by chouseknecht** [comment]
@pmarques 

Not finding an existing account for `pmarques`. Was the username of the existing account different?

**Comment by chouseknecht** [comment]
Poked around in our database using your GitHub UID and couldn't find an account that way either.

**Comment by pmarques** [comment]
@chouseknecht maybe it's my fault, can you check the username patrickfmarques or email address patrickfmarques at gmail dot com ?

**Comment by chouseknecht** [comment]
Found user `patrickfmarques` and removed from the database. Please try logging in a again.

**Comment by pmarques** [comment]
It worked, thanks!
