### ISSUE TITLE
namespace: tranquilit

### ISSUE THREAD

**Issue by agauvrit-tis** [ansible/galaxy#2343]
## Namespace Request
Namespace: tranquilit

##### Description
Tranquil IT provides Ansible roles to install WAPT Server, deploy WAPT agent and configure WAPT repository replication.

##### GitHub Org Link
https://github.com/tranquilit

##### Admins
- agauvrit_tis

**Comment by chouseknecht** [comment]
Namespace `tranquilit` created.
