### ISSUE TITLE
Namespace Request

### ISSUE THREAD

**Issue by lucasmaurice** [ansible/galaxy#2351]
## Namespace Request
Namespace: justereseau

##### Description
Netwok and Infrastrucure Team of the student club Lan ETS.

##### GitHub Org Link
https://github.com/justereseau

##### Admins
https://github.com/lucasmaurice

The namespace already exist but I can't add the github organisation to the Provider Namespaces. The organisation is not in the list of availables Provider Namespaces.

**Comment by chouseknecht** [comment]
I don't see the provider namespace 'justereseau' in our database. It may be that Galaxy does not have access to it. Check that you granted read access to the Galaxy application. Also, is it possible that the organization name changed at some point? If so, what was the old name?

**Comment by lucasmaurice** [comment]
Thanks for the answer!

We never changes the name of the organisation.

Where should I go to allow the read access to the application ?

**Comment by lucasmaurice** [comment]
Where should I go to allow the read access to the application ? I can't find the setting in the organisation settings.

**Comment by chouseknecht** [comment]
Think what I would do is go here: https://github.com/settings/applications Then click on the *Authorized Oauth Apps*, find Ansible Galaxy, and revoke its access.

**Comment by lucasmaurice** [comment]
Oh thank's I finally find it! It work well.

Thanks for the help!
