### ISSUE TITLE
Namespace request: datacom 

### ISSUE THREAD

**Issue by vgkleinubing** [ansible/galaxy#2354]
Namespace: datacom

##### Description:
DATACOM is the leading manufacturer of network equipment for data telecommunication in Latin America

##### GitHub Org Link:
https://github.com/datacom-teracom

##### Admins:
vgkleinubing / https://github.com/vgkleinubing
witter-datacom / https://github.com/witter-datacom

**Comment by chouseknecht** [comment]
Done
