### ISSUE TITLE
SSH Error Ansible

### ISSUE THREAD

**Issue by telus-beep** [ansible/galaxy#2355]
## Bug Report 
ssh error

##### SUMMARY
[root@osboxes osboxes]# ansible-playbook check.yml -i host -k
SSH password: 

PLAY [Various Checks] ***********************************************************************

TASK [Checks IP Status] *********************************************************************
fatal: [R3]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "Error reading SSH protocol banner"}

PLAY RECAP **********************************************************************************
R3                         : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

When running playbook from ansible controller with jump host to cisco device I get this error
 
ansible 2.9.6
python version = 2.7.5 
```

**Comment by chouseknecht** [comment]
Pleas file this issue at the [ansible project](https://github.com/ansible/ansible). I would also recommend requesting help on IRC at the Freenode #ansible channel.
