### ISSUE TITLE
unable to map namespace to my account

### ISSUE THREAD

**Issue by bjarnoldus** [ansible/galaxy#2361]
### SUMMARY
I have my own namespace (bjarnoldus) but I am also the part of the GitHub organization repleo. Both bjarnoldus and repleo exist as namespaces in Ansible Galaxy but it appears not to be able to set the Provider Namespace for both of them. When I try to add "repleo" as a Provider Namespace for repleo I'm presented with the message This provider namespace is already associated with a Galaxy namespace (repleo)

Is is possible for me to set the name provider for repleo?

### STEPS TO REPRODUCE
Login to Ansible Galaxy
Navigate to the Edit Properties for repleo
Select repleo from the list of Provider Namespaces
Click Save

### EXPECTED RESULTS
Add repleo as the Provider Namespace for the repleo namespace.

### ACTUAL RESULTS
Error dialogue with the message This provider namespace is already associated with a Galaxy namespace (repleo)

**Comment by chouseknecht** [comment]
Appears the provider namespace `repleo` was associated with the namespace `Repleo`, rather than `repleo`. Notice the case difference. Deleted the `Repleo` namespace, so that you can associate with it with `repleo`.
