### ISSUE TITLE
Galaxy Login Issues (Server Error (500))

### ISSUE THREAD

**Issue by kalranitin** [ansible/galaxy#2366]
I have the same issue as in #2176, can't sign in to galaxy with GitHub account.

My username is kalranitin (email kalranitin@hotmail.com).
STEPS TO REPRODUCE

Trying to login https://galaxy.ansible.com/accounts/login/
EXPECTED RESULTS

Sucessfull login.
ACTUAL RESULTS

When I try to sing up, I get:

    An account already exists with this e-mail address. Please sign in to that account first, then connect your GitHub account.

When I try to sign in with the old username, I get:

    Server Error (500)

**Comment by chouseknecht** [comment]
Removed the existing user account. That should fix the issue.

**Comment by chouseknecht** [comment]
Assuming this is fixed and closing.
