### ISSUE TITLE
Recurrent failure of role imports on ansible galaxy since approx Apr.22 (continued)

### ISSUE THREAD

**Issue by Voronenko** [ansible/galaxy#2369]
## Bug Report 

Roles import launched from CD/CI tools continues to misbehave.

Related issue:  https://github.com/ansible/galaxy/issues/2362

New error message 
```
Starting import: task_id=621757, repository=softasap/sa-gitlab-runner 
 
Task "621757" failed: 401 {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'} 
```

ansible galaxy is pinged like

```
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
```

confirmed by  @tobias-richter  

CC: @cutwater @chouseknecht

**Comment by tobias-richter** [comment]
@Voronenko thanks for creating this issue! If I can do anything please let me know.

**Comment by chouseknecht** [comment]
Fix merged for this. Let us know, if you run into further issues.
