### ISSUE TITLE
Make path part of URL case insensitive

### ISSUE THREAD

**Issue by machacekondra** [ansible/galaxy#237]
When accessing any organization/user on github the path part of URL is case insensitive, following URLs, all will take you on same page:

 - https://github.com/oVirt/
 - https://github.com/ovirt/
 - https://github.com/ovirT/
 - https://github.com/OVIRT/

But in Ansible Galaxy the users are case sensitive so following two URLs are completely different:

 - https://galaxy.ansible.com/ovirt/
 - https://galaxy.ansible.com/oVirt/

Since Galaxy is integrated only with github, the URL should be consistent.

**Comment by chouseknecht** [comment]
We'll address this as part of refactoring Galaxy namespaces #243

**Comment by chouseknecht** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Case insensitive URLs](https://trello.com/c/xemKlnbF/7-case-insensitive-urls)

**Comment by chouseknecht** [comment]
The route to the content detail page is `:namespace/:repository`. Working on it in PR #447. When fetching the requested repository and content, the queries are forced to lowercase. You can see the actual queries by [viewing the resolver code here](https://github.com/ansible/galaxy/pull/447/files#diff-04a504b7f43c062ce5a7c464abc08217R25).

**Comment by chouseknecht** [comment]
Fixed in 3.0

**Comment by machacekondra** [comment]
@chouseknecht So now following URLs:

https://galaxy.ansible.com/oVirt/ovirt-ansible-roles
https://galaxy.ansible.com/ovirt/ovirt-ansible-roles

Both goes to the: `ovirt/ovirt-ansible-roles`.
Unfortunately, this is not right. I would like to remove `ovirt/ovirt-ansible-roles`, but I don't remember how did I upload it. It would be great if it could be removed and only will persist `oVirt/ovirt-ansible-roles`. But for some reason I can't remove `ovirt/ovirt-ansible-roles`, looks like some bug to me. Can you please remove it, so those URLs are correct? Thanks!
