### ISSUE TITLE
l3o

### ISSUE THREAD

**Issue by cfelder** [ansible/galaxy#2372]
## Namespace Request
Namespace: l3o

##### Description
l3o.io ansible collections and roles

##### GitHub Org Link
https://github.com/l3o-io

##### Admins
* cfelder

Hi I am the owner of l3o.io domain as well as l3o-io namespace on GitHub. It would be great to share the l3o namespace here.

**Comment by chouseknecht** [comment]
Done

**Comment by cfelder** [comment]
Thanks
