### ISSUE TITLE
Namespace Request T_Systems_MMS

### ISSUE THREAD

**Issue by rndmh3ro** [ansible/galaxy#2376]
## Namespace Request
Namespace: T_Systems_MMS

##### Description
 Collections managed by the T-Systems Multimedia Solutions GmbH

##### GitHub Org Link
https://github.com/T-Systems-MMS

##### Admins
- https://galaxy.ansible.com/rndmh3ro/
- https://galaxy.ansible.com/schurzi

**Comment by chouseknecht** [comment]
Created the namespace. Found user `schurzi`. Don't see a user by the name of `rndmh3ro`.

**Comment by rndmh3ro** [comment]
Well it's right here:
https://galaxy.ansible.com/rndmh3ro

Maybe check under "zufallsheld" or mail address galaxy@gumpri.ch

**Comment by rndmh3ro** [comment]
schurzi made me admin, thanks!
