### ISSUE TITLE
Galaxy Login Issues (Server Error (500))

### ISSUE THREAD

**Issue by felsen** [ansible/galaxy#2377]
I have the same issue as in #2176, can't sign in to galaxy with GitHub account.

My username is ```felsen``` (<felsen88@gmail.com> )

##### STEPS TO REPRODUCE
Trying to login https://galaxy.ansible.com/accounts/login/

##### EXPECTED RESULTS
Login successful

##### ACTUAL RESULTS
500 Error

**Comment by chouseknecht** [comment]
I deleted user `felsen` from our database. Please try logging in again.

**Comment by felsen** [comment]
@chouseknecht Thank you, It works fine. :)
