### ISSUE TITLE
Galaxy Login Issue (Server Error (500))

### ISSUE THREAD

**Issue by mkoshelev** [ansible/galaxy#2378]
##### SUMMARY
Hi, I'm trying to link my Ansible Galaxy account with GitHub but I get Server Error 500 after signing in to Galaxy. I've reset my password, but login still results in Server Error 500. This seems to be a common issue - could you please help ?

My email is m.koshelev@gmail.com

##### STEPS TO REPRODUCE
Use https://galaxy.ansible.com/accounts/login/ to login

##### EXPECTED RESULTS
Login should work.

##### ACTUAL RESULTS
Server returns error 500 every time.

```

```

**Comment by chouseknecht** [comment]
Deleted user `mkoshelev`. Please try logging in again.

**Comment by mkoshelev** [comment]
Login works now, thank you!
