### ISSUE TITLE
namespace: honeylogic-io

### ISSUE THREAD

**Issue by danihodovic** [ansible/galaxy#2380]
## Namespace Request
Namespace: honeylogic-io

##### Description
HoneyLogic (https://honeylogic.io)

##### GitHub Org Link
https://github.com/honeylogic-io

##### Admins
- danihodovic

**Comment by chouseknecht** [comment]
Done. Note that the namespace is actually `honeylogic_io`.

**Comment by danihodovic** [comment]
@chouseknecht That doesn't match the Github namespace and makes it impossible to add roles under that namespace.
