### ISSUE TITLE
Request zeroae namespace

### ISSUE THREAD

**Issue by sodre** [ansible/galaxy#2385]
## Namespace Request
Namespace: zeroae

##### Description
The ZeroA.E., LLC Ansible Infrastructure

##### GitHub Org Link
https://github.com/zeroae

##### Admins
@sodre : [Galaxy link](https://galaxy.ansible.com/sodre)

**Comment by sodre** [comment]
Updated request with my link in Galaxy

**Comment by chouseknecht** [comment]
Done
