### ISSUE TITLE
namespace request: mpes

### ISSUE THREAD

**Issue by estevao90** [ansible/galaxy#2386]
## Namespace Request
Namespace: mpes

##### Description
Ministério Público do Estado do Espírito Santo (MPES) - Brasil

##### GitHub Org Link
https://github.com/MP-ES

##### Admins
-ecosta
-eulercamposbarros
-izontm
-rafaelbubach

**Comment by chouseknecht** [comment]
Namespace created with `estevao90` and `eulercamposbarros` as admins. Other admins can be added by going to My Content, and clicking on the *Edit Properties* option found in the menu to the right of the namespace.
