### ISSUE TITLE
Request InAccel namespace

### ISSUE THREAD

**Issue by eliaskoromilas** [ansible/galaxy#2387]
## Namespace Request
Namespace: `inaccel`

##### Description
InAccel

##### GitHub Org Link
https://github.com/inaccel

##### Admins
* `inaccelbot`

##### Extra
Purge `inaccelbot` namespace, including the related roles and collections.

**Comment by chouseknecht** [comment]
Done

**Comment by eliaskoromilas** [comment]
Could you please fulfil our **Extra** request too?

> Purge `inaccelbot` namespace, including the related roles and collections.

Thank you.
