### ISSUE TITLE
Galaxy thinks license and license_file are mutually exclusive

### ISSUE THREAD

**Issue by emonty** [ansible/galaxy#2388]
##### SUMMARY
After building a collection with the latest version of ansible-galaxy from tip of devel, the upload process failed with:

```
ERROR! Galaxy import process failed: Invalid collection metadata. The 'license' and 'license_file' keys are mutually exclusive (Code: None)
```

but nothing in ```ansible-galaxy collection build``` or ```ansible-test sanity``` complained.

It would be awesome if there was some sort of linter or build-time check that could be run as part of my CI or something.

##### STEPS TO REPRODUCE
Put both keys in galaxy.yml, make a collection, upload it to galaxy.

##### EXPECTED RESULTS
Something should complain before the upload step.

##### ACTUAL RESULTS
The upload bombs out.

**Comment by emonty** [comment]
Nevermind - it seems that ```ansible-test sanity``` actually would have caught this except that it ignores ```galaxy.yml``` if it's in ```.gitignore``` (which ours is since it's generated)

**Comment by felixfontein** [comment]
I seriously doubt ansible-test does that.

**Comment by chouseknecht** [comment]
@emonty @felixfontein 

You can also run the `galaxy-importer` locally. See [galaxy-importer here](https://github.com/ansible/galaxy-importer)

**Comment by emonty** [comment]
@chouseknecht yes! this is exactly what I was looking for

**Comment by pabelanger** [comment]
Just hit this. Thanks, going to also try galaxy-importer to validate the collection tarball.

**Comment by emonty** [comment]
@pabelanger https://review.opendev.org/#/c/729294/ has some wrapper logic you might need until https://github.com/ansible/galaxy-importer/pull/66 lands and is released.

**Comment by pabelanger** [comment]
@emonty thanks! Now integrated into our zuul jobs for collections.
