### ISSUE TITLE
Do I really need two files with dependencies?

### ISSUE THREAD

**Issue by WeslyG** [ansible/galaxy#2389]
## Feature Request
I develop my role and specify meta/main dependencies in it. Why should I do this also in requirements.yml, it makes me feel bad. Developing on node js I have package.json. Developing in Java - pom.xml, C# - csproj. In nodejs i run ```npm install``` and all the specified dependencies are installed locally, other package managers have similar behavior. In Ansible, I have a seemingly meta/main.yml and I just want to say ```ansible-galaxy install``` (I expect all locally specified dependencies to be installed, it's logical, a file with dependencies!) But no, I'm being asked to create another file! With other dependencies. So that I can install them through it. Do I have to think about syncing two files all the time? I spent many days re-reading the documentation and other questions on github to understand why this decision was made. If I haven't noticed the answer to this, let me know. But I would really like to have a single place to manage my dependencies.

### Use Case
I am developing a certain java application and wrote a role to install it, and I also need a Java role obviously. Now I'm writing a role for my server. It includes both the java and my app roles at the same time. I specify this in meta/main in the dependencies section. But I can't test the role locally or in CI without creating a ```requirements.yml``` file to install them! I just want to specify dependencies as always in the meta/main file and call local installation of all packages. This would allow my ci to run faster, and I would always have a logical single file with dependencies.

### Proposed Solution
I see it as logical to always have dependencies set from the meta/main.yml and not just for transitive dependencies. This would make my experience easier, and allow ci to work more conveniently.

### Alternatives
For now, as an "alternative", I load my own role from git every time I need to install dependencies (on ci or locally). This forces galaxy to install the roles specified in meta/main. I think this approach is very strange.

### Implementation
I see this as an option in the galaxy cli. For an example, ```ansible-galaxy install``` would be great, but since it expects to see roles/collections I would suggest the ```ansible-galaxy install local``` option.
The ability to use ```requirements.yml``` was probably important to someone. I think it is logical to leave it, so as not to break the current tools.

**Comment by chouseknecht** [comment]
These are things that need to be sorted out at the [ansible project](https://github.com/ansible/ansible), as that's where the `ansible-galaxy` CLI lives.
