### ISSUE TITLE
namespace: fortinet

### ISSUE THREAD

**Issue by chillancezen** [ansible/galaxy#2397]
## Namespace Request
Namespace: 
fortinet
##### Description

https://galaxy.ansible.com/fortinet

##### GitHub Org Link

https://github.com/fortinet

##### Admins

chillancezen

**Comment by chillancezen** [comment]
this is following https://github.com/ansible/galaxy/issues/2103, adding one more admin user.

@chouseknecht 
thanks

**Comment by chouseknecht** [comment]
`chillancezen` added as an admin.
