### ISSUE TITLE
namespace: fortinet

### ISSUE THREAD

**Issue by fortiweb** [ansible/galaxy#2400]
Namespace:
fortinet

Description
https://galaxy.ansible.com/fortinet

GitHub Org Link
https://github.com/fortinet

Admins
fortiweb

**Comment by fortiweb** [comment]
this is following #2103, adding one more admin user.

**Comment by chouseknecht** [comment]
There is no `fortiweb` account in Galaxy. You will need to first log into `galaxy.ansible.com` with that GitHub username. After logging in, any of the existing owners of the `fortinet` namespace can go to *My Content* and use the *Edit Properties* menu option to add additional owners.

**Comment by fortiweb** [comment]
> There is no `fortiweb` account in Galaxy. You will need to first log into `galaxy.ansible.com` with that GitHub username. After logging in, any of the existing owners of the `fortinet` namespace can go to _My Content_ and use the _Edit Properties_ menu option to add additional owners.

It's my mistask,  my account name in Galaxy is `yangsong01`, can you help set again? thanks a lot.
