### ISSUE TITLE
Namespace: ClockwerksSoftware

### ISSUE THREAD

**Issue by BenjamenMeyer** [ansible/galaxy#2402]
## Namespace Request
Namespace: ClockwerksSoftware

##### Description
For Clockwerks Software, LLC - a software and software services company with a mind to supporting Open Source.

##### GitHub Org Link
https://github.com/ClockwerksSoftware

##### Admins
BenjamenMeyer - https://github.com/BenjamenMeyer

**Comment by BenjamenMeyer** [comment]
@gundalow any updates? Any more information needed?

**Comment by chouseknecht** [comment]
Namepsace `clockwerkssoftware` created.

**Comment by BenjamenMeyer** [comment]
@chouseknecht thanks!
