### ISSUE TITLE
namespace: ramiroto

### ISSUE THREAD

**Issue by ramiroto** [ansible/galaxy#2407]
## Namespace Request
Namespace: ramiroto

##### Description
ramiroto

##### GitHub Org Link
https://github.com/ramiroto

##### Admins
ramiroto

Hi,
I'm creating this issue, but I don't know if this is the problem with my account, somehow I can't import my roles, even after authorizing Ansible Galaxy with Github it only returns Bad Request

**Comment by chouseknecht** [comment]
Deleted the `ramiroto` namespace and re-created it. Please re-associate the `ramiroto` GitHub org with it again, and try the import.

**Comment by ramiroto** [comment]
Hi,

For some reason it still doesn't work.
Things I've tried:

- Logged/Logout from Ansible Galaxy
- Removed Ansible Galaxy from Github as authorized app

When I try to view anything on **My content** page at Ansible Galaxy, it keeps showing a Github error.

**Comment by ramiroto** [comment]
When I click the 3 dots menu on **My content**, I get this error `Error! Query user failed: (Http failure response for https://galaxy.ansible.com/api/v1/providers/sources/: 500 OK)`

**Comment by chouseknecht** [comment]
Deleted the `ramiroto` namespace and user. Please try logging in again from scratch.

**Comment by ramiroto** [comment]
Hi Chris,

Now it's working, when I clicked **Import Role from Github** it showed my repositories.
Thank you for your time and support.
