### ISSUE TITLE
Galaxy login issue

### ISSUE THREAD

**Issue by armyf35** [ansible/galaxy#2408]
##### SUMMARY
Same issue as #2048 
When I try to sign in, through GitHub, I am prompted to sign in or sign up. When trying to sign into my old account I get a `Server Error (500)` upon login

Looks like from previous issues my account needs to be deleted. It should be as follows:
username: armyf35
email: armyf35@gmail.com

##### STEPS TO REPRODUCE
Login using the login button on https://galaxy.ansible.com

##### EXPECTED RESULTS
Successful login and linking of my old account w/github

##### ACTUAL RESULTS
`Server Error (500)`

**Comment by chouseknecht** [comment]
Deleted the existing `armyf35` account. Please try logging in again.

**Comment by armyf35** [comment]
That worked, thanks!
