### ISSUE TITLE
'local' namespace reservation for local content

### ISSUE THREAD

**Issue by geerlingguy** [ansible/galaxy#2409]
## Namespace Request

Namespace: `local`

##### Description

I do NOT want this namespace, but I was wondering if maybe we could make it a 'reserved' / 'blocked' namespace for local collections/roles, similar to how the domain `localhost` is blocked in the DNS system for local systems.

##### GitHub Org Link

N/A

##### Admins

N/A

**Comment by chouseknecht** [comment]
I created the `local` namespace and assigned @gundalow and @geerlingguy as owners. There's not any other way to reserve a namespace.

**Comment by geerlingguy** [comment]
@chouseknecht - Thanks! We can leave it alone then, and people will be able to use the local namespace for whatever purpose without risk of getting something from Galaxy accidentally.
