### ISSUE TITLE
namespace request : solarwinds

### ISSUE THREAD

**Issue by melord** [ansible/galaxy#2414]
## Namespace Request
Namespace: solarwinds

##### Description
IT monitoring and management tools

##### GitHub Org Link
https://github.com/solarwinds

##### Admins
melord
d-maslyk
lootek

**Comment by melord** [comment]
any updates?

**Comment by chouseknecht** [comment]
Done. 

There's no user `d-maslyk` in Galaxy. After that person logs in for the first time, you can add them on the My Content page. From the kabob menu to the right of the namespace, choose Edit Properties.
