### ISSUE TITLE
Unable to publish collection, invalid namespace

### ISSUE THREAD

**Issue by theNewFlesh** [ansible/galaxy#2416]
##### SUMMARY
I cannot publish my collection. I get an invalid namespace error. My collection is a aggregation of previously, separately published roles to ansible galaxy. I intend on deleting all those repositories and replacing them with this collection repo.

##### STEPS TO REPRODUCE
```
git clone git@github.com:theNewFlesh/dev-roles.git
ansible-galaxy collection build
ansible-galaxy collection publish ./theNewFlesh-dev_roles-1.0.0.tar.gz
```

##### EXPECTED RESULTS
A published collection

##### ACTUAL RESULTS
```
ERROR! Error when publishing collection to default (https://galaxy.ansible.com/api/) (HTTP Code: 400, Message: Invalid namespace: 'theNewFlesh' Code: invalid)
```

##### TRACEBACK
```
master ▶ ansible-galaxy collection publish ./theNewFlesh-dev_roles-1.0.0.tar.gz                                                                                               
Publishing collection artifact '/Users/alex/Documents/projects/dev-roles/theNewFlesh/dev_roles/theNewFlesh-dev_roles-1.0.0.tar.gz' to default https://galaxy.ansible.com/api/
ERROR! Error when publishing collection to default (https://galaxy.ansible.com/api/) (HTTP Code: 400, Message: Invalid namespace: 'theNewFlesh' Code: invalid)
```

**Comment by chouseknecht** [comment]
We might need to change your namespace to `thenewflesh` or `the_new_flesh`. I'm guessing the existing one doesn't fit within these guidelines: https://galaxy.ansible.com/docs/contributing/namespaces.html#namespace-limitations

**Comment by theNewFlesh** [comment]
I figured as much. the_new_flesh is fine.

**Comment by theNewFlesh** [comment]
...

**Comment by chouseknecht** [comment]
Changed to `the_new_flesh`.
