### ISSUE TITLE
brocade

### ISSUE THREAD

**Issue by jdmcclellan** [ansible/galaxy#2417]
## Namespace Request
Namespace:

**Comment by jdmcclellan** [comment]
Daniel Chung will be managing the Broadcom (Brocade) namespace.   Jason

**Comment by chouseknecht** [comment]
Namespace `brocade` created with `jdmcclellan` as owner. You can go to [My Content](https://galaxy.ansible.com/my-content/), and from the kabob menu to the right of the namespace, choose Edit Properties and add Daniel after he logs into Galaxy for the first time.

**Comment by jdmcclellan** [comment]
daniel_chung_broadcom has logged into galaxy.ansible.com through gitbhu.com but the name does not appear as one of the available name space owners to be chosen.

**Comment by chouseknecht** [comment]
I already added his username.
