### ISSUE TITLE
namespace: FIXME (change theNewFlesh to the_new_flesh)

### ISSUE THREAD

**Issue by theNewFlesh** [ansible/galaxy#2418]
## Namespace Request
Namespace: the_new_flesh

##### GitHub Org Link

Not an org just a user with 49 existing roles that I want to role into a collection.

##### Admins

theNewFlesh

**Comment by theNewFlesh** [comment]
related issue
https://github.com/ansible/galaxy/issues/2416

**Comment by chouseknecht** [comment]
Changed to `the_new_flesh`.
