### ISSUE TITLE
Requesting new namespace

### ISSUE THREAD

**Issue by till** [ansible/galaxy#2419]
## Namespace Request
Namespace: hostwithquantum

##### Description

Planetary Quantum GmbH

##### GitHub Org Link

https://github.com/hostwithquantum/

##### Admins

till15

**Comment by chouseknecht** [comment]
Done.

**Comment by till** [comment]
@chouseknecht Thank you, I just checked. I think I need to select our Github org for the namespace, but it doesn't show. Can you kick the wheels to sync Github? Or is this something I can do myself?

**Comment by chouseknecht** [comment]
If you're uploading collections, you don't need to do that.

There's no wheel to kick. It's likely a permission issue. You have to give Galaxy access to read the org.

**Comment by till** [comment]
@chouseknecht That seems correct. The App is authorized for my personal account and another GH Org. How do I add an org to that? Is there a screen on Galaxy to start the process?

**Comment by chouseknecht** [comment]
It's done on GitHub at https://github.com/settings/connections/applications/. Click on the *Oauth Apps* tab, and click on *Ansible Galaxy*.

**Comment by till** [comment]
@chouseknecht THANK YOU!

I had no idea. Okay, now the org shows up and I assigned it!

Thanks again!
