### ISSUE TITLE
New redhat Ansible Galaxy namespace

### ISSUE THREAD

**Issue by sabre1041** [ansible/galaxy#2421]
## Namespace Request
Namespace: redhat

##### Description
Upstream content 

##### GitHub Org Link
Right now, we have our initial content posted here:

https://github.com/wildfly-extras/ansible_collections_jcliff

However, I foresee that additional content that will be used as upstream content for downstream content

##### Admins
* sabre1041
* rpelisse

**Comment by chouseknecht** [comment]
Done

**Comment by abenokraitis** [comment]
Unfortunately, utilizing `redhat` as an upstream namespace in Galaxy is forbidden. The `redhat` namespace can only be used downstream in Automation Hub. Please move this collection to an upstream project namespace like `wildfly.jcliff` or `jcliff.jcliff` . @gundalow @chouseknecht can either of you help make this happen? Thank you!

**Comment by abenokraitis** [comment]
Moving to `wildfly.jcliff` per @sabre1041 in email.
