### ISSUE TITLE
namespace: adding owner to brocade

### ISSUE THREAD

**Issue by daniel-chung-broadcom** [ansible/galaxy#2423]
brocade name space has been created. However, my account daniel.chung@broadcom.com does not show up as available name space owners for Jason McClellan to assign. I am already a owner of brocade name space in github.com and I have logged into galaxy.ansible.com using github.com credential many times. Please provide detail instructions on how to make sure that I show up as available name space owners for Jason or add me to the list of owners for brocade. Thanks.

**Comment by chouseknecht** [comment]
User added to brocade.
