### ISSUE TITLE
My user with inappropriate access

### ISSUE THREAD

**Issue by dfederlein** [ansible/galaxy#2424]
Pretty sure I don't need the access Ansible Galaxy is telling me I have, since I haven't been a RH/Ansible Employee for over 18 months. Let's audit my user's permissions, please?

Also, can we make sure that my user is associated correctly as controlling the Mindpointgroup space, since I am in charge of those? I'm not sure how to ensure that given my user's current permissions.

**Comment by chouseknecht** [comment]
@dfederlein 

Deleted your account from Galaxy. Please log in again using your GitHub account, and that should create a new account from scratch.

**Comment by chouseknecht** [comment]
Haven't seen a response, so guessing we're good now.

**Comment by dfederlein** [comment]
Thanks, yeah we're good.
