### ISSUE TITLE
namespace: Alias for redhat_cop namespace

### ISSUE THREAD

**Issue by sean-m-sullivan** [ansible/galaxy#2426]
Currently believe that these are same owners of redhat-cop namespace, would like to keep that as alias with current roles so requirements.yml and other links don't break, and have redhat_cop be the new space that everything goes in. Please do not change namespace, yet, but want to know what our options are on the above. 

## Namespace Request
Namespace: redhat_cop

##### Description
The Red Hat Communities of Practice

##### GitHub Org Link
https://github.com/redhat-cop

##### Admins
Galaxy Users
@sabre1041 
@oybed

Thank you

**Comment by chouseknecht** [comment]
We don't have the ability to create aliases, but the namespace `redhat_cop` has been created. Now both `redhat-cop` and `redhat_cop` exist. Put new things in `redhat_cop`, and when you're ready we can move existing content to `redhat_cop`.

**Comment by sean-m-sullivan** [comment]
Thats great, I think the only question I would have, and as I'm not adminitstrator, when they login to galaxy the admins will see both namespaces, correct? and be able to select which one to add content to?

**Comment by chouseknecht** [comment]
Yes. They will see both namespaces on the *My Content* page, and can decide which one to use when adding content.
