### ISSUE TITLE
'builtin' namespace reservation for core content

### ISSUE THREAD

**Issue by geerlingguy** [ansible/galaxy#2432]
## Namespace Request
Namespace: `builtin`

##### Description

This namespace is reserved for Ansible core content.

##### GitHub Org Link

https://github.com/ansible

##### Admins

  - @geerlingguy 
  - @gundalow

**Comment by geerlingguy** [comment]
cc @jimi-c and @felixfontein (this was discussed during the contributor summit today)

**Comment by felixfontein** [comment]
I guess this should be special in the sense that's it impossible to have content under this name in galaxy (except if core team wishes to have something in there).

**Comment by geerlingguy** [comment]
@felixfontein - It seems that there's currently no feature that can do that (create a reserved namespace or create a namespace but block adding content to it). See related: https://github.com/ansible/galaxy/issues/2409

> There's not any other way to reserve a namespace.

**Comment by gundalow** [comment]
https://galaxy.ansible.com/builtin has been claimed, thanks
