### ISSUE TITLE
Import error: git clone returned non-zero exit status 128

### ISSUE THREAD

**Issue by Thulium-Drake** [ansible/galaxy#2435]
##### SUMMARY

Git error 128, but no explanation why it's using HEAD instead of whatever branch is supposed to be used (in this case 'master')
##### STEPS TO REPRODUCE

ansible-galaxy import Thulium-Drake ansible-role-sshd --role-name=sshd    

##### EXPECTED RESULTS

To import my role to Galaxy.
##### ACTUAL RESULTS

It borks, see below:
(other roles work just fine, just this one keeps borking out)

```
$ ansible-galaxy import Thulium-Drake ansible-role-sshd --role-name=sshd    
Successfully submitted import request 665948
Starting import: task_id=665948, repository=Thulium-Drake/ansible-role-sshd
 
Task "665948" failed: Command '['git', 'clone', '--quiet', '--depth', '1', '--branch', 'HEAD', 'https://github.com/Thulium-Drake/ansible-role-sshd.git', '/var/tmp/galaxy/imports/tmpz8i1063d']' returned non-zero exit status 128.
```

**Comment by chouseknecht** [comment]
Did you try setting `github_branch` in role metadata? There's an [example metadata file here](https://galaxy.ansible.com/docs/contributing/creating_role.html#role-metadata).

**Comment by Thulium-Drake** [comment]
No, this repo only has a single branch (master) and the import in question is supposed to import the latest tag (2.0.2).

And the interesting part is that the import has worked in the past (I haven't changed the meta file in 10 months), but stopped working 2 months ago (wasn't able to look into it earlier)

**Comment by Thulium-Drake** [comment]
So I ended up deleting the 'current' import of the role and run the import command again om my laptop, presto, import succeeded.

Still not entirely sure what the issue was, but it's working again :-)
