### ISSUE TITLE
No default namespace created

### ISSUE THREAD

**Issue by matthewcosgrove** [ansible/galaxy#2439]
##### SUMMARY
The [docs](https://galaxy.ansible.com/docs/contributing/namespaces.html) say "The first time you log into Galaxy using your GitHub credentials a namespace is created for your GitHub username automatically."

##### STEPS TO REPRODUCE
Login to Ansible Galaxy via GitHub

##### EXPECTED RESULTS
A namespace is created for my GitHub username automatically 

##### ACTUAL RESULTS
My Content shows "No items available"

Also, if I try to use the API I get a message
```
ERROR! Error when publishing collection to default (https://galaxy.ansible.com/api/) (HTTP Code: 403, Message: The namespace listed on your filename must match one of the namespaces you have access to. Code: permission_denied)
```
The namespace is defined in galaxy.xml so maybe the message should refer to that rather than say "on your filename" which is a bit vague.

Seems to have happened before in https://github.com/ansible/galaxy/issues/1108 and https://github.com/ansible/galaxy/issues/1568 as result of the namespace already pre-existing.
The fix in both cases being deletion of the pre-existing namespace by @chouseknecht, so could you please take of it for me? There is only one old role in the pre-existing namespace so its fine to delete if that is the easiest fix.

**Comment by chouseknecht** [comment]
The namespace `matthewcosgrove` existed, but for some reason your account was not actually associated with it. Fixed on our side. Please try the upload again.

**Comment by matthewcosgrove** [comment]
Works now! Thanks @chouseknecht
