### ISSUE TITLE
Request for a new namespace: recordsansible

### ISSUE THREAD

**Issue by dmsimard** [ansible/galaxy#2440]
Hi :wave:

## Namespace Request
Namespace: recordsansible

##### Description
Ansible Galaxy namespace for ARA Records Ansible content

##### GitHub Org Link
https://github.com/ansible-community/ara-collection
(Note that https://github.com/recordsansible exists but there is nothing of interest there)

##### Admins
arecordsansible ( https://github.com/arecordsansible )

Thanks !

**Comment by chouseknecht** [comment]
Done

**Comment by dmsimard** [comment]
@chouseknecht pinged on IRC but no luck. I see that the namespace was created but it doesn't look like I have access to it. Is there something missing or am I doing something wrong ? Thanks !

**Comment by chouseknecht** [comment]
@dmsimard 

Added `arecordsansible` to the list of owners.

**Comment by dmsimard** [comment]
@chouseknecht looks good now, thanks ! Much appreciated.
