### ISSUE TITLE
Mediafellows namespace

### ISSUE THREAD

**Issue by stefanhorning** [ansible/galaxy#2442]
## Namespace Request
Namespace: mediafellows

##### Description
Please add the "mediafellows" namespace to Galaxy. So I have a seperate namespace for the Github org https://github.com/mediafellows/ and don't have to use my personal. (as we I was previously able todo with old org mediapeers)

Thank you!

##### GitHub Org Link
https://github.com/mediafellows/

##### Admins
stefanhorning

**Comment by chouseknecht** [comment]
Done
