### ISSUE TITLE
Delete collection dellemc.openmanage version 2.1.1

### ISSUE THREAD

**Issue by jagadeeshnv** [ansible/galaxy#2444]
We uploaded https://galaxy.ansible.com/dellemc/openmanage version 2.1.1 instead of 1.0.0. As we had to start with 1.0.0
**Could you please delete the specific upload?** We want to retain the collection name(openmanage) and start with a lower version number. **The other collections in this dellemc namespace is owned by other teams, which should not be modified in any aspect**. This issue is specifically for this collection "openmanage". Tagging @anil-degwekar and @rajeevarakkal for awareness.
@chouseknecht  @cutwater 
[openmanage](https://galaxy.ansible.com/dellemc/openmanage)

**Comment by cutwater** [comment]
@jagadeeshnv I deleted openmanage collection. Feel free to upload it again.

**Comment by jagadeeshnv** [comment]
**Thank you @cutwater for quickly resolving the issue.**
