### ISSUE TITLE
NetDevOpsX

### ISSUE THREAD

**Issue by generalovmaksim** [ansible/galaxy#2449]
## Namespace Request
Namespace: netdevopsx

##### Description

Collections produced by NetDevOpsX

##### GitHub Org Link

https://github.com/netdevopsx

##### Admins

generalovmaksim

**Comment by generalovmaksim** [comment]
Hi @gundalow 
Sorry for disturbing you, could you guide me regarding adding my collection which stored in the netdevopsx organisation (github.com) into galaxy ? I don't see netdevopsx in the namespace's list.

**Comment by generalovmaksim** [comment]
Hi @gundalow
Just friendly reminder :-)

**Comment by generalovmaksim** [comment]
Hi @gundalow
Just friendly reminder :-)

**Comment by chouseknecht** [comment]
Namespace created.
