### ISSUE TITLE
namespace: redhat_cop

### ISSUE THREAD

**Issue by sabre1041** [ansible/galaxy#2450]
## Namespace Request
Namespace: redhat_cop

##### Description

Ansible Galaxy namespace for the Red Hat Community of Practice

##### Admins
* sabre1041
* redhat-cop-galaxy
* oybed
* jlozadad

**Comment by chouseknecht** [comment]
Namespace `redhat_cop` already exists, and `sabre1041` is an owner. You can go to My Content, and click on Edit Properties to the right of the namespace, and add/remove any additional owners.
