### ISSUE TITLE
Update existing versions of macOS in platforms

### ISSUE THREAD

**Issue by roolo** [ansible/galaxy#2452]
### Use Case
Users could use current versions of macOS as supported platforms for a role.

### Implementation

- Existing versions: https://en.wikipedia.org/wiki/MacOS#Release_history
- Versions in Ansible Galaxy: https://galaxy.ansible.com/api/v1/platforms/?name=macOS

**Comment by alisonlhart** [comment]
All versions of supported macOS have been added to supported platforms.
