### ISSUE TITLE
Serverscom namespace for serverscom API modules

### ISSUE THREAD

**Issue by amarao** [ansible/galaxy#2453]
## Namespace Request
Namespace: serverscom

##### Description
Servers.com is a hosting provider with automated provision of dedicated and cloud servers. There is [a public API](https://developers.servers.com/) for managing servers, and there is [a collection](https://github.com/serverscom/serverscom-ansible/) for modules to work with servers.com API (under construction): 

##### GitHub Org Link
https://github.com/serverscom

##### Admins
https://galaxy.ansible.com/amarao (or is is george.shuklin? It's the same user).

**Comment by amarao** [comment]
Hello?

**Comment by gundalow** [comment]
Created.
Though for the record it's under your old GitHub name, which is `george.shuklin`
