### ISSUE TITLE
Galaxy Namespace for Famedly GmbH

### ISSUE THREAD

**Issue by jcgruenhage** [ansible/galaxy#2454]
## Namespace Request
Namespace: famedly

##### Description
Secure and decentralized communication for the healthcare sector

##### ~~GitHub Org Link~~
We use GitLab, not GitHub, but the content we'd like to publish is available at https://gitlab.com/famedly/ansible, and our website is available at famedly.com (German only for now).

##### Admins
- @jcgruenhage
- @ratzupaltuff

**Comment by gundalow** [comment]
@jcgruenhage @ratzupaltuff Created.
It's fine that you are using GitLab.
