### ISSUE TITLE
namespace: puzzle

### ISSUE THREAD

**Issue by puzzleitc** [ansible/galaxy#2455]
## Namespace Request
Namespace: puzzle

##### Description
Opensource Solutions for all kind of fields

##### GitHub Org Link
https://github.com/puzzle/

##### Admins

@n-ik
@id101010
@niwo
@friendlypenguin

**Comment by gundalow** [comment]
@puzzleitc Hi, looks like https://galaxy.ansible.com/puzzleitc already exists and hs `puzzleitc` as an owner

**Comment by anshulbehl** [comment]
@puzzleitc Do you need a namespace as `puzzle` or the current `puzzleitc` is fine?

**Comment by puzzleitc** [comment]
Hi,

Yes, we need the puzzle namespace as puzzle is the organization.

Thanks,
Nik

**Comment by thedoubl3j** [comment]
Hey @puzzleitc we were able to create the namespace but the only user present on galaxy was @friendlypenguin. The other users will need to navigate to galaxy and login there which connect galaxy to their github. @friendlypenguin can add them in as admins once that is done as they are an admin on the namespace but feel free to reopen once those users are logged in and we can add them in.
