### ISSUE TITLE
namespace: Galaxy and GH handle not in synch

### ISSUE THREAD

**Issue by ddimatos** [ansible/galaxy#2465]
@thedoubl3j  - I know its been a while; my college has been handling our uploads but would like to resolve this.

I think the issue is that I initially [signed up](https://galaxy.ansible.com/accounts/signup/) instead of using one of the supported third party accounts and it resulted in some confusion as i signed up with I think with `dimatos` while my github handle is `ddimatos` both connected to same email ( i prefer we continue with my github handle). When ever i log into Galaxy even though i choose the github handle it does not show me ownership to the `ibm` namespace. 

Signed up here:
<img width="327" alt="image" src="https://user-images.githubusercontent.com/25803172/90284629-170c6300-de27-11ea-9bb2-c6d1a1e37f43.png">

I choose:
<img width="973" alt="image" src="https://user-images.githubusercontent.com/25803172/90284709-3efbc680-de27-11ea-96d3-8d4a14a3b704.png">

It logs me in as:
<img width="455" alt="image" src="https://user-images.githubusercontent.com/25803172/90284794-6f436500-de27-11ea-9485-8e5aa79e0cbd.png">

Yet my GH handle is `ddimatos`
https://github.com/ddimatos

The original PR for my namespace has been closed you can follow it here: https://github.com/ansible/galaxy/issues/2236

**Comment by chouseknecht** [comment]
Deleted the `dimatos` and `ddimatos` users from Galaxy. The next time you log in using your GitHub username, it will create correctly in Galaxy, and then we can complete the association to the `ibm` namespace.

**Comment by ddimatos** [comment]
@chouseknecht Thanks Chris, 
I logged in , looks good as I can see `ddimatos` as the user. 
Do you need me to resubmit anything for the `ibm` namespace?

**Comment by chouseknecht** [comment]
Added `ddimatos` to the `ibm` namespace.

**Comment by ddimatos** [comment]
@chouseknecht Awesome , thanks for the speedy turn around!!!
