### ISSUE TITLE
Feature idea: tagging of ACD collections

### ISSUE THREAD

**Issue by resmo** [ansible/galaxy#2468]
## Feature Idea

I see an increase in questions from users "where do I find the source of module.."

To better route them to the corresponding collection, it would be helpful to have a special tag e.g. `acd` on galaxy.ansible.com to list all collections being part of ACD.

**Comment by pxeger** [comment]
I just finished a little app inspired by this issue: https://wtf-is-this-ansible-module.netlify.app/
