### ISSUE TITLE
pan-community namespace request

### ISSUE THREAD

**Issue by nembery** [ansible/galaxy#2469]
## Namespace Request
Namespace: pan_community

##### Description

This namespace contains collections and tools for PAN-OS created and maintained by the Community

##### GitHub Org Link

https://github.com/pan-community

##### Admins

nembery, scotchoaf, kevwal1

**Comment by anshulbehl** [comment]
The Name can only contain [A-Za-z0-9_]
Can you please suggest some other name? like `pan_community`?

**Comment by nembery** [comment]
`pan_community` would be fine. Thanks

**Comment by anshulbehl** [comment]
https://galaxy.ansible.com/pan_community

has been created
