### ISSUE TITLE
Galaxy Login failure (server error 500)

### ISSUE THREAD

**Issue by maximumG** [ansible/galaxy#2479]
Same issue as #2048
When I try to sign in, through GitHub, I am prompted to sign in or sign up. When trying to sign into my old account I get a Server Error (500) upon login

Looks like from previous issues my account needs to be deleted. It should be as follows:
username: maximumG
email: maxime.gerges@live.fr

STEPS TO REPRODUCE
Login using the login button on https://galaxy.ansible.com

EXPECTED RESULTS
Successful login and linking of my old account w/github

ACTUAL RESULTS
Server Error (500)

Many thanks.

**Comment by chouseknecht** [comment]
Done. User `maximumG` deleted. You should be able to log in using GitHub now.
