### ISSUE TITLE
problem with fortios_system_ntp module

### ISSUE THREAD

**Issue by Chkcmd** [ansible/galaxy#2481]
##### SUMMARY

When I try to apply the playbook to a new device , I get the error "Error in repo"

##### STEPS TO REPRODUCE

ansible 2.9.6
  config file = /home/deznak/PycharmProjects/Ansible/fortios/ansible.cfg
  configured module search path = ['/home/deznak/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]

set_ntp_global_playbook.yml

- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: no
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 80
  tasks:
  - name: Configure system NTP information.
    fortios_system_ntp:
      vdom:  "{{ vdom }}"
      system_ntp:
        ntpserver:
         -
            id: "0"
            server: "NTP1"
         -
            id: "1"
            server: "NTP2"
        ntpsync: "enable"
        type: "custom"

inventory/hosts
[fortigates]
some_ip_address

[fortigates:vars]
ansible_network_os=fortinet.fortios.fortios
ansible_user="my_username"
ansible_password="my_pass"

ansible command:

ansible-playbook forti_playbook/set_ntp_global.yml -i inventory/hosts --limit some_ip_address

##### EXPECTED RESULTS

fortigate_100d # show system ntp
    set ntpsync enable
    set type custom
    config ntpserver
        edit 1
            set server "NTP1"
        next
        edit 2 
            set server "NTP2"
        next
    end
end

##### ACTUAL RESULTS

I enabled debug on my fortigate 100d with the following commands:
diagnose debug enable
diagnose debug cli 8
When the playbook is turned on, the fortios_system_ntp module does the following until it receives an error:
fortigate_100d # config system ntp
0: set ntpsync enable
0: set type custom
-651: end

It seems to me there is an error in the logic of the fortios_system_ntp module.  Since the server ntp was not specified, but the module tries to complete the configuration with the "end" command, the fortigate does not apply the settings and returns error 651

IMPORTANT! This bug is relevant only for devices on which NTP servers have never been configured. If you configure the ntp server at least once, fortios will remember it and no error will occur.

```
PLAY [fortigates] 
[DEPRECATION WARNING]: Distribution Ubuntu 20.04 on host 10.159.131.194 should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered 
platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
fatal: [10.159.131.194]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "meta": {"build": 1064, "http_method": "PUT", "http_status": 424, "name": "ntp", "path": "system", "serial": "FG100D5D18802162", "status": "error", "vdom": "root", "version": "v5.4.1"}, "msg": "Error in repo"}

https://kb.fortinet.com/kb/documentLink.do?externalID=FD40266
https://kb.fortinet.com/kb/documentLink.do?externalID=FD46280


```

**Comment by newswangerd** [comment]
This is the repository for galaxy.ansible.com web service. https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues is probably the correct place for issues relating to the `fortinet.fortios` collection
