### ISSUE TITLE
Request Namespace cybus

### ISSUE THREAD

**Issue by mschm** [ansible/galaxy#2483]
## Namespace Request
Namespace: cybus

##### Description
Cybus Connectware Deployment

##### GitHub Org Link
https://github.com/orgs/cybusio

##### Admins
mschm
NotoriousBIT

**Comment by anshulbehl** [comment]
https://galaxy.ansible.com/cybus

has been created with the said admins.

I also want to touch base with you if you are interested in posting content Ansible Galaxy, please also take a look at Ansible Automation Platform and Partner Program at ansible.com/partners
Let us know if you are interested to know more about it.

Thanks,
