### ISSUE TITLE
need a namespace for codeaffen

### ISSUE THREAD

**Issue by cmeissner** [ansible/galaxy#2486]
## Namespace Request
Namespace: codeaffen

##### Description
My colleges and I want to contribute some modules and roles to ansible galaxy. We don't want to use our personal namespace. As I am the owner of `codeaffen` github organization I request the galaxy namespace too.

##### GitHub Org Link
https://github.com/codeaffen

##### Admins
cmeissner
FlatKey

**Comment by cmeissner** [comment]
@anshulbehl any news on this request? I saw that you grant a namespace for klusters org, which had later request a namespace. Any thing what we can do to speed up the process?

**Comment by thedoubl3j** [comment]
picking it up @cmeissner

**Comment by thedoubl3j** [comment]
done :)

**Comment by cmeissner** [comment]
Grazie mille!
