### ISSUE TITLE
dconf - uint64 value

### ISSUE THREAD

**Issue by RJGhugo** [ansible/galaxy#2489]
## Bug Report 

Module: dconf

##### SUMMARY

A value with uint64 does not work.

##### STEPS TO REPRODUCE

Working:

- name: Thumbnail Cache
  dconf:
    key: "/org/gnome/desktop/thumbnail-cache/maximum-age"
    value: "20"
    state: present

Not working:

- name: Thumnailerzeugungslimit
  dconf:
    key: "/org/gnome/nautilus/preferences/thumbnail-limit"
    value: "200"
    state: present

Working:

- name: Thumbnailerzeungslimit
  command: gsettings set org.gnome.nautilus.preferences thumbnail-limit 200

##### EXPECTED RESULTS

The value of thumbnail-limit should change to 200.
##### ACTUAL RESULTS

It throws an error.

```

```

**Comment by Akasurde** [comment]
Please file issue against https://github.com/ansible-collections/community.general.
