### ISSUE TITLE
 Namespace request: cloud

### ISSUE THREAD

**Issue by goneri** [ansible/galaxy#2491]
## Namespace Request
Namespace: cloud

##### Description

I would like to upload cloud.common, a dependecy of vmware.vmware_rest.

##### GitHub Org Link

https://github.com/ansible-collections/cloud.common/

##### Admins

- https://github.com/goneri
- https://github.com/jillr
- https://github.com/Akasurde

**Comment by anshulbehl** [comment]
This has been created
