### ISSUE TITLE
Namespace Request for Sendinblue (https://www.sendinblue.com/)

### ISSUE THREAD

**Issue by build-failure** [ansible/galaxy#2492]
## Namespace Request
Namespace:  sendinblue

##### Description
Sendinblue is a SaaS solution for relationship marketing.

##### GitHub Org Link
https://github.com/sendinblue

##### Admins
https://galaxy.ansible.com/sananguliyev
https://galaxy.ansible.com/build_failure

**Comment by thedoubl3j** [comment]
done :) however, @build-failure when  was the last time you logged into galaxy? I was unable to add you as admin but was able to find your user. normally see this when someone hasn't logged in. I was able to add as an admin though

**Comment by thedoubl3j** [comment]
@build-failure I was able to add you. your username is still `build-failure` but your namespace is `build_failure` due to namespaces not allowing `-` in the name. Closing, please reach out if you have any issues with the namespace

**Comment by build-failure** [comment]
@thedoubl3j , thank you very much for adding the namespace! I'm able to see it within my Ansible Galaxy account, unfortunately, I'm not able to see the https://github.com/sendinblue organization within the provider namespaces. Could you help me out? Thank you in advance!

**Comment by anshulbehl** [comment]
@build-failure  Provider Namespaces represents the list of namespaces or ogranizations you have access to in GitHub.
If you are not able to see sendinblue, that means you probably don't have access to that org on Github, please check

**Comment by build-failure** [comment]
@anshulbehl , sorry, I forgot to mention it. I have definitely access to the https://github.com/sendinblue organization as an owner. I've also tried to make my membership public, but no luck. Still I can't see it within the provider namespaces...

**Comment by build-failure** [comment]
@anshulbehl , it works now! Initially I've missed the guide on how to refresh the GitHub OAuth application authorization - https://galaxy.ansible.com/docs/contributing/importing.html.

**Comment by thedoubl3j** [comment]
@build-failure awesome! yes, that is new for some folks as login sessions can last a while but oauth stuff does need to get refreshed if we update that integration.
