### ISSUE TITLE
Ansible Galaxy Namespace for Klusters Org

### ISSUE THREAD

**Issue by anisf** [ansible/galaxy#2493]
## Namespace Request
Namespace: klusters

##### Description
Klusters Team

##### GitHub Org Link
https://github.com/klusters/ansible-collection-system

##### Admins
anisf <anis@fathallah.fr>

**Comment by anshulbehl** [comment]
https://galaxy.ansible.com/klusters

has been added with you as admin @anisf .

**Comment by anisf** [comment]
Thanks !
