### ISSUE TITLE
namespace: senzing

### ISSUE THREAD

**Issue by docktermj** [ansible/galaxy#2498]
## Namespace Request
Namespace: senzing

##### Description
Want to spend more energy on being creative rather than mundane tasks? We seek to democratize Entity Resolution. Join us!

##### GitHub Org Link
https://github.com/senzing

##### Admins
docktermj
brianmacy
jaeadams

**Comment by docktermj** [comment]
@anshulbehl , @JohnLieske , @thedoubl3j  Is there anything else I need to submit?

**Comment by thedoubl3j** [comment]
nothing else @docktermj it has been created :)
