### ISSUE TITLE
delete collection codeaffen.phpipam 0.0.1

### ISSUE THREAD

**Issue by cmeissner** [ansible/galaxy#2501]
We tried out the publishing pipeline here and uploaded version 0.0.1. Later we recognized that we can't delete accidentally uploaded collection versions by our self.

**Comment by cmeissner** [comment]
@thedoubl3j whom should i ping for that issue? It's two week ago that I created it.

**Comment by thedoubl3j** [comment]
@cmeissner sadly collections cannot be deleted unless a security issue was identified. then, the proper protocol should be followed via notification. collections by their nature can have other collections depending on them so deleting them is not taken lightly. Our recommendation is to either version bump the collection or deprecate it if needed.

**Comment by cmeissner** [comment]
Got it. Thanks for clarification.
