### ISSUE TITLE
Namespace Request: stationgroup

### ISSUE THREAD

**Issue by reelsense** [ansible/galaxy#2502]
## Namespace Request
Namespace: stationgroup

##### Description

https://stationgroup.301.zone
##### GitHub Org Link

https://github.com/stationgroup

##### Admins

reelsense
atlas-of-mercury

---
Will I be able to update the Description in my Ansible Galaxy account once this is created?

**Comment by thedoubl3j** [comment]
@reelsense done :)  https://galaxy.ansible.com/stationgroup
