### ISSUE TITLE
Requesting brightcomputing namespace to be assigned to BrightComputing org

### ISSUE THREAD

**Issue by FooBarQuaxx** [ansible/galaxy#2505]
## Namespace Request
Namespace: brightcomputing

##### Description
[Bright Computing](https://www.brightcomputing.com/) Ansible Namespace

##### GitHub Org Link
https://github.com/Bright-Computing

##### Admins
https://github.com//FooBarQuaxx
https://github.com/johnnydevaprasad
https://github.com/martijndv

Best Regards,

**Comment by anshulbehl** [comment]
https://galaxy.ansible.com/brightcomputing

has been created, @FooBarQuaxx I can only add you as an admin.
other users have to login to galaxy.ansible.com once through their github login

You can add them too now since you are an admin.

**Comment by FooBarQuaxx** [comment]
@anshulbehl Thanks for the quick response.
