### ISSUE TITLE
namespace: mgit_at

### ISSUE THREAD

**Issue by ohdearaugustin** [ansible/galaxy#2506]
## Namespace Request
Namespace: mgit_at

##### Description
We will need a new namespace as our organisation contains a "-" in its name.

##### GitHub Org Link
https://github.com/mgit-at

##### Admins
gebi
ohdearaugustin

**Comment by anshulbehl** [comment]
https://galaxy.ansible.com/mgit_at

Has been created

**Comment by ohdearaugustin** [comment]
Thank you.
