### ISSUE TITLE
Namespace for Organization "totaldebug"

### ISSUE THREAD

**Issue by marksie1988** [ansible/galaxy#2509]
## Namespace Request
Namespace:  totaldebug

##### Description

[projects.totaldebug.uk](projects.totaldebug.uk)
##### GitHub Org Link

[github.com/totaldebug](github.com/totaldebug)

##### Admins

- marksie1988

**Comment by anshulbehl** [comment]
https://galaxy.ansible.com/totaldebug

has been created
