### ISSUE TITLE
namespace: goneri

### ISSUE THREAD

**Issue by goneri** [ansible/galaxy#2511]
## Namespace Request
Namespace: goneri

##### Description

I would like to use the namespace for my personal collections.

##### GitHub Org Link
https://github.com/goneri/

##### Admins

goneri

**Comment by Thulium-Drake** [comment]
You already have that namespace :-) you can sign in on Galaxy with your Github account. Then check the 'My Content' menu on the left!

**Comment by goneri** [comment]
Oh, great :-)
