### ISSUE TITLE
namespace: escapace

### ISSUE THREAD

**Issue by l5x** [ansible/galaxy#2514]
## Namespace Request

Hello probably due to seats reshuffle on [escapace GH](https://github.com/escapace) and  username changes, I have lost access to `escapace` galaxy namespace and associated [roles](https://github.com/escapace/ansible-roles).

Currently, the `l5x` associated username on galaxy is stale and has two empty namespaces. Is it possible to (A) rename the user to match the github username, (B) remove the empty namespaces, and (C) restore access to `escapace` galaxy namespace?

Thank you so much!

**Comment by thedoubl3j** [comment]
hey @l5x I am not seeing a username for l5x but it is a namespace. I am seeing a user by the name of `epiloque` as an admin over the `l5x` namespace. 

We cannot rename users sadly. I can check on removing namespaces but they cannot be removed if their is content in them. I can grant admin access to escapace to a user.

**Comment by sinisterstumble** [comment]
---

**Comment by thedoubl3j** [comment]
done @l5x anything else I can do?

**Comment by l5x** [comment]
@thedoubl3j that is all, thank you very much!
