### ISSUE TITLE
Unable to access new Galaxy Namespace after GitHub user rename

### ISSUE THREAD

**Issue by maxhoesel** [ansible/galaxy#2519]
I recently changed the username of my GitHub account from 'AriosThePhoenix' to 'maxhoesel' and would like to use that new namespace in Ansible-Galaxy. While I can see the new namespace when i go into `My Content` -> `Edit Properties` on my existing namespace, attempting to add that namespace to my account results in the following error:

`Error! This provider namespace is already associated with a Galaxy namespace (maxhoesel)`

I quickly checked the namespace on the Galaxy website and it seems like it [does indeed exist already](https://galaxy.ansible.com/maxhoesel). I assume that the namespace somehow got created but not linked to my Galaxy account, perhaps due to the mismatch in name? (The Galaxy account still uses the old username).

If at all possible, I would like to have access to the new prefix on my Galaxy account.

Thanks in advance!

**Comment by chouseknecht** [comment]
In Galaxy, the username `maxhoesel` is now an owner of the namespace `AriosThePhoenix`. You should be able to move the provider namespace (i.e. the GitHub organization) to whichever namespace you like.

**Comment by maxhoesel** [comment]
Thanks for having a look at this. Unfortunately, it doesn't seem like this resolved my issue, unless I'm missing something. Trying to assign the `maxhoesel` namespace to my logged in account (which shows as `AriosThePhoenix` on Galaxy) still results in the same error message. [Here's a screenshot for reference](https://i.imgur.com/XsoeHjf.png)

Just to make sure that there's no misunderstanding, I'm trying to gain access to the galaxy namespace for my new GitHub username (`maxhoesel`) on my Galaxy account that is still linked to the old name (`AriosThePhoenix`), seemingly because it didn't get updated when I changed my GitHub username. There's no organization involved, the old GitHub username simply doesn't exist anymore.

**Comment by chouseknecht** [comment]
Deleted the `maxhoesel` provider namespace from Galaxy. You have access to `maxhoesel` and `ariosthephoenix` namespaces in Galaxy, so you should now be able to associate the GitHub namespace `maxhoesel` with either one.

**Comment by maxhoesel** [comment]
That seems to have worked - I can access the namespace now. Thanks for the help!
