### ISSUE TITLE
namespace: consensys

### ISSUE THREAD

**Issue by ConsensysOps** [ansible/galaxy#2520]
## Namespace Request
Namespace: consensys

##### Description

ConsenSys is the software engineering leader of the blockchain space. Our full-stack Ethereum products help developers build next-generation networks.

##### GitHub Org Link

https://github.com/orgs/Consensys/

##### Admins
- joshuafernandes
- devops-consensys

**Comment by anshulbehl** [comment]
https://galaxy.ansible.com/consensys

This has been created
