### ISSUE TITLE
SSO login failure

### ISSUE THREAD

**Issue by ConsensysOps** [ansible/galaxy#2521]
## Bug Report 
Unable to login to Galaxy via SSO using Github 

##### SUMMARY

When I try and login to Galaxy Im redirected to a page where I can sign in via google, twitter or github -however none work and I 
have to sign in via uname and password - I'd very much like to sign in via the Github SSO option 

##### STEPS TO REPRODUCE

When I try and login to Galaxy Im redirected to a page where I can sign in via google, twitter or github -however none work and I 
have to sign in via uname and password - I'd very much like to sign in via the Github SSO option 

Could my handle on galaxy also be updated to 'ConsensysOps' please?

##### EXPECTED RESULTS

Get to the dashboard of galaxy

##### ACTUAL RESULTS

I get an error saying SSO failure.

![image](https://user-images.githubusercontent.com/72234181/95821417-3400dc00-0d6d-11eb-86e9-84bcc0bce340.png)

```

```

**Comment by chouseknecht** [comment]
I deleted the `consensys-devops` account from Galaxy. Try logging in again from scratch. Let us know when you do by responding on this ticket. We’ll need to connect the new account to the existing namespaces in Galaxy.

**Comment by joshuafernandes** [comment]
Thank you @chouseknecht , atm I get a 504 error when I attempt to login using the github creds

```Error 504 Ray ID: 60152ecf8f82da52 • 2020-12-14 04:29:46 UTC```

**Comment by joshuafernandes** [comment]
Scratch that @chouseknecht , seems to work perfectly fine now to login via SSO using github creds :+1:  Thank you for sorting this out!
