### ISSUE TITLE
Namespace Request: cloudflight

### ISSUE THREAD

**Issue by theSuess** [ansible/galaxy#2522]
## Namespace Request
Namespace: `cloudflight`

##### Description
Ansible Roles by Cloudflight

##### GitHub Org Link
https://github.com/cloudflightio/

##### Admins
* `theSuess` (@theSuess)
* `Exordian` (@Exordian)

**Comment by anshulbehl** [comment]
https://galaxy.ansible.com/cloudflight

This has been created
