### ISSUE TITLE
Namespace Request for GitHub Organisation

### ISSUE THREAD

**Issue by jpylypiw** [ansible/galaxy#2523]
## Namespace Request
Namespace: **softbauware**

##### Description
SOFTBAUWARE GmbH

##### GitHub Org Link
https://github.com/softbauware

##### Admins
@jpylypiw

**Comment by anshulbehl** [comment]
https://galaxy.ansible.com/softbauware

This has been created

**Comment by jpylypiw** [comment]
@anshulbehl Thank you very much 👍
