### ISSUE TITLE
Request to add Namespace

### ISSUE THREAD

**Issue by monitorapp-dev** [ansible/galaxy#2526]
## Namespace Request
Namespace: monitorapp.monitorapp_waf

##### Description
Monitorapp WAF Ansible collection

##### GitHub Org Link
We have no Github organization yet

##### Admins
tech_qa (tech_qa@monitorapp.com)

**Comment by anshulbehl** [comment]
tech_qa (tech_qa@monitorapp.com)

The above user has not signed up on Galaxy yet, please signup using your Github login and provide us the username accordingly

**Comment by monitorapp-dev** [comment]
Could you check name by monitorapp-dev? (I`m confused with Red hat account)
Also, i changed Namespace monitorapp_dev.monitorapp_waf to monitorapp.monitorapp_waf

Please check again
Sorry for my mistake.

**Comment by anshulbehl** [comment]
https://galaxy.ansible.com/monitorapp

has now been created
