### ISSUE TITLE
Namespace request for community performancecopilot collection

### ISSUE THREAD

**Issue by natoscott** [ansible/galaxy#2528]
## Namespace Request
Namespace: community.performancecopilot

##### Description
Performance Co-Pilot Ansible collection

##### GitHub Org Link
https://github.com/performancecopilot/

##### Admins
natoscott
andreasgerstmayr
portante

**Comment by thedoubl3j** [comment]
@natoscott do you want this collection to be a part of the community collection? or do you want to have your own namespace to ship this collection from?

**Comment by natoscott** [comment]
@thedoubl3j part of the community collection please.

**Comment by natoscott** [comment]
Er, well - perhaps I should check that further - 'community namespace' I think that should be?  We have a performancecopilot namespace from when we started out with just a single role (performancecopilot.pcp) - but that's grown into several roles (and now we wish to move to using a collection) ... my understanding is this would be suited to the 'community' namespace as its a community collection.  See the https://github.com/performancecopilot/ansible-pcp repo for details.

**Comment by thedoubl3j** [comment]
@natoscott we cannot grant access access to the community namespace from here. you would need to work with @gundalow to get that stuff worked out. Since you have active admins and have active development, I would think that it probably best for that to remain in your own namespace. What is the end goal for this collection? Are you trying to get into the ansible community release package? The community namespace is rather reserved for content that is managed/maintained by the community team.

**Comment by natoscott** [comment]
@thedoubl3j hmm, OK.  My intent is just to do 'the right thing' and land this content in the most appropriate namespace.  We work with Grafana, Zabbix and similar technologies - I found these projects are using the community namespace and it felt like the right fit for the performancecopilot collection too.

**Comment by natoscott** [comment]
@gundalow any thoughts?  Would the performancecopilot collection be suited to the 'community' namespace?  (what are the rules / guidelines for that?)  Thanks!

**Comment by gundalow** [comment]
Hi,
Since you have https://galaxy.ansible.com/performancecopilot I think it's fine to use that existing namespace.

**Comment by natoscott** [comment]
@gundalow OK, I'll explore that further I guess.  Since logically the collection name is 'performancecopilot', I'd been looking for a namespace that would gave us something other than 'performancecopilot.performancecopilot' ... seems a bit of an eyesore.  But I'll think of something - thanks for the input, all.
