### ISSUE TITLE
namespace: insight-stratum

### ISSUE THREAD

**Issue by robcxyz** [ansible/galaxy#2529]
## Namespace Request
Namespace: insight-stratum

##### Description

[Insight Data Science's](https://insightfellows.com/) contributions to the Stratum V2 upgrade for mining pools. 

##### GitHub Org Link

https://github.com/insight-stratum

##### Admins

- robcyxz
- shinyfoil
- pranavt61

**Comment by thedoubl3j** [comment]
hey @robcxyz namespaces cannot contain a `-`, would you be fine with this containing a `_` instead?

**Comment by robcxyz** [comment]
@thedoubl3j - Forgot about that. Yes that is fine.  `insight_stratum`.

Thank you so much!

**Comment by thedoubl3j** [comment]
hey @robcxyz I was able to create the namespace but was unable to add you as an admin, the other 2 were added but I couldn't find your username. Have you logged into galaxy and connected your accounts? (login and then we will auth through GH for you) Or do you possibly have a legacy account?

**Comment by robcxyz** [comment]
Hi @thedoubl3j - sorry for late response. 

I have other namespaces already registered so the only reason I think I can't be added is because I changed my Github username about 3 months ago.  Could that have anything to do with this?  

For this one namespace, it is not a major issue but for future namespaces I'd be interested if you think this the cause of the issues. 

Thanks again for your help.

**Comment by robcxyz** [comment]
@thedoubl3j - This had issues and we just changed the org name so going to close this out for [#2566](https://github.com/ansible/galaxy/issues/2566)
