### ISSUE TITLE
Ansible Galaxy API is down?

### ISSUE THREAD

**Issue by Yajo** [ansible/galaxy#2532]
##### SUMMARY

![imagen](https://user-images.githubusercontent.com/973709/97546233-7280d280-19cc-11eb-8228-2ec1c92f676f.png)

When installing from CLI it says: 

    when attempting to call Galaxy at 'https://galaxy.ansible.com/api/': The read operation timed out

##### STEPS TO REPRODUCE

Visit https://galaxy.ansible.com/

##### EXPECTED RESULTS

Works

##### ACTUAL RESULTS

Doesn't work.

It seems I'm not the only one: https://twitter.com/MartinJuul/status/1321731913934143488

**Comment by cr-zlilaharon** [comment]
We are getting the same thing, both from AWX and the website.
Worked yesterday, did not make any change.

**Comment by aternowy** [comment]
same

**Comment by shmileee** [comment]
+1, can't fetch roles.
`==> vagrant: [WARNING]: - geerlingguy.java was NOT installed successfully: Error when
==> vagrant: finding available api versions from default (https://galaxy.ansible.com) (HTTP
==> vagrant: Code: 503, Message: Service Unavailable)`

**Comment by alanriemer** [comment]
Same error here!
**[WARNING]: - ansistrano.deploy was NOT installed successfully: Failed to get
data from the API server (https://galaxy.ansible.com/api/): HTTP Error 503:
Service Unavailable**

**Comment by kenchrcum** [comment]
works again

**Comment by eexit** [comment]
It's back up!

![sumo dance](https://user-images.githubusercontent.com/57098/97553194-72390500-19d5-11eb-9b3a-b447a0628bfa.gif)

**Comment by cutwater** [comment]
Hello, we had an incident that caused an outage during the upgrade work. It has been resolved and Galaxy API is now up and running.

Apologies for the inconvenience.

**Comment by aternowy** [comment]
> Hello, we had an incident that caused an outage during the upgrade work. It has been resolved and Galaxy API is now up and running.
> 
> Apologies for the inconvenience.

Do you have some kind of https://www.githubstatus.com/ for galaxy on your plan?
