### ISSUE TITLE
Search page - Add Fork Count

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#254]
We currently track the repository fork count, but we don't surface it in the UI. Let's add it to the following pages:

- [x] On the search page, add it to the list of counts (i.e., downloads, stars, watchers)
- [ ] On the content detail page, add a Fork button that shows the count. When clicked, it will take the user to the GitHub repository page, where they can actually fork it.

**Comment by chouseknecht** [comment]
We're 50% done. w00t!

**Comment by chouseknecht** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Fork count to search page](https://trello.com/c/mlQcafiZ/3-add-fork-count-to-search-page)

**Comment by newswangerd** [comment]
Closing this because the content detail page already has a fork count and a link to github.
