### ISSUE TITLE
please add namespace ibm_zos_sysauto to the ibm namespace

### ISSUE THREAD

**Issue by LUEDDEA** [ansible/galaxy#2545]
## Namespace Request
Namespace: ibm/ibm_zos_sysauto

##### Description
Ansible collection providing samples and roles to facilitate uniting your Ansible automation with automated operations on z/OS using IBM Z System Automation.

##### GitHub Org Link
https://github.com/ansible-collections/ibm_zos_sysauto

##### Admins
lueddea
ulrich_hild

**Comment by thedoubl3j** [comment]
done @LUEDDEA however, username: ulrich_hild was not found in galaxy. Have them log into galaxy again and then they should be good. As an admin now you can add them whenever they get correct access.
