### ISSUE TITLE
Content cannot be uploaded from Github on new namespace

### ISSUE THREAD

**Issue by ConsensysOps** [ansible/galaxy#2547]
Cannot upload content to namespace `consensys` in devops-consensys account.

##### SUMMARY
Our devops-consensys account has two namespaces `consensys` and `devops_consensys`. Namespace `consensys` does not have the ability to upload content from the Github.

##### STEPS TO REPRODUCE
1. Log-in to Galaxy as user devops-consensys
2. Click on `My Content` on left hand menu
3. Select namespace `consensys` 
4. Click `add content`
5. Option `Import Role from Github` is disabled

##### EXPECTED RESULTS
Should be able to import roles on the namespace consensys

##### ACTUAL RESULTS
Unable to upload roles from Github as option is disabled

![galaxy-content-upload](https://user-images.githubusercontent.com/72234181/99328084-17edde80-28c7-11eb-8eef-0ed58e5dfe95.png)

```

```

**Comment by pegasys-admin** [comment]
Still import roles from Github is not active for the namespace consensys. How can this get resolved? Appreciate any help on this.

**Comment by ConsensysOps** [comment]
Hi @chouseknecht, @cutwater, @alikins, @newswangerd, @awcrosby, @tima, @gregdek, saw your names in the about section and assuming you are maintainers, apologies if this isn't the case, and would really appreciate any insights on how to progress this please

![image](https://user-images.githubusercontent.com/72234181/101843482-0500be00-3b96-11eb-9b42-c29563328ff7.png)

**Comment by ConsensysOps** [comment]
Noticed that request GET https://galaxy.ansible.com/api/v1/providers/sources/ receives 500 error when try to edit properties of the namespaces. Hope this information helps.

<img width="613" alt="galaxy-namespace-edit-error" src="https://user-images.githubusercontent.com/72234181/101845700-0b456900-3b9b-11eb-88c9-2cdde8a2c009.png">

**Comment by chouseknecht** [comment]
To add roles from GitHub to the `consensys` namespace in Galaxy, you will need to do the following:

1. Log into Galaxy using one of the following GitHub accounts: devops-consensys, joshuafernandes, cdivitotawela
2. Go to My Content
3. Click on the Edit Properties menu. NOTE: There’s a little kabob menu icon to the right of the `Add Content` button. Click on that to see the menu, where `Edit Properties` is one of the options.
4. Near the bottom of the Edit Properties page you will see a `Provider Namespaces` section. Here you will need to add the GitHub namespace or organization containing the public repositories that need to be “imported” into Galaxy. The GitHub user that is logged into Galaxy must be an owner or member of the GitHub namespace containing the public repositories to be imported into Galaxy. 

Hope this helps.

**Comment by ConsensysOps** [comment]
Hello @chouseknecht 
Thank you for that. Appreciate you looking into this! I've tried doing that but the consensys namespace isn't listed there and we get a 500 response back (see screenshot) - I think there is something wrong with the auth/integration with Github. We are not able to login via SSO either and have to manually provide credentials when signing in. I'd opened up #2521 to request if that could be looked at as well, but we've not heard back.

![image](https://user-images.githubusercontent.com/72234181/102027392-6f606b00-3def-11eb-968a-1614f53764f9.png)

Appreciate your help in this.

Have a great day
Cheers

**Comment by joshuafernandes** [comment]
Hi @chouseknecht 

Thank you for sorting #2521, if you could add the `consensys` namespace to this account, we'd be really grateful !

Appreciate you looking into this

Cheers
Josh

**Comment by chouseknecht** [comment]
The `ConsensysOps` user is now associated with the `consensysops`, `consensys`, and `consensys_devops` namespaces in Galaxy. 

From here, if you’re attempting to import Roles from GitHub, you’ll need to associate the GitHub org containing the Role repositories with the appropriate Galaxy namespace, as described in my comment above.

Note: you can only associate a given GitHub organization with a single Galaxy namespace.

**Comment by ConsensysOps** [comment]
Excellent. Thanks a lot fixing this. We can publish Consensys ansible roles on Consensys namespace. Thanks again actively working on this and getting fixed.
