### ISSUE TITLE
Add Ubuntu 20.10 "Groovy Gorilla" as a platform

### ISSUE THREAD

**Issue by albers** [ansible/galaxy#2548]
### Use Case
Ansible Galaxy does not yet support the current Ubuntu release 20.10 "Groovy Gorilla" ([release notes](https://discourse.ubuntu.com/t/groovy-gorilla-release-notes/15533)):
```bash
$ curl -s "https://galaxy.ansible.com/api/v1/platforms/?name=Ubuntu&release=groovy" | jq
{
  "count": 0,
  "next": null,
  "next_link": null,
  "previous": null,
  "previous_link": null,
  "results": []
}
```

### Proposed Solution
Please add Ubuntu "groovy" as a supported Platform.

ping @chouseknecht

**Comment by chouseknecht** [comment]
Done. Platform Ubuntu Groovy added. You can view it here: https://galaxy.ansible.com/api/v1/platforms/?release=groovy
