### ISSUE TITLE
Request for fedora namespace

### ISSUE THREAD

**Issue by richm** [ansible/galaxy#2549]
## Namespace Request
Namespace: fedora

##### Description
For hosting collections related to Fedora

##### GitHub Org Link
Hmm - well there isn't a specific github org for `fedora` . . . the first sub-organization that will be publishing content under the `fedora` namespace will be the linux system roles team - https://github.com/linux-system-roles - others will follow

##### Admins
richm
pcahyna
nhosoi

**Comment by richm** [comment]
@nhosoi @pcahyna

**Comment by abenokraitis** [comment]
Looks good, spoke with the team offline. ACKed.

**Comment by thedoubl3j** [comment]
@abenokraitis sounds good, thanks. working on it now

**Comment by thedoubl3j** [comment]
done @richm :)

**Comment by richm** [comment]
https://galaxy.ansible.com/fedora/linux_system_roles
