### ISSUE TITLE
Cannot login to ansible.galaxy with my GH account

### ISSUE THREAD

**Issue by v1v** [ansible/galaxy#2553]
##### SUMMARY

For some reason when I login with my GH account to the ansible galaxy the user is not `v1v` but `aninfinite` (that's my twitter account).

I tried to reset the password but even though the only way to access to ansible galaxy is with GitHub authentications, so it did not work at all.

##### EXPECTED RESULTS

To login to https://galaxy.ansible.com/v1v

##### ACTUAL RESULTS

Login as https://galaxy.ansible.com/aninfinite

Email account: VictorMartinezRubio@gmail.com

**Comment by v1v** [comment]
Is there anything missing? :pray:

**Comment by v1v** [comment]
@chouseknecht, @cutwater, @alikins, @newswangerd, @awcrosby, @tima, @gregdek  since I saw your names in the `about` section, so I assumed you might be the team helping with ansible-galaxy:

![image](https://user-images.githubusercontent.com/2871786/100443976-96563780-30a2-11eb-9840-fb0ff6d4c70c.png)

I wonder if you could help me with since I've no clue how I can enable my `v1v` account (that's the account I used it in 2014 to upload my unique ansible role back in the days)

My apologies if I should not use this approach, I could not find any references how to proceed

Thanks

**Comment by chouseknecht** [comment]
@v1v Deleted the old account, `aninfinite`. You should now be able to login via GitHub as v1v. Let me know, after you log in for the first time, if you still cannot access the `v1v` namespace.

**Comment by v1v** [comment]
Thanks @chouseknecht , I see now `v1v` but i cannot access the `v1v` namespace:

![image](https://user-images.githubusercontent.com/2871786/101685773-1051cd80-3a60-11eb-935a-8c7749b8ca1c.png)

I tried to import one new role but i got 404, so maybe related to the above mentioned v1v namespace issue, in any case see the below traces:

```bash
$ ansible-galaxy role import --token <TOKEN>  -v --role-name v1v.jenkins_plugin_cli v1v ansible-role-jenkins_plugin_cli
No config file found; using defaults
ERROR! None (HTTP Code: 403, Message: Forbidden)
```

**Comment by chouseknecht** [comment]
@v1v Connected your username to the `v1v` namespace. You should be able to import things now.

**Comment by v1v** [comment]
Thanks! It works now like a charm, so I managed to upload my new role. Thanks again. 
I'll close this issue now then.
