### ISSUE TITLE
NetFoundry Collection

### ISSUE THREAD

**Issue by qrkourier** [ansible/galaxy#2555]
## Namespace Request
Namespace: netfoundry

##### Description
Use your NetFoundry Network with Ansible

##### GitHub Org Link
https://github.com/netfoundry

**Comment by qrkourier** [comment]
Further admins:
* gormami
* emoscardini

**Comment by anshulbehl** [comment]
Created

**Comment by qrkourier** [comment]
Thank you. I have changed galaxy.yml for my collection to use the new namespace, but I encounter a "permission denied" because it seems my API token does not have access to "netfoundry". Are additional steps on my side necessary that are not detailed in [the doc](https://galaxy.ansible.com/docs/contributing/namespaces.html#requesting-additional-namespaces)?

**Comment by qrkourier** [comment]
```bash
❯ ansible-galaxy collection publish --token $GALAXY_API_KEY netfoundry-platform-*.tar.gz
Publishing collection artifact '/home/kbingham/Sites/netfoundry/github/developer-tools/ansible_collections/netfoundry-platform-1.2.0.tar.gz' to default https://galaxy.ansible.com/api/
ERROR! Error when publishing collection to default (https://galaxy.ansible.com/api/) (HTTP Code: 403, Message: The namespace listed on your filename must match one of the namespaces you have access to. Code: permission_denied)
```

```bash
❯ yq r ./netfoundry/platform/galaxy.yml namespace
netfoundry

❯ yq r ./netfoundry/platform/galaxy.yml name
platform
```

**Comment by thedoubl3j** [comment]
@qrkourier You didn't request admin privileges on the namespace so it will reject you. I will add you now

**Comment by thedoubl3j** [comment]
@qrkourier should be good to go. should show up under my content tab as well
