### ISSUE TITLE
Create a namespace for my github organization

### ISSUE THREAD

**Issue by nicobo** [ansible/galaxy#2556]
Hello

Maybe I'm missing something but I cannot create/add a role to a galaxy namespace named after my GitHub organization. Could you please create it ?

##### Namespace Request
Namespace: nicolabs

##### Description
nico**labs** [sea~ dev# & fun!]

##### GitHub Org Link
https://github.com/nicolabs

##### Admins
nicobo

**Comment by thedoubl3j** [comment]
done :)
