### ISSUE TITLE
Mikamai Namespace request

### ISSUE THREAD

**Issue by MatteoJoliveau** [ansible/galaxy#2558]
## Namespace Request
Namespace: mikamai

##### Description
MIKAMAI is a leading Cloud consultancy and development agency

##### GitHub Org Link
https://github.com/mikamai

##### Admins
matteojoliveau
nicolaracco
aletheia
oeN
mapteo

**Comment by anshulbehl** [comment]
https://galaxy.ansible.com/mikamai

has been created with required admins, you can add more admins now after logging in to Ansible Galaxy

**Comment by MatteoJoliveau** [comment]
Thank you @anshulbehl !
