### ISSUE TITLE
firehawkvfx

### ISSUE THREAD

**Issue by queglay** [ansible/galaxy#2562]
## Namespace Request
Namespace: firehawkvfx

##### Description
Firehawk VFX produces open source Infrastructure As Code for VFX Artists

##### GitHub Org Link
https://github.com/firehawkvfx

##### Admins
queglay@gmail.com

**Comment by queglay** [comment]
A while ago I thought I had created this namespace for the org, but I hadn't published any collections yet.  I'm not sure if it was erased or if in fact it was never created.  Hopefully its still ok though as the org has been authenticated.

**Comment by queglay** [comment]
I'm also not clear on what was happening in the UI here, because firehawkvfx does show up under provider namespaces form the github org, but uploading a tar states it doesn't exist.

https://imgur.com/iZiKCj1

**Comment by anshulbehl** [comment]
https://galaxy.ansible.com/firehawkvfx

has been created. It was not there before, please check now
