### ISSUE TITLE
rdiffbackup

### ISSUE THREAD

**Issue by ericzolf** [ansible/galaxy#2563]
## Namespace Request
rdiffbackup

##### Description
Automation of rdiff-backup, a cross-platform reverse differential backup, local or remote over SSH.

##### GitHub Org Link
https://github.com/rdiff-backup/

##### Admins
ericzolf
rdiff-backup-admin

**Comment by anshulbehl** [comment]
https://galaxy.ansible.com/rdiffbackup

has been created.
