### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by ppadial** [ansible/galaxy#2564]
Hello,

Could you please delete the account for ppadial completely with all corresponding files?

Thanks in advance.

**Comment by ppadial** [comment]
@chouseknecht 

Could you please help me ? i saw you was helping with similar issues here: https://github.com/ansible/galaxy/issues/319

Thank you very much in advance,

**Comment by chouseknecht** [comment]
Account `ppadial` has been deleted.

**Comment by ppadial** [comment]
Hi @chouseknecht the link in galaxy stills existing, should it be deleted too ?https://galaxy.ansible.com/ppadial
