### ISSUE TITLE
namespace: insight_nervos

### ISSUE THREAD

**Issue by shinyfoil** [ansible/galaxy#2566]
## Namespace Request
Namespace: insight_nervos 

**This request is a follow-up to [#2529](https://github.com/ansible/galaxy/issues/2529) which can be closed/deleted as there were issues with that request.  Please replace with this new namespace.** 

##### Description

[Insight Data Science's](https://insightfellows.com/) contributions to the Stratum V2 upgrade for mining pools.

##### GitHub Org Link

[https://github.com/insight-nervos](https://github.com/insight-nervos)

##### Admins

https://github.com/shinyfoil

**Comment by thedoubl3j** [comment]
@shinyfoil done :)
