### ISSUE TITLE
namespace: exoscale

### ISSUE THREAD

**Issue by resmo** [ansible/galaxy#2569]
## Namespace Request
Namespace: exoscale

##### Description

European Cloud Hosting

##### GitHub Org Link

https://github.com/exoscale

##### Admins

@llambiel
@resmo

Additional information: we are going to consolidate ngine_io.exoscale with this namespace with ACD 3.0.0.

**Comment by thedoubl3j** [comment]
done @resmo however, I was unable to add @llambiel as an admin as I could not find the user. Has the user logged into galaxy yet or possibly have a legacy account? Either way, you can add them as admins now :). If you have any issues or want to learn about the Ansible partner program, feel free to reach out.

**Comment by resmo** [comment]
@thedoubl3j thx, yes, this was the case, but no problem, adding him by myself.
