### ISSUE TITLE
New Namespace: Onepassword

### ISSUE THREAD

**Issue by verkaufer** [ansible/galaxy#2570]
## Namespace Request
Namespace: onepassword

##### Description

The easiest way to use and store secrets.

##### GitHub Org Link

https://github.com/1password

##### Admins

- [verkaufer](https://galaxy.ansible.com/verkaufer) (@verkaufer)

**Comment by thedoubl3j** [comment]
done @verkaufer :) if you have any issues or would like to get involved in the Ansible partner program, please feel free to reach out.
