### ISSUE TITLE
namespace: please add djungle-io

### ISSUE THREAD

**Issue by xrmx** [ansible/galaxy#2571]
## Namespace Request
Namespace: djungle-io

##### Description
djungle.io tech team

##### GitHub Org Link
https://github.com/djungle-io

##### Admins
elmisi and xrmx

Thanks!

**Comment by anshulbehl** [comment]
@xrmx The namespace cannot contain hypen(-), and has to follow the python package naming convention.
Let me know what name suits you after that context

**Comment by xrmx** [comment]
djungle_io would be fine. Thanks!

**Comment by anshulbehl** [comment]
https://galaxy.ansible.com/djungle_io has been created
