### ISSUE TITLE
Requesting a galaxy namespace for "redhattelco"

### ISSUE THREAD

**Issue by termlen0** [ansible/galaxy#2575]
## Namespace Request
Namespace: redhattelco

##### Description

Ansible collections for Telco and IT operators
##### GitHub Org Link

https://github.com/RedHatTelco
##### Admins

termlen0: https://galaxy.ansible.com/termlen0
willtome: https://galaxy.ansible.com/willtome

**Comment by termlen0** [comment]
CC: @willtome

**Comment by chouseknecht** [comment]
Done
