### ISSUE TITLE
Requesting a galaxy namespace for "smartgic"

### ISSUE THREAD

**Issue by goldyfruit** [ansible/galaxy#2576]
## Namespace Request
Namespace: smartgic

##### Description
Ansible collections for MagicMirror, Raspberry Pi and Mycroft AI

##### GitHub Org Link
https://github.com/smartgic

##### Admins
https://galaxy.ansible.com/goldyfruit

**Comment by chouseknecht** [comment]
Done

**Comment by goldyfruit** [comment]
There is a typo on the namespace, I requested `smartgic` but `smartmagic` has been created.
Do I need to open a new issue?

**Comment by anshulbehl** [comment]
Done now.

**Comment by goldyfruit** [comment]
> Done now.

All good :+1:  Thanks
