### ISSUE TITLE
Request a new namespace for DeltaBG

### ISSUE THREAD

**Issue by mlg1** [ansible/galaxy#2579]
## Namespace Request
Namespace: deltabg

##### Description
Ansible collections and roles from Delta.BG

##### GitHub Org Link
https://github.com/DeltaBG

##### Admins
https://galaxy.ansible.com/vdzhorov
https://galaxy.ansible.com/mlg1

**Comment by thedoubl3j** [comment]
done @mlg1 :) let us know if you have any problems with the namespace
