### ISSUE TITLE
Hello Could you please tell me, which yml file i need to call in 1st ? 

### ISSUE THREAD

**Issue by namithcc** [ansible/galaxy#2580]
I am trying to test it on my machines, via azure devops

could you please tell me, which main.yml file i will call 1st , example [ansible-playbook playbook yml]
which will call the entire code. similarly i didnt see ant yml file with a role 

playbook.yml

---

- name: CIS
  hosts: rhelvm
  become: yes
  ignore_errors: True

  roles:
    - RHEL7-CIS-Benchmarks

**Comment by Akasurde** [comment]
Hi @namithcc !

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
