### ISSUE TITLE
Invalid collection name 'git+https', name must be in the format <namespace>.<collection>.

### ISSUE THREAD

**Issue by petermetz** [ansible/galaxy#2586]
##### SUMMARY

Tried to install the latest edge for the kubernetes collection, directly from git as per the documentation [1], but failed.

[1]: https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#installing-a-collection-from-a-git-repository

##### STEPS TO REPRODUCE

```sh
$ ansible-galaxy collection install git+https://github.com/ansible-collections/community.kubernetes.git main
Process install dependency map
ERROR! Invalid collection name 'git+https', name must be in the format <namespace>.<collection>. 
Please make sure namespace and collection name contains characters from [a-zA-Z0-9_] only.

```

```sh
ansible-galaxy collection install community.kubernetes git+https://github.com/ansible-collections/community.kubernetes.git main
Process install dependency map
ERROR! Invalid collection name 'git+https', name must be in the format <namespace>.<collection>. 
Please make sure namespace and collection name contains characters from [a-zA-Z0-9_] only.
```

##### EXPECTED RESULTS

The collection is installed from git.

##### ACTUAL RESULTS

```sh
$ ansible-galaxy collection install git+https://github.com/ansible-collections/community.kubernetes.git main
Process install dependency map
ERROR! Invalid collection name 'git+https', name must be in the format <namespace>.<collection>. 
Please make sure namespace and collection name contains characters from [a-zA-Z0-9_] only.

```

**Comment by TrueXakeP** [comment]
Which version of Ansible are you using? This functionality was introduced in 2.10. You can update it via pip3. You referencing the latest docs which are for 2.10.

**Comment by s-hertel** [comment]
This should be filed in https://github.com/ansible/ansible if it doesn't work with 2.10+ since this isn't maintained here. It looks like your syntax is wrong for the version - use a comma instead of a space before `main`.

**Comment by petermetz** [comment]
> Which version of Ansible are you using?

@TrueXakeP  Oops. `2.9.6` Thanks for clarifying!

> It looks like your syntax is wrong for the version - use a comma instead of a space before main.

@s-hertel Another ooops, could've sworn I did it exactly how the documentation said so (copy paste) but apparently not. Apologies for the both of you, closing this now. Thank you for the help!
