### ISSUE TITLE
namespace: hifis

### ISSUE THREAD

**Issue by tobiashuste** [ansible/galaxy#2589]
## Namespace Request
Namespace: hifis

##### Description
Helmholtz Federated IT Services (HIFIS)

##### GitHub Org Link
https://github.com/hifis-net

##### Admins
@Normo
@christianhueserhzdr
@tobiashuste

Thanks a lot :)

**Comment by thedoubl3j** [comment]
done @tobiashuste if you all encounter any issues please let us know :)
