### ISSUE TITLE
Rename namespace

### ISSUE THREAD

**Issue by aurelienmaury** [ansible/galaxy#2590]
## Namespace Request
Existing Namespace: WeScale
New Namespace name: wescale

Could you please rename this namespace, created long before ansible collections and their name format constraints. I already renamed Github organization to reflect the lowercasing of the name. (https://github.com/wescale) ?

Regards.

**Comment by thedoubl3j** [comment]
done :) this was successful due to there being no content in your namespace, otherwise, the dependency chain would have caused some issues.
