### ISSUE TITLE
Namespace: netcloud

### ISSUE THREAD

**Issue by richardstrnad** [ansible/galaxy#2591]
## Namespace Request
Namespace: netcloud

##### Description
Swiss based integrator for clouds, managed services and IT solutions.

##### GitHub Org Link
https://github.com/netcloud

##### Admins
@richardstrnad
@rknaus

**Comment by richardstrnad** [comment]
Added @rknaus to the admin list

**Comment by thedoubl3j** [comment]
done @richardstrnad :) both you and @rknaus were added as admins

**Comment by richardstrnad** [comment]
@thedoubl3j Thanks!
