### ISSUE TITLE
namespace: citrix add admin user

### ISSUE THREAD

**Issue by giorgos-nikolopoulos** [ansible/galaxy#2593]
Hello.

I had requested the citrix namespace with my account among the admins.

See #2208

I tried to upload a collection to the citrix namespace and I get a permission denied error
``` HTTP Code: 403, Message: The namespace listed on your filename must match one of the namespaces you have access to. Code: permission_denied```

could you make the account `giorgos_nikolopoulos` admin of the `citrix` namespace so I can upload collections there?

Thank you.

**Comment by thedoubl3j** [comment]
hey @giorgos-nikolopoulos the user name `giorgos_nikolopoulos` was not found but it is a namespace. I added the user `giorgos-nikolopoulos` which I assume is you as it matches your GH username. Let me know here if it does not work

**Comment by giorgos-nikolopoulos** [comment]
@thedoubl3j 
Thanks that worked.
I was able to upload a collection to the citrix namespace.
