### ISSUE TITLE
Request a Namespace: sudoinclabs

### ISSUE THREAD

**Issue by hameedullah** [ansible/galaxy#2596]
## Namespace Request
Namespace: sudoinclabs

##### Description
SUDO - Elevate your DevOps

##### GitHub Org Link
https://github.com/sudoinclabs
Docker Hub: https://hub.docker.com/orgs/sudoinclabs/

##### Admins
hameedullah - https://galaxy.ansible.com/hameedullah

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/sudoinclabs
