### ISSUE TITLE
Request a new namespace for amnews

### ISSUE THREAD

**Issue by TheRojam** [ansible/galaxy#2598]
## Namespace Request
Namespace: amnews

##### GitHub Org Link
https://github.com/amNews

##### Admins
@therojam

**Comment by JohnLieske** [comment]
A description is required in order to create the namespace. The description may be short.

**Comment by TheRojam** [comment]
> 
> ## Namespace Request
> 
> Namespace: amnews
> ##### Description
amnews is namespace of a freelancing german
> ##### GitHub Org Link
> 
> https://github.com/amNews
> ##### Admins
> 
> @TheRojam

**Comment by JohnLieske** [comment]
Namespace has been created:

https://galaxy.ansible.com/amnews
