### ISSUE TITLE
Create "backupscale" namespace

### ISSUE THREAD

**Issue by colans** [ansible/galaxy#2601]
## Namespace Request
Namespace: `backupscale`

##### Description

Ansible assets for the BackUpScale service

##### GitHub Org Link

* https://github.com/consensus-enterprises/
* https://gitlab.com/consensus.enterprises

##### Admins

Same as for the "consensus" namespace:

- ergonlogic
- lamech
- sensespidey
- colans

**Comment by JohnLieske** [comment]
Namespace created:

https://galaxy.ansible.com/backupscale
