### ISSUE TITLE
Namespace Request: cub_oit_pe

### ISSUE THREAD

**Issue by willhaines** [ansible/galaxy#2602]
## Namespace Request
Namespace: cub_oit_pe

##### Description
Platform Engineering team within OIT at the University of Colorado Boulder

##### GitHub Org Link
https://github.com/CUB-OIT-PE

##### Admins
- [willhaines](https://github.com/willhaines)
- [erinn](https://github.com/erinn)

**Comment by JohnLieske** [comment]
Namespace created:

https://galaxy.ansible.com/cub_oit_pe
