### ISSUE TITLE
Request namespace abims_sbr

### ISSUE THREAD

**Issue by loraine-gueguen** [ansible/galaxy#2605]
## Namespace Request
Namespace: abims_sbr

##### Description

ABiMS - Station Biologique de Roscoff - France - CNRS/SU

##### GitHub Org Link

https://github.com/abims-sbr

##### Admins

https://galaxy.ansible.com/lecorguille
https://galaxy.ansible.com/loraine_gueguen

Thanks!

Loraine Guéguen

**Comment by thedoubl3j** [comment]
@loraine-gueguen `loraine_gueguen` is a namespace but I was able to find your username. Both users have been added as admins, let us know if you have any issues with the namespace! cheers, https://galaxy.ansible.com/abims_sbr
