### ISSUE TITLE
Issue importing new role to galaxy

### ISSUE THREAD

**Issue by marksie1988** [ansible/galaxy#2609]
##### SUMMARY

when trying to import an ansible role i receive this error: 

```
Error! Save repository failed: (Ensure this field has no more than 255 characters.)
```
there is no indication of what is causing this error.

##### STEPS TO REPRODUCE

1. go to my content
2. Add content
3. Import role from github
4. select role (totaldebug/ansible-role-hassio)
5. click OK and error appears

##### EXPECTED RESULTS

Repository is imported into ansible galaxy for consumption

##### ACTUAL RESULTS

Error was observed nothing else happens: 

```
Error! Save repository failed: (Ensure this field has no more than 255 characters.)
```

```

```

**Comment by marksie1988** [comment]
I have run it via a github action and this was successful so closing

**Comment by simeononsecurity** [comment]
This issue unfortunately is still persisting. I will try the github action. It's unfortunate however
