### ISSUE TITLE
Request namespace: senhasegura

### ISSUE THREAD

**Issue by lfraga** [ansible/galaxy#2610]
## Namespace Request
Namespace: senhasegura

##### Description
senhasegura, recognized as the best PAM solution by customers, through the Customers' Choice 2021 of Gartner Peer Insights

##### GitHub Org Link
https://github.com/senhasegura

##### Admins
lfraga

**Comment by JohnLieske** [comment]
Namespace created.
https://galaxy.ansible.com/senhasegura
