### ISSUE TITLE
Namespace Request: swisstxt

### ISSUE THREAD

**Issue by joschi36** [ansible/galaxy#2614]
## Namespace Request
Namespace: swisstxt

##### Description
SWISS TXT AG is based in Biel/Bienne and a daughter company of SRG SSR (Swiss Public Broadcasting Corporation).

##### GitHub Org Link
https://github.com/swisstxt

##### Admins
- @joschi36

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/swisstxt

Added you as admin to the namespace.
