### ISSUE TITLE
namespace: FIXME

### ISSUE THREAD

**Issue by just-paja** [ansible/galaxy#2616]
## Namespace Request
Namespace: lazyninjas

##### Description

Well documented ansible roles for extremely lazy people

##### GitHub Org Link

https://github.com/lazyninjas

##### Admins
https://galaxy.ansible.com/just-paja

**Comment by JohnLieske** [comment]
Namespace created. Added @just-paja as admin.
https://galaxy.ansible.com/lazyninjas
