### ISSUE TITLE
namespace: geometrylabs

### ISSUE THREAD

**Issue by robcxyz** [ansible/galaxy#2619]
## Namespace Request
Namespace: geometrylabs

##### Description

Geometry Labs playbooks for blockchain applications.

##### GitHub Org Link

https://github.com/geometry-labs

##### Admins

@robc-io
@shinyfoil

**Comment by JohnLieske** [comment]
Added namespace: https://galaxy.ansible.com/geometrylabs

Users @robc-io and @shinyfoil added as admin
