### ISSUE TITLE
gepaplexx namespace

### ISSUE THREAD

**Issue by ckaserer** [ansible/galaxy#2620]
## Namespace Request
Namespace: gepaplexx

##### Description
gepaplexx

##### GitHub Org Link
https://github.com/gepaplexx

##### Admins
* ckaserer
* rwrabel

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/gepaplexx

I was able to add user ckaserer but the user rwrabel does not show up in Galaxy. Please have the user log in (using GH sso) to galaxy.ansible.com to be able to add them. As the namespace has an active administrator you should be able to complete the task at your pace. Please let us know if there are any problems.
