### ISSUE TITLE
Namespace request: Equinix

### ISSUE THREAD

**Issue by detiber** [ansible/galaxy#2621]
## Namespace Request
Namespace: Equinix

##### Description
We are looking to migrate the existing packet modules from the community collection to reflect our new branding as Equinix Metal. To enable this, we are requesting a new namespace named Equinix.

##### GitHub Org Link
https://github.com/equinix

##### Admins
https://galaxy.ansible.com/detiber

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/equinix

User detiber added as admin
