### ISSUE TITLE
bloxberg namspace

### ISSUE THREAD

**Issue by iosifpeterfi** [ansible/galaxy#2624]
## Namespace Request
Namespace: bloxberg

##### Description
The Trusted Research Infrastructure

##### GitHub Org Link
https://github.com/bloxberg-org

##### Admins
iosifpeterfi
crossoveranx

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/bloxberg

Admins added: 
iosifpeterfi
crossoveranx
