### ISSUE TITLE
namespace: networktocode

### ISSUE THREAD

**Issue by FragmentedPacket** [ansible/galaxy#2627]
## Namespace Request
Namespace: networktocode

##### Description

House Ansible Collections under `networktocode` namespace.

There is already a "Provider Namespace" under jedelman8 for `networktocode`, but apparently there is a difference between a normal namespace and a "Provider Namespace".

We would like the `networktocode` namespace to be under jedelma8 if at all possible.

Tagging @jedelman8 since he owns the **Network to Code** Github organization just in case additional approval needs to happen.

##### GitHub Org Link

https://github.com/networktocode

##### Admins

There are already admins setup under the "Provider Namespace" that should be admins of the `networktocode` namespace.
- itdependsnetwork
- dgarros
- jmcgill298
- FragmentedPacket
- jvanderaa
- jedelman8

![Screen Shot 2021-02-25 at 11 09 31 AM](https://user-images.githubusercontent.com/29315002/109197221-f61fb580-7759-11eb-887f-bd82f656b8ce.png)

This is under the **jedelman8** namespace.

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/networktocode

Admins added: itdependsnetwork, dgarros, jmcgill298, FragmentedPacket, jvanderaa, jedelman8

More on managing namespaces & adding content to your namespace may be found here:
https://galaxy.ansible.com/docs/contributing/namespaces.html
https://galaxy.ansible.com/docs/contributing/importing.html
