### ISSUE TITLE
Namespace Request

### ISSUE THREAD

**Issue by kds-rune** [ansible/galaxy#2629]
## Namespace Request
Namespace: kred

##### Description
Kreditorforeningens Driftssentral DA

##### GitHub Org Link
https://github.com/Kreditorforeningens-Driftssentral-DA

##### Admins
kds-rune (rune.ronneseth@kred.no)

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/kred

Added kds-rune as an admin
