### ISSUE TITLE
Namespace request: almalinux

### ISSUE THREAD

**Issue by ezamriy** [ansible/galaxy#2630]
## Namespace Request
Namespace: almalinux

##### Description
AlmaLinux OS deployment and testing automation.

##### GitHub Org Link
https://github.com/AlmaLinux/

##### Admins
* ezamriy
* dmalyavkina
* mrybas

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/almalinux

Admins added:
ezamriy
dmalyavkina
mrybas
