### ISSUE TITLE
namespace: fortinet

### ISSUE THREAD

**Issue by chillancezen** [ansible/galaxy#2633]
## Namespace Request
Namespace: 
fortinet
##### Description

https://galaxy.ansible.com/fortinet
##### GitHub Org Link

https://github.com/fortinet
https://github.com/fortinet-ansible-dev
##### Admins

@JieX19

**Comment by chillancezen** [comment]
hi Admin,

could you please help review the namespace request ?

thanks

**Comment by JohnLieske** [comment]
@chillancezen  This namespace already exists
