### ISSUE TITLE
Requesting the "stonesoupkitchen" namespace

### ISSUE THREAD

**Issue by Overflow0xFFFF** [ansible/galaxy#2636]
## Namespace Request
Namespace: stonesoupkitchen

##### Description
Open source software for like-minded people.

##### GitHub Org Link
https://github.com/StoneSoupKitchen

##### Admins
* Overflow0xFFFF (that's me!)

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/stonesoupkitchen

Admin added: Overflow0xFFFF
