### ISSUE TITLE
Please add more users with ownership rights to conoa namespace

### ISSUE THREAD

**Issue by faridjoubbi** [ansible/galaxy#2639]
## Namespace Request
Namespace: conoa

There is a namespace named conoa already, which you kindly created.
We would like to add more users with ownership rights to this namespace.
(It would be nice to be able to manage users ourselves, but I can't find such a feature/setting on the page.)

##### Admins

faridjoubbi - is already there
AndreasDavour
danielsigwid
kalbinsson
rjes
spixx

**Comment by JohnLieske** [comment]
Added the following:
AndreasDavour
danielsigwid
kalbinsson
rjes
spixx

You should ber able to manage the admins by editing the properties of your namespace. The easiest way to do this is to go to My Content & searching for your namespace. When you are an admin you should see the option next to the "Add Content" button in the form of a three-dot dropdown menu.

![Screenshot from 2021-03-09 10-12-07](https://user-images.githubusercontent.com/9461032/110492322-120f4980-80c0-11eb-8663-129c08c9a073.png)

Once in the properties menu you would add / remove users from the "Namespace Owners" section.
