### ISSUE TITLE
Requesting maykinmedia namespace

### ISSUE THREAD

**Issue by sergei-maertens** [ansible/galaxy#2641]
## Namespace Request
Namespace: `maykinmedia`

##### Description
Awesome webdevelopment - https://maykinmedia.nl

##### GitHub Org Link
https://github.com/maykinmedia/

##### Admins
- joeribekker
- sergei_maertens

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/maykinmedia

Admins added:
* joeribekker
* sergei_maertens
