### ISSUE TITLE
Request "h3c" namespace for  my company,  H3C

### ISSUE THREAD

**Issue by gooduone** [ansible/galaxy#2646]
## Namespace Request
Namespace: h3c

##### Description

H3C is an industry leader in the provision of Digital Solutions, and is committed to becoming the most trusted partner of its customers

##### GitHub Org Link

https://github.com/h3c

##### Admins

gooduone

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/h3c

Admin added: gooduone
