### ISSUE TITLE
Requestig namespace for fgci-org

### ISSUE THREAD

**Issue by VilleS1** [ansible/galaxy#2647]
## Namespace Request
Namespace: fgci-org

##### Description

Finnish grid and cloud infrastructure

##### GitHub Org Link

https://github.com/fgci-org

##### Admins

VilleS1

**Comment by JohnLieske** [comment]
Hello @VilleS1 per [docs](https://galaxy.ansible.com/docs/contributing/namespaces.html#requesting-additional-namespaces): `Namespace names in Galaxy are limited to lowercase word characters (i.e., a-z, 0-9) and ‘_’, must have a minimum length of 2 characters, and cannot start with an ‘_’. No other characters are allowed, including ‘.’, ‘-‘, and space.`

**Comment by VilleS1** [comment]
Maybe just fgci then. If it is called fgci-org in github does it work when the name here is fgci?

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/fgci

Admin added:
* VilleS1
