### ISSUE TITLE
Let's Package Ansible Roles and Collections into OCI image format 🚀

### ISSUE THREAD

**Issue by abdennour** [ansible/galaxy#2650]
### Use Case
Any new technology comes with its build and package system. 
**App Code Artifacts** are able to be unified into one package format which is container image (OCI image).
However, **infra code artifacts** still have different formats:
 - Ansible --> git repo or tgz file
 - Terraform -> git repo or ... 
 - ... so on

### Proposed Solution

I propose to unify the package format of Ansible roles/Collections into OCI image, so it can be pushed to Container Registry as like App artifacts

```sh
# create OCI image
ansible-galaxy role package ./my-role
ansible-galaxy collection package ./my-collection

# package to OCI image than push it to
ansible-galaxy push /my-role  myregistry.example.com/ansible/my-role:v.123
# so on...
```

# Solution Advantages: 

- Unified Artifact Package format.
- Ability to add Entrypoint to the container image: So not only packaging the collection, but also when it run , it execute a job.
- Reduce the learning curve of people by documenting how spin off container (giving env vars) from this OCI image, instead going deep dive into what's inside the collection/role (vars,.. )

### Alternatives
Inspire it from  https://helm.sh/docs/topics/registries/

### Implementation
Inspire it from  https://helm.sh/docs/topics/registries/

**Comment by thedoubl3j** [comment]
open this on ansible/ansible @abdennour if you wish to start the conversation, this repo is for galaxy.ansible.com code and relative funcationality, the CLI tool is packaged with ansible itself.

**Comment by abdennour** [comment]
Thank you @thedoubl3j  ! i did https://github.com/ansible/ansible/issues/74327
