### ISSUE TITLE
Requesting microsoft namespace

### ISSUE THREAD

**Issue by richm** [ansible/galaxy#2651]
## Namespace Request
Namespace: microsoft

##### Description
We are working on a Microsoft SQL Server collection which we would like to make available as `microsoft.sql.mssql` - source is here - https://github.com/linux-system-roles/mssql/

##### GitHub Org Link
https://github.com/linux-system-roles/mssql/

##### Admins
richm nhosoi pcahyna

**Comment by richm** [comment]
Please also add amvin87 as an admin

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/microsoft

Admins added:
* richm
* nhosoi
* pcahyna
* amvin87
