### ISSUE TITLE
Request namespace anexia

### ISSUE THREAD

**Issue by anxstj** [ansible/galaxy#2653]
## Namespace Request
Namespace: anexia

##### Description

I would like to reserve the namespace 'anexia' for Anexia, an Austrian IT infrastructure company.

##### GitHub Org Link
https://github.com/orgs/anexia-it/

##### Admins

speijnik (https://github.com/speijnik; Stephan Speijnik-Steinwender)
anxstj (https://github.com/anxstj/; Stefan Jakobs)

**Comment by JohnLieske** [comment]
namespace created: https://galaxy.ansible.com/anexia

Admins added:
* speijnik
* anxstj
