### ISSUE TITLE
macOS Big Sur 11.x has been available for a year now...

### ISSUE THREAD

**Issue by jorhett** [ansible/galaxy#2656]
### Use Case

Support for macOS Big Sur in a galaxy module.

### Proposed Solution

```
       {
            "name": "macOSBigSur",  # or OSXI or whatever
            "release": "11",
            "active": true
        },
```

### Alternatives

No alternatives possible.

### Implementation

shown above

**Comment by thedoubl3j** [comment]
@jorhett I am not sure I understand what you are requesting, galaxy currently has no modules. are you referring to the command line utility? bigsur is a supported OS for ansible and I can confirm it's functionality.

**Comment by jorhett** [comment]
> @jorhett I am not sure I understand what you are requesting, galaxy currently has no modules. are you referring to the command line utility? bigsur is a supported OS for ansible and I can confirm it's functionality.

and yet one cannot say that their module supports Big Sur because it's not in the list. It's impossible to add a module to galaxy that does support it.

**Comment by thedoubl3j** [comment]
@jorhett I am assuming that you are referring to the list of platforms? The way your worded your question made me think you were referring to `ansible-galaxy` having `modules` that supoorted big sur. 

If you are referring to the supported platforms list, we can add it as an option. 

will comment and close when it does

**Comment by thedoubl3j** [comment]
`macOS-Big-Sur` added to platform list.
