### ISSUE TITLE
Namespace request for lmco (Lockheed Martin)

### ISSUE THREAD

**Issue by dokuhebi** [ansible/galaxy#2657]
## Namespace Request
Namespace: lmco

##### Description
Ansible content created by the Lockheed Martin Corporation

##### GitHub Org Link
https://github.com/lmco

##### Admins
dokuhebi

**Comment by dokuhebi** [comment]
The members of our github profile are private by default.  I can temporarily make my profile public for the purpose of verification if required.

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/lmco

Admin added: 
dokuhebi

There is no need to make any profile public. As long as the admin users are available to link in Galaxy (having used the GH SSO to log in), then the namespace can be created.

Thanks for your patience.
