### ISSUE TITLE
delete account

### ISSUE THREAD

**Issue by j0hnL** [ansible/galaxy#2660]
##### SUMMARY
I am unable to login to ansible galaxy I believe due to an account already created with my email address.  I have already filed ticket #2618.  What do I need to do to connect my github account and login to Galaxy?

```

```

**Comment by thedoubl3j** [comment]
@chouseknecht when you have time ^^

**Comment by chouseknecht** [comment]
@j0hnL 

Found a 'jlockman3' account, and deleted. Try logging in again from scratch. Thanks!

**Comment by j0hnL** [comment]
That did it, thanks!
