### ISSUE TITLE
namespace: ciscosmb

### ISSUE THREAD

**Issue by qaxi** [ansible/galaxy#2664]
## Namespace Request
Namespace: ciscosmb

##### Description

Cisco Small Bussiness devices - lines SG300, SG500, SG350, SG550, CBS350

##### GitHub Org Link

https://github.com/qaxi/ansible-ciscosmb

##### Admins

https://galaxy.ansible.com/qaxi   - qaxi - Petr Klíma

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/ciscosmb

Admin added: @qaxi

**Comment by qaxi** [comment]
Hmm, it is some misudestanding ...

I hoped to be able be in Ansible community collections ... https://github.com/ansible-collections for example https://github.com/ansible-collections/community.ciscosmb

**Comment by JohnLieske** [comment]
@qaxi this is not the method to get items into the community repos. The Ansible Community Guide has the information you need to contribute to the community repo:

https://docs.ansible.com/ansible/latest/community/index.html

**Comment by abenokraitis** [comment]
probably better to just contribute to `community.network`

**Comment by gundalow** [comment]
Hi,
I can create https://github.com/ansible-collections/community.ciscosmb for you.

Is there anyone else that will be helping maintain this collection?

**Comment by gundalow** [comment]
1) @qaxi https://github.com/ansible-collections/community.ciscosmb has been created and you have `maintainer` powers please accept invite via https://github.com/ansible-collections/community.ciscosmb/invitations

2) Is aim to move (including history) https://github.com/qaxi/ansible-ciscosmb to this new repo?

3) If so it will be `ansible-galaxy collection install community.ciscosmb`

4) Is there anyone else that we could add as a maintainer?

**Comment by gundalow** [comment]
Or what we could do is move your existing repo (which would keep issue and PR history)

**Comment by qaxi** [comment]
Thank you,
and for first sorry for misunderstanding ...

>    @qaxi https://github.com/ansible-collections/community.ciscosmb has been created and you have maintainer powers please accept invite via https://github.com/ansible-collections/community.ciscosmb/invitations
Thank you

>    Is aim to move (including history) https://github.com/qaxi/ansible-ciscosmb to this new repo?
Yes it is, with a little refactoring - galaxy.yml, changelog ....

>    If so it will be ansible-galaxy collection install community.ciscosmb
OK, thank you

>    Is there anyone else that we could add as a maintainer?
currently no.

Moving current reppo wtih is history is preffered.

**Comment by gundalow** [comment]
Of you can give me admin on your existing repo then I can move it to ansible-collections

**Comment by qaxi** [comment]
Invitation sent https://github.com/qaxi/ansible-ciscosmb/invitations

**Comment by gundalow** [comment]
I've deleted ansible-collections/community.ciscosmb

at the bottom of https://github.com/qaxi/ansible-ciscosmb/settings there is a `transfer` button, can you see if you can transfer to `ansible-collections`?


If that doesn't work please give me admin on your existing repo and I'll do the transfer

**Comment by qaxi** [comment]
I transfered the repository to **you**, `transfer` to `ansible-collections` did not work ...

**Comment by gundalow** [comment]
Perfect, GitHub transfers can be a bit particular about permissions.

Can confirm that https://github.com/qaxi/ansible-ciscosmb/issues/18 correctly gets redirected to https://github.com/ansible-collections/community.ciscosmb/issues/18

note the repo has been renamed to `community.ciscosmb`

Closing this, and tracking remaining tasks via https://github.com/ansible-collections/community.ciscosmb/issues/25

**Comment by qaxi** [comment]
Hello,
repostiory https://github.com/qaxi/ansible-ciscosmb is correctly redirecting to https://github.com/ansible-collections/community.ciscosmb

Starting to work on collection transformation.

Thank you for your help.
