### ISSUE TITLE
Request to add ntih / NamingThingsIsHard namespace

### ISSUE THREAD

**Issue by LoveIsGrief** [ansible/galaxy#2666]
## Namespace Request

Namespace: ntih

##### Description

NamingThingsIsHard

##### GitHub Org Link

It isn't a GitHub Org but a Gitlab one https://gitlab.com/NamingThingsIsHard

##### Admins

I'm the only Galaxy user: https://galaxy.ansible.com/loveisgrief

Updates to the collection will be pushed by the CI.

**Comment by JohnLieske** [comment]
Created namespace: https://galaxy.ansible.com/ntih

Added admin:
* @LoveIsGrief 

So you know ahead of time: Galaxy has no API connections to GitLab like it does with GitHub.

**Comment by LoveIsGrief** [comment]
Thanks @JohnLieske .
