### ISSUE TITLE
New Namespace for Ohio SuperComputer Center (OSC)

### ISSUE THREAD

**Issue by johrstrom** [ansible/galaxy#2669]
## Namespace Request
Namespace: osc

##### Description
A namespace for the Ohio SuperComputer Center  https://www.osc.edu/

##### GitHub Org Link
https://github.com/osc/

##### Admins

johrstrom
osc-bot

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/osc

Admins added: 
* johrstrom
* osc-bot
