### ISSUE TITLE
Unable to add organisation Github in Provider Namespace

### ISSUE THREAD

**Issue by safalkhanal** [ansible/galaxy#2670]
I requested a namespace (https://github.com/ansible/galaxy/issues/2544) with my organization's GitHub account, but I am unable to see the organization in the Provider Namespace list. I am, therefore, unable to add roles from the organization Github repo. If there has been a mistake on my part, please suggest me the right steps. 

https://galaxy.ansible.com/respiro

**Comment by mtlynch** [comment]
I'm seeing the same thing. I'm the owner of the [tiny-pilot Github org](https://github.com/tiny-pilot):

![image](https://user-images.githubusercontent.com/7783288/119860343-3838ce80-bee4-11eb-9a75-34e477062874.png)

When I try to add it as a namespace, it doesn't appear in the list:

![image](https://user-images.githubusercontent.com/7783288/119860479-5dc5d800-bee4-11eb-852c-16109ea5c85a.png)

I've tried searching for the org name explicitly, and it still doesn't come up:

![image](https://user-images.githubusercontent.com/7783288/119860602-7df59700-bee4-11eb-981a-ce746438d380.png)

I'm not sure if the namespace has to match the Github org. In my case, I own the Github org `tiny-pilot` (with a dash), but I [have the Ansible Galaxy namespace](https://github.com/ansible/galaxy/issues/2708) `tinypilot` (no dash).

**Comment by thedoubl3j** [comment]
@safalkhanal @mtlynch this might be a symptom from your user account settings. if I recall how we slurp stuff from the API, there is a setting somewhere that hides your organization association to the API, which is how we populate the provider's list.

**Comment by thedoubl3j** [comment]
did some digging, that looks like the problem, at least for you @mtlynch though I am not sure what...setting needs to change on Github (source: https://api.github.com/users/mtlynch/orgs) and same for you @safalkhanal https://api.github.com/users/safalkhanal/orgs

**Comment by chouseknecht** [comment]
@mtlynch Fixed the tinypilot namespace.

**Comment by thedoubl3j** [comment]
looks like whatever magic @chouseknecht can see and work, he fixed it!

**Comment by mtlynch** [comment]
Thanks, @chouseknecht @thedoubl3j!
