### ISSUE TITLE
New namespace 'univention' for Univention GmbH

### ISSUE THREAD

**Issue by dominikkaminski** [ansible/galaxy#2671]
## Namespace Request
Namespace: univention

##### Description
This namespace should be used for Roles and Modules around Univention and its Corporate Server (UCS)

##### GitHub Org Link
https://github.com/univention

##### Admins
- dominikkaminski

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/univention

Admin added: 
* dominikkaminski
