### ISSUE TITLE
New namespace for ElektraInitiative

### ISSUE THREAD

**Issue by kodebach** [ansible/galaxy#2672]
## Namespace Request
Namespace: `elektra_initiative`

##### Description
Elektra serves as a universal and secure framework to access configuration parameters in a global, hierarchical key database.

##### GitHub Org Link
https://github.com/ElektraInitiative

##### Admins
kodebach

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/elektra_initiative

Admin Added:
* kodebach
