### ISSUE TITLE
namespace: em

### ISSUE THREAD

**Issue by ewuramaminka** [ansible/galaxy#2673]
## Namespace Request
Namespace: piandt

##### Description
em namespace contain custom ansible roles

##### GitHub Org Link
https://github.com/piandt

##### Admins
ewuramaminka

**Comment by ewuramaminka** [comment]
ERROR! Error when publishing collection to default (https://galaxy.ansible.com/api/) (HTTP Code: 400, Message: Namespace "em" does not exist. Code: invalid)

**Comment by JohnLieske** [comment]
Your error message is because it has not yet been created.

Your namespace cannot be two characters long. Please choose a namespace name that is three or more characters.

**Comment by JohnLieske** [comment]
Thanks for your patience.

Namespace created:
https://galaxy.ansible.com/piandt

Admin added:
* @ewuramaminka
