### ISSUE TITLE
C2 Games Namespace

### ISSUE THREAD

**Issue by Rudedog9d** [ansible/galaxy#2675]
## Namespace Request
Namespace: c2games

##### Description
C2Games is a team of college faculty members, cybersecurity professionals, and recent graduates creating a new kind of cybersecurity competition.

##### GitHub Org Link

https://gitlab.com/c2-games

##### Admins

@Burrch3s
@rudedog9d

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/c2games

Admins added:
* @Burrch3s
* @Rudedog9d
