### ISSUE TITLE
new namespace: uberspace

### ISSUE THREAD

**Issue by luto** [ansible/galaxy#2676]
## Namespace Request
Namespace: uberspace

##### Description
Roles developed and maintained by uberspace.de for general usage.

##### GitHub Org Link
https://github.com/uberspace

##### Admins
- luto

Thank you!

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/uberspace

Admin added:
* @luto

**Comment by luto** [comment]
thank you!
