### ISSUE TITLE
namespace: napalm

### ISSUE THREAD

**Issue by ktbyers** [ansible/galaxy#2681]
## Namespace Request
Namespace: napalm

##### Description
I am one of the core maintainers of the NAPALM project and would like to get the napalm namespace assigned to my Galaxy account (ktbyers)

##### GitHub Org Link
https://github.com/napalm-automation/napalm

##### Admins
ktbyers   (Kirk Byers)

**Comment by JohnLieske** [comment]
Namespace created: 
https://galaxy.ansible.com/napalm

Admin added:
* @ktbyers

**Comment by ktbyers** [comment]
Great thanks @JohnLieske
