### ISSUE TITLE
Please add zosmf-Mira to the ibm namespacenamespace

### ISSUE THREAD

**Issue by zosmf-Mira** [ansible/galaxy#2687]
## Namespace Request
Namespace: ibm

##### GitHub Org Link
https://github.com/IBM

##### Admins

zosmf-Mira

**Comment by zosmf-Mira** [comment]
Another question, up to now, can ansible galaxy deprecate role or module of a collection. 
Eg, for [ibm_zos_zosmf](https://galaxy.ansible.com/ibm/ibm_zos_zosmf) collection, I want to deprecate 4 roles, zmf_workflow_complete, zmf_cpm_manage_software_instance, zmf_cpm_provision_software_service, zmf_cpm_remove_software_instance. And 1 module, zmf_workflow.

**Comment by thedoubl3j** [comment]
@zosmf-Mira deprecation can only take place at the package level in regards to outwardly facing materials (aka displayed on galaxy etc). For deprecating specific content inside a collection, specifically roles, I would document this in the changelog in readme with the timeline of the deprecation and then adhere to that. This way you have a publicly documented plan on when the content will exit. As for deprecating the module, see `plugin_routing` here: https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html#meta-directory for more info on how to deprecate modules. 

As for the addition of you as an admin, as their are already admins on the namespace, this will need to be routed through one of the existing admins. cc @ddimatos

**Comment by ddimatos** [comment]
@thedoubl3j - I can handle it from here, I will coordinate with the IBM z/OSMF team if other admins need to be given access to the namespace. Thank you @thedoubl3j .
