### ISSUE TITLE
Namespace Request for https://www.ebbba.org/

### ISSUE THREAD

**Issue by BrutalBirdie** [ansible/galaxy#2689]
## Namespace Request
Namespace: ebbba

##### Description
The EBBBA n. e. V. - European Big Blue Button Association n.e.V.

##### GitHub Org Link
https://github.com/ebbba-org

##### Admins
https://galaxy.ansible.com/brutalbirdie

**Comment by thedoubl3j** [comment]
done @BrutalBirdie
