### ISSUE TITLE
New namespace elkarbackup

### ISSUE THREAD

**Issue by elacunza** [ansible/galaxy#2690]
## Namespace Request
Namespace: elkarbackup

##### Description
This is a backup solution with a management REST API. We have developed an ansible collection and will like to publish it on galaxy.

##### GitHub Org Link
github.com/elkarbackup

##### Admins
elacunza

**Comment by JohnLieske** [comment]
Namespace added:
https://galaxy.ansible.com/elkarbackup

Admin Added:
* elacunza

**Comment by elacunza** [comment]
Thanks @JohnLieske
