### ISSUE TITLE
Name Space Request

### ISSUE THREAD

**Issue by niall-byrne** [ansible/galaxy#2696]
## Namespace Request
Namespace: osx_provisioner

##### Description
Roles for the OSX machine provisioner project.

##### GitHub Org Link
https://github.com/osx-provisioner

##### Admins
niall-byrne

**Comment by JohnLieske** [comment]
Looks like you did nothing wrong, I was searching with incorrect params! Thanks for the tip!

Namespace created:
https://galaxy.ansible.com/osx_provisioner

Admin added:
* niall_byrne
