### ISSUE TITLE
model-driven-devops namespace

### ISSUE THREAD

**Issue by stevenca** [ansible/galaxy#2700]
## Namespace Request
Namespace: 
model-driven-devops

##### Description

Model-Driven DevOps 

##### GitHub Org Link

https://github.com/model-driven-devops

##### Admins

stevenca

**Comment by stevenca** [comment]
Never mind... dashed in namespaces seems like a bad idea.

**Comment by thedoubl3j** [comment]
@stevenca dashes wouldn't work but you can use `_` if you would
