### ISSUE TITLE
Roles cannot be imported

### ISSUE THREAD

**Issue by SRv6d** [ansible/galaxy#2702]
##### SUMMARY
The [My Imports](https://galaxy.ansible.com/my-imports) page is completely blank and [My Content](https://galaxy.ansible.com/my-content/namespaces) reports "No Items Available".

##### ACTUAL RESULTS

<img width="1185" alt="Screenshot 2021-05-17 at 14 06 38" src="https://user-images.githubusercontent.com/18124752/118485772-1b98db80-b719-11eb-9714-04fc67a0dc62.png">
<img width="1440" alt="Screenshot 2021-05-17 at 14 07 11" src="https://user-images.githubusercontent.com/18124752/118485835-2eabab80-b719-11eb-9e1b-f21cf1bc6ff0.png">

**Comment by chouseknecht** [comment]
Should be fixed now. If it is, please close this issue. Thanks!

**Comment by SRv6d** [comment]
Fixed, thanks.
