### ISSUE TITLE
Namespace: tinypilot

### ISSUE THREAD

**Issue by mtlynch** [ansible/galaxy#2708]
## Namespace Request

Namespace: tinypilot

##### Description

Use your Raspberry Pi as a browser-based KVM.

##### GitHub Org Link

<https://github.com/tiny-pilot>

##### Admins

* @mtlynch

**Comment by thedoubl3j** [comment]
@mtlynch done :)

**Comment by mtlynch** [comment]
@thedoubl3j - Thanks! I'm able to see the new namespace but I'm not able to link it to my Github org (#2670). Is there any way to fix this?
