### ISSUE TITLE
Gremlin namespace request

### ISSUE THREAD

**Issue by fred-gremlin** [ansible/galaxy#2715]
## Namespace Request
Namespace: Gremlin

##### Description
Build resilience to failure, maintain customer trust, and improve incident response with Gremlin’s Chaos Engineering platform.

##### GitHub Org Link
https://github.com/gremlin

##### Admins
Nekototori
khultman

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/gremlin

Admins added:
* Nekototori
* khultman
