### ISSUE TITLE
spextreme

### ISSUE THREAD

**Issue by devkingdom** [ansible/galaxy#2717]
## Namespace Request
Namespace:  spextreme

##### Description
All my stuff is SP extreme and has been since '94 when I created it but that name was taken in GitHub (i have it in GitLab).  Since my name isn't accurate in GitHub I would like to have it for my projects.

##### GitHub Org Link
https://github.com/devkingdom

##### Admins
Just myself

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/spextreme

Admins added:
* @devkingdom

**Comment by devkingdom** [comment]
thank you
