### ISSUE TITLE
commscope

### ISSUE THREAD

**Issue by thamaraig** [ansible/galaxy#2718]
## Namespace Request
Namespace: Commscope

##### Description
Commscope

##### GitHub Org Link
https://github.com/commscope-ruckus

##### Admins
sushma.pradeep

**Comment by thamaraig** [comment]
@anshulbehl @JohnLieske @thedoubl3j can you please approve. Our collection is ready for long. I need to upload under commscope namespace immediately. Management is behind me.

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/commscope

Admins added:
* @thamaraig
