### ISSUE TITLE
Add CumulusLinux as a platform

### ISSUE THREAD

**Issue by davidmnoriega** [ansible/galaxy#272]
I found the list of platforms galaxy knows about from here: https://galaxy.ansible.com/api/v1/platforms/ and I see junos and nxos are there, but not one for Cumulus. I found the json string in the repo that defines this, but it contains date stamps in it, and wasn't sure about making a PR to update it.

**Comment by davidmnoriega** [comment]
Just as I write this, I found #80. Feel free to close out in favor of it, if that will become the future.

**Comment by chouseknecht** [comment]
I would really like to fix the platform issue, but we're not getting to it anytime soon, given all the other development work we have in progress. 

Will get this added early next week.

**Comment by chouseknecht** [comment]
Added Cumulus 2.5, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5. Let me know, if I missed one.
