### ISSUE TITLE
Please create a namespace which can be an owner of Ansible Roles

### ISSUE THREAD

**Issue by MonolithProjects** [ansible/galaxy#2721]
## Namespace Request
Namespace: lablabs

##### Description
Managed services for the cloud era. Helping companies with adoption and operations of cloud, containers and serverless.

##### GitHub Org Link
https://github.com/lablabs

##### Admins
monolithprojects, haad, martinhaus, thumbiceq

**Comment by JohnLieske** [comment]
Namespace created:
lablabs

Admins added:
* monolithprojects
* haad
* martinhaus
* thumbiceq
