### ISSUE TITLE
namespace: aussielunix

### ISSUE THREAD

**Issue by aussielunix** [ansible/galaxy#2724]
## Namespace Request

Namespace: aussielunix
I think I used to have a namespace for my personal GitHub account before the migration but now it is not showing for me and I cannot import any roles ("Permission denied").

##### Description

Enabling developers to deliver value at speed with safety

##### GitHub Org Link

it is a personal Github account - https://github.com/aussielunix

##### Admins

- aussielunix

**Thank you all**

**Comment by JohnLieske** [comment]
Hi, it looks like you had the namespace created but were not made an admin of the space. I have corrected that, so you should now be good. If you have any problems let us know.

Namespace name: 
https://galaxy.ansible.com/aussielunix

Admins:
* aussielunix
