### ISSUE TITLE
Request middleware_automation namespace

### ISSUE THREAD

**Issue by rpelisse** [ansible/galaxy#2730]
## Namespace Request
Namespace: ansible_middleware

##### Description

Ansible content for middleware (Wildfly, Apache Tomcat...)
##### GitHub Org Link

https://github.com/ansible-middleware/
##### Admins
sabre1041

**Comment by JohnLieske** [comment]
Hi @rpelisse ,

Is this a RH-related namespace request?

**Comment by rpelisse** [comment]
@JohnLieske  Yes, this is Red Hat related, but this is _not_ product related. This will be a **community** namespace. We will use it to release upstream content.

**Comment by JohnLieske** [comment]
@rpelisse the hesitation is about using the product name (Ansible) in the namespace request, especially if this is community for the middleware and not for RH Ansible (for which there's already a community GH & Galaxy). Is there a possibility of using something different than `ansible_middlerware` (as an example: `jboss_middleware`)?

**Comment by rpelisse** [comment]
@JohnLieske JBoss is even more problematic, sadly! Middleware is a very generic term (not a brand). Let me come back to you on that. We'll brainstorm another name. (please leave this issue open, I'll update it, so we keep track of the discussion.

**Comment by JohnLieske** [comment]
@rpelisse My bad! I totally wasn't thinking. This can absolutely remain open for the time being. I'll be notified when updated.

**Comment by rpelisse** [comment]
@JohnLieske So finally, after much discussion, we decided to go with **middleware_automation**.

**Comment by JohnLieske** [comment]
@rpelisse thanks so much for your patience.

Namespace created: https://galaxy.ansible.com/middleware_automation

Admin added:
sabre1041

Let me know if there are any questions.
