### ISSUE TITLE
New namespace for 'speechmatics'

### ISSUE THREAD

**Issue by weakcamel** [ansible/galaxy#2735]
## Namespace Request
Namespace: speechmatics

##### Description

Roles and collections by Speechmatics: https://github.com/speechmatics

Request raised per https://galaxy.ansible.com/docs/contributing/namespaces.html#requesting-additional-namespaces

##### GitHub Org Link

https://github.com/speechmatics

##### Admins

* speechmatics-bot
* weakcamel

**Comment by thedoubl3j** [comment]
@weakcamel done :) let us know if you have any problems.

**Comment by weakcamel** [comment]
@thedoubl3j Thank you!

I do have an issue with the new namespace to be honest. It showed on the list in "My content" but I'm experiencing the same issue as described here: https://github.com/ansible/galaxy/issues/2735 - I'm unable to add it in "Provider Namespaces"

![Screenshot 2021-06-29 at 11 18 56](https://user-images.githubusercontent.com/2445059/123781263-f37dca00-d8cb-11eb-9d10-eb20c9f8f735.png)

and my upload attempts via Github Actions finish with an error message

```
ERROR! None (HTTP Code: 500, Message: Internal Server Error)
```

https://github.com/speechmatics/ansible-role-hostname/runs/2940978841?check_suite_focus=true

Could you advise please?

**Comment by weakcamel** [comment]
@thedoubl3j @anshulbehl @JohnLieske help!

**Comment by JohnLieske** [comment]
@weakcamel What is the provider namespace org are you trying to add? Is it already a provider to another namespace? I can try to help you but I will need more information.

**Comment by JohnLieske** [comment]
Reopening to troubleshoot.

**Comment by JohnLieske** [comment]
@weakcamel Here is why you are having trouble from what I can see:

![Screenshot from 2021-06-30 09-14-15](https://user-images.githubusercontent.com/9461032/123966809-be34b300-d983-11eb-8576-a34e71b92336.png)

You already have speechmatics-bot as the provider namespace for the Galaxy namespace called speechmatics_bot. It cannot be the provider namespace for two Galaxy namespaces. You will have to remove it from one to add to the other.

**Comment by weakcamel** [comment]
@JohnLieske  I'm trying to set up the namespace `speechmatics` (ak.a. the company name), created on this this very request (see issue headline).

`speechmatics-bot` is a service account name, I don't want to publish company roles under it :)

**Comment by thedoubl3j** [comment]
so the github org that you linked is not showing up under the provider namespaces @weakcamel?

**Comment by weakcamel** [comment]
@thedoubl3j  Correct.

When I open `speechmatics` namespace, do `Edit properties` and go to provider namespaces, `speechmatics` isn't there on the list and I can't select it.

The same situation whether I use the _speechmatics-bot_ or my own _weakcamel_ account.

<img width="1443" alt="Screenshot 2021-06-30 at 20 03 00" src="https://user-images.githubusercontent.com/2445059/124017117-4051c580-d9de-11eb-922d-ee3300bbd4f9.png">



I believe the other linked requests for new namespaces suffered from the same problem:

- https://github.com/ansible/galaxy/issues/2670
- https://github.com/ansible/galaxy/issues/2708

**Comment by thedoubl3j** [comment]
@weakcamel I updated one of them 2670, I will see if you are suffering the same thing. one moment

**Comment by thedoubl3j** [comment]
so it looks like the api is showing correctly, did you grant galaxy access to the org @weakcamel? I think that might be the problem because things are displaying properly on the github api side which tells me galaxy wasn't allowed to see it.
docs: https://galaxy.ansible.com/docs/contributing/importing.html

**Comment by weakcamel** [comment]
@thedoubl3j  It makes sense, it could be permissions!

When I logged into galaxy for the first place, I don't believe I was asked for permissions - so there's nothing on the github side for me to confirm. Or, possibly, organization I own didn't yet exist.

Is there a way to re-trigger Galaxy asking me for access? I don't see a way how I could otherwise grant it on Github side.

**Comment by weakcamel** [comment]
OK, I've managed to work around it by creating yet another Github user, adding it to the organization and then logging into Galaxy. - which let me grant the organization access.

It would still be IMO valuable to know a better way how to re-trigger the organization access request.

**Comment by thedoubl3j** [comment]
@weakcamel there is, I think it is under the security settings and oauth applications. from there you can reject the app and then re-add it. The re-add process i am not super clear on but I would start with logging out and back into galaxy.

**Comment by weakcamel** [comment]
@thedoubl3j I'm not sure it would be there in organization as it was never allowed but maybe checking both personal and organizational OAuth might work.
I think I'll not test it though now that I'm finally set up unless i have to do it again :)

Thanks for you all your help and advice!

**Comment by thedoubl3j** [comment]
@weakcamel it would be at the user level but you grant the access to the org for galaxy (the image in the docs shows what I am trying to convey, I am just conveying it poorly). galaxy will only have read rights to the org but we do it through your user.

and no problem, glad we got it somewhat solved.
