### ISSUE TITLE
New Galaxy Namespace: ploigos

### ISSUE THREAD

**Issue by andykrohg** [ansible/galaxy#2737]
## Namespace Request
Namespace: ploigos

##### Description

Ploigos is an opinionated workflow used to transform ideas into delivered software in a production environment. 

##### GitHub Org Link

https://github.com/ploigos

##### Admins

andykrohg
itewk

**Comment by andykrohg** [comment]
Hey there, @anshulbehl @JohnLieske @thedoubl3j 👋 any chance I could get some help with this? Please let me know if there's anything else you need from me

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/ploigos

Admins added:
* andykrohg
* itewk

We're sorry for the delay, let us know if there are any questions.
