### ISSUE TITLE
New name space 'aedir'

### ISSUE THREAD

**Issue by stroeder** [ansible/galaxy#2741]
## Namespace Request
Namespace: aedir

##### Description
Æ-DIR collections, roles and modules

##### GitHub Org Link
Not available because Æ-DIR project is hosted here: https://gitlab.com/ae-dir

##### Admins
stroeder

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/aedir

Admin added 
* stroeder
