### ISSUE TITLE
Create a namespace for lefilament

### ISSUE THREAD

**Issue by remi-filament** [ansible/galaxy#2743]
## Namespace Request
Namespace: lefilament

##### Description
Namespace for Le Filament, French cooperative company

##### GitHub Org Link
https://github.com/lefilament

##### Admins
remi-filament (https://github.com/remi-filament)

If I may, once the namespace will be created, how can I move all roles / collections in my name to this new namespace ?
Thanks,
Best Regards,

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/lefilament

Admin added:
remi-filament

For your question, you may have to re-upload your content. You can find more about managing namespaces on our docs site: https://galaxy.ansible.com/docs/contributing/namespaces.html
