### ISSUE TITLE
Namespace Request - cookielab

### ISSUE THREAD

**Issue by Vrtak-CZ** [ansible/galaxy#2747]
## Namespace Request
Namespace: cookielab

##### Description
OpenSourced playbooks from Cookielab.io

##### GitHub Org Link
https://github.com/cookielab

##### Admins
- https://github.com/Vrtak-CZ
- https://github.com/jindrichskupa

**Comment by JohnLieske** [comment]
Namespace added:
https://galaxy.ansible.com/cookielab

Admins added:
* @Vrtak-CZ 
* @jindrichskupa
