### ISSUE TITLE
Can't add Stylers LLC organization

### ISSUE THREAD

**Issue by gabor-nagy-stylers** [ansible/galaxy#2752]
# ISSUE
I can't see my organization when trying to edit provider namespaces here: https://galaxy.ansible.com/my-content/namespaces/30706

## Namespace Request
Namespace: stylers_llc

##### Description
Stylers LLC Organization

##### GitHub Org Link
https://github.com/stylers-llc

##### Admins
gabor-nagy-stylers

**Comment by thedoubl3j** [comment]
@gabor-nagy-stylers are requesting a new namespace with this issue or is it for the organization issue? the link you provided is directly to your personal namespace

**Comment by gabor-nagy-stylers** [comment]
@thedoubl3j primarily I am asking for help in my case :) 
which is I am trying to add my github organization to provider namespaces as described [here](https://galaxy.ansible.com/docs/contributing/namespaces.html#adding-github-organizations-to-a-namespace), but it is not shown in the list.

[https://github.com/stylers-llc](https://github.com/stylers-llc) is my organization link, not my personal namespace.
I have owner role on the organization. 
Am I missing something?

Thank you

**Comment by thedoubl3j** [comment]
did you grant galaxy permissions to view the org? that would be my first thought

**Comment by gabor-nagy-stylers** [comment]
oh, that was the problem. I have reauthorized ansible app and granted access for organization and it works.

Thank you!
