### ISSUE TITLE
Request stylers namespace

### ISSUE THREAD

**Issue by gabor-nagy-stylers** [ansible/galaxy#2753]
## Namespace Request
Namespace: stylers  (or stylersllc)

##### Description
Collections and roles managed by Stylers LLC.

##### GitHub Org Link
https://github.com/stylers-llc

##### Admins
gabor-nagy-stylers

**Comment by JohnLieske** [comment]
Hi, is the non-parenthetical your first choice?

**Comment by gabor-nagy-stylers** [comment]
yes, it is. I was not sure whether it is available.

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/stylers

Admin added
* gabor-nagy-stylers

**Comment by gabor-nagy-stylers** [comment]
Thank you
