### ISSUE TITLE
Namespace request: bitsyai

### ISSUE THREAD

**Issue by leigh-johnson** [ansible/galaxy#2755]
## Namespace Request
Namespace: `bitsyai`

##### Description
Bitsy AI Labs is a research organization for machine learning on embedded systems.

##### GitHub Org Link
https://github.com/bitsy-ai

##### Admins
https://github.com/leigh-johnson / https://galaxy.ansible.com/leigh_johnson

Thank you!

**Comment by thedoubl3j** [comment]
@leigh-johnson done :)
