### ISSUE TITLE
Request Galaxy Namespace for Liqid, inc.

### ISSUE THREAD

**Issue by kirby-michael** [ansible/galaxy#2756]
## Namespace Request
Namespace: liqidinc

##### Description
Ansible modules for Liqid, Inc. composable infrastructure.

##### GitHub Org Link
https://github.com/liqidinc

##### Admins
kirby-michael

**Comment by thedoubl3j** [comment]
done @kirby-michael :) if you all are interested in the partner program at RedHat Ansible, please don't hesitate to reach out to ansiblepartners@redhat.com
