### ISSUE TITLE
namespace: claranet

### ISSUE THREAD

**Issue by ElieDeloumeau** [ansible/galaxy#2757]
## Namespace Request
Namespace: claranet

##### Description
Experts in modernising and running critical applications, data and infrastructure

##### GitHub Org Link
https://github.com/claranet/

##### Admins
https://github.com/ElieDeloumeau (`googley` on Galaxy, waiting for https://github.com/ansible/galaxy/issues/2739)
https://github.com/maxenced

**Comment by thedoubl3j** [comment]
@ElieDeloumeau created, in reference to #2739 I can't make direct edits to the back DBs and the folks that can are busy working on other downstream projects currently for ansiblefest. I will see if I can get some of these issues in front of them but I can't make any promises.
