### ISSUE TITLE
Request a Namespace - containernerds

### ISSUE THREAD

**Issue by daniel-lynch** [ansible/galaxy#2761]
## Namespace Request
Namespace: containernerds

##### Description
Enterprise Cloud Architect Consulting Group

##### GitHub Org Link
https://github.com/ContainerNerds

##### Admins
anthonyloukinas
daniel_lynch

**Comment by thedoubl3j** [comment]
@daniel-lynch done :)

**Comment by daniel-lynch** [comment]
Thanks! :)
