### ISSUE TITLE
Cannot login to Ansible Galaxy

### ISSUE THREAD

**Issue by Zorlin** [ansible/galaxy#2764]
SUMMARY
I have the same issue as in #2176 and #2274 and #2327 can't sign in to galaxy with GitHub account.

My email is zorlin ---at--- gmail.com.

STEPS TO REPRODUCE
Trying to login https://galaxy.ansible.com/accounts/login/

EXPECTED RESULTS
Successful login.

ACTUAL RESULTS
When I try to sign up, I get:

"An account already exists with this e-mail address. Please sign in to that account first, then connect your GitHub account."

When I try to sign in with the old username, I get:

"Server Error (500)"

Old username is "zorlin".

Had the issue for a while, I think it was due to deleting a GitHub authorisation. Please delete my Ansible Galaxy account so I can start fresh.

**Comment by Zorlin** [comment]
Still have the login issue which makes it hard to use Galaxy.

**Comment by chouseknecht** [comment]
Deleted the existing 'zorlin' account. You should be able to log in now.

**Comment by Zorlin** [comment]
> Deleted the existing 'zorlin' account. You should be able to log in now.

Thanks! It worked :) I'm able to login as normal now.
