### ISSUE TITLE
can't delete a running role from galaxy.ansible.com 

### ISSUE THREAD

**Issue by ThaddeusJiang** [ansible/galaxy#277]
my role is running. I want to stop it or delete it.

<img width="1161" alt="running" src="https://user-images.githubusercontent.com/17308201/34640578-7bcc82f2-f338-11e7-9dd6-03cd6efe6ee7.png">

**Comment by chouseknecht** [comment]
There were 3 imports related to that role, and they all have a state of 'FAILED'. When an import gets stuck in a 'RUNNIG' state, it generally gets cleaned up overnight.
