### ISSUE TITLE
namespace: community.elastic

### ISSUE THREAD

**Issue by rhysmeister** [ansible/galaxy#2771]
## Namespace Request
Namespace: community.elastic

##### Description
This Ansible collection provides modules to work with Elasticsearch instances and clusters.

##### GitHub Org Link
https://github.com/ansible-collections/community.elastic

##### Admins
@rhysmeister
@bndabbs

**Comment by gundalow** [comment]
Hi @rhysmeister 
Is the request to have Zuul CI publish the collection to Galaxy when a new `git tag` is pushed, ie same process as the other collections you maintain?


Also would you like me to give @bndabbs commit on https://github.com/ansible-collections/community.elastic

**Comment by rhysmeister** [comment]
Hello @gundalow Yes, that's correct.

1. Zuul CI for community.elastic
2. Perms for @bndabbs on community.elastic

Cheers,

Rhys

**Comment by thedoubl3j** [comment]
@gundalow ping for this
