### ISSUE TITLE
Platforms `opensuse 15.3`, `CentOS Steam 8/9` and `CentOS` successors missing

### ISSUE THREAD

**Issue by githubixx** [ansible/galaxy#2774]
##### SUMMARY
~~My [role](https://github.com/githubixx/ansible-role-wireguard) supports Fedora 33 and 34. But these platforms are not available for Galaxy: https://galaxy.ansible.com/api/v1/platforms/?page=2&search=fedora This causes that these two platforms are not listed in `OS Platforms` on the [Galaxy site of my role](https://galaxy.ansible.com/githubixx/ansible_role_wireguard) despite the fact that they are listed in [meta/main.yml](https://github.com/githubixx/ansible-role-wireguard/blob/master/meta/main.yml#L25-L28)~~ (Issue already open: https://github.com/ansible/galaxy/issues/2533)

Also `opensuse 15.3` is missing which was released July 2021.

I'd provide a PR but besides [test-data/platform.json](https://github.com/ansible/galaxy/blob/devel/test-data/platform.json) I'm not able to locate the file that provides all the platform information.

As you probably know `CentOS 8` has an EOL by end of 2021. The "official" successor is `CentOS Steam 8/9` but I guess nobody will migrate to that one who is currently running any version of `CentOS` for stability reasons. So I guess those people will more likely focus on one of the "unofficial" successors which most probably are:

[AlmaLinux](https://almalinux.org/)
[Rocky Linux](https://rockylinux.org/)
[Oracle Linux](https://www.oracle.com/linux/)

Any plans to add them too to Galaxy supported platforms?

##### STEPS TO REPRODUCE
See above.

##### EXPECTED RESULTS
Support `opensuse 15.3`, `CentOS Steam 8/9` and `CentOS` successors mentioned above.

**Comment by githubixx** [comment]
Looks like for Fedora 33/34 (and 35) there is already an issue: https://github.com/ansible/galaxy/issues/2533
But still `opensuse 15.3` and `CentOS Steam 8/9` are missing and also how the `CentOS` successors should be handled.

**Comment by gotmax23** [comment]
Hi everybody,

 > As you probably know `CentOS 8` has an EOL by end of 2021. The "official" successor is `CentOS Steam 8/9` but I guess nobody will migrate to that one who is currently running any version of `CentOS` for stability reasons. So I guess those people will more likely focus on one of the "unofficial" successors which most probably are:
> 
> [AlmaLinux](https://almalinux.org/)
> [Rocky Linux](https://rockylinux.org/)
> [Oracle Linux](https://www.oracle.com/linux/)
> 
> Any plans to add them too to Galaxy supported platforms?

All these CentOS replacement distributions should be covered by the existing `EL`  platform. You are right about Stream and Leap 15.3.

I made a full list of missing platforms in #2533, the aforementioned issue; hopefully, the developers will address that soon.

Thanks,
Maxwell

Also, I really like your Wireguard role, @githubixx!

**Comment by githubixx** [comment]
Thanks @gotmax23 ! Judging from how many important issues are open for month and partly years I guess nothing will change that soon :wink: But we'll see.

**Comment by gotmax23** [comment]
I agree, @githubixx. It seems that much of the development effort has moved to [galaxy_ng](https://github.com/ansible/galaxy_ng).

**Comment by githubixx** [comment]
A few new platforms were added as mentioned in https://github.com/ansible/galaxy/issues/2533. Also discussion about CentOS Steam and CentOS successors are happening there. So I'll close my issue in favor of https://github.com/ansible/galaxy/issues/2533
