### ISSUE TITLE
Not receiving verification email

### ISSUE THREAD

**Issue by tsailiming** [ansible/galaxy#2775]
##### SUMMARY

Have been trying to verify the email but not receiving the email.

##### STEPS TO REPRODUCE

Go to profile and click resend verification. Not email receiving including spam box. 

##### EXPECTED RESULTS

Should get a verification email.

##### ACTUAL RESULTS

Nothing happened. There is a popup box that says "Sending Verification We've sent your verification code to to xxx@xxx.com"

There is also a typo in the notification message. A double "to".

```

```

**Comment by silviuvulcan** [comment]
Same problem here. 

Doublechecked it is not in spam.

Tried both with a gmail address and another provider (gandi). None work.

**Comment by mikedlr** [comment]
Same here.  Also tried resend - confirm that the web page is sending a POST to 

https://galaxy.ansible.com/api/v1/emails/verification/

containing a JSON like so
`
{"email_address": [integer-number-deleted-here] }`

and is getting 200 success

`{"email_address":[integer-number-deleted-here],"verified":false,"url":"","related":{},"summary_fields":{},"created":"2021-08-31T09:47:41.107519Z","modified":null,"active":null}
`

**Comment by jmclement** [comment]
Same here. Multiple attempts and checked but no email received.

**Comment by rjlasko** [comment]
Same.  :(

**Comment by chrisvanmeer** [comment]
Same here.

**Comment by it-pappa** [comment]
Same here

**Comment by mharris-rh** [comment]
Same issue. confirmed with mail admin they are not seeing anything hit our mail servers/spam filters.

**Comment by Tony-Sol** [comment]
Same here

**Comment by fronczek** [comment]
Same here...

**Comment by mikedlr** [comment]
This issue has been pinged in the Ansible core meeting which brought it to the attention of the Galaxy team which is investigating.  TBH somehow it seems it was missed. I don't think it was clear that this blocked use of Galaxy by contributors in various important ways. Hopefully there will be some progress.

**Comment by obvionaoe** [comment]
Thanks @mikedlr for the update!

**Comment by federico-razzoli** [comment]
@mikedlr  Thanks for the update. And yes, it's important for contributors.

**Comment by it-pappa** [comment]
@mikedlr  thank you for the update :) 

Is there a way to delete old namesspaces also?
