### ISSUE TITLE
Role namespace changed to "info"

### ISSUE THREAD

**Issue by benwebber** [ansible/galaxy#278]
Previously [this role](https://github.com/devops-coop/ansible-haproxy/) was available as `devops-coop.haproxy`. Now it is only available as `info.haproxy`.

If it helps, this role has a somewhat complex history:

1. Originally hosted at <https://github.com/FloeDesignTechnologies/ansible-haproxy>, listed as `FloeDesignTechnologies.haproxy`.
2. Moved to current home at <https://github.com/devops-coop/ansible-haproxy/>.
3. Reimported as `devops-coop.haproxy`.

This probably happened because of the December changes. I thought I checked the namespace was still correct after those changes, but I may be mistaken.

Could it be restored to `devops-coop.haproxy`?

**Comment by PierrePaul** [comment]
To add some insights into this, I was the original author and maintainer of this project. My name on ansible galaxy is `info`, which is derived from my email address (`info@pierre-pa**.com`).

**Comment by chouseknecht** [comment]
Fixed. 

```
ansible-galaxy install devops-coop.haproxy
- downloading role 'haproxy', owned by devops-coop
- downloading role from https://github.com/devops-coop/ansible-haproxy/archive/v1.2.0.tar.gz
- extracting devops-coop.haproxy to /Users/chouseknecht/projects/roles/devops-coop.haproxy
- devops-coop.haproxy (v1.2.0) was installed successfully
```

**Comment by benwebber** [comment]
Thanks kindly!
