### ISSUE TITLE
Create a namespace for breuninger

### ISSUE THREAD

**Issue by FlxPeters** [ansible/galaxy#2782]
## Namespace Request
Namespace: breuninger

##### Description

Ansible roles and collections developed and provided by E. Breuninger GmbH & Co

##### GitHub Org Link

https://github.com/e-breuninger

##### Admins

* flxpeters

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/breuninger

Admin added:
* @FlxPeters

**Comment by FlxPeters** [comment]
Hey, thanks for creating the namespace. Do we need any further steps to get out Github organization mapped to this?
At the moment i'm not able to add Git repos from our Org: 
![grafik](https://user-images.githubusercontent.com/346241/132712267-359b3632-e6de-402b-a29b-60f85920f1e7.png)

I'm a user of the Github Org, but i cannot see the it in the "Provider Namespaces" selections.
Another Org im member of is available there.
