### ISSUE TITLE
Request for namespace creation

### ISSUE THREAD

**Issue by mberetti** [ansible/galaxy#2783]
## Namespace Request
Namespace: community.efficientip

##### Description
EfficientIP Ansible Collection

##### GitHub Org Link
https://github.com/mberetti/community.efficientip

##### Admins
mberetti

Thanks in advance,
Best regards,
MB

**Comment by gundalow** [comment]
@mberetti Hi, thank you for the GitHub issue.

We generally keep the `community.` GitHub repos under https://github.com/ansible-collections/ is that OK?

Do you have any code already written, https://github.com/mberetti/community.efficientip is a 404 for me.

**Comment by mberetti** [comment]
@gundalow Hi, thank you for your answer !

What do you mean about the "we generally keep the `community`", can this collection be hosted on a `community` namespace ? 
https://github.com/ansible-collections/community.efficientip is what I was looking for, but let me know if this is not possible...

Indeed, this repo is empty, actual code is hosted on gitlab.com/efficientip but has not yet been published.

Thanks in advance,
Best regards,
MB

**Comment by mberetti** [comment]
Hi,

Just to be sure, do I need to provide you with anything in order to be able to release our collection under https://github.com/ansible-collections/community.efficientip ?

Thanks in advance for your help,
Best regards,
MB

**Comment by thedoubl3j** [comment]
@mberetti a good starting place would be https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst

**Comment by mberetti** [comment]
@thedoubl3j  Thank you for your feedback, I am checking the URL you provided and I will reopen a request when ready...
