### ISSUE TITLE
namespace admin addition

### ISSUE THREAD

**Issue by itsBryantP** [ansible/galaxy#2788]
## Namespace Request
Namespace: IBM 

##### Description
Would like to use https://galaxy-dev.ansible.com for testing and need to be added to the IBM namespace. 

##### Admins
itsBryantP

**Comment by itsBryantP** [comment]
I am also looking for more information on the usage of https://galaxy-dev.ansible.com. I've seen it referenced several times to be used as a test server but I could not find any guidance or documentation. I'd like to know if there are any limitation when testing on this server and what the lifecycle of the content that is uploaded there? Does content get periodically erased and/or do content owners have more flexibility in managing their content?

**Comment by JohnLieske** [comment]
@itsBryantP the IBM org manages its own namespacer-- I'm not authorized to add you through this communication channel, they must add you or request through internal communications.

If thery need to know how to add you, the steps are:
* Navigate to My Content
* search for the namespace name
* find your namespace in the results
* click the three dots to the right of "Add Content"
* select "Edit Properties"
* Search the Galaxy users under Namespace Owners to add an admin

**Comment by itsBryantP** [comment]
@JohnLieske I'm already an admin on Galaxy.ansible.com but am not on galaxy-dev.ansible.com. Theres no way for me to tell who is an admin to request access. Any other guidance on my question above regarding usage of galaxy-dev.ansible.com?
