### ISSUE TITLE
Request namespace for Mila

### ISSUE THREAD

**Issue by btravouillon** [ansible/galaxy#2792]
## Namespace Request
Namespace: mila

##### Description
Mila Quebec Artificial Intelligence Institute roles and collections - https://mila.quebec

##### GitHub Org Link
https://github.com/mila-iqia

##### Admins
btravouillon

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/mila

Admin added:
@btravouillon

**Comment by btravouillon** [comment]
Thank you @thedoubl3j !
