### ISSUE TITLE
Request Namespace einfachit

### ISSUE THREAD

**Issue by Bassinator** [ansible/galaxy#2801]
## Namespace Request
Namespace: einfachit

##### Description
Ansible artefacts used by the einfachit society

##### GitHub Org Link
https://github.com/einfachIT

##### Admins
only one admin
Ansible user: bassinator
Github: https://github.com/Bassinator
email: bastian.greuel@gmail.com

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/einfachit

Admin added:
* @Bassinator
