### ISSUE TITLE
Ansible galaxy installs fail with 530 today morning

### ISSUE THREAD

**Issue by endriu0** [ansible/galaxy#2809]
##### SUMMARY
Trying to install collections from galaxy today morning - getting error 530. Tried upgrading ansible to latest version / no change. Passing a token doesn't fix it.

##### STEPS TO REPRODUCE
1. Try to install collection : ansible-galaxy collection install community.general --force
2. Get error : ERROR! Error when getting the collection info for community.general from default (https://galaxy.ansible.com/api/) (HTTP Code: 530, Message:  Code: Unknown)

##### EXPECTED RESULTS
Collection installs itself

##### ACTUAL RESULTS
ERROR! Error when getting the collection info for community.general from default (https://galaxy.ansible.com/api/) (HTTP Code: 530, Message:  Code: Unknown)

##### Debug output
ansible-galaxy collection install community.general-vvv --token super_secret_token                    
ansible-galaxy [core 2.11.6]
  config file = None
  configured module search path = ['/Users/myuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/myuser/opt/miniconda3/envs/ansible/lib/python3.8/site-packages/ansible
  ansible collection location = /Users/myuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/myuser/opt/miniconda3/envs/ansible/bin/ansible-galaxy
  python version = 3.8.5 | packaged by conda-forge | (default, Aug 29 2020, 01:18:42) [Clang 10.0.1 ]
  jinja version = 3.0.2
  libyaml = True
No config file found; using defaults
Starting galaxy collection install process
Found installed collection ansible.posix:1.2.0 at '/Users/myuser/.ansible/collections/ansible_collections/ansible/posix'
Found installed collection kubernetes.core:1.2.1 at '/Users/myuser/.ansible/collections/ansible_collections/kubernetes/core'
Process install dependency map
Created /Users/myuser/.ansible/galaxy_token
ERROR! Error when getting the collection info for community.general from default (https://galaxy.ansible.com/api/) (HTTP Code: 530, Message:  Code: Unknown)

```

```

**Comment by OneHappyForever** [comment]
Same issue, cannot run any roles.... what's going on?

**Comment by ChamMach** [comment]
Maybe add https://galaxy.ansible.com/ on https://status.redhat.com/ ?
