### ISSUE TITLE
change default namespace, due to GitHub username incompatible character

### ISSUE THREAD

**Issue by andreas-john** [ansible/galaxy#2814]
## Namespace Request
Namespace: andreas_john 

##### Description
cannot use my default assigned/created namespace (andreas-john) which is an invalid namespace according to https://galaxy.ansible.com/docs/contributing/namespaces.html#namespace-limitations. 
It seems that the namespace name was taken from my gibthub username. 
A validation/transformation was only performed for my ansible galaxy name (which is already andreas_john, https://galaxy.ansible.com/andreas_john ) but not for my default namespace.

renaming the current namespace andreas-john to andreas_john would resolve that issue 

##### GitHub Org Link
https://github.com/andreas-john

##### Admins

https://galaxy.ansible.com/andreas_john

**Comment by JohnLieske** [comment]
Hi @andreas-john 

From what I can see you already have a Galaxy namespace by this name. When I go to `My Content` and search the string "andreas_john" I sdee the following
![Screenshot from 2021-11-01 16-29-14](https://user-images.githubusercontent.com/9461032/139738133-4e8a37c1-4ab0-4869-af2d-8b1bf9263ae6.png)

**Comment by andreas-john** [comment]
As far as I understand this is the name, but in "My Content/ Edit Namespace" the Namespace listed in "Available Namespaces" for "Provider Namespaces" is named andreas-john

![Bildschirmfoto 2021-11-01 um 21 50 37](https://user-images.githubusercontent.com/631494/139740807-ac7d5e83-de67-46f8-aeec-ea766fecb819.png)
