### ISSUE TITLE
Namespace request for O1 Labs github org

### ISSUE THREAD

**Issue by 0x0I** [ansible/galaxy#2815]
## Namespace Request
Namespace: 01

##### Description
The 01 ansible-galaxy namespace will host roles and collections developed for providing Ansible-based automated, IaC solutions to support O1 Lab's mission to serve as an open/decentralized infrastructure, operations and managed service platform which leverages the technical expertise and insights of worldwide communities dedicated to the broad landscape of opensource projects.

##### GitHub Org Link
* **primary:** https://github.com/0x0I
* *secondary (secondary/currently transitioning to):* https://github.com/O1labs

##### Admins
* 0x0I

**Comment by 0x0I** [comment]
**Note:** I am currently receiving the following error when attempting to upload collections into my existing namespace, `0x0I`:

```
$ ansible-galaxy collection publish 0x0I-crypto-0.1.0.tar.gz  --api-key 52ce0a45f96de47adf283437cdc736917363f97f
Publishing collection artifact '/home/ahmad/lab/operator/ansible/O1labs/crypto/0x0I-crypto-0.1.0.tar.gz' to default https://galaxy.ansible.com/api/
ERROR! Error when publishing collection to default (https://galaxy.ansible.com/api/) (HTTP Code: 400, Message: Invalid namespace: '0x0I' Code: invalid)

$ ansible-galaxy collection publish 0x0i-crypto-0.1.0.tar.gz  --api-key 52ce0a45f96de47adf283437cdc736917363f97f
Publishing collection artifact '/home/ahmad/lab/operator/ansible/O1labs/crypto/0x0i-crypto-0.1.0.tar.gz' to default https://galaxy.ansible.com/api/
ERROR! Error when publishing collection to default (https://galaxy.ansible.com/api/) (HTTP Code: 400, Message: Invalid namespace: '0x0i' Code: invalid)
```

Not really sure why publishing to the `0x0i` namespace is failing since it fits the namespace naming limitations (i.e. alphanumeric, all lowercase and contains no special characters) according to #2201. In any case, I'm hoping and believe that the requested namespace, `01`, does indeed fit the naming requirements but please advise if not.

**Comment by alisonlhart** [comment]
@0x0I Just to confirm, you are requesting namespace `01`, not namespace `O1`?

**Comment by alisonlhart** [comment]
@0x0I I would attempt upload again, as it appears there have been previous successful uploads to the 0x0I namespace with no issues. Do you know if those uploads were via CLI in the past? 

Your namespace `01` is also valid according to namespace limitations: https://galaxy.ansible.com/docs/contributing/namespaces.html#namespace-limitations . However, I would suggest instead the name of o1_labs or 01_labs as the namespace for better identification in galaxy.

**Comment by 0x0I** [comment]
Hey, thanks for following up - I'm requesting 01 (zero one) since something
like O1 (capital 'oh' one) and preferred doesn't fit the lower-case
characters limitation.

**Comment by 0x0I** [comment]
> @0x0I I would attempt upload again, as it appears there have been previous successful uploads to the 0x0I namespace with no issues. Do you know if those uploads were via CLI in the past?

Are you referring to collections uploads as well? I've had no issue uploading roles via both the CLI and webUI though haven't been able to upload collections with my current namespace (`0x0i`) using either.

> Your namespace `01` is also valid according to namespace limitations: https://galaxy.ansible.com/docs/contributing/namespaces.html#namespace-limitations . However, I would suggest instead the name of o1_labs or 01_labs as the namespace for better identification in galaxy.

Great, got it..thanks. I kind of like the name "01" (zero one) and how succinct it is though I somewhat get how it could be a bit troublesome as an identifier in galaxy. Proceeding with "01" for now would be great but we can revisit later if it becomes an issue.

**Comment by 0x0I** [comment]
**Request edit:**

## Namespace Request
Namespace: 0labs

##### Description
The 0labs ansible-galaxy namespace will host roles and collections developed for providing Ansible-based automated, IaC solutions to support O1 Lab's mission to serve as an open/decentralized infrastructure, operations and managed service platform which leverages the technical expertise and insights of worldwide communities dedicated to the broad landscape of opensource projects.

##### GitHub Org Link
* **primary:** https://github.com/0x0I
* *secondary (secondary/currently transitioning to):* https://github.com/O1labs

##### Admins
* 0x0I

**Comment by alisonlhart** [comment]
@0x0I I verified with other community contributors, and there are different restrictions on namespace names when it comes to roles and collections. Collections can only be uploaded to namespaces that are valid python identifiers. This adds the additional restriction of namespaces not starting with a numeric [0-9]. Roles do not have this restriction. This does not appear to be in Galaxy documentation at the moment and the community is looking to add it. 

This would also apply to the new namespace request here. We can set up the namespace o1labs or olabs instead of 0labs. 

Waiting to hear back on your preference before creating the namespace.

**Comment by 0x0I** [comment]
Hey @alisonlhart, ah thanks for looking into this and ok got it. Not a huge fan of any of the options atm tbh but will go with "olabs".

**Comment by alisonlhart** [comment]
**olabs** namespace has been created.

**Comment by 0x0I** [comment]
Hey @alisonlhart, thanks for setting up the namespace! Just curious about the process to rename/modify a namespace. Based on further discussions with my team, `o1labs` may make more sense and be easier to recognize considering the sort of "before and after" merged approach works a bit better with an  actual 'O' or '0' than a 'o'. Apologies for the inconvenience - the naming constraints have been a bit tougher to reason about and work around.

**Comment by 0x0I** [comment]
Hey, I opened #2819 regarding the namespace change.
