### ISSUE TITLE
Request for a fretlink namespace

### ISSUE THREAD

**Issue by technofret** [ansible/galaxy#2816]
## Namespace Request
Namespace: fretlink

##### Description
Role made at [fretlink](https://www.fretlink.com) to cover our needs

##### GitHub Org Link
https://github.com/fretlink

##### Admins

* technofret
* gaetanfl

Thanks in advance

**Comment by alisonlhart** [comment]
**fretlink** namespace created. Admins **technofret** and **gaetanfl** have been added.
