### ISSUE TITLE
Request to create virt-roles namespace

### ISSUE THREAD

**Issue by stefanha** [ansible/galaxy#2817]
## Namespace Request
Namespace: virt-roles

##### Description
Ansible roles for Linux KVM development

##### GitHub Org Link
https://github.com/virt-roles

##### Admins
stefanha

**Comment by alisonlhart** [comment]
@stefanha Need confirmation:

"-" is not permitted under namespace name restrictions. Is the namespace virt_roles acceptable?

**Comment by stefanha** [comment]
On Thu, Nov 4, 2021, 18:24 Alison Hart ***@***.***> wrote:

> @stefanha <https://github.com/stefanha> Need confirmation:
>
> "-" is not permitted under namespace name restrictions. Is the namespace
> virt_roles acceptable?
>

Yes, underscore is good. Thanks!

**Comment by alisonlhart** [comment]
**virt_roles**  namespace has been created with admin **stefanha**.
