### ISSUE TITLE
namespace: ableton

### ISSUE THREAD

**Issue by nre-ableton** [ansible/galaxy#2818]
## Namespace Request
Namespace: ableton

##### Description

Ableton makes Push and Live, hardware and software for music production, creation and performance.

##### GitHub Org Link

https://github.com/Ableton

##### Admins

@ala-ableton
@nre-ableton

**Comment by alisonlhart** [comment]
**ableton** namespace created.

**Comment by nre-ableton** [comment]
@alisonlhart thanks!
