### ISSUE TITLE
namespace: o1labs request/change

### ISSUE THREAD

**Issue by 0x0I** [ansible/galaxy#2819]
## Namespace Request/Change
Namespace: o1labs (previously olabs)

##### Description
The o1labs ansible-galaxy namespace will host roles and collections developed for providing Ansible-based automated, IaC solutions to support O1 Lab's mission to serve as an open/decentralized infrastructure, operations and managed service platform which leverages the technical expertise and insights of worldwide communities dedicated to the broad landscape of opensource projects.

##### GitHub Org Link
* **primary:** https://github.com/0x0I
* *secondary (secondary/currently transitioning to):* https://github.com/O1labs

##### Admins
* 0x0I

**Comment by 0x0I** [comment]
Related to #2815

**Comment by alisonlhart** [comment]
Namespace modified to **o1labs**.
