### ISSUE TITLE
No default namespace shown under My Content in Ansible Galaxy 

### ISSUE THREAD

**Issue by avnes** [ansible/galaxy#2821]
##### SUMMARY
I have linked my GitHub account to Ansible Galaxy. When I login to Ansible Galay in the browser, and go to "My Content", no namespace is shown. I can only see the message "No Items Available"  even though I have published roles in the past. 
I tried to unlink my GitHub OAuth integration to Galaxy and create it again, but the problem persist.

I guess that because of that I get a HTTP 403 error code when I try to do "ansible-galaxy role import" from the command line too...

##### STEPS TO REPRODUCE
1. https://galaxy.ansible.com/my-content/namespaces does not show any namespacec or content.

##### EXPECTED RESULTS
1. I would have expected to see a namespace called avnes with 5 roles in it.

##### ACTUAL RESULTS

``
![mycontent](https://user-images.githubusercontent.com/20299875/141425191-cb0092c6-c62b-4162-abe1-ca6fc2a78eed.png)
`

```

**Comment by alisonlhart** [comment]
@avnes Please try accessing your namespace and content now. It appears your account was unlinked from your namespace.

**Comment by avnes** [comment]
Thanks @alisonlhart - It works now :)
