### ISSUE TITLE
moinulrony

### ISSUE THREAD

**Issue by moinulrony** [ansible/galaxy#2825]
## Namespace Request
Namespace: moinulrony

##### Description
moinulrony namespace init

##### Admins
moinulrony

**Comment by thedoubl3j** [comment]
@moinulrony was the namespace not created when you logged into galaxy? user namespaces are automatically created. unless you have a legacy account

**Comment by JohnLieske** [comment]
@moinulrony your username does not appear in Galaxy. You must first go to https://galaxy.ansible.com/login and sign in using your GH account. Once you do, a namespace matching your username will be created automatically. You will be able to access the namespace from the My Content section on the site.
