### ISSUE TITLE
namespace: mambaorg

### ISSUE THREAD

**Issue by maresb** [ansible/galaxy#2827]
## Namespace Request
Namespace: mambaorg

##### Description

The Fast Cross-Platform Package Manager, and related tools

##### GitHub Org Link

<https://github.com/mamba-org>

##### Admins

@atrawog, @wolfv, @maresb

**Comment by thedoubl3j** [comment]
@maresb Done, let us know if you have any problems though we might be mia for the next few days due to NA holidays
