### ISSUE TITLE
namespace: mambaorg (can't find provider namespace)

### ISSUE THREAD

**Issue by maresb** [ansible/galaxy#2829]
This is a follow-up to #2827.

I am now an owner of the [Galaxy namespace named `mambaorg`](https://galaxy.ansible.com/mambaorg). I would like to be able to add a role from a GitHub repository under the [`mamba-org` GitHub organization](https://github.com/mamba-org/). As I understand from [the docs](https://galaxy.ansible.com/docs/contributing/namespaces.html#adding-github-organizations-to-a-namespace), the prerequisite is to add the GitHub organization as a Provider Namespace.

I am trying to add the [`mamba-org` Git organization](https://github.com/mamba-org/) as a "Provider Namespace" to the [Galaxy namespace `mambaorg`](https://galaxy.ansible.com/mambaorg), but I seem to be unable to select it. (There are 0 results.) Am I doing something wrong? Thank you!

![image](https://user-images.githubusercontent.com/15216687/143274292-69cef9a6-a812-4fe1-8cdb-1bea814d3cce.png)

**Comment by thedoubl3j** [comment]
@maresb you need to grant galaxy access to the org via you. should be under settings and then security I think? https://galaxy.ansible.com/docs/contributing/importing.html#updating-github-permissions

**Comment by maresb** [comment]
Thanks @thedoubl3j, that worked!

I also made the PR #2831 in an attempt to improve the docs so that I would have found this info myself.

Hope you all had a happy thanksgiving! :turkey:
