### ISSUE TITLE
Namespace-request: cybercyber.org

### ISSUE THREAD

**Issue by toelke** [ansible/galaxy#2835]
## Namespace Request
Namespace: cybercyber.org

##### Description
Guiding through the world of cyber

##### GitHub Org Link
https://github.com/cybercyber-org/

##### Admins
toelke

**Comment by alisonlhart** [comment]
@toelke Galaxy namespace guidelines follow Python naming conventions. This excludes the "." character. Could an "_" be used instead? 
Namespace: cybercyber_org

**Comment by toelke** [comment]
Yes, I would be happy with that. Thank you!

**Comment by alisonlhart** [comment]
namespace: cybercyber_org created. 
administrator: toelke

Closing request.

**Comment by toelke** [comment]
Thanks!
