### ISSUE TITLE
Requesting namespace: spot

### ISSUE THREAD

**Issue by SHxKM** [ansible/galaxy#2836]
## Namespace Request
Namespace: `spot`

##### Description
Spot by NetApp

##### GitHub Org Link
https://github.com/spotinst/

##### Admins
- https://galaxy.ansible.com/shxkm
- https://galaxy.ansible.com/noham1412

CC: @noham1412

**Comment by alisonlhart** [comment]
namespace: spot
administrators: shxkm, noham1412

Namespace created. Closing.

**Comment by alisonlhart** [comment]
@SHxKM Since this product is by Netapp, we can help you get connected the owners of their namespace so you can get access to upload there instead of having a separate one.

**Comment by alisonlhart** [comment]
@carchi8py Can you grant @SHxKM access to the Netapp namespace so the Spot content can be uploaded?

**Comment by SHxKM** [comment]
@alisonlhart hey Alison, thanks a lot for being so responsive and approving this quickly. 

Re Spot:NetApp - I would like to allow the different product teams to discuss this first and reach a decision. Thanks again!

**Comment by SHxKM** [comment]
> @alisonlhart Yes give me a sec
> @SHxKM let me contact you internally, as i need to run this through our PM for all Ansible collection netapp releases.

Hey @carchi8py - this should be discussed between PMs as you wrote. I’ve got no say in this.
