### ISSUE TITLE
namespace: whiletruedoio (Change Request)

### ISSUE THREAD

**Issue by dschier-wtd** [ansible/galaxy#2837]
Hi all,

I want to request a change of the existing namespace while_true_do to whiletruedoio. This is due to some re-organization and migration work (tools that do or don't support underscores, dashes, etc...) that needs to be done.

## Namespace Request

old Namespace: while_true_do
new Namespace: whiletruedoio

##### Description

Open Source - Development, Community, Infrastructure

##### GitHub Org Link

old: https://github.com/while_true_do
new: https://github.com/whiletruedoio

##### Admins

dschier-wtd (me)

(edit: username and old github org link)

**Comment by alisonlhart** [comment]
namespace changed from while_true_do to whiletruedo. closing.

**Comment by dschier-wtd** [comment]
hi @alisonlhart unfortunately, I requested the change to whiletruedoio and not whiletruedo. Could you fix this please? I can also open a new issue, if this is recommended :)

Also, the provider namespace seems to point to github.com/while_true_do and not to the new github.com/whiletruedoio.

**Comment by dschier-wtd** [comment]
And even more interesting: the "view on github" button points to our website and not to the github project :/

**Comment by alisonlhart** [comment]
@dschier-wtd My apologies for the mix up. I'll get that resolved right away along with the URL issue.

**Comment by alisonlhart** [comment]
The namespace name has been corrected to **whiletruedoio** . The URL has also been updated to the new repo: https://github.com/whiletruedoio. 

The provider namespace is something I'm unable to edit. As long as you are a member of that organization on github, it should allow you to update the namespace under "Provider Namespaces, Available Namespaces" in the namespace settings. If you are unable to see the new repo there, please let me know and I can escalate the issue.

**Comment by dschier-wtd** [comment]
Thanks a lot for the quick fix. The name looks fine now and the link in the community overview seems also fine. For the provider namespace, I will check back after pushing the first role, maybe this aligns the namespace. For now, it only displays the old namespaces (dschier-wtd and while_true_do).

Thank you again :)

**Comment by alisonlhart** [comment]
Closing as resolved for now - we can reopen if there's any further issues.
