### ISSUE TITLE
Namespace request: TechTribeOne

### ISSUE THREAD

**Issue by slconley** [ansible/galaxy#2843]
## Namespace Request
Namespace: TechTribeOne

##### Description
Ansible Roles and Collections by TechTribeOne

##### GitHub Org Link
https://github.com/TechTribeOne

##### Admins
slconley

**Comment by alisonlhart** [comment]
Namespace **techtribeone** created. 

Capitalization was removed to comply with galaxy namespace requirements.

**Comment by slconley** [comment]
thanks so much!
