### ISSUE TITLE
Change namespace to remove minus sign in name

### ISSUE THREAD

**Issue by laurentdavid** [ansible/galaxy#2845]
## Namespace Request
Namespace: call_learning

##### Description
A few years ago I created an account using call-learning as an account name (from github) but I recently understood that namespace rules did not allow for '-' in the name. 
I would like to be able to change it if possible. I am not sure why but I cannot manage any projet under https://galaxy.ansible.com/call-learning which I should be admin on.

##### GitHub Org Link
(https://github.com/call-learning)

##### Admins
laurentdavid

**Comment by alisonlhart** [comment]
Namespace name changed to: call_learning from call-learning. @laurentdavid You've been added to the namespace as an admin. For some reason, you weren't on there.
