### ISSUE TITLE
namespace: dagos

### ISSUE THREAD

**Issue by MLNW** [ansible/galaxy#2851]
## Namespace Request
Namespace: dagos

##### Description
DAG-OS ansible roles.

##### GitHub Org Link
<https://github.com/DAG-OS>

##### Admins
<https://github.com/MLNW>

**Comment by alisonlhart** [comment]
Namespace dagos created.

**Comment by MLNW** [comment]
@alisonlhart I am sadly unable to add the DAG-OS organization as a namespace provider:

![image](https://user-images.githubusercontent.com/20930814/148205609-d96b9951-2547-409b-aacc-07aefe6e4785.png)

**Comment by MLNW** [comment]
I was able to fix it myself with the hints provided here: https://github.com/ansible/galaxy/issues/2735#issuecomment-872357362

In the end I revoked the access via my users GitHub preferences, logged out of ansible galaxy and logged in again, this time granting permissions on the organization.
