### ISSUE TITLE
Namespace request: ecgalaxy

### ISSUE THREAD

**Issue by jfhovinne** [ansible/galaxy#2854]
## Namespace Request

Namespace: ecgalaxy

##### Description

The European Commission ECGALAXY project provides a set of reusable Infrastructure as Code (IaC) tools and components

##### GitHub Org Link

https://github.com/ecgalaxy

##### Admins

jfhovinne
nicolimo86

**Comment by alisonlhart** [comment]
Namespace ecgalaxy created.

**Comment by jfhovinne** [comment]
Thank you @alisonlhart
