### ISSUE TITLE
namespace: Ansible Galaxy name change problem

### ISSUE THREAD

**Issue by 6nsh** [ansible/galaxy#2855]
## Namespace Request
Namespace: 
6nsh(new), banshee-art (old).

##### Description

Hi everyone!
Not so long ago I changed my name on GitHub from "banshee-art" to "6nsh". After that, I expected that the name on Galaxy will change automatically, but this did not happen. So...can you help me with it? Cause it gives me some inconvenience.
P.S. And...can you delete an old namespace "banshee_art" ?
Thank you!
##### GitHub Org Link

https://github.com/6nsh

##### Admins

https://galaxy.ansible.com/6nsh  (new)
https://galaxy.ansible.com/banshee-art  (old)

**Comment by thedoubl3j** [comment]
hey @6nsh we can't delete the old one but you can deprecate everything there. The old namespace will always exist as that was created when you logged into galaxy and will always be your "personal" namespace. At the end of the day, galaxy and github are separate systems, we just use github to auth and then use your username from github if it available on galaxy as well. 

I will create a new namespace and add you as an admin there so that you can upload content etc.

**Comment by 6nsh** [comment]
> hey @6nsh we can't delete the old one but you can deprecate everything there. The old namespace will always exist as that was created when you logged into galaxy and will always be your "personal" namespace. At the end of the day, galaxy and github are separate systems, we just use github to auth and then use your username from github if it available on galaxy as well.
> 
> I will create a new namespace and add you as an admin there so that you can upload content etc. Do note though that namespaces must follow pep-8 naming conventions so the 6 will need to be changed to something else. "sixnsh" or something of the sort. See [1password](https://galaxy.ansible.com/onepassword) as an example.

Hey @thedoubl3j . Thanks, I already created the new namespace myself. Can you change my nickname on Galaxy (banshee-art) to one like here (6nsh), or is it out of your control? Thanks again for your reply.

**Comment by alisonlhart** [comment]
@6nsh There's unfortunately no way to update the Galaxy nickname at this time on our end. It will continue to show the original nick from Github from when you authed for the first time. It does not affect functionality since as long as you're an admin on the namespace, you can upload to it.

**Comment by 6nsh** [comment]
> @6nsh There's unfortunately no way to update the Galaxy nickname at this time on our end. It will continue to show the original nick from Github from when you authed for the first time. It does not affect functionality since as long as you're an admin on the namespace, you can upload to it.

@alisonlhart , yeah, i know about: "It does not affect functionality". Okay, it was only a matter of aesthetics :) 
Thank you a lot. I guess the issue is closed.
