### ISSUE TITLE
namespace request

### ISSUE THREAD

**Issue by 1mr** [ansible/galaxy#2856]
## Namespace Request
Namespace: leadlineit

##### GitHub Org Link
https://github.com/leadlineit

##### Admins
@1mr, @6nsh

**Comment by thedoubl3j** [comment]
hey @1mr I am not seeing these users on galaxy, do you have a different account there? If you don't have an account, just navigate to galaxy and then click login and auth through github, that should create an account with your github username.

**Comment by 6nsh** [comment]
> hey @1mr I am not seeing these users on galaxy, do you have a different account there? If you don't have an account, just navigate to galaxy and then click login and auth through github, that should create an account with your github username.

Hello @thedoubl3j . In a situation with me, you don't see me because:
https://github.com/ansible/galaxy/issues/2855
Can somebody help with it?)

**Comment by 6nsh** [comment]
> 

Hi @alisonlhart . Yeah, namespace "leadlineit" work fine. Thank you. I think this issue can be close.

**Comment by 6nsh** [comment]
> @6nsh @1mr Both of your accounts are still showing up in galaxy as banshee-art and stas.stavnichuk respectively. Until this is able to be resolved on the galaxy backend, you should still be able to access this new namespace as your github accounts are still connected to these accounts on galaxy. Please let me know if you have any issues uploading.
> 
> As mentioned in the comment on #2855, non-pythonic variable names (such as names starting with a number like 1mr and 6nsh) will cause issues if you upload collections to galaxy. Let us know if you'd like us to create new namespaces for your galaxy accounts. These namespaces will need to be modified slightly to something like "sixnsh" or "onemr". Still, at this time, everything should be working correctly, even if the account names on galaxy still show your old git names.

Hi @alisonlhart . Yeah, namespace "leadlineit" work fine. Thank you. I think this issue can be close.

**Comment by alisonlhart** [comment]
@6nsh Thanks for following up. Closing issue.
