### ISSUE TITLE
Namespace Request

### ISSUE THREAD

**Issue by philippwaller** [ansible/galaxy#2857]
## Namespace Request
Dear team, I would like to apply for a new namespace for the organization "wallernetwork". The namespace is already linked to the admin user on galaxy.ansible.com. Thanks!

Namespace: wallernetwork

##### Description
Wallernet.work

##### GitHub Org Link
https://github.com/wallernetwork

##### Admins
philippwaller

**Comment by alisonlhart** [comment]
Namespace wallernetwork with admin philippwaller created.
