### ISSUE TITLE
Hellebore Consulting Group

### ISSUE THREAD

**Issue by james-adamo-hcg** [ansible/galaxy#2859]
## Namespace Request
Namespace: hellebore_consulting_group

##### Description
Welcome to Hellebore. A different kind of software company. 

##### GitHub Org Link
https://github.com/Hellebore-Consulting-Group

##### Admins
james.adamo@hellebore.com

**Comment by alisonlhart** [comment]
Namespace hellebore_consulting_group created with admin james-adamo-hcg.
