### ISSUE TITLE
namespace: Unable to add organisation Github in Provider Namespace

### ISSUE THREAD

**Issue by FlxPeters** [ansible/galaxy#2865]
## Namespace Request
Namespace: breuninger

##### Description

This is a follow up of a previous ticket #2782. The Namespace in galaxy is created but i cannot assign a provider namespace. Seams to be the same issue like #2670.

Note: The Github namespace is `e-breuninger` but the Galaxy namespace is just `breuninger`. 

![grafik](https://user-images.githubusercontent.com/346241/150630048-9fc2d424-3837-474d-beee-ac0129e49084.png)

The Namespace `breuninger`already exist, but i cannot add content. 

##### GitHub Org Link

https://github.com/e-breuninger

##### Admins

* FlxPeters

**Comment by alisonlhart** [comment]
@FlxPeters The breuninger namespace has been deleted and recreated with you as an admin. You may need to update the e-breuninger GH organization's Third Party Access Policy to allow Ansible Galaxy if you still can't add the provider namespace. Please tag me in your response once you're able to test.

**Comment by FlxPeters** [comment]
Thanks,the issue is fixed. App permissions did the trick.
