### ISSUE TITLE
Create ansible714 namespace

### ISSUE THREAD

**Issue by xtof-osd** [ansible/galaxy#2871]
## Namespace Request
Namespace: ansible714

##### Description
Ansible714 is a toolset developped by volunteers at Article714 informal association

##### GitHub Org Link
[Article714 on Github](https://github.com/article714/)
[Article714 on gitlab](https://gitlab.com/article714)
[Ansible714 project on gitlab](https://gitlab.com/article714/ansible714)
[Ansible714 first collection on gitlab](https://gitlab.com/article714/ansible714-ovh-collection)

##### Admins
[xtof-osd](https://github.com/xtof-osd) will be the only admin at the start

**Comment by alisonlhart** [comment]
Namespace ansible714 created. https://galaxy.ansible.com/ansible714

**Comment by xtof-osd** [comment]
Many Thanks @alisonlhart .
