### ISSUE TITLE
Namespace Request

### ISSUE THREAD

**Issue by NavidSassan** [ansible/galaxy#2876]
## Namespace Request
Namespace: linuxfabrik

##### Description
Linuxfabrik

##### GitHub Org Link
https://github.com/linuxfabrik/

##### Admins
@navidsassan
@markuslf
@sandrolf

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/linuxfabrik

Admins added:
* @NavidSassan 
* @markuslf
* @sandrolf
