### ISSUE TITLE
Namespace Request

### ISSUE THREAD

**Issue by dabo-devconsole** [ansible/galaxy#2878]
Namespace: devconsole

Description
DevConsole

GitHub Org Link
https://github.com/devconsole-de

Admins
dabo-devconsole

_Originally posted by @JohnLieske in https://github.com/ansible/galaxy/issues/2875#issuecomment-1030262624_

I know that there already is a user namespace, but I want one for the organization, because I will transfer the repo to the organization.

**Comment by alisonlhart** [comment]
@dabo-devconsole The namespace has been created. You should be able to access and upload to it now. 
https://galaxy.ansible.com/devconsole
