### ISSUE TITLE
Namespace request: rudder

### ISSUE THREAD

**Issue by Fdall** [ansible/galaxy#2883]
## Namespace Request
Namespace: rudder

##### Description
Rudder Ansible Collection.

##### GitHub Org Link
https://github.com/Normation

##### Admins
[@amousset](https://github.com/amousset)
[@Fdall](https://github.com/Fdall)

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/rudder

Admins added:
* @amousset
* @Fdall

**Comment by amousset** [comment]
Thanks!
