### ISSUE TITLE
IMPORTER101: Invalid platform: "Debian-11", skipping.

### ISSUE THREAD

**Issue by Tronde** [ansible/galaxy#2886]
##### SUMMARY

Galaxy quality score shows "IMPORTER101: Invalid platform: "Debian-11", skipping." after import.
##### STEPS TO REPRODUCE

Import role using `meta/main.yml` containing:

~~~
  platforms:
  - name: Debian
    versions:
      - 11
~~~

##### EXPECTED RESULTS

I'd expect that version 11 is recognized since Bullseye is released for a while.
##### ACTUAL RESULTS

IMPORTER101: Invalid platform: "Debian-11", skipping.

Please add Debian 11 to the platforms list.

**Comment by alisonlhart** [comment]
Debian-bullseye is in the platforms list. https://galaxy.ansible.com/api/v1/platforms/226/
