### ISSUE TITLE
namespace: FIXME

### ISSUE THREAD

**Issue by MikePadge** [ansible/galaxy#2887]
## Namespace Request
Namespace: P2X-3YZ

##### Description

SGC Galaxy Collection

##### GitHub Org Link

https://github.com/p2x3yz

##### Admins

MikePadge

**Comment by JohnLieske** [comment]
Hi @MikePadge , if we create the namespace as requested we would have to exclude the dash & capitalization. The resulting namespace would be p2x3yz. Is this okay?

**Comment by alisonlhart** [comment]
(Gentle reminder on John's question @MikePadge )

**Comment by alisonlhart** [comment]
@MikePadge (Another nudge, as we will close this issue in 7 days if we don't hear back. We will reopen if requested)
