### ISSUE TITLE
ansible-galaxy collection install timeout

### ISSUE THREAD

**Issue by lsstreet** [ansible/galaxy#2890]
In Ansible Tower  using  the file collections/requirements.yml  in playbooks  now  we are  facing with timout issues.

Example of the command used by Ansible Tower to install the collection
` ansible-galaxy collection install -r collections/requirements.yml --collections-path /var/lib/awx/projects/.__awx_cache/_188__linux_expinfunixpro_playbook_tower152022/stage/requirements_collections  -vvv\n`

Error:
`"stderr": "ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/v2/collections/theforeman/foreman/versions/': ('The read operation timed out',)",`

making some tests directly on URL with curl command 10% of the requests are failing with next output:
```
< HTTP/1.1 504 Gateway Timeout
< Date: Mon, 21 Feb 2022 23:50:57 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
< Cache-Control: no-cache
< CF-Cache-Status: DYNAMIC
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=RxRnv%2BY2u7vBXsySxxj%2Bz8fGvRIcOHviuA%2B15qGpS0DDl1IXMBeII9m07Qn11e3dOm4qZTqRq2VdgVZDX9qlCEj3q9xAFOHAtScuY9pW6K6xMIgKhT39xziaNBekqBdFvzGrrQ%3D%3D"}],"group":"cf-nel","max_age":604800}
< NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< Server: cloudflare
< CF-RAY: 6e13e084383e03b4-ORD
```

Please check and fix this issue

**Comment by TimofeyBiryukov** [comment]
Galaxy API appears to be down

![image](https://user-images.githubusercontent.com/2659111/155074459-cd5f2599-6aed-421e-96a3-866f04088889.png)

**Comment by RanabirChakraborty** [comment]
still, it's not working.

```
[WARNING]: Skipping Galaxy server [https://galaxy.ansible.com/api/.](https://galaxy.ansible.com/api/) Got an
unexpected error when getting available versions of collection
containers.podman: Unknown error when attempting to call Galaxy at 'https://gal
axy.ansible.com/api/v2/collections/containers/podman/versions/?page_size=100':
The read operation timed out
ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/v2/collections/containers/podman/versions/?page_size=100': The read operation timed out
```

**Comment by fnzv** [comment]
Same issue here, from multiple locations i get:
`$ ansible-galaxy collection install community.vmware


Process install dependency map
|
-
ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/v2/collections/community/vmware/versions/?page=2': The read operation timed out`

**Comment by hangrum** [comment]
AWX Operation here.. help me
`{
  "changed": false,
  "stdout": "Starting galaxy collection install process\nProcess install dependency map\nStarting collection install process\nDownloading https://galaxy.ansible.com/download/amazon-aws-3.1.1.tar.gz to /var/lib/awx/projects/.__awx_cache/_15__penny_v2_0442_pm/stage/tmp/ansible-local-44765ld8c3fe/tmp06_ug1qd/amazon-aws-3.1.1-f5fc_23j\nto see the full traceback, use -vvv",
  "stderr": "ERROR! Unexpected Exception, this is probably a bug: The read operation timed out",
  "rc": 250,
  "cmd": [
    "ansible-galaxy",
    "collection",
    "install",
    "-r",
    "/var/lib/awx/projects/_15__penny_v2_0442_pm/collections/requirements.yml",
    "--collections-path",
    "/var/lib/awx/projects/.__awx_cache/_15__penny_v2_0442_pm/stage/requirements_collections"
  ],
  "start": "2022-02-22 07:53:04.590575",
  "end": "2022-02-22 07:53:16.814724",
  "delta": "0:00:12.224149",
  "msg": "non-zero return code",
  "invocation": {
    "module_args": {
      "chdir": "/var/lib/awx/projects/_15__penny_v2_0442_pm",
      "_raw_params": "ansible-galaxy collection install -r /var/lib/awx/projects/_15__penny_v2_0442_pm/collections/requirements.yml --collections-path /var/lib/awx/projects/.__awx_cache/_15__penny_v2_0442_pm/stage/requirements_collections \n",
      "_uses_shell": false,
      "warn": false,
      "stdin_add_newline": true,
      "strip_empty_ends": true,
      "argv": null,
      "executable": null,
      "creates": null,
      "removes": null,
      "stdin": null
    }
  },
  "stdout_lines": [
    "Starting galaxy collection install process",
    "Process install dependency map",
    "Starting collection install process",
    "Downloading https://galaxy.ansible.com/download/amazon-aws-3.1.1.tar.gz to /var/lib/awx/projects/.__awx_cache/_15__penny_v2_0442_pm/stage/tmp/ansible-local-44765ld8c3fe/tmp06_ug1qd/amazon-aws-3.1.1-f5fc_23j",
    "to see the full traceback, use -vvv"
  ],
  "stderr_lines": [
    "ERROR! Unexpected Exception, this is probably a bug: The read operation timed out"
  ],
  "_ansible_no_log": false,
  "item": "/var/lib/awx/projects/_15__penny_v2_0442_pm/collections/requirements.yml",
  "ansible_loop_var": "item",
  "_ansible_item_label": "/var/lib/awx/projects/_15__penny_v2_0442_pm/collections/requirements.yml"
}`

**Comment by bbethell-1** [comment]
Its stilll down here, does anyone have an update or ETA? Cheers

**Comment by itbane** [comment]
Same here. From multiple locations (all inside Germany). Requests break at different stages though, so I think the API has a number of dead backends behind their loadbalancing.

Sometimes it even works.

```
ansible-galaxy 2.10.8
  config file = None
  configured module search path = [~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible-galaxy
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
No config file found; using defaults
Reading requirement file at 'requirements.yaml'
Starting galaxy collection install process
Process install dependency map
Initial connection to galaxy_server: https://galaxy.ansible.com
Opened ~/.ansible/galaxy_token
Calling Galaxy at https://galaxy.ansible.com/api/
Processing requirement collection 'ansible.posix'
Collection requirement 'ansible.posix' is the name of a collection
Found API version 'v1, v2' with Galaxy server default (https://galaxy.ansible.com/api/)
Calling Galaxy at https://galaxy.ansible.com/api/v2/collections/ansible/posix/versions/
ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/v2/collections/ansible/posix/versions/': The read operation timed out
```

On another machine:

```
$ ansible-galaxy collection install -r requirements.yaml -vvvvv
ansible-galaxy 2.10.8
  config file = None
  configured module search path = [~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible-galaxy
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
No config file found; using defaults
Reading requirement file at 'requirements.yaml'
Starting galaxy collection install process
Process install dependency map
Initial connection to galaxy_server: https://galaxy.ansible.com
Opened ~/.ansible/galaxy_token
Calling Galaxy at https://galaxy.ansible.com/api/
Processing requirement collection 'ansible.posix'
Collection requirement 'ansible.posix' is the name of a collection
Found API version 'v1, v2' with Galaxy server default (https://galaxy.ansible.com/api/)
Calling Galaxy at https://galaxy.ansible.com/api/v2/collections/ansible/posix/versions/
Calling Galaxy at https://galaxy.ansible.com/api/v2/collections/ansible/posix/versions/?page=2
ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/v2/collections/ansible/posix/versions/?page=2': The read operation timed out
```

**Comment by falsedlah** [comment]
Also down, France.

**Comment by siliconsheep** [comment]
Same for Belgium

**Comment by kyrogue** [comment]
Down, Singapore

**Comment by Slm0n87** [comment]
Same from Germany - and I guess from Moon, too.

**Comment by gianmarco-mameli** [comment]
Same from Italy, thanks

**Comment by bjordanov4** [comment]
Same from Bulgaria. Does anyone knows what is expected resolution time?

**Comment by ael-p** [comment]
> Same from Bulgaria. Does anyone knows what is expected resolution time?

@bjordanov4 There is an issue opened : #https://github.com/ansible/galaxy/issues/2891

**Comment by ael-p** [comment]
Seems resolved.

**Comment by falsedlah** [comment]
work on my side, France

**Comment by TimofeyBiryukov** [comment]
Apperas to be working now.

**Comment by raskallen** [comment]
It kinda works, yes. It takes a very long time, but at least it doesn't time out. 1m 23 seconds for downlading 858K is quite slow.

```
xxx@xxx:~$ time ansible-galaxy collection download community.vmware
Process install dependency map
Starting collection download process to '/home/xxx/collections'
Downloading collection 'community.vmware' to '/home/xxx/collections/community-vmware-2.1.0.tar.gz'
Downloading https://galaxy.ansible.com/download/community-vmware-2.1.0.tar.gz to /home/xxx/.ansible/tmp/ansible-local-673552rc8y3uu3/tmpxwouhbo5
community.vmware (2.1.0) was downloaded successfully
Writing requirements.yml file of downloaded collections to '/home/xxx/collections/requirements.yml'

real	1m23,127s
user	0m0,894s
sys	0m0,129s
```

**Comment by bbethell-1** [comment]
Please can you create a statuspage for Galaxy?
