### ISSUE TITLE
Namespace Request: opennetworkingfoundation

### ISSUE THREAD

**Issue by zdw** [ansible/galaxy#2893]
## Namespace Request
Namespace: `onf`

(or if not available, `opennetworkingfoundation`

##### Description
Open Networking Foundation

Roles created by https://opennetworking.org/

##### GitHub Org Link
https://github.com/opennetworkingfoundation

##### Admins
zdw

**Comment by thedoubl3j** [comment]
done @zdw namespace is `onf`
