### ISSUE TITLE
New organization namespace

### ISSUE THREAD

**Issue by raffael-mnhn** [ansible/galaxy#2897]
## Namespace Request
Namespace: MnhnL

##### Description
Musée National d'Histoire Naturelle

##### GitHub Org Link
[](https://github.com/MnhnL)

##### Admins
raffael.mancini@mnhn.lu

**Comment by alisonlhart** [comment]
@raffael-mnhn Galaxy requires Pythonic names for namespaces, so we will need to change the namespace to: **mnhnL** or **mnhnl**
Please let me know which would be acceptable.

**Comment by raffael-mnhn** [comment]
mnhnl is good. Thanks @alisonlhart

**Comment by alisonlhart** [comment]
@raffael-mnhn All we need now is a link to the github repository for the project, so I can also add that to the namespace.

**Comment by raffael-mnhn** [comment]
@alisonlhart https://github.com/MnhnL/ansible-collection-sidpnat there you go. Thanks for your help so far
