### ISSUE TITLE
Create 'cdillc' namespace

### ISSUE THREAD

**Issue by lowell80** [ansible/galaxy#2899]
## Namespace Request
Namespace:  cdillc

##### Description
Computer Design and Integration, LLC

##### GitHub Org Link
https://github.com/cdillc

##### Admins

* lowell80
* ljonsson
* brian-kennedy (galaxy user not confirmed yet)

**Comment by alisonlhart** [comment]
Namespace cdillc created with admins lowell80 and ljonsson . Please let me know if an additional user needs to be added (after they authenticate to galaxy at least once).

**Comment by lowell80** [comment]
Looks like we can add another user to the org later (once they sign in), right?   Assuming that's true we can close this out.

Thanks for the amazing turn around time!

**Comment by lowell80** [comment]
oh, can we set a logo set to match the GiHub logo?

**Comment by alisonlhart** [comment]
@lowell80 Yes, we can set that up! And now that the namespace is created, you can edit your own namespace at any time if you want to update the logo or add additional members. But if you prefer, I can add the logo for you now.

**Comment by lowell80** [comment]
@alisonlhart, ah okay I found the page where I can edit.  I've taken care of it.

Thanks so much!
