### ISSUE TITLE
Add OracleLinux and OVS to the list of platforms

### ISSUE THREAD

**Issue by zdudic** [ansible/galaxy#2902]
### Use Case
1. "Oracle Linux" is missing from the list of platforms (https://www.oracle.com/linux)
2. "Oracle VM Server"  is missing from the list of platforms (https://en.wikipedia.org/wiki/Oracle_VM_Server_for_x86)

### Proposed Solution
Please add these two to the list of platforms. 

Name: OracleLinux
Versions: 5, 6, 7, 8

Name: OVS
Versions: 3 

### Alternatives
N/A

### Implementation
N/A

**Comment by zdudic** [comment]
Hi there, I hope there is no any obstacle for this to be resolved. Thanks in advance.

**Comment by alisonlhart** [comment]
Platforms added:
OracleLinux: https://galaxy.ansible.com/api/v1/platforms/?search=OracleLinux
OVS: https://galaxy.ansible.com/api/v1/platforms/?search=OVS
