### ISSUE TITLE
Add version 11.4 for platform Solaris

### ISSUE THREAD

**Issue by zdudic** [ansible/galaxy#2903]
### Use Case
Platform Solaris is missing version 11.4

### Proposed Solution
Add version 11.4 for platform Solaris

### Alternatives
N/A

### Implementation
N/A

**Comment by zdudic** [comment]
Hi there, I hope there is no any obstacle for this to be resolved. Thanks in advance.

**Comment by alisonlhart** [comment]
Version added: https://galaxy.ansible.com/api/v1/platforms/262/
