### ISSUE TITLE
Request for Namespace Icinga

### ISSUE THREAD

**Issue by bobapple** [ansible/galaxy#2906]
## Namespace Request
Namespace: Icinga

##### Description
Collections to setup and manage components of the Icinga software stack

##### GitHub Org Link
https://github.com/icinga

##### Admins
* bobapple: https://galaxy.ansible.com/bobapple
* mkayontour: https://galaxy.ansible.com/mkayontour

**Comment by alisonlhart** [comment]
@bobapple Do you have any concerns with changing the name to lowercase-I "icinga"? Galaxy requires namespace names adhere to Pythonic variable conventions.

**Comment by bobapple** [comment]
@bobapple nope, I'm fine with the lowercase :thumbsup:

**Comment by alisonlhart** [comment]
@bobapple It looks like "icinga" is already taken, as well as "icingaadmin". Is there an alternative name we can create it with?

**Comment by bobapple** [comment]
@alisonlhart not really, we would prefer the "icinga" namespace since it matches the organization name on GitHub and everywhere else (like Docker Hub, Puppet Forge, Chef Supermarket)

Is there any way to take over the existing "icinga" namespace? There's no GitHub user attached to that, since it's an organization

**Comment by alisonlhart** [comment]
Actually, I see both @widhalmt and @gethash are part of the github icinga organization and they're currently the namespace owners. If I could get confirmation from one of them, we can just add you and mkayontour to it and add the modifications.

**Comment by bobapple** [comment]
I see! That should be possible.

@gethash could you please confirm?

**Comment by alisonlhart** [comment]
Thank you! Namespace has been modified to include the description and URL specified and bobapple and mkayontour have been added as owners. https://galaxy.ansible.com/icinga

**Comment by alisonlhart** [comment]
Closing issue as resolved. If there's anything we need to modify, we can reopen at any time.

**Comment by bobapple** [comment]
Thanks a lot @alisonlhart !
