### ISSUE TITLE
Requesting Galaxy Namespace `stolostron`

### ISSUE THREAD

**Issue by nathanweatherly** [ansible/galaxy#2907]
## Namespace Request
Namespace: stolostron

##### Description

`(stolos = fleet, tron = tool)`

^ Question-- is that editable after initiation?

##### GitHub Org Link

`https://github.com/stolostron`

##### Admins

nathanweatherly (me)
hanqiuzh
tphee
TheRealHaoLiu

**Comment by alisonlhart** [comment]
@nathanweatherly We try not to update namespace names once they're created. Usually at that point, we create a new namespace and recommend migrating the content. Are there any changes you want to make before we create the **stolostron** namespace?

**Comment by alisonlhart** [comment]
@nathanweatherly I just realized, I think your question was directed towards the description of the namespace and not the name. Namespace descriptions can be updated at any time. Namespace has been created: https://galaxy.ansible.com/stolostron

**Comment by nathanweatherly** [comment]
Hot stuff! Thanks Alison!
