### ISSUE TITLE
Requesting Galaxy Namespace `VictoriaMetrics`

### ISSUE THREAD

**Issue by denisgolius** [ansible/galaxy#2908]
## Namespace Request
**Namespace:** victoriametrics

##### Description
Ansible roles for installing and configuring **VictoriaMetrics** time series database and tools

##### GitHub Org Link
https://github.com/VictoriaMetrics

##### Admins:
* denisgolius (me)
* tenmozes

**Comment by alisonlhart** [comment]
@denisgolius Namespace names need to follow pythonic variable naming conventions. Are there any objections to lowercasing the name to: victoriametrics or victoriaMetrics?

**Comment by denisgolius** [comment]
> @denisgolius Namespace names need to follow pythonic variable naming conventions. Are there any objections to lowercasing the name to: victoriametrics or victoriaMetrics?

Hi @alisonlhart !
I've edited request and applied your suggestions. We will use **victoriametrics**.

**Comment by alisonlhart** [comment]
Great. Namespace has been created: https://galaxy.ansible.com/victoriametrics
