### ISSUE TITLE
Verify Galaxy correctly handles imports triggered by TravisCI

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#291]
As an Author, I want changes pushed to GitHub to be automatically imported

- [x] Test that our Webhook endpoint works as expected, and triggers an import
- [x] Review our signature verification process, and insure that it's up to date with latest [Travis docs](https://docs.travis-ci.com/user/notifications/#Verifying-Webhook-requests).

**Comment by chouseknecht** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Review Travis webhook signature verification](https://trello.com/c/sfKM46HG/20-review-travis-webhook-signature-verification)

**Comment by chouseknecht** [comment]
Assuming that since we haven't tested this at all under v3.0, it's most likely broken.

**Comment by cutwater** [comment]
@chouseknecht Can you please clarify expected behavior of webhook handler:

1. If it's triggered for non-existing repository, should repository be created?
2. If repository should be created, to which namespace it should belong? User default namespace?

**Comment by cutwater** [comment]
>  Review our signature verification process, and insure that it's up to date with latest Travis docs.
Based to the Travis CI docs and sample implementation, our signature verification process corresponds to actual process used by Travis CI.
