### ISSUE TITLE
namespace: whiletruedoio (problem handling)

### ISSUE THREAD

**Issue by dschier-wtd** [ansible/galaxy#2929]
## Namespace Request
Namespace: whiletruedoio

##### Description

I requested a change of my namespace in #2837 and it was handled fast. Thank you for this.
Today, I wanted to start uploading new roles and collections, but identified an issue.

If I am opening the "Add content" dialog, I have the choice between dschiert-wtd and while-true-do.

The first one is my personal workspace, the second one is the old one. The new workspace for this namespace is located at
https://github.com/whiletruedoio and not https://github.com/while-true-do.

Is there any chance to fix this?

##### GitHub Org Link

https://github.com/whiletruedoio

##### Admins

Here comes another situation. The current user is daniel-wtd, which is linked to the GitHub handle dschier-wtd. If by any mean possible, I would love to fix the Ansible name, too. I am also not able to change my e-mail address, due to #2833 and #2822.

I am also open for any other way (including complete reset/deletion and recreation of my user and the linked organization) to fix this situation. :)

Thank you, a lot, for your support and the effort you are putting into galaxy.

Best regards,
Daniel

**Comment by alisonlhart** [comment]
@dschier-wtd Hello Daniel! The namespace URL appears to have been changed to https://github.com/whiletruedoio already. Were you able to edit this? Let me know if it still isn't linking to the desired workspace in the way you expect. 

As for the username: there is unfortunately no current way to update usernames for galaxy after OAuth through Github. There have been rare occasions that users from Galaxy have been deleted, but typically users would unlink from Github and leave it at that. I'm unsure if there's an efficient way to do this at the moment without causing database chaos. 

I will poke the galaxy team and see if there's any movement on #2822 as well.

**Comment by dschier-wtd** [comment]
Hello @alisonlhart the "website" field is changed, yes. But the "Provider Namespace" only includes the old organization (which still exists).

![Screenshot 2022-05-17 at 20-04-10 Ansible Galaxy](https://user-images.githubusercontent.com/6490538/168880407-06ffeb4a-60fd-4c78-93e9-2badac60f4d7.png)

In my initial request, I hoped that the old provider namespace can be removed and pointing to the new one.

- old provider namespace: github.com/while-true-do
- new provider namespace: github.com/whiletruedoio

Do you see a chance to fix this?

Thank you for the superfast reply. I really appreciate it :)

**Comment by alisonlhart** [comment]
@dschier-wtd My mistake, I misunderstood the ask. Galaxy should pull any organization that you're a member of and offer them in the available namespace selection. I can see you're a public member on the while-true-do organization but I can't see you on the whiletruedoio organization. Can you add your dschier-wtd account to the People in that organization and check to see if you can then add it as a provider namespace?

**Comment by dschier-wtd** [comment]
I see, the visibility of my user was set to "private" (whoever decided that this is a nice default ^^).
I have updated the visibility to public, but cannot see this (or other) public organizations that I am part of. 

That brought me to: "I may have limited the oAuth token", which finally solved the situation. After granting Ansible Galaxy access to the organization, I can choose it as a provider.

Sorry for the inconvenience and thank you a ton for your support. Your hint brought the solution :)

**Comment by dschier-wtd** [comment]
Thank you again. I hope it is ok to close the issue.

Awesome support, really. :heart:

**Comment by alisonlhart** [comment]
Great! I'm glad that was the fix. Happy to help with any other future requests. :)
