### ISSUE TITLE
Requesting "wayofdev" namespace

### ISSUE THREAD

**Issue by lotyp** [ansible/galaxy#2931]
## Namespace Request
Namespace: wayofdev

##### Description
Making things to build better software.

##### GitHub Org Link
[wayofdev](https://github.com/wayofdev)

##### Admins
@lotyp

Currently tried all variants to get my roles to be published under my organization namespace, and looks like it is not possible? Always I'm getting all my roles under my default username "lotyp"

Screenshot for example, how my content page looks like:

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/94047334/169355885-4c73a296-5cdf-41f2-b744-4ca09b340f92.png">

So, please, create new namespace for me!

Thanks!

**Comment by alisonlhart** [comment]
Namespace created: https://galaxy.ansible.com/wayofdev
