### ISSUE TITLE
Namespace Request

### ISSUE THREAD

**Issue by eb37** [ansible/galaxy#2933]
## Namespace Request
Namespace: eb

##### Description
Various Ansible collections for home IT automation

##### GitHub Org Link
[https://github.com/eb37](https://github.com/eb37)

##### Admins
eb37

**Comment by alisonlhart** [comment]
@eb37 Please provide a longer namespace name. Galaxy does not accept namespace names of 2 characters or less.

**Comment by eb37** [comment]
@alisonlhart The [documentation](https://galaxy.ansible.com/docs/contributing/namespaces.html#galaxy-namespace-limitations) says:

> Namespace names in Galaxy are limited to lowercase word characters (i.e., a-z, 0-9) and ‘_’, must have a minimum length of 2 characters [...]

According to this clause, the namespace `eb` should be fine unless it has been reserved already.

**Comment by JohnLieske** [comment]
Closing this request because an alternative was not requested
