### ISSUE TITLE
Error on default namespace name dclement-dawan

### ISSUE THREAD

**Issue by dclement-dawan** [ansible/galaxy#2934]
## Namespace Request
Namespace: dclement

##### Description
My default namespace name contains an hyphen : dclement-dawan

So I cant publish : 

ansible-galaxy collection publish --token xxxxxxxxxx  dclement-dawan-common-1.0.0.tar.gz
Publishing collection artifact '/home/david/ansible/ansible_collections/dclement-dawan-common-1.0.0.tar.gz' to default https://galaxy.ansible.com/api/
ERROR! Error when publishing collection to default (https://galaxy.ansible.com/api/) (HTTP Code: 400, Message: Invalid version string: 'common-1.0.0' Code: invalid)

##### Admins
dclement-dawan

Thank you.

**Comment by alisonlhart** [comment]
Namespace created: https://galaxy.ansible.com/dclement
