### ISSUE TITLE
Please add `kustosz` namespace

### ISSUE THREAD

**Issue by mirekdlugosz** [ansible/galaxy#2936]
## Namespace Request
Namespace: `kustosz`

##### Description
Focus on the worthwhile content with Kustosz, open source self-hosted web application.

##### GitHub Org Link
https://github.com/KustoszApp

##### Admins

- `mirekdlugosz`

**Comment by alisonlhart** [comment]
Namespace created: https://galaxy.ansible.com/kustosz

**Comment by mirekdlugosz** [comment]
Thank you, @alisonlhart !
