### ISSUE TITLE
Verification email not sent

### ISSUE THREAD

**Issue by federico-razzoli** [ansible/galaxy#2942]
##### SUMMARY
My emails are not verified because I don't receive any verification email.

Before you ask, I checked spam folders and I know that my emails work normally.

##### STEPS TO REPRODUCE

Go to Preferences, click Resend Verification.

##### EXPECTED RESULTS
An email should be sent.

##### ACTUAL RESULTS
I'm told that an email has been sent but it's not true.

**Comment by Tony-Sol** [comment]
Duplicates https://github.com/ansible/galaxy/issues/2775

**Comment by alisonlhart** [comment]
Refer to #2775 - issue has been closed and reported to be fixed.
