### ISSUE TITLE
namespace: skriptfabrik

### ISSUE THREAD

**Issue by FrankGiesecke** [ansible/galaxy#2944]
## Namespace Request
Namespace: skriptfabrik

##### Description
Ansible Roles and Collections provided by skriptfabrik GmbH

##### GitHub Org Link
https://github.com/skriptfabrik

##### Admins
- @FrankGiesecke
- @schroedan

**Comment by JohnLieske** [comment]
namespace created: https://galaxy.ansible.com/skriptfabrik

Admins added:
* @FrankGiesecke
* @schroedan
