### ISSUE TITLE
New namespace NeowayLabs

### ISSUE THREAD

**Issue by marcelokkruger** [ansible/galaxy#2945]
## Namespace Request
Namespace: NeowayLabs

##### Description
NeowayLabs was created by the company Neoway to promote open source to the community

##### GitHub Org Link
https://github.com/NeowayLabs

##### Admins
[marcelokkruger](https://github.com/marcelokkruger)

**Comment by JohnLieske** [comment]
I'm sorry but that namespace already exists. Do you have a backup name request?

**Comment by JohnLieske** [comment]
Hi @marcelokkruger ,

These namespaces are public community requests. This means the namespace was requested already & provided to the requester. Might this request already have been made by you, or from another account of yours? The GH account for the previous maintainer (https://github.com/drrzmr) is no longer available, are you a new maintainer/contributor for the provider namespace (https://github.com/NeowayLabs)?

**Comment by JohnLieske** [comment]
Closing for lack of responses
