### ISSUE TITLE
ansible-galaxy timeout error

### ISSUE THREAD

**Issue by anilkumar0611** [ansible/galaxy#2947]
[WARNING]: Skipping Galaxy server https://galaxy.ansible.com/api/. Got an
unexpected error when getting available versions of collection
community.general: Unknown error when attempting to call Galaxy at 'https://gal
axy.ansible.com/api/v2/collections/community/general/versions/?page_size=100':
The read operation timed out
ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/v2/collections/community/general/versions/?page_size=100': The read operation timed out

**Comment by thedoubl3j** [comment]
hey @anilkumar0611 this repo is for the site that is galaxy.ansible.com, ansible-galaxy (the command line tool) support and issues should be opened on [ansible/ansible](https://github.com/ansible/ansible)
