### ISSUE TITLE
Namespace Request - entropygraph

### ISSUE THREAD

**Issue by tyler-smith** [ansible/galaxy#2950]
## Namespace Request
Namespace: `entropygraph`

##### Description
Various Ansible resources created by my company, [EntropyGraph](https://entropygra.ph).

##### GitHub Org Link
https://github.com/entropygraph

##### Admins
- tyler-smith (https://galaxy.ansible.com/tyler-smith)

**Comment by alisonlhart** [comment]
Namespace created: https://galaxy.ansible.com/entropygraph
