### ISSUE TITLE
Namespace missing provider namespaces

### ISSUE THREAD

**Issue by SRv6d** [ansible/galaxy#2953]
##### SUMMARY
Namespace `initq`with GitHub org link https://github.com/iq-ltd was assigned in #2937, but missing provider namespace within
galaxy.

##### STEPS TO REPRODUCE

- Login to Galaxy
- Navigate to "My Content"
- Click "Add Content"

##### EXPECTED RESULTS

Be able to import roles / collections from org repositories.

##### ACTUAL RESULTS

![](https://user-images.githubusercontent.com/18124752/173201297-0e46d33c-aa58-41f7-a80c-35b5b2a60f1a.png)
![](https://user-images.githubusercontent.com/18124752/173201286-f4f6eb40-89d8-4416-bc90-2eba0b05a963.png)

```

```

**Comment by alisonlhart** [comment]
@SRv6d Is your SRv6d account added as a member of the [iq-ltd](https://github.com/iq-ltd) organization? Galaxy should automatically pull all organizations you're a member of and list them as a provider namespace.

**Comment by thedoubl3j** [comment]
Galaxy will also need permission to do that so if you didn't grant it permission, then it can't see the organizations.

**Comment by SRv6d** [comment]
@alisonlhart [Yes](https://github.com/orgs/iq-ltd/people).
@thedoubl3j Is this what you are talking about ?
<img width="969" alt="Screenshot 2022-06-21 at 14 05 47" src="https://user-images.githubusercontent.com/18124752/174795113-c14395fb-6e88-49c0-ab97-9afdb72a1487.png">
If yes, how do I trigger an access request ?

**Comment by thedoubl3j** [comment]
@SRv6d that is it, docs here https://galaxy.ansible.com/docs/contributing/importing.html#updating-github-permissions should help I think.
