### ISSUE TITLE
Namespace request: cloudstruct

### ISSUE THREAD

**Issue by agaffney** [ansible/galaxy#2956]
## Namespace Request
Namespace: `cloudstruct`

##### Description
`CloudStruct`

##### GitHub Org Link
https://github.com/cloudstruct

##### Admins
`agaffney` (and the same on `galaxy-dev.ansible.com`)

**Comment by alisonlhart** [comment]
@agaffney Namespace on Galaxy created: https://galaxy.ansible.com/cloudstruct

Just to double check, you want the same namespace specs for a cloudstruct namespace on galaxy-dev?

**Comment by agaffney** [comment]
Correct

**Comment by alisonlhart** [comment]
Here is the galaxy-dev namespace. https://galaxy-dev.ansible.com/cloudstruct
