### ISSUE TITLE
Access/recover organisation namespace?

### ISSUE THREAD

**Issue by joelnb** [ansible/galaxy#2961]
I am part of the organisation https://github.com/caddy-ansible on github and recently created a new release in the main role repository https://github.com/caddy-ansible/caddy-ansible/releases/tag/v3.1.0 which is the repo for this role https://galaxy.ansible.com/caddy_ansible/caddy_ansible but this release has not been picked up by ansible-galaxy. Previously when I have made github releases they have always been picked up there without me needing to do anything.

I do not know who has access on the ansible-galaxy side & even if I did I would probably not have a way to contact them. Is there anything I can do to recover the namespace? I don't seem able to create a new namespace on ansible-galaxy for the https://github.com/caddy-ansible organisation because it can correctly see that a namespace already exist for that organisation:

![2022-06-30-19-35-19](https://user-images.githubusercontent.com/6627979/176752754-d2ab7014-0798-45ca-a154-3dbdfe3da68c.png)

This means that just updating the README and publishing the role under a new namespace does not seem to be an option.

**Comment by joelnb** [comment]
Apologies if I have submitted this incorrectly - I originally selected a namespace request but decided that was probably wrong because it is not a new namespace & intended to submit as a general request. Can't find any way to change that now.

**Comment by joelnb** [comment]
The original namespace request seems to be here which does list me as an admin but I don't seem to have any access to it.

https://github.com/ansible/galaxy/issues/2096

**Comment by alisonlhart** [comment]
@joelnb It looks like you already have admin access to the caddy-ansible namespace. I tried resetting your permissions and saving them again. Can you attempt to access/edit the namespace now?

**Comment by joelnb** [comment]
Thanks, that seems to have worked - previously I could not see the namespace on https://galaxy.ansible.com/my-content/namespaces but it is there now and I was able to force an import on it (although one had automatically run and published the new version in the meantime). Appreciate your help!
