### ISSUE TITLE
Namespace Request

### ISSUE THREAD

**Issue by ScriptyMcJankerton** [ansible/galaxy#2963]
## Namespace Request
Namespace: terranimbus

##### Description

Hello, may I please request being granted the namespace "terranimbus" in Galaxy? Thank you!

##### GitHub Org Link

https://github.com/terranimbus-inc

##### Admins

scriptymcjankerton
terranimbus

**Comment by JohnLieske** [comment]
The namespace already exists, with the user @terranimbus already as an admin. The user terranimbus can add you as an admin by going to My Content, clicking the three dots at the right of the namespace, then selecting 'Edit Properties'.
