### ISSUE TITLE
gurisitx namespace

### ISSUE THREAD

**Issue by ulvida** [ansible/galaxy#2965]
## Namespace Request
Namespace: gurisitx

##### Description
gurisito.uy team's developments 

##### GitHub Org Link
https://github.com/Gurisitx

##### Admins
ulvida

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/gurisitx

Admin added:
@ulvida

**Comment by ulvida** [comment]
Hello again, @JohnLieske. 

Sorry to bother if I am missing a step, but I don't see `gurisitx` namespace in "My contents", when logged in in Ansible Galaxy, as I see for other namespaces I manage.
