### ISSUE TITLE
namespace: MGDIS

### ISSUE THREAD

**Issue by github-mgdis** [ansible/galaxy#2966]
## Namespace Request
Namespace: MGDIS

##### Description
MGDIS - SRE and Development teams

##### GitHub Org Link
https://github.com/MGDIS

##### Admins
github-mgdis
Laricchi

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/mgdis

Admins added:
* @github-mgdis 
* @Laricchi
