### ISSUE TITLE
Create ansible_26lights namespace

### ISSUE THREAD

**Issue by gdacier2** [ansible/galaxy#2967]
## Namespace Request
Namespace: ansible_26lights

##### Description
Namespace used to store 26lights collections

##### GitHub Org Link
https://github.com/orgs/26lights/repositories

##### Admins
gdacier2, renaudlenne,oleastre

Will it be possible to change the admins once the namespace is created?

**Comment by thedoubl3j** [comment]
@gdacier2 yes, admins can change. We can change them or other admins can change them as well.

**Comment by thedoubl3j** [comment]
namespace was created, however these 2 users were not found `renaudlenne` `oleastre` @gdacier2
