### ISSUE TITLE
cielito galaxy namespce

### ISSUE THREAD

**Issue by ulvida** [ansible/galaxy#2968]
## Namespace Request
Namespace: cielito

##### Description
Namespace to migrate to collections the roles we presently maintain under UdelaRInterior namespace, to have an identity separated of our University. Eventually we own the cielito.uy domain as a web of the project and our instances using it.   

##### GitHub Org Link
https://github.com/udelarinterior/

##### Admins
@ulvida
@santiagomr

**Comment by thedoubl3j** [comment]
@ulvida done :)

**Comment by ulvida** [comment]
Thank you very much!
