### ISSUE TITLE
Namespace Request 

### ISSUE THREAD

**Issue by tybrann** [ansible/galaxy#2969]
## Namespace Request
Namespace:  delinea

##### Description

delinea

##### GitHub Org Link

https://github.com/DelineaXPM

##### Admins

tybrann
sheldonhull

[List_GalaxyUsers.txt](https://github.com/ansible/galaxy/files/9133987/List_GalaxyUsers.txt)

**Comment by thedoubl3j** [comment]
@tybrann mind listing those users in a comment please rather in a downloadable file

**Comment by tybrann** [comment]
@thedoubl3j  Let me know if there is anything else I need to do in order to have this namespace created. Thx!

**Comment by thedoubl3j** [comment]
nothing else needed, just time on my part @tybrann namespace created  https://galaxy.ansible.com/delinea

**Comment by tybrann** [comment]
Thank you!
