### ISSUE TITLE
Galaxy namespace request : datarsense

### ISSUE THREAD

**Issue by matt6697** [ansible/galaxy#2970]
## Namespace Request
Namespace: datarsense

##### GitHub Org Link
Link : [ https://github.com/datarsense/](https://github.com/datarsense/)

##### Admins
Admin : https://galaxy.ansible.com/matt6697/

**Comment by matt6697** [comment]
Is something blocking this namespace request ?

**Comment by JohnLieske** [comment]
This process isn't automatic, and you didn't include a description (which is required).

Namespace created: https://galaxy.ansible.com/datarsense

Admin added:
* @matt6697
