### ISSUE TITLE
Namespace creation request

### ISSUE THREAD

**Issue by dz-stormpay** [ansible/galaxy#2973]
## Namespace Request
Namespace: paystorm

##### Description
https://stormpay.io/about-us

##### GitHub Org Link
https://github.com/paystorm

##### Admins
dz-stormpay
zubarevich

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/paystorm

Admins added:
* @dz-stormpay 
* @zubarevich
