### ISSUE TITLE
Namespace creation request: maxbytes

### ISSUE THREAD

**Issue by maximiliancsuk** [ansible/galaxy#2974]
## Namespace Request
Namespace: maxbytes

##### Description
[https://max-bytes.com](https://max-bytes.com)

##### GitHub Org Link
[https://github.com/max-bytes](https://github.com/max-bytes)

##### Admins
maximiliancsuk

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/maxbytes

Admin added:
* @maximiliancsuk
