### ISSUE TITLE
namespace: companieshouse

### ISSUE THREAD

**Issue by marcransome** [ansible/galaxy#2978]
## Namespace Request
Namespace: companieshouse

##### Description
UK registrar of companies

##### GitHub Org Link
https://github.com/companieshouse

##### Admins
[marcransome](https://galaxy.ansible.com/marcransome)

**Comment by JohnLieske** [comment]
Namespace created:
    https://galaxy.ansible.com/companieshouse

Admin added:
* @marcransome
