### ISSUE TITLE
Galaxy importer hangs on collection import

### ISSUE THREAD

**Issue by sylvainmetayer** [ansible/galaxy#2980]
SUMMARY

Import of a new version of a collection hangs at "waiting" step.

STEPS TO REPRODUCE

Import a new version of a collection from the galaxy command line

EXPECTED RESULTS

Import would complete successfully

ACTUAL RESULTS

namespace: sylvainmetayer
collection: workstation

current output:

Nothing, just a waiting loader which never ends.

Their is no way to cancel the operation, which seems to blocks other builds. Could you remove my running builds please ?

**Comment by BaculaSystems** [comment]
I'm also facing this issue when I tried to publish a new collection.

Any news on this topic?

Thank you very much!

**Comment by BaculaSystems** [comment]
After some time, the import failed with an error message. It just took too long to finish.

**Comment by sylvainmetayer** [comment]
I've had the same results, after 1 day, the import failed with an error message.
