### ISSUE TITLE
namespace: no admin of "gurisitx" namespace. 

### ISSUE THREAD

**Issue by ulvida** [ansible/galaxy#2982]
I requested gurisitx namespace in issue #2965. 

@JohnLieske created [the namespace](https://galaxy.ansible.com/gurisitx) and said [I was added as admin](https://github.com/ansible/galaxy/issues/2965#issuecomment-1183503576), but I can't see the namespace gurisitx in "My contents" logged in into Ansible Galaxy.

Am I missing a step?

If not, could you check my username @ulvida is set as admin of [the namespace gurisitx](https://galaxy.ansible.com/gurisitx)? 

Thanks in advance.

**Comment by thedoubl3j** [comment]
@ulvida check it for me now

**Comment by ulvida** [comment]
Now I see it. Thank you very much, @thedoubl3j !
