### ISSUE TITLE
Add adshares namespace

### ISSUE THREAD

**Issue by m-pilarczyk** [ansible/galaxy#2983]
## Namespace Request
Namespace: adshares

##### Description
Blockchain in adtech.

##### GitHub Org Link
https://github.com/adshares

##### Admins
m-pilarczyk

**Comment by JohnLieske** [comment]
Namespace added:
https://galaxy.ansible.com/adshares

Admin added:
* @m-pilarczyk

**Comment by m-pilarczyk** [comment]
thanks a lot!
