### ISSUE TITLE
Create a namespace `grafana`

### ISSUE THREAD

**Issue by ishanjainn** [ansible/galaxy#2984]
## Namespace Request
Namespace: grafana

##### Description
Namespace to be used for publishing Grafana's Ansible collection

##### GitHub Org Link
https://github.com/grafana

##### Admins
Ishan Jain - ishanjainn

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/grafana

Admin added:
* @ishanjainn

**Comment by ishanjainn** [comment]
Thanks for sharing

I have been developing the the tests as required for the collection to be included in the community package.
I have been facing an issue 
```shell
ERROR: Output on stderr from ansible-doc is considered an error.
```
You can find it [here](https://github.com/grafana/grafana-ansible-collection/runs/7832908754?check_suite_focus=true#step:6:140)

At the end of the GitHub Action its says the error is due to 
```shell
FATAL: Command "docker exec ansible-test-controller-9T16Qvpc /usr/bin/env ANSIBLE_TEST_CONTENT_ROOT=/root/ansible_collections/grafana/grafana LC_ALL=en_US.UTF-8 /usr/bin/python3.10 /root/ansible/bin/ansible-test sanity -v --containers '{}' --coverage --truncate 0 --color yes --host-path tests/output/.tmp/host-h96ltluu --metadata tests/output/.tmp/metadata-zfsalxse.json" returned exit status 1.
```
You can find it [here](https://github.com/grafana/grafana-ansible-collection/runs/7832908754?check_suite_focus=true#step:6:241). I have tried finding a solution for this and havent been able to find it yet. Would really appreaciate I could get some help with this.

**Comment by ishanjainn** [comment]
Thanks for helping out!

**Comment by ishanjainn** [comment]
Hey @alisonlhart , How can I go about adding a picture to the Grafana profile https://galaxy.ansible.com/grafana ?
Thanks in advance
