### ISSUE TITLE
Can´t delete collection uploaded to https://galaxy.ansible.com/

### ISSUE THREAD

**Issue by achillemyette1** [ansible/galaxy#2986]
##### SUMMARY
We cannot delete collection uploaded to https://galaxy.ansible.com/ , from the WebUI or CLI

##### STEPS TO REPRODUCE
1. Upload a collection
2. No option to delete it

##### EXPECTED RESULTS
To have an option to delete a collection. There seems to be an option to delete roles.

##### ACTUAL RESULTS
From https://galaxy.ansible.com/my-content/namespaces ->

Roles have an option to delete them:
![image](https://user-images.githubusercontent.com/80416563/184151913-58b49a9c-8c96-4d51-be39-a680fc4329f2.png)

Collection do not: 
![image](https://user-images.githubusercontent.com/80416563/184152081-e00ec8c3-f0c7-4239-812b-93649eb8e2ea.png)

**Comment by mahendrapaipuri** [comment]
+1

**Comment by soulraven** [comment]
+1

**Comment by btravouillon** [comment]
Hi @gundalow any thought about that?

**Comment by btravouillon** [comment]
Any update on this?

I realize the description of this ticket is incomplete: the collection https://galaxy.ansible.com/mila/monitoring was uploaded by mistake, this is proprietary code that should not be available on the Internet. Deprecating the collection is not enough, it has to be deleted.

I can't find the terms agreement of the service, is there any copyright waiver clause when using https://galaxy.ansible.com? 

cc Galaxy Team: @chouseknecht @cutwater @alikins  @newswangerd @awcrosby @tima

**Comment by awcrosby** [comment]
We have added the capability to delete collections and collection versions into `ansible/galaxy_ng`, which will eventually replace the backend of galaxy.ansible.com, currently served by `ansible/galaxy`.

In this codebase, we do have a manual workaround to safely delete an individual collection version, but unfortunately not the entire collection. If you like, we can import an empty collection version (0.1.1) and delete 0.1.0. @btravouillon please let us know if you would like us to do that.

**Comment by awcrosby** [comment]
Will do, I hope to get to this next week.

**Comment by btravouillon** [comment]
@awcrosby would this help if I upload an empty collection version 0.1.1?

**Comment by btravouillon** [comment]
@awcrosby the new (empty) version 0.1.1 has been uploaded.

**Comment by awcrosby** [comment]
@btravouillon version 0.1.0 been deleted.

**Comment by btravouillon** [comment]
Great! Thank you so much @awcrosby!!

**Comment by btravouillon** [comment]
Looks like I can't close this issue, but it's solved.
