### ISSUE TITLE
 Namespace Request Namespace: scale_computing

### ISSUE THREAD

**Issue by ddemlow** [ansible/galaxy#2989]
## Namespace Request
Namespace: scale_computing

##### Description
Official Ansible collection for Scale Computing SC//HyperCore (HC3) v1 API 
##### GitHub Org Link
https://github.com/ScaleComputing

##### Admins
ddemlow
loughmiller

**Comment by alisonlhart** [comment]
Namespace created: https://galaxy.ansible.com/scale_computing
