### ISSUE TITLE
Organizational Namespace request - redhat4gov

### ISSUE THREAD

**Issue by twling** [ansible/galaxy#3000]
## Namespace Request
Namespace: redhat4gov

##### Description
Red Hat Customer Success - Consulting for Government

##### GitHub Org Link
https://github.com/RedHat4Gov

##### Admins

- twling
- itewk
- rbuilta
- HunterGerlach
- BillBensing
- bontreger
- dwinchell
- mammerman

**Comment by alisonlhart** [comment]
Namespace created. https://galaxy.ansible.com/redhat4gov
The following accounts are not currently visible on Galaxy: 
rbuilta
HunterGerlach
BillBensing
bontreger
dwinchell
mammerman

If these users have not signed into Galaxy (OAuth through Github), their accounts will not show up. Once they sign in for the first time, they will be visible and can be added to the namespace. The twling and itewk admins both have access to edit the namespace and can add these accounts once they've signed into Galaxy.
