### ISSUE TITLE
New Galaxy Namespace sva

### ISSUE THREAD

**Issue by mwester117** [ansible/galaxy#3004]
## Namespace Request
Namespace: sva

##### Description
Namespace powered by [System Vertrieb Alexander GmbH](www.sva.de)

##### GitHub Org Link
https://github.com/svalabs

##### Admins
mwester117
jan-walther
nwerker
stdevel

**Comment by alisonlhart** [comment]
Namespace created: https://galaxy.ansible.com/sva
