### ISSUE TITLE
Namespace for our product

### ISSUE THREAD

**Issue by stephanbuys** [ansible/galaxy#3006]
## Namespace Request
Namespace: panoptix

##### Description
We would like to publish our software's role, but under a more professional namespace.

##### GitHub Org Link
https://github.com/panoptix-za

##### Admins
stephanbuys, beukeshu

**Comment by thedoubl3j** [comment]
@stephanbuys done ;) let us know if you need anything else

**Comment by stephanbuys** [comment]
@thedoubl3j thank you! We're trying to add our github organization to our "providers" so that we can do a github link to import the role. It however says:
```
Error! This provider namespace is already associated with a Galaxy namespace (panoptix-za)
```
Can you please assist?
