### ISSUE TITLE
Request for medeopolis namespace

### ISSUE THREAD

**Issue by goetzk** [ansible/galaxy#3008]
## Namespace Request
Namespace: medeopolis

##### Description

Ansible add-on materials developed by https://github.com/orgs/medeopolis/people for Medeopolis and made available to the public.

##### GitHub Org Link

https://github.com/medeopolis/

##### Admins

Goetzk.

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/medeopolis

Admin added @goetzk

**Comment by goetzk** [comment]
Thanks!
