### ISSUE TITLE
Unable to Publish collection, invalid namespace

### ISSUE THREAD

**Issue by Chithu51** [ansible/galaxy#3009]
## Namespace Request
Namespace: 

##### Description
I cannot publish my collection. I get an invalid namespace error. My collection is a aggregation of previously, separately published roles to ansible galaxy. I intend on deleting all those repositories and replacing them with this collection repo.

##### GitHub Org Link
[root@ip-172-32-11-77 Downloads]# ansible-galaxy collection publish Chithu51-war_deploy_collection-1.0.0.tar.gz --api-key=<api-key>
Publishing collection artifact '/home/user1/Downloads/Chithu51-war_deploy_collection-1.0.0.tar.gz' to default https://galaxy.ansible.com/api/
ERROR! Error when publishing collection to default (https://galaxy.ansible.com/api/) (HTTP Code: 400, Message: Invalid namespace: 'Chithu51' Code: invalid)

**Comment by Chithu51** [comment]
<img width="453" alt="image" src="https://user-images.githubusercontent.com/60918138/193014652-f96a5497-8274-4c8a-a1ac-3c9343ebc4dd.png">

**Comment by thedoubl3j** [comment]
@Chithu51 collection will need a runtime file, specifically with the `requires_ansible` key. Here is an example of one: https://github.com/ansible-collections/amazon.aws/blob/main/meta/runtime.yml#L2 (you will only need those first 2 lines unless you have other redirects etc). 

I would just default to the version being `2.9.10` as that is when the final collection spec code was merged into ansible itself.

**Comment by thedoubl3j** [comment]
were you able to figure out the namespace issue?

**Comment by Chithu51** [comment]
yeah, I believe If I use "c" instead of "C", it will work. 
For runtime.yml, I added the file and used "requires_ansible" inside it and then I again build it and tried to push. Still i am getting the same error. since we are explicitly adding this file, so it doesn't recognize the file and the content I believe

**Comment by thedoubl3j** [comment]
which namespace are you looking to publish to? When I get time I can go look at the logs for the namespace and see the imports.
