### ISSUE TITLE
namespace: budibase

### ISSUE THREAD

**Issue by jonnymccullagh** [ansible/galaxy#3010]
## Namespace Request
Namespace: budibase

##### Description
Adding ansible role for Budibase low-code platform

##### GitHub Org Link
https://github.com/Budibase

##### Admins
@jonnymccullagh
@shogunpurple
@mjashanks

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/budibase

Admins added
@jonnymccullagh
@shogunpurple
@mjashanks
