### ISSUE TITLE
Namespace Request: techprober

### ISSUE THREAD

**Issue by yqlbu** [ansible/galaxy#3013]
## Namespace Request

Namespace: techprober

##### Description

Would like to have it be used within the [techprober](http://github.com/techprober) organization

##### GitHub Org Link

http://github.com/techprober

##### Admins

- https://github.com/yqlbu
- https://github.com/kunish

**Comment by yqlbu** [comment]
Recently, we renamed our organization from `TechProber` to `techprober`. However, I was NOT able to remove the deprecated namespace from the `Selected Provider Namespaces` list. May I get some help with this as well, please?

**Comment by yqlbu** [comment]
May I get a review please? cc @JohnLieske @thedoubl3j @alisonlhart

**Comment by JohnLieske** [comment]
Namespace created: https://galaxy.ansible.com/techprober

Admins added:
@yqlbu 
@kunish
