### ISSUE TITLE
"ansible-galaxy collection list COLLECTION" exits with exit code 0 even if the collection does not exist

### ISSUE THREAD

**Issue by luksi1** [ansible/galaxy#3025]
##### SUMMARY

`ansible-galaxy collection list COLLECTION` always exits with exit code 0, regardless of whether the collection exists or not

##### STEPS TO REPRODUCE

```bash
ansible-galaxy collection install community.kubernetes
ansible-galaxy collection list community.kubernetes
echo $?
ansible-galaxy collection list community.kubernetet
echo $?
```

##### EXPECTED RESULTS

`ansible-galaxy collection list community.kubernetet` should exit with exit code 1

##### ACTUAL RESULTS

`ansible-galaxy collection list community.kubernetet` exits with exits code 0

```

**Comment by s-hertel** [comment]
Issues with the ansible-galaxy CLI should be opened in https://github.com/ansible/ansible, please refile there so this isn't lost.
