### ISSUE TITLE
New Namespace Request

### ISSUE THREAD

**Issue by made4git** [ansible/galaxy#3028]
## Namespace Request
Namespace: made4ansible

##### Description
Namespace for Made4IT Ansible projects

##### GitHub Org Link
https://github.com/made4ansible

##### Admins
made4git
luiz-made4it

**Comment by alisonlhart** [comment]
Namespace created: https://galaxy.ansible.com/made4git

The user luiz-made4it was not found. If the user has not logged into galaxy before with their github account, their user won't be available to add. Please do this first. 

You can add additional users to the namespace by going to My Content -> Click the 3 dots on the side of the made4it namespace -> Edit Properties -> Namespace Owners -> Filter by name (luiz-made4it) -> Select User -> Save.
