### ISSUE TITLE
New namespace: EGI-Federation

### ISSUE THREAD

**Issue by gwarf** [ansible/galaxy#3031]
## Namespace Request

Namespace: EGI-Federation

##### Description

Advanced Computing for Research

##### GitHub Org Link

https://github.com/EGI-Federation/

##### Admins

Galaxy users to be set as admins: gwarf, enolfc, orviz

**Comment by gwarf** [comment]
Dear @alisonlhart, egi_federation with an underscore looks great, thanks!

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/egi_federation

Admins added:
* gwarf
* enolfc
* orviz

**Comment by gwarf** [comment]
Thanks!
