### ISSUE TITLE
Namespace Request: adfinis

### ISSUE THREAD

**Issue by s3lph** [ansible/galaxy#3032]
## Namespace Request
Namespace: `adfinis`

##### Description

Adfinis AG

##### GitHub Org Link

https://github.com/adfinis

##### Admins

@adfinisbot
@fujexo
@karras
@s3lph

**Comment by alisonlhart** [comment]
Namespace created: https://galaxy.ansible.com/adfinis

**Comment by fujexo** [comment]
Thank you!
