### ISSUE TITLE
Buster and Bionic are unsupported

### ISSUE THREAD

**Issue by fubarhouse** [ansible/galaxy#304]
I've just created some Docker images to support my existing roles on, which has Bionic Beaver (Ubuntu 18.04) and Debian Buster (Debian 10).

Unfortunately they aren't supported by galaxy yet, is there any chance we could add it?

![image](https://user-images.githubusercontent.com/3070264/35178803-3d8d8b76-fde2-11e7-96bf-0f23d67a55f7.png)

**Comment by chouseknecht** [comment]
@fubarhouse 

Thanks for pointing this out. Both platforms are now available.

**Comment by fubarhouse** [comment]
Thank you @chouseknecht, love your work!

**Comment by fubarhouse** [comment]
@chouseknecht, I've had another look a couple of days later in case there was a caching thing.

Bionic is still unsupported:
![image](https://user-images.githubusercontent.com/3070264/35190645-61f8ab66-feba-11e7-92f8-eab9c88f0ed3.png)
