### ISSUE TITLE
Namespace Request: opentermsarchive

### ISSUE THREAD

**Issue by Ndpnt** [ansible/galaxy#3045]
## Namespace Request
Namespace: opentermsarchive

##### Description
Collections managed by Open Terms Archive

##### GitHub Org Link
https://github.com/OpenTermsArchive

##### Admins
Ndpnt, OTA-Bot, MattiSG

**Comment by JohnLieske** [comment]
Namespace createdf:
https://galaxy.ansible.com/opentermsarchive

Admins added:
* @Ndpnt 
* @OTA-Bot
* @MattiSG

**Comment by martinratinaud** [comment]
Would it be possible to add @martinratinaud also ? @JohnLieske.

I may have to work on this at some point
Thanks

**Comment by Ndpnt** [comment]
@martinratinaud I will take care of it via the web application. You need to create an account on ansible galaxy first, that's why you weren't added before.

**Comment by martinratinaud** [comment]
I created an account with my GitHub email (gmail)

**Comment by Ndpnt** [comment]
Done
