### ISSUE TITLE
New namespace for automationiberia

### ISSUE THREAD

**Issue by ivarmu** [ansible/galaxy#3046]
## Namespace Request
Namespace: automationiberia

##### Description
Automation Iberia collections. Currently available: Ansible Automation Platform related content and other tools' automation.

##### GitHub Org Link
[automationiberia Organization](https://github.com/organizations/automationiberia)

##### Admins
ivarmu
silvinux
adonisgarciac

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/automationiberia

Admins added:
* @ivarmu 
* @adonisgarciac

The user silvinux has not logged into Galaxy and cannot be added until doing so. Once they have logged into Galaxy you will be able to add them to your namespace by editing from the My Content section of the site.
