### ISSUE TITLE
Namespace u99-net

### ISSUE THREAD

**Issue by thewiwi** [ansible/galaxy#3050]
## Namespace Request
Namespace:  u99-net

##### Description
u99.net

##### GitHub Org Link
https://github.com/u99-net

##### Admins
wiwi@progon.net (thewiwi)

**Comment by JohnLieske** [comment]
This nameapce cannot be created because it contains a special character. As outlined in our docs (https://galaxy.ansible.com/docs/contributing/namespaces.html#requesting-additional-namespaces) :

```
Namespace names in Galaxy are limited to lowercase word characters (i.e., a-z, 0-9) and ‘_’, must have a minimum length of 2 characters, and cannot start with an ‘_’. No other characters are allowed, including ‘.’, ‘-‘, and space.
```

Please edit your request appropriately.

**Comment by thedoubl3j** [comment]
@thewiwi you have an update here for the namespace request?

**Comment by alisonlhart** [comment]
Closing as the issue is stale. We can reopen if needed.
