### ISSUE TITLE
namespace: blackieops

### ISSUE THREAD

**Issue by alexblackie** [ansible/galaxy#3051]
## Namespace Request
Namespace: `blackieops`

##### Description
Automation from BlackieOps.

##### GitHub Org Link
https://github.com/blackieops

##### Admins
@alexblackie (https://galaxy.ansible.com/alexblackie)

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/blackieops

Admin added:
* @alexblackie
