### ISSUE TITLE
Namespace ipfs_search for GH organisation ipfs-search

### ISSUE THREAD

**Issue by dokterbob** [ansible/galaxy#3055]
## Namespace Request
Namespace: `ipfs_search`

##### Description
When registering, I somehow got the `ipfs-search` namespace. Somehow, the `-` wasn't replaced by `_` and currently I am unable to publish as our organisation.

##### GitHub Org Link
https://github.com/ipfs-search/

##### Admins
dokterbob

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/ipfs_search

Admin added:
* @dokterbob
