### ISSUE TITLE
namespace: cowdogmoo

### ISSUE THREAD

**Issue by l50** [ansible/galaxy#3056]
## Namespace Request
Namespace: cowdogmoo

##### Description
Various roles, playbooks, and collections used for home automation. 

##### GitHub Org Link
https://github.com/cowdogmoo

##### Admins
l50

**Comment by JohnLieske** [comment]
Namespace created: 
https://galaxy.ansible.com/cowdogmoo

Admin added:
* @l50

**Comment by l50** [comment]
Thank you very much!
