### ISSUE TITLE
Add `Kali Linux` as a platform

### ISSUE THREAD

**Issue by mcdonnnj** [ansible/galaxy#3059]
### Use Case

Kali Linux is one of the most prominent Linux distributions for security-focused needs. However it is not available as a platform on Ansible Galaxy.

### Proposed Solution

`Kali Linux` is added as a platform for Ansible Galaxy

### Implementation

The list of releases for Kali Linux can be found at https://www.kali.org/releases/

**Comment by alisonlhart** [comment]
Platforms added: https://galaxy.ansible.com/api/v1/platforms/?search=Kali
