### ISSUE TITLE
Duplicate support for platform appears to be breaking support.

### ISSUE THREAD

**Issue by fubarhouse** [ansible/galaxy#306]
After the completion of #304, I had failings with the support introduced to bionic.

![image](https://user-images.githubusercontent.com/3070264/35190645-61f8ab66-feba-11e7-92f8-eab9c88f0ed3.png)

From looking at the following link, there's one entry for Buster, and two entries for Bionic.
* https://galaxy.ansible.com/api/v1/platforms/

TL/DR: Platform 154 and 155 are duplicated within the space of a few minutes, and it appears it's causing issues.

![image](https://user-images.githubusercontent.com/3070264/35217702-52f6704c-ffc0-11e7-85a6-2c8a905dd218.png)

**Comment by chouseknecht** [comment]
Fixed. Now there is only one. Sorry about that.
