### ISSUE TITLE
Route Views Ansible Galaxy Namespace

### ISSUE THREAD

**Issue by ryeleo** [ansible/galaxy#3060]
## Namespace Request
Namespace: routeviews

##### Description
Manage 

##### GitHub Org Link
https://github.com/routeviews

## Namespace Request
Namespace: routeviews

##### Description
Manage Route Views services.

##### GitHub Org Link
https://github.com/routeviews

##### Admins
- ryeleo (self)
- route-views

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/routeviews

Admins added:
* @route-views
* @ryeleo
