### ISSUE TITLE
Namespace request: sedi

### ISSUE THREAD

**Issue by se-di** [ansible/galaxy#3063]
## Namespace Request
Namespace: sedi

##### Description
collections made by secure diversITy

##### GitHub Org Link
https://github.com/secure-diversITy

##### Admins
@se-di

**Comment by se-di** [comment]
@JohnLieske , @thedoubl3j , @alisonlhart any chance we can get this processed before christmas :) that would be highly appreciated...

**Comment by JohnLieske** [comment]
Namespace crerated:
https://galaxy.ansible.com/sedi

Admin added:
* @se-di

**Comment by se-di** [comment]
Unfortunately this stopped working since the move to galaxy NG.. :( 
@JohnLieske , @thedoubl3j , @alisonlhart 

also opened a forum topic about that as its unclear atm where to report: https://forum.ansible.com/t/lost-namespaces-access/1399

**Comment by alisonlhart** [comment]
Hello @se-di, This is a known issue with some namespaces since the migration. I see there was a response on forum.ansible.com to your post! Please continue to communicate with the Galaxy team there as that is the best way to receive assistance on Galaxy NG issues.
