### ISSUE TITLE
Change owner of orgranization's namespace

### ISSUE THREAD

**Issue by kotbauk** [ansible/galaxy#3066]
Hello!
Can you change the owner of an organization's namespace [moira-alert](https://galaxy.ansible.com/moira-alert)? 
The engineer who created and owns this namespace no longer works for the company that develops this role. I'm the DevOps of an organization developing a [role](https://galaxy.ansible.com/moira-alert/moira-trigger-role) in this namespace and we can't get the current role owner to sign over to us, so could you make me (kotbauk) the owner?
I am a member of a Github organization that includes a repository with role

**Comment by kotbauk** [comment]
@thedoubl3j, @alisonlhart, excuse me for disturbing, could you help with this issue, please?

**Comment by kissken** [comment]
@JohnLieske
@thedoubl3j
@alisonlhart

Hello, sorry, but could you help us please with this issue? 😊

**Comment by kissken** [comment]
@thedoubl3j thank you so much! 🙌
