### ISSUE TITLE
Namespace request for 6connect Inc

### ISSUE THREAD

**Issue by steffann** [ansible/galaxy#3069]
## Namespace Request
Namespace: sixconnect

We would prefer 6connect, but I guess that wouldn't work with Python…

##### Description
Revolutionary network automation & provisioning for ISP's and enterprises around the world

##### GitHub Org Link
https://github.com/orgs/6connect/people

##### Admins
- steffann
- procopes

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/sixconnect

Admins added:
* @steffann 
* @procopes
