### ISSUE TITLE
Please grant us the "freexian" namespace

### ISSUE THREAD

**Issue by rhertzog** [ansible/galaxy#3070]
## Namespace Request
Namespace: freexian

##### Description
Collaborators of Freexian, a service company specialized in Debian.

##### GitHub Org Link
https://salsa.debian.org/freexian-team
(or https://github.com/freexian that I created on purpose hoping that I could get the namespace attributed automatically, alas I had already created my ansible-galaxy account)

##### Admins
* rhertzog

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/freexian

Admin added:
* @rhertzog
