### ISSUE TITLE
Request rls namespace

### ISSUE THREAD

**Issue by zerwes** [ansible/galaxy#3073]
## Namespace Request
Namespace: rls

##### Description
Rosa-Luxemburg-Stiftung Gesellschaftsanalyse und politische Bildung e. V.

##### GitHub Org Link
https://github.com/Rosa-Luxemburgstiftung-Berlin

##### Admins
 * zerwes

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/rls

Admin added:
* @zerwes
