### ISSUE TITLE
Request ansible galaxy namespace 'release_engineering' to publish https://github.com/release-engineering/dockpulp-ansible

### ISSUE THREAD

**Issue by hongweiliu17** [ansible/galaxy#3077]
## Namespace Request
Namespace: release_engineering

##### Description
Red Hat Release Engineering

##### GitHub Org Link
https://github.com/orgs/release-engineering

##### Admins
https://galaxy.ansible.com/ktdreyer
https://galaxy.ansible.com/hongweiliu17

**Comment by thedoubl3j** [comment]
namespace created and admins added @hongweiliu17
