### ISSUE TITLE
namespace: community-fabric named incorrectly

### ISSUE THREAD

**Issue by minitriga** [ansible/galaxy#3078]
## Namespace Request
Namespace: community-fabric

##### Description
The namespace `community-fabric` looks to be incorrect as it should be `community_fabric` looks like it has been created without the `_`.

##### GitHub Org Link
https://github.com/community-fabric

##### Admins
@minitriga

**Comment by alisonlhart** [comment]
Namespace created: https://galaxy.ansible.com/community_fabric

Admins added: @minitriga (minitrig in Galaxy)
