### ISSUE TITLE
namespace: mmul

### ISSUE THREAD

**Issue by rascasoft** [ansible/galaxy#3080]
## Namespace Request
Namespace: mmul

##### Description
The MMUL project Ansible collection

##### GitHub Org Link
https://github.com/mmul-it

##### Admins
rascasoft

**Comment by JohnLieske** [comment]
Namespace created: 
https://galaxy.ansible.com/mmul

Admin added:
* @rascasoft

**Comment by rascasoft** [comment]
Nevermind, I needed to grant the access for the Ansible Galaxy App to the organization https://github.com/settings/connections/applications/, and now it works. Many thanks!
