### ISSUE TITLE
Create `digitalocean` namespace

### ISSUE THREAD

**Issue by mamercad** [ansible/galaxy#3091]
## Namespace Request
Namespace: `digitalocean`

##### Description

DigitalOcean simplifies cloud computing so builders can spend more time creating software that changes the world.

##### GitHub Org Link

[https://github.com/digitalocean/](https://github.com/digitalocean/)

##### Admins

@mamercad

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/digitalocean

Admin added 
* @mamercad

**Comment by mamercad** [comment]
> Namespace created: https://galaxy.ansible.com/digitalocean
> 
> Admin added
> 
> * @mamercad

Thanks ❤️
