### ISSUE TITLE
Can't get correct avatar/logo inside mmul namespace

### ISSUE THREAD

**Issue by rascasoft** [ansible/galaxy#3092]
Hi there!
After you kindly created my organization namespace (https://galaxy.ansible.com/mmul) I'm not seeing in here the correct Logo that appears in the GitHub page (https://github.com/mmul-it) and I can't find any place in which I can do this autonomously.

Is this something you need to do manually or am I missing something?

Many thanks!

Raoul

**Comment by alisonlhart** [comment]
@rascasoft I added your github user avatar into the namespace properties. There is an avatar URL that is filled automatically for auto-generated profiles when you OAuth with github, but it isn't filled in for manually created organization namespaces. You can change this in the `Edit namespace` properties.

**Comment by rascasoft** [comment]
> @rascasoft I added your github user avatar into the namespace properties. There is an avatar URL that is filled automatically for auto-generated profiles when you OAuth with github, but it isn't filled in for manually created organization namespaces. You can change this in the `Edit namespace` properties.

I see! Many thanks for your support!
