### ISSUE TITLE
`chainflip` namespace

### ISSUE THREAD

**Issue by vdoflip** [ansible/galaxy#3094]
## Namespace Request
Namespace:  chainflip

##### Description
The efficient cross-chain swapping protocol (chainflip.io)

##### GitHub Org Link
https://github.com/chainflip-io

##### Admins

`vdoflip` 
`ahasna`

**Comment by vdoflip** [comment]
please also add `tomjohnburton` as admin: https://galaxy.ansible.com/tomjohnburton

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/chainflip

Admins added:
* @vdoflip 
* @ahasna
* @tomjohnburton

(note: you may add more admins by going to My Content and editing your namespace properties)
