### ISSUE TITLE
Octupus

### ISSUE THREAD

**Issue by escrimaglia** [ansible/galaxy#3096]
## Namespace Request
Namespace: octupus

##### Description

Octupus Collections

##### GitHub Org Link

https://github.com/OctupusCloud

##### Admins
escrimaglia

**Comment by escrimaglia** [comment]
I will appreciate AG to allow us to have a new namespace

Thanks

Ed Scrimaglia
https://www.octupus.com/

**Comment by escrimaglia** [comment]
Hi,

Dear @alisonlhart @JohnLieske and @thedoubl3j any news about the new name space called octupus?

best regards

**Comment by thedoubl3j** [comment]
namespace created and admins added @escrimaglia apologies on the delay
