### ISSUE TITLE
Add admins to Confluent namespace

### ISSUE THREAD

**Issue by utkarsh5474** [ansible/galaxy#3102]
## Namespace Request
Namespace: Confluent

##### Admins
We need to add following people as admins:

wadhwa1
mansisinha

**Comment by JohnLieske** [comment]
Admins have been added.

For future reference, you should be able to edit your own namespace properties to include more admins in the future. By using the [My Content](https://galaxy.ansible.com/my-content/namespaces) section on Ansible Galaxy and clicking the three-dot context menu and selecting "Edit Properties".
![Screenshot from 2023-02-07 11-41-16](https://user-images.githubusercontent.com/9461032/217337673-f81e1d54-25e1-44fc-b37b-e0fa6a9a151a.png)

You can add admins in the "Namespace Owners" section by searching the GH username. (please note the user must have logged into Galaxy once to be found).
![Screenshot from 2023-02-07 11-42-16](https://user-images.githubusercontent.com/9461032/217338038-21e9fc37-7b76-4dfa-a3cb-afa8e72e5ada.png)

Hopefully this helps in the future.

**Comment by utkarsh5474** [comment]
This'll definitely help, thanks!
