### ISSUE TITLE
Please add admin to namespace: instana

### ISSUE THREAD

**Issue by arthurdm** [ansible/galaxy#3104]
Hi - I am architect with IBM / Instana and wanted to create a new repository in the Instana (https://galaxy.ansible.com/instana) namespace.  The issue is that namespace was created many years ago and nobody has access to it anymore.

Can you please add me (Galaxy ID:  `arthurdm`   arthurdm@ca.ibm.com) as an admin to this namespace?

I am currently working with Red Hat's EDA team (CC @benthomasson) on a new Instana Plugin for EDA and would like to host it (along with relevant rulebooks and playbooks) in this namespace.  Thank you in advance!

**Comment by alisonlhart** [comment]
This has been completed (via email to @ ansiblepartners)
