### ISSUE TITLE
Delete version of ansible collection

### ISSUE THREAD

**Issue by framtale** [ansible/galaxy#3105]
Hey I'm referencing to a similar case as in #2986.
I would like to delete the version 1.3.0 in the namespace https://galaxy.ansible.com/roclub/edge, so that the only remaining version is 0.1.0.

Thanks in advance!

**Comment by awcrosby** [comment]
I should be able to take care of this by the end of next week.

**Comment by awcrosby** [comment]
@framtale it is now completed, sorry for the delay. Thanks!
