### ISSUE TITLE
namespace: Please add Admins to Namespace appdynamics 

### ISSUE THREAD

**Issue by pavankrish123** [ansible/galaxy#3106]
## Namespace Request
Namespace: appdynamics

##### Description
Please add the following members from AppDynamics as admins to namespace appdynamics in galaxy.ansible.com. The namespace was created and nobody has access to it anymore.

##### GitHub Org Link
github.com/AppDynamics 

##### Admins
- pavankrish123 https://galaxy.ansible.com/pavankrish123 
- sanketmehta28 https://galaxy.ansible.com/sanketmehta28 
- justaugustus https://galaxy.ansible.com/justaugustus 
- detiber https://galaxy.ansible.com/detiber

**Comment by detiber** [comment]
Please also add @justaugustus and myself (@detiber) to the list of Admins for this namespace, that way we (Cisco's OSPO) can provide continuity for these types of situations.

https://galaxy.ansible.com/justaugustus and https://galaxy.ansible.com/detiber are our related Galaxy users.

**Comment by thedoubl3j** [comment]
@detiber @pavankrish123 users added, we will let you all remove existing admins as you all can affirm if they are still relevant or not (users are iogbole, AlexJov)

**Comment by pavankrish123** [comment]
This is wonderful news. Thanks a ton. We will update the accounts.
