### ISSUE TITLE
brettops namespace

### ISSUE THREAD

**Issue by bweir** [ansible/galaxy#3108]
## Namespace Request
Namespace: `brettops` (preferred) or `brettops-io`

##### Description
Ready-made CI/CD ecosystem for getting things done.

##### GitHub Org Link
https://github.com/brettops-io
https://gitlab.com/brettops
https://brettops.io/

##### Admins
- `bweir`

**Comment by alisonlhart** [comment]
Namespace created: https://galaxy.ansible.com/brettops
Admins added: @bweir
