### ISSUE TITLE
Mysterium Network

### ISSUE THREAD

**Issue by redhatua** [ansible/galaxy#3119]
## Namespace Request
Namespace: mysteriumnetwork

##### Description
An open-source ecosystem of protocols, tools and infrastructure to liberate the web

##### GitHub Org Link
[mysteriumnetwork](https://github.com/mysteriumnetwork)

##### Admins
- redhatua

**Comment by thedoubl3j** [comment]
namespace created and user added as admin, let us know if we can help out with anything else @redhatua
