### ISSUE TITLE
Request for Namespace bwinfosec

### ISSUE THREAD

**Issue by br-olf** [ansible/galaxy#3123]
## Namespace Request
Namespace: bwinfosec

##### Description

The universities in the state of Baden-Württemberg, Germany have joined forces to form the bwInfoSec federation in order to jointly improve information security at the state’s universities.

##### GitHub Org Link

https://github.com/bwInfoSec

##### Admins

https://galaxy.ansible.com/br_olf
https://galaxy.ansible.com/stefandeveloper

**Comment by br-olf** [comment]
I just saw, we have a slightly shorter Description on our GitHub Org, please use that one on the galaxy namespace too:
The universities in the state of Baden-Württemberg have joined forces to form the bwInfoSec federation in order to jointly improve information security.

**Comment by thedoubl3j** [comment]
namespace created and admins added (note username for @br-olf remained the same so it was `br-olf`, just the namespace that contains the `_`) and used newer description.
