### ISSUE TITLE
Shiftsystems Namespace Request

### ISSUE THREAD

**Issue by tiny6996** [ansible/galaxy#3125]
## Namespace Request
Namespace:  shiftsytsems

##### Description

Shift Systems Ansible Automation for backups and observability
##### GitHub Org Link

https://github.com/shiftsystems
##### Admins

tiny6996

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/shiftsytsems

Admin added:
@tiny6996

**Comment by tiny6996** [comment]
It looks like I made a typo. The namespace I wanted was shiftsystems not shiftsytsems. Should I create a new request?

**Comment by tiny6996** [comment]
submitted #3127 to resolve the typo issue
