### ISSUE TITLE
Namespace: HackersLLC

### ISSUE THREAD

**Issue by codytubbs** [ansible/galaxy#3128]
## Namespace Request
Namespace: `hackersllc`

##### Description
open-source roles and collections for Hackers LLC -- security solutions developed from an unwavering proactive mindset and resolute approach to zero-trust cyber security.

##### GitHub Org Link
[HackersLLC](https://github.com/HackersLLC)

##### Admins
- `codytubbs`

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/hackersllc

Admin added:
* @codytubbs
