### ISSUE TITLE
London Project namespace request

### ISSUE THREAD

**Issue by captainjacksparrowat** [ansible/galaxy#3129]
## Namespace Request
Namespace: londonproject

##### Description
London Project ansible collection

##### GitHub Org Link
https://github.com/gitpaxukraina

##### Admins
captainjacksparrowat
Nevge

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/londonproject

Admins added:
* @captainjacksparrowat 
* @Nevge
