### ISSUE TITLE
namespace: community_fabric.ansible update admins

### ISSUE THREAD

**Issue by minitriga** [ansible/galaxy#3130]
## Namespace Request
Namespace: community_fabric.ansible

##### Description
I would like an additional admin to my namespace. I'm the current admin of community_fabric.ansible but would like to add @ipfabric-solution-architect

##### GitHub Org Link
[](https://github.com/ipfabric-solution-architect)

##### Admins
@minitriga
@ipfabric-solution-architect

**Comment by alisonlhart** [comment]
Admin added. 

You can add additional admins by going to "My Content", clicking on the three dots (hamburger) on your namespace, clicking "Edit Properties" in the dropdown that appears. This will open your namespace properties, and you can search for/add additional admins in the "Namespace Owners" field.

**Comment by minitriga** [comment]
Thank you. I did try a quick google but couldnt find anything to do it myself. Thank you for the information.
