### ISSUE TITLE
Requesting new namespace infra for infra.osbuild collection

### ISSUE THREAD

**Issue by maxamillion** [ansible/galaxy#3132]
## Namespace Request
Namespace: infra

##### Description

A set of Collections for various infrastructure use cases (e.g. OS and enterprise applications automation)

##### GitHub Org Link

https://github.com/redhat-cop

##### Admins

maxamillion
jillr
matoval
resolutecoder
cidrblock
gravesm

**Comment by JohnLieske** [comment]
This namespace is currently in use with the description "RedHat CoP Infrastructure"

https://galaxy.ansible.com/infra
