### ISSUE TITLE
Requesting new Namespace: l3d

### ISSUE THREAD

**Issue by DO1JLR** [ansible/galaxy#3133]
## Namespace Request
Namespace: ``l3d``

##### Description
I love open source and automation. So I wrote some ansible roles and released them as open source.

##### GitHub Org Link
[github.com/roles-ansible/](https://github.com/roles-ansible/)

##### Admins
[do1jlr](https://galaxy.ansible.com/do1jlr)

**Comment by DO1JLR** [comment]
And I also have a question.

Is there a recommended way to move existing roles or collections from one namespace to another? *Unfortunately I could not find anything in this regard?*

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/l3d

Admin added:
* @DO1JLR 

To your question: We don't have any mechanism for moving items from one namespace to another at this time. They will have to be re-uploaded to the new namespace.
