### ISSUE TITLE
namespace acoby

### ISSUE THREAD

**Issue by trickert76** [ansible/galaxy#3135]
## Namespace Request
Namespace: acoby

##### Description

I'd like to add a new namespace acoby to import some new roles and collections to Ansible Galaxy. I've added a user trickert76 and added the github org acoby, but I cannot upload a collection to acoby namespace, it says, the namespace does not exist.

##### GitHub Org Link

https://github.com/acoby

##### Admins

trickert76

**Comment by JohnLieske** [comment]
Namespace created: 
https://galaxy.ansible.com/acoby

Admin added:
* @trickert76
