### ISSUE TITLE
Request a Namespace - slingnode

### ISSUE THREAD

**Issue by karolpivo** [ansible/galaxy#3137]
## Namespace Request
Namespace: slingnode

##### Description

Ansible roles for deploying and managing Ethereum nodes. 

##### GitHub Org Link

https://github.com/SlingNode/

##### Admins

karolpivo
pgjavier

**Comment by JohnLieske** [comment]
Namespace created:
https://galaxy.ansible.com/slingnode

Admins added:
* @karolpivo 
* @pgjavier
