### ISSUE TITLE
Add Ubuntu 22.10 Kinetic Kudu to platforms

### ISSUE THREAD

**Issue by kotovalexarian** [ansible/galaxy#3139]
**Ubuntu 22.10 Kinetic Kudu** has been released six month ago, but it is not in [the API](https://galaxy.ansible.com/api/v1/platforms/?search=Ubuntu).

Also I think that you should do something about it, because this is a repeating problem:  #1946

**Comment by alisonlhart** [comment]
Platform added: https://galaxy.ansible.com/api/v1/platforms/271/
