### ISSUE TITLE
Add a platform for Amazon Linux 2023

### ISSUE THREAD

**Issue by jsf9k** [ansible/galaxy#3141]
### Use Case

[Amazon Linux 2023 was officially released on March 15, 2023](https://aws.amazon.com/about-aws/whats-new/2023/03/amazon-linux-2023/) but [there is no suitable platform listed in the Ansible Galaxy API](https://galaxy.ansible.com/api/v1/platforms/?name__icontains=amazon).  It would be great if one could be added.

In our ([cisagov's](https://github.com/cisagov)) case, we want to drop support for the ancient Amazon Linux 2 and support only Amazon Linux 2023.  At the moment that is tricky because we can't list the Amazon Linux 2023 platform in our Ansible role metadata.

### Proposed Solution

Add a platform for Amazon Linux 2023, just as the various Amazon Linux 2 platforms have been added over the years.

### Alternatives

A reworking of the platform enumeration, as was discussed, e.g., in #80.

### Implementation

I'm not sure what to put here, but I'd like to see an Amazon Linux 2023 platform appear in [this list](https://galaxy.ansible.com/api/v1/platforms/?name__icontains=amazon).

**Comment by alisonlhart** [comment]
Platform added here: https://galaxy.ansible.com/api/v1/platforms/286/

**Comment by jsf9k** [comment]
Thank you @alisonlhart!
