### ISSUE TITLE
Please add a MAAS namespace to Galaxy

### ISSUE THREAD

**Issue by cpg1111** [ansible/galaxy#3148]
## Namespace Request
Namespace: MAAS

##### Description
Namespace for the MAAS Ansible Collection

##### GitHub Org Link
https://github.com/maas

##### Admins

- cpg1111
- sparkiegeek

**Comment by alisonlhart** [comment]
Namespace created: https://galaxy.ansible.com/maas

Admins added:
cpg1111
sparkiegeek
