### ISSUE TITLE
Request an Organisation Namespace

### ISSUE THREAD

**Issue by iamsarvagyaa** [ansible/galaxy#3149]
## Namespace Request
Namespace: `kloudies`

##### Description
A small community for Platform Eng, Security Eng, Developers, & Learners. Cheers 🍺

##### GitHub Org Link
- https://github.com/Kloudies

##### Admins
- iamsarvagyaa : https://galaxy.ansible.com/iamsarvagyaa

**Comment by alisonlhart** [comment]
Namespace created with admin `iamsarvagyaa` : https://galaxy.ansible.com/kloudies
