### ISSUE TITLE
Namespace request: happydns

### ISSUE THREAD

**Issue by nemunaire** [ansible/galaxy#3151]
Hi Ansible team, we are releasing a collection to setup and use [happyDomain](https://github.com/happyDomain/ansible-collection).

## Namespace Request
Namespace: happydns

##### Description
Finally a simple interface for domain names.

##### GitHub Org Link
https://github.com/happyDNS

##### Admins
@nemunaire

**Comment by alisonlhart** [comment]
Namespace created: https://galaxy.ansible.com/happydns

Admin [nemunaire](https://github.com/nemunaire) added.
