### ISSUE TITLE
Namespace Request

### ISSUE THREAD

**Issue by therapac** [ansible/galaxy#3154]
## Namespace Request
Namespace:  StadtLuzernIO

##### Description
Stadt Luzern

##### GitHub Org Link
https://github.com/StadtLuzernIO)](https://github.com/StadtLuzernIO

##### Admins
therapac
raphael.baechi@stadtluzern.ch

**Comment by thedoubl3j** [comment]
created @therapac however, capitals are not allowed so the namespace is `stadtluzernio`
