### ISSUE TITLE
Add namespace for BorgBase

### ISSUE THREAD

**Issue by m3nu** [ansible/galaxy#3157]
## Namespace Request
Namespace: `borgbase`

##### Description
Roles related to server backups

##### GitHub Org Link
https://github.com/borgbase/

##### Admins
`m3nu`

Hi, Requesting this namespace to avoid using a personal account for our [role](https://github.com/borgbase/ansible-role-borgbackup), which some users find [strange](https://github.com/borgbase/ansible-role-borgbackup/issues/128). Thanks!

**Comment by alisonlhart** [comment]
Namespace created: https://galaxy.ansible.com/borgbase
