### ISSUE TITLE
Namespace renaming request: tribe29 -> Checkmk

### ISSUE THREAD

**Issue by robin-checkmk** [ansible/galaxy#3158]
## Namespace Request
Namespace: Checkmk (formerly known as `tribe29`)

Our company went through a re-branding process, so I want to align our Galaxy namespace.
I have a few questions though:
- How do we go about this the most elegantly?
- Do I need to request a new namespace and move all the content?
- Can the namespace be renamed or at least redirect to the new namespace?
- Can I retain the `tribe29` namespace, if there are no redirects, so no one else can request it and I can manage a redirect manually?
- Is there documentation on this, or other things to consider?

##### Description

The official Checkmk Ansible collection - brought to you by the Checkmk company. 

##### GitHub Org Link

https://github.com/Checkmk/

##### Admins

- @robin-checkmk
- @lgetwan
- @godspeed-you

**Comment by alisonlhart** [comment]
Hello @robin-checkmk , the best way to do this is to create a new namespace `checkmk` and migrate all the `tribe29` content. You can keep the `tribe29` namespace and do all needed redirects. 
There is documentation on how the community requires redirects for renaming collections inside the Ansible Community Package, but that does not apply to this situation, and renaming a namespace is a fairly unique case and so isn't covered in our docs. The documentation is here for renaming collections, if you'd like to check it out anyway! https://github.com/ansible-community/ansible-build-data/blob/main/README.md#renaming-a-collection

Let me know if you'd like us to create the `checkmk` namespace and give you access.

**Comment by robin-checkmk** [comment]
Hi @alisonlhart and thanks for your reply.
I would like to move forward with the new namespace then, as we cannot break anything with that approach and I can proceed as you suggested.
If anything else comes up, I would hit IRC/Matrix or create a follow-up issue.

**Comment by alisonlhart** [comment]
Hello @robin-checkmk, I have created the `checkmk` namespace. The only admin whose account I could locate is @godspeed-you. Have you (@robin-checkmk) or @lgetwan changed your Github username? Galaxy keeps an association of the original account name used when OAuthing to Galaxy for the first time, so that may be why it's not showing up. 

https://galaxy.ansible.com/checkmk

**Comment by robin-checkmk** [comment]
Thanks! :tada: 

Well, I definitely changed my name, that is true. My original name is `robin-tribe29`.
I think `lgetwan` might not yet have logged into the Galaxy, so that would be fine.
If you can add me, we are good. I can do the additional user management later.
