### ISSUE TITLE
Namespace Request: daeuniverse

### ISSUE THREAD

**Issue by yqlbu** [ansible/galaxy#3159]
## Namespace Request

Namespace: daeuniverse

##### Description

Would like to have it be used within the [daeuniverse](http://github.com/daeuniverse) organization

##### GitHub Org Link

http://github.com/daeuniverse

##### Admins

- https://github.com/yqlbu
- https://github.com/kunish

##### Galaxy Repo

https://github.com/daeuniverse/dae-galaxy.git

**Comment by yqlbu** [comment]
May I get a review please? cc @JohnLieske @thedoubl3j @alisonlhart

**Comment by alisonlhart** [comment]
https://galaxy.ansible.com/daeuniverse

Admins added.
