### ISSUE TITLE
sysdig namespace

### ISSUE THREAD

**Issue by manuelbcd** [ansible/galaxy#3161]
## Namespace Request
Namespace: sysdig

##### Description
Sysdig Observability and Security Platform.

##### GitHub Org Link
https://github.com/sysdiglabs/

##### Admins
manuelbcd, mavimo, aroberts87

**Comment by alisonlhart** [comment]
Namespace created: https://galaxy.ansible.com/sysdig

Admins added: manuelbcd, mavimo. **aroberts87** could not be added, as their user was not found in Galaxy. They may need to OAuth to Galaxy through Github. If this has not been done before, their account will not appear. 

Once they have done this, one of the other admins can add their account by navigating to `My Content`, click on the three dots to the right of the `sysdig` namespace in the list, and select `Edit properties`. Scroll down in the namespace properties page to `Namespace Owners`, and search for the new admin's username there. It should then appear in the list. 

Please reach out with any questions about this!

**Comment by manuelbcd** [comment]
thanks @alisonlhart

**Comment by mavimo** [comment]
@alisonlhart @manuelbcd thanks! 🚀
