### ISSUE TITLE
haufe-it namespace

### ISSUE THREAD

**Issue by JakobHaufe** [ansible/galaxy#3162]
## Namespace Request
Namespace: haufe-it

##### Description
haufe.it

##### GitHub Org Link
https://github.com/haufe-it/

##### Admins
JakobHaufe

**Comment by alisonlhart** [comment]
Namespace created: https://galaxy.ansible.com/haufe_it

(`-` is not allowed in namespace names, so an `_` was substituted)

**Comment by JakobHaufe** [comment]
Thanks!
