### ISSUE TITLE
namespace: powerdevops

### ISSUE THREAD

**Issue by aklyachkin** [ansible/galaxy#3163]
## Namespace Request
Namespace: powerdevops

##### Description
Ansible Collections built for IBM Power. https://www.power-devops.com 

##### GitHub Org Link
https://github.com/power-devops

##### Admins
aklyachkin

It looks like that the namespace was created with hyphen in it during the user creation:

![grafik](https://github.com/ansible/galaxy/assets/3786052/dc14c338-270c-4dcf-a38e-e54e39a11500)

I can't change it. Please rename it to powerdevops or create a new namespace with the correct name.

Thank you!

**Comment by alisonlhart** [comment]
Namespace created: https://galaxy.ansible.com/powerdevops
