### ISSUE TITLE
Namespace request for rcx.one

### ISSUE THREAD

**Issue by E1k3** [ansible/galaxy#3165]
## Namespace Request
Namespace: rcx_one

##### Description
Collections developed on and provided via http://git.rcx.one

##### GitHub Org Link
https://github.com/rcx-one

##### Admins
e1k3

**Comment by E1k3** [comment]
Just checking if this request is missing information, because the documentation states
> A team member will review the request and create the new namespace within 1 to 2 business days.

A short update would be appreciated.
Thank You!

**Comment by alisonlhart** [comment]
Namespace created: https://galaxy.ansible.com/rcx_one
