### ISSUE TITLE
namespace: sol1_ansible

### ISSUE THREAD

**Issue by joshsol1** [ansible/galaxy#3167]
## Namespace Request
Namespace: sol1_ansible

##### Description
Collections supplied by Sol1 Pty Ltd

GitHub Org Link
https://github.com/sol1-ansible

Admins
joshsol1
davekempe

**Comment by joshsol1** [comment]
Just touching base to see if I need to add anything else to get this setup?

**Comment by joshsol1** [comment]
hello? any chance we can get an update?

**Comment by joshsol1** [comment]
this is really holding up some internal projects, I don't know how to get more traction on this to get this setup.. Halp please.

**Comment by alisonlhart** [comment]
Hello! Apologies for the delay.

Namespace created: https://galaxy.ansible.com/sol1_ansible
