### ISSUE TITLE
Rename the namespace from fp_secure_flexedge_sdwan to fp_flexedge_secure_sdwan

### ISSUE THREAD

**Issue by fp-flexedge-secure-sdwan** [ansible/galaxy#3172]
## Namespace Request
Namespace: fp-flexedge-secure-sdwan

##### Description

Automation of Forcepoint Next Generation Firewall NGFW using SMC api in Ansible.

##### GitHub Org Link

https://github.com/fp-flexedge-secure-sdwan/ngfw_smc_ansible

##### Admins

The namespace created automatically initially was fp_secure_flexedge_sdwan with respect to the github account provided. However, now we have changed the github account name to fp-flexedge-secure-sdwan. Therefore the new namespace name should be fp_flexedge_secure_sdwan. This is not displayed on the top right corner of ansible galaxy webpage.
Kindly requesting you to change the namespace name.
![image](https://github.com/ansible/galaxy/assets/135787113/6033ea46-1bad-43a2-b1f5-21521802470d)

**Comment by alisonlhart** [comment]
Hello, 

The top right shows your account name. Galaxy account names cannot be changed from the original name of the Github account used. Namespace names also cannot be changed. 

However, we can create a new namespace for you under `fp-flexedge-secure-sdwan` and assign your account `fp_secure_flexedge_sdwan` to it as an owner.

**Comment by thedoubl3j** [comment]
@fp-flexedge-secure-sdwan any update here or are we good to close?

**Comment by fp-flexedge-secure-sdwan** [comment]
Yes, we can close this now. Thanks!
