### ISSUE TITLE
namespace request for company/organisation

### ISSUE THREAD

**Issue by mho21** [ansible/galaxy#3175]
## Namespace Request
Namespace: mhx

##### Description
roles and collections maintained by MHx Operations GmbH

##### GitHub Org Link
https://github.com/MHx-Operations

##### Admins
https://galaxy.ansible.com/mho21

**Comment by thedoubl3j** [comment]
done @mho21 it should show up under my content for you now

**Comment by mho21** [comment]
@thedoubl3j Thank you for your fast response!
