### ISSUE TITLE
Request a new namespace for my GitHub Org

### ISSUE THREAD

**Issue by santiagomr** [ansible/galaxy#3176]
## Namespace Request
Namespace: `LibreDevOps`

##### Description
DevOps and freedom

##### GitHub Org Link
https://github.com/LibreDevOps

##### Admins
`santiagomr4` on Ansible Galaxy ([santiagomr](https://github.com/santiagomr) on GitHub)

**Comment by thedoubl3j** [comment]
done @santiagomr though we can't allow upper case letters due to python things so the name space is `libredevops` instread.
