### ISSUE TITLE
Unable to create namespace or add the same as provider namespace

### ISSUE THREAD

**Issue by anugram** [ansible/galaxy#3181]
## Namespace Request
Namespace: thalesgroup

##### Description
Namespace for adding the Thales data security platform's API modules i.e. CipherTrust Manager

##### GitHub Org Link
https://github.com/ThalesGroup

##### Admins
anugram

**Comment by anugram** [comment]
Bumping this up a bit. Any idea when you would be able to have a look into this ticket? Thanks.

**Comment by anugram** [comment]
Hey guys, checking in again. Thanks.

**Comment by thedoubl3j** [comment]
@anugram done, it should appear in your "My content" ribbon on galaxy.

**Comment by anugram** [comment]
@thedoubl3j Thanks and really appreciate it. 
I can now see the required namespace in My Content now. Thanks again.
