### ISSUE TITLE
Request a Namespace

### ISSUE THREAD

**Issue by 532910** [ansible/galaxy#3182]
## Namespace Request
Namespace: nspcc

##### Description

Neo SPCC – R&D team developing an open-source truly decentralized cloud platform and supporting the Neo core

##### GitHub Org Link

https://github.com/nspcc-dev

##### Admins

https://galaxy.ansible.com/sami_nspcc
https://galaxy.ansible.com/532910
https://galaxy.ansible.com/aprasolova

**Comment by 532910** [comment]
What's up?

**Comment by thedoubl3j** [comment]
done @532910
