### ISSUE TITLE
namespace: osx_provisioner (galaxy-dev.ansible.com)

### ISSUE THREAD

**Issue by niall-byrne** [ansible/galaxy#3183]
## Namespace Request
Namespace: osx_provisioner 

##### Description
I have this namespace on the prod server, could I kindly add this to dev server?

##### GitHub Org Link
https://github.com/osx-provisioner

##### Admins
niall-byrne

Thanks!

**Comment by thedoubl3j** [comment]
done @niall-byrne usual statements around galaxy-dev, it is a dev server and its status/health are liable to change. do NOT depend on it as DB dumps/downtime can occur without notice (unlikely as the work for galaxy_ng transition continues but again, don't depend on a dev server)

**Comment by niall-byrne** [comment]
Thanks!
