### ISSUE TITLE
namespace: stackbuilders

### ISSUE THREAD

**Issue by sestrella** [ansible/galaxy#3187]
## Namespace Request
Namespace: stackbuilders

##### Description
Our team strives to push the boundaries of the software industry through quality, pragmatic custom solutions that bring the visions of our clients to life.

##### GitHub Org Link
http://github.com/stackbuilders/

##### Admins
- Galaxy: https://galaxy.ansible.com/sestrella
  GH: https://github.com/sestrella

**Comment by thedoubl3j** [comment]
@sestrella that namespace already exists, I will add you as an admin since GH profile shows you are part of stackbuilders public org.

**Comment by sestrella** [comment]
@thedoubl3j thank you!
