### ISSUE TITLE
Namespace Request: serversideup

### ISSUE THREAD

**Issue by jaydrogers** [ansible/galaxy#3189]
## Namespace Request
Namespace: 
```
serversideup
```

##### Description

```
Quality tutorials & resources. No BS.
```

##### GitHub Org Link

https://github.com/serversideup/

##### Admins

- https://galaxy.ansible.com/jaydrogers

**Comment by jaydrogers** [comment]
Just bumping this in case it got buried from me posting last week on a Friday evening.

The docs said 1-2 business days, so I wanted to make sure it came through okay.

Thanks for your help & support 😃

**Comment by thedoubl3j** [comment]
done @jaydrogers everything came through fine, we are gonna have to update those docs since we are only 2 people now that also have other obligations. apologies for the delay

**Comment by jaydrogers** [comment]
Thanks for your help @thedoubl3j!

I appreciate your help! Have a great weekend 😎
