### ISSUE TITLE
Request for namespace

### ISSUE THREAD

**Issue by crypto-services** [ansible/galaxy#3190]
## Namespace Request
Namespace: republic

##### Description
Republic Crypto Runtime is a platform that simplifies access to the blockchain economy—a portal for staking tokens, white-labeling validators, and integrating our arsenal into any product.

##### GitHub Org Link
[Republic Crypto Github](https://github.com/republic-crypto)

##### Admins
crypto-services

##### Background
We are looking to provide a collection that simplifies deploying and configuring blockchain infrastructure with a collection called crypto under the namespace republic. 

##### Company Link
[Republic Crypto Website](https://republiccrypto.com)

##### Team Email
runtime-support@republiccrypto.com

**Comment by thedoubl3j** [comment]
done @crypto-services

**Comment by crypto-services** [comment]
Thank you!!
