### ISSUE TITLE
Request for namespace rename or lowercase

### ISSUE THREAD

**Issue by alexandermeindl** [ansible/galaxy#3191]
## Namespace Request
Namespace: alphanodes

##### Description
Professional Services with Open Source

##### GitHub Org Link
https://github.com/alphanodes

##### Admins
alexandermeindl

We already have namespace `AlphaNodes` (with upper letter), see https://galaxy.ansible.com/AlphaNodes . This is because our github company name was with upper letters. We want to use lower letters for the existing namespace, because we cannot import collections (because namespaces only allow lower case letters).
If renaming is not possible maybe a new additional name with lower letters would be a solution.

**Comment by alexandermeindl** [comment]
Just more information about the problem. If I publish a collection, the following error occurs:

```
ansible-galaxy collection publish alphanodes-tasks-1.0.0.tar.gz -vvvv
ansible-galaxy [core 2.15.1]
  config file = None
  configured module search path = ['/Users/alex/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/alex/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-galaxy
  python version = 3.11.4 (main, Jun 20 2023, 16:59:59) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/usr/local/opt/python@3.11/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
No config file found; using defaults
Initial connection to galaxy_server: https://galaxy.ansible.com
Opened /Users/alex/.ansible/galaxy_token
Galaxy token file /Users/alex/.ansible/galaxy_token malformed, unable to read it
Calling Galaxy at https://galaxy.ansible.com/api/
Found API version 'v1, v2' with Galaxy server default (https://galaxy.ansible.com/api/)
Publishing collection artifact '/Users/alex/dev/ansible.tasks/alphanodes-tasks-1.0.0.tar.gz' to default https://galaxy.ansible.com/api/
Calling Galaxy at https://galaxy.ansible.com/api/v2/collections/
ERROR! Error when publishing collection to default (https://galaxy.ansible.com/api/) (HTTP Code: 400, Message: Namespace "alphanodes" does not exist. Code: invalid)
```

**Comment by alexandermeindl** [comment]
If I upload the collection tarball, I get this error:

<img width="602" alt="invalid_namesapce" src="https://github.com/ansible/galaxy/assets/205221/94f76163-a993-43c6-80dd-37b9b09f18fc">

I can now select a lower case company name in settings:

<img width="573" alt="settings" src="https://github.com/ansible/galaxy/assets/205221/2ba38456-c458-42c4-9a45-681c5323cf79">

But this does not work - same result as before: "invalid Namespace "alphanodes" does not exist."

Is there a known problem or is there anything missing on my side to publish a collection with namespace `alphanodes`? (I am the owner of this namespace)

**Comment by thedoubl3j** [comment]
@alexandermeindl this should be resolved now. since the old namespace contained no collection artifacts, I was able to rename it. also, provider namespaces are not galaxy namespaces, hence why it is throwing that error. those are just namespaces in github that can sync roles to the namespace. we might be able to change some wording around in the UI to make that a bit more clearer.
