### ISSUE TITLE
SilexData Namespace Request

### ISSUE THREAD

**Issue by mhyclak-silex** [ansible/galaxy#3194]
## Namespace Request
Namespace: silexdata

##### Description
Silex Data Solutions - https://www.silexdata.com/

##### GitHub Org Link
[SilexDataTeam](https://github.com/SilexDataTeam)

##### Admins
- mhyclak-silex
- kpavon-silex
- ljsilex

**Comment by alisonlhart** [comment]
Namespace created: https://galaxy.ansible.com/silexdata
