### ISSUE TITLE
`netscaler` namespace request

### ISSUE THREAD

**Issue by sumanth-lingappa** [ansible/galaxy#3196]
## Namespace Request
Namespace: netscaler

##### Description
Ansible Collection for NetScaler devices

##### GitHub Org Link
https://github.com/netscaler/

##### Admins
sumanth-lingappa

**Comment by sumanth-lingappa** [comment]
Hello @alisonlhart and @thedoubl3j, do I have any update on this request?

**Comment by alisonlhart** [comment]
Namespace created: https://galaxy.ansible.com/netscaler.
