### ISSUE TITLE
Namespace Request

### ISSUE THREAD

**Issue by ugsto** [ansible/galaxy#3201]
## Namespace Request
Namespace: ugsto

##### Description
A personal namespace dedicated to various utility scripts and configurations.

##### GitHub Org Link
https://github.com/ugsto-org

##### Admins
- ugsto

**Comment by alisonlhart** [comment]
This namespace exists already: https://galaxy.ansible.com/ugsto

The requested admin `ugsto` is an admin of this namespace.
