### ISSUE TITLE
Requesting the smallstep namespace

### ISSUE THREAD

**Issue by jdoss** [ansible/galaxy#3203]
## Namespace Request
Namespace: smallstep

##### Description
End-to-end encryption for distributed applications and the people who manage them.

##### GitHub Org Link
https://github.com/smallstep

##### Admins
jdoss
dopey
tashian
joshdrake

**Comment by jdoss** [comment]
Sorry, can you add carl@smallstep.com to the admin list as well.

**Comment by thedoubl3j** [comment]
@jdoss we will need galaxy usernames for admins, not email addresses. galaxy uses github for auth and doesn't see email addresses.

**Comment by jdoss** [comment]
My bad @thedoubl3j here ya go:

jdoss
dopey
tashian
joshdrake

Do they need to sign up for Galaxy first or can they do that after they are added to the namespace?

**Comment by jdoss** [comment]
I just asked them to signup first. I will update this issue once they have Galaxy usernames. Sorry for the troubles!

**Comment by jdoss** [comment]
Hey @thedoubl3j the users

jdoss
dopey
tashian
joshdrake

should all be good to go in Galaxy. Thanks!!

**Comment by chynasan** [comment]
Howdy!

I've added the smallstep namespace with the users as requested: https://galaxy.ansible.com/smallstep.

**Comment by jdoss** [comment]
Thank you @chynasan!!
