### ISSUE TITLE
namespace: FIXME

### ISSUE THREAD

**Issue by AllRWeak** [ansible/galaxy#3204]
## Namespace Request
Namespace: cs

##### Description
Clarified Security Collections & Roles

##### GitHub Org Link
https://github.com/ClarifiedSecurity

##### Admins
AllRWeak - https://galaxy.ansible.com/allrweak

**Comment by thedoubl3j** [comment]
hey @AllRWeak 2 character namespaces are not allowed, the minimum character amount is 3. we did just check docs and it says 2 but I can confirm when attempting to create the namespace that it is 3. I opened an issue to update the docs

**Comment by alisonlhart** [comment]
Namespace created: https://galaxy.ansible.com/clarified
