### ISSUE TITLE
namespace: caffeinated-labs

### ISSUE THREAD

**Issue by jadyndev** [ansible/galaxy#3205]
## Namespace Request
Namespace: `caffeinated-labs`

##### Description
made with :heart: and :coffee:

##### GitHub Org Link
https://github.com/caffeinated-labs

##### Admins
@jadyndev

**Comment by alisonlhart** [comment]
Namespace Created! The dash was changed to an underscore to accommodate our naming requirements. 

https://galaxy.ansible.com/caffeinated_labs
