### ISSUE TITLE
Request for deleting collection or versions

### ISSUE THREAD

**Issue by AllRWeak** [ansible/galaxy#3207]
Hello

I saw a couple of similar issues https://github.com/ansible/galaxy/issues/2986 & https://github.com/ansible/galaxy/issues/3105

I would also like all of the older versions before v1.1.1 do be deleted from https://galaxy.ansible.com/clarified/core here. If it is possible to delete the whole collection then I'd like that otherwise just version before 1.1.1

**Comment by thedoubl3j** [comment]
this capability will come in the deployment of galaxy_ng for users (both for versions and whole collections). We currently cannot delete unless it is a security concern, this is due to the nature of the current system and how it handles artifacts in the DB.
