### ISSUE TITLE
Namespace Request: cube_exchange

### ISSUE THREAD

**Issue by rickdavis404-cube** [ansible/galaxy#3211]
## Namespace Request
Namespace: cube_exchange

##### Description
Official Cube Exchange Collection for Ansible

##### GitHub Org Link
https://github.com/cubexch

##### Admins
- rickdavis404-cube
- wquark

**Comment by alisonlhart** [comment]
Namespace created: https://galaxy.ansible.com/cube_exchange

**Comment by rickdavis404-cube** [comment]
@alisonlhart, sorry for the hassle, but would it be possible to rename this namespace to match our GH org? `cube_exchange` --> `cubexch`
