### ISSUE TITLE
Creating a new Torque namespace

### ISSUE THREAD

**Issue by shirel-m** [ansible/galaxy#3213]
## Namespace Request
Namespace: torque

##### Description
Roles and collections by Quali Torque

##### GitHub Org Link
https://github.com/QualiTorque

##### Admins
https://galaxy.ansible.com/shirel_m
https://galaxy.ansible.com/johnathanvidu

**Comment by chynasan** [comment]
Hello!

I've created the namespace as requested: https://galaxy.ansible.com/torque
