### ISSUE TITLE
Namespace Request: ydb_platform

### ISSUE THREAD

**Issue by artgromov** [ansible/galaxy#3215]
## Namespace Request
Namespace: ydb_platform

##### Description

Official YDB Platform namespace for Ansible Galaxy collections.

##### GitHub Org Link

https://github.com/ydb-platform/

##### Admins

artgromov

**Comment by chynasan** [comment]
Hello,

I have created the namespace as requested: https://galaxy.ansible.com/ydb_platform

Have a good weekend!
