### ISSUE TITLE
dettonville

### ISSUE THREAD

**Issue by lj020326** [ansible/galaxy#3216]
## Namespace Request
Namespace: dettonville

##### Description
Dettonville contributed collections

##### GitHub Org Link
https://github.com/dettonville/

##### Admins
lee.james.johnson@gmail.com

**Comment by chynasan** [comment]
Hello,

For Galaxy, we can search for and add admins by github username rather than by email.
Would you like me to make lj020326 an admin?

Thanks,
Chyna

**Comment by lj020326** [comment]
Yes, if you could please do that, that would be great.

**Comment by chynasan** [comment]
Hello,

I have created the namespace as requested: https://galaxy.ansible.com/dettonville
