### ISSUE TITLE
New namespace for Hyperledger

### ISSUE THREAD

**Issue by ryjones** [ansible/galaxy#3221]
## Namespace Request
Namespace: hyperledger

##### Description
Official Hyperledger Foundation Collections for Ansible

##### GitHub Org Link
https://github.com/hyperledger

##### Admins
hyperledger-bot
ryjones

**Comment by chynasan** [comment]
Hello,

I have created your namespace as requested: https://galaxy.ansible.com/hyperledger

**Comment by benjsmi** [comment]
Sorry to bother every one, but this namespace https://galaxy.ansible.com/hyperledger seems redundant with this namespace: https://galaxy.ansible.com/hyperledger_labs... Given that the code is actually coming from https://github.com/hyperledger-labs/fabric-ansible-collection, I would suggest sunsetting/removing the https://galaxy.ansible.com/hyperledger  namespace.  @ryjones , what do you think?

**Comment by chynasan** [comment]
Hello,

I wanted to chime in here and let you know that because there are published collections in https://galaxy.ansible.com/hyperledger, we cannot remove it.

**Comment by ryjones** [comment]
Hi - there will be more items published into both. I appreciate @benjsmi 's concern; however, I will be working with the other projects (Bevel, Firefly, Cactus) to publish to Galaxy. Instead of making one request now and one later, I made two at once.

Also - against my wishes, labs is publishing into the main space. It was easier than making all of the edits to get them publishing into the lab space, then once the repo migrates, un-doing the changes.
