### ISSUE TITLE
BeyondTrust namespace

### ISSUE THREAD

**Issue by arianehanlon** [ansible/galaxy#3227]
## Namespace Request
Namespace: beyondtrust

##### Description
BeyondTrust is the worldwide leader in Privileged Access Management.

##### GitHub Org Link
https://github.com/beyondtrust

##### Admins
arianehanlon
ipowellBT

**Comment by thedoubl3j** [comment]
@arianehanlon namespace created, it can be found in the "My Content" for each user.
