### ISSUE TITLE
Requesting Additional Namespaces : Netcraftsmen

### ISSUE THREAD

**Issue by joelwking** [ansible/galaxy#3230]
## Namespace Request
Namespace: netcraftsmen

##### Description
NetCraftsmen, a BlueAlly company, provides  IT consulting and solutions.

##### GitHub Org Link
https://github.com/netcraftsmen

##### Admins
- Joel W. King @joelwking
- Dan Wade @dannywade

**Comment by chynasan** [comment]
Hello, 

I have created this namespace as requested: https://galaxy.ansible.com/netcraftsmen

**Comment by joelwking** [comment]
Thank you!
