### ISSUE TITLE
namespace: biptec

### ISSUE THREAD

**Issue by levkohimins** [ansible/galaxy#3234]
## Namespace Request
Namespace: biptec

##### Description
Biptec OÜ

##### GitHub Org Link
https://github.com/biptec

##### Admins
levko.himins@biptec.com @levkohimins

**Comment by chynasan** [comment]
Hello, I have created the biptec namespace as requested: https://galaxy.ansible.com/biptec

**Comment by lev-ok** [comment]
@chynasan Thank you!
