### ISSUE TITLE
Mark community.kubevirt as deprecated

### ISSUE THREAD

**Issue by 0xFelix** [ansible/galaxy#3240]
### Use Case

The `community.kubevirt` collection should be marked as deprecated on Ansible Galaxy, as it was replaced by the `kubevirt.core` collection. See also https://github.com/ansible-community/community-topics/issues/270 as a justification for marking it as deprecated.

### Proposed Solution

Mark the `community.kubevirt` collection as deprecated on Ansible Galaxy, so it is not shown anymore in searches with the default parameters (`deprecated == false`).

**Comment by Andersson007** [comment]
+1

**Comment by 0xFelix** [comment]
The collection was marked as deprecated, thanks @Andersson007!
