### ISSUE TITLE
Please add our organization as namespace to Galaxy

### ISSUE THREAD

**Issue by ms-automatics** [ansible/galaxy#3242]
## Namespace Request
Namespace: automatics_ai

##### Description
No more stupid routine tasks! Automate your SAP Basis operation!

##### GitHub Org Link
https://github.com/automatics-ai

##### Admins
ms-automatics (manuel.sanz@automatics.ai)

**Comment by chynasan** [comment]
Howdy!

I have created the namespace as requested: https://galaxy.ansible.com/automatics_ai

Thanks! :)

**Comment by ms-automatics** [comment]
Many thanks! :)
