### ISSUE TITLE
HidraCloud

### ISSUE THREAD

**Issue by JoseCarlosGarcia95** [ansible/galaxy#3250]
## Namespace Request
Namespace: hidracloud

##### Description
I want to publish an ansible role for my project, hidra: https://github.com/hidracloud/ansible-role-hidra
##### GitHub Org Link
https://github.com/hidracloud/

##### Admins
JoseCarlosGarcia95

**Comment by chynasan** [comment]
Hello! Sorry for the delay, but this has been created! https://galaxy.ansible.com/ui/namespaces/hidracloud/
