### ISSUE TITLE
namespace: rokku_cz (or rokkucz)

### ISSUE THREAD

**Issue by chladic** [ansible/galaxy#3251]
## Namespace Request
Namespace: rokku_cz

##### Description
We update veeam plugins for ansible to support more features

##### GitHub Org Link
https://github.com/rokku-cz

##### Admins
chladic

Looks like namespace was created with hyphen and I cant add content there

<img width="1505" alt="image" src="https://github.com/ansible/galaxy/assets/26329455/8940b542-bd61-4603-bf8d-fc8cc7378cc6">

Thanks a lot for renaming it

**Comment by chynasan** [comment]
Hi,

I created the new galaxy namespace: https://galaxy.ansible.com/rokku_cz

The screenshot you included is the provider namespace (github), rather than the galaxy namespace.
The namespace I just created is the only Ansible galaxy namespace attached to the name Rokku.
