### ISSUE TITLE
New namespace request

### ISSUE THREAD

**Issue by mattgeddes** [ansible/galaxy#3252]
## Namespace Request
Namespace:  versatus

##### Description
Versatus Labs Web3 Compute Platform

##### GitHub Org Link
https://github.com/versatus

##### Admins
mattgeddes

**Comment by mattgeddes** [comment]
Can we also make mikehostetler an admin too? He just created his galaxy account. Thanks.

**Comment by chynasan** [comment]
Hello,

I have created the namespace as requested: https://galaxy.ansible.com/versatus

I have added both  mattgeddes and mikehostetler as admins. 

Have a good weekend!

**Comment by mattgeddes** [comment]
Hi @chynasan . I don't see the `versatus` namespace listed under My Namespaces in the Galaxy NG UI, nor does @mikehostetler. I don't see the namespace when I follow the link above (https://galaxy.ansible.com/versatus) or when constructing a URL to match the pattern used when browsing other namespaces (https://galaxy.ansible.com/ui/namespaces/versatus for example). Does something else need to happen for this change to take effect? Thanks for your help!
