### ISSUE TITLE
`publish` is broken

### ISSUE THREAD

**Issue by charlesrocket** [ansible/galaxy#3255]
##### SUMMARY
CLI failing to push

##### STEPS TO REPRODUCE
Push a collection

##### EXPECTED RESULTS
Published collection

##### ACTUAL RESULTS
```
ERROR! Error when publishing collection to default (https://galaxy.ansible.com/api/) (HTTP Code: 403, Message: You do not have permission to perform this action. Code: permission_denied)
```

Also noticed a copy of my username on the platform, with `0` suffix.

**Comment by charlesrocket** [comment]
Same with GH action (https://github.com/ansible/ansible-publish-action/issues/3)

**Comment by charlesrocket** [comment]
Apparently v2 is no more but this repo still looks like current (while NG docs touching beta publishing exclusively).

**Comment by freemanlatrell** [comment]
I'm seeing this also. When logging into the UI, it looks like I'm no longer the owner of my previous namespace `freemanlatrell`, and now only have access to a new namespace called `freemanlatrell1` that I didn't create.

![image](https://github.com/ansible/galaxy/assets/24191850/5c19ab03-a2b5-4f71-99b1-a3aaf51c6c28)

**Comment by alisonlhart** [comment]
Hello all, this is a known issue occurring with some namespaces after the data migration to Galaxy NG. Please relay this over to a topic on [forum.ansible.com](https://forum.ansible.com/latest) where the Galaxy Team will quickly assist. Thanks!

**Comment by ddimatos** [comment]
@freemanlatrell - I have added you to the topic [here](https://forum.ansible.com/t/ibm-namespace-in-galaxy-ng-has-lost-most-of-its-users-and-owners/1474) , lets wait how they want us to proceed.
