### ISSUE TITLE
Request to create an org. namespace

### ISSUE THREAD

**Issue by marianavillarp** [ansible/galaxy#3256]
Hi, I would like to create a new namespace for the **ibm-messaging** org.

## Namespace Request
Namespace: **ibm-messaging** or **ibm_messaging**

##### Description
Community around IBM Messaging products.

##### GitHub Org Link
https://github.com/ibm-messaging

##### Admins
@marianavillarp
@stewmcl
@rcoppen

**Comment by thedoubl3j** [comment]
hey @marianavillarp since the new deployment, we have had to pause galaxy namespace creation to let the team address bugs that have come from the release, once we are able to create them again (timeline is fuzzy but hoping in a week or 2)we will come back through all requests and get them created.

**Comment by chynasan** [comment]
Hi @marianavillarp!

I am happy to report that we are able to create namespaces again, so I've gone ahead and created https://galaxy.ansible.com/ui/namespaces/ibm_messaging/ as per your request, and added the admins listed in your original request.

**Comment by marianavillarp** [comment]
thank you!
