### ISSUE TITLE
namespace: pokerops

### ISSUE THREAD

**Issue by wpninfra** [ansible/galaxy#3258]
## Namespace Request
Namespace: pokerops

##### Description
Hello team. We would like to request a new namespace called pokerops. Thank you

##### GitHub Org Link
https://github.com/pokerops

##### Admins
wpninfra
carlosgo13
teddyphreak

**Comment by chynasan** [comment]
Hello, 

I have created https://galaxy.ansible.com/ui/namespaces/pokerops/ as requested, and added the admins listed.

**Comment by wpninfra** [comment]
Thank you for your help.
