### ISSUE TITLE
New Collection Release for community.mongodb is not pushed to Galaxy

### ISSUE THREAD

**Issue by rhysmeister** [ansible/galaxy#3259]
##### SUMMARY
New collection version, publish via tag, has not been pushed to Galaxy. I prepared a release as usual, merged to master and then tagged this with the version 1.6.3. This new version has not made it to the Galaxy website, 1.6.2 being the latest version available.

Galaxy Page for Collection: https://galaxy.ansible.com/ui/repo/published/community/mongodb/
My tagged release: https://github.com/ansible-collections/community.mongodb/releases/tag/1.6.3
PR: https://github.com/ansible-collections/community.mongodb/pull/604
Ansible Third Party Check: https://ansible.softwarefactory-project.io/zuul/buildset/34d6c9fee1984057b4b71a55fba405a8 (all good)

##### STEPS TO REPRODUCE
I performed the release the same way (noted in project README.md)

- Create a new branch
- Update galaxy.yml with version and any other appropriate info
- Update changelogs/changelog.yaml
- Update CHANGELOG.rst
- Create a pull request
- Review and merge when happy
- Tag release on the master branch

##### EXPECTED RESULTS
Collection version 1.6.3 to be available in collection

##### ACTUAL RESULTS
No release is pushed to Galaxy. I have been unable to find any clue or problem as to why this might be.

**Comment by felixfontein** [comment]
@rhysmeister this should work again since Friday evening. (The problem was that the user account used by Zuul to publish collections lost access to the namespaces. See this thread on the forum: https://forum.ansible.com/t/bot-used-for-publishing-has-lost-namespace-access/1413)

**Comment by rhysmeister** [comment]
It's there now: https://galaxy.ansible.com/ui/repo/staging/community/mongodb/

Fix:

```bash
git tag -d 1.6.3
git push origin :refs/tags/1.6.3
git tag 1.6.3
git push --tags
```
