### ISSUE TITLE
namespace: fausecteam

### ISSUE THREAD

**Issue by F30** [ansible/galaxy#3262]
## Namespace Request
Namespace: fausecteam

##### Description
FAU Security Team: CTF team of Friedrich-Alexander University Erlangen-Nürnberg (FAU)

##### GitHub Org Link
https://github.com/fausecteam

##### Admins
- F30
- rudis

**Comment by chynasan** [comment]
Hey there!

I've created your namespace: https://galaxy.ansible.com/ui/namespaces/fausecteam/?

Sorry about the delay!
