### ISSUE TITLE
IPFS namespace

### ISSUE THREAD

**Issue by hsanjuan** [ansible/galaxy#3263]
## Namespace Request
Namespace: ipfs

##### Description
Namespace to publish ansible roles for the ipfs ecosystem (gateway, kubo nodes, ipfs-cluster nodes etc.)

##### GitHub Org Link
https://github.com/ipfs

##### Admins
@hsanjuan

**Comment by chynasan** [comment]
Hello!

I have created this namespace for you: https://galaxy.ansible.com/ui/namespaces/ipfs/
