### ISSUE TITLE
Cannot upgrade existing collection

### ISSUE THREAD

**Issue by zachary-plencner** [ansible/galaxy#3264]
##### SUMMARY
I'm trying to publish an update to my collection and am receiving the following error:  
ERROR! Galaxy import process failed: duplicate key value violates unique constraint "unique_is_highest"  
DETAIL:  Key (collection_id, is_highest)=(f250c7a0-78a6-4691-a841-4f5ad68e4fca, t) already exists. (Code: UNKNOWN)

The collection I am trying to upgrade is zachary_plencner.k1000

##### STEPS TO REPRODUCE
ansible-galaxy collection build -f  
ansible-galaxy collection publish zachary_plencner-k1000-x.x.x.tar.gz

##### EXPECTED RESULTS
Upgrade my collection with changes

##### ACTUAL RESULTS
Receive the error from the summary and my collection stays on current version. In addition, it seems like it's storing the fact that I tried to upgrade the collection using the same semantic version. For example, if I set the version to 2.3.15 and do the above commands, it will give me the "unique_is_highest" error. When I try to upgrade it again, without changing the version, I receive this message:  
ERROR! Error when publishing collection to published (https://galaxy.ansible.com/api/) (HTTP Code: 400, Message: Artifact already exists Code: invalid)  

When I check Ansible Galaxy though, my collection is still on the old version from months ago.

```

```

**Comment by alisonlhart** [comment]
@zachary-plencner Hello! This was a widespread issue on Galaxy that is now resolved. You should be able to reupload the artifact now.
