### ISSUE TITLE
namespace: umn-community

### ISSUE THREAD

**Issue by cmcfadden** [ansible/galaxy#3266]
## Namespace Request
Namespace: umn-community

##### Description
University of Minnesota community-developed Ansible tooling

##### GitHub Org Link
http://github.com/umn-ansible/umn-rhel9-management/actions

##### Admins
cmcfadden
tjsobeck

**Comment by chynasan** [comment]
Hey there! Namespaces can't have dashes, so I went ahead and created umn_community instead:
https://galaxy.ansible.com/ui/namespaces/umn_community/
