### ISSUE TITLE
API Updates Broken: Duplicate key value violates unique constraint "unique_is_highest"

### ISSUE THREAD

**Issue by crypto-services** [ansible/galaxy#3267]
##### SUMMARY
Attempting to build the and deploy the `republic.infra` collection via github workflows. The first run exited after upload with the error message: `duplicate key value violates unique constraint "unique_is_highest"`

Attempting to re-run returns: `ERROR! Error when publishing collection to default (https://galaxy.ansible.com/api/) (HTTP Code: 400, Message: Collection republic.infra-0.0.4 already exists Code: invalid)`

However this is not the version that is present, `republic.infra-0.0.3` is still the latest

##### STEPS TO REPRODUCE
Via GitHub workflows: ansible-galaxy collection publish --api-key *** republic-infra-*.tar.gz

Our build process has not changed. I had just renewed the API key for `republic.infra` and `republic.crypto`, not sure if that could be a factor. 

##### EXPECTED RESULTS
I expected it to deploy as normal. 

##### ACTUAL RESULTS
It did not deploy, however the API  seems to have saved the binary so it will not accept the latest version.

**Comment by dineshsuthar786** [comment]
We are also facing the same issue while publishing the `oracle.oci` ansible collection to galaxy server. When we tried to publish `oracle.oci-4.34.0` version, we got error message as `ERROR! Galaxy import process failed: duplicate key value violates unique constraint "unique_is_highest"`.

Galaxy import process failure logs - https://galaxy.ansible.com/api/v3/plugin/ansible/imports/collections/018b47d8-15b5-7a17-a3d9-ae958fafeb23/

After retrying to publish `oracle.oci-4.34.0` version, we got error message as `ERROR! Error when publishing collection to default (https://galaxy.ansible.com/api/) (HTTP Code: 400, Message: Artifact already exists Code: invalid)`

**Comment by crypto-services** [comment]
@dineshsuthar786 I managed to get it to deploy by bumping the version and redeploying. Not ideal but at least we can use the collection.

**Comment by dineshsuthar786** [comment]
@crypto-services Bumping the version might not help for us, Then it will be a version mismatch between github repo and galaxy version. I found this article on [Ansible Forum](https://forum.ansible.com/t/could-not-upload-a-new-collection-version-to-ansible-galaxy/1816) and it seems like a global issue affecting Galaxy. As per this article, It will be addressed by https://github.com/pulp/pulp_ansible/pull/1624 PR.

**Comment by crypto-services** [comment]
Ah OK! Ours all done in a GitHub workflow so we don't have a mismatch just a random missed number in our versioning. Not ideal but at least it works again. Looking forward to the fix so things can get back to normal!

**Comment by stewartfrancis** [comment]
Is this addressed?  I see the referenced PR has been merged.  I'm unable to re-upload my collection as it now says that it's a duplicate version.

**Comment by stewartfrancis** [comment]
@jctanner I saw you had commented on the referenced Ansible Forum thread

**Comment by crypto-services** [comment]
As far as I can tell the pulp issue above doesn't address the fact that the failed uploads did successfully upload, but failed while the tar.gz was being unarchived and processed. The tar.gz file still exists in storage, so you can't upload the same version to trigger processing/inclusion. A version bump fixed it for us but this is not possible for many as @dineshsuthar786 explained.

**Comment by domq** [comment]
Trying to deploy [`epfl_si/docker`](https://galaxy.ansible.com/ui/repo/published/epfl_si/docker/) here, and bumping the version number does not help — I keep hitting the duplicate key issue.

<details>
<summary>Excerpt from <code>ansible-galaxy collection publish epfl_si-docker-0.2.1.tar.gz</code></summary>
<pre>
ERROR! Galaxy import process failed: duplicate key value violates unique constraint "unique_is_highest"
DETAIL:  Key (collection_id, is_highest)=(d9364238-cd9d-4ce9-b596-05d5771e7f4b, t) already exists. (Code: UNKNOWN)
</pre>
</details>

**EDIT:** in my case, the successful workaround was to delete the latest version through the Web UI: https://galaxy.ansible.com/ui/my-namespaces/ → Display collections → click on your collection → ⋮ (top right) → Delete version *VERSION* from system

**Comment by jctanner** [comment]
Hi folks, we're still in the process of getting the patch out to production. Here's a list things we typically have to do to get a patch deployed:

1) get the pulp_ansible PR merged https://github.com/pulp/pulp_ansible/pull/1624
2) make a backport for pulp_ansible https://github.com/pulp/pulp_ansible/pull/1625
3) bump the pulp_ansible version in galaxy_ng https://github.com/ansible/galaxy_ng/pull/1950
4) wait for the CI/CD setup to deploy galaxy_ng's master branch to galaxy-dev.ansible.com
5) do QA/QE on dev
6) trigger a deploy to galaxy-stage.ansible.com and do QA/QE there again
7) trigger a deploy to galaxy.ansible.com

We're on step 4 right now and will get through the rest as quick as we can.

**Comment by dineshsuthar786** [comment]
@tannerjc Thanks for the fix, I am able to deploy the latest collection to galaxy and did not face any issue.

**Comment by crypto-services** [comment]
Closing as the issue seems to be in hand. Thanks guys!
