### ISSUE TITLE
Lost access to namespace `checkmk` in galaxy-ng

### ISSUE THREAD

**Issue by robin-checkmk** [ansible/galaxy#3270]
## Namespace Request
Namespace: checkmk

##### Description

After galaxy-ng was deployed to galaxy.ansible.com, I lost access to my `checkmk` namespace.
This might have happened to the admins below as well (but I figure it was just my updated GitHub username that took effect).
Can you double-check the access and let me know what I can do to enable this?
Thanks in advance!

##### GitHub Org Link

https://github.com/Checkmk/

##### Admins

@robin-checkmk
@lgetwan
@godspeed-you
@Max-checkmk

**Comment by robin-checkmk** [comment]
Forum post for cross-reference: https://forum.ansible.com/t/lost-access-to-namespace-checkmk-in-galaxy-ng/2051

**Comment by jctanner** [comment]
I think this should be resolved now. We can follow up in the forum post if not.
