### ISSUE TITLE
namespace: FujitsuNetworkCommunications

### ISSUE THREAD

**Issue by davewink-fujitsu** [ansible/galaxy#3271]
## Namespace Request
Namespace: FujitsuNetworkCommunications

##### Description
Fujitsu Network Communications Collections

##### GitHub Org Link
https://github.com/FujitsuNetworkCommunications

##### Admins
davewink-fujitsu

**Comment by davewink-fujitsu** [comment]
Hello Team.  Is there any update on this?

**Comment by jlmitch5** [comment]
Hello @davewink-fujitsu can you get @dwterwil to ack on this request?  It seems he is the only user in the org currently

**Comment by davewink-fujitsu** [comment]
@jlmitch5   sorry I just changed my status to be public.  you should see me as a owner of the org now.

**Comment by dwterwil** [comment]
David,

Just confirming. There is nothing I need to do. Is this correct?

Thanks,

David T.

**Comment by davewink-fujitsu** [comment]
No I do not think there is anything for you to do.

**Comment by davewink-fujitsu** [comment]
@jlmitch5 Can this Namespace be created now?

**Comment by chynasan** [comment]
Hello,

We were able to create the namespace: https://galaxy.ansible.com/ui/namespaces/fujitsunetworkcommunications/
