### ISSUE TITLE
namespace: infisical

### ISSUE THREAD

**Issue by maidul98** [ansible/galaxy#3278]
## Namespace Request
Namespace: infisical

##### Description
The open-source secret management platform: Sync secrets/configs across your team/infrastructure and prevent secret leaks.

##### GitHub Org Link
https://github.com/Infisical

##### Admins
maidul98

**Comment by maidul98** [comment]
Hello team, any updates on this?

**Comment by chynasan** [comment]
Hey there, sorry for the delay!

This namespace has been created: https://galaxy.ansible.com/ui/namespaces/infisical/
