### ISSUE TITLE
Two namespaces created after migration to Galaxy NG 

### ISSUE THREAD

**Issue by karolpivo** [ansible/galaxy#3280]
##### SUMMARY
After Galaxy NG release there are two namespaces for our Org.  

Original namespace: SlingNode
New namespace: slingnode

We are ok to keep either but we can't publish to SlingNode. We can publish to "slingnode" but when we install the role using

```shell
ansible-galaxy role install  slingnode.ethereum 
```

it installs  the role from SlingNode namespace that we don't have access to.  

##### STEPS TO REPRODUCE

Searching for "slingnode" returns two namespaces: 

https://galaxy.ansible.com/ui/standalone/namespaces/?page=1&page_size=10&sort=-created&keywords=slingnode

##### EXPECTED RESULTS

Only one namespace exists. 

"ansible-galaxy role install" fetches the role from working namespace.

##### ACTUAL RESULTS

Two namespaces are found, one of them is not accessible. 

Installing role using ansible-galaxy role install uses the inaccessible namespace that we cannot update.

```

```

**Comment by thedoubl3j** [comment]
@karolpivo can you create a post https://forum.ansible.com/c/help/6/none with the tag galaxy-ng? that is where the team is actively triageing issues.

**Comment by agarov** [comment]
Hi @karolpivo, we have the same problem for our organization.
Did you find any solution to bypass this ?
Thanks

**Comment by karolpivo** [comment]
Hi @agarov

I've posted in this forum https://forum.ansible.com/tag/galaxy-ng and one of the very helpful Galaxy Devs sorted it out. It needs to be fixed in the backend. 

Here is my post https://forum.ansible.com/t/two-namespaces-created-after-migration-to-galaxy-ng/2142/2

Good luck
