### ISSUE TITLE
nofusscomputing namespace

### ISSUE THREAD

**Issue by jon-nfc** [ansible/galaxy#3283]
## Namespace Request
Namespace: nofusscomputing

##### Description

No Fuss Computing. Using technology to make life easier.

##### GitHub Org Link

https://github.com/NoFussComputing

##### Admins

https://github.com/jon-nfc

**Comment by thedoubl3j** [comment]
done @jon-nfc

**Comment by jon-nfc** [comment]
@thedoubl3j, cheers. As it's not real clear, I can see the namesapce in the collections tab however not in the roles tab. does this namespace also cover roles? if not can you also make the same namespace for roles?

**Comment by jon-nfc** [comment]
bump

>@thedoubl3j, cheers. As it's not real clear, I can see the namesapce in the collections tab however not in the roles tab. does this namespace also cover roles? if not can you also make the same namespace for roles?

question still pending
