### ISSUE TITLE
namespace: redhatci

### ISSUE THREAD

**Issue by tonyskapunk** [ansible/galaxy#3284]
## Namespace Request
Namespace: redhatci

##### Description
RedHat CI - CI tooling

##### GitHub Org Link
https://github.com/redhatci

##### Admins
- fredericlepied
- thekad
- tonyskapunk

**Comment by thedoubl3j** [comment]
done @tonyskapunk and all users listed added as admins

**Comment by tonyskapunk** [comment]
Thanks so much @thedoubl3j !
