### ISSUE TITLE
namespace: Opsmill

### ISSUE THREAD

**Issue by BeArchiTek** [ansible/galaxy#3285]
## Namespace Request
Namespace: Opsmill

##### Description
We believe that a strong data management platform is critical to unleash the full power of infrastructure automation.

##### GitHub Org Link
https://github.com/opsmill

##### Admins
[opsmill-bot](https://galaxy.ansible.com/ui/namespaces/opsmill_bot)
[bearchitek](https://galaxy.ansible.com/ui/namespaces/bearchitek)

**Comment by BeArchiTek** [comment]
Hello,

Do you have any update ?

**Comment by chynasan** [comment]
Hello,

I was able to add this namespace (https://galaxy.ansible.com/ui/namespaces/opsmill/) and made [opsmill-bot](https://galaxy.ansible.com/ui/namespaces/opsmill_bot) an admin, but was not able to add  [bearchitek](https://galaxy.ansible.com/ui/namespaces/bearchitek). 
Have you logged into galaxy as [bearchitek](https://galaxy.ansible.com/ui/namespaces/bearchitek)? That is the most common reason for the user to not show up in the list of possible admins.

**Comment by BeArchiTek** [comment]
Hello,

I already logged in on galaxy with my bearchitek account, https://galaxy.ansible.com/ui/search/?keywords=BeArchiTek

Edit : I was able to add myself, look like the search is key sensitive, so as the account is BeArchiTek and not bearchitek, you didn't find it
