### ISSUE TITLE
namespace: blinklabs

### ISSUE THREAD

**Issue by agaffney** [ansible/galaxy#3286]
## Namespace Request
Namespace: `blinklabs`

##### Description
`Blink Labs`

##### GitHub Org Link
https://github.com/blinklabs-io

##### Admins
`agaffney` (and the same on `galaxy-dev.ansible.com`)

**Comment by chynasan** [comment]
Hello!

I've created the namespace as requested here: https://galaxy.ansible.com/ui/namespaces/blinklabs/ and https://galaxy-dev.ansible.com/ui/namespaces/blinklabs/.

The Galaxy team has requested that I let you know that galaxy-dev has no SLA and may disappear at any moment. They suggested that "galaxy-stage" may be more stable, so I can create the namespace there as well if you'd like.

**Comment by agaffney** [comment]
@chynasan I did not know that `galaxy-stage` was a thing, but I would appreciate the namespace also being created there. I mostly just need a place to test deploy/publish workflows targeting Galaxy

**Comment by chynasan** [comment]
It is done: https://galaxy-stage.ansible.com/ui/namespaces/blinklabs/

Enjoy! :)

**Comment by agaffney** [comment]
@chynasan Thanks!
