### ISSUE TITLE
namespace: nahsilabs

### ISSUE THREAD

**Issue by nahsi** [ansible/galaxy#3289]
## Namespace Request
Namespace: nahsilabs

##### Description
Nahsi Labs

##### GitHub Org Link
https://github.com/nahsilabs

##### Admins
https://galaxy.ansible.com/ui/namespaces/nahsi

**Comment by chynasan** [comment]
I have created the namespace as requested and granted nahsi admin privileges for the namespace: https://galaxy.ansible.com/ui/namespaces/nahsilabs/

**Comment by nahsi** [comment]
@chynasan Hi. It seems that namespace for roles was not created.
Same with https://github.com/ansible/galaxy/issues/3293

![image](https://github.com/ansible/galaxy/assets/28529663/5a0d79e9-da79-433a-bf8e-5f07e2454f45)

**Comment by chynasan** [comment]
Hey! Sorry about this! I've now created the role namespace and made nahsilabs the provider namespace for permissions! https://galaxy.ansible.com/ui/standalone/namespaces/12872/
