### ISSUE TITLE
platforms api endpoint returns 404 not found

### ISSUE THREAD

**Issue by Yannik** [ansible/galaxy#3292]
##### SUMMARY
The `meta/main.yml` of a role created with `ansible-galaxy role init` contains the following:

>   To view available platforms and versions (or releases), visit:
>  https://galaxy.ansible.com/api/v1/platforms/

This url currently returns a 404 error.
 

##### STEPS TO REPRODUCE
Visit https://galaxy.ansible.com/api/v1/platforms/

##### EXPECTED RESULTS
List of platforms should be returned.

##### ACTUAL RESULTS
404 not found error.

**Comment by jctanner** [comment]
We chose to deprecate the platform api and have no ported them over to the galaxy_ng codebase that now powers galaxy.ansible.com.

If you'd like to see the comment removed from the role template, you'll need to file a bug on in the ansible/ansible repo.

**Comment by bkabrda** [comment]
@jctanner can you please explain what is the source of truth location for platform names right now? Thanks!
