### ISSUE TITLE
namespace: fluencelabs

### ISSUE THREAD

**Issue by nahsi** [ansible/galaxy#3293]
## Namespace Request
Namespace: fluencelabs

##### Description
Decentralized Serverless Platform

##### GitHub Org Link
https://github.com/fluencelabs

##### Admins
https://galaxy.ansible.com/ui/namespaces/nahsi

**Comment by chynasan** [comment]
Hello,
I have created https://galaxy.ansible.com/ui/namespaces/fluencelabs/ as requested.

**Comment by chynasan** [comment]
Hey there!

I created the role namespace and set the provider namespace to fluencelabs for permissions! https://galaxy.ansible.com/ui/standalone/namespaces/12873/
