### ISSUE TITLE
Please add EMCL-Research-ITSecLab namespace

### ISSUE THREAD

**Issue by br-olf** [ansible/galaxy#3294]
## Namespace Request
Namespace: EMCL-Research-ITSecLab

##### Description

IT-Security Lab of the EMCL Research Group
##### GitHub Org Link

https://github.com/EMCL-Research-ITSecLab
##### Admins

https://github.com/br-olf
https://github.com/stefanDeveloper

**Comment by chynasan** [comment]
I created https://galaxy.ansible.com/ui/namespaces/emcl_research_itseclab/ - please note that only lowercase letters, numbers, and underscores are allowed namespace characters, so I have adjusted the requested namespace accordingly. 

I have made br-olf and stefanDeveloper namespace admins as requested.
