### ISSUE TITLE
Request for an "entrust" galaxy namespace.

### ISSUE THREAD

**Issue by sapnajainEntrust** [ansible/galaxy#3298]
## Namespace Request
Namespace: entrust

##### Description
Entrust Certificate Authorities Ansible Collection

##### GitHub Org Link
https://github.com/EntrustCorporation

##### Admins
sapnajainEntrust

**Comment by alisonlhart** [comment]
Hello! The namespace has been created here with admin `sapnajainEntrust`: https://galaxy.ansible.com/ui/namespaces/entrust
