### ISSUE TITLE
Unable to import roles anymore: namespace different from github organization

### ISSUE THREAD

**Issue by rascasoft** [ansible/galaxy#3299]
##### SUMMARY

Something has changed in the way imports work for organization roles, and I'm getting Forbidden when importing a role into Galaxy.

- My Galaxy namespace is `mmul` https://galaxy.ansible.com/ui/standalone/namespaces/9440/ (see the ISSUE I opened for creation here: https://github.com/ansible/galaxy/issues/3080).
- My GitHub organization name is `mmul-it` (https://github.com/mmul-it/).
- My GitHub username is `rascasoft` (https://github.com/rascasoft/).
 
I already have three roles imported in Galaxy:

1. https://galaxy.ansible.com/ui/standalone/roles/mmul/kubelab/ -> https://github.com/mmul-it/kubelab
2. https://galaxy.ansible.com/ui/standalone/roles/mmul/kpa_generator/ -> https://github.com/mmul-it/kpa_generator
3. https://galaxy.ansible.com/ui/standalone/roles/mmul/terraform_tfs_generator/ -> https://github.com/mmul-it/terraform_tfs_generator

Before I was able to update the imports using CMD and GitHub Actions, now I'm getting forbidden.

NOTE: for some reason a `mmul-it` namespace (https://galaxy.ansible.com/ui/standalone/namespaces/4735/) with an old role already exists. Surely this causes confusion and needs to be removed.

##### STEPS TO REPRODUCE

```console
$ ansible-galaxy role import -vvvv --role-name mmul.kubelab mmul-it kubelab
ansible-galaxy [core 2.16.0]
  config file = /home/rasca/Git/mmul-it/kubelab/ansible.cfg
  configured module search path = ['/home/rasca/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rasca/Labs/venvs/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/rasca/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/rasca/Labs/venvs/ansible/bin/ansible-galaxy
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/home/rasca/Labs/venvs/ansible/bin/python3)
  jinja version = 3.1.2
  libyaml = True
Using /home/rasca/Git/mmul-it/kubelab/ansible.cfg as config file
Initial connection to galaxy_server: https://galaxy.ansible.com/api/
Opened /home/rasca/.ansible/galaxy_token
Calling Galaxy at https://galaxy.ansible.com/api/
Found API version 'v3, pulp-v3, v1' with Galaxy server beta (https://galaxy.ansible.com/api/)
Calling Galaxy at https://galaxy.ansible.com/api/v1/imports/
ERROR! None (HTTP Code: 403, Message: Forbidden)
```

Token is declared in ansible.cfg:

```console
[galaxy]
server_list = beta

[galaxy_server.beta]
url = https://galaxy.ansible.com/api/
token = <REDACTED>
```

But even if I specify it on the command line it doesn't work:

```console
$ ansible-galaxy role import -vvvv --token <REDACTED> --role-name mmul.kubelab mmul-it kubelab
ansible-galaxy [core 2.16.0]
  config file = /home/rasca/Git/mmul-it/kubelab/ansible.cfg
  configured module search path = ['/home/rasca/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rasca/Labs/venvs/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/rasca/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/rasca/Labs/venvs/ansible/bin/ansible-galaxy
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/home/rasca/Labs/venvs/ansible/bin/python3)
  jinja version = 3.1.2
  libyaml = True
Using /home/rasca/Git/mmul-it/kubelab/ansible.cfg as config file
Initial connection to galaxy_server: https://galaxy.ansible.com/api/
Opened /home/rasca/.ansible/galaxy_token
Calling Galaxy at https://galaxy.ansible.com/api/
Found API version 'v3, pulp-v3, v1' with Galaxy server beta (https://galaxy.ansible.com/api/)
Calling Galaxy at https://galaxy.ansible.com/api/v1/imports/
ERROR! None (HTTP Code: 403, Message: Forbidden)
```

##### EXPECTED RESULTS

A successful import.

##### ACTUAL RESULTS

```console
$ ansible-galaxy role import -vvvv --role-name mmul.kubelab mmul-it kubelab
ansible-galaxy [core 2.16.0]
  config file = /home/rasca/Git/mmul-it/kubelab/ansible.cfg
  configured module search path = ['/home/rasca/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rasca/Labs/venvs/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/rasca/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/rasca/Labs/venvs/ansible/bin/ansible-galaxy
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/home/rasca/Labs/venvs/ansible/bin/python3)
  jinja version = 3.1.2
  libyaml = True
Using /home/rasca/Git/mmul-it/kubelab/ansible.cfg as config file
Initial connection to galaxy_server: https://galaxy.ansible.com/api/
Opened /home/rasca/.ansible/galaxy_token
Calling Galaxy at https://galaxy.ansible.com/api/
Found API version 'v3, pulp-v3, v1' with Galaxy server beta (https://galaxy.ansible.com/api/)
Calling Galaxy at https://galaxy.ansible.com/api/v1/imports/
ERROR! None (HTTP Code: 403, Message: Forbidden)
```

**Comment by oo4abhishek** [comment]
Facing similar issue while importing role on Ansible galaxy

**Comment by stefangweichinger** [comment]
I also hit this: https://github.com/stefangweichinger/ansible-rclone/issues/141

The role is there at: https://galaxy.ansible.com/ui/standalone/roles/stefangweichinger/ansible_rclone/ 

I try to figure out if the id has changed or ... whatever

Help appreciated.

**Comment by rascasoft** [comment]
As explained here https://forum.ansible.com/t/unable-to-import-roles-anymore-namespace-different-from-github-organization/2737/14 situations like the one I described end up in creating mixed environments, where the import works differently based upon the repository.

At the moment I have these associations for my three repositories:

- https://github.com/mmul-it/kubelab -> https://galaxy.ansible.com/ui/standalone/roles/mmul/kubelab/ (correct)
- https://github.com/mmul-it/terraform_tfs_generator -> https://galaxy.ansible.com/ui/standalone/roles/mmul/terraform_tfs_generator/ (correct)
- https://github.com/mmul-it/kpa_generator -> https://galaxy.ansible.com/ui/standalone/roles/mmul-it/kpa_generator/ (NOT correct, note `mmul-it` instead of `mmul`)

So the main issue now is to get some sort of consistency here.

Can someone please provide feedback on this issue?

Many thanks!

**Comment by rascasoft** [comment]
The recent Galaxy release solved the issue, [as explained here](https://forum.ansible.com/t/unable-to-import-roles-anymore-namespace-different-from-github-organization/2737/19), so I'm closing this.
