### ISSUE TITLE
namespace: stewartfrancis

### ISSUE THREAD

**Issue by stewartfrancis** [ansible/galaxy#3300]
## Namespace Request
Namespace: stewartfrancis

##### Description
I previously uploaded a collection to this namespace which I need to delete.  I'm not able to delete it as I'm not an admin for the namespace, and as far as I can tell, the namespace has no admins.  I was hoping to register the namespace so that I can delete the collection from it (which in the previous version of Galaxy I was only able to deprecate).

##### GitHub Org Link
https://github.com/stewartfrancis/

##### Admins
stewartfrancis

**Comment by alisonlhart** [comment]
Hello @stewartfrancis, you are an admin on this namespace and should be able to delete the collection now. Please try out this workflow and let us know if this doesn't work!

**Comment by stewartfrancis** [comment]
Thanks, worked perfectly!
