### ISSUE TITLE
Failed to import roles to newly created pokerops namespace

### ISSUE THREAD

**Issue by carlosgo13** [ansible/galaxy#3304]
Hello everyone.

After successfully created a new namespace called pokerops, I have been unable to import roles to it. I've just tried from webui in galaxy.ansible.com and seems like the namespace is not being found. However, I can see it in my namespaces.

Can you check, please?

Best regards.

**Comment by chynasan** [comment]
Hi there!

I created a roles namespace and set it as provided by pokerops, so it should inherit permissions from the pokerops namespace and you should be able to add roles to it now. Please let us know if that is not the case!
