### ISSUE TITLE
namespace: mirsg

### ISSUE THREAD

**Issue by drmatthews** [ansible/galaxy#3305]
## Namespace Request
Namespace: mirsg

##### Description

Ansible collections maintained by the Medical Imaging Research Software Group at UCL ARC.

##### GitHub Org Link

https://github.com/UCL-MIRSG

##### Admins

drmatthews

Will the new namespace will appear on `galaxy_ng`? I'm submitting the issue here as https://github.com/ansible/galaxy_ng does not have issues enabled.

Thanks!

**Comment by chynasan** [comment]
Hello,

I have created https://galaxy.ansible.com/ui/namespaces/mirsg/

It is in galaxy_ng!
