### ISSUE TITLE
namespace: apisnetworks

### ISSUE THREAD

**Issue by msaladna** [ansible/galaxy#3308]
## Namespace Request
Namespace: apisnetworks

##### Description
Namespace for Apis Networks, INC. (www.apisnetworks.com)

##### GitHub Org Link
https://github.com/apisnetworks

##### Admins
msaladna

**Comment by chynasan** [comment]
Hello,

I have created the namespace as requested.

https://galaxy.ansible.com/ui/namespaces/apisnetworks/
