### ISSUE TITLE
namespace: eclipse_bluechi

### ISSUE THREAD

**Issue by ygalblum** [ansible/galaxy#3309]
## Namespace Request
Namespace: eclipse_bluechi

##### Description
Eclipse BlueChi is a systemd service controller intended for multi-node environments 

##### GitHub Org Link
https://github.com/eclipse-bluechi

##### Admins
ygalblum
mwperina
engelmi
eclipse-bluechi-bot

**Comment by chynasan** [comment]
Hello, I have created the namespace as requested.

https://galaxy.ansible.com/ui/namespaces/eclipse_bluechi/
