### ISSUE TITLE
namespace: omnitoolkit

### ISSUE THREAD

**Issue by panguruh** [ansible/galaxy#3312]
## Namespace Request
Namespace: omnitoolkit

##### Description
Collections and Roles provided by omnitoolkit

##### GitHub Org Link
https://github.com/omnitoolkit

##### Admins
@panguruh

**Comment by chynasan** [comment]
Hello,

I have created the namespace as requested. 
https://galaxy.ansible.com/ui/namespaces/omnitoolkit/
