### ISSUE TITLE
namespace: cloudera

### ISSUE THREAD

**Issue by wmudge** [ansible/galaxy#3316]
## Namespace Request
Namespace: cloudera

##### Description
Manage your [Cloudera Data Platform (CDP)](https://www.cloudera.com/products.html) Public Cloud and Private Cloud resources and services.

##### GitHub Org Link
https://github.com/cloudera-labs

##### Admins
wmudge

(More admins will be added in the near future.)

**Comment by traytorous** [comment]
@wmudge the namespace has been created. Please review it and let me know if it works for you. 
https://galaxy.ansible.com/ui/namespaces/cloudera/

**Comment by wmudge** [comment]
Thank you! I will test in the next day or two.
