### ISSUE TITLE
namespace: vodafone

### ISSUE THREAD

**Issue by tomkivlin** [ansible/galaxy#3317]
## Namespace Request
Namespace: vodafone

##### Description
Namespace for Vodafone (www.vodafone.com)

##### GitHub Org Link
https://github.com/Vodafone

##### Admins
tomkivlin

**Comment by traytorous** [comment]
@tomkivlin the namespace has been created. https://galaxy.ansible.com/ui/namespaces/vodafone/

**Comment by tomkivlin** [comment]
Thanks!
