### ISSUE TITLE
namespace: kit_iai

### ISSUE THREAD

**Issue by Phill93** [ansible/galaxy#3319]
## Namespace Request
Namespace: kit_iai

##### Description
Institute for Automation and Applied Informatics
An institute of the Karlsruhe Institute of Technology (KIT)

##### GitHub Org Link
https://github.com/KIT-IAI

##### Admins
https://github.com/Phill93

**Comment by traytorous** [comment]
@Phill93 the namespace has been created. Please let us know if you need anymore help. -> https://galaxy.ansible.com/ui/namespaces/kit_iai/
