### ISSUE TITLE
namespace: metno

### ISSUE THREAD

**Issue by KjetilKnutsen** [ansible/galaxy#3320]
## Namespace Request
Namespace: metno

##### Description
Roles created by the Norwegian Meteorological Institute

##### GitHub Org Link
https://github.com/metno

##### Admins
KjetilKnutsen
arnsteio

**Comment by traytorous** [comment]
@KjetilKnutsen the namespace has been created. Please let us know if you need anymore help -> https://galaxy.ansible.com/ui/namespaces/metno/
