### ISSUE TITLE
namespace: ednz_cloud

### ISSUE THREAD

**Issue by ednxzu** [ansible/galaxy#3322]
## Namespace Request
Namespace: ednz_cloud

##### Description
Ansible content from ednz-cloud.

##### GitHub Org Link
https://github.com/ednz-cloud

##### Admins
@ednxzu (same username on ansible-galaxy)

**Comment by ednxzu** [comment]
Any news on this one ? :)

**Comment by ednxzu** [comment]
Hi @alisonlhart, @chynasan, @traytorous,

Sorry to bother you with this, but I have some content that would need to be pushed within the coming weeks, ideally to this new namespace so I don't have to re-push it later. 


Thank you in advance, and sorry again for bothering you with this.

**Comment by traytorous** [comment]
Hello @ednxzu! The namespace has been created. Please let us know if we can help you with anything else. https://galaxy.ansible.com/ui/namespaces/ednz_cloud/
