### ISSUE TITLE
namespace: kentik

### ISSUE THREAD

**Issue by jryburn** [ansible/galaxy#3323]
## Namespace Request
Namespace: kentik

##### Description
Namespace for automations in Ansible against the Kentik Network Observability platform.

##### GitHub Org Link
https://github.com/kentik

##### Admins
jryburn

**Comment by traytorous** [comment]
Good evening,
@jryburn the namespace has been created. A link to the namespace is provided below. Please let me know if there is anything we can help you with.

https://galaxy.ansible.com/ui/namespaces/kentik/
