### ISSUE TITLE
namespace: entropia

### ISSUE THREAD

**Issue by jdreichmann** [ansible/galaxy#3327]
## Namespace Request
Namespace: entropia

##### Description
Namespace for Entropia e.V. (CCC Karlsruhe) 

##### GitHub Org Link
https://github.com/entropia/

##### Admins
transcaffeine
promasu

**Comment by chynasan** [comment]
Hello!

I have created the namespace as requested: https://galaxy.ansible.com/ui/namespaces/entropia/
