### ISSUE TITLE
Namespace Request: moc

### ISSUE THREAD

**Issue by hakasapl** [ansible/galaxy#3328]
## Namespace Request
Namespace: moc

##### Description
This active partnership between higher education, medical research centers, government, and industry provides structure and resources that enable a close collaboration between research, development, and operations in a series of interconnected projects. The goal of this collaboration is to provide predictable low cost resources and facilitator support for domain researchers, and more broadly, innovation in the public cloud. https://massopen.cloud/

##### GitHub Org Link
https://github.com/CCI-MOC/

##### Admins
hakasapl

**Comment by epacific1** [comment]
Hello, 

I have created the namespace as requested: https://galaxy.ansible.com/ui/namespaces/moc/

**Comment by hakasapl** [comment]
Thank you!

**Comment by hakasapl** [comment]
@epacific1 is it possible to rename the namespace to CCI-MOC instead of `moc`? Looks like there is a different user on github under `moc` and the profile avatar is showing theirs on the site.

Thank you!

**Comment by epacific1** [comment]
@hakasapl it is not possible to rename the existing namespace. 
The old namespace will be deleted. 

I have created a new namespace for you `cci_moc`
https://galaxy.ansible.com/ui/namespaces/cci_moc/

**Comment by hakasapl** [comment]
That works, thanks!
