### ISSUE TITLE
namespace: badsectorlabs

### ISSUE THREAD

**Issue by kernel-sanders** [ansible/galaxy#3329]
## Namespace Request
Namespace: badsectorlabs

##### Description
Ansible collections and roles published by Bad Sector Labs

##### GitHub Org Link
https://github.com/bad-sector-labs

##### Admins
kernel-sanders (id: `22867`)

**Comment by epacific1** [comment]
Hello, 

I have created the namespace as requested https://galaxy.ansible.com/ui/namespaces/badsectorlabs/

**Comment by kernel-sanders** [comment]
Thank you! Our collection namespace was created correctly, however our role namespace is not a child of our collection namespace.

Collection namespace showing no role namespace: https://galaxy.ansible.com/ui/standalone/namespaces/?provider=badsectorlabs

Role namespace (broken): https://galaxy.ansible.com/ui/standalone/namespaces/13410/

**Comment by epacific1** [comment]
This should now be corrected. Please recheck.

**Comment by kernel-sanders** [comment]
Everything is working. Thank you!
