### ISSUE TITLE
namespace: zpe

### ISSUE THREAD

**Issue by zpe-dnesvera** [ansible/galaxy#3337]
## Namespace Request
Namespace: zpe

##### GitHub Org Link
https://github.com/ZPESystems

##### Admins
zpe_reneneumann, zpe_dnesvera

**Comment by epacific1** [comment]
Hi, 
I am unable to find the usernames provided for admin rights:
zpe_reneneumann, zpe_dnesvera

Reason might be that those users have not logged in the ansible.galaxy.com previously. 
Please let me know once those users have logged in and I can then add them as admins to the zpe namespace requested.

**Comment by zpe-dnesvera** [comment]
Hello,
My bad. Username has hyphens instead of underscore.
zpe-reneneumann, zpe-dnesvera

I already logged to galaxy.ansible.com

**Comment by epacific1** [comment]
Ok, great. I was able to add the admins. 
New namespace has been created: 
https://galaxy.ansible.com/ui/namespaces/zpe/

**Comment by zpe-dnesvera** [comment]
Thank you 😄
