### ISSUE TITLE
 Receive Server Error 500 at Login

### ISSUE THREAD

**Issue by CatalinaSindrilaru** [ansible/galaxy#3338]
When I want to login to galaxy.ansible.com I receive "Server Error 500". My user is 'CatalinaSindrilaru'. I received this error starting yesterday, but in the past I was able to log in. You can help me? 

@alisonlhart 
@chynasan 
@epacific1 
@traytorous

**Comment by alisonlhart** [comment]
@CatalinaSindrilaru I recommend opening a new topic on [forum.ansible.com](https://forum.ansible.com/). The forum is now the best place to get in touch with engineers who work on the Galaxy project, as this is the legacy Galaxy repository we primarily only use for namespace requests.

**Comment by CatalinaSindrilaru** [comment]
> @CatalinaSindrilaru I recommend opening a new topic on [forum.ansible.com](https://forum.ansible.com/). The forum is now the best place to get in touch with engineers who work on the Galaxy project, as this is the legacy Galaxy repository we primarily only use for namespace requests.

I just created an account on forum.ansible.com, but I can't open a new topic. Can you help me?

@alisonlhart
