### ISSUE TITLE
namespace: cse

### ISSUE THREAD

**Issue by klin938** [ansible/galaxy#3340]
## Namespace Request
Namespace: cse

##### Description
UNSW [Computer Science and Engineering](https://www.unsw.edu.au/engineering/our-schools/computer-science-and-engineering)

##### GitHub Org Link
(https://github.com/UNSWComputing)

##### Admins
klin938@gmail.com
kezhang.lin@unsw.edu.au

**Comment by epacific1** [comment]
Hi,
I am unable to find the usernames provided for admin rights:
klin938@gmail.com, kezhang.lin@unsw.edu.au

Reason might be that those users have not logged in the ansible.galaxy.com previously.
Please let me know once those users have logged in and I can then add them as admins to the cse namespace requested.

**Comment by klin938** [comment]
Hi, I have setup both on the galaxy.

d.lin klin938@gmail.com
derlin-unsw kezhang.lin@unsw.edu.au

Please let me know if they work.

Cheers
D

**Comment by epacific1** [comment]
Hello. 
I was able to add the user: derlin-unsw.
The user: d.lin is still not available. 
Please create that user and let me know.

**Comment by klin938** [comment]
Hi there,

I think the actual account name is klin938 (it is displayed as D.LIN). Can you please try agian.

Cheers
D

**Comment by epacific1** [comment]
I was able to add klin938 as a user for the cse namespace. 
You should now have everything in place. 
https://galaxy.ansible.com/ui/namespaces/cse/

**Comment by klin938** [comment]
thank you!
