### ISSUE TITLE
namespace: liquibase

### ISSUE THREAD

**Issue by jandroav** [ansible/galaxy#3342]
## Namespace Request
Namespace: liquibase

We would like to have the liquibase namespace so we can import our liquibase ansible role there.

##### Description
Liquibase is an open-source database-independent library for tracking, managing and applying database schema changes.

##### GitHub Org Link
https://github.com/liquibase

##### Admins
jandroav
jnewton03
liquibot
sayaliM0412

**Comment by epacific1** [comment]
Hi, 

The namespace has been created. 
https://galaxy.ansible.com/ui/namespaces/liquibase/


Please note that the following users were not available on galaxy: 
jnewton03
sayaliM0412
Reason might be that those users have not logged in the ansible.galaxy.com previously.

Currently, there are only two admins defined: 
jandroav
liquibot

To add the two missing admins, please create them as required and update me. 

Thanks

**Comment by jandroav** [comment]
hey @epacific1 ! Done! Thanks a lot for your support! We can close this.
