### ISSUE TITLE
namespace: mitre

### ISSUE THREAD

**Issue by wdower** [ansible/galaxy#3343]
## Namespace Request
Namespace: mitre

##### Description
I would like to create a namespace for the MITRE Corporation.

##### GitHub Org Link
https://github.com/mitre

##### Admins
- @wdower
- @aaronlippold

**Comment by aaronlippold** [comment]
thank you

**Comment by epacific1** [comment]
Hi,

Namespace created as requested: https://galaxy.ansible.com/ui/namespaces/mitre/
