### ISSUE TITLE
namespace: sensa

### ISSUE THREAD

**Issue by gardar** [ansible/galaxy#3346]
## Namespace Request
Namespace: sensa

##### Description
Sensa is a Professional and Managed Services provider founded in Iceland in 2002.

##### GitHub Org Link
(https://github.com/sensaehf)

##### Admins
 - @gardar
 - @gislikarl
 - @Saevar2000

**Comment by traytorous** [comment]
@gardar Namespace has been created. Please go here -> https://galaxy.ansible.com/ui/namespaces/sensa/. Let us know if this works. If it does not please re-open the ticket.

**Comment by gardar** [comment]
Seems to be working, thanks!
