### ISSUE TITLE
namespace: m3i-dev

### ISSUE THREAD

**Issue by BMeach** [ansible/galaxy#3348]
## Namespace Request
Namespace: m3i-dev

##### Description
A Small R&D company

##### GitHub Org Link
https://github.com/M3i-dev

##### Admins
@BMeach

**Comment by traytorous** [comment]
@BMeach Good evening, the namespace you requested cannot be created. This is due to the naming convetions of the namespace. It cannot have a "-" dash in it. Only letters and numbers. Please let me know how you would like to proceed with this.

**Comment by BMeach** [comment]
'm3idev' will work, thank you!

**Comment by traytorous** [comment]
@BMeach Please access the namespace here -> https://galaxy.ansible.com/ui/namespaces/m3idev/
