### ISSUE TITLE
namespace: Create a namespace for organization revboot

### ISSUE THREAD

**Issue by lpalgarvio** [ansible/galaxy#3349]
## Namespace Request
Namespace: revboot

##### Description
Dedicated to Free and Opensource Software development, services and hosting.
Revboot - Tecnologias de Informação e Comunicação, Unipessoal Lda

##### GitHub Org Link
https://github.com/revboot/cloudflare

##### Admins
- @lpalgarvio

Copying and adapting from a fellow contributor,

I'd like to have the namespace revboot on Galaxy and set @lpalgarvio as the admin users. This namespace would be for collections and roles that are owned by our GitHub org - https://github.com/revboot

Still jumpstarting this organization so we do not currently have a website, though we have the domain revboot.com.

Thanks!

Related:
- #1488

**Comment by epacific1** [comment]
Hello,

Namespace created: https://galaxy.ansible.com/ui/namespaces/revboot/
