### ISSUE TITLE
New namespace: OPI

### ISSUE THREAD

**Issue by sknrao** [ansible/galaxy#3350]
## Namespace Request
Namespace: opi

##### Description
Open Programmable Infrastructure (OPI) Project aims to foster a community-driven standards-based open ecosystem for next generation architectures and frameworks based on DPU/IPU-like technologies.

##### GitHub Org Link
https://github.com/opiproject

##### Admins
glimchb
sknrao

**Comment by traytorous** [comment]
Hello @sknrao could you create another name for the namespace. It seems due to the fact of how short the name is it is messing with our filters.

**Comment by glimchb** [comment]
> Hello @sknrao could you create another name for the namespace. It seems due to the fact of how short the name is it is messing with our filters.

@traytorous how about `opiproject` ?

**Comment by traytorous** [comment]
https://galaxy.ansible.com/ui/namespaces/opiproject/
@sknrao  namespace was created. Let me know if you it works.

**Comment by sknrao** [comment]
Yes, opiproject is perfect. Thanks a lot.

**Comment by glimchb** [comment]
> https://galaxy.ansible.com/ui/namespaces/opiproject/ @sknrao namespace was created. Let me know if you it works.

published! all works! thanks!
