### ISSUE TITLE
namespace: get_edi_io

### ISSUE THREAD

**Issue by lueschem** [ansible/galaxy#3351]
## Namespace Request
Namespace: get_edi_io

##### Description
Collections that extend and complement the edi tool.

##### GitHub Org Link
[lueschem](https://github.com/lueschem/)
[get-edi-io](https://github.com/orgs/get-edi-io)

##### Admins
lueschem

**Comment by chynasan** [comment]
Hello,

I have created the namespace as requested: https://galaxy.ansible.com/ui/namespaces/get_edi_io/
