### ISSUE TITLE
namespace: osahris

### ISSUE THREAD

**Issue by mkbrechtel** [ansible/galaxy#3353]
## Namespace Request
Namespace: osahris

##### Description
 Open Source Alliance for Health Research Infrastructure 

##### GitHub Org Link
https://github.com/osahris

##### Admins
@mkbrechtel
@tomraja
@NoDataIsAvailable

**Comment by traytorous** [comment]
@mkbrechtel namespace has been created. However tomraja and NoDataIsAvaialbe cannot be added it seems. Did they sign into galaxy. 

https://galaxy.ansible.com/ui/namespaces/osahris/?tab=access

**Comment by traytorous** [comment]
@mkbrechtel Are there any update on this issue?

**Comment by mkbrechtel** [comment]
> @mkbrechtel Are there any update on this issue?

@traytorous I talked to them and they said they now have a galaxy profile.

**Comment by traytorous** [comment]
@mkbrechtel they have been added to the namespace. Please confirm with them

**Comment by chynasan** [comment]
I am closing this as it appears the original ask has been solved.
