### ISSUE TITLE
namespace: inwx

### ISSUE THREAD

**Issue by inwx-developer** [ansible/galaxy#3356]
Please transfer ownership over the inwx namespace to org owners.

## Namespace Request
Namespace: inwx

##### GitHub Org Link
https://github.com/inwx

##### Admins
inwx-developer

**Comment by chynasan** [comment]
Hello!

Before transferring this to you, as I do not see any indication that you are a contributor or associated with the org, I'd like to confirm this with @ddmler, @marpes and/or @NickUfer. I am going to follow up with them via email as well to approve this before I add you as an administrator to the namespace.

**Comment by NickUfer** [comment]
Hello @chynasan, I can hereby confirm the transfer of the namespace `inwx` to the user `inwx-developer`. I will confirm again via email.

**Comment by chynasan** [comment]
Hi @NickUfer!
 
Thanks so much for your response. I've gone ahead and added [inwx-developer](https://github.com/inwx-developer) to the [inwx namespace](https://galaxy.ansible.com/ui/namespaces/inwx/) in Ansible Galaxy as an administrator. They are able to add and remove other namespace admins and upload collections to Galaxy now.
