### ISSUE TITLE
namespace: digitalegesellschaft

### ISSUE THREAD

**Issue by ryru** [ansible/galaxy#3358]
## Namespace Request
Namespace: digitalegesellschaft

##### Description
Ansible collections and roles published by Digitale Gesellschaft Switzerland. We plan to publish our public DNS resolver configuration soon: https://github.com/DigitaleGesellschaft/DNS-Resolver

##### GitHub Org Link
https://github.com/DigitaleGesellschaft/

##### Admins
- https://github.com/ryru

Thank you

**Comment by epacific1** [comment]
Hi, 

Namespace created as requested: 
https://galaxy.ansible.com/ui/namespaces/digitalegesellschaft/
Admin: ryru

**Comment by ryru** [comment]
looks good, thank you @epacific1 !
