### ISSUE TITLE
namespace: greenitsolutions and opendc

### ISSUE THREAD

**Issue by Support-Green-IT-Solutions** [ansible/galaxy#3359]
## Namespace Request : greenitsolutions
Namespace: greenitsolutions

##### Description
Green IT Solutions fournit aux PME et PMI un bouquet de services et de solutions pour que leur système d'information réponde à toutes leurs attentes.

##### GitHub Org Link
https://github.com/GreenItSolutions

##### Admins
Support-Green-IT-Solutions

## Namespace Request : opendc
Namespace: opendc

##### Description
OpenDC est un datacenter essentiellement constitué de technologie open source.

##### GitHub Org Link
https://github.com/OpenDC-IT

##### Admins
Support-Green-IT-Solutions

**Comment by epacific1** [comment]
Hi, 
Two namespaces created: 
**greenitsolutions**
https://galaxy.ansible.com/ui/namespaces/greenitsolutions/
**opendc**
https://galaxy.ansible.com/ui/namespaces/opendc/

Same Admin for both namespaces: Support-Green-IT-Solutions
