### ISSUE TITLE
namespace: sennadx

### ISSUE THREAD

**Issue by witalloliveira** [ansible/galaxy#3360]
## Namespace Request
Namespace: sennadx

##### Description
Senna Developer Experience (SDX Platform)

##### GitHub Org Link
https://github.com/sennadx

##### Admins
@witalloliveira

**Comment by epacific1** [comment]
Hi, 
Namespace has been created: 
https://galaxy.ansible.com/ui/namespaces/sennadx/
Admin: witalloliveira
