### ISSUE TITLE
namespace: varnish

### ISSUE THREAD

**Issue by varnishsoftware** [ansible/galaxy#3362]
## Namespace Request
Namespace: varnish

##### Description
Varnish Software Ansible Roles

##### GitHub Org Link
https://github.com/varnish

##### Admins
@varnishsoftware

**Comment by chynasan** [comment]
Hello! I have created your namespace as requested: https://galaxy.ansible.com/ui/namespaces/varnish/

**Comment by varnishsoftware** [comment]
Thanks for the prompt action :)
