### ISSUE TITLE
Create a namespace for github organization - namespace `godepict` under account `godepict-dev`

### ISSUE THREAD

**Issue by godepict-dev** [ansible/galaxy#3365]
## Namespace Request
Namespace: godepict

##### Description
I have a galaxy account `godepict_dev` attached to github account that belongs to the `https://github.com/godepict` github org. Can you please create the namespace `godepict` under this account?

##### GitHub Org Link
https://github.com/godepict

##### Admins
https://github.com/godepict-dev   (email: godepict@gmail.com)

**Comment by epacific1** [comment]
Hi, 
Namespace created. 
https://galaxy.ansible.com/ui/namespaces/godepict/
