### ISSUE TITLE
namespace: rancherfederal

### ISSUE THREAD

**Issue by aleiner** [ansible/galaxy#3366]
## Namespace Request
Namespace: rancherfederal

##### Description
Galaxy Collections from Rancher Federal

##### GitHub Org Link
https://github.com/rancherfederal

##### Admins
aleiner
mddamato

**Comment by epacific1** [comment]
Hello, 
Namespace created. 
It can be accessed here: https://galaxy.ansible.com/ui/namespaces/rancherfederal/
