### ISSUE TITLE
namespace: fw-oss

### ISSUE THREAD

**Issue by tldev-de** [ansible/galaxy#3367]
## Namespace Request
Namespace: `fw-oss` (or if not working because of the dash: `fw_oss`)

##### Description
Ansible collections and roles published by FW OSS.

##### GitHub Org Link
https://github.com/fw-oss

##### Admins
@pwannenmacher
@lonjo
@adminioni
@janitor-of-code
@tldev-de

**Comment by epacific1** [comment]
Hi, 
Namespace has been created (not with dash, but with underscore)
https://galaxy.ansible.com/ui/namespaces/fw_oss/
All admins have been added as requested.
