### ISSUE TITLE
requesting namespace named andavarapu

### ISSUE THREAD

**Issue by sampatkalyan** [ansible/galaxy#3369]
## Namespace Request
Namespace:  andavarapu

##### Description
Developing oracle_sql modules

##### GitHub Org Link
(https://github.com/sampatkalyan)
don't have a org it is just a username

##### Admins
sampatkalyan

**Comment by epacific1** [comment]
Hello, 
Namespace has been created. 
It can be accessed here: https://galaxy.ansible.com/ui/namespaces/andavarapu/

**Comment by sampatkalyan** [comment]
@epacific1 thankyou
