### ISSUE TITLE
namespace: derfeldev

### ISSUE THREAD

**Issue by sagat79** [ansible/galaxy#3372]
## Namespace Request
Namespace: derfeldev

##### Description
Ansible collections and roles published by derfeldev

##### GitHub Org Link
[https://github.com/derfeldev](https://github.com/derfeldev)

##### Admins
@sagat79

**Comment by traytorous** [comment]
Name space has been created. Please check now -> https://galaxy.ansible.com/ui/namespaces/derfeldev/
