### ISSUE TITLE
Namespace request: `infisical`

### ISSUE THREAD

**Issue by varonix0** [ansible/galaxy#3373]
## Namespace Request
Namespace: `infisical`

##### Description

The official Ansible namespace for Infisical (infisical.com).

##### GitHub Org Link
https://github.com/infisical

##### Admins
- DanielHougaard
- maidul98

### NOTE:
We already have a Collections namespace. However, we don't have a roles namespace associated to our collections namespace.
**This request is for a role namespace, not a collections namespace.**

**Comment by epacific1** [comment]
Hi, 
A role namespace has now been created as requested. 
Please check: https://galaxy.ansible.com/ui/namespaces/infisical/ under the Role Namespaces tab.
