### ISSUE TITLE
Ansible Galaxy Download page has broken

### ISSUE THREAD

**Issue by bbethell-1** [ansible/galaxy#3374]
##### SUMMARY
https://galaxy.ansible.com/ui/repo/published/redhat_cop/aap_utilities/  and any other collection download is broken 

##### STEPS TO REPRODUCE
Click Download tarball under any collection or via cli 

##### EXPECTED RESULTS
A download of the collection works

##### ACTUAL RESULTS
```

> This XML file does not appear to have any style information associated with it. The document tree is shown below.
> <Error>
> <Code>InvalidAccessKeyId</Code>
> <Message>The AWS Access Key Id you provided does not exist in our records.</Message>
> <AWSAccessKeyId>xxxxxx</AWSAccessKeyId>
> <RequestId>xxxxxx</RequestId>
> <HostId>xxxxxx</HostId>
> </Error>

```

**Comment by kimdre** [comment]
I also experience this issue.

**Comment by JeGoi** [comment]
https://forum.ansible.com/t/jul-8-2024-ansible-galaxy-service-degradation-info-thread/7142
```
Hello everyone,
We are currently experiencing some issues with our S3 file storage that we are actively working to fix.

During the interruption, artifact upload and download will not work, and avatars will not be displayed, as they utilize this file storage tool.

Database access is not impacted, so browsing/searching still works as expected.

We do not currently have an ETA for when things will be fixed, but I will share in this thread as soon as we do.
```

**Comment by Frewx** [comment]
I'm having this problem too. Tried to upgrade AWX operator version to solve this, because I didn't see any announcements or galaxy status pages. I thought about galaxy is having problems but tried to upgrade anyway. What a waste of time. I think galaxy should have status pages. If it does, please help me find it.

**Comment by bbethell-1** [comment]
Seems to be resolved now

**Comment by claude-peon-nyt** [comment]
Looks like old-galaxy.ansible.com is still having the issue. E.g. https://old-galaxy.ansible.com/amazon/aws
