### ISSUE TITLE
Namespace Request for Cloud68.co

### ISSUE THREAD

**Issue by kominoshja** [ansible/galaxy#3376]
## Namespace Request
Namespace: cloud68

##### Description
Cloud68.co makes the use of free and open source software as easy as possible and provides you with reliable managed hosting services. Ansible is used to automate installation of various open source platforms, as well as different utilities for managing the lifecycle of the infrastructure

##### GitHub Org Link
github.com/Cloud68-co

##### Admins
kominoshja

**Comment by epacific1** [comment]
Hi,
Namespace created. 
Can be accessed here: https://galaxy.ansible.com/ui/namespaces/cloud68/
