### ISSUE TITLE
namespace: e4_computer_engineering

### ISSUE THREAD

**Issue by dobbi84** [ansible/galaxy#3377]
## Namespace Request
Namespace: e4_computer_engineering

##### Description
We make high-tech solutions for HPC Clusters, Cloud services, Data Analytics, Artificial Intelligence and Hyper-converged infrastructures

##### GitHub Org Link
[E4_Computer_Engineering](https://github.com/E4-Computer-Engineering)

##### Admins
dobbi84
ilciko

**Comment by epacific1** [comment]
Hi, 
The namespace you have requested does not comply with namespace requirements. 
A valid name can only contain lower case letters, underscores and numbers. 

Please provide a valid name and we will be happy to add it. 
Regards
Einat

**Comment by dobbi84** [comment]
Hi, corrected, thanks

**Comment by epacific1** [comment]
Hi. 
Namespace created. 
You can access it via: https://galaxy.ansible.com/ui/namespaces/e4_computer_engineering/
