### ISSUE TITLE
namespace: seapath

### ISSUE THREAD

**Issue by insatomcat** [ansible/galaxy#3378]
## Namespace Request
Namespace: seapath

##### Description
SEAPATH - (S)oftware (E)nabled (A)utomation (P)latform and (A)rtifacts (TH)erein

##### GitHub Org Link
https://github.com/seapath/

##### Admins
insatomcat

**Comment by epacific1** [comment]
Hi, 
Namespace created: https://galaxy.ansible.com/ui/namespaces/seapath/
