### ISSUE TITLE
namespace: myriadrf

### ISSUE THREAD

**Issue by 9600** [ansible/galaxy#3381]
## Namespace Request
Namespace: myriadrf

##### Description
Myriad RF is a family of open source hardware and software projects for wireless communications.

##### GitHub Org Link
https://github.com/myriadrf/

##### Admins
9600

**Comment by chynasan** [comment]
https://galaxy.ansible.com/ui/namespaces/myriadrf/ has been created, and 9600 has been granted admin rights.

**Comment by 9600** [comment]
Many thanks!
