### ISSUE TITLE
namespace: itential

### ISSUE THREAD

**Issue by kvelarde-itential** [ansible/galaxy#3382]
## Namespace Request
Namespace: itential

##### Description
Itential - Automate & Orchestrate Your Network at Scale

##### GitHub Org Link
https://github.com/itential

##### Admins
steven-schattenberg-itential
kvelarde-itential
Nick-Andreano
Madias2222

**Comment by epacific1** [comment]
Hi, 
Namespace has been created. 
It can be seen here: https://galaxy.ansible.com/ui/namespaces/itential/

However, not all the Admins requested could not be found as users. 
The only user found and added was: 
kvelarde-itential

**Not added:** 
steven-schattenberg-itential
Nick-Andreano
Madias2222

Possible reason is that the above users have not logged in. 
Please review and let me know regarding those users that could not be added. 

Regards, 
Einat

**Comment by epacific1** [comment]
Hi, 
Added: 
steven-schattenberg-itential
Nick-Andreano

The user "Madias2222" has still not logged into galaxy and therefore cannot be added as admin. 
I'll close off this issue for now .
