### ISSUE TITLE
namespace: shaspen

### ISSUE THREAD

**Issue by masoud-maghsoudi** [ansible/galaxy#3383]
## Namespace Request
Namespace: shaspen

##### Description
it used to be my old github and galaxy username

##### GitHub Org Link
https://github.com/shaspen is not used by any one and I want to reserve it for my future use.
##### Admins
@masoud-maghsoudi

**Comment by chynasan** [comment]
Hello, I've created https://galaxy.ansible.com/ui/namespaces/shaspen/ and granted your user @masoud-maghsoudi admin rights for the namespace.
