### ISSUE TITLE
Create 'kubesmith' namespace

### ISSUE THREAD

**Issue by lwencel-priv** [ansible/galaxy#3384]
## Namespace Request
Namespace: kubesmith

##### Description
Automation for deploying and managing Kubernetes clusters.

##### GitHub Org Link
https://github.com/Margays/kubesmith

##### Admins
- lwencel-priv

**Comment by chynasan** [comment]
Hello, I have created https://galaxy.ansible.com/ui/namespaces/kubesmith/ as requested.
