### ISSUE TITLE
Namespace request: CodethinkLabs

### ISSUE THREAD

**Issue by sdclarke** [ansible/galaxy#3385]
## Namespace Request
Namespace: CodethinkLabs

##### Description
Ansible roles and collections published by Codethink

##### GitHub Org Link
https://github.com/CodethinkLabs

##### Admins
sdclarke

**Comment by epacific1** [comment]
Hi, 
Namespaces can only contain lower case letters. 
Please let me know whether codethinklabs is an acceptable namespace, or, whether you would like another namespace. 

Regards, 
Einat

**Comment by sdclarke** [comment]
> Please let me know whether codethinklabs is an acceptable namespace

Yes that's alright, thanks!

**Comment by epacific1** [comment]
Cool!
Namespace created and can be accessed here: https://galaxy.ansible.com/ui/namespaces/codethinklabs/

Einat
