### ISSUE TITLE
namespace: pidginhost

### ISSUE THREAD

**Issue by pidginhostofficial** [ansible/galaxy#3387]
## Namespace Request
Namespace: pidginhost

##### Description
I need to create the company namespace before uploading a cloud module

##### GitHub Org Link
https://github.com/pidginhost

##### Admins
pidginhostofficial

**Comment by traytorous** [comment]
@pidginhostofficial  the link for the namspace is here -> https://galaxy.ansible.com/ui/namespaces/pidginhost/ . Please check to make sure that you can access it
