### ISSUE TITLE
New namespace request

### ISSUE THREAD

**Issue by devolutionsinfra** [ansible/galaxy#3389]
## Namespace Request
Namespace: devolutions

##### Description
Devolutions is a leading provider of remote connections, network accesses, password and credential management tools.

##### GitHub Org Link
https://github.com/Devolutions

##### Admins
devolutionsinfra
dannybedard

**Comment by chynasan** [comment]
Hello, I have created the namespace as requested: https://galaxy.ansible.com/ui/namespaces/devolutions/?

**Comment by chynasan** [comment]
The user dannybedard does not seem to have ever logged onto galaxy with that username. Once they have logged in, you should be able to add them as a namespace admin from the devolutionsinfra account.
