### ISSUE TITLE
namespace: stormshield

### ISSUE THREAD

**Issue by remip2** [ansible/galaxy#3391]
## Namespace Request
Namespace: stormshield

##### Description
Stormshield - Trusted cybersecurity solutions

##### GitHub Org Link
https://github.com/stormshield/

##### Admins
remip2
fabientstormshield

Thanks!

**Comment by epacific1** [comment]
Hi there, 
Namespace created successfully. It can be accessed here: https://galaxy.ansible.com/ui/namespaces/stormshield/
