### ISSUE TITLE
namespace: rnx

### ISSUE THREAD

**Issue by rnxch** [ansible/galaxy#3392]
## Namespace Request
Namespace: rnx

##### Description
Riedo Networks Ltd.

##### Admins
rnxch

Thank you very much :slightly_smiling_face:

**Comment by rnxch** [comment]
If it is possible to remove the default namespace `rnxch` that would be nice :slightly_smiling_face:. Thank you

**Comment by traytorous** [comment]
@rnxch The namespace rnxch has been deleted and the namespace has been created https://galaxy.ansible.com/ui/namespaces/rnx/. Please let me know if there is anything else I can do for you.
