### ISSUE TITLE
Namespace: fujitsu

### ISSUE THREAD

**Issue by jiajun-guo-tech** [ansible/galaxy#3396]
Namespace Request
Namespace: fujitsu

 GitHub Org Link
https://github.com/fujitsu

 Admins
jiajun-guo-tech

**Comment by epacific1** [comment]
Hi, 
the fujitsu namespace already exists in galaxy.
https://galaxy.ansible.com/ui/namespaces/fujitsu

If you need access to that namespace, please contact the owner of that namespace. 
Else, you may request a different namespace that does not currently exist in Ansible Galaxy.
