### ISSUE TITLE
namespace: rhvp

### ISSUE THREAD

**Issue by mhjacks** [ansible/galaxy#3398]
## Namespace Request
Namespace:  rhvp

##### Description
Red Hat Validated Patterns team namespace for collections used within and for the validated patterns framework

##### GitHub Org Link
https://github.com/validatedpatterns/

##### Admins
mhjacks

**Comment by chynasan** [comment]
Hi Martin! I've created the namespace as requested. https://galaxy.ansible.com/ui/namespaces/rhvp/
