### ISSUE TITLE
namespace: 0srv

### ISSUE THREAD

**Issue by 0srv** [ansible/galaxy#3399]
The namespace for my username was not created automatically. Trying here.

## Namespace Request
Namespace: 0srv

##### Description
System administration

##### GitHub Org Link
https://github.com/0srv

##### Admins
0srv

**Comment by epacific1** [comment]
Hi, 

Namespace 0srv created. It can be found [here.](https://galaxy.ansible.com/ui/namespaces/0srv) 

Einat
