### ISSUE TITLE
namespace: celestica

### ISSUE THREAD

**Issue by dharmaraj-gurusamy** [ansible/galaxy#3401]
## Namespace Request
Namespace: celestica

##### Description
Ansible collection and roles published by Celestica Inc.

##### Admins
dharmaraj-gurusamy

**Comment by epacific1** [comment]
Hi. 
Namespace created and can be found [here](https://galaxy.ansible.com/ui/namespaces/celestica/).

**Comment by dharmaraj-gurusamy** [comment]
Thank you very much @epacific1
