### ISSUE TITLE
namespace: selfhosted

### ISSUE THREAD

**Issue by SpeakinTelnet** [ansible/galaxy#3403]
## Namespace Request
Namespace: selfhosted

##### Description
Automated deployment of various services with the scope selfhosting.

##### GitHub Org Link
https://github.com/ansible-selfhosted

##### Admins
SpeakinTelnet

**Comment by chynasan** [comment]
Hi there! I have created the namespace as requested: https://galaxy.ansible.com/ui/namespaces/selfhosted/
