### ISSUE TITLE
namespace: bitbone

### ISSUE THREAD

**Issue by pbecker-bitbone** [ansible/galaxy#3404]
## Namespace Request
Namespace: bitbone

##### Description
Open source projects and samples from bitbone AG.

##### GitHub Org Link
https://github.com/bitbone

##### Admins
sscheuring
pbecker-bitbone

**Comment by traytorous** [comment]
@pbecker-bitbone the namespace has been created. Please check here -> https://galaxy.ansible.com/ui/namespaces/bitbone
