### ISSUE TITLE
Bad namespace for my account?

### ISSUE THREAD

**Issue by HanXHX** [ansible/galaxy#3405]
## Namespace fix
Namespace: hanxhx

##### Description

Hi, I created a post about my problem on the forum: https://forum.ansible.com/t/cannot-import-role-to-galaxy/8127

My namespace (hanxhx) is dropped?

##### GitHub Org Link

Note: not an org, just a personnal account.

https://github.com/HanXHX

##### Admins
Only me

**Comment by traytorous** [comment]
@HanXHX Hello! If you could can you provide me more details on what you would like for us to do?

**Comment by traytorous** [comment]
@HanXHX After looking at your namespace I saw that the reason why you were having issues may have been due to a permission issue. We have added you as a namespace owner to the namespace you were having issues with. Please check now and see if you still get an error.

**Comment by HanXHX** [comment]
Hi @traytorous,

It works now. Thanks! :partying_face:
