### ISSUE TITLE
namespace: agnosticd

### ISSUE THREAD

**Issue by newgoliath** [ansible/galaxy#3406]
## Namespace Request
Namespace:  agnosticd

##### Description

Collections related to the Red Hat Demo Platform's Open Source "AgnosticD" Infrastructure Deployment Tool.  Powers much of demo.redhat.com

##### GitHub Org Link

https://github.com/agnosticd

##### Admins

newgoliath
jkupferer

**Comment by chynasan** [comment]
Hi! 
I am happy to report I have created the namespace as requested: https://galaxy.ansible.com/ui/namespaces/agnosticd/

Feel free to ping me if you have any questions!
