### ISSUE TITLE
namespace: TheSudoYT

### ISSUE THREAD

**Issue by Josh-Tracy** [ansible/galaxy#3408]
## Namespace Request
Namespace:  TheSudoYT

##### Description
TheSudoYT Ansible Galaxy Namespace

##### GitHub Org Link
https://github.com/TheSudoYT

##### Admins
Josh-Tracy

**Comment by traytorous** [comment]
Good evening,

The namespace name that you requested cannot be used. Is it okay for all the letters to be lowercase? That is the only way it will work

**Comment by traytorous** [comment]
@Josh-Tracy

**Comment by Josh-Tracy** [comment]
> @Josh-Tracy

That will work fine yes.

**Comment by traytorous** [comment]
Hello @Josh-Tracy the namespace has been created. Please let me know if everything works correctly. https://galaxy.ansible.com/ui/namespaces/thesudoyt/

**Comment by Josh-Tracy** [comment]
> Hello @Josh-Tracy the namespace has been created. Please let me know if everything works correctly. https://galaxy.ansible.com/ui/namespaces/thesudoyt/

LGTM!
