### ISSUE TITLE
Add namespace for deslicer

### ISSUE THREAD

**Issue by RogerLindquist** [ansible/galaxy#3412]
## Namespace Request
Namespace: deslicer

##### Description
A variety of Ansible content to help automate the management of Deslicer services.

##### GitHub Org Link
https://github.com/orgs/deslicer

##### Admins
RogerLindquist
SaikrishnaGundeti
YoungDan

**Comment by traytorous** [comment]
@RogerLindquist the namespace has been created: https://galaxy.ansible.com/ui/namespaces/deslicer/
Please check and verify it works

**Comment by RogerLindquist** [comment]
Thank you @traytorous, it works. Thanks for fast resolution!
