### ISSUE TITLE
namespace: lingfra

### ISSUE THREAD

**Issue by lingling9000** [ansible/galaxy#3413]
## Namespace Request
Namespace: lingfra

##### Description
Automation content for managing systems and hosting services. 

##### GitHub Org Link
<https://github.com/lingfra>

##### Admins
[lingling9000](https://galaxy.ansible.com/ui/namespaces/lingling9000/)

**Comment by epacific1** [comment]
Hi, 
Namespace created. You may access it here: https://galaxy.ansible.com/ui/namespaces/lingfra

**Comment by lingling9000** [comment]
Yes, I can access it in the my-namespaces tab. Thank you @epacific1!
