### ISSUE TITLE
namespace: cloudkrafter

### ISSUE THREAD

**Issue by brianveltman** [ansible/galaxy#3414]
## Namespace Request
Namespace: cloudkrafter

##### Description
Developers of nexus repository ansible roles

##### GitHub Org Link
https://github.com/CloudKrafter

##### Admins
- brianveltman

**Comment by epacific1** [comment]
Hi, 
Namespace created. It is available here: https://galaxy.ansible.com/ui/namespaces/cloudkrafter/

**Comment by brianveltman** [comment]
thnx! @epacific1 

Can I import roles/collections that are owned by our organization in Github? or does the repo has to be owned by a Github user?

**Comment by epacific1** [comment]
You can import roles/collections that are owned by your organization in github.

**Comment by brianveltman** [comment]
@epacific1 I just tried to import a role from a repo our organization owns, but Galaxy returns a ERROR! None (HTTP Code: 500, Message: Internal Server Error).

command I used: `ansible-galaxy role import --token *** --branch main CloudKrafter nexus3_config_api`

**Comment by brianveltman** [comment]
Ah sorry, the username needs to be lowercase

**Comment by traytorous** [comment]
has your issue been resolved @brianveltman ?

**Comment by brianveltman** [comment]
yes it has! thnx!
