### ISSUE TITLE
namespace: scaleway

### ISSUE THREAD

**Issue by rockyluke** [ansible/galaxy#3415]
## Namespace Request
Namespace: scaleway

##### Description
Europe's empowering cloud provider

##### GitHub Org Link
https://github.com/scaleway

##### Admins
rockyluke

**Comment by traytorous** [comment]
Hello @rockyluke there is already a scaleway namespace. Are you asking to be added to the scaleway namespace already created or create a new namespace?

**Comment by rockyluke** [comment]
apology for that, I am new in the company and I missed that. Could you then add me to the org ? (I am part of the GitHub organisation).

**Comment by traytorous** [comment]
You have been added to the namespace. Please check here -> https://galaxy.ansible.com/ui/namespaces/scaleway/?tab=collections
