### ISSUE TITLE
namespace: kangaroot

### ISSUE THREAD

**Issue by smeeus** [ansible/galaxy#3416]
## Namespace Request
Namespace: kangaroot

##### Description
For publishing collections maintained by Kangaroot

##### GitHub Org Link
https://github.com/kangaroot/

##### Admins
- peterdens
- smeeus

Thank you

**Comment by traytorous** [comment]
@smeeus Your namespace has been created. Please check here -> https://galaxy.ansible.com/ui/namespaces/kangaroot/
