### ISSUE TITLE
namespace: LaVioletteLabInfrastructure

### ISSUE THREAD

**Issue by barrettMCW** [ansible/galaxy#3418]
## Namespace Request
Namespace: lavlab

##### Description
ansible roles and collections used in the LaViolette Lab

##### GitHub Org Link
https://github.com/LavLabInfrastructure

##### Admins
barrettMCW
peterlaviolette

we're a research lab at The Medical College of Wisconsin looking to upload our [ansible stack](https://github.com/LavLabInfrastructure/lavlab-olympus-ansible) to galaxy, made myself, the software guy, and Pete, the PI, the admins, thanks!

**Comment by traytorous** [comment]
Hey @barrettMCW thank you for using galaxy and I hope that everthing works out for you and Pete! Here is the namespace -> https://galaxy.ansible.com/ui/namespaces/lavlab/

Check to make sure you can access it and let me know if I can do anything else for you :)
