### ISSUE TITLE
Please create rhtelco namespace

### ISSUE THREAD

**Issue by sshnaidm** [ansible/galaxy#3422]
## Namespace Request
Namespace: rhtelco

##### Description

Collections for Telco CI automation

##### GitHub Org Link

https://github.com/openshift-kni/telco-ci/

##### Admins

@sshnaidm

**Comment by traytorous** [comment]
@sshnaidm Your namespace has been created. Please check to make sure everything works! -> https://galaxy.ansible.com/ui/namespaces/rhtelco/
