### ISSUE TITLE
Namespace request

### ISSUE THREAD

**Issue by leandroramos** [ansible/galaxy#3423]
## Namespace Request
Namespace: ecausp

##### Description
Namespace for roles and collection from ECA USP (Escola de Comunicações e Artes/Universidade de São Paulo)

##### GitHub Org Link
[Link to my GitHub org](https://github.com/ecausp/)

##### Admins
leandroembu

**Comment by traytorous** [comment]
Hello @leandroembu! Your namespace has been created, please click here and check to make sure everything works correctly -> https://galaxy.ansible.com/ui/namespaces/ecausp/

**Comment by leandroramos** [comment]
Everything is working fine. Thank you.
