### ISSUE TITLE
namespace: torproject

### ISSUE THREAD

**Issue by rhatto** [ansible/galaxy#3424]
## Namespace Request
Namespace:  torproject

##### Description

The Tor Project - https://www.torproject.org

##### GitHub Org Link

https://github.com/torproject/

##### Admins

* anarcat
* lelutin
* ahf
* rhatto

**Comment by epacific1** [comment]
Hi, 

Namespace created and admins added. 
Namespace can be viewed here: https://galaxy.ansible.com/ui/namespaces/torproject/

Einat

**Comment by epacific1** [comment]
Hi, 

New namespace created. It can be seen here: https://galaxy.ansible.com/ui/namespaces/torproject/
