### ISSUE TITLE
namespace: portworx

### ISSUE THREAD

**Issue by parveenp-px** [ansible/galaxy#3425]
## Namespace Request
Namespace:  portworx

##### GitHub Org Link

https://github.com/portworx
https://github.com/parveenp-px

##### Admins

parveenp-px

**Comment by epacific1** [comment]
Hi, 

The namespace portworx already exists in galaxy.ansible.com.
If you'd like a different namespace, please let us know and we'd be happy to help. 

Einat

**Comment by parveenp-px** [comment]
how Can I get the access of that namespace, As the previous person no longer with Organization and he was the only person as admin there

**Comment by epacific1** [comment]
Hi, 

Do you know the username of the previous admin? 
If I get some details about the previous admin, I can remove them as admin for this namespace and replace them with parveenp-px.

**Comment by parveenp-px** [comment]
Here is the old admin username: jsilberm

**Comment by epacific1** [comment]
I have removed the old admin and added the new admin: parveenp-px
The namespace can be accessed via: 
https://galaxy.ansible.com/ui/namespaces/portworx/
