### ISSUE TITLE
namespace: aovpn

### ISSUE THREAD

**Issue by Nmishin** [ansible/galaxy#3426]
## Namespace Request
Namespace: aovpn

##### Description
Ansible role to install and configure OpenVPN server

##### GitHub Org Link
https://github.com/aovpn

##### Admins
nmishin
kvendingoldo
gesundes

**Comment by epacific1** [comment]
Hi, 

The three admin names do not exist in galaxy, they need to login to galaxy so that i can add them as admins. 
Please make the necessary changes and update this issue. 

Einat

**Comment by Nmishin** [comment]
Hello, sorry about that, they've logged in the galaxy now.

**Comment by epacific1** [comment]
Hi, 

I've created the namespace and added: 
kvendingoldo
gesundes
[NOTE: nmishin has not logged in to galaxy and the user could not be found.]
The namespace can be accessed here: https://galaxy.ansible.com/ui/namespaces/aovpn/

If you'd still like to add nmishin please ensure the user login to galaxy.

**Comment by Nmishin** [comment]
hmm, could you please check username Nmishin?

**Comment by epacific1** [comment]
Yup, that worked. 
Nmishin added. 
The namespace can be accessed here: https://galaxy.ansible.com/ui/namespaces/aovpn/
Closing the issue.
