### ISSUE TITLE
namespace: DINFRA

### ISSUE THREAD

**Issue by rvalle** [ansible/galaxy#3428]
## Namespace Request
Namespace: 

DINFRA

##### Description

DINFRA, decentralized infrastructure, is substrate orchestrated infrastructure, a decentralized alternative to public clouds. A project supported by the Web3 Foundation grants program.

##### GitHub Org Link

https://gitlab.com/dinfra/dinfra

##### Admins

rvalle

**Comment by rvalle** [comment]
Our project is hosted in gitlab, hope is not a problem.

**Comment by epacific1** [comment]
Hi, 
Namespaces cannot be with capital letters. 
Namespaces may only contain alphanumeric lowercase characters and underscores. Namespaces cannot start with underscores or numbers and cannot contain consecutive underscores.

Please let me know how you'd like to proceed.

**Comment by rvalle** [comment]
"dinfra" is perfectly fine @epacific1

**Comment by epacific1** [comment]
Hi, 

Namespace created. It can be viewed here: https://galaxy.ansible.com/ui/namespaces/dinfra/

Einat
