### ISSUE TITLE
NVIDIA Doca namespace request

### ISSUE THREAD

**Issue by eneiderman** [ansible/galaxy#3430]
## Namespace Request
Namespace: NVIDIA-DOCA

##### Description
NVIDIA DOCA (Data Center on a Chip)

##### GitHub Org Link
https://github.com/NVIDIA-DOCA

##### Admins
eneiderman

**Comment by epacific1** [comment]
Hi,
Namespaces cannot be with capital letters.
Namespaces may only contain alphanumeric lowercase characters and underscores. Namespaces cannot start with underscores or numbers and cannot contain consecutive underscores.

Please let me know how you'd like to proceed.

Einat

**Comment by eneiderman** [comment]
Hi Einat,

then please name it 'nvidia_doca'
Thanks,
Erez.

**Comment by epacific1** [comment]
Hi Erez, 

Namespace created. It can be accessed here: https://galaxy.ansible.com/ui/namespaces/nvidia_doca/

Einat
