### ISSUE TITLE
Namespace Request for UltraDNS

### ISSUE THREAD

**Issue by stevedejong** [ansible/galaxy#3431]
## Namespace Request
Namespace: ultradns

##### Description
Collection for managing UltraDNS

##### GitHub Org Link
https://github.com/ultradns

##### Admins
stevedejong

**Comment by epacific1** [comment]
Hi,
Namespaces cannot contain  capital letters.
Namespaces may only contain alphanumeric lowercase characters and underscores. Namespaces cannot start with underscores or numbers and cannot contain consecutive underscores.

Please let me know how you'd like to proceed.

Einat

**Comment by stevedejong** [comment]
Hello,

Namespace: ultradns

I think that name meets the criteria you indicated.

**Comment by epacific1** [comment]
Hi, 
Indeed, my apologies. I was looking at the title of the issue rather than the request text itself. 
The namespace has been created. It can be accessed here: https://galaxy.ansible.com/ui/namespaces/ultradns/
