### ISSUE TITLE
Namespace request for Unredacted

### ISSUE THREAD

**Issue by lunarthegrey** [ansible/galaxy#3432]
## Namespace Request
Namespace: unredacted

##### Description
Unredacted is a 501(c)(3) non-profit organization that provides free and open services that help people evade censorship and protect their right to privacy

##### GitHub Org Link
https://github.com/unredacted

##### Admins
lunarthegrey

**Comment by epacific1** [comment]
Hi, 

Namespace created. it can be found here: https://galaxy.ansible.com/ui/namespaces/unredacted/

Einat
