### ISSUE TITLE
namespace: bluecadet

### ISSUE THREAD

**Issue by claytercek** [ansible/galaxy#3433]
## Namespace Request
Namespace: bluecadet

##### Description

Combining design, technology, content and craft to tell meaningful stories across digital and physical space.

##### GitHub Org Link

https://github.com/bluecadet

##### Admins

- BluecadetInstallations
- claytercek

**Comment by traytorous** [comment]
Here is your namespace. Please check to make sure it is what you need -> https://galaxy.ansible.com/ui/namespaces/bluecadet/
