### ISSUE TITLE
requesting fossgalaxy as a namespace

### ISSUE THREAD

**Issue by webpigeon** [ansible/galaxy#3440]
## Namespace Request
Namespace: fossgalaxy

##### Description
A Free Software group based in the United Kingdom.

##### GitHub Org Link
https://github.com/fossgalaxy/

##### Admins
- [webpigeon](https://galaxy.ansible.com/ui/namespaces/webpigeon/)

**Comment by Andersson007** [comment]
Hello,
The namespace has been created and can be accessed on https://galaxy.ansible.com/ui/namespaces/fossgalaxy/
Thanks and congrats!
