### ISSUE TITLE
Request admin rights to dynatrace namespace

### ISSUE THREAD

**Issue by jakubrak** [ansible/galaxy#3441]
## Namespace Request
Namespace:  dynatrace

##### Description
Request admin rights to dynatrace namespace

##### GitHub Org Link
https://github.com/Dynatrace

##### Admins
jakubrak
WStechura
filip-szweda

**Comment by samccann** [comment]
Hey @jakubrak ! The other two were already admins. I added you. In the future, you or they should be able to add additional people through the admin tab at https://galaxy.ansible.com/ui/namespaces/dynatrace/?tab=collections

Let me know if there's any issues before I close this issue.

**Comment by jakubrak** [comment]
Thanks, looks good
