### ISSUE TITLE
namespace: corpusops

### ISSUE THREAD

**Issue by kiorky** [ansible/galaxy#3444]
## Namespace Request
Namespace: corpusops
namespace link: https://galaxy.ansible.com/ui/standalone/namespaces/1408/

##### Description
I published a long time ago this namespace, but seems i lost access on the new galaxy website.

##### GitHub Org Link
https://github.com/corpusops

##### Admins
kiorky

Basically, maybe the solution is to delete the namespace and related resources.
Because of EU CRA, i'm on my way to tear down the corpusops project and at least do not publish things.

**Comment by Andersson007** [comment]
@kiorky hello, thanks for reaching out to us, you have the access now

**Comment by kiorky** [comment]
Thanks @Andersson007 ! 

But seems something is still missing, see #3445
