### ISSUE TITLE
Reopening of #3444

### ISSUE THREAD

**Issue by kiorky** [ansible/galaxy#3445]
Hello,
This is a reopening of #3444, where i asked either to get access for deleting all what is tied to `corpusops` namespace, or for you to do directly, whatever is easier for you.

Behind the scene, i want to remove:
- this namespace: https://galaxy.ansible.com/ui/namespaces/corpusops/
- this standalone namespace: https://galaxy.ansible.com/ui/standalone/namespaces/1408/
- And all the resources behind (like https://galaxy.ansible.com/ui/standalone/roles/corpusops/actionhelper/ but not limited to).

Maybe i do not do the right things, but here what i tried without success:

1. going on the interface: (https://galaxy.ansible.com/ui/namespaces/corpusops/ & https://galaxy.ansible.com/ui/standalone/namespaces/1408/)<BR/>

Here, on both, i do not see any admin interface appearing letting me delete those ressources.

2. API 

I also tried to play with the API, and trying to delete for example the `corpusops.actionhelper` role with the TOKEN obtained in the UI, here is what happen:
```
# i can confirm to get corpusops.actionhelper here:
curl  -H 'accept: application/json' -H "Authorization: Token $token" -sSLvvvX 'GET'    'http://galaxy.ansible.com/api/v1/roles/6366'|jq -C
# so i try to delete it, but without success
curl  -H 'accept: application/json' -H "Authorization: Token $token" -sSLvvvX 'DELETE' 'http://galaxy.ansible.com/api/v1/roles/6366'|jq -C
{
  "detail": "Authentication credentials were not provided."
}
# ( i tried also with -u "kiorky:$token" )
```

edit: forgot to mention that i was following this documentation : https://ansible.readthedocs.io/projects/galaxy-ng/en/latest/community/userguide/#deleting-roles

**Comment by Andersson007** [comment]
@kiorky i pinged people internally, thanks

**Comment by kiorky** [comment]
Hello, any news ?

**Comment by Andersson007** [comment]
> Hello, any news ?

@kiorky hello, responses can arrive slower than usual in this part of the year, I'm sure someone from the galaxy team will take a look ASAP

**Comment by samccann** [comment]
Looking at this now @kiorky

**Comment by samccann** [comment]
Verified that the code base - https://github.com/corpusops is marked as archived/abandoned so will work on the deletion now.

**Comment by kiorky** [comment]
When everything will be wiped, can i also be sure no one can put something in the namespace; impersonating it with rogue content ? Like letting here just an empty namespace ?

**Comment by samccann** [comment]
Hmm so it sounds like you want to keep ownership of the namespace, but delete the current content because it's outdated/unmaintained.  So it has a couple of roles that you need to delete - https://ansible.readthedocs.io/projects/galaxy-ng/en/latest/community/userguide/#ansible-galaxy-cli

Once you delete the current roles, the namespace remains yours, but no one else can upload additional content.

**Comment by kiorky** [comment]
Ok, pb is that it did'nt worked (this is object of this ticket).

So did you changed something since my ticket filling for me to delete the inner roles and let the namespace empty ?

**Comment by kiorky** [comment]
seems deletion still not work.
```
curl  -H 'accept: application/json' -H "Authorization: Token $token" -sSLvvvX 'DELETE' 'http://galaxy.ansible.com/api/v1/roles/6366'|jq -C
{
  "detail": "Authentication credentials were not provided."
}
```

**Comment by samccann** [comment]
ah okay. Sorry taking me a bit to catch up with the original ask here. So did you try the CLI version of the role delete?

And no - you were given permissions to the namespace in the other resolved issue. I didn't change anything since then.

**Comment by samccann** [comment]
Okay, I'm unfamiliar with this and most people 'in the know' are out for the remainder of the year. I see there is an older user 'corpusops' associated with this namespace. I added the same rights that account has to your username. Can you try again pls?

**Comment by kiorky** [comment]
Sorry, was deleting all the roles :)

I retried, & the cli worked, so was just getting the full list to batch it.

A lot have been deleted, checking now that this task is finished.

**Comment by samccann** [comment]
Okay I'm going to delete that other user 'corpusops' from this namespace so that only you have access to uploading new content .

**Comment by kiorky** [comment]
So, namespace corpusops cleaned using cli, we are good !
Thank you !

https://galaxy.ansible.com/ui/standalone/namespaces/1408/

**Comment by samccann** [comment]
your welcome!
