### ISSUE TITLE
namespace: ceru1ean

### ISSUE THREAD

**Issue by 0x07cf-dev** [ansible/galaxy#3447]
## Namespace Request
Namespace: ceru1ean

##### GitHub Org Link

https://github.com/0x07cf-dev

##### Admins

0x07cf-dev

I have previously requested the `0x07cf` namespace. Though it has been succesfully created, I cannot use it for importing roles from my repos. Since namespaces cannot start with numbers, all I can do is request another one. You may remove the previous namespace, as it cannot be used for imports on Galaxy (but I can use it locally when installing from requirements.yml by using a git repo as the source).

Thank you for your time.

**Comment by Andersson007** [comment]
@0x07cf-dev hello, created https://galaxy.ansible.com/ui/namespaces/ceru1ean/ ,could you please check? Thank you
