### ISSUE TITLE
Request for new namespace: CloudTooling

### ISSUE THREAD

**Issue by hypery2k** [ansible/galaxy#3449]
## Namespace Request
Namespace: CloudTooling

##### Description
Tools for operating easy on different cloud environments

##### GitHub Org Link
https://github.com/CloudTooling

##### Admins
[hypery2k](https://galaxy.ansible.com/ui/standalone/namespaces/2921/)

**Comment by Andersson007** [comment]
@hypery2k hello, thanks for reading out to us, https://galaxy.ansible.com/ui/namespaces/cloudtooling/ has been created, you're made its owner
