### ISSUE TITLE
500 Server Error on /api/v1/repos/refresh/

### ISSUE THREAD

**Issue by onegreyonewhite** [ansible/galaxy#348]
Couldn't update projects list and import role to galaxy.
On import:
```
Starting import 205127: role_name=wordpress-ansible-role repo=onegreyonewhite/wordpress-ansible-role
Failed to connect to the GitHub API. This is most likely a temporary error, please retry your import in a few minutes.
```

**Comment by robertdebock** [comment]
Same [here](https://galaxy.ansible.com/imports#/?github_user=robertdebock&github_repo=ansible-role-bootstrap).

Not sure if that's only accessible by me, otherwise:
```
Starting import 205395: role_name=bootstrap repo=robertdebock/ansible-role-bootstrap
Failed to connect to the GitHub API. This is most likely a temporary error, please retry your import in a few minutes.
```

**Comment by sunggun-yu** [comment]
+1

**Comment by onegreyonewhite** [comment]
Now it`s working. Issue could be close, but it would be nice to get comments from ansible galaxy contributors.

**Comment by chouseknecht** [comment]
@onegreyonewhite 

Thanks for reporting the issue. There seems to have been some connectivity issues with the GitHub API yesterday.  Imports are working OK today. We'll keep a closer eye on it, as the day progresses.
