### ISSUE TITLE
macOS 10.13 is an "invalid platform" apparently

### ISSUE THREAD

**Issue by danbohea** [ansible/galaxy#352]
My role just failed when importing to Galaxy because I'd used `10.13` as a version of `MacOSX`:

```
Invalid platform: MacOSX-10.13 (skipping)
```

**Comment by chouseknecht** [comment]
You'll find the full list of platforms here: https://galaxy.ansible.com/api/v1/platforms/

It's actually `mac0S`, and the release is `Sierra`

**Comment by danbohea** [comment]
Thanks!

**Comment by danbohea** [comment]
Hang on, that makes no sense. 10.13 should be "High Sierra". 10.12 is "Sierra". Is this an error?
