### ISSUE TITLE
Ansible Galaxy installs some roles in wrong directories

### ISSUE THREAD

**Issue by madhead** [ansible/galaxy#353]
I'm trying to install two roles - `geerlingguy.pip` and `geerlingguy.nginx` with ansible galaxy. The first one (`geerlingguy.pip`) got installed in `/etc/ansible/roles`, while the latter one is installed in `/root/.ansible/roles`, which is not what I expect:

    $ sudo ansible-galaxy install geerlingguy.pip --force -vvvv
    ansible-galaxy 2.4.3.0
      config file = /home/madhead/Projects/seaowl/ansible/ansible.cfg
      configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
      ansible python module location = /usr/lib/python2.7/site-packages/ansible
      executable location = /usr/bin/ansible-galaxy
      python version = 2.7.14 (default, Jan  5 2018, 10:41:29) [GCC 7.2.1 20171224]
    Using /home/madhead/Projects/seaowl/ansible/ansible.cfg as config file
    Opened /root/.ansible_galaxy
    Processing role geerlingguy.pip 
    - changing role geerlingguy.pip from 1.2.0 to unspecified
    Opened /root/.ansible_galaxy
    Initial connection to galaxy_server: https://galaxy.ansible.com
    Base API: https://galaxy.ansible.com/api/v1
    - downloading role 'pip', owned by geerlingguy
    https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=pip
    https://galaxy.ansible.com/api/v1/roles/18064/versions/?page_size=50
    - downloading role from https://github.com/geerlingguy/ansible-role-pip/archive/1.2.0.tar.gz
    - extracting geerlingguy.pip to /etc/ansible/roles/geerlingguy.pip
    - geerlingguy.pip (1.2.0) was installed successfully

    $ sudo ansible-galaxy install geerlingguy.nginx --force -vvvv
    ansible-galaxy 2.4.3.0
      config file = /home/madhead/Projects/seaowl/ansible/ansible.cfg
      configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
      ansible python module location = /usr/lib/python2.7/site-packages/ansible
      executable location = /usr/bin/ansible-galaxy
      python version = 2.7.14 (default, Jan  5 2018, 10:41:29) [GCC 7.2.1 20171224]
    Using /home/madhead/Projects/seaowl/ansible/ansible.cfg as config file
    Opened /root/.ansible_galaxy
    Processing role geerlingguy.nginx 
    - changing role geerlingguy.nginx from 2.5.0 to unspecified
    Opened /root/.ansible_galaxy
    Initial connection to galaxy_server: https://galaxy.ansible.com
    Base API: https://galaxy.ansible.com/api/v1
    - downloading role 'nginx', owned by geerlingguy
    https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=nginx
    https://galaxy.ansible.com/api/v1/roles/471/versions/?page_size=50
    - downloading role from https://github.com/geerlingguy/ansible-role-nginx/archive/2.5.0.tar.gz
    - extracting geerlingguy.nginx to /root/.ansible/roles/geerlingguy.nginx
    - geerlingguy.nginx (2.5.0) was installed successfully

I am running Manjaro Linux:

    $ cat /etc/lsb-release
    DISTRIB_ID=ManjaroLinux
    DISTRIB_RELEASE=17.1.6
    DISTRIB_CODENAME=Hakoila
    DISTRIB_DESCRIPTION="Manjaro Linux"

Ansible versions:

    $ ansible --version
    ansible 2.4.3.0
      config file = /home/madhead/Projects/seaowl/ansible/ansible.cfg
      configured module search path = [u'/home/madhead/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
      ansible python module location = /usr/lib/python2.7/site-packages/ansible
      executable location = /usr/bin/ansible
      python version = 2.7.14 (default, Jan  5 2018, 10:41:29) [GCC 7.2.1 20171224]
    $ ansible-galaxy --version
    ansible-galaxy 2.4.3.0
      config file = /home/madhead/Projects/seaowl/ansible/ansible.cfg
      configured module search path = [u'/home/madhead/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
      ansible python module location = /usr/lib/python2.7/site-packages/ansible
      executable location = /usr/bin/ansible-galaxy
      python version = 2.7.14 (default, Jan  5 2018, 10:41:29) [GCC 7.2.1 20171224]

**Comment by chouseknecht** [comment]
@madhead 

You can control where roles are installed by setting `roles_path` in your `ansible.cfg` file, or `ANSIBLE_ROLES_PATH` in the environment. See http://docs.ansible.com/ansible/latest/intro_configuration.html#roles-path

On the CLI, you can also pass the `--roles-path` option to `install`.

**Comment by madhead** [comment]
Yeah, seen that options and they indeed work. The problem was the default behavior. However, after updating to 2.5.0 it is not reproducible anymore.

Sorry for disturbing.
