### ISSUE TITLE
sort release versions by number 

### ISSUE THREAD

**Issue by nusenu** [ansible/galaxy#360]
I released ansible-relayor on 2018-03-06 which has a last commit authored in 2017.

The sorting on the galaxy page is apparently by the date the commit has been authored, which results in strange sorting:
https://galaxy.ansible.com/nusenu/relayor/

ansible-galaxy install ...
installs 0.3.2 and works fine.

Maybe change the sorting on the galaxy page?

**Comment by cutwater** [comment]
@nusenu Thanks for reporting this issue. It seems that sorting is done by `Release date` field, so it's likely a bug.

**Comment by nusenu** [comment]
The "Release Date" column on galaxy appears to use the date of the last commit instead of the date when the release has actually been tagged. So by improving the way the "Release Date" determined, this bug would be implicitly be solved.

**Comment by chouseknecht** [comment]
We're running into the same issue on the client, as it relates to comparing Ansible content versions, and making install/uninstall/upgrade decisions.

@alikins is going to come up with a solution that works with the semantic version spec. Please collaborate with him on this, and make sure that we implement the same on the server side.

To support the UI, let's please return API results for version in descending order, such that the most recent version is at the top of the list. The UI should not contain any version logic, nor version sorting algorithms.
