### ISSUE TITLE
Decouple import process from worker

### ISSUE THREAD

**Issue by cutwater** [ansible/galaxy#369]
Separate import process from the database. Import process should not communicate with database. 

* All parameters should be passed to the process (task) when it starts.
* The result of import process should be represented as a plain JSON \ YAML serializable object.

As a result when we migrate to implementing Ansible Lint, Ansible Test, and other testing, this will insure separation between import nodes and the database, and thus provide better isolation and security.

**Comment by chouseknecht** [comment]
PR #401
