### ISSUE TITLE
Django admin: Missing .svg files

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#378]
- [x] .svg files not loading on the Admin site. 
- [x] Seeing 304 redirects on static content when loading Admin site. 

Could be a browser issue. Seeing the problem in Safari and Firefox, both after clearing cache. Haven't tried in Chrome.

**Comment by cutwater** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Django admin: Missing .svg files](https://trello.com/c/NaEBj7WM/40-django-admin-missing-svg-files)
