### ISSUE TITLE
Support role for Devuan OS

### ISSUE THREAD

**Issue by HanXHX** [ansible/galaxy#379]
Hi,

I have an error while importing a role:

```
Invalid platform: Devuan-jessie (skipping)
```
It seems [Devuan](https://devuan.org) OS is not supported by galaxy. Can you manage this OS?

Release names (right now) are: jessie, ascii, beowulf and ceres. [Source](https://devuan.org/index.html#download).

Cheers!

**Comment by chouseknecht** [comment]
Added `Devaun`
