### ISSUE TITLE
Galaxy Role title (update) not in sync with GitHub

### ISSUE THREAD

**Issue by AdnanHodzic** [ansible/galaxy#380]
Recently I updated one of my roles to provide Let's Encrypt encryption out of box. Although I've [updated title of my role on GitHub](https://github.com/AdnanHodzic/ansible-role-containerized-wordpress) changes haven't been propagated on [Ansible Galaxy for same role](https://galaxy.ansible.com/AdnanHodzic/containerized-wordpress/).

I'd want if my role would show up in search results if someone is looking for ["wordpress letsencrypt"](https://galaxy.ansible.com/list#/roles?page=1&page_size=10&autocomplete=wordpress%20letsencrypt) on Galaxy, which currently isn't the case. I don't want to re-import the role from begining or create another role to avoid having duplicates.

So is there any way my role can be updated to its new title accordingly?

**Comment by chouseknecht** [comment]
@AdnanHodzic 

Update the description in `meta/main.yml`. Galaxy gets the description from the metadata.
