### ISSUE TITLE
issue with docker-py

### ISSUE THREAD

**Issue by jlozadad** [ansible/galaxy#412]
hello,

Just tried to install using docker local option and using a virtualenv with docker-py,docker and docker-compose and I get this error during install https://pastebin.com/sM34PtpG
but, if I remove docker-py and leave it with docker and docker-compose the installation succeeds.
```
docker-py-1.10.6
docker-3.1.4 
docker-compose-1.20.1
```

**Comment by chouseknecht** [comment]
@jlozadad 

What version of Ansible are you using?

**Comment by jlozadad** [comment]
ansible 2.5

**Comment by jlozadad** [comment]
I'll close this since you are changing the readme and doing `pip install docker` fixed this for me.
