### ISSUE TITLE
Limit Namespace creation and deletion to Staff

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#433]
There's concern that anyone can log into Galaxy and create any Namespace they like. This leaves us vulnerable to folks creating namespaces for which they have no actual copyright or claim.

- [x] Disable the Add button on My Content when the user is not a staff member
- [x] Namespace owners can enable/disable a namespace, but they cannot delete. Add a delete button on My Content that is only enabled when the user is a staff member.
- [x] Add a route guard for /my-content/add. Only staff members should be allowed to navigate to the page.

**Comment by chouseknecht** [comment]
Also, for admins, don't require provider namespaces to be associated with the Namespace. Will need to test what happens with Add Content when no provider namespaces are available.

**Comment by duckie** [comment]
Hi guys

That's well and great, but how can I create a namespace for my company ? Do you have a dedicated process for it, an email address I can write to ?
