### ISSUE TITLE
Galaxy QA Deployment

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#444]
We're working toward deploying on OpenShift

- [x] Deployment should be based on the `installer`, not the old `deploy` playbooks
- [ ] Modify the Red Hat branding to work in the new UI framework (house)
- [ ] Build an image that contains the Red Hat branding
- [x] Figure out where to push the image (Does engint have a registry? Check with Steven Speicher)
- [x] Test the deployment
- [x] Configure a route, and point galaxy-qa.ansible.com with an SSL certificate

**Comment by cutwater** [comment]
> Figure out where to push the image (Does engint have a registry? Check with Steven Speicher)
OpenShift allows pushing images to its internal registry. For more details refer to https://blog.openshift.com/getting-started-docker-registry/
