### ISSUE TITLE
Problems registering with Galaxy

### ISSUE THREAD

**Issue by keirbadger** [ansible/galaxy#471]
Howdy,

I'm trying to register in Ansible Galaxy using my github account (keirbadger). I have not received the verification email and it has been over 30 minutes. I have attempted to re-request the verification email but still have not received it. Would you be able to help? The email associated with this github account is keir.badger@acuris.com.

Thanks!

**Comment by chouseknecht** [comment]
For some reason the `keirbadger` user account has a barclays email address. The account was created on Jan 30, 2018.  Updated it to the acuris.com address. Hopefully, when you log in and log out, it won't get switched back.

There is also a `keirbadger03` user account created a few days ago. It has a gmail email address. Let me know, if you want to update that address as well.

**Comment by chouseknecht** [comment]
Marked the acuris address as the primary address, and set it to verified.

FWIW, there is a `Manage E-mail` menu option under your username (top right). It's available when you're logged in, so you may not have been able to access it.

**Comment by keirbadger** [comment]
Thanks for the help.
Just tried to login and got a 500 server error :(
