### ISSUE TITLE
Start an import on POST or UPDATE of /repostories

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#485]
Adding new content to a Namespace is currently a 2 step process for the UI. It first creates a repository, and then it submits a request to start an import. Ideally, this should be a single step.

To simplify the UI, when a user creates a new repository or updates an existing repository, the API should automatically trigger an import of the repository. The result returned by the API should be the new or modified repository, and the serializer should include the new import task in `latest_import` within `summary_fields`.

**Comment by cutwater** [comment]
@chouseknecht Just a side note: as we discussed during Tower API meeting, AWX team uses `summary_fields` in a very different way.

**Comment by cutwater** [comment]
Fixed by #493
