### ISSUE TITLE
Import of *_plugin and module_utils not working

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#486]
### Reproducer:

Fork, and import [atestuseraccount/galaxy-test-role](https://github.com/atestuseraccount/galaxy-test-role)

### Expected Results
- Each individual '.py' file found in 'library' is imported, and represented in /content
- Each individual role found in 'roles'  is imported, and represented in /content 
- Each individual '.py' file found in 'module_utils' is imported, and represented in /content
- Each individual '.py' file found in 'strategy_plugin' is imported, and represented in /content

### Actual results
- Each individual '.py' file found in 'library' is imported, and represented in /content
- Each individual role found in 'roles'  is imported, and represented in /content 
- '.py' files found in 'strategy_plugin' are not imported, and not returned in the /content results
- '.py' files found in 'modules_utils' are not imported, and not returned in the /content results
- An item named 'module_utils' is returned in the /content results.

**Comment by cutwater** [comment]
@chouseknecht IIRC when we designed `module_utils` feature it was supposed to import module utils as a single content item, not each file individually.
