### ISSUE TITLE
My Imports long polling 

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#489]
My Imports long polls to update the status of imports. It currently fetches all imports for the user, and updates the list of imports on the left side of the page. This update causes some bounce on the page.

It doesn't actually need to update all imports. Instead, it should only poll on the current import, and update the log information. All we care about is that the log for a running import gets updated in near real-time.

**Comment by cutwater** [comment]
@chouseknecht is it a critical bug? It seems that it's rather a feature and not critical, since it doesn't blocks our release.

**Comment by chouseknecht** [comment]
It's not critical for this release, but I feel a sense of responsibility, I suppose. Fixed by #502.
