### ISSUE TITLE
User defined role and repository names

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#498]
As an author, it should be easy to set the role or repository name for my content.

Define a consistent method of determining a repository \ role name that can be used by the Galaxy CLI, and Pulp.

**Acceptance criteria:**
* The UI should not be used to set the repo name, or role name.
* User should not need to log into Galaxy, in order to trigger an import.
* Single import User shouldn't have to import something 2x, in order to get it named correctly.
* Role contributors should be able to set the role name.
* Role name should be set in metadata, and metadata should be the single source of truth for alternate name.

**Action Items:**
_TBD_

---
- [x] When importing a traditional role, where a `meta/main.yml` exists at the root of the project, the following will be used to set the role name on the Galaxy server:
    - Use `galaxy_info.role_name`, if set in `meta/main.yml`
    - ~~When `galaxy_info.role_name` is not set, then start with the SCM repository name, and remove /^ansible-role[-_+.]/, remove /^ansible[-_+.]/, and remove /^role[-_+.]/~~

- [ ] When importing a role from a multi-content repository, the following will be used to set the role name on the Galaxy server:
    - ~~Use `galaxy_info.role_name`, if set in `role_directory_name/meta/main.yml`~~
    - ~~When `galaxy_info.role_name` is not set, then start with the role's directory name , and remove /^ansible-role[-_+.]/, remove /^ansible[-_+.]/, and remove /^role[-_+.]/~~

- [ ] The UI will not attempt to override the repository or role name, ~~nor will it allow the user to override a repository or role name. The logic for setting the repository and role name will exist only in the API.~~

- [x] The UI will continue to allow the user to override the Repository name

- [ ] When the UI submits a repository for import, it will receive the repository `original_name` and `name` attributes, and surface them accordingly 

- [ ] ~~Update the role `init` templates in Galaxy CLI to include `galaxy_info.role_name`~~

**Comment by chouseknecht** [comment]
@alikins @daviddavis

Let me know, if you have questions or comments regarding the above.

**Comment by daviddavis** [comment]
LGTM 👍

**Comment by chouseknecht** [comment]
We still have this wrong. 
- The UI should not be used to set the repo name, or role name. You should not need to log into Galaxy, in order to trigger an import, and you shouldn't have to import something 2x, in order to get it named correctly.
- Role contributors expect to be able to set the role name.
- Role name should be set in metadata, and metadata should be the single source of truth.

**Comment by chouseknecht** [comment]
@cutwater see my comment above

**Comment by cutwater** [comment]
@chouseknecht How we should handle repositories until we implement support of `.ansible-galaxy.yml` metadata file.

**Comment by chouseknecht** [comment]
@cutwater 

For now we're punting. There won't be a facility for overriding the name of a multi-content repository. When we implement `ansible-galaxy.yml`, we'll discuss it, and evaluate feedback, to see if we really need the feature.

**Comment by chouseknecht** [comment]
@alikins 

@cutwater added support for `galaxy_info.role_name` in `meta/main.yml` on the server import side. Please do the same on the install side. Ping, if you have questions.
