### ISSUE TITLE
supported platforms in metadata

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#52]
_From @opichon on April 23, 2017 14:20_

Where can I find the list of supported platforms for a role metadata?

Or more generally a complete description of the metadata syntax.

_Copied from original issue: ansible/galaxy-issues#256_

**Comment by chouseknecht** [comment]
_From @danlamanna on April 25, 2017 17:25_

This would be a great topic to have documented. Current practice for me is googling and discovering how other roles have things set up.

**Comment by chouseknecht** [comment]
_From @roumano on May 2, 2017 21:2_

👍 
Can't find from google but this links list of supported platforms for a role metadata 👍 
https://galaxy.ansible.com/api/v1/platforms/
you can adapt the query like this : https://galaxy.ansible.com/api/v1/platforms/?name=EL and the result is a json, so managable by ansible too ...

**Comment by mwilck** [comment]
This method doesn't work any more,
https://galaxy.ansible.com/api/v1/platforms/ returns HTTP 404

Any idea what else to use?

**Comment by stdevel** [comment]
Just stumbled upon the same issue. Is there something comparable for the new Ansible Galaxy?

**Comment by hdub-tech** [comment]
@mwilck @stdevel - I had the same question and, while I'm not sure that this is the "right" answer, I did find the ansible-lint schema for platforms: 

https://github.com/ansible/ansible-lint/blob/v24.2.3/src/ansiblelint/schemas/meta.json

(Linked to current version at this time, as the [README in the same directory](https://github.com/ansible/ansible-lint/blob/v24.2.3/src/ansiblelint/schemas/README.md#schema-bundle) mentions a planned future consolidation to just the ansible.json)

Edit: Looks like `platforms` is going to be removed soon: https://forum.ansible.com/t/role-meta-data-platform-key-broken/4651/9
