### ISSUE TITLE
Not all repositories have a 'format' value

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#544]
##### SUMMARY
Finding existing Repository objects (things that existed in V2, and got upgraded) with a format = null.

##### STEPS TO REPRODUCE
Query: `/api/v1/repositories/?provider_namespace__namespace__name__iexact=030`

##### EXPECTED RESULTS
All pre-existing repositories should have a format = 'role'.

##### ACTUAL RESULTS
Repositories exist with no format.

**Comment by chouseknecht** [comment]
Repositories with a format = null might be the same ones that have 0 Content objects. Once those are handled, this problem may go away.

**Comment by cutwater** [comment]
Relates to #540
