### ISSUE TITLE
Verify and improve content download count calculation

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#556]
As a user, I expect Download count to be reasonably accurate, as it impacts search result relevance

- [x] Track download count at the repository level. It's currently a Content attribute
- [x] Coordinate between old client, and new client how to determine a download.
- [ ] ~~Review existing throttle code. Research, should we keep it, can we make it better?~~

**Comment by alikins** [comment]
For throttling, one approach that could help is having the client send some per system info along with http requests (for ex, generating a uuid on first use of client on a system and sending it along with each request in the future).

That should help distinguishing between multiple systems that end up with the same ip address.  In production, it will also help troubleshooting any issues that seem to effect particular clients (assuming this info also makes it in the logs)

**Comment by cutwater** [comment]
> For throttling, one approach that could help is having the client send some per system info along with http requests (for ex, generating a uuid on first use of client on a system and sending it along with each request in the future).

This approach can give more accurate results than throttling by IP addresses, however I am worried about stateless CI systems. In case somebody executes client from container, UUID will be different on each run.

P.S. Maybe it's worth to think in different direction. PyPi removed download counts at all and they described their reasons behind this decision: https://mail.python.org/pipermail/distutils-sig/2013-May/020855.html. Some of them seem to me legitimate in context of galaxy.

**Comment by chouseknecht** [comment]
@cutwater 

Based on those examples, my thinking is that we do 2 things:

1. Remove any attempt at throttling.
2. Track it at the repo level
3. Track over last 30 days. Maybe something was popular and/or maintained in the past, but now it's not
4. Make it easy to get total, overall downloads for the last 30 days.

Before we do any work on this, let's review as a team. Adding as a topic to the weekly server meeting agenda.

**Comment by alikins** [comment]
@cutwater Looking at this again, I think my comments at https://github.com/ansible/galaxy/issues/556#issuecomment-390673783 doesn't make sense for this download_count (the one potentially displayed to users). The per system uuid case would be better suited for abuse detection, but doesn't seem necessary for user facing info.

**Comment by chouseknecht** [comment]
@newswangerd 

Review the UI, and make sure we're surfacing download count correctly. It should show up on Search and Content Details. On Content Details it may actually be hardcoded to 0, as we were waiting for it to land on the Repository object and /api/v1/repositories endpoints.

**Comment by chouseknecht** [comment]
@newswangerd 

We need to add the logic for incrementing the download count on the backend. It was lost when we removed the throttle code. For the old throttle code, see:  https://github.com/ansible/galaxy/commit/69d6b53ceac7cc4c1720001139b4538d35cb36a7#diff-ff62d95fd3235dce68994aff3ecef764L34 

Add to the RoleList view the logic (from above) that checks for query params 'owner__username' and 'name', and if found, increments the download count.

Here's the corresponding code in the legacy Ansible client: https://github.com/ansible/ansible/blob/devel/lib/ansible/galaxy/api.py#L192
