### ISSUE TITLE
Verify UI gracefully surfaces data integrity errors

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#570]
- [x] Verify namespace.name invalid char validation errors are surfaced on Namespace create/edit form
- [x] Verify namespace.name unique constraint errors are surfaced on Namespace create/edit form
- [x] Verify repository.name is surfaced correctly should the API replace '.' with '_', on My Content
- [x] Verify repository.name invalid char validation errors are surfaced, on My Content
- [x] Verify content name invalid char validation errors from the import process are surfaced, on My Imports
- [x] Verify content name unique constraint validation errors from the import process are surfaced, on My Imports

**Comment by chouseknecht** [comment]
Depends on #429

**Comment by newswangerd** [comment]
Last bullet fails. See #664
