### ISSUE TITLE
Inconsistent licensing info in ansible/galaxy repo

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#58]
_From @grossws on February 7, 2017 21:40_

https://github.com/ansible/galaxy repo contains `LICENSE` file with Apache License v2 and `license='Proprietary'` + `'License :: Other/Proprietary License',` in `classifiers` in `setup.py`.

_Copied from original issue: ansible/galaxy-issues#233_

**Comment by chouseknecht** [comment]
Fixed.

**Comment by grossws** [comment]
@chouseknecht, also `package.json` has `"license": "Commercial"` in it
