### ISSUE TITLE
Galaxy does not respond when importing large repository

### ISSUE THREAD

**Issue by cutwater** [ansible/galaxy#583]
##### SUMMARY
When importing large repository https://github.com/drybjed/debops-qa/ Galaxy does not respond.

##### STEPS TO REPRODUCE
1. Import repository https://github.com/drybjed/debops-qa/

##### EXPECTED RESULTS
Repository imports successfully.

**Comment by chouseknecht** [comment]
@cutwater 

Forked the repo to `atestuseraccount/debops`, and added a symlink `roles -> ansible/roles` in the master branch.

I was able to import the fork to my local dev environment. There are a bunch of things that our static analysis flagged. Think they are all module/plugin related. 

Here's a gist of the output: https://gist.github.com/chouseknecht/ea1949f4b1c0999f82fcaa66da38be72

**Comment by drybjed** [comment]
@chouseknecht Interesting. Do you plan to publish the linter somewhere separately, so that the users could validate their repositories locally before importing them on Galaxy?

**Comment by drybjed** [comment]
I updated the [DebOps monorepo](https://github.com/debops/debops/) to fix most of the issues reported by the linting tool. I'm not sure about the errors found in the Python scripts, `pycodestyle` doesn't report anything. What tools are you using for linting the scripts?

**Comment by cutwater** [comment]
@drybjed Currently we use `flake8` and `yamllint` slightly customized to match ansible coding style.

**Comment by drybjed** [comment]
@cutwater Thanks, I'll check them out.

**Comment by chouseknecht** [comment]
Snippet from IRC: 

> ok, so if a role with the same name already exists in an organization, say 'debops.nginx', the same > role from multi-role repo gets skipped
> 9:36 AM but if roles in multi-repo have names like 'debops.monorepo.nginx', wouldn't that make the two cases different?
> 9:37 AM either import all roles in the multi-role repo under 'org.repo.*' namespace, or skip existing ones as it is now, but publish multi-role repo roles as '<org>.<role-name>' namespace
> 9:37 AM the second option would be better, IMO
> 9:39 AM this is very important for dependency resolution - for example, my current 'debops.nginx' role depends on 'debops.secret' in meta/main.yml
> 9:39 AM let's see what happens if I remove that role and re-import the monorepo...
> 9:43 AM yeah... so i removed 'debops.secret' and now buch of roles is skipped during import because the dependency doesn't exist
> 9:43 AM so I would need to move all of the roles in my repository to be named like, debops.monorepo.secret
> 9:44 AM so that the import would make sense
> 9:46 AM interesting, the debops.nginx role has been imported as debops.monorepo.nginx, but now it doesn't have any role dependencies - which it definitely has
> 9:46 AM so guys, let me know if I need to rename all my roles and update playbooks, or will you publish roles as <org>.* namespace :-)

Based on the above, we need to do the following:

- [ ] Eliminate individual role install instructions. I think we've decided to not support installing individual pieces of content from a multi-content repo. As is evident from the above, it confuses everyone. 
- [ ] Test that individual roles can be referenced as dependencies using `<namespace>.<role_name>` 
- [ ] Test dependency resolution during import. Roles within the same repo should be able to depend on one another.

**Comment by drybjed** [comment]
For the first point, I assume that the multi-role repository would be downloaded to `~/.ansible/content/roles/<org>.<repo>/`, correct? In that case how would the roles be referenced in playbooks?
```
- name: Example playbook
  hosts: all
   roles:
     - role: 'org.repo/org.role1'
     - role: 'org.repo/org.role2'
```
Or would that be something else? Because this also might require updates to role dependencies.

**Comment by chouseknecht** [comment]
The plan is to install roles as:

```
~/.ansible/content/<namespace>/roles/
    role1/
    role2/
    role3/
    ...
```

And then referencing them in a playbook would look like the following:

```
- name: Example playbook
  hosts: all
   roles:
     - role: '<namespace>.role1'
     - role: '<namespace>.role2'
```

**Comment by drybjed** [comment]
I see, so in addition to Ansible resolving role names in directories specified by `roles_path`, Ansible will also support more advanced directory structure in `~/.ansible/content/`, correct? Would the `~/.ansible/content/` need to be added to `roles_path` (implying that other directories with this structure might exist), or will that be hardcoded in Ansible, or configured via yet another option in `ansible.cfg`?

**Comment by chouseknecht** [comment]
We're working on the path question now. The role loader will likely prepend `ANSIBLE_CONTENT_PATH` to  `ROLES_PATH`, giving the precedence the new content path scheme.

**Comment by chouseknecht** [comment]
I think we can close this discussion for now, and open new issues as needed during the development of 3.2 where we'll be finally solving collections.
