### ISSUE TITLE
Infrastructure: Move migration out of container init

### ISSUE THREAD

**Issue by cutwater** [ansible/galaxy#600]
##### SUMMARY

Currently we apply migrations as a part of galaxy container initialization. It leads to simultaneous migrations applying when running more than one instance of galaxy container.
We should move migrations apply out of container and configure OpenShift to apply migrations when upgrading galaxy service.

##### EXPECTED RESULTS
OpenShift runs pod to apply migrations as a part of upgrade process before starting galaxy containers.

**Comment by chouseknecht** [comment]
@cutwater @matburt 

Please coordinate with the Tower team, and see how they're handling this issue. I believe they have solved it already, and it would be good to consider their solution, and maybe borrow it.

They also did something really cool with custom middleware (I think), that tells the UI to show a message and spinner while migrations are being applied. It would be good to capture that, and apply the same to Galaxy.

Remember, Tower and Galaxy are sister products, so anything we can do to make the UX feel similar, we do it.

**Comment by chouseknecht** [comment]
Agree, they are separate issues, and we will track them separately. Just wanted to point out that while you're looking at Tower, and potentially asking the engineering team for information/help, it would be good to get all of the information (or as much as possible) in one go.

Thanks for thinking about this whole problem, and working on it. I'm really excited to see the solution come together!
