### ISSUE TITLE
Trouble signing up / logging into galaxy via Github

### ISSUE THREAD

**Issue by someara** [ansible/galaxy#631]
I'm having trouble signing up / logging into galaxy via Github... I had a defunct email as the primary address in my Github profile. I've since fixed that and revoked/reauthorized galaxy, but it feels like there's something cached somewhere.

jlozadad in IRC suggested I create an issue in the ansible-galaxy repo.

If this isn't the correct place, please point me in the right direction.

Thanks in advance,

-s

**Comment by chouseknecht** [comment]
Looking at this now...

**Comment by chouseknecht** [comment]
@someara 

Galaxy had an email address for you @ fastly, and it was not verified. I changed it to verified. That should fix any issues you're seeing. 

Please verify that it's working as expected. 

Thanks!

**Comment by chouseknecht** [comment]
@someara 

Also, once you get signed in, there is a 'Manage E-mail' option in the account drop-down menu. From there, you can change the email address.

**Comment by someara** [comment]
Works now. Thanks!
-s
