### ISSUE TITLE
Please add 10.13 to MacOS platform versions

### ISSUE THREAD

**Issue by elliotweiser** [ansible/galaxy#654]
## Summary

For Ansible roles that aim to officially support MacOS 10.13 (High Sierra), it would be nice if they could declare version `10.13` for the `MacOS` platform in their `meta/main.yml`. However, `10.13` is missing from this list in the [Galaxy Platforms API](https://galaxy.ansible.com/api/v1/platforms/?name=MacOSX). Any chance this could be updated? 

Tangential question: what is the general process by which platform updates are reflected in Ansible Galaxy?

**Comment by chouseknecht** [comment]
Added. Note the name is "macOS", and the release is "High-Sierra"

https://galaxy.ansible.com/api/v1/platforms/?name=macOS&release=High-Sierra

**Comment by elliotweiser** [comment]
I was wondering why the platform name was different from what I expected. It turns out I typo-ed the platform name (`MacOSX`). Sorry about that.

As long as there's something to declare, it's probably fine. Any thoughts on consolidating these two platforms? It's a little strange that there are two.

https://galaxy.ansible.com/api/v1/platforms/?name=MacOSX
https://galaxy.ansible.com/api/v1/platforms/?name=macOS

**Comment by lhazlewood** [comment]
@chouseknecht can you help please clarify why there are two different names and version sets for Mac?  Having two platforms for the same actual platform causes difficulty and complexity.  Which are we supposed to use as the canonical source?  Thanks.

**Comment by lotyp** [comment]
> I was wondering why the platform name was different from what I expected. It turns out I typo-ed the platform name (`MacOSX`). Sorry about that.
> 
> As long as there's something to declare, it's probably fine. Any thoughts on consolidating these two platforms? It's a little strange that there are two.
> 
> [galaxy.ansible.com/api/v1/platforms/?name=MacOSX](https://galaxy.ansible.com/api/v1/platforms/?name=MacOSX) [galaxy.ansible.com/api/v1/platforms/?name=macOS](https://galaxy.ansible.com/api/v1/platforms/?name=macOS)

MacOSX probably stands for OSX = X means 10.x
Apple renamed their releases after end of cycle of 10.x releases

So:
MacOSX = legacy
MacOS = current
