### ISSUE TITLE
Multi role repositories with roles that have the same name overwrite each other.

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy#664]
When you import a repository with multiple roles that have the same name in `meta/main.yml` or the name of the folder, the application should throw an error on import and fail, but instead one role overwrites the other.

Try importing https://github.com/newswangerd/same-name-test. There are two roles here, but after the import only one shows up in Galaxy.

**Comment by newswangerd** [comment]
We also need to validate that the names in `meta/main.yaml` are case insensitively unique.

**Comment by chouseknecht** [comment]
Punting this for now. Mazer is installing content to the local filesystem as `namespace.repository_name`. For example, the GitHub repo geerlinguy/ansible-role-apache gets installed locally as `~ansible/content/geerlingguy.ansible-role-apache/roles/apache/`.

This doesn't align with our unique index on Content, which is currently Namespace.name + contenty_tpe + name. It doesn't account for Repository.original_name. We need to decide what the implication is of adding Repository.original_name to the index, as it probably changes how we present things in the UI.
