### ISSUE TITLE
Can not import my role

### ISSUE THREAD

**Issue by gforcada** [ansible/galaxy#674]
##### SUMMARY
I updated my role and galaxy.ansible.com seems to not be able to import it.

My role: https://github.com/gforcada/ansible-compile-python

##### STEPS TO REPRODUCE
Do a commit and tag a role and go to the galaxy import roles functionality.

It keeps spinning for a while, and afterwards complains with:

```
Starting import 251965: role_name=compile-python repo=gforcada/ansible-compile-python
Import timed out, please try again. If you continue seeing this message you may have a syntax error in your meta/main.yml file. 
```
I did import that role quite a few times, and the ``meta/main.yml`` file hasn't been touched between the last import and the current one that fails.

##### EXPECTED RESULTS
That the role is successfully imported in galaxy.ansible.com

##### ACTUAL RESULTS
An error message is printed, see above.

**Comment by chouseknecht** [comment]
When the import process attempts to access the GitHub API, it seems to be having trouble with the token we have in our database for you. Here's the error:

```
Role 10071: INFO - Starting import 253856: role_name=compile-python repo=gforcada/ansible-compile-python
[2018-06-20 15:17:14,687: INFO/MainProcess] Task galaxy.main.celerytasks.tasks.import_role[6dbb77e1-1efc-4a56-ae4d-f3e4927123bb] raised expected: BadCredentialsException(401, {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'})
```

I suspect if you go to `https://galaxy.ansible/com` and logout/login, that should refresh the OAuth token.

**Comment by gforcada** [comment]
@chouseknecht thanks! That was it.

**Comment by gforcada** [comment]
@chouseknecht as a post mortem, a more explanatory error message would be helpful :+1:
