### ISSUE TITLE
Update installer to work with release/3.0

### ISSUE THREAD

**Issue by greenscar** [ansible/galaxy#675]
##### SUMMARY
README.md link to "inventory file" broken / file missing

##### STEPS TO REPRODUCE
goto https://github.com/ansible/galaxy/blob/release/3.0/INSTALL.md#pre-deployment-steps
click either of the [inventory](https://github.com/ansible/galaxy/blob/release/3.0/installer/inventory) links.

looking @ the develop branch, there is the *installer* dir... which is missing in 3.0 branch.
##### EXPECTED RESULTS
it works? :)

##### ACTUAL RESULTS
404

**Comment by chouseknecht** [comment]
It's on the `develop` branch. Soon we'll merge the two branches and fix the installer. Apologies for the inconvenience.

**Comment by cutwater** [comment]
Duplicate of #487
