### ISSUE TITLE
Cannot delete wrong import

### ISSUE THREAD

**Issue by lucianprecup** [ansible/galaxy#684]
##### SUMMARY
I launched a wrong import by error: 
```
$ ansible-galaxy import lucianprecup https://github.com/adelean/ansible-oracle-java.git
```
The import is stuck here: 
```
Starting import 253767: role_name=https://github.com/adelean/ansible-oracle-java.git repo=lucianprecup/https://github.com/adelean/ansible-oracle-java.git
```
and it appears in searches : https://galaxy.ansible.com/list#/roles?page=1&page_size=10&autocomplete=oracle%20java%20github

Furthermore, I cannot delete the import: 
```
$ ansible-galaxy delete lucianprecup "https://github.com/adelean/ansible-oracle-java.git"
ERROR! Galaxy user lucianprecup does not have access to repo lucianprecup/https://github.com/adelean/ansible-oracle-java.git
```

##### STEPS TO REPRODUCE
Issue a wrong import query in this way: 
```
ansible-galaxy import <user> https://github.com/<company>/<repo>.git
```
Try to delete the import: 
```
ansible-galaxy delete <user> "https://github.com/<company>/<repo>.git"
```

##### EXPECTED RESULTS
The wrong import should be properly deleted.

##### ACTUAL RESULTS
```
ERROR! Galaxy user <user> does not have access to repo <user>/https://github.com/<company>/<repo>.git
```

**Comment by chouseknecht** [comment]
Are you attempting to delete the 'import', or do you actually want to remove the role from Galaxy?

It seems your Galaxy roles are imported under the GitHub username of 'adelean'. You can view them here: https://galaxy.ansible.com/adelean/

If you're attempting to delete the role from Galaxy, the CLI command would be:

```
ansible-galaxy delete adelean ansible-oracle-java
```

If that doesn't work, and it may not, if you renamed your GitHub user account, let us know. We can delete your roles, and then you re-import them under the correct GitHub username.

**Comment by chouseknecht** [comment]
BTW, the import command will be the same:

```
ansible-galaxy import adelean ansible-oracle-java
```

**Comment by lucianprecup** [comment]
Hello,

The adelean roles are correct. The issue I have is with a wrong import (see above). That also created a role that was here https://galaxy.ansible.com/list#/roles?page=1&page_size=10&autocomplete=oracle%20java%20github. It is no longer there so it's fine for the Galaxy role. 

So, in this case, I have an issue with the 'import'. I am talking about this one (see screenshot :  
![ansible_galaxy_error](https://user-images.githubusercontent.com/1573533/41708465-f9f8da42-7540-11e8-90fa-008482b0c6df.png) )

**Comment by chouseknecht** [comment]
@lucianprecup 

I think the only thing to do is to delete the unwanted role created by the errant import. Closing this.
