### ISSUE TITLE
Disallow additional special chars in Namespace and Repository names

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#692]
From the content namespace discussion with the core team, Galaxy server must enforce the following:

For namespace names:
- Only accept word characters. No '-' or '.' are allowed.
- Enforce a minimum length of 2 characters
- Don't allow leading '_'

For repository names:
- Convert '-' and '.' to '_', so that the resulting repository name contains word chars only
- Enforce a minimum length of 2 characters
- Don't allow leading '_'

Test from the UI side that the above is true, and that useful errors are surfaced.

**Comment by newswangerd** [comment]
@chouseknecht  if we disallow '-' and '.' in namespace names, won't that make it impossible for some people to create accounts on galaxy?

**Comment by chouseknecht** [comment]
See comment on #429 for repository/role import fixes 

Fix account creation during login. This is the login signal handler. Replace the if statement on line #44 with logic something like the following: 

- Get the user's social login, e.g. newswanger-test
- Convert social login to lowercase, and replace [-.] to _, giving newswanger_test
- Check to see if a namespace matching the converted social login exists. If so, exit
- Create a namespace for the converted social login
