### ISSUE TITLE
Home UI improvements

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy#709]
Galaxy Home:

Breadcrumbs 
- Breadcrumbs in general need fixing to match the styling in the mockups.

Panels
- All panel styles should match as there are two different kinds on the landing screen.

Featured Vendors Panel
- Arrows are #b7b7b7 and fa-caret left/right.

Most Popular Panel
- Content left align vs center
- hover color #f2f2f2

**Comment by chouseknecht** [comment]
This is probably a duplicate of #719

**Comment by newswangerd** [comment]
Closed as duplicate
