### ISSUE TITLE
UI: Global Style Fixes

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#718]
From @trahman73 

### Breadcrumbs 
- [x] Breadcrumbs in general need fixing to match the styling in the mockups.
- [x] Divider lines need to go all the across.
- [x] Don't fit across mobile phone screens. For small screens should probably be hidden.

### Filters
- ~Tighten up spacing to match mockups.~
- ~Sort dropdown has selection highlighted in a darker blue, while search type dropdown doesn’t have this same behavior.~
- ~Add tooltip to sort button.~

### Buttons (Details and Read Me)
- [x] Match styling, color, and case from mockups for both active and regular states.
- [x] Don’t add disabled to the active button.
- [x] Remove icons.

### Tags/Badges
- [x] Add left/right 5px padding to all tags/badges.

**Comment by newswangerd** [comment]
Unfortunately the filter problems are all issues with patternfly ng, so we can't address them here
