### ISSUE TITLE
UI: Home page style fixes

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#719]
From @trahman73 

### Panels
- All panel styles should match as there are two different kinds on the landing screen.

### Featured Vendors Panel
- Arrows are #b7b7b7 and fa-caret left/right.
- Reduce size of vendor logos to match mockups and keep size consistent in all detail view areas.

### Most Popular Panel
- Content left align vs center
- hover color #f2f2f2

**Comment by newswangerd** [comment]
Reducing the size of the logos turns out to be disproportionately difficult because the height values are non relative and are hard coded into the CSS at different places. In the interest of getting these changes into production before we go live tomorrow, I think it's best to change that later.
