### ISSUE TITLE
UI: Role Detail Style Fixes

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#722]
From @trahman73 

- [x] Match top details area format to mockups.
- [x] Reduce size of icons text of Downloads, Watchers, etc. to match Author Details page.
- [x] ~Remove the form field from Installation and add a copy icon.~
- [x] ~Keep Info and Platform panels in one line to match mockups.~
- [x] Add 5px left/right padding to platform tags/version.
- [x] Match Read Me header styling from mockups.

**Comment by newswangerd** [comment]
#722

**Comment by newswangerd** [comment]
#841

**Comment by newswangerd** [comment]
We can't get ride of the command to download roles because that's an important piece of functionality and we can't put info and platform panels on the same row because there are 4 cards that appear dynamically on the second row depending on what metadata we have about a content item.
