### ISSUE TITLE
Docs home page won't load without a trailing slash.

### ISSUE THREAD

**Issue by tima** [ansible/galaxy#734]
##### SUMMARY

If you omit the trailing slash from the docs site URL (https://galaxy-qa.ansible.com/docs) the page won't load and will eventually timeout.

##### STEPS TO REPRODUCE

Type in https://galaxy-qa.ansible.com/docs (as opposed to click help) in your browser

##### EXPECTED RESULTS

The Galaxy docs home page to load right up.

##### ACTUAL RESULTS

Browser sits at "Connecting" until it times out.

**Comment by chouseknecht** [comment]
Duplicate of #830. Closing this one.
