### ISSUE TITLE
Bluish accents in next galaxy are visually noisy heavier than titles and headers

### ISSUE THREAD

**Issue by akaRem** [ansible/galaxy#746]
##### SUMMARY

inline code is highlighted with blue. And it's the only colourful and contrast thing in readme.
It attracts too much attention and brings some visual noise, see pictures below

I'd propose to stick with old style when inline code had the same colour as code blocks

##### ACTUAL RESULTS

```

```
<img width="1569" alt="image" src="https://user-images.githubusercontent.com/1472728/42062638-d4166050-7b36-11e8-906d-ed3badad773b.png">
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/1472728/42062659-e08d4038-7b36-11e8-943b-f908c5c43143.png">

**Comment by chouseknecht** [comment]
The style of inline code should match that of GitHub. Not sure how it ended up blue.

**Comment by akaRem** [comment]
Additional info if useful:
Safari 11.1.1 (12605.2.8), no browser ext

Same look in Opera and Chrome
