### ISSUE TITLE
Sorting authors by description is useless and strange (next galaxy)

### ISSUE THREAD

**Issue by akaRem** [ansible/galaxy#748]
##### SUMMARY

on https://galaxy-qa.ansible.com/community
If I choose sort by description, then those authors who have empty description are at the top of results, so in order to find ones whose description starts with "A" requires a lot of extra movements

Most of authors duplicate their nickname in description, so this kind of sorting duplicates sort by name.

In conj with prev problem, sorting by description becomes useless

##### ACTUAL RESULTS

```

```
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/1472728/42063287-96cb8a06-7b39-11e8-8d4a-cf58908a57f3.png">

<img width="761" alt="image" src="https://user-images.githubusercontent.com/1472728/42063327-d6bae648-7b39-11e8-844a-49af57923b66.png">

**Comment by chouseknecht** [comment]
Duplicate of #747
