### ISSUE TITLE
Add platform support for cosmic cuttlefish (Ubuntu 18.10)

### ISSUE THREAD

**Issue by fubarhouse** [ansible/galaxy#749]
The Platform API does not include "cosmic" in it's list of supported platforms.

Could somebody please make sure Cosmic Cuttlefish is available to official support?

* https://galaxy.ansible.com/api/v1/platforms/ 
* [Ubuntu 18.10 - Cosmic Cuttlefish](https://wiki.ubuntu.com/Releases)

**Comment by chouseknecht** [comment]
@fubarhouse 

Added. You can view the new platform here: https://galaxy.ansible.com/api/v1/platforms/?name=Ubuntu&release=cuttlefish
