### ISSUE TITLE
Latest version not updated after Travis build notifies Galaxy

### ISSUE THREAD

**Issue by elliotweiser** [ansible/galaxy#776]
##### SUMMARY

There's a possible issue related to importing Ansible roles (and creating new versions/releases) through travis-ci.org using the [Notifications API](https://galaxy.ansible.com/api/v1/notifications)

##### STEPS TO REPRODUCE

I'm not entirely certain about how to reproduce this. I suppose you could try to create a new tag on an existing role and see if this imports correctly when notifying Galaxy from Travis CI. In any case, here's the relevant information in this case.

This is the [notification](https://galaxy.ansible.com/api/v1/notifications/198419/) received by Ansible Galaxy after [this Travis build](https://travis-ci.org/geerlingguy/ansible-role-homebrew/builds/398724591) passed. 

##### EXPECTED RESULTS

The notification should have triggered an import, which would have created the 2.4.3 release.

##### ACTUAL RESULTS

Nothing happened. 2.4.2 remains the latest release.

See versions in https://galaxy.ansible.com/geerlingguy/homebrew

**Comment by chouseknecht** [comment]
Looks like it started the import, but there was an error. Here's a link to the import log:

https://galaxy.ansible.com/my-imports?namespace=geerlingguy&repository_name=homebrew&selected=257923&page_size=10

Not sure why it got a duplicate key error though. Investigating...

**Comment by chouseknecht** [comment]
Somehow I think we're creating new content records, and the new content record of course has '-' converted to '_'.

The unique key on Content is: 'namespace', 'repository', 'name', 'content_type'

During import, in `galaxy/worker/importers/base`, the the get_or_create() is:

```
obj, is_created = models.Content.objects.get_or_create(
            namespace=ns,
            repository=repo,
            content_type=models.ContentType.get(self.data.content_type),
            original_name=original_name,
            defaults={
                'name': self.translate_content_name(name),
                'is_valid': False,
            }
```

I think our unique index is incorrect. It should be based on original_name, rather than name, and then the two would line up.

**Comment by chouseknecht** [comment]
Fixed deployed to https://galaxy-qa.ansible.com - our public QA site. An import in QA should work now, and it should not change '-' to '_'.

**Comment by chouseknecht** [comment]
The patch will be deployed to production tomorrow morning, btw.

**Comment by lae** [comment]
@chouseknecht will this be a retroactive fix as well (i.e. will travis_lxc get renamed back to travis-lxc?)?

**Comment by cutwater** [comment]
@lae `travis_lxc` is fixed.

**Comment by lae** [comment]
Thanks!

**Comment by chouseknecht** [comment]
Closing this issue, as the duplicate key error is fixed, and Travis builds are working. We're still working on NOT renaming existing repo names. See issue #775

**Comment by Voronenko** [comment]
@chouseknecht  What linter is used for roles during the import ?  How can I check role locally before releasing ?

Why galaxy UI does not provide easy way for authors to spot roles with problems in import (especially one via travis hook) ?
