### ISSUE TITLE
Names of roles can't be set

### ISSUE THREAD

**Issue by robertdebock** [ansible/galaxy#791]
##### SUMMARY
The previous version of Ansible Galaxy used to offer a web-interface button to rename roles. That feature is not available anymore, but luckily a [command argument] to ansible-galaxy is available: `--role-name`. This feature does not have the intended result though.

##### STEPS TO REPRODUCE
1. Delete a role from Ansible Galaxy if it exists.
2. Run `ansible-galaxy import {{ github_user_name }} {{ github_repository_name }} --role-name {{ a_role_name }}`
3. See that the role is not saved with the role name `{{ a_role_name }}`.

In my case, I've tried to import: https://github.com/robertdebock/ansible-role-at
With the command: `ansible-galaxy import  robertdebock ansible-role-at --role-name at`
After the (successful) import this can be installed with: `ansible-galaxy install robertdebock.ansible_role_at` where I was expecting to install it with `ansible-galaxy install robertdebock.at`

##### EXPECTED RESULTS
A role renamed to the value given after `--role-name`.

##### ACTUAL RESULTS
The value used in `--role-name` seems to be ignored.

**Comment by thepax** [comment]
I just hit the same issue. Providing role_name has fixed it. 
It's going to be (very) frequently asked question.

**Comment by robertdebock** [comment]
That's actually a lot better than using the web-interface. Thanks @chouseknecht!

**Comment by geerlingguy** [comment]
> Role names are limited to lowercase word characters (i.e., a-z, 0-9) and ‘_’. No special characters are allowed, including ‘.’, ‘-‘, and space. During import, any ‘.’ and ‘-‘ characters contained in the repository name or role_name will be replaced with ‘_’.

(From the docs) This is a little painful to swallow, since legacy roles can still use dashes. Dots I can understand in terms of namespacing... but dashes and underscores should both be allowed imo :P
