### ISSUE TITLE
Custom role names are not longer supported 

### ISSUE THREAD

**Issue by timorunge** [ansible/galaxy#794]
##### SUMMARY
Custom role names are not longer possible since v3.

##### STEPS TO REPRODUCE
Create a new ansible role, e.g. ansible-test and import it in galaxy. The name will be https://galaxy.ansible.com/timorunge/ansible_test. 

In the previous version you have been able to rename the role to "test" which will result in a nice name like e.g. timorunge.test. Now we've timorunge.ansible_test. 

##### EXPECTED RESULTS
It should be possible to rename the roles again.

**Comment by robertdebock** [comment]
Please see #791 .

Boils down to adding `role_name: test` for your role in meta/main.yml.

**Comment by timorunge** [comment]
Thanks @robertdebock. Didn't see the issue before.
