### ISSUE TITLE
Docs: Title is missing on contributing index page

### ISSUE THREAD

**Issue by kbugaienko** [ansible/galaxy#798]
##### SUMMARY
Page title is missing on contributing [1] and finding [2] index pages.

[1] https://galaxy-qa.ansible.com/docs/contributing/index.html
[2] https://galaxy-qa.ansible.com/docs/finding/index.html

![screen shot 2018-06-28 at 15 39 08](https://user-images.githubusercontent.com/3986911/42176186-613e7550-7e28-11e8-95e1-bb53a1828c76.jpg)
![screen shot 2018-06-28 at 16 34 52](https://user-images.githubusercontent.com/3986911/42176187-615f9582-7e28-11e8-9289-0cb6dd622a18.jpg)

##### EXPECTED RESULTS
Docs >> Contributing Content
Docs >> Finding Content

##### ACTUAL RESULTS
Docs >> `<no title>`

**Comment by chouseknecht** [comment]
@kbugaienko 

Thanks for reporting this!

**Comment by chouseknecht** [comment]
Closed by #801
