### ISSUE TITLE
Docs: Logo image on docs site has visible background

### ISSUE THREAD

**Issue by kbugaienko** [ansible/galaxy#799]
##### SUMMARY
On site Galaxy Documentation logo has visible gray background box. 

![screen shot 2018-06-28 at 22 21 45](https://user-images.githubusercontent.com/3986911/42176380-0751d612-7e29-11e8-99b6-1c2faa2a035f.jpg)

##### EXPECTED RESULTS
Logo image should have transparent background.

**Comment by chouseknecht** [comment]
@newswangerd 

It might be easiest to change the navigation background color in `docs/docsite/_themes/sphinx_rtd_theme` to match the logo color. 

We need to apply the same change to ansible/galaxy-deploy. In that case, make the navigation background color match the Ansible logo file, which is that repo as well.
