### ISSUE TITLE
Can't find playbook bundles

### ISSUE THREAD

**Issue by akaRem** [ansible/galaxy#808]
##### STEPS TO REPRODUCE

From main page (https://galaxy.ansible.com/home) click "Playbook Bundles"
It will navigate to https://galaxy.ansible.com/search?content_type=apb&order_by=-relevance&page_size=10 which is empty

##### ACTUAL RESULTS

```

```
<img width="682" alt="image" src="https://user-images.githubusercontent.com/1472728/42217059-78553d88-7ecc-11e8-8c89-9a6c73de5480.png">

**Comment by chouseknecht** [comment]
Have any been imported? I don't know that anyone has actually imported one.
