### ISSUE TITLE
Random search tag is added during navigation

### ISSUE THREAD

**Issue by akaRem** [ansible/galaxy#809]
##### STEPS TO REPRODUCE

goto https://galaxy.ansible.com/search?content_type=apb&order_by=-relevance&page_size=10
<img width="606" alt="image" src="https://user-images.githubusercontent.com/1472728/42217105-9d485e18-7ecc-11e8-9d7f-417bbdf72216.png">
click search
<img width="699" alt="image" src="https://user-images.githubusercontent.com/1472728/42217126-a9cd9fa4-7ecc-11e8-9842-2df9d9102c0c.png">
Contributor type: community is added unexpectedly

##### ACTUAL RESULTS

```

```

**Comment by newswangerd** [comment]
@akaRem I haven't been able to replicate this issue. As far as I can tell we don't have a search button, and clicking the other UI elements doesn't seem to do anything.

**Comment by cutwater** [comment]
@newswangerd @akaRem I guess the issue is about `Contributor Type: community` tag being added? Is that correct?

**Comment by chouseknecht** [comment]
@newswangerd 

If there's already a bunch of query params, and you click the Search menu option, it probably should not automatically add 'vendor=false'
