### ISSUE TITLE
404 on some resources

### ISSUE THREAD

**Issue by akaRem** [ansible/galaxy#811]
##### STEPS TO REPRODUCE

Open console
<img width="749" alt="image" src="https://user-images.githubusercontent.com/1472728/42217345-7b9b4284-7ecd-11e8-8999-387145618675.png">

##### ACTUAL RESULTS

```

```

**Comment by chouseknecht** [comment]
In `ansible/galaxy-deploy`, add the Google Analytics and Hubspot scripts to static assets, and fix the links in index.html.

**Comment by chouseknecht** [comment]
Fixed in `ansible/galaxy-deploy`.

@cutwater please review https://github.com/ansible/galaxy-deploy/pull/19
