### ISSUE TITLE
Tiles are not clickable, but highlighted

### ISSUE THREAD

**Issue by akaRem** [ansible/galaxy#812]
##### SUMMARY

<img width="661" alt="image" src="https://user-images.githubusercontent.com/1472728/42217480-0fd82cc8-7ece-11e8-8271-f5f5f010a2cf.png">

When I mousever `.list-pf-item`, it changes its background.

<img width="660" alt="image" src="https://user-images.githubusercontent.com/1472728/42217465-01f06a80-7ece-11e8-9d28-156f016a4afc.png">

So I expect that Item is tile and interactive. But it's not interacive and click does nothing.
Instead, I should search for a clickable element.

After I mouseover `.description` the cursor changes to `pointing finger`, and I expect that I can click it. But again nothing happens.

In the end I found that only clickable things are build status and title

##### ACTUAL RESULTS

```

```

**Comment by chouseknecht** [comment]
Fix the cursor on description.

**Comment by chouseknecht** [comment]
On all patternfly lists, the list item automatically changes background color on hover. Not changing, as this is default behavior. Also, if we make the item clickable, then individual links within the item don't work as expected, so again, not changing.

#833 fixing the cursor change on description. When hovering over description, the cursor no longer changes.

**Comment by chouseknecht** [comment]
Closed by #833
