### ISSUE TITLE
Text selection on Tags doesn't work properly

### ISSUE THREAD

**Issue by akaRem** [ansible/galaxy#813]
##### STEPS TO REPRODUCE

navigate to search https://galaxy.ansible.com/search?vendor=false&order_by=-relevance&page_size=10

there are `tags` and `search tags` and they look the same way

<img width="400" alt="image" src="https://user-images.githubusercontent.com/1472728/42217682-cbd08434-7ece-11e8-8fe0-61a7ab910c09.png">

The interesting thing here is that cursor changes to `editable` (similar to `I` symbol) on mouseover  but
1) none of tags are editable.
2) you can select text on both
3) on search tags selection is cancelled after mouseover

Why are they editable?
Why text can not be selected on search tags?

##### ACTUAL RESULTS

```

```

**Comment by chouseknecht** [comment]
Setting the cursor on non-clickable tags to 'default'. Hopefully this removes the confusion.

**Comment by akaRem** [comment]
@chouseknecht Still see `I` cursor over tags. Is it intentional?
