### ISSUE TITLE
UI: Search page is not responsive

### ISSUE THREAD

**Issue by akaRem** [ansible/galaxy#814]
##### STEPS TO REPRODUCE

goto https://galaxy.ansible.com/search?tags=development&order_by=-relevance&page_size=10
resize window
<img width="800" alt="image" src="https://user-images.githubusercontent.com/1472728/42218205-7a837800-7ed0-11e8-9e4c-7f3297409b85.png">

##### ACTUAL RESULTS

```

```

**Comment by chouseknecht** [comment]
You mean 'responsive' features.
