### ISSUE TITLE
Popover doesn't hide

### ISSUE THREAD

**Issue by akaRem** [ansible/galaxy#815]
##### STEPS TO REPRODUCE

Popover details or readme, then click
after mouse left it will not hide:
<img width="428" alt="image" src="https://user-images.githubusercontent.com/1472728/42218332-e42d2058-7ed0-11e8-926d-8e724e66097d.png">
<img width="632" alt="image" src="https://user-images.githubusercontent.com/1472728/42218357-fafadd20-7ed0-11e8-92af-dd87eec0987d.png">

##### ACTUAL RESULTS

```

```

**Comment by akaRem** [comment]
<img width="422" alt="image" src="https://user-images.githubusercontent.com/1472728/42218414-29c46dce-7ed1-11e8-9434-8cb9c1aa3b3b.png">

**Comment by chouseknecht** [comment]
Not able to reproduce in Chrome 67.0.3396.99 (Official Build) (64-bit), nor in 52.4.1 (64-bit), both running on Mac OS 10.13.5.

Reproduced in Safari 11.1.1

**Comment by chouseknecht** [comment]
There's an unsolved, yet closed issue in ngx-bootstrap that's related: https://github.com/valor-software/ngx-bootstrap/issues/1702. Also, see 

Plus this one: https://github.com/valor-software/ngx-bootstrap/issues/3294

Clearly issues with ngx-bootstrap's tooltip component and Safari. Upgrading to 3.0.1 (latest stable) doesn't help either. Not sure what we can do to fix this.

**Comment by akaRem** [comment]
Reproducible on Safari 11.1.2 (12605.3.8.1)
Not reproducible on Chrome 67.0.3396.99
macOS 10.12.6 (16G1408)

**Comment by newswangerd** [comment]
I couldn't reproduce this in safari Version 11.1.1 (13605.2.8)

**Comment by newswangerd** [comment]
Since this appears to be a bug in another library we're going to hold off on trying to fix it in Galaxy.
