### ISSUE TITLE
Popular clouds have 0 rating and have strange sorting

### ISSUE THREAD

**Issue by akaRem** [ansible/galaxy#817]
##### SUMMARY

Why the heck those clouds are so popular? Did they pay for popularity?
Did Google pay more than Amazon and more than ovirt? Because A should be sorted higher than G and higher than O from my POV.

##### STEPS TO REPRODUCE

in search page

<img width="237" alt="image" src="https://user-images.githubusercontent.com/1472728/42218480-6214f75c-7ed1-11e8-9573-bec68953866c.png">

##### ACTUAL RESULTS

```

```

**Comment by cutwater** [comment]
The number on the right of cloud platform name indicates repositories / roles count associated with that cloud platform. Since cloud platforms is a new feature and we don't have any related content, numbers are all `0`

**Comment by chouseknecht** [comment]
This seems to be a UI issue. We're not passing 'name' as part of the 'order_by' query param.

**Comment by chouseknecht** [comment]
Fixed by #835

**Comment by akaRem** [comment]
Still reproducible on galaxy and galaxy-qa. Is fix deployed anywhere?
