### ISSUE TITLE
UI: Incorrect column arrangement on some author's profile pages

### ISSUE THREAD

**Issue by kbugaienko** [ansible/galaxy#819]
##### SUMMARY
On some Author profile pages [1] repositories list is displayed incorrectly. Table columns are not arranged properly.

[1] https://galaxy-qa.ansible.com/aaronpederson

##### ACTUAL RESULTS

![screen shot 2018-07-02 at 16 09 55](https://user-images.githubusercontent.com/3986911/42219617-cb789a64-7ecc-11e8-849b-0c97732c4a72.jpg)

![screen shot 2018-07-03 at 14 25 54](https://user-images.githubusercontent.com/3986911/42219695-1169df2e-7ecd-11e8-81ff-23164b7499ef.jpg)

**Comment by chouseknecht** [comment]
I think there's already an issue to re-factor this page.

**Comment by akaRem** [comment]
Same issue with responsiveness.
On resizing explodes like in https://github.com/ansible/galaxy/issues/814
