### ISSUE TITLE
APB name changed on import

### ISSUE THREAD

**Issue by djzager** [ansible/galaxy#827]
##### SUMMARY

When an APB is imported to galaxy-qa.ansible.com, ie. `postgresql-apb` it's name is changed to `postgresql_apb`.

##### STEPS TO REPRODUCE

Import an APB into galaxy-qa.

![20180703_135528_scrot](https://user-images.githubusercontent.com/569754/42236542-2cce8d04-7ec9-11e8-8200-36067c145ccd.png)

##### EXPECTED RESULTS

The name of the role to be `postgresql-apb`

##### ACTUAL RESULTS

![20180703_135542_scrot](https://user-images.githubusercontent.com/569754/42236561-3c370668-7ec9-11e8-9665-168643c67927.png)

**Comment by chouseknecht** [comment]
Yep. Galaxy is moving toward Python compatible namespaces in preparation for ingesting modules and plugins. Any net new namespace names and repository names are being created without '-' in them.

**Comment by chouseknecht** [comment]
From an API standpoint, as far as finding things, you query on 'original_name', which should contain the actual GitHub repo name.

**Comment by djzager** [comment]
I believe we are OK, no workaround needed, with the way Galaxy is translating. I probably could have looked in the changelog to find why the translation is happening. I don't see any further action required on this front so feel free to close this issue if you agree.

**Comment by chouseknecht** [comment]
Closing. Thanks!
