### ISSUE TITLE
Support BitBucket as repository in addition to GitHub

### ISSUE THREAD

**Issue by strus38** [ansible/galaxy#829]
### Use Case
Currently the Galaxy UI only authorized to have GitHub repo registered.
Since Galaxy can be installed privately, being able to support other GIT compatible source repo could add a lot of value. I suggest BitBucket since it is one of the most used in big companies.

### Proposed Solution
Implement BitBucket the same way GitHub is done currently.

### Alternatives
N/A

### Implementation
N/A

**Comment by chouseknecht** [comment]
Need to get the 3.1 roadmap published. We're not going to add more SCMs. Instead, we're going to add an 'upload' feature, allowing artifacts to be uploaded to Galaxy, and then your source can live anywhere you like. It could even be private.

**Comment by rmauc** [comment]
Hi @chouseknecht 
Can you tell me; was this implemented at 3.1? I don't see any reference to uploads in the contributor guide, roadmap or changelog.
Thanks

**Comment by cutwater** [comment]
Hi @rmauc,

Unfortunately this feature wasn't implemented in 3.1 and it's currently planned to be part of 3.2.

**Comment by rmauc** [comment]
Thanks for the update @cutwater 
Can you tell me when 3.2 is expected?
