### ISSUE TITLE
[BREAKING CHANGES] Package name changes again and again

### ISSUE THREAD

**Issue by tristanbes** [ansible/galaxy#831]
Hello,

Since last week, our Tower instance kept breaking silently because a package name changed (or you changed it I don't know) without notice.

It's been 3 times already that there is a change in this package name breaking 3 times our Tower instance.

This weekend the package `dj-wasabi.telegraf` became `dj_wasabi.telegraf`
Yesterday the package became `dj_wasabi.telegraf` to `dj-wasabi.telegraf`
And today it seems that in a short timeframe, the package name changed again.

What happened ? Will it happen again ? 

https://github.com/dj-wasabi/ansible-telegraf/issues/56#issuecomment-402720871

Thank you

**Comment by fxfitz** [comment]
This is happening to us too. Can we please reach a stable state?

Is there any more information regarding this published somewhere?

**Comment by fxfitz** [comment]
(note: we saw this happen with all Galaxy users who had a dash in their name; not just with dj-wasabi)

**Comment by chouseknecht** [comment]
The '-' in namespaces has been restored with the release of v3.0.2. See [the change log for details and links to PRs](https://github.com/ansible/galaxy/blob/devel/CHANGELOG.rst).

The namespace is back to it's original state of 'dj-wasabi'. To install the role, the command is the same as it was prior to v3.0.0, `ansible-galaxy install dj-wasabi.telegraf`

**Comment by fxfitz** [comment]
Thanks @chouseknecht

**Comment by chouseknecht** [comment]
@fxfitz 

FWIW, we've been sending out Galaxy updates to the [ansible-project](https://groups.google.com/group/ansible-project) Google group.

**Comment by fxfitz** [comment]
Ah, gotcha! I was looking in [ansible-devel](https://groups.google.com/forum/#!forum/ansible-devel). Thanks (and joins ansible-project group). :-)

**Comment by chouseknecht** [comment]
I believe this is resolved, so closing. If you need further assistance, please feel free to open a new issue.

Thanks!

**Comment by tristanbes** [comment]
This is happening again in an intermittent way. We're seeing this right now in our Tower instance. @chouseknecht 
This is becoming very irritating because unstable :/

**Comment by tristanbes** [comment]
Ok this time it seems that it's a role that disappeared. 

```
[WARNING]: - tersmitten.fail2ban was NOT installed successfully: - sorry, tersmitten.fail2ban was not found on
https://galaxy.ansible.com.
```

**Comment by chouseknecht** [comment]
I think there's some confusion between the namespace 'tersmitten' and 'Oefenweb'. In response to #849, we moved roles from 'tersmitten' to 'Oefenweb'. I *think* all the roles actually belong under 'Oefenweb'.
