### ISSUE TITLE
Error! Save repository failed: (Ensure this field has no more than 256 characters.)

### ISSUE THREAD

**Issue by privateip** [ansible/galaxy#843]
##### SUMMARY
Trying to import a new repo and it is generating the following message:

```
Error! Save repository failed: (Ensure this field has no more than 256 characters.)
```

##### STEPS TO REPRODUCE
Import the repo from `https://github.com/privateip/ios`

##### EXPECTED RESULTS
The repo would be successfully imported

##### ACTUAL RESULTS
The web UI produced the error message and the repo was not imported

**Comment by chouseknecht** [comment]
@privateip 

It's getting hung up on the commit message. My guess is that it contains a bunch of spaces, pushing it past the limit of 256 chars.

Adding a fix that will prevent this in the future. Should land next week in v3.0.3. In the meantime, amend the commit message, and it should import.

**Comment by privateip** [comment]
Thanks, just verified that the work around works and reducing the size of the commit message allows me to import the role.  I tend to promote the use of detailed commit messages, is there a new limit to the size of a commit message that Galaxy will accept?

**Comment by chouseknecht** [comment]
The change I made truncates our copy of the commit message to 256 chars before storing it in the DB, just to prevent the error.

We're not actually surfacing the commit message anywhere, so not sure there's value in expanding the amount of data we store. Plus, we have a link to the commit, so if we did surface it, we ould link to the actual commit, where users could view the full message.
