### ISSUE TITLE
Incorrect namespace owners

### ISSUE THREAD

**Issue by paulfantom** [ansible/galaxy#846]
##### SUMMARY

Incorrect owners of roles namespace.

##### STEPS TO REPRODUCE

1. Logged into galaxy as paulfantom
2. Go to "My Content" -> "cloudalchemy" namespace
3. Check "Owners"

##### EXPECTED RESULTS

See same owners as in github (paulfantom and rdemachkovych - https://github.com/orgs/cloudalchemy/people)

##### ACTUAL RESULTS

I see myself (paulfantom) and "tgrzesik" as owners of the namespace, even though "tgrzesik" isn't a member or a collaborator in any of the repositories in cloudalchemy organization. Removing "tgrzesik" from galaxy UI also doesn't work

![screenshot_20180707_203640](https://user-images.githubusercontent.com/3531758/42413681-7ae8e89a-8225-11e8-81d0-e8a6b0efb285.png)

```

```

**Comment by chouseknecht** [comment]
Definitely a bug on that page. 

Managed to remove 'tgrzesik'.

Not finding 'rdemachkovych' in Galaxy. If you have him log into Galaxy, that will create his account, and you should be able to add him as an owner.

**Comment by rdemachkovych** [comment]
@paulfantom I successfully logged in galaxy.ansible.com via github.com account.

**Comment by chouseknecht** [comment]
Confirmed @rdemachkovych is now an owner of the `cloudalchemy` namespace.

Closing this issue, as I believe we have resolved everything. If you run into more problems, please let us know. Thanks!
