### ISSUE TITLE
oefenweb.snmpd was not found on https://galaxy.ansible.com

### ISSUE THREAD

**Issue by theNailz** [ansible/galaxy#849]
I can't install [oefenweb.snmpd](https://galaxy.ansible.com/Oefenweb/snmpd) using `ansible-galaxy install oefenweb.snmpd` (or `ansible-galaxy install Oefenweb.snmpd` for that matter):

```
ansible-galaxy 2.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/itbo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-galaxy
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
Using /etc/ansible/ansible.cfg as config file
Opened /home/itbo/.ansible_galaxy
Processing role oefenweb.snmpd
Opened /home/itbo/.ansible_galaxy
Initial connection to galaxy_server: https://galaxy.ansible.com
Base API: https://galaxy.ansible.com/api/v1
- downloading role 'snmpd', owned by oefenweb
https://galaxy.ansible.com/api/v1/roles/?owner__username=oefenweb&name=snmpd
 [WARNING]: - oefenweb.snmpd was NOT installed successfully: - sorry, oefenweb.snmpd was not found on https://galaxy.ansible.com.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

Looks like https://galaxy.ansible.com/api/v1/roles/?owner__username=oefenweb&name=snmpd does not return any results, while it should return oefenweb.snmpd? Might this be related to the case sensitivity issues of last week?

**Comment by chouseknecht** [comment]
Looks like a data migration problem on our side. You have 136 repositories correctly mapped to the `Oefenweb` namespace. However, only 40 content items (i.e. roles) are mapped to the Oefenweb namespace.

**Comment by cutwater** [comment]
Fixed manually. All remaining 96 repositories were re-assigned to appropriate namespace.
