### ISSUE TITLE
Import on galaxy uses master branch by default

### ISSUE THREAD

**Issue by trishnaguha** [ansible/galaxy#857]
##### SUMMARY

Everytime I am doing import on the role ansible-network/network-engine, it is failing with the following the error. 
Looks like galaxy is trying to clone the branch master, but we do not have a master branch on the repo.
##### STEPS TO REPRODUCE

https://galaxy.ansible.com/ansible-network/network-engine

##### EXPECTED RESULTS

Should import successfully
##### ACTUAL RESULTS

```
INFO Starting import: task_id=261218, repository=ansible-network/network-engine
Task "261218" failed: Command '['git', 'clone', '--quiet', '--depth', '1', '--branch', u'master', 'https://github.com/ansible-network/network-engine.git', '/var/lib/galaxy/downloads/tmpjmPvb3']' returned non-zero exit status 128
```

**Comment by cutwater** [comment]
@trishnaguha I confirm it's a bug in our importer. I fixed in in our database, please initiate import process again.
Issue fix will land with next Galaxy update shortly.

**Comment by trishnaguha** [comment]
@cutwater Thanks very much. Import works now.

**Comment by shepdelacreme** [comment]
Any idea when this is fix is going to make it to the Galaxy site? It is affecting several of our roles.

**Comment by cutwater** [comment]
@shepdelacreme It will land on Galaxy site in next update by the end of this week.

**Comment by chouseknecht** [comment]
I can confirm that this is working in our QA environment. I forked `mindpoint/rhel6-stig` repository and imported it. The result is here: https://galaxy-qa.ansible.com/api/v1/repositories/?provider_namespace__namespace__name=chouseknecht&name=rhel6_stig You can see that `import_branch` is set to *devel*, which matches the repository default branch.

**Comment by chouseknecht** [comment]
This fix will land in production tomorrow morning when `release/3.0.3` is deployed.

**Comment by shepdelacreme** [comment]
Thanks for the update!
