### ISSUE TITLE
Importer doesn't validate meta/main.yml data types ('author')

### ISSUE THREAD

**Issue by 030** [ansible/galaxy#859]
When I try to import the following is shown:

```
INFO Starting import: task_id=215481, repository=030/ansible-firefox
INFO Content search - Looking for file "apb.yml"
INFO Content search - Looking for top level role metadata file
Task "215481" failed: argument of type 'int' is not iterable
```

Is this my author name contains an integer? 

https://github.com/030/ansible-firefox/blob/master/meta/main.yml

**Comment by cutwater** [comment]
From YAML format standpoint your name is integer indeed. The easiest solution would be to enquote your author name:

```
author: '030'
```

On the other hand the error message itself is definitely a bug. Importer should handle this case when validating `meta/main.yml` file.

**Comment by chouseknecht** [comment]
We actually need to move the `meta/main.yml` validation bits into out Ansible Lint and scoring. Let's talk about this, before changing any code.

**Comment by awcrosby** [comment]
Galaxy now handles this case without failing the import, and ansible-lint will warn on it via https://github.com/ansible/ansible-lint/issues/514
