### ISSUE TITLE
Enh: Allow the ability to store roles in internal gitlab instance

### ISSUE THREAD

**Issue by aram535** [ansible/galaxy#86]
Hi, I'm planning on running a copy of ansible-galaxy internally in our company to allow specific internal roles to be published. We're using an internal version of gitlab that'll host the repositories.  Is this something that is possible today?

**Comment by chouseknecht** [comment]
@aram535 

Thanks for the question!

It's not currently possible out of the box. Everything in the Galaxy codebase is specific to GitHub. This is a problem we will eventually solve. In the meantime, if you have some ideas, we would love to hear them.

**Comment by aram535** [comment]
Let me take a look at the code and see what it would take.  Happy to contribute it back.
