### ISSUE TITLE
Repo import error: (Task "262732" failed: argument of type 'NoneType' is not iterable) 

### ISSUE THREAD

**Issue by grooveadelic** [ansible/galaxy#902]
When I try to import my repository (ansible-i2p) on galaxy I get the following failure output:

```
INFO Starting import: task_id=262732, repository=grooveadelic/ansible-i2p
INFO Content search - Looking for file "apb.yml"
INFO Content search - Looking for top level role metadata file
Task "262732" failed: argument of type 'NoneType' is not iterable
```

I had no issue with the import before the new design rolled out. Tried to reauthenticate galaxy just in case. Also for a role I'm not sure the metadata would be in the top level, if it's refering to `meta/main.yml`

**Comment by chouseknecht** [comment]
@cutwater 

The  [meta/main.yml file for this role](https://github.com/grooveadelic/ansible-i2p/blob/master/meta/main.yml) is invalid. Note that `company` is empty, and list of `platforms` does not have the right structure. I suspect one or both is causing the failure. 

Obviously invalid YAML should not cause the import to fail. We should be able to detect invalid YAML, and provide a meaningful error to the user.

Can we fix this as part of `release/3.03`, please.

**Comment by grooveadelic** [comment]
Removed the empty company field and platforms and now the import works. Have to find what the correct format for the platform section is; I'm pretty sure I generated the role with ansible-galaxy init and just tweaked the metadata values.

**Comment by alikins** [comment]
I think this error is because the https://github.com/grooveadelic/ansible-i2p repository does not have a 'description' set.

**Comment by awcrosby** [comment]
Issue was related to platforms not being in correct format, https://github.com/ansible/ansible-lint/issues/514 will warn on this
