### ISSUE TITLE
--role-name option ignored

### ISSUE THREAD

**Issue by quocvu** [ansible/galaxy#906]
##### SUMMARY
when importing a role from Github, the --role-name option is being ignored. The role name is based on the github repo name regardless

##### STEPS TO REPRODUCE

% ansible-galaxy --version                                                                                                                                              ansible-galaxy 2.4.0.0
  config file = None
  configured module search path = [u'/Users/i857085/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-galaxy
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 
% ansible-galaxy import --role-name="postgresql" quocvu postgresql-ansible                                                                                     Successfully submitted import request 263010
INFO Starting import: task_id=263010, repository=quocvu/postgresql-ansible
INFO Content search - Looking for file "apb.yml"
INFO Content search - Looking for top level role metadata file
INFO [role] Linting...
INFO [role] Linting OK.
INFO [role] Created new Content instance: id=27576, content_type="role", name="postgresql_ansible"
INFO [role] Adding role metadata tags
INFO [role] Adding role platforms
INFO Updating repository versions...
Import completed

##### EXPECTED RESULTS
the role should have been `quocvu.postgresql`

##### ACTUAL RESULTS

The role is `quocvu.postgresql-ansible` which is reflecting the repo name

**Comment by cutwater** [comment]
@quocvu This is intended behavior. You can set role name using `galaxy_info.role_name` in `meta/main.yml`. For more details please refer to [Role Names](https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names) paragraph of Galaxy documentation.

**Comment by quocvu** [comment]
Thanks for the link.  That works for me.  What is the usage of the --role-name parameter?
