### ISSUE TITLE
no way to create namespace for github organization

### ISSUE THREAD

**Issue by kharkevich** [ansible/galaxy#909]
##### SUMMARY

In galaxy v.2 we have a easy way to use github organization as namespace in galaxy
https://www.ansible.com/blog/ansible-galaxy-2-release
In v.3 I see no options for it (only import into personal namespace)
##### STEPS TO REPRODUCE

Create new github organization (e.g. https://github.com/lean-delivery/)
Login to galaxy
Try to import any role from github organization
##### EXPECTED RESULTS

We got some way to create special namespace for github organization
##### ACTUAL RESULTS

No way to create special namespace for github organization (only import into personal)

**Comment by chouseknecht** [comment]
We can create it for you. It can be either `lean_delivery`, or `leandelivery`. Which would you prefer?

**Comment by kharkevich** [comment]
Could you please create lean_delivery namespace

**Comment by chouseknecht** [comment]
Created. You have ownership rights, so you should be able to add your GitHub org using the My Content page.

**Comment by kharkevich** [comment]
Cool. But in case attach "lean-delivery" organization into lean_delivery namespace 
I got following error:
Error! This provider namespace is already associated with a Galaxy namespace (lean-delivery)

**Comment by chouseknecht** [comment]
@kharkevich 

Think this is sorted out now. The GitHub organization `lean-delivery` was associated with the `ibarysev` namespace. Looks like that belongs to username `ibarysev`, your co-collaborator. Moved it over to `lean_delivery`, and added user `ibarysev` as a co-owner.

**Comment by kharkevich** [comment]
@chouseknecht thanks!
but one more issue:
if I try import some repository (e.g. `lean-delivery/ansible-role-java`)
I got following error:
`Error! Save repository failed: (Ensure this field has no more than 256 characters.)`

@ibarysev could you please confirm that you have only on `lean_delivery` namespace instead of `lean-delivery`

**Comment by ibarysev** [comment]
@kharkevich, confirm

**Comment by miha-plesko** [comment]
@chouseknecht we have similar situation, can you help us as well, please? Would like to have organization namespace `xlab`.

**Comment by chouseknecht** [comment]
@miha-plesko 

It looks like you already have the GitHub organization `xlab-si` associated with the Galaxy namespace `miha_plesko`. On the *My Content* page, use the Edit Properties option for `miha_plesko`, and change the name to `xlab_si`, and you should be good to go.

**Comment by chouseknecht** [comment]
Closing this issue. If you still need assistance, @miha-plesko, please open a new issue.
