### ISSUE TITLE
adding repositories to lean_delivery failed

### ISSUE THREAD

**Issue by kharkevich** [ansible/galaxy#921]
##### SUMMARY

if I try add some repository (e.g. lean-delivery/ansible-role-java)
I got following error:
Error! Save repository failed: (Ensure this field has no more than 256 characters.)

##### STEPS TO REPRODUCE

go to https://galaxy.ansible.com/my-content/namespaces 
`lean_delivery` namespace
try to add `lean-delivery/ansible-role-java` repository

##### EXPECTED RESULTS

Repository successfully added
##### ACTUAL RESULTS

Failed. Error message:
`Error! Save repository failed: (Ensure this field has no more than 256 characters.)`

UPD: It's can be related to #920 
js console errors:
![console errors](https://i.imgur.com/8ALtPwI.png)

**Comment by chouseknecht** [comment]
This is a known bug we fixed here: https://github.com/ansible/galaxy/pull/845

It will land with release/3.0.3 this Friday, 20 July, in the AM.

**Comment by chouseknecht** [comment]
Closing. Believe this is fixed in #845. Fix will land in production 20 June.

**Comment by chouseknecht** [comment]
I can confirm that importing this role works on our QA site. Forked and imported it under my namespace with no issues.
