### ISSUE TITLE
All roles get my personal namespace instead group one

### ISSUE THREAD

**Issue by miha-plesko** [ansible/galaxy#923]
##### SUMMARY
I would like to import Ansible role that lives on our company's GitHub, https://github.com/xlab-si/ansible-role-nuage-remove-entity to be specific. I would like it to be available to other users as 

```
xlab_si.nuage_remove_entity
```

but it gets assigned under my personal namespace as

```
miha_plesko.nuage_remove_entity
``` 
no matter what.

##### STEPS TO REPRODUCE

1.) Login into Ansible Galaxy as miha-plesko
2.) Navigate to My Content tab

![image](https://user-images.githubusercontent.com/8102426/42902176-094ac6ac-8ace-11e8-9954-7d4862c7ef24.png)
Notice how I'm only able to see my personal namespace `miha_plesko` even if I have two provider namespaces available. If I click **Add Content** the role will be added into my namespace even if it's coming from my company's namespace.

##### EXPECTED RESULTS

I'd expect that I'm somehow able to import role into `xlab_si` namespace.

##### ACTUAL RESULTS

I'm actually only able to import it into `miha_plesko` namespace.

**Comment by miha-plesko** [comment]
@chouseknecht thanks for suggesting visiting the **Edit Properties** page, but namespace field is disabled for me:

![image](https://user-images.githubusercontent.com/8102426/42902642-9e5052c0-8acf-11e8-8c5b-58b14346b56a.png)

Could this PR https://github.com/ansible/galaxy/issues/703 from 3 weeks ago be causing such behavior?

**Comment by chouseknecht** [comment]
Your namespace name is now `xlab_si`.

**Comment by miha-plesko** [comment]
Thanks, I confirm it works, closing. Would prefer a more general solution (e.g. a button on the UI) than manually modifying the database, but as long as it works for me I'm fine😄
