### ISSUE TITLE
UI: Unable to remove namespace owner

### ISSUE THREAD

**Issue by kbugaienko** [ansible/galaxy#929]
##### SUMMARY
Unable to remove namespace owner by clicking on the corresponding button → "X". 

##### STEPS TO REPRODUCE

1. Open page `My Content`.
2. Click on `Edit properties`.
3. In section `Namespace Owners` select any galaxy user.
4. Click on the button `Save`.
5. Go back to the page `Edit properties`.
6. In section `Selected Galaxy Users` try to remove user.

![screen_shot_2018-07-19_at_17_13_27](https://user-images.githubusercontent.com/3986911/42954166-5a363af2-8b7c-11e8-9104-906ee24ed854.jpg)

##### EXPECTED RESULTS
The user is successfully removed.

##### ACTUAL RESULTS
Selected user is not removed.

**Comment by chouseknecht** [comment]
I think this is fixed already by #847

**Comment by chouseknecht** [comment]
@kbugaienko can you try this in [QA](https://galaxy-qa.ansible.com), and verify that is fixed. Thanks!

**Comment by kbugaienko** [comment]
@chouseknecht  I confirm that the issue is fixed in QA.

**Comment by chouseknecht** [comment]
@kbugaienko 

Awesome! Thank you for the feedback, and for your help. Really appreciate it!
