### ISSUE TITLE
Role name for geerlingguy.packer-rhel is incorrect

### ISSUE THREAD

**Issue by geerlingguy** [ansible/galaxy#941]
##### SUMMARY

The `geerlingguy.packer-rhel` role is incorrectly named when using the `ansible-galaxy` command line too. It should be `packer-rhel` but after the transition to the new version of galaxy it is showing as `packer_rhel`.

##### STEPS TO REPRODUCE

```
ansible-galaxy install geerlingguy.packer-rhel
```

##### EXPECTED RESULTS

The https://galaxy.ansible.com/geerlingguy/packer-rhel role should be installed.

##### ACTUAL RESULTS

```
- downloading role 'packer-rhel', owned by geerlingguy
[WARNING]: - geerlingguy.packer-rhel was NOT installed successfully: - sorry,
geerlingguy.packer-rhel was not found on https://galaxy.ansible.com.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**Comment by chouseknecht** [comment]
@geerlingguy 

Fixed. Meant to get to this sooner.
