### ISSUE TITLE
Roles with `ansible-` prefix changed names

### ISSUE THREAD

**Issue by triplepoint** [ansible/galaxy#942]
##### SUMMARY
All of my roles have `ansible-` prefixes in their Github repo names.  Previously, these roles had that prefix removed when publishing to Galaxy.  Two of my roles no longer function this way, and no amount of deleting and reimporting will get Galaxy to recognize their original names.  This is causing issues with playbooks that previously imported the roles under their old names.
- https://galaxy.ansible.com/triplepoint/ansible_dnsmasq
- https://galaxy.ansible.com/triplepoint/ansible_unifi

Reading up it seems multiple people have had this issue, and it was an ETL issue around recent galaxy.ansible.com service maintenance.

##### STEPS TO REPRODUCE
Looking at the URLs above, it's clear the "ansible-" prefix is not being stripped.  For instance, the `installation` field for one reads `ansible-galaxy install triplepoint.ansible_dnsmasq`, where it previously was `ansible-galaxy install triplepoint.dnsmasq`.

##### EXPECTED RESULTS
See above.

##### ACTUAL RESULTS
See above.

**Comment by chouseknecht** [comment]
Galaxy no longer manipulates the repository name. You can set the value of *role_name* in `meta/main.yml` as described under [Role Name in the Galaxy docs](https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names)
