### ISSUE TITLE
Ansible 3.0.3 install guide

### ISSUE THREAD

**Issue by majed-elbour** [ansible/galaxy#951]
Hello,

When could we have the new install guide ?

Thank you 
Majed

**Comment by chouseknecht** [comment]
You can follow the [CONTRIBUTING guide](https://github.com/ansible/galaxy/blob/devel/CONTRIBUTING.md) to standup a local Galaxy instance. There's no immediate plan to update the old installer

**Comment by majed-elbour** [comment]
@chouseknecht  thank you !
