### ISSUE TITLE
ansible-galaxy import IGNORES --role-name 

### ISSUE THREAD

**Issue by vbotka** [ansible/galaxy#973]
##### SUMMARY

ansible-galaxy import completed, but requested --role-name **freebsd-ssmtp** was ignored (name="**ansible_freebsd_ssmtp**")

> ansible-galaxy import --role-name freebsd-ssmtp  vbotka ansible-freebsd-ssmtp
Successfully submitted import request 266091
INFO Starting import: task_id=266091, repository=vbotka/ansible-freebsd-ssmtp
INFO Content search - Looking for file "apb.yml"
INFO Content search - Looking for top level role metadata file
INFO [role] Linting...
INFO [role] Linting OK.
INFO [role] Created new Content instance: id=27864, content_type="role", name="ansible_freebsd_ssmtp"
INFO [role] Adding role metadata tags
INFO [role] Adding role platforms
INFO Updating repository versions...
Import completed

##### STEPS TO REPRODUCE

Run the command from SUMMARY.

##### EXPECTED RESULTS

I expected that the role would be named as requested in the parameter --role-name freebsd-ssmtp

##### ACTUAL RESULTS

The roles is named name="ansible_freebsd_ssmtp"

**Comment by chouseknecht** [comment]
Not sure the state of the `--role-name` parameter. Will take a look today. We may actually need to remove that parameter, as we've enabled the `role_name` setting in `meta/main.yml` as the preferred way of setting the role name. See [Role Names](https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names) for more details.

**Comment by vbotka** [comment]
Meta role_name works exactly as described in the doc. Thank you very much!

**Comment by chouseknecht** [comment]
Assuming we can close this, since `role_name` in `meta/main.yml` is working.
