### ISSUE TITLE
Role names do not allow "-" in names

### ISSUE THREAD

**Issue by tschifftner** [ansible/galaxy#974]
The role "munin-node" already existed for a long time. Today its name was changed even though the meta role_name is set:

> Tags must container lowercase letters and digits only

This is really annoying as other roles start to fail because the role cannot be found anymore. 

> https://github.com/tschifftner/ansible-role-munin-node

**Comment by chouseknecht** [comment]
I'm guessing it was deleted and reimported, in which it's considered a new role. Starting in v3.0 of Galaxy we're enforcing some standards/rules for names. See [Role Names](https://galaxy.ansible.com/docs/contributing/creating_role.html#id5) for more details.

The reason for the rules is that we can combine multiple Ansible content types (modules, plugins. roles, etc.) into a single repository. To do that, names have to conform to Python naming conventions.
