### ISSUE TITLE
No blank lines in defaults/main.yml allowed

### ISSUE THREAD

**Issue by tschifftner** [ansible/galaxy#975]
During importing roles to ansible galaxy:

> INFO [role] Linting...
> ERROR [role] ./defaults/main.yml:121:1: [error] too many blank lines (1 > 0) (empty-lines)
> ERROR Lint failed

Role: tschifftner.munin_node

**Comment by chouseknecht** [comment]
Yep. It's a linting error. Remove the extra lines, and the role will import.

**Comment by tschifftner** [comment]
There are no blank lines allowed? How about readability?
