### ISSUE TITLE
Add a new namespace for my org

### ISSUE THREAD

**Issue by caphrim007** [ansible/galaxy#976]
Hello,

Today, I have 2 namespaces in my galaxy account and would like to add one more namespace to the account.

the namespace i would like to add is `f5networks` and it should be associated with the https://github.com/F5Networks organization on Github.

Thanks!

**Comment by chouseknecht** [comment]
`F5Networks` namespace created, with `caphrim007` as an owner. From My Content, you can add more owners, GitHub namespaces, and GitHub repositories.

**Comment by caphrim007** [comment]
works! thanks @chouseknecht !
