### ISSUE TITLE
Improve Search and My Imports

### ISSUE THREAD

**Issue by Voronenko** [ansible/galaxy#978]
### Use Case
As a user I want to be able to find role.
At a moment, if I saying, know portion or whole role name, but do not recall author - no option
to find role by free search from
https://galaxy.ansible.com/search

Also, on My Imports -  previously I had a chance to filter my roles by name.
No I need:  
a) 10 secs to switch and apply filter by organization
b) for every attempt to filter smth - spend 10 secs on 
      switch to repository name ->  put search fragment  -> get result filtered -> detect what I need to change to find what I want -> clear search filter by click -> repeat procedure

Why in "Content" we have nice in place filtering search, and in My Imports so complex sequence?

c) Again my imports - in current implementation there is no easy way to see that role has import issues.
This is generally must have pre-defined search on that section.

That list can be, basically, continued somewhere to letter w.

Whatever goal was set for galaxy website redesign - usability has degraded a lot.

### Proposed Solution

Galaxy website should _help_ to do common tasks both for role authors and consumers, and do not force them to spend enormous amount of time on most often tasks.

**Comment by chouseknecht** [comment]
@Voronenko 

Thanks for the feedback!

I think what you're asking for on the Search page, is the ability to search by Role Name. That should be easy enough to add.

On My Content, the filter automatically filters for your personal namespace, which may not be helpful when you are a part of multiple namespaces or organizations.

The first thing we should do is see if we can make clearing the filter faster. Right now, when you clear the filter, it takes several seconds to refresh the list of imports.

On the old My Imports (v2.4), imports were filtered by 'owner'. This provided a view of imports across organizations. The user did not have to think about 'Namespaces'. In the current implementation, we're seeding the filter with *namespace=owner*, and providing of view of imports for a single organization.

The concept of owner is different now. However, a fix might be to get the set of organizations for which the user is an owner, and seed the filter with all of the organizations. We'll need to change the backend view to support filtering by multiple namespaces. Right now, if you attempt to filter by multiple namespaces, it applies an 'and' condition, and returns 0 results.

**Comment by newswangerd** [comment]
HI @Voronenko 

We added the ability to filter and items on the My Content page in #928. That patch should be live now. I wanted to add the ability to filter repositories by their import status (see #933), but our current database schema doesn't allow for us to structure queries that way.

I think you're probably right. We have a long way to go to make the search work better.

**Comment by Voronenko** [comment]
Thank you very much!  Side question - when role reports linter errors - can you advise what linter command is used to check?

**Comment by newswangerd** [comment]
Closing this issue as it is being tracked in #1024 #928 and #933.

@Voronenko sorry I didn't see your question until just now. I'm not sure which linter command we use. @cutwater might be able to help.
