### ISSUE TITLE
500 Internal Server Error when adding content after organization name change

### ISSUE THREAD

**Issue by berkas1** [ansible/galaxy#983]
##### SUMMARY
When I try to "Add Content" (import roles at galaxy.ansible.com) for organisation thats' name has been changed, I get this error: 
`Error! Query user failed: (Http failure response for https://galaxy.ansible.com/api/v1/providers/sources/github/vaizard/: 500 Internal Server Error)`

![screen shot 2018-07-30 at 16 35 16](https://user-images.githubusercontent.com/614935/43403903-9290f980-9416-11e8-939e-5e05aa5075ec.png)

Change of name was from "Vaizard" to "vaizard". Both were added as namespaces.

##### STEPS TO REPRODUCE
Import roles from Github organization public repository -> rename the organization at Github -> add the renamed version as new namespace -> import any role (won't work from any namespace).

##### ACTUAL RESULTS
Error 500 is thrown.

**Comment by chouseknecht** [comment]
@berkas1 

Removed the 'Vaizard' provider namespace from the Galaxy `Vaizard` namespace. I think that might fix the error you're seeing. Please try to add repos again.

**Comment by berkas1** [comment]
Thank you very much, it helped and everything works as designed.
